add description of filter tags env variables
DataDog/documentation pull request #10006
Opened 2021-03-11 19:03 UTC by nicoledanuwidjaja

Add `DD_APM_FILTER_TAGS_REQUIRE` and `DD_APM_FILTER_TAGS_REJECT` to apm docs

2021-03-11 19:16 UTC, kayayarai requested changes
Slight wording revision for clarity.

2021-03-11 19:16 UTC, kayayarai commented on content/en/agent/docker/apm.md
> +| `DD_APM_FILTER_TAGS_REJECT`      | Defines rejected tags that traces must not have and are dropped by the Agent.
```suggestion
| `DD_APM_FILTER_TAGS_REJECT`      | Defines rejection tags. The Agent drops traces that have these tags.       |
```

2021-03-12 08:29 UTC, gbbr approved these changes

2021-03-15 15:18 UTC, kayayarai approved these changes

2021-03-15 15:18 UTC, merged