Adding docs for the new restrict access to Dashboards and Monitors functionality
DataDog/documentation pull request #10007
Opened 2021-03-11 23:56 UTC by apigirl

### What does this PR do?
Adding docs for the new restrict access to Dashboards and Monitors functionality

- https://docs-staging.datadoghq.com/kaylyn/restrict-monitor/account_management/rbac/#restrict-access-to-dashboards-and-monitors
- https://docs-staging.datadoghq.com/kaylyn/restrict-monitor/dashboards/#restrict-access
- https://docs-staging.datadoghq.com/kaylyn/restrict-monitor/getting_started/application/monitors/#restrict-access

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-03-15 16:15 UTC, kayayarai commented
This looks fine except for the empty `static/images/account_management/saml/google_idp_tile_sml.png` file included?

2021-03-16 19:17 UTC, cswatt requested changes
small edits

2021-03-16 19:17 UTC, cswatt commented on content/en/account_management/rbac/_index.md
> +## Restrict access to Dashboards and Monitors
```suggestion
## Restrict access to dashboards and monitors
```

2021-03-16 19:17 UTC, cswatt commented on content/en/account_management/rbac/_index.md
> +Once you have RBAC roles set up, you can restrict access to Dashboards and Monitors by user role. For more information, see the [Dashboard permissions docs][8], and the [Monitors permissions docs][9]
```suggestion
Once you have RBAC roles set up, you can restrict access to dashboards and monitors by user role. For more information, see the [Dashboard Permissions docs][8] and the [Monitors Permissions docs][9].
```

2021-04-23 14:25 UTC, kayayarai approved these changes

2021-04-23 14:26 UTC, merged