adding a new troubleshooting issue for SNMP
DataDog/documentation pull request #10060
Opened 2021-03-18 19:46 UTC by apigirl

### What does this PR do?
Adds a new troubleshooting issue for SNMP

### Motivation

https://docs-staging.datadoghq.com/kaylyn/snmp-faq/network_monitoring/devices/troubleshooting/#what-do-i-do-if-datadog-supports-a-vendor-or-device-type-but-my-specific-model-isn’t-supported

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-03-18 21:30 UTC, ruthnaebeck requested changes

2021-03-18 21:30 UTC, ruthnaebeck commented on content/en/network_monitoring/devices/troubleshooting.md
> +**Note**: If you do not know the `sysobjectid` of your device, first try googling for it, or run a `snmpwalk` on a host that can reach out to your device. Use the output to list the profile to match
```suggestion
**Note**: If you do not know the `sysobjectid` of your device, try doing an Internet search or run a `snmpwalk` on a host that can reach out to your device. Use the output to list the profile to match against. 
```

2021-04-23 14:21 UTC, kayayarai requested changes

2021-04-23 14:21 UTC, kayayarai commented on content/en/network_monitoring/devices/troubleshooting.md
> +2. Profiles can be extended to support additional `sysobjectid`’s
```suggestion
2. Profiles can be extended to support additional `sysobjectid` values. 
```

2021-04-23 14:21 UTC, kayayarai commented on content/en/network_monitoring/devices/troubleshooting.md
> +2. Profiles can be extended to support additional `sysobjectid`’s
This shouldn't be an ordered list -- we don't expect people to do both these things, right? How about: "Contact support to request support for your model. Alternatively, extend the profile to supports your sysobjectid value. For example, to monitor another type of Cisco CSR, modify the ISR profile to list ..." Also. Where do they do this modification? In a file (which one)? On the command line?

2021-04-23 17:50 UTC, kayayarai approved these changes

2021-04-30 15:44 UTC, merged