Migration of logs RBAC permissions
DataDog/documentation pull request #10114
Opened 2021-03-24 20:02 UTC by sarina-dd

### What does this PR do?

- Moves the logs RBAC permissions section in the account management RBAC permissions docs into its own guide.
- Updates the partial so we link to the new guide url.
- Adds further reading link.

### Motivation
The RBAC permissions page is now automatically generated for multiple products, and were creating individual guides for each section that will be linked to as content keeps growing.

### Preview
https://docs-staging.datadoghq.com/sarina/logs-rbac-reorg/logs/guide/
https://docs-staging.datadoghq.com/sarina/logs-rbac-reorg/logs/guide/logs-rbac-permissions
https://docs-staging.datadoghq.com/sarina/logs-rbac-reorg/account_management/rbac/permissions

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-03-25 17:39 UTC, sarina-dd commented
@bgdeutsch Hey there! Was able to update the URL for the logs RBAC permissions docs and it looks like the preview is working fine. Can you review whenever you get a chance? Thanks in advance for helping us with this! 😸

2021-03-29 20:39 UTC, kayayarai requested changes

2021-03-29 20:39 UTC, kayayarai commented on content/en/logs/guide/logs-rbac-permissions.md
> +To scope this permission to a subset of indexes, first remove the `logs_read_index_data` and `logs_modify_indexes` permissions on the role. Then
Should there be a colon after "Then", like it's introducing the tabs? or did this sentence get chopped off?

2021-03-29 20:39 UTC, kayayarai commented on content/en/logs/guide/logs-rbac-permissions.md
> +This permission is global, and grants access to the livetail irregardless of [Log Read Index Data](#logs-read-index-data) permission.
```suggestion
This permission is global, and grants access to the livetail regardless of [Log Read Index Data](#logs-read-index-data) permission.
```

2021-03-29 22:21 UTC, kayayarai approved these changes

2021-03-30 21:19 UTC, bgdeutsch reviewed
Looks good to me!   Just one thing, the legacy logs permissions `href` attributes are hard-coded [here](https://github.com/DataDog/documentation/blob/master/layouts/partials/rbac-permissions-table.html#L71-L78), do we want to update these to point to the new logs rbac guide page as well?

2021-03-31 15:52 UTC, sarina-dd commented on layouts/partials/rbac-permissions-table.html
> +          <a href="/logs/guide/logs-rbac-permissions/#logs_live_tail"><code>logs_read_index_data</code></a>
```suggestion
          <a href="/logs/guide/logs-rbac-permissions/#logs_read_index_data"><code>logs_read_index_data</code></a>
```

2021-03-31 15:53 UTC, sarina-dd commented on layouts/partials/rbac-permissions-table.html
> +          <a href="/logs/guide/logs-rbac-permissions/#logs_live_tail"><code>logs_read_index_data</code></a>
Looks like this was previously incorrect; updating so it redirects to the correct location!

2021-03-31 15:53 UTC, sarina-dd commented
@kayayarai Pushed the final commit 😸  Once the build is finished, we are good to merge!

2021-03-31 17:17 UTC, merged