Security Monitoring Explorer
DataDog/documentation pull request #10127
Opened 2021-03-25 19:20 UTC by sarina-dd

### What does this PR do?

- Adds notes about projection, suppression list, and dashboards to security explorer docs
- Updates images as they're outdated

### Motivation
Jira request

### Preview
https://docs-staging.datadoghq.com/sarina/sec-mon-explorer/security_monitoring/explorer

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-03-25 22:08 UTC, ruthnaebeck requested changes
Also fix image as discussed

2021-03-25 22:08 UTC, ruthnaebeck commented on content/en/security_monitoring/explorer.md
> +To better understand activity, the Security Signal Panel summarizes tags and attributes from all logs that trigger a signal so you can quickly troubleshoot without having to pivot to Log Explorer. Fo
```suggestion
To better understand activity, the Security Signal Panel summarizes tags and attributes from all logs that trigger a signal so you can troubleshoot without having to pivot to Log Explorer. For example, you can determine at a glance the list of IPs attempting to log into a user account, or the AWS accounts and availability zones running the authentication service.
```

2021-03-29 18:47 UTC, sarina-dd commented
@ruthnaebeck Got the approval to merge 👍

2021-04-05 18:59 UTC, apigirl approved these changes

2021-04-05 19:59 UTC, merged