updates to the developers overview page
DataDog/documentation pull request #10347
Opened 2021-04-20 22:20 UTC by apigirl

### What does this PR do?
Adds a link and explanation of who might be using this page, and how they can use it.

2021-04-20 22:35 UTC, cswatt requested changes

2021-04-20 22:35 UTC, cswatt commented on content/en/developers/_index.md
> +The Developers section contains reference materials for developing on Datadog. You may want to develop on Datadog if there is data you want to see in the product that you are currently not seeing, or
```suggestion
The Developers section contains reference materials for developing on Datadog. You may want to develop on Datadog if there is data you want to see in the product that you are not seeing, or if you are a partner who wants to build on Datadog and contribute to the Datadog Marketplace or to Datadog's community integrations. For more information about becoming a Datadog partner, see the [Partner program page][1].
```

I'm feeling that "integrations extras" is an internal name and that normal people probably just think of them as "Datadog's community integrations"?

2021-04-20 22:35 UTC, cswatt commented on content/en/developers/_index.md
> +Developers have several choices for sending unsupported data to Datadog. The main considerations are effort (time to develop) and budget (cost of custom metrics). If you are a Partner developing on D
```suggestion
Developers have several choices for sending unsupported data to Datadog. The main considerations are effort (time to develop) and budget (cost of custom metrics). If you are a Partner developing on Datadog Marketplace or community integrations, jump straight to the [Marketplace][2] and [building an integration][3] docs. If you are trying to see data that Datadog doesn't support, start by deciding which method makes the most sense to start sending data:
```

2021-04-21 22:09 UTC, apigirl commented
closing this in favor of https://github.com/DataDog/documentation/pull/10366

2021-04-21 22:09 UTC, closed without merging