Add advanced openmetrics AD config
DataDog/documentation pull request #10350
Opened 2021-04-21 08:52 UTC by ahmed-mez

### What does this PR do?

Document how to add advanced `prometheusScrape` configurations in the agent.

### Preview

https://docs-staging.datadoghq.com/ahmed/prom-advanced-config/agent/kubernetes/prometheus/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-04-21 09:18 UTC, clamoriniere commented on content/en/agent/kubernetes/prometheus.md
> +- Datadog Agent v7 or v6.27+ (for Pod checks)
```suggestion
- Datadog Agent v7.27+ or v6.27+ (for Pod checks)
```

2021-04-21 16:04 UTC, jtappa requested changes

2021-04-21 16:04 UTC, jtappa commented on content/en/agent/kubernetes/prometheus.md
> +It is possible to define advanced Openmetrics check configuration or custom Autodiscovery rules other than native Prometheus annotations thanks the `additionalConfigs` configuration field in `values.
```suggestion
You can define advanced Openmetrics check configurations or custom Autodiscovery rules other than native Prometheus annotations with the `additionalConfigs` configuration field in `values.yaml`.
```

2021-04-21 16:04 UTC, jtappa commented on content/en/agent/kubernetes/prometheus.md
> +The autodiscovery configuration can be based on container names or kubernetes annotations or both. When both `kubernetes_container_names` and `kubernetes_annotations` are defined, it’s an AND (both r
```suggestion
The autodiscovery configuration can be based on container names or kubernetes annotations or both. When both `kubernetes_container_names` and `kubernetes_annotations` are defined, it uses AND logic (both rules must match).
```

2021-04-21 16:04 UTC, jtappa commented on content/en/agent/kubernetes/prometheus.md
> +**Note:** The default value of `kubernetes_annotations` in the Datadog Agent configuration is the following
```suggestion
**Note:** The default value of `kubernetes_annotations` in the Datadog Agent configuration is the following:
```

2021-04-21 16:04 UTC, jtappa commented on content/en/agent/kubernetes/prometheus.md
> +In this example we're defining an advanced configuration targeting a container named `my-app` running in a pod labeled `app=my-app`. We're customising the Openmetrics check configuration as well, by
```suggestion
In this example we're defining an advanced configuration targeting a container named `my-app` running in a pod labeled `app=my-app`. We're customizing the Openmetrics check configuration as well, by enabling the `send_distribution_buckets` option and defining a custom timeout of 5 seconds.
```

2021-04-23 22:35 UTC, apigirl approved these changes

2021-04-23 22:36 UTC, merged