Cloud service autodetection feature documentation
DataDog/documentation pull request #10394
Opened 2021-04-23 18:44 UTC by kassenq

### What does this PR do?
Adds documentation to the NPM page under "Queries" that informs readers on how to make queries for seeing traffic to AWS cloud services

### Motivation
Cloud service autodetection is a new feature in NPM that we'd like to include in the documentation.

### Preview
https://docs-staging.datadoghq.com/npm-cloud-service-autodetection/network_monitoring/performance/network_page/

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-04-23 19:00 UTC, shlomoartzi commented on content/en/network_monitoring/performance/network_page.md
> +- To view integration metrics for a service: in the Network Page, click on a row in the [dependency table](#table). In the opened side panel, click *Integration Metrics*.
the last point on integration metrics can focus more on value - e.g. use the integration metrics tab to analyze the performance of the cloud service and distinguish b/w a client-side and cloud provider-side issue

2021-04-26 18:37 UTC, kayayarai requested changes
Thank you for this PR! Some minor style edits for you.

2021-04-26 18:37 UTC, kayayarai commented on content/en/network_monitoring/performance/network_page.md
> +Filtering by specific third-party services such as S3, RDS, Kinesis, and ELB can help pinpoint latency, assess database performance, and visualize your network more completely. For instance, you can
```suggestion
By filtering on third-party services such as S3, RDS, Kinesis, and ELB, you can pinpoint latency, assess database performance, and visualize your network more completely. For instance, you can filter a search query by service, view the service in the Network Map, and trace communication on that node to see affected services.
```

2021-04-26 18:37 UTC, kayayarai commented on content/en/network_monitoring/performance/network_page.md
> +- To filter a query: in search bar(s), enter tags such as `service:s3`, `service:kinesis`, and `service:elb`. For a number of services, you can break down latency and retransmits further by using mor
```suggestion
- **To filter a query**: In a search bar, enter tags such as `service:s3`, `service:kinesis`, and `service:elb`. For some services, you can break down latency and retransmits further by using more out-of-the-box tags like `s3_bucket` and `rds_instance_type`.
```

2021-04-26 18:37 UTC, kayayarai commented on content/en/network_monitoring/performance/network_page.md
> +- To visualize specific managed services: in the [Network Map][2], click the dropdown next to *View* and type or select desired tags. In the map, click a particular node to view troubleshooting optio
```suggestion
- **To visualize specific managed services**: In the [Network Map][2], click the dropdown next to *View* and type or select desired tags. In the map, click a node to view troubleshooting options.
```

2021-04-26 18:37 UTC, kayayarai commented on content/en/network_monitoring/performance/network_page.md
> +- To view integration metrics for a service: in the Network Page, click on a row in the [dependency table](#table). In the opened side panel, use the *Integration Metrics* tab to analyze the performa
```suggestion
- **To view integration metrics for a service**: In the Network Page, click a row in the [dependency table](#table). In the opened side panel, use the *Integration Metrics* tab to analyze the performance of cloud services and distinguish between a client-side and cloud provider issue.
```

2021-04-26 18:37 UTC, kayayarai commented on content/en/network_monitoring/performance/network_page.md
> +To monitor other endpoints where an Agent cannot be installed (such as public APIs), group the destination in the Network Overview by  the [`domain` tag](#dns-resolution).
```suggestion
To monitor other endpoints where an Agent cannot be installed (such as public APIs), group the destination in the Network Overview by the [`domain` tag](#dns-resolution).
```

2021-04-26 21:37 UTC, kayayarai approved these changes

2021-04-26 22:02 UTC, shlomoartzi approved these changes

2021-04-26 22:04 UTC, merged