Add Role Permissions synonyms
DataDog/documentation pull request #10508
Opened 2021-05-06 16:32 UTC by sarina-dd

### What does this PR do?
Add Role Permissions synonyms to the Algolia config to populate Datadog Role Permissions docs.

### Motivation
Searching `Permissions` didn't formerly populate `Datadog Role Permissions` docs within search.

### Preview
https://docs-staging.datadoghq.com/sarina/permissions-algolia/

### Additional Notes
Search for `Permissions` in both the docs homepage and in a few subsequent pages to test to ensure `Datadog Role Permissions` populates. Ran locally and this fix seemed to do the trick.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-05-06 19:46 UTC, sarina-dd commented
It looks like this is not working in the latest preview, back to WIP.

2021-05-07 18:24 UTC, kayayarai requested changes

2021-05-07 18:24 UTC, kayayarai commented on local/etc/algolia/docs_datadoghq.json
>              ["RUM", "rum", "real user monitoring"]
```suggestion
            ["RUM", "rum", "real user monitoring"],
```

2021-05-07 18:24 UTC, kayayarai commented on local/etc/algolia/docs_datadoghq_preview.json
>              ["RUM", "rum", "real user monitoring"]
```suggestion
            ["RUM", "rum", "real user monitoring"],
```

2021-05-07 18:28 UTC, merged