Verify some images w/ Docker Content Trust
DataDog/documentation pull request #10516
Opened 2021-05-07 02:38 UTC by trishankatdatadog

### What does this PR do?

Verify the core agent, dogstatds, and cluster agent on Docker Hub with Docker Content Trust (DCT).

### Motivation

Previously, the images were verified using DCT, but it appears that new documentation overhaul removed this.

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

N/A

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-05-07 09:46 UTC, olivielpeau commented
(requesting for a review from @DataDog/container-integrations since they own the docker images)

2021-05-07 10:40 UTC, clamoriniere approved these changes

2021-05-07 18:07 UTC, sarina-dd approved these changes

2021-05-07 18:20 UTC, trishankatdatadog commented
Should I also update a few `docker run` commands?

2021-05-07 18:28 UTC, sarina-dd commented
@trishankatdatadog I don't think it hurts to add. I know we have it mentioned in a few other locations.

2021-05-07 18:30 UTC, trishankatdatadog commented
@sarina-dd I'll try to find everything I can

2021-05-12 15:39 UTC, sarina-dd reviewed
LGTM for docs 👍  @clamoriniere Can you take another look and verify the newly added content?

2021-05-12 17:35 UTC, clamoriniere commented
@trishankatdatadog 
It was on purpose that we move the default image to the `gcr.io` to avoid customer being impacted any dockerhub rate limit issue.
But unfortunately, gcr.io doesn't provide content trust verification.
So I'm not sure we really want to change the default image.

2021-05-12 17:43 UTC, clamoriniere requested changes
Please wait validation from product

2021-05-12 23:34 UTC, trishankatdatadog commented
Closing because we are moving away from Docker Hub by default and, hence, Docker Content Trust. Will work with product to design and implement a registry-agnostic solution.

2021-05-12 23:34 UTC, closed without merging