Adding guide about Synthetics usage monitoring
DataDog/documentation pull request #10766
Opened 2021-06-07 17:39 UTC by MargotLepizzera

### What does this PR do?

This PR adds a guide about Synthetics usage monitoring.

### Motivation

Release of the new metrics

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-06-07 17:52 UTC, MargotLepizzera commented on content/en/synthetics/guide/monitor-usage.md
> +Synthetic tests come with [estimated usage metrics][1] allowing you to keep track of your usage. These metrics notably enable you to:
```suggestion
Synthetic tests come with [estimated usage metrics][1] that allows you to keep track of your usage. These metrics notably enable you to:
```

2021-06-07 17:52 UTC, MargotLepizzera commented on content/en/synthetics/guide/monitor-usage.md
> +You can graph and monitor these metrics against static thresholds as well as machine learning based algorithms like [anomaly detection][5] or [forecast][6] to ensure you do not get alerted for expect
```suggestion
You can graph and monitor these metrics against static thresholds as well as use machine learning based algorithms like [anomaly detection][5] or [forecast][6] to ensure you do not get alerted for expected usage growth.
```

2021-06-07 18:18 UTC, kayayarai requested changes

2021-06-07 18:18 UTC, kayayarai commented on content/en/synthetics/guide/monitor-usage.md
> +Synthetic tests come with [estimated usage metrics][1] that allows you to keep track of your usage. These metrics notably enable you to:
```suggestion
Synthetic tests come with [estimated usage metrics][1] that allow you to keep track of your usage. These metrics notably enable you to:
```

2021-06-07 18:18 UTC, kayayarai commented on content/en/synthetics/guide/monitor-usage.md
> +* Visualize which teams, applications, or services are contributing the most to your Synthetics usage and have the largest coverage
```suggestion
* Understand how your usage evolves over time.
* Visualize which teams, applications, or services are contributing the most to your Synthetics usage and have the largest coverage.
```

2021-06-07 18:18 UTC, kayayarai commented on content/en/synthetics/guide/monitor-usage.md
> +You can also scope or group these metrics by any tags associated with your test such as `team` or `application` for a higher level of refinement.
```suggestion
For a higher level of refinement, scope or group these metrics by tags associated with your test, such as `team` or `application`. 
```

2021-06-08 10:36 UTC, MargotLepizzera commented on content/en/synthetics/guide/monitor-usage.md
> +* [Single][2] and [Multistep API tests][3]: `sum:datadog.estimated_usage.synthetics.api_test_runs{*}.as_count()`
```suggestion
* [Single][2] and [Multistep API tests][3]: `sum:datadog.estimated_usage.synthetics.api_test_runs{*}.as_count().`
```

2021-06-08 10:36 UTC, MargotLepizzera commented on content/en/synthetics/guide/monitor-usage.md
> +* [Single][2] and [Multistep API tests][3]: `sum:datadog.estimated_usage.synthetics.api_test_runs{*}.as_count().`
```suggestion
* [Single][2] and [Multistep API tests][3]: `sum:datadog.estimated_usage.synthetics.api_test_runs{*}.as_count()`
```

2021-06-08 14:00 UTC, kayayarai approved these changes

2021-06-10 14:56 UTC, merged