Update summary.md
DataDog/documentation pull request #10850
Opened 2021-06-15 18:58 UTC by ijkaylin

Adding description of buttons on Metrics Summary

### What does this PR do?
To describe bulk tag configuration and bulk percentiles buttons on Metrics Summary

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-06-16 20:26 UTC, jtappa requested changes
Can you please add a shadow box around the two buttons in the first image? It's not immediately apparent that's what we're referencing since there's a lot of text in that image.

Thanks!

2021-06-17 19:51 UTC, ijkaylin commented
updated image with box

2021-06-17 21:00 UTC, jtappa requested changes

2021-06-17 21:00 UTC, jtappa commented on content/en/metrics/summary.md
> +* **Configure Tags**: Configure tags on multiple distribution metrics (Metrics without Limits* beta users will be able to use this functionality on counts,gauges,rates as well)
```suggestion
* **Configure Tags**: Configure tags on multiple distribution metrics (Metrics without Limits* beta users will be able to use this functionality on counts, gauges, and rates as well).
```

2021-06-17 21:00 UTC, jtappa commented on content/en/metrics/summary.md
> +* **Calculate Percentiles**: Add percentile aggregations to multiple distribution metrics
```suggestion
* **Calculate Percentiles**: Add percentile aggregations to multiple distribution metrics.
```

2021-06-28 18:45 UTC, jtappa approved these changes

2021-06-28 18:47 UTC, jtappa approved these changes

2021-06-28 18:47 UTC, merged