Adding a new library
DataDog/documentation pull request #10918
Opened 2021-06-23 16:46 UTC by apigirl

Adding a new library to the developer libraries page:

https://docs-staging.datadoghq.com/kaylyn/adding-finagle/developers/libraries/

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-06-23 17:29 UTC, jtappa approved these changes

2021-06-23 17:30 UTC, jtappa requested changes
actually, it looks like this table is alphabetized, maybe we should add Finagle in alphabetic order of the table?

2021-06-23 22:25 UTC, apigirl commented
hey, this is a good catch! for this library I would prefer to have it at the bottom just because it is not going to be used nearly as much as the other ones.

2021-06-28 18:48 UTC, jtappa approved these changes

2021-06-28 18:49 UTC, merged