Add a note regarding the Datadog Agent service account
DataDog/documentation pull request #10928
Opened 2021-06-24 13:56 UTC by julien-lebot

### What does this PR do?
This PR clarifies that the Datadog Agent service account should also be in the `Users` group.

### Motivation
A support case revealed that in some cases the Datadog Agent service account was not in the `Users` group, and it caused permission issues.

### Preview
https://docs-staging.datadoghq.com/julien.lebot/clarify_users_group/agent/faq/windows-agent-ddagent-user/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-06-24 18:13 UTC, ruthnaebeck requested changes

2021-06-24 18:13 UTC, ruthnaebeck commented on content/en/agent/faq/windows-agent-ddagent-user.md
> +**Note**: The installer doesn't add the account it creates to the `Users` groups by default. On most systems this is fine.
```suggestion
**Note**: The installer doesn't add the account it creates to the `Users` groups by default.
```

2021-06-24 18:13 UTC, ruthnaebeck commented on content/en/agent/faq/windows-agent-ddagent-user.md
> +If you encounter permission issues running the Datadog Agent service, make sure the account under which the service runs is in the `Users` group.
```suggestion
If you encounter permission issues running the Datadog Agent service, add the account the service runs on to the `Users` group.
```

2021-06-28 17:35 UTC, ruthnaebeck commented on content/en/agent/faq/windows-agent-ddagent-user.md
> +**Note**: The installer doesn't add the account it creates to the `Users` groups by default. On most systems this is fine.
@julien-lebot Suggestion updated

2021-06-29 17:20 UTC, ruthnaebeck approved these changes
👍  for docs. Ping when you are ready for merge.

2021-06-29 18:43 UTC, albertvaka approved these changes
LGTM

2021-06-29 19:03 UTC, merged