DOCS-1980 Add IM getting started
DataDog/documentation pull request #10936
Opened 2021-06-24 21:57 UTC by maycmlee

### What does this PR do?
Adding IM Getting Started

### Motivation
DOCS-1980

### Preview

https://docs-staging.datadoghq.com/may-lee/im-getting-started2/getting_started/incident_management

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-06-24 22:40 UTC, kayayarai commented
Oops! We remembered and then forgot we need to update the main sidebar nav. The change goes in the file `/config/_default/menus/menus.en.yaml` somewhere around line 337. Follow the pattern and update any weight values as needed.

2021-06-24 22:59 UTC, kayayarai requested changes
A few edits, plus add entry to main sidebar nav. 🎉

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +### Declaring an Incident
```suggestion
### Declaring an incident
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +For this guide, we are using the [Datadog Clipboard][2] to declare an incident.
```suggestion
This guide describes using the [Datadog Clipboard][2] to declare an incident.
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +### Resolution / Postmortem
```suggestion
### Resolution and postmortem
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/monitors/incident_management/_index.md
> +Work through an example workflow in our [Getting Started with Incident Management][12].
```suggestion
Work through an example workflow in the [Getting Started with Incident Management][12] guide.
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/monitors/incident_management/_index.md
>  [4]: https://docs.datadoghq.com/integrations/slack/?tab=slackapplicationus
```suggestion
[4]: /integrations/slack/
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/monitors/incident_management/_index.md
> +[11]: https://docs.datadoghq.com/integrations/webhooks/#sending-sms-through-twilio
```suggestion
[8]: /integrations/pagerduty/
[9]: /integrations/jira/
[10]: /integrations/webhooks/
[11]: /integrations/webhooks/#sending-sms-through-twilio
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +[7]:/incident_management/#status-levels
```suggestion
[7]: /monitors/incident_management/#status-levels
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +[1]:/integrations/slack/?tab=slackapplicationus#overview
```suggestion
[1]:/integrations/slack/
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +1. Open the Clipboard: **Ctrl**/**Cmd** + **Shift** + **K**
```suggestion
1. Open the Clipboard: **Ctrl**/**Cmd** + **Shift** + **K**.
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +3. Click **Save.**
```suggestion
3. Click **Save**.
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +7. Click **Generate Postmortem.**
```suggestion
7. Click **Generate Postmortem**.
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +9. Click **Generate.**
```suggestion
9. Click **Generate**.
```

2021-06-24 22:59 UTC, kayayarai commented on content/en/getting_started/incident_management/_index.md
> +To customize Incident Management, go to the [incident settings page][9]. From the Datadog menu on the left-hand side, go to **Monitors** > **Incidents** (if you get an Incident Management welcome scr
```suggestion
To customize Incident Management, go to the [incident settings page][9]. From the Datadog menu on the left-hand side, go to **Monitors** > **Incidents** (if you get an Incident Management welcome screen, click **Get Started**). Then on the top right corner, click **Settings**.
```

2021-06-25 13:56 UTC, maycmlee commented on content/en/getting_started/incident_management/_index.md
> +### Resolution / Postmortem
Should postmortem be capitalized?

2021-06-25 14:53 UTC, maycmlee commented on content/en/getting_started/incident_management/_index.md
> +### Resolution / Postmortem
nevermind!

2021-06-25 18:48 UTC, kayayarai approved these changes

2021-06-25 19:21 UTC, apigirl approved these changes

2021-06-25 19:26 UTC, merged