[ci-app] Javascript – Add Known Limitations and Best Practices
DataDog/documentation pull request #10942
Opened 2021-06-25 08:31 UTC by juan-fernandez

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-06-28 14:53 UTC, kayayarai requested changes
Some grammar and style edits

2021-06-28 14:53 UTC, kayayarai commented on content/en/continuous_integration/setup_tests/javascript.md
> +  * Mocha >=9.0.0 has [**partial support**](#known-limitations).
```suggestion
  * Mocha >=9.0.0 has [partial support](#known-limitations).
```

2021-06-28 14:53 UTC, kayayarai commented on content/en/continuous_integration/setup_tests/javascript.md
> +[Mocha >=9.0.0][8] has gone ESM-first to load test files. That means that if ES modules are used (for example, by defining test files with the .mjs extension), **the instrumentation will be limited**
```suggestion
[Mocha >=9.0.0][8] uses an ESM-first approach to load test files. That means that if ES modules are used (for example, by defining test files with the `.mjs` extension), _the instrumentation will be limited_. Tests are detected, but there isn't visibility into your test. For more information about ES modules, see [the NodeJS documentation][9].
```

2021-06-28 14:53 UTC, kayayarai commented on content/en/continuous_integration/setup_tests/javascript.md
> +### ES Modules
```suggestion
### ES modules
```

2021-06-28 14:53 UTC, kayayarai commented on content/en/continuous_integration/setup_tests/javascript.md
> +The Javascript Tracer does not support browsers. This means that if you're running browser tests with `mocha` or `jest`, there won't be visibility within the test itself.
```suggestion
The JavaScript tracer does not support browsers, so if you run browser tests with `mocha` or `jest`, there isn't visibility within the test itself.
```

2021-06-28 14:53 UTC, kayayarai commented on content/en/continuous_integration/setup_tests/javascript.md
> +The following practices allow to take full advantage of the testing framework and CI Visibility.
```suggestion
Follow these practices to take full advantage of the testing framework and CI Visibility.
```

2021-06-28 14:53 UTC, kayayarai commented on content/en/continuous_integration/setup_tests/javascript.md
> +Whenever possible, leverage the tools the testing frameworks provide for parameterized tests. For example, for `jest`:
```suggestion
Whenever possible, leverage the tools that testing frameworks provide for parameterized tests. For example, for `jest`:
```

2021-06-28 14:53 UTC, kayayarai commented on content/en/continuous_integration/setup_tests/javascript.md
> +And use instead the supported [`test.each`][10] instead:
```suggestion
And use instead the supported [`test.each`][10] instead:
```
```suggestion
And use [`test.each`][10] instead:
```

2021-06-28 14:53 UTC, kayayarai commented on content/en/continuous_integration/setup_tests/javascript.md
> +For `mocha`, [`mocha-each`][11] is supported:
```suggestion
For `mocha`, use [`mocha-each`][11]:
```

2021-06-28 14:53 UTC, kayayarai commented on content/en/continuous_integration/setup_tests/javascript.md
> +By using this approach, both the testing framework and CI Visibility will be able to tell your tests apart.
```suggestion
When you use this approach, both the testing framework and CI Visibility can tell your tests apart.
```

2021-06-29 06:50 UTC, juan-fernandez commented
thanks for the great feedback @kayayarai ! I applied all of it

2021-06-29 14:35 UTC, kayayarai approved these changes

2021-06-29 14:35 UTC, merged