Getting Started with Synthetic Monitoring > Multistep API Tests
DataDog/documentation pull request #10946
Opened 2021-06-25 18:52 UTC by alai97

Adding a section on multistep API tests.

### What does this PR do?

Revamp the Getting Started with API Tests page with updated content about multistep API tests.

### Motivation

DOCS-1979

### Preview

https://docs-staging.datadoghq.com/alai97/synthetics-api-tests-getting-started/getting_started/synthetics/api_test

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-06-25 22:00 UTC, kayayarai requested changes
Looks good! Just two things

2021-06-25 22:27 UTC, sarina-dd reviewed
Small suggestions 😸

2021-06-25 22:27 UTC, sarina-dd commented on content/en/getting_started/synthetics/api_test.md
> +Multistep API tests also **monitor your API endpoints** and **alert you** when they become too slow or fail. These tests verify that your services are responding to HTTP requests and meeting any cond
```suggestion
Multistep API tests **monitor your API endpoints** and **alert you** when they become too slow or fail. These tests verify that your services are responding to HTTP requests and meeting any conditions you define, such as **response time**, **HTTP status code**, and **header or body contents**. 
```

2021-06-25 22:27 UTC, sarina-dd commented on content/en/getting_started/synthetics/api_test.md
> +    - You can select **Advanced Options** to add request options, request body, certificates, and proxies.
```suggestion
    -  Select **Advanced Options** to add request options, request body, certificates, and proxies.
```

2021-06-25 22:27 UTC, sarina-dd commented on content/en/getting_started/synthetics/api_test.md
> +    - You can optionally add new assertions, enable execution parameters, and extract variables from the response content.
```suggestion
    - Optionally, add new assertions, enable execution parameters, and extract variables from the response content.
```

2021-06-25 22:27 UTC, sarina-dd commented on content/en/getting_started/synthetics/api_test.md
> +When you're ready to run your test, click **Save Test**.
```suggestion
When you're ready to create your test, click **Save Test**. 
```

2021-06-25 22:27 UTC, sarina-dd commented on content/en/getting_started/synthetics/api_test.md
> +With Datadog's [APM integration with Synthetic Monitoring][5], you can access the root cause of a failed test run by looking at the trace generated from the test run in the **Traces** tab.
```suggestion
With Datadog's [APM integration with Synthetic Monitoring][5], access the root cause of a failed test run by looking at the trace generated from the test run in the **Traces** tab.
```

2021-06-25 22:27 UTC, alai97 commented on content/en/getting_started/synthetics/api_test.md
> +Multistep API tests also **monitor your API endpoints** and **alert you** when they become too slow or fail. These tests verify that your services are responding to HTTP requests and meeting any cond
```suggestion
Multistep API tests also **monitor your API endpoints** and **alert you** when they become too slow or fail. These tests verify that your services are executing HTTP requests and meeting any conditions you define, such as **response time**, **HTTP status code**, and **header or body contents**. 
```

2021-06-25 22:27 UTC, sarina-dd commented on content/en/getting_started/synthetics/api_test.md
> +Multistep API tests also **monitor your API endpoints** and **alert you** when they become too slow or fail. These tests verify that your services are responding to HTTP requests and meeting any cond
+1

2021-06-25 22:34 UTC, sarina-dd commented
@alai97 A quick note on this page: it looks like quite a few of the screenshots are outdated. The one in configure a request section should be updated to reflect multiple request types now (SSL, TCP, DNS, etc.) The assertions image too as the right panel has changed (it no longer shows the request preview / has a few options for response, docs, and variables that are nifty!)

2021-06-25 22:44 UTC, alai97 commented on content/en/getting_started/synthetics/api_test.md
> +Multistep API tests also **monitor your API endpoints** and **alert you** when they become too slow or fail. These tests verify that your services are responding to HTTP requests and meeting any cond
How about this? @kayayarai @sarina-dd

2021-06-25 22:45 UTC, alai97 commented on content/en/getting_started/synthetics/api_test.md
> +Creating a multistep API test slightly differs from creating an API test. You can link HTTP requests and create variables from the request response data in **Define steps**.
Is "aPI" a typo here @kayayarai?

2021-06-25 22:46 UTC, kayayarai commented on content/en/getting_started/synthetics/api_test.md
> +Creating a multistep API test slightly differs from creating an API test. You can link HTTP requests and create variables from the request response data in **Define steps**.
Yes _shakes fist at wireless keyboard_

2021-06-25 22:48 UTC, kayayarai commented on content/en/getting_started/synthetics/api_test.md
> +Multistep API tests also **monitor your API endpoints** and **alert you** when they become too slow or fail. These tests verify that your services are responding to HTTP requests and meeting any cond
```suggestion
Multistep API tests chain multiple HTTP requests together, allowing you to configure API tests on complex backend systems. 
```
I think we could whittle it down to this ^

2021-06-25 22:52 UTC, alai97 commented on content/en/getting_started/synthetics/api_test.md
> +Multistep API tests also **monitor your API endpoints** and **alert you** when they become too slow or fail. These tests verify that your services are responding to HTTP requests and meeting any cond
yas

2021-06-28 15:11 UTC, kayayarai approved these changes

2021-06-28 21:12 UTC, sarina-dd approved these changes

2021-06-28 21:25 UTC, merged