Rewrite of logs pipelines page, edits to archives
DataDog/documentation pull request #10978
Opened 2021-06-29 23:23 UTC by sarina-dd

### What does this PR do?
- Rewrite and organization of the logs pipelines page
- Edits to the logs archives page

### Motivation
Giving the logs pages some TLC 💟 

### Preview
https://docs-staging.datadoghq.com/sarina/logs-audit-config/logs/log_configuration/archives
https://docs-staging.datadoghq.com/sarina/logs-audit-config/logs/log_configuration/pipelines

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-09 19:08 UTC, jtappa requested changes
just one small nit 😸

2021-07-09 19:08 UTC, jtappa commented on content/en/logs/log_configuration/pipelines.md
> +    **Note**: The pipeline filtering is applied before any of the pipeline's processors, hence you cannot filter on an attribute that is extracted in the pipeline itself.
```suggestion
    **Note**: The pipeline filtering is applied before any of the pipeline's processors. For this reason, you cannot filter on an attribute that is extracted in the pipeline itself.
```

2021-07-15 19:15 UTC, sarina-dd commented
@jtappa Ready for final review 👍

2021-07-15 20:29 UTC, jtappa approved these changes

2021-07-15 20:29 UTC, merged