Add instructions to enable the Allocation Profiler
DataDog/documentation pull request #11016
Opened 2021-07-06 08:50 UTC by luhenry

Because the allocation profiler can overwhelm the profiler in
allocation-heavy applications. To guarantee an optimal experience, we
want to make it opt-in.

We are adding a message in the web ui pointing to this section of the
documentation.

### What does this PR do?

Add documentation section on enabling the Allocation Profiler.

### Motivation

We are making the Allocation Profiler opt-in in the Java Profiler.

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-06 21:13 UTC, GaurabAryal commented
Looks good to me!

2021-07-06 21:26 UTC, GaurabAryal approved these changes

2021-07-06 21:29 UTC, dbenamydd reviewed
1. Can we make it easier to enable this functionality? Seems like we're asking users to jump through hoops for what is, conceptually, "ENABLE_ALLOCATION_PROFILING=1"
2. I wonder if this would be better on the setup page rather than troubleshooting. The pointer from the ui will help make it discoverable but folks who want to try using it in their initial setup will probably not see it here, will deploy everything, go to the ui, _then_ learn about it, and need to go back to early in the process. If we do want to keep it here, maybe put it at the top of the page since it'll (hopefully) be the most commonly used entry?

2021-07-06 21:29 UTC, dbenamydd commented on content/en/tracing/profiler/profiler_troubleshooting.md
> +The allocation profiler is turned off by default because it can overwhelm the profiler in allocation-heavy applications. To turn it back on, enable the following events in your `jfp` [override templa
Should this link to "creating and using a jfr template..."?

2021-07-06 21:41 UTC, cswatt requested changes

2021-07-06 21:41 UTC, cswatt commented on content/en/tracing/profiler/profiler_troubleshooting.md
> +## Enabling the Allocation Profiler
```suggestion
## Enabling the allocation profiler
```

2021-07-06 21:48 UTC, luhenry commented
@dbenamydd @GaurabAryal  let me update the doc beginning of my day tomorrow and do another round of reviews afterwards.

2021-07-08 08:12 UTC, luhenry commented
@dbenamydd @GaurabAryal I updated the documentation with pointers to `-Ddd.profiling.allocation.enabled=true` and `DD_PROFILING_ALLOCATION_ENABLED=true` (implemented in https://github.com/DataDog/dd-trace-java/pull/2890).

2021-07-08 14:37 UTC, cswatt approved these changes

2021-07-08 15:00 UTC, cswatt approved these changes

2021-07-08 15:00 UTC, merged