Sending events and logs to Datadog with Amazon EventBridge API Destinations
DataDog/documentation pull request #11029
Opened 2021-07-06 23:04 UTC by apigirl

## What does this PR do?
Adds a guide around the new(ish) Datadog support in Eventbridge destinations

https://docs-staging.datadoghq.com/kaylyn/eventbridge/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations/

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-08 16:18 UTC, jimmycaputo commented
Step 3 is a little confusing. This is only relevant if your rule is triggering when data is uploaded to S3, which is the example in the AWS post, but S3 is only one of many services that post events to EventBridge. Might be better to just combine 3 and 4 and say you'll see your logs or events show up in Datadog a few minutes after your rules with Datadog destinations trigger?

Also, should we add a link in the intro to the other EventBridge integration page and directs readers there if looking to push events to EventBridge:
https://docs.datadoghq.com/integrations/amazon_event_bridge/#overview

I could see someone finding this page and being confused about how to push events. Or vice versa if they go to the EventBridge integration page and are looking to send events to Datadog.

2021-07-09 22:13 UTC, apigirl commented
@jimmycaputo - thanks for the feedback! I've updated based on it. I did not remove the S3 example entirely, because I still think it's a really good example, but I did make it more clear that it was one way of many, with your suggested more clear links to how to send events from Datadog to EventBridge. I am also going to open up a separate PR to add a link from the EventBridge integration docs to this guide.

2021-07-12 15:44 UTC, jimmycaputo approved these changes
LGTM

2021-07-14 18:14 UTC, jtappa requested changes

2021-07-14 18:14 UTC, jtappa commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +    - Use API key Authorization, with `DD-API-KEY` as your key name and your [Datadog API key][3] as the value.
```suggestion
    - Use API key authorization, with `DD-API-KEY` as your key name and your [Datadog API key][3] as the value.
```

2021-07-14 18:14 UTC, jtappa commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +    - For your destination endpoint, input `https://http-intake.logs.datadoghq.com/v1/input` for logs or `https://api.datadoghq.com/api/v1/events` for events, and set `POST` as the HTTP method. For m
```suggestion
    - For your destination endpoint, use `https://http-intake.logs.datadoghq.com/v1/input` for logs or `https://api.datadoghq.com/api/v1/events` for events, and set `POST` as the HTTP method. For more information about the differences between logs and events, see the [logs section][6], and the [events section][7] of the [Categories of Data docs page][8].
```

2021-07-14 18:14 UTC, jtappa commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +3. Once you've set up the rule with Datadog as the destination, trigger an event by posting an event to EventBridge. For more information about pushing events to EventBridge from Datadog, see the [Ev
```suggestion
3. Once you've set up the rule with Datadog as the destination, trigger an event by posting an event to EventBridge. For more information about pushing events to EventBridge from Datadog, see the [EventBridge integration docs][1]. For example, to trigger a test event by [uploading the objects to an S3 bucket][10] in your account, use this AWS CloudShell command:
```

2021-07-14 18:14 UTC, jtappa commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +4. Once events and logs are sending, after about five minutes, you start seeing the data in the Datadog [logs console][11] or [events stream][12], depending on which endpoint you are sending them.
```suggestion
4. Once events and logs are sending, after about five minutes, the data is available in the Datadog [logs console][11] or [events stream][12], depending on which endpoint you are sending them to.
```

2021-07-14 19:13 UTC, jtappa approved these changes

2021-07-14 19:15 UTC, merged