Update graphing details for new metric dropdown
DataDog/documentation pull request #11061
Opened 2021-07-09 16:50 UTC by meghanlo

### What does this PR do?

Adding documentation for new metric dropdown with additional metric details/metadata

### Motivation

### Preview
https://docs-staging.datadoghq.com/meghan.lo/graphing-metric-details/dashboards/querying/#choose-the-metric-to-graph

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-09 19:16 UTC, ruthnaebeck requested changes

2021-07-09 19:16 UTC, ruthnaebeck commented on content/en/dashboards/querying/_index.md
> +Choose the metric to graph by searching or selecting it from the dropdown next to **Metric**. If you don't know which metric to use, the metric dropdown also provides additional information, includin
```suggestion
Choose the metric to graph by searching or selecting it from the dropdown next to **Metric**. If you don't know which metric to use, the metric dropdown provides additional information, including the `unit`, `type`, `interval`, `description`, `tags`, and number of `tag values`. 
```

2021-07-09 19:16 UTC, ruthnaebeck commented on content/en/dashboards/querying/_index.md
> +{{< img src="dashboards/querying/metric_dropdown.png" alt="Metric Selector Dropdown"  style="width:75%;" >}}
```suggestion
{{< img src="dashboards/querying/metric_dropdown.png" alt="Metric Selector Dropdown" responsive="true" style="width:75%;">}}
```

2021-07-09 19:16 UTC, ruthnaebeck commented on content/en/dashboards/querying/_index.md
> +If you want to explore your metrics further, start with the [Metrics Explorer][3] or a [notebook][4]. You can also see a list of metrics on the [Metrics Summary page][5].
```suggestion
Explore your metrics further with the [Metrics Explorer][3], a [Notebook][4], or see a list of metrics on the [Metrics Summary page][5].
```

2021-07-30 16:01 UTC, sarina-dd approved these changes

2021-07-30 16:01 UTC, merged