Add definition for root span
DataDog/documentation pull request #11086
Opened 2021-07-13 15:21 UTC by wantsui

### What does this PR do?

Explains what the root span of a trace is.

### Motivation

This definition is necessary to understand how to use other APM features.

### Preview

https://docs-staging.datadoghq.com/wantsui/rootspan-definition/tracing/visualization

### Additional Notes

Should be reviewed by @andrewardito

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-13 15:43 UTC, cswatt requested changes
small grammar/style stuff

2021-07-13 15:43 UTC, cswatt commented on content/en/tracing/visualization/_index.md
> +| [Root span](#root-span) | The first span generated by a request and, as a result, does not have a parent                      |
```suggestion
| [Root span](#root-span) | The first span generated by a request and, as a result, does not have a parent.                      |
```

2021-07-13 15:43 UTC, cswatt commented on content/en/tracing/visualization/_index.md
> +The very first span generated by a request and, as a result, does not have a parent. You can visualize this on the flamegraph by finding the span on the top of the flamegraph that initiates the reque
```suggestion
The root span is the very first span generated by a request and, as a result, does not have a parent. You can visualize this on the flamegraph by finding the span on the top of the flamegraph that initiates the request.
```

2021-07-20 16:04 UTC, wantsui commented
I'm going to close this PR for now since the definitions will be revisited at a later time.

2021-07-20 16:04 UTC, closed without merging