Update webhooks URLs for CI visibility integration with Gitlab
DataDog/documentation pull request #11114
Opened 2021-07-15 10:07 UTC by AdrianLC

### What does this PR do?
Update webhooks URLs for CI visibility integration with Gitlab

### Motivation
The current URLs are deprecated so this needs an update for users to adopt the new ones.

### Preview

https://docs-staging.datadoghq.com/adrian.lopezcalvo/ciapp-gitlab-webhooks-update-urls

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-15 10:28 UTC, fermayo approved these changes

2021-07-15 22:13 UTC, ruthnaebeck requested changes

2021-07-15 22:13 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/gitlab.md
> +* **URL**: `https://webhooks-http-intake.logs.datadoghq.com/v2/api/webhook/?dd-api-key=<API_KEY>` where `<API_KEY>` is one generated [here][5].
```suggestion
* **URL**: `https://webhooks-http-intake.logs.datadoghq.com/v2/api/webhook/?dd-api-key=<API_KEY>` where `<API_KEY>` is [your Datadog API key][5].
```

2021-07-16 17:46 UTC, apigirl approved these changes

2021-07-16 17:46 UTC, merged