Update GitLab instructions
DataDog/documentation pull request #11117
Opened 2021-07-15 18:13 UTC by fermayo

### What does this PR do?

Clarifies where can the integration be enabled on GitLab depending on the version

### Motivation

Due to a bug present in GitLab < 14.1, the integration cannot be enabled at the group or instance level, and it's causing a lot of support tickets.

### Preview

https://docs-staging.datadoghq.com/fermayo/ciapp-update-gitlab-instructions/continuous_integration/setup_pipelines/gitlab/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-15 22:35 UTC, ruthnaebeck requested changes

2021-07-15 22:35 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/gitlab.md
> +* For Omnibus installations:
```suggestion
**Omnibus installations**
```

2021-07-15 22:35 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/gitlab.md
> +* For installations from source:
```suggestion
**From source installations**
```

2021-07-15 22:35 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/gitlab.md
> +* For Kubernetes installations:
```suggestion
**Kubernetes installations**
```

2021-07-15 22:35 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/gitlab.md
> +You need to enable the `datadog_ci_integration` [feature flag][1] to activate the integration. Run the following commands, which use GitLab's [Rails Runner][2], depending on your installation type:
```suggestion
Enable the `datadog_ci_integration` [feature flag][1] to activate the integration. Run one of the following commands, which use GitLab's [Rails Runner][2], depending on your installation type:
```

2021-07-15 22:35 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/gitlab.md
> +<div class="alert alert-info"><strong>Note</strong>: The native Datadog integration is the recommended approach and the one that is actively under development</div>
```suggestion
<div class="alert alert-info"><strong>Note</strong>: The native Datadog integration is the recommended approach and the option that is actively under development.</div>
```

2021-07-15 22:35 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/gitlab.md
> +* **URL**: `https://webhooks-http-intake.logs.datadoghq.com/v1/input/<API_KEY>` where `<API_KEY>` is one generated [here][2].
```suggestion
* **URL**: `https://webhooks-http-intake.logs.datadoghq.com/v1/input/<API_KEY>` where `<API_KEY>` is [your Datadog API key][2].
```

2021-07-15 22:35 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/gitlab.md
> +After the integration is successfully configured, both [Pipelines][4] and [Pipeline Executions][5] pages will start populating with data after pipelines finish.
```suggestion
After the integration is successfully configured, the [Pipelines][4] and [Pipeline Executions][5] pages populate with data after the pipelines finish.
```

2021-07-16 07:52 UTC, AdrianLC approved these changes

2021-07-19 18:15 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/gitlab.md
> +: Specifies which [Datadog site][1] to send data to. Only `datadoghq.com` is currently supported.<br/>
```suggestion
: Specifies which [Datadog site][1] to send data to. Only `datadoghq.com` is supported.<br/>
```

2021-07-19 18:35 UTC, ruthnaebeck approved these changes

2021-07-19 18:35 UTC, merged