[CIAPP] No need to have special flags for MsTest anymore
DataDog/documentation pull request #11115
Opened 2021-07-15 12:49 UTC by fermayo

### What does this PR do?

Removes special instructions for MsTest V2 as the latest version of the tracer does not need them

### Motivation

New version of the .NET tracer

### Preview

https://docs-staging.datadoghq.com/fermayo/ciapp-update-dotnet-docs/continuous_integration/setup_tests/dotnet/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-15 12:53 UTC, tonyredondo approved these changes
LGTM

2021-07-15 22:21 UTC, ruthnaebeck requested changes

2021-07-15 22:21 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_tests/dotnet.md
> +To install (or update if already installed) the `dd-trace` command globally on the machine, run:
```suggestion
To install or update the `dd-trace` command globally on the machine, run:
```

2021-07-15 22:21 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_tests/dotnet.md
>  All tests will be automatically instrumented.
```suggestion
All tests are automatically instrumented.
```

2021-07-19 18:14 UTC, ruthnaebeck approved these changes
Ping #documentation when you are ready for merge

2021-07-19 18:34 UTC, merged