[rum] add RUM watchdog insights docs page
DataDog/documentation pull request #11189
Opened 2021-07-22 14:54 UTC by hdelaby

### What does this PR do?

* Create page for "RUM Watchdog Insights" doc

### Motivation

* New feature! 🎉 

### Preview

https://docs-staging.datadoghq.com/hdelaby/rum_watchdog_insights/real_user_monitoring/explorer/watchdog_insights/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-26 22:15 UTC, alai97 requested changes
Standardized image alt text, restructured lists in the Collections section, and suggested comments with doc feedback.

2021-07-26 22:15 UTC, alai97 commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +Latency outliers are computed for [Core Web Vitals][2] (First Contentful Paint, First Input Delay and Cumulative Layout Shift) and [Loading Time][3].
```suggestion
Latency outliers are computed for [Core Web Vitals][2] such as First Contentful Paint, First Input Delay, and Cumulative Layout Shift, and [Loading Time][3].
```

2021-07-26 22:15 UTC, alai97 commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +  * The value of the performance metric that has this field, and what the baseline is for the rest of the data.
```suggestion
In the **banner card** view, you can see:

* The field name.
* The performance metric value containing the field and the baseline for the rest of the data.
```

2021-07-26 22:15 UTC, alai97 commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +{{< img src="real_user_monitoring/explorer/watchdog_insights/latency_outlier_s_card.png" alt="Latency Outlier card (S)" style="width:60%;" >}}
```suggestion
{{< img src="real_user_monitoring/explorer/watchdog_insights/latency_outlier_s_card.png" alt="Latency Outlier banner card view" style="width:100%;" >}}
```

2021-07-26 22:15 UTC, alai97 commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +  * The timeseries of the performance metric for this field, and of the baseline for the rest of the data.
```suggestion
In the **side panel card** view, you can see a timeseries of the performance metric for the field and baseline for the rest of the data.
```

2021-07-26 22:15 UTC, alai97 commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +{{< img src="real_user_monitoring/explorer/watchdog_insights/latency_outlier_l_card.png" alt="Latency Outlier card (L)" style="width:60%;" >}}
```suggestion
{{< img src="real_user_monitoring/explorer/watchdog_insights/latency_outlier_l_card.png" alt="Latency Outlier side panel view" style="width:100%;" >}}
```

2021-07-26 22:15 UTC, alai97 commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +  * A list of RUM views that have this field, to be able to find the root cause of the performance issue in the [performance waterfall][4].
```suggestion
In the **full side panel** view, you can see a list of RUM events that contain the field. Look for the root cause of the performance issue in the [performance waterfall][4].
```

2021-07-26 22:15 UTC, alai97 commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +{{< img src="real_user_monitoring/explorer/watchdog_insights/latency_outlier_side_panel.png" alt="Latency Outlier side panel" style="width:60%;" >}}
```suggestion
{{< img src="real_user_monitoring/explorer/watchdog_insights/latency_outlier_side_panel.png" alt="Latency Outlier full side panel view" style="width:100%;" >}}
```

2021-07-27 07:29 UTC, hdelaby commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +In the following example, Watchog Insights highlights that the instance of our application deployed on `view.url_host:www.shopist.io` causes most of the errors observed in a specific time range.
🙈

2021-07-27 07:34 UTC, hdelaby commented
Hey @alai97, thanks a lot for the review! While I'm OK with most of the comments, I mostly copied/pasted https://docs.datadoghq.com/logs/explorer/watchdog_insights/ and adapted it to RUM. Does it change the way we want to do things here?

2021-07-27 15:25 UTC, alai97 commented
Hey @hdelaby, thanks for the additional context. It doesn't change my doc review of the Watchdog Insights for RUM; in fact, I recommend porting over the changes here to that page for Watchdog Insights for Logs to be more consistent. Let me know if you're down with that and either you and I can create a separate PR for that page 😀

2021-07-30 08:16 UTC, hdelaby commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +With Watchdog Insights, find your way faster to the root cause of problems with contextual insights you receive as you explore Real User Monitoring (RUM) events. Watchdog Insights complements your ex
I think this changes the meaning of the sentence too much. Watchdog Insights helps you navigating through the RUM Explorer by recommending outliers and potential performance bottlenecks impacting a subset of users.

The suggested change implies that RM offers contextual insights AND watchdog insights - which reads a bit weird.

2021-07-30 08:33 UTC, hdelaby commented
Hey @alai97 thanks a lot for your work on this one, it's not an easy concept and you nailed it!

2021-07-30 16:45 UTC, alai97 commented on content/en/real_user_monitoring/explorer/watchdog_insights.md
> +With Watchdog Insights, find your way faster to the root cause of problems with contextual insights you receive as you explore Real User Monitoring (RUM) events. Watchdog Insights complements your ex
Good feedback, @hdelaby! I amended my suggestion, how's this for a rewording?

2021-07-30 16:46 UTC, alai97 commented
Thanks, Hugo! One more comment and we're good to merge.

2021-08-02 08:06 UTC, hdelaby commented
We're good to go! Thank you 💯

2021-08-03 22:16 UTC, alai97 approved these changes
Sounds good, @hdelaby! I'll create a ticket to port over these changes into Watchdog Insights for Logs.

2021-08-03 22:22 UTC, merged