Join all the instructions to enable logs in Jenkins
DataDog/documentation pull request #11198
Opened 2021-07-22 21:29 UTC by fermayo

### What does this PR do?

Puts together all instructions to get logs enabled on the Jenkins plugin under one section.

### Motivation

Align with the in-app onboarding.

### Preview

https://docs-staging.datadoghq.com/fermayo/ciapp-update-jenkins-docs/continuous_integration/setup_pipelines/jenkins/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-22 21:48 UTC, ruthnaebeck requested changes

2021-07-22 21:48 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/jenkins.md
> +### Enable job log collection on the Agent
```suggestion
### Datadog Agent
```

2021-07-22 21:48 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/jenkins.md
> +First, the Datadog Agent needs to be configured to open a TCP port to collect logs:
```suggestion
First, enable job log collection on the Datadog Agent by opening a TCP port to collect logs:
```

2021-07-22 21:48 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/jenkins.md
> +### Enable job log collection in the plugin
```suggestion
### Datadog Plugin
```

2021-07-22 21:48 UTC, ruthnaebeck commented on content/en/continuous_integration/setup_pipelines/jenkins.md
> +Second, enable job log collection on the plugin:
```suggestion
Second, enable job log collection on the Datadog Plugin:
```

2021-07-26 14:39 UTC, drodriguezhdez approved these changes

2021-07-26 17:31 UTC, fermayo commented
@ruthnaebeck this is ready to go

2021-07-27 14:23 UTC, ruthnaebeck approved these changes

2021-07-27 14:24 UTC, merged