[rum] guide on upgrade to browser sdk v3
DataDog/documentation pull request #11257
Opened 2021-07-29 14:21 UTC by hdelaby

### What does this PR do?

Guide that summarises the evolutions of Browser SDK v3.

### Motivation

New feature and necessity to document breaking changes.

### Preview

https://docs-staging.datadoghq.com/hdelaby/migrate-v3-browser/real_user_monitoring/guide/v3-browser-sdk-upgrade/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-07-29 21:33 UTC, ruthnaebeck requested changes

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/_index.md
> +    {{< nextlink href="real_user_monitoring/guide/v3-browser-sdk-upgrade" >}}Upgrading the Browser SDK to v3{{< /nextlink >}}
```suggestion
    {{< nextlink href="real_user_monitoring/guide/browser-sdk-upgrade" >}}Upgrade the Browser SDK{{< /nextlink >}}
```

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +title: Upgrading the Browser SDK to v3
```suggestion
title: Upgrade the Browser SDK
```

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +---
Rename file to `browser-sdk-upgrade.md`

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +Version 3 of the RUM Browser SDK introduces [Session Replay][1]. With this new major version, several breaking changes were made to the Browser SDK.
```suggestion
RUM Browser SDK v3 introduces [Session Replay][1]. With this major version update, several breaking changes were made to the Browser SDK.
```

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +### Stopping the generation of a RUM error for failed network requests
```suggestion
## Changes
### RUM errors
```

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +If you want to continue seeing these failed network requests as RUM errors, Datadog recommends intercepting the resource with the [beforeSend API][4], checking the `status_code` property and manually
```suggestion
To continue seeing the failed network requests as RUM errors, Datadog recommends intercepting the resource with the [beforeSend API][4], checking the `status_code` property, and manually sending an error with the [addError API][5].
```

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +### Removing the source attribute from the addError API
```suggestion
### Source attribute
```

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +The Browser SDK no longer lets you specify the source of an error collected with the [addError API][5]. All errors collected with this API now have their source attribute set to `custom`. The [addErr
```suggestion
The Browser SDK no longer lets you specify the source of an error collected with the [addError API][5]. All errors collected with this API have their source attribute set to `custom`. The [addError API][5] accepts a context object as its second parameter, which should be used to pass extra context about the error.
```

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +### Deprecated Typescript types
```suggestion
## Deprecated
### TypeScript types
```

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +### Deprecated initialization options
```suggestion
### Initialization options
```

2021-07-29 21:33 UTC, ruthnaebeck commented on content/en/real_user_monitoring/guide/v3-browser-sdk-upgrade.md
> +### Deprecated API
```suggestion
### API
```

2021-07-30 08:02 UTC, hdelaby commented
Thank @ruthnaebeck, you took it to the next level 🙇 🥇  Ready to merge :)

2021-07-30 08:10 UTC, bcaudan approved these changes

2021-07-30 17:00 UTC, ruthnaebeck approved these changes

2021-07-30 17:01 UTC, merged