(DOCS-2057) Teams and Faces updates
DataDog/documentation pull request #11267
Opened 2021-07-29 20:13 UTC by jtappa

### Preview
https://docs-staging.datadoghq.com/jorie/DOCS-2057/account_management/
---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### To-Do (Jorie)
- [ ] /account_management/ index updates
- [ ] /account_management/org_settings updates
- [ ] /account_management/users/ updates
- [ ] /developers/events/email/ updates
- [ ] Remove any screenshots that have the "Teams" icon 
- [ ] Remove or update any screenshots that have the old user/org settings links
- [ ] Make sure to `git -rm` the actual files for images removed from markdown files

### To-Do (Kaylyn)
- [ ] service accounts updates

2021-07-31 02:28 UTC, jtappa commented
Note for Kaylyn:
The only thing I didn't get fixed up was the sidenav, it was just too hairy with conflicts and gross and I got frustrated and gave up 😭 sorry. But I added what I was *trying* to get it to look like in the review checklist, if you can take a stab at it. There's just one new page, and it's definitely not *required* to re-org all the links around, I just thought this layout would make more sense based on how things are organized in the app now.

2021-08-16 19:55 UTC, jtappa commented
Update: Giving the sidebar another try this afternoon. Will change PR from Draft once those commits are in place.

2021-08-20 18:29 UTC, alai97 requested changes
Mostly bold and spacing suggestions!

2021-08-20 18:29 UTC, alai97 commented on content/en/events/guides/email.md
> +2. From the Account menu at the bottom left, select **Organization Settings**
```suggestion
2. From the **Account** menu at the bottom left, select **Organization Settings**.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/users/_index.md
> +See the [Role Based Access Control][2] documentation to discover all of the roles available and how to create custom ones.
```suggestion
To discover all of the roles available and how to create custom ones, see the [Role Based Access Control documentation][2].
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/users/_index.md
> +1. Go to the Users tab of Organization Settings.
```suggestion
1. Go to the **Users** tab of **Organization Settings**.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/users/_index.md
>  2. Select the *Edit* button on the right of the user line.
```suggestion
2. Select the **Edit** button on the right of the user line.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/users/_index.md
> +To resend an invite in list view, click the user to open the user side panel, and click **Resend Invite**. Or in grid view, hover over the user box and click **Resend Invite**.
```suggestion
To resend an invite in list view, click the user to open the user side panel and click **Resend Invite**. Or in grid view, hover over the user box and click **Resend Invite**.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/users/_index.md
> +The new user receives an email with a link to log in. The user is marked with the status `Invite Pending` until they log in. To cancel their invite before they log in, click the *Delete Invite* butto
```suggestion
The new user receives an email with a link to log in. The user is marked with the status `Invite Pending` until they log in. To cancel their invite before they log in, click the **Delete Invite** button on the right of the user line in list view, or on the user box in grid view. 
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/plan_and_usage.md
> +Your account billing history is available from the Billing History tab in the [Plan & Usage section][2]. For specific billing questions, contact your account representative or [success@datadoghq.com]
```suggestion
Your account billing history is available from the **Billing History** tab in the [Plan & Usage section][2]. For specific billing questions, contact your account representative or [success@datadoghq.com][4].
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/plan_and_usage.md
> +Upgrade or downgrade your account from the Plan tab on the Plan & Usage section.
```suggestion
Upgrade or downgrade your account from the **Plan** tab on the Plan & Usage section.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +To rename your organization, click the **Rename organization** tab, enter the new name, then click save.
```suggestion
To rename your organization, click the **Rename organization** tab, enter the new name, then click **Save**.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +**Note**: **Your organization name may not exceed 32 characters**.
```suggestion
**Note: Your organization name may not exceed 32 characters.**
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +#### Audit Logs
```suggestion

#### Audit Logs
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +#### Audit Log Settings
```suggestion

#### Audit Log Settings
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +### General
```suggestion

### General
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +The **Audit Log Settings** tab allows you to set the retention period of audit logs, and enable archiving to other cloud storage services.
```suggestion
The **Audit Log Settings** tab allows you to set the retention period of audit logs and enable archiving to other cloud storage services.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +
```suggestion
If your application does not have an existing Datadog integration, and you don’t want to create a custom Agent check, you can send events with email. To learn how to set up events API emails, read the [Events with email guide][8].
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +You can filter application keys by name, ID, or owner, or click the **Only My Keys** toggle to only view application keys you own. Read the [documentation on application keys][6] for more information
```suggestion
You can filter application keys by name, ID, or owner, or click the **Only My Keys** toggle to only view application keys you own. Read the [Application keys documentation][6] for more information on how to add or remove them.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +Users who log in with SAML and do not have the values that map to a Datadog role will be stripped of all roles and are not allowed to log in.
```suggestion
Users who log in with SAML and do not have the values that map to a Datadog role are stripped of all roles and are not allowed to log in.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +Read the [Mapping SAML attributes][4] documentation to learn more about how to create and set mappings.
```suggestion
To learn how to create and set mappings, read the [Mapping SAML attributes documentation][4].
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +When enabled, users logging in with SAML to your Datadog account are stripped of their current roles and reassigned to new roles based on the details in their SAML assertion passed on from your Ident
```suggestion
When enabled, users logging in with SAML to your Datadog account are stripped of their current roles and reassigned to new roles based on the details in their SAML assertion passed on from your Identity Provider and the mappings you've created.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +Read the [Role Based Access Controll][3] documentation to learn about default and custom roles in Datadog.
```suggestion
To learn about default and custom roles in Datadog, read the [Role Based Access Control documentation][3].
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/org_settings.md
> +The Organization Settings allow you to manage users, groups, RBAC, keys and tokens, more. This page outlines each section and where in the documentation you can learn about specific tasks in **Organi
```suggestion
Organization Settings allow you to manage users, groups, RBAC, keys, and tokens. This page outlines every section and where in the documentation you can learn about specific tasks in **Organization Settings**.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/api-app-keys.md
> +To remove a Datadog application key, navigate to **Organization Settings -> Application Keys**. If you have the [permission][5] to create and manage application keys, you can see your own keys and cl
```suggestion
To remove a Datadog application key, navigate to **Organization Settings** > **Application Keys**. If you have the [permission][5] to create and manage application keys, you can see your own keys and click **Revoke** next to the key you want to revoke. If you have the permission to manage all org application keys, you can search for the key you want to revoke and click **Revoke** next to it.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/api-app-keys.md
> +**Note**: Application key names cannot be blank.
```suggestion
**Note:** Application key names cannot be blank.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/api-app-keys.md
> +To add a Datadog application key, navigate to **Organization Settings -> Application Keys**. If you have the [permission][5] to create application keys you can click **New Key**.
```suggestion
To add a Datadog application key, navigate to **Organization Settings** > **Application Keys**. If you have the [permission][5] to create application keys, click **New Key**.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/api-app-keys.md
> +To remove a Datadog API key or client token, navigate to the list of keys or tokens, and click the trash can icon with **Revoke** next to the key or token you want to remove.
```suggestion
To remove a Datadog API key or client token, navigate to the list of keys or tokens, and click the **trash can** icon with **Revoke** next to the key or token you want to remove.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/api-app-keys.md
>  **Note**:
```suggestion
**Notes:**
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/api-app-keys.md
> +To manage your client tokens, go to Organization settings, then click the **Client Tokens** tab.
```suggestion
To manage your client tokens, go to **Organization Settings**, then click the **Client Tokens** tab.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/_index.md
> +The *Application Keys* tab in *Personal Settings* allows you to manage your application keys. To copy a key, hover over it until the **Copy Key** icon appears to the right, and click on it. You can a
```suggestion
The **Application Keys** tab in **Personal Settings** allows you to manage your application keys. To copy a key, hover over it until the **Copy Key** icon appears to the right, and click on it. You can also click into a specific key to edit its name, view when it was created, view the profile of the key's owner, copy it, or revoke it.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/_index.md
> +The *Organizations* page in *Personal Settings* lists all of the organizations you are associated with. Switch between these organizations from this page or by hovering over the account menu in the l
```suggestion
The **Organizations** page in **Personal Settings** lists all of the organizations you are associated with. Switch between these organizations from this page or by hovering over the account menu in the left-side navigation.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/_index.md
> +If you are unsure if an email digest or report is relevant to you, you can view an example by clicking the **Example** link next to each email subscription. You can also use the **Unsubscribe From Al
```suggestion
If you are unsure if an email digest or report is relevant to you, view an example by clicking the **Example** link next to each email subscription. You can also use the **Unsubscribe From All** button to quickly unsubscribe from all email subscriptions.

```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/_index.md
> +You can set your timezone, desktop notifications, and email subscriptions from the [*Preferences* tab][3] within the *Personal Settings* page. Under email subscriptions, you have access to the follow
```suggestion
You can set your timezone, desktop notifications, and email subscriptions from the [**Preferences** tab][3] within the **Personal Settings** page. Under email subscriptions, you have access to the following reports:
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/_index.md
> +If you log in to Datadog using Google authentication, your email address is provided by your Google account and is *not* editable within Datadog. To change your email address in Google, see the [Goog
```suggestion
If you log in to Datadog using Google authentication, your email address is provided by your Google account and is **not** editable within Datadog. To change your email address in Google, see the [Google documentation][2].
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/_index.md
> +Your profile is how others in your organization recognize you in Datadog. Set or update your name, email address and title here.
```suggestion
Your profile is how others in your organization recognize you in Datadog. Set or update your name, email address, and title here.
```

2021-08-20 18:29 UTC, alai97 commented on content/en/account_management/_index.md
> +The personal settings pages in Datadog allow you to control how you appear to others in your organization; switch or leave organizations; manage your notification preferences and more.
```suggestion
The personal settings pages in Datadog allow you to control how you appear to others in your organization, switch or leave organizations, and manage your notification preferences.
```

2021-08-20 20:43 UTC, alai97 approved these changes

2021-08-20 20:44 UTC, merged