Update CSPM regions.md
DataDog/documentation pull request #11326
Opened 2021-08-05 01:42 UTC by ItsYamnitsky

### What does this PR do?
Clarify that CSPM is available in EU.

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-08-05 20:11 UTC, ruthnaebeck requested changes

2021-08-05 20:11 UTC, ruthnaebeck commented on content/en/security_platform/cspm/findings.md
>  {{< site-region region="us3,gov,eu" >}}
```suggestion
{{< site-region region="us3,gov" >}}
```

2021-08-05 20:11 UTC, ruthnaebeck commented on content/en/security_platform/cspm/findings.md
> +Cloud Security Posture Management is not currently available in US1-FED and US3.
```suggestion
Cloud Security Posture Management is not available in US1-FED or US3.
```

2021-08-12 17:17 UTC, sarina-dd approved these changes

2021-08-12 17:17 UTC, sarina-dd approved these changes

2021-08-12 17:17 UTC, merged