[datadog-lambda-go] Rename WrapHandler -> WrapFunction
DataDog/documentation pull request #11374
Opened 2021-08-10 17:20 UTC by DarcyRaynerDD

### What does this PR do?
For clarity reasons recently updated the datadog-lambda-go library to rename the WrapHandler function to WrapFunction. The old method still exists and works, but is marked as deprecated.

### Motivation
The most recent release of datadog-lambda-go

### Preview

https://docs-staging.datadoghq.com/darcy.rayner/update-dd-lambda-go-doc/serverless/installation/go/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-08-11 14:34 UTC, astuyve commented
![image](https://user-images.githubusercontent.com/1598537/129048679-ed8f774b-608e-481e-877f-d8cdb1273a99.png)
Looks like we're missing one rename here?

2021-08-11 14:35 UTC, astuyve commented
Ah yes, here: https://github.com/DataDog/documentation/pull/11374/files#diff-dec86e3385da3fbf860403d3a6225838f9aea041fc7ffe4bead805e2451719ffR81

2021-08-11 22:38 UTC, apigirl approved these changes

2021-08-11 22:40 UTC, apigirl commented on content/en/serverless/installation/go.md
>        lambda.Start(ddlambda.WrapHandler(myHandler, &ddlambda.Config{
```suggestion
      lambda.Start(ddlambda.WrapFunction(myHandler, &ddlambda.Config{
```

2021-08-12 14:10 UTC, tianchu approved these changes

2021-08-12 14:11 UTC, Hesperide approved these changes

2021-08-12 16:07 UTC, cswatt requested changes

2021-08-12 16:07 UTC, cswatt approved these changes

2021-08-12 16:07 UTC, merged