[CIAPP-2255] Add CirclecI docs for webhooks for ci visibility
DataDog/documentation pull request #11496
Opened 2021-08-23 15:50 UTC by AdrianLC

### What does this PR do?
Add new page to CI Visibility docs for CircleCI support.

### Preview

https://docs-staging.datadoghq.com/adrian.lopezcalvo%2Fci-visibility-circleci-docs/continuous_integration/setup_pipelines/circleci

### Additional Notes
**To be kept in draft status and not merged until we test in private with some organizations.**

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-08-23 16:07 UTC, cg14823 requested changes

2021-08-23 16:07 UTC, cg14823 commented on content/en/continuous_integration/setup_pipelines/circleci.md
> +* **Webhook URL**: `https://webhooks-http-intake.logs.datadoghq.com/api/v2/webhook/?dd-api-key=<API_KEY>` where `<API_KEY>` is [your Datadog API key][1].
```suggestion
* **Webhook URL**: `https://webhooks-http-intake.logs.datadoghq.eu/api/v2/webhook/?dd-api-key=<API_KEY>` where `<API_KEY>` is [your Datadog API key][1].
```

2021-08-23 16:09 UTC, edrevo commented
Preview URL isn't working

2021-08-24 08:35 UTC, AdrianLC commented
> Preview URL isn't working

It's working now

2021-08-24 08:59 UTC, cg14823 approved these changes

2021-08-24 10:02 UTC, edrevo approved these changes

2021-08-31 16:43 UTC, fermayo commented on content/en/continuous_integration/setup_pipelines/circleci.md
> +{{< /site-region >}}
```suggestion
{{< /site-region >}}

Afterwards, click on **Add Webhook** to save the new webhook.
```

2021-09-16 16:50 UTC, kayayarai approved these changes

2021-09-16 17:16 UTC, merged