Alerting new documentation structure
DataDog/documentation pull request #11576
Opened 2021-09-01 14:36 UTC by dussault-antoine

### What does this PR do?
New structure for the alerting documentation : [Jira DOCS ticket](https://datadoghq.atlassian.net/browse/DOCS-2364)

### Motivation
See JIRA ticket

### Preview

https://docs-staging.datadoghq.com/antoine.dussault/alerting_new_structure/monitors

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-09-01 23:00 UTC, ruthnaebeck requested changes
Initial Feedback.

Also, remove file `content/en/monitors/monitor_types_old/_index.md`

2021-09-02 09:44 UTC, dussault-antoine commented on content/en/monitors/manage/monitor_status.md
>  kind: documentation
don't we want to keep file names transparent to page titles ?
- _search_monitors_ for Search Monitors
- _monitor_status_ for Monitor Status

2021-09-02 10:13 UTC, dussault-antoine commented on content/en/monitors/manage/search_monitors.md
>  ---
same comment here : don't we want to keep file names transparent to page titles ?
- _search_monitors_ for Search Monitors
- _monitor_status_ for Monitor Status

2021-09-02 10:13 UTC, dussault-antoine commented on content/en/monitors/create/monitor_types/_index.md
> +---
This was changed 👍

2021-09-02 10:14 UTC, dussault-antoine commented on content/en/monitors/create/_index.md
> +{{< img src="/monitors/create/choose_monitor_type.png" alt="Choose monitor type" style="width:100%;">}}
I replaced it by a gif to make it go through all monitor types. I think it adds some value + I will make sure to update it when new monitor types are added, wdyt ?

2021-09-07 20:54 UTC, ruthnaebeck commented on content/en/monitors/manage/monitor_status.md
>  kind: documentation
As much as possible without repeating words. Google tends to block pages with words repeated in the web url structure.

2021-09-07 20:56 UTC, ruthnaebeck commented on content/en/monitors/_index.md
> +[Monitor Notifications][2]: Set up notifications when creating monitors in order to keep your team informed of issues. Route the notifications to the right people, leverage template variables to incl
See the [files page](https://github.com/DataDog/documentation/pull/11576/files#diff-7bd8294b471f5765c52024b522ee07a765e818ac636bd2d3492e80d8f3a91503R34) for issues.

2021-09-08 14:38 UTC, dussault-antoine commented on content/en/monitors/manage/monitor_status.md
>  kind: documentation
https://docs.datadoghq.com/monitors/manage_monitor/
https://docs.datadoghq.com/monitors/monitor_types/
We are already doing the same today, that's why I am asking. I can definitely make the change, it's just that I thought transparent urls may be more explicit. Just let me know. All the other changes should already be committed

2021-09-08 19:45 UTC, ruthnaebeck commented on content/en/monitors/manage/monitor_status.md
>  kind: documentation
Yep, but this is an opportunity to change them since they are being changed anyway. Changing links is a lot of effort.

2021-09-08 22:11 UTC, ruthnaebeck requested changes
Docs review (part 1)

2021-09-08 22:11 UTC, ruthnaebeck commented on content/en/monitors/create/monitor_configuration.md
> +{{% tab "Check Alert" %}}
```suggestion
{{% tab "Check alert" %}}
```

2021-09-08 22:11 UTC, ruthnaebeck commented on content/en/monitors/create/monitor_configuration.md
> +A check alert tracks consecutive statuses submitted per check grouping and compares it to your thresholds. Set up the check alert to :
```suggestion
A check alert tracks consecutive statuses submitted per check grouping and compares it to your thresholds. Set up the check alert to:
```

2021-09-08 22:11 UTC, ruthnaebeck commented on content/en/monitors/create/monitor_configuration.md
> +See the [process check][1], [integration check][2] and [custom check][3] monitors documentation for more information on how to configure check alerts.
```suggestion
See the documentation for [process check][1], [integration check][2], and [custom check][3] monitors for more information on configuring check alerts.
```

2021-09-08 22:11 UTC, ruthnaebeck commented on content/en/monitors/create/monitor_configuration.md
> +The time (in seconds) to wait before starting alerting, to allow newly created groups to boot and applications to fully start. This should be a non-negative integer.
```suggestion
The time (in seconds) to wait before starting alerts to allow newly created groups to boot and applications to fully start. This should be a non-negative integer.
```

2021-09-08 22:11 UTC, ruthnaebeck commented on content/en/monitors/create/types/metric.md
> +For detailed instructions on the advanced alert options (No data, Autoresolve, etc), see the [Monitor Configuration][6] page.
```suggestion
For detailed instructions on the advanced alert options (no data, autoresolve, etc.), see the [Monitor Configuration][6] page.
```

2021-09-10 23:40 UTC, ruthnaebeck requested changes
Docs review (part 2)

2021-09-10 23:40 UTC, ruthnaebeck commented on content/en/monitors/manage/_index.md
> +| Mute      | Mute the selected monitors for `1h`, `4h`, `12h`, `1d`, `1w`, or `Forever` |
```suggestion
| Mute      | Mute the selected monitors for `1h`, `4h`, `12h`, `1d`, `1w`, or `Forever`. |
```

2021-09-10 23:40 UTC, ruthnaebeck commented on content/en/monitors/manage/_index.md
> +Monitor tags are independent of tags sent by the Agent or integrations. Add up to 32 tags directly to your monitors for filtering on the [manage monitors][1], [triggered monitors][5], or [manage down
```suggestion
Monitor tags are independent of tags sent by the Agent or integrations. Add up to 32 tags directly to your monitors for filtering on the [manage monitors][1], [triggered monitors][5], or [manage downtime][6] pages. Learn more about monitor tags in [Assigning Tags for the UI][7].
```

2021-09-10 23:40 UTC, ruthnaebeck commented on content/en/monitors/manage/_index.md
> +**Note**: Those tags are added to the alert event generated by the monitor, up to 25 tags in total on the alert event.
```suggestion
**Note**: Monitor tags are added to the alert event generated by the monitor, up to 25 tags in total on the alert event.
```

2021-09-10 23:40 UTC, ruthnaebeck commented on content/en/monitors/notify/_index.md
> +The escalation message can be added in the following ways:
```suggestion

The escalation message can be added in the following ways:
```

2021-09-10 23:40 UTC, ruthnaebeck commented on content/en/monitors/notify/_index.md
> +Learn how to configure your monitors for those use cases in [the example section](#examples).
```suggestion
Learn how to configure your monitors for those use cases in the [example section](#examples).
```

2021-09-10 23:40 UTC, ruthnaebeck commented on content/en/monitors/notify/_index.md
> +To override the monitor priority in the notification message, use `{{override_priority 'Pi'}}` where `Pi` is between P1 and P5.
```suggestion
To override the monitor priority in the notification message, use `{{override_priority 'Pi'}}` where `i` is a number from 1 to 5.
```

2021-09-10 23:40 UTC, ruthnaebeck commented on content/en/monitors/notify/_index.md
> +**Note**: Handles that include parentheses (`(`, `)`) are not supported. When a handle with parentheses is used, the handle is not be parsed and no alert is created.
```suggestion
**Note**: Handles that include parentheses (`(`, `)`) are not supported. When a handle with parentheses is used, the handle is not parsed and no alert is created.
```

2021-09-10 23:40 UTC, ruthnaebeck commented on content/en/monitors/notify/_index.md
> +2. From the test notifications pop-up, choose the monitor case to test in. You can only test states that are available in the monitor’s configuration for the thresholds specified in the alerting cond
```suggestion
2. From the test notifications pop-up, choose the monitor case to test. You can only test states that are available in the monitor’s configuration for the thresholds specified in the alerting conditions. [Recovery thresholds][13] are an exception, as Datadog sends a recovery notification once the monitor either is no longer in alert, or it has no warn conditions.
```

2021-09-12 14:07 UTC, alirezayosefian commented
Hello Dear friends
I did a Google search for [**فرش قیطران**](https://hyperfarsh.com/product-brands/%d9%81%d8%b1%d8%b4-%d9%82%db%8c%d8%b7%d8%b1%d8%a7%d9%86/) SEO and with the help of seobility I came across this message: Avoid internal links with dynamic URL parameters. Thank you for your help. What is this problem for?
Thanks

2021-09-13 16:59 UTC, dussault-antoine commented on config/_default/menus/menus.en.yaml
> +    url: monitors/create/types/host/
i think it's actually useful to keep the side menu opened when selecting a monitor_type

2021-09-15 20:51 UTC, ruthnaebeck approved these changes

2021-09-15 21:38 UTC, merged