DOCS-2143 Synthetic Settings Screenshots Update
DataDog/documentation pull request #11583
Opened 2021-09-01 22:48 UTC by alai97

### What does this PR do?

Update two screenshots (Specify Value, Create from HTTP Tests) in Synthetics Settings.

### Motivation

DOCS-2143

### Preview

https://docs-staging.datadoghq.com/alai97/xpath-support-screenshot-update/synthetics/settings

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-09-02 16:48 UTC, ruthnaebeck requested changes

2021-09-02 16:48 UTC, ruthnaebeck commented on content/en/synthetics/settings/_index.md
> +{{< img src="synthetics/settings/variable_value_2.png" alt="Global Variable Specify Value"  style="width:100%;">}}
```suggestion
{{< img src="synthetics/settings/variable_value_2.png" alt="Global Variable Specify Value" style="width:100%;">}}
```

2021-09-02 16:48 UTC, ruthnaebeck commented on content/en/synthetics/settings/_index.md
> +{{< img src="synthetics/settings/variable_fromhttp_2.png" alt="Variable from http"  style="width:100%;">}}
```suggestion
{{< img src="synthetics/settings/variable_fromhttp_2.png" alt="Variable from http" style="width:100%;">}}
```

2021-09-02 16:49 UTC, ruthnaebeck approved these changes

2021-09-05 17:27 UTC, MargotLepizzera commented
@alai97 Thanks for putting that PR together! Some comments:

- `Settings` page: do you think you could add an example of a variable actually being created from a JSON payload? Similar to what currently exists (with an actual JSONPath and preview). If you need help getting one working, don't hesitate to schedule some time on my cal for me to show you! 
- The XPath link is linking to RBAC instead of to some XPath doc.
- We would also need to update the [Multistep API test doc](https://docs.datadoghq.com/synthetics/multistep?tab=requestoptions#extract-variables-from-the-response) as well as on the [HTTP step](https://docs.datadoghq.com/synthetics/browser_tests/actions#extract-a-variable-from-the-response) for Browser tests.

2021-09-08 21:31 UTC, alai97 commented
@MargotLepizzera are you asking if we can add a video instead of a screenshot in the **Create from HTTP** section? If that's the case, can I ask you to provide me that content? 🙏🏼

The Multistep API Test screenshot is updated in PR #11307 (https://github.com/DataDog/documentation/pull/11307/files)! 

I'm updating the XPath link and adding a video for Browser Tests in the following commit.

2021-09-14 11:24 UTC, MargotLepizzera commented
Ok so here are some links you can use @alai97 :

Settings - Create from HTTP test: https://a.cl.ly/L1urv2nG

Browser tests - HTTP step - Setup https://a.cl.ly/9ZuQLBRP
Browser tests - HTTP step - Add assertions https://a.cl.ly/NQuY517A
Browser tests - HTTP step - Extract variable https://a.cl.ly/P8uGDy6E

Multistep API tests - Define requests - Define the request https://a.cl.ly/Blux21jL
Multistep API tests - Define requests - Add assertion https://a.cl.ly/bLuqywY4
Multistep API tests - Define requests - Extract variables from response https://a.cl.ly/jku46Dr6

2021-09-15 21:53 UTC, alai97 commented on content/en/synthetics/browser_tests/actions.md
> +{{< img src="synthetics/browser_tests/browser_test_vft2.mp4" alt="Create a variable from an HTTP request in a Browser test" video="true"  width="80%" >}}
```suggestion
{{< img src="synthetics/browser_tests/browser_test_vft2.mp4" alt="Create a variable from an HTTP request in a Browser test" video="true" width="80%" >}}
```

2021-09-20 13:56 UTC, MargotLepizzera commented on content/en/synthetics/browser_tests/actions.md
> +Once created, this variable can be used in the following steps of your browser test.
Add link to following section?

2021-09-20 14:00 UTC, MargotLepizzera commented on content/en/synthetics/multistep.md
>  You can create up to 20 assertions per step by clicking on **New Assertion** or by clicking directly on the response preview:
```suggestion
You can create up to 20 assertions per step by clicking on **New Assertion** or by clicking directly on the response preview.
```

2021-09-20 14:02 UTC, MargotLepizzera commented on content/en/synthetics/multistep.md
> +{{< img src="synthetics/api_tests/ms_define_request2.png" alt="Define request for your Multistep API test" style="width:90%;" >}}
Let's move the image at the end of the section!

2021-09-20 14:05 UTC, MargotLepizzera commented
Looking good @alai97! Added a few comments inline and just one last note about the updates on the browser test page: it looks like the [main HTTP request section](https://docs-staging.datadoghq.com/alai97/xpath-support-screenshot-update/synthetics/browser_tests/actions#http-requests) and the [setup section ](https://docs-staging.datadoghq.com/alai97/xpath-support-screenshot-update/synthetics/browser_tests/actions#set-up) are still using old screenshots? The [extract variable from response section](https://docs-staging.datadoghq.com/alai97/xpath-support-screenshot-update/synthetics/browser_tests/actions#extract-a-variable-from-the-response) also seems to have one screenshot and one recording - why not using just the new screenshot?

2021-09-20 18:34 UTC, alai97 commented on content/en/synthetics/browser_tests/actions.md
> +Once created, this variable can be used in the following steps of your browser test.
```suggestion
Once created, this variable can be used in the [following steps][#using-variables] of your browser test.
```

2021-09-22 02:32 UTC, alai97 commented on content/en/synthetics/multistep.md
> +[13]: /api/v1/synthetics/#create-a-test
```suggestion
[13]: /api/latest/synthetics/#edit-an-api-test
```

2021-09-22 02:38 UTC, merged