Update send-aws-services-logs-with-the-datadog-kinesis-firehose-desti…
DataDog/documentation pull request #11599
Opened 2021-09-02 22:50 UTC by sarina-dd

### What does this PR do?
Adds a section on how to find logs by AWS Kinesis Firehose ARN in Datadog

### Motivation
Jira request

### Preview
https://docs-staging.datadoghq.com/sarina/kinesis-logs-explorer/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination/

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-09-07 16:57 UTC, alai97 requested changes
Standardize header titles for consistency and a minor grammar nit.

2021-09-07 16:57 UTC, alai97 commented on content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
> +## Searching for AWS Kinesis logs in Datadog
```suggestion
## Search for AWS Kinesis logs in Datadog
```

2021-09-07 16:57 UTC, alai97 commented on content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
> +Once you have set up an Amazon Kinesis delivery stream, logs subscribed to your delivery stream are now available for analysis within Datadog. To populate all logs by ARN:
```suggestion
Once you have set up an Amazon Kinesis delivery stream, you can analyze the logs subscribed to your delivery stream in Datadog. 

To populate all logs by ARN:
```

2021-09-07 16:57 UTC, alai97 commented on content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
> +1. Navigate to [Logs Explorer][5] in Datadog to see all of your subscribed logs.
```suggestion
1. Navigate to the [Logs Explorer][5] in Datadog to see all of your subscribed logs.
```

2021-09-07 16:57 UTC, alai97 commented on content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
> +2. In the search bar, type `@aws.firehose.arn:"<ARN>"`, replacing `<ARN>` with your Amazon Kinesis Data Firehose ARN, and press enter.
```suggestion
2. In the search bar, type `@aws.firehose.arn:"<ARN>"`, replace `<ARN>` with your Amazon Kinesis Data Firehose ARN, and press **Enter**.
```

2021-09-07 16:57 UTC, alai97 commented on content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
> +1. Navigate to [Logs Explorer][5] in Datadog to see all of your subscribed logs.
Should this link send users to the in-app Logs Explorer or the Logs Explorer documentation?

2021-09-13 15:28 UTC, sarina-dd commented
@alai97 Thanks for the review! This PR is ready for final review.

2021-09-13 17:25 UTC, alai97 approved these changes

2021-09-14 15:30 UTC, merged