Clarifying recording flow in case of config options
DataDog/documentation pull request #11619
Opened 2021-09-07 07:39 UTC by MargotLepizzera

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-09-07 07:44 UTC, MargotLepizzera commented on content/en/synthetics/browser_tests/_index.md
> +**Note:** These options are set at every test execution and on every step of your browser test. They are however only applied at execution time and not at recording time. You should consequently manu
```suggestion
**Note:** These options are set at every test execution and for every step of your browser test. They are however only applied at execution time and not at recording time. You should consequently manually apply these on the page that is being used for recording and only then record steps the test should go through.
```

2021-09-07 07:45 UTC, MargotLepizzera commented on content/en/synthetics/guide/app-that-requires-login.md
> +These are set at every test execution and on every step of your browser test. Note that these settings are only applied at execution time and not at recording time. You should consequently manually a
```suggestion
These are set at every test execution and for every step of your browser test. Note that these settings are however only applied at execution time and not at recording time. You should consequently manually apply the configured headers, cookies, and/or credentials on the page that is being used for recording and only then record steps the test should perform post login. At execution time, the browser test automatically first goes through authentication thanks to the header/cookie/credentials you applied and then performs all the recorded steps.
```

2021-09-07 15:49 UTC, alai97 requested changes
Two wording nits and we can merge!

2021-09-07 15:49 UTC, alai97 commented on content/en/synthetics/browser_tests/_index.md
> +**Note:** These options are set at every test execution and for every step of your browser test. They are however only applied at execution time and not at recording time. You should consequently man
```suggestion
**Note:** These request options are set at every test execution and apply to every step of your browser test at execution time, not recording time. You can manually apply these options on the page you are recording and selectively record those steps for your test.
```

2021-09-07 15:49 UTC, alai97 commented on content/en/synthetics/guide/app-that-requires-login.md
> +These are set at every test execution and for every step of your browser test. Note that these settings are however only applied at execution time and not at recording time. You should consequently m
```suggestion
These options are set at every test execution and apply to every step of your browser test at execution time, not recording time. 

You can manually apply these configured headers, cookies, and credentials on the page you are recording and selectively record those steps your test performs post-login. By default, the browser test automatically passes through authentication with your specified headers, cookies, and credentials at execution time and performs all recorded steps.
```

2021-09-17 22:54 UTC, alai97 approved these changes

2021-09-20 18:11 UTC, merged