Rancher 2.5 control plane docs
DataDog/documentation pull request #11639
Opened 2021-09-09 13:26 UTC by ahmed-mez

### What does this PR do?
Document how to configure Control Plane integrations on Rancher RKE 2.5

### Motivation

### Preview

https://docs-staging.datadoghq.com/ahmed/rancher-control-plane/agent/kubernetes/control_plane

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-09-09 15:44 UTC, clamoriniere commented on content/en/agent/kubernetes/control_plane.md
> +      name: "gcr.io/datadoghq/agent:latest"
thanks to operator v0.7.0 and the defaulting logic. I think we can remove the need of defining the image

```suggestion
```

2021-09-09 15:44 UTC, clamoriniere commented on content/en/agent/kubernetes/control_plane.md
> +      name: "gcr.io/datadoghq/cluster-agent:latest"
same for the `clusterAgent.image`

```suggestion
```

2021-09-09 15:46 UTC, clamoriniere reviewed
Looks great !
just a view comment. 
quick question: no additional RBAC was required?

2021-09-09 15:59 UTC, clamoriniere approved these changes

2021-09-15 16:14 UTC, jtappa requested changes

2021-09-15 16:14 UTC, jtappa commented on content/en/agent/kubernetes/control_plane.md
> +1. The `pushprox` daemonsets are deployed via `rancher-monitoring` and running in the `cattle-monitoring-system` namespace.
Our flavor of markdown gets buggy if you leave numbered lists all the same number 😢 
```suggestion
1. Install the [rancher-monitoring chart][11].
2. The `pushprox` daemonsets are deployed with `rancher-monitoring` and running in the `cattle-monitoring-system` namespace.
```

2021-09-15 16:14 UTC, jtappa commented on content/en/agent/kubernetes/control_plane.md
> +By adding headless Kubernetes services to define check configurations, the Datadog Agent will be able to target the `pushprox` pods and collect metrics.
```suggestion
By adding headless Kubernetes services to define check configurations, the Datadog Agent is able to target the `pushprox` pods and collect metrics.
```

2021-09-15 16:14 UTC, jtappa commented on content/en/agent/kubernetes/control_plane.md
> +### API Server
```suggestion
### API server
```

2021-09-15 16:14 UTC, jtappa commented on content/en/agent/kubernetes/control_plane.md
> +### ETCD, Controller Manager and Scheduler
```suggestion
### Add Kubernetes services
```

2021-09-15 16:32 UTC, clamoriniere commented on content/en/agent/kubernetes/control_plane.md
> +### ETCD, Controller Manager and Scheduler
@jtappa can we be more specific like
```suggestion
### Add Kubernetes services to configure auto-discovery checks
```

2021-09-15 17:16 UTC, jtappa commented on content/en/agent/kubernetes/control_plane.md
> +### ETCD, Controller Manager and Scheduler
Yes, that's better!

2021-09-15 20:01 UTC, clamoriniere commented
@jtappa let me know if you see other change needed

2021-09-15 20:05 UTC, jtappa approved these changes

2021-09-15 20:06 UTC, merged