DOCS-2500 Alerting section link updates
DataDog/documentation pull request #11802
Opened 2021-09-27 21:15 UTC by ruthnaebeck

### What does this PR do?
Update links for Alerting section restructure https://github.com/DataDog/documentation/pull/11576

### Motivation
Alerting section restructure

### Preview
https://docs-staging.datadoghq.com/ruth/docs-2500/monitors/

### Additional Notes
N/A

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-09-27 22:13 UTC, kayayarai requested changes
The changes to links look fine throughout (I skimmed), but the changes to aliases should at least keep the old aliases. We don't want to lose redirects from the old structure. I'm not sure that you need aliases from old file names with new folder names, though. (I commented on a few, but then stopped).

2021-09-27 22:13 UTC, kayayarai commented on content/en/monitors/create/types/apm.md
> +  - /monitors/create/types/apm
I think for aliases you want to keep the old ones (and maybe add the new ones? but definitely keep the old ones)

2021-09-27 22:13 UTC, kayayarai commented on content/en/monitors/create/types/composite.md
> +    - /monitors/create/types/composite
keep the old one too

2021-09-27 22:13 UTC, kayayarai commented on content/en/monitors/create/types/custom_check.md
> +    - /monitors/create/types/custom_check
keep the old one too

2021-09-28 14:32 UTC, ruthnaebeck commented
> The changes to links look fine throughout (I skimmed), but the changes to aliases should at least keep the old aliases. We don't want to lose redirects from the old structure. I'm not sure that you need aliases from old file names with new folder names, though. (I commented on a few, but then stopped).

Fixed, thanks!

2021-09-30 22:19 UTC, merged