[CIAPP-2828] Add GitHub CI Visibility docs
DataDog/documentation pull request #11995
Opened 2021-10-18 16:12 UTC by cg14823

### What does this PR do?

Adds the documentation for tracing GitHub Action workflows with CI Visibility.

### Motivation

### Preview

https://docs-staging.datadoghq.com/carlos.gonzalez/ci-app-gh-docs/continuous_integration/setup_pipelines/github/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-11-03 14:47 UTC, fermayo requested changes

2021-11-03 14:47 UTC, fermayo commented on content/en/continuous_integration/setup_pipelines/_index.md
> +    {{< nextlink href="continuous_integration/setup_pipelines/github" >}}GitHub{{< /nextlink >}}
Should be OK to leave it as GitHub to be consistent with our in-app onboarding

2021-11-03 14:47 UTC, fermayo commented on content/en/continuous_integration/setup_pipelines/github.md
> +## Compatibility
```suggestion
<div class="alert alert-info">GitHub Actions integration is in beta. There are no billing implications for activating the GitHub Actions integration during this period.
</div>

## Compatibility
```

2021-11-03 18:34 UTC, fermayo commented
@cg14823 looks like the merge didn't go very well, as there are tons of changes now in this PR that are unrelated

2021-11-04 07:58 UTC, cg14823 commented
@fermayo  Yes, I just noticed not sure what happened at this point I think it is easier to just copy paste the relevant ones into a new PR.

2021-11-04 08:17 UTC, cg14823 commented
Closing in favour of https://github.com/DataDog/documentation/pull/12192 as the merge went haywire so it is easier yo just copy paste the relevant stuff than fixing this.

2021-11-04 08:17 UTC, closed without merging