DOCS-2599 Compute Apdex and Custom Performance Indicators with RUM Data Guide
DataDog/documentation pull request #12085
Opened 2021-10-26 01:33 UTC by alai97

### What does this PR do?

Adds a guide about computing your Apdex score with RUM data.

### Motivation

DOCS-2599

### Preview

https://docs-staging.datadoghq.com/alai97/real-user-monitoring-apdex-score-guide/real_user_monitoring/guide/compute-apdex-with-rum-data

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-11-05 15:57 UTC, alai97 commented on content/en/real_user_monitoring/guide/compute-apdex-with-rum-data.md
> +With a threshold of `T = 2 sec` and the minimum frustrating latency of `4T = 8 sec`, compute three queries with a formula in a Query Value widget to visualize your Apex score on a quick graph.
```suggestion
Let's use a hypothetical threshold of `T = 2 sec`. The minimum frustrating latency is `4T = 8 sec`. Compute three queries with a formula in a Query Value widget to visualize your Apex score on a quick graph.
```

2021-11-05 16:01 UTC, amina196 approved these changes

2021-11-09 18:09 UTC, kayayarai requested changes
Looking good! A few edits, mostly simplifying things. Let me know if you aren't sure what I'm getting at in any of them.

2021-11-09 18:09 UTC, kayayarai commented on content/en/real_user_monitoring/guide/compute-apdex-with-rum-data.md
> +
```suggestion
To access the JSON code for this graph, click the **JSON** tab next to **Edit**.

```

2021-11-09 18:09 UTC, kayayarai commented on content/en/real_user_monitoring/guide/compute-apdex-with-rum-data.md
> +- To compute the Apdex score with another RUM performance metric such as First Contentful Paint, replace `@view.LargestContentfulPaint` with `@view.FirstContentfulPaint` in the query.
```suggestion
- To compute the Apdex score with another RUM performance metric such as First Contentful Paint, replace `@view.LargestContentfulPaint` with `@view.FirstContentfulPaint` in the queries.
```

2021-11-09 19:10 UTC, alai97 commented on content/en/real_user_monitoring/guide/compute-apdex-with-rum-data.md
> +2. Click **Update query** in the dropdown menu. The `Largest Contentful Paint:<2s` query appears next to `RUM` for query `a`.
```suggestion
2. Press Enter or click **Update query** in the dropdown menu. The `Largest Contentful Paint:<2s` query appears next to `RUM` for query `a`.
```

2021-11-09 19:14 UTC, alai97 commented on content/en/real_user_monitoring/guide/compute-apdex-with-rum-data.md
> +3. Click **Update query** in the dropdown menu. The `Largest Contentful Paint:[2s - 3s]` query appears next to `RUM` for query `b`.
```suggestion
3. Press Enter or click **Update query** in the dropdown menu. The `Largest Contentful Paint:[2s - 3s]` query appears next to `RUM` for query `b`.
```

2021-11-09 19:14 UTC, alai97 commented on content/en/real_user_monitoring/guide/compute-apdex-with-rum-data.md
> +3. Click **Update query** in the dropdown menu. The `Type:view` query appears next to `RUM` for query `c`.
```suggestion
3. Press Enter or click **Update query** in the dropdown menu. The `Type:view` query appears next to `RUM` for query `c`.
```

2021-11-09 19:28 UTC, kayayarai approved these changes
💥

2021-11-09 20:05 UTC, merged