new docs for OAuth Apps management page
DataDog/documentation pull request #12187
Opened 2021-11-03 21:55 UTC by rzyxie

### What does this PR do?
Documentation for org OAuth Apps management page under Organization Settings 

<img width="1866" alt="org-management-page" src="https://user-images.githubusercontent.com/62684843/140198379-6cb65602-8eb5-451d-9149-8f1992344f14.png">

### Motivation
GA for org OAuth Apps management page as Datadog Apps feature is rolling out 

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-11-05 17:43 UTC, ruthnaebeck requested changes

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings.md
> +The [**OAuth Apps**][9] tab allows you to view or manage OAuth applications in your organization.
```suggestion
The [**OAuth Apps**][9] page allows you to view or manage OAuth applications in your organization. 
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings.md
> +[9]: /account_management/oauth_apps
I pushed a commit to re-arrange the page:
```suggestion
[9]: /account_management/org_settings/oauth_apps
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +The **OAuth Apps** management page in [Organization Settings][1] helps you manage and gain visibility into your organization’s OAuth applications, such as the scopes and permissions granted to an app
```suggestion
Use the **OAuth Apps** management page under [Organization Settings][1] to manage and gain visibility into your organization's OAuth applications, such as the scopes and permissions granted to an application and the users that have authorized access for it.
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +## Permissions
```suggestion
## Setup
### Permissions
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +
```suggestion

### Enable

OAuth applications include the Datadog Mobile App and your custom [Datadog Apps][2] that have [OAuth API Access][3]. 
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +## Disable an OAuth application
```suggestion
### Disable
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +Disabling OAuth access for an application revokes access to this application for all users in your organization. While the application remains installed, users are no longer able to use the applicati
```suggestion
Disabling OAuth access for an application revokes access to this application for all users in your organization. While the application remains installed, users are no longer able to use the application and are prompted with an error if they attempt to authorize it.
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +1. Hover over your application in the apps table to reveal the **Disable** button on the right-hand side of the row.
```suggestion
1. Hover over your application in the apps table to reveal the **Disable** button on the right side of the row.
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +2. Click on your application to open the detailed view of the application and reveal the **Disable Application** button.
```suggestion
2. Click on your application to open the detailed view of the application and click the **Disable Application** button.
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +**Note**: Enabled applications allow users with necessary permissions to grant it access on their behalf. When re-enabled, users that have previously authorized the application are required to re-aut
```suggestion
**Note**: Enabled applications allow users with necessary permissions to grant it access on their behalf. When re-enabled, users that previously authorized the application are required to re-authorize the application to regain access.
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +## Revoke OAuth access for a user
```suggestion
### Revoke access
```

2021-11-05 17:43 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +Revoking OAuth access to an application removes all access that a user has to the application. If the user has the required permissions to authorize the application, they can gain access again by re-
```suggestion
Revoking a user's OAuth access to an application removes all access to that application. If the user has the required permissions to authorize the application, they can regain access by re-authorizing it.
```

2021-11-05 20:23 UTC, ruthnaebeck commented on content/en/account_management/org_settings/oauth_apps.md
> +Enabled OAuth applications allow users with necessary permissions to authorize access on their behalf.  OAuth applications include the Datadog Mobile App and your custom [Datadog Apps][2] that have [
```suggestion
Enabled OAuth applications allow users with necessary permissions to authorize access on their behalf. OAuth applications include the Datadog Mobile App and your custom [Datadog Apps][2] that have [OAuth API Access][3]. 
```

2021-11-05 20:23 UTC, ruthnaebeck reviewed
👍

2021-11-05 20:23 UTC, ruthnaebeck approved these changes
👍

2021-11-09 18:45 UTC, cswatt approved these changes

2021-11-09 18:45 UTC, merged