cluster alert guide
DataDog/documentation pull request #12225
Opened 2021-11-09 14:13 UTC by NBParis

### What does this PR do?
Adds a guide to configure cluster alerts

### Motivation
It's pretty hacky but using min_cutoff and count_nonzero can get users what they want so adding a guide for them to look into a setup example was important. 

### Preview

https://docs-staging.datadoghq.com/nils/cluster-alert-guide/monitors/guide/create-cluster-alert/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-11-09 17:59 UTC, cswatt requested changes

2021-11-09 17:59 UTC, cswatt commented on content/en/monitors/guide/create-cluster-alert.md
> +* Divide one by the other to get the percentage of host with a high CPU
In this example, you want to receive a notification when 40 percent of hosts have a CPU usage above 50 percent. Leverage the `min_cutoff` and `count_nonzero` functions:

* Use the `min_cutoff` function to count the number of hosts that have CPU usage above 50 percent.
* Use the `count_nonzero` function to count the total number of hosts.
* Divide one by the other for the resulting percentage of hosts with CPU usage above 50 percent.

2021-11-09 17:59 UTC, cswatt commented on content/en/monitors/guide/create-cluster-alert.md
> +* Then set the condition to alert if the percentage of hosts in that condition reaches 40%
```suggestion
* Then, set the condition to alert if the percentage of hosts in that condition reaches 40 percent.
```

2021-11-09 17:59 UTC, cswatt commented on content/en/monitors/guide/create-cluster-alert.md
> +This monitor then track the percentage of host that have a CPU above 50% within the last 10 minutes and generate a notification if more than 40% of those hosts meet the condition.
```suggestion
This monitor tracks the percentage of host that have a CPU usage above 50 percent within the last ten minutes and generates a notification if more than 40 percent of those hosts meet the specified condition.
```

2021-11-10 12:40 UTC, NBParis commented
@ceciliawatt ready to merge when you are. Thanks for the updates

2021-11-16 23:16 UTC, apigirl approved these changes

2021-11-16 23:16 UTC, merged