zachG add UDS setup to Kubernetes trace collection docs
DataDog/documentation pull request #12258
Opened 2021-11-12 00:18 UTC by ZStriker19

### What does this PR do?
Add Unix domain socket configurations to the K8s Tracer setup docs

### Motivation
APM is moving towards using UDS as the default and we're more often recommending that to customers since it's more reliable than UDP. How to set this up is not entirely intuitive to customers.

### Preview

https://docs-staging.datadoghq.com/add-k8s-apm-uds-configs/agent/kubernetes ?

### Additional Notes
This is for Kari to review since we've chatted about it before.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-11-12 17:22 UTC, cswatt requested changes

2021-11-12 17:22 UTC, cswatt commented on content/en/agent/kubernetes/apm.md
> +To enable trace collection with your Agent, follow the instructions below. You can configure the agent to intake traces via UDP or Unix Domain Socket:
```suggestion
To enable trace collection with your Agent, follow the instructions below. You can configure the Agent to intake traces via UDP or Unix Domain Socket:
```

2021-11-12 17:22 UTC, cswatt commented on content/en/agent/kubernetes/apm.md
> +If sending traces to the agent via Unix Domain Socket you need to mount the directory the socket is in to the application container and specify the path with `DD_TRACE_AGENT_URL`.
```suggestion
If you are sending traces to the Agent by using Unix Domain Socket, mount the directory the socket is in to the application container and specify the path with `DD_TRACE_AGENT_URL`.
```

2021-11-12 17:22 UTC, cswatt commented on content/en/agent/kubernetes/apm.md
> +3. **Configure your application tracers to emit traces**: Point your application-level tracers to where the Datadog Agent host is using the environment variable `DD_APM_RECEIVER_SOCKET` or for Helm `
```suggestion
3. **Configure your application tracers to emit traces**: Point your application-level tracers to where the Datadog Agent host is using the environment variable `DD_APM_RECEIVER_SOCKET` or for Helm `apm.socketPath`. For Helm and Operator the default for this value is `"/var/run/datadog/apm.socket"`. Some tracers do not support Unix Domain Socket. Refer to the [language-specific APM instrumentation docs][3] to see if this is supported for your tracer.
```

2021-11-12 17:24 UTC, cswatt approved these changes

2021-11-15 19:30 UTC, kayayarai approved these changes

2021-11-15 19:31 UTC, merged