Updates to Security Platform landing pages
DataDog/documentation pull request #12286
Opened 2021-11-15 17:03 UTC by sarina-dd

### What does this PR do?
Updates all Security Platform landing pages to be more consistent with the current UI and add more context to each product area.

### Motivation
Clean-up prior to nav reorganization / new content

### Preview
https://docs-staging.datadoghq.com/sarina/security-landing-page/security_platform/
https://docs-staging.datadoghq.com/sarina/security-landing-page/security_platform/cloud_workload_security/
https://docs-staging.datadoghq.com/sarina/security-landing-page/security_platform/cspm/
https://docs-staging.datadoghq.com/sarina/security-landing-page/security_platform/security_monitoring/

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-11-18 22:05 UTC, jtappa requested changes

2021-11-18 22:05 UTC, jtappa commented on content/en/security_platform/cspm/_index.md
> +- **Security posture score**: Percentage of your environment that satisfies all of your active [Datadog’s OOTB rules][1]. Formula: `(# of evaluation:pass findings) / (total # of findings)`. Datadog t
```suggestion
- **Security posture score**: Percentage of your environment that satisfies all of your active [Datadog OOTB rules][1]. Formula: `(# of evaluation:pass findings) / (total # of findings)`. Datadog then weighs this formula by severity: low severity rules have a weighting of "1" and critical severity rules have a weighting of "5". This means critical severity rules impact scores five times more than low severity rules to put greater emphasis on the rules that pose greater security risk. The score is also normalized to treat all all resource types and resource volumes the same (for example, 500 failing containers are weighted the same as three failing S3 buckets in the computed score). This normalization factor allows scores to be comparable across your cloud accounts, without the risk that they are heavily skewed if one account has more containers, or another has fewer storage buckets.
```

2021-11-22 22:26 UTC, sarina-dd commented on content/en/security_platform/_index.md
> +[Cloud Workload Security (CWS)][5] monitors file and process activity across your environment to detect threats to your infrastructure, like AWS EC2 instances, and workloads, like Kubernetes clusters
Thanks for catching this! I'm changing it back to CWS as the team confirmed it's still CWS, just shows as `Workload Security` in app.

2021-11-22 22:30 UTC, sarina-dd reviewed
Updated instances of WS and PM

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cloud_workload_security/_index.md
> +title: Workload Security
```suggestion
title: Cloud Workload Security
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cloud_workload_security/_index.md
> +Datadog Workload Security detects threats to your production workloads in real-time. With Workload Security, monitor file and process activity across your environment to detect threats to your infras
```suggestion
Datadog Cloud Workload Security detects threats to your production workloads in real-time. With Cloud Workload Security, monitor file and process activity across your environment to detect threats to your infrastructure, like AWS EC2 instances, docker containers, or Kubernetes clusters, in real-time at the kernel level. Use **File Integrity Monitoring (FIM)** to watch for changes to key files and directories. Use **Process Execution Monitoring** to monitor process executions for suspicious, malicious, or anomalous activity.
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cloud_workload_security/_index.md
> +{{< img src="security_platform/cws/workload_security_rules.png" alt="Workload Security rules in the Datadog app" width="100%">}}
```suggestion
{{< img src="security_platform/cws/workload_security_rules.png" alt="Cloud Workload Security rules in the Datadog app" width="100%">}}
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cloud_workload_security/_index.md
> +Workload Security uses the Datadog Agent, so if you’re already using Datadog to monitor your environment, there’s no need to provision additional resources or introduce new agents. If you don't alrea
```suggestion
Cloud Workload Security uses the Datadog Agent, so if you’re already using Datadog to monitor your environment, there’s no need to provision additional resources or introduce new agents. If you don't already have the Datadog Agent set up, [start with setting up the Agent][1]. As a part of the Datadog platform, you can easily combine real-time threat detection with metrics, logs, traces, and other telemetry to see the full context surrounding a potential attack on your workloads.
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cloud_workload_security/_index.md
>    {{< nextlink href="/security_platform/cloud_workload_security/workload_security_rules">}}Learn about Workload Security rules{{< /nextlink >}}
```suggestion
  {{< nextlink href="/security_platform/cloud_workload_security/workload_security_rules">}}Learn about Cloud Workload Security rules{{< /nextlink >}}
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cloud_workload_security/_index.md
> +  {{< nextlink href="/security_platform/default_rules/#cat-workload-security">}}Start using out-of-the-box Workload Security rules{{< /nextlink >}}
```suggestion
  {{< nextlink href="/security_platform/default_rules/#cat-workload-security">}}Start using out-of-the-box Cloud Workload Security rules{{< /nextlink >}}
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cspm/_index.md
> +title: Posture Management
```suggestion
title: Cloud Security Posture Management
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cspm/_index.md
> +Datadog Posture Management makes it easier to assess and visualize the current and historic security posture of your cloud environment, automate audit evidence collection, and catch misconfigurations
```suggestion
Datadog Cloud Security Posture Management (CSPM) makes it easier to assess and visualize the current and historic security posture of your cloud environment, automate audit evidence collection, and catch misconfigurations that leave your organization vulnerable to attacks.
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cspm/_index.md
> +{{< img src="security_platform/cspm/getting_started/rules.png" alt="A list of Posture Management rules" style="width:65%;">}}
```suggestion
{{< img src="security_platform/cspm/getting_started/rules.png" alt="A list of Cloud Security Posture Management rules" style="width:65%;">}}
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cspm/_index.md
> +{{< img src="security_platform/cspm/getting_started/frameworks.png" alt="The frameworks overview in the Posture Management landing page" style="width:100%;">}}
```suggestion
{{< img src="security_platform/cspm/getting_started/frameworks.png" alt="The frameworks overview in the Cloud Security Posture Management landing page" style="width:100%;">}}
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cspm/_index.md
> +  {{< nextlink href="/security_platform/default_rules/#cat-cloud-configuration">}}Implement out-of-the-box Posture Management rules{{< /nextlink >}}
```suggestion
  {{< nextlink href="/security_platform/default_rules/#cat-cloud-configuration">}}Implement out-of-the-box Cloud Security Posture Management rules{{< /nextlink >}}
```

2021-11-22 22:30 UTC, sarina-dd commented on content/en/security_platform/cspm/_index.md
> +  {{< nextlink href="/security_platform/cspm/findings">}} Learn about Posture Management findings{{< /nextlink >}}
```suggestion
  {{< nextlink href="/security_platform/cspm/findings">}} Learn about Cloud Security Posture Management findings{{< /nextlink >}}
```

2021-11-22 23:45 UTC, sarina-dd commented on content/en/security_platform/security_monitoring/_index.md
> +[1]: /security_platform/security_monitoring/sucurity_home/
```suggestion
[1]: /security_platform/security_monitoring/security_home/
```

2021-11-30 22:14 UTC, jtappa approved these changes

2021-11-30 22:32 UTC, merged