docs: remove `source` from `addError` calls
DataDog/documentation pull request #12436
Opened 2021-11-30 09:05 UTC by alk-mandrianarijaona

this argument was removed at https://github.com/DataDog/browser-sdk/pull/936

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-12-01 19:18 UTC, jtappa requested changes
Suggestions based on our current examples in the english docs. Looks like there's at least one more instance that needs updating.

2021-12-01 19:18 UTC, jtappa commented on content/fr/real_user_monitoring/browser/collecting_browser_errors.md
> +    datadogRum.addError(error, undefined);
```suggestion
    datadogRum.addError(error);
```

2021-12-01 19:18 UTC, jtappa commented on content/fr/real_user_monitoring/browser/collecting_browser_errors.md
> +    datadogRum.addError(error, undefined);
```suggestion
    datadogRum.addError(error);
```

2021-12-02 08:18 UTC, alk-mandrianarijaona commented
thanks for that @jtappa

2021-12-02 17:54 UTC, jtappa approved these changes

2021-12-02 17:54 UTC, merged