[2022 key rotation docs] Recommend updating the install method
DataDog/documentation pull request #12559
Opened 2021-12-13 15:02 UTC by albertvaka

### What does this PR do?
Recommend updating the install method instead of trusting the
new key manually, since this will continue to work in the future.

### Preview
https://docs-staging.datadoghq.com/albertvaka/signing-keys-recommend-updating-install-method/agent/faq/linux-agent-2022-key-rotation

2021-12-13 16:19 UTC, sarina-dd requested changes

2021-12-13 16:19 UTC, sarina-dd commented on content/en/agent/faq/linux-agent-2022-key-rotation.md
> +We encourage users to use one of the install methods above which automatically trust the new GPG key, as they will also automatically fetch future keys as well. If this is not an option, these instru
```suggestion
Datadog encourages you to use one of the install methods above, which automatically trusts the new GPG key as it also automatically fetches future keys. If this is not an option, the following instructions also downloads and trusts the new key.
```

2021-12-13 17:41 UTC, albertvaka commented on content/en/agent/faq/linux-agent-2022-key-rotation.md
> +We encourage users to use one of the install methods above which automatically trust the new GPG key, as they will also automatically fetch future keys as well. If this is not an option, these instru
```suggestion
Datadog encourages you to use one of the install methods above, which trust the new GPG key as well as all future keys automatically. If this is not an option, the following instructions manually download and trust the new key.
```

2021-12-14 19:02 UTC, KSerrania approved these changes

2021-12-15 15:43 UTC, sarina-dd approved these changes

2021-12-15 15:44 UTC, merged