Add instructions for mitigating log4j vuln in datadog-lambda-java
DataDog/documentation pull request #12604
Opened 2021-12-16 16:45 UTC by agocs

### What does this PR do?

This adds an **Upgrading** section to the datadog-lambda-java installation instructions with an alert box discussing the log4j vulnerability and a description box with upgrade instructions. Also while I'm at it, I bump the latest dd-trace-java layer version to 4 (unrelated to log4j, just housekeeping).

### Motivation

### Preview

https://docs-staging.datadoghq.com/chris.agocs/add_log4j_mitigation_instructions/serverless/installation/java/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-12-16 20:18 UTC, ruthnaebeck requested changes
Docs review

2021-12-16 20:18 UTC, ruthnaebeck commented on content/en/serverless/installation/java.md
> +Find this section and change the `VERSION` to the latest release (omitting the preceeding `v`) ![Maven Cental][4]
```suggestion
Find this section and change the `VERSION` to the latest release (omitting the preceeding `v`) ![Maven Cental][1].
```

2021-12-16 20:18 UTC, ruthnaebeck commented on content/en/serverless/installation/java.md
> +
References have to go inside of tabs:
```suggestion
[1]: https://img.shields.io/maven-central/v/com.datadoghq/datadog-lambda-java
[2]: https://github.com/DataDog/datadog-lambda-java/releases
```

2021-12-16 20:18 UTC, ruthnaebeck commented on content/en/serverless/installation/java.md
> +Find this section and change the `VERSION` to the latest release (omitting the preceeding `v`) ![Maven Cental][4]
```suggestion
Find this section and change the `VERSION` to the latest release (omitting the preceeding `v`) ![Maven Cental][1].
```

2021-12-16 20:18 UTC, ruthnaebeck commented on content/en/serverless/installation/java.md
> +
References have to go inside of tabs:
```suggestion
[1]: https://img.shields.io/maven-central/v/com.datadoghq/datadog-lambda-java
[2]: https://github.com/DataDog/datadog-lambda-java/releases
```

2021-12-16 20:18 UTC, ruthnaebeck commented on content/en/serverless/installation/java.md
> +[13]: https://github.com/DataDog/datadog-lambda-java/releases
Remove `[13]` here if not used elsewhere

2021-12-16 21:24 UTC, agocs commented
Hi @ruthnaebeck , thank you very much for the review! I chose to move the bulk of the instructions to the bottom, leaving a red alert box at the top. I also moved the references so that they outside of the tabs, to preserve one references section at the bottom of the file (although it's good to know that references have to go inside of tabs, for the future!). Let me know if I missed anything!

2021-12-16 22:30 UTC, ruthnaebeck requested changes
Docs review 2

2021-12-16 22:30 UTC, ruthnaebeck commented on content/en/serverless/installation/java.md
> +There are versions of datadog-lambda-java that import log4j <=2.14.0 as a transitive dependency. Upgrade instructions are <a href="#upgrading">here</a>.
```suggestion
There are versions of datadog-lambda-java that import log4j <=2.14.0 as a transitive dependency. <a href="#upgrading">Upgrade instructions</a> are below. 
```

2021-12-16 22:30 UTC, ruthnaebeck commented on content/en/serverless/installation/java.md
> +Your `build.gradle` file contains a section like similar to the following:
```suggestion
Your `build.gradle` file contains a section similar to the following:
```

2021-12-17 15:07 UTC, agocs commented
Thank you for the second review!

2021-12-17 15:35 UTC, ruthnaebeck approved these changes

2021-12-17 15:36 UTC, merged