📝 [RUMF-1031] RUM browser: document technical limitations
DataDog/documentation pull request #12666
Opened 2021-12-23 10:49 UTC by bcaudan

### What does this PR do?

document dome RUM technical limitations

### Motivation

explain some potential event / request rejection

### Preview

https://docs-staging.datadoghq.com/bcaudan/limitation-doc/real_user_monitoring/browser/troubleshooting/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-12-23 21:02 UTC, ruthnaebeck requested changes
Docs review

2021-12-23 21:02 UTC, ruthnaebeck commented on content/en/real_user_monitoring/browser/troubleshooting.md
> +Each event sent by the Browser RUM SDK is built with:
```suggestion
Each event sent by the Browser RUM SDK is built with the following:
```

2021-12-23 21:02 UTC, ruthnaebeck commented on content/en/real_user_monitoring/browser/troubleshooting.md
> +- the RUM global context
```suggestion
- RUM global context
```

2021-12-23 21:02 UTC, ruthnaebeck commented on content/en/real_user_monitoring/browser/troubleshooting.md
> +- the event context (if any)
```suggestion
- Event context (if any)
```

2021-12-23 21:02 UTC, ruthnaebeck commented on content/en/real_user_monitoring/browser/troubleshooting.md
> +- the attributes specific to the event
```suggestion
- Attributes specific to the event
```

2021-12-23 21:02 UTC, ruthnaebeck commented on content/en/real_user_monitoring/browser/troubleshooting.md
> +It creates an action event:
```suggestion
The example code creates the following action event:
```

2021-12-23 21:02 UTC, ruthnaebeck commented on content/en/real_user_monitoring/browser/troubleshooting.md
> +If an event or a request go beyond any of the following limitations, it will be rejected by our intake.
```suggestion
If an event or a request goes beyond any of the following limitations, it is rejected by the Datadog intake.
```

2021-12-27 16:09 UTC, ruthnaebeck approved these changes
👍  for docs
post in #documentation or ping when you are ready to merge

2022-01-03 08:20 UTC, amortemousque approved these changes

2022-01-03 14:30 UTC, merged