Document running the OpenTelemetry Collector alongside the Datadog Agent
DataDog/documentation pull request #12668
Opened 2021-12-23 11:55 UTC by mx-psi

### What does this PR do?

Document our recommended approach when running the OpenTelemetry Collector alongside the Datadog Agent.

### Motivation

This approach avoids some issues that may happen when the host metadata from the Datadog Agent is inconsistent with the OpenTelemetry Collector.

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

Blocked by #12658

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-12-23 12:01 UTC, mx-psi commented
This is reviewable but merging it is blocked by #12658 (since I need to replace the "TODO" by an actual link)

2022-01-10 15:54 UTC, albertvaka commented on content/en/tracing/setup_overview/open_standards/_index.md
> +2. Define an OTLP exporter to your metrics and traces pipelines, pointing to the Datadog Agent endpoint. For example, if your Datadog Agent is listening on port 4317 and you are running on the same h
```suggestion
2. On the OpenTelemetry collector config, define an OTLP exporter pointing to the Datadog Agent endpoint. For example, if your Datadog Agent is listening on port 4317 and you are running on the same host, you may define the exporter as:
```

2022-01-10 15:54 UTC, albertvaka commented on content/en/tracing/setup_overview/open_standards/_index.md
> +3. Replace the Datadog exporter in your metrics and traces pipelines by the OTLP exporter.
```suggestion
3. On the OpenTelemetry collector config, replace uses of the Datadog exporter in your metrics and traces pipelines by the OTLP exporter.
```
Is there some example YAML we can provide for this point?

2022-01-11 18:00 UTC, albertvaka approved these changes
LGTM. Is there some example YAML we can provide for point 3, though?

2022-01-12 12:11 UTC, mx-psi commented
> Is there some example YAML we can provide for point 3, though?

Yes! Sorry, missed that. I added it in my last commit

2022-01-12 16:45 UTC, urseberry requested changes
Thanks, this looks great. I have just a couple of suggestions.

2022-01-12 16:45 UTC, urseberry commented on content/en/tracing/setup_overview/open_standards/_index.md
> +If running the OpenTelemetry Collector on a host with an existing Datadog Agent, replace the Datadog exporter by an OTLP exporter pointing to the Datadog Agent:
```suggestion
If running the OpenTelemetry Collector on a host with an existing Datadog Agent, replace the Datadog exporter with an OTLP exporter pointing to the Datadog Agent:
```

2022-01-12 16:45 UTC, urseberry commented on content/en/tracing/setup_overview/open_standards/_index.md
> +3. On the OpenTelemetry collector config, replace uses of the Datadog exporter in your metrics and traces pipelines by the OTLP exporter. For example, if you have one metrics and one traces pipeline
```suggestion
3. On the OpenTelemetry collector config, replace uses of the Datadog exporter in your metrics and traces pipelines with the OTLP exporter. For example, if you have one metrics and one traces pipeline with the Datadog exporter, use the following configuration:
```

2022-01-12 17:13 UTC, merged