Re-generate the sample kubernetes manifests from the Helm chart 2.28.11
DataDog/documentation pull request #12703
Opened 2021-12-31 15:26 UTC by L3n41c

### What does this PR do?

Regenerate the sample kubernetes manifests from the latest version of the Helm chart.

### Motivation

Keep those kubernetes manifests up-to-date

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

This PR has been fully generated by the execution of the [`generate.sh` script](https://github.com/DataDog/documentation/blob/master/static/resources/yaml/generate.sh).

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-01-03 22:14 UTC, maycmlee requested changes

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-apm.yaml
> +        # if the CRI or is not provived we should try to mount the default containerd pipe.
```suggestion
        # if the CRI is not provided, try to mount the default containerd pipe.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-apm.yaml
> +        # by default "datadog.dockerOrCriSocketPath" mount the docker pipe.
```suggestion
        # By default, "datadog.dockerOrCriSocketPath" mounts the Docker pipe.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-apm.yaml
> +        # so with this additional hostPath, by default both are mounted.
```suggestion
        # So with this additional hostPath, by default, both are mounted.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-logs-apm.yaml
> +        # if the CRI or is not provived we should try to mount the default containerd pipe.
```suggestion
        # If the CRI is not provided, try to mount the default containerd pipe.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-logs-apm.yaml
> +        # by default "datadog.dockerOrCriSocketPath" mount the docker pipe.
```suggestion
        # By default, "datadog.dockerOrCriSocketPath" mounts the Docker pipe.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-logs-apm.yaml
> +        # so with this additional hostPath, by default both are mounted.
```suggestion
        # So with this additional hostPath, by default, both are mounted.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-logs.yaml
> +        # if the CRI or is not provived we should try to mount the default containerd pipe.
```suggestion
        # If the CRI is not provided, try to mount the default containerd pipe.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-logs.yaml
> +        # by default "datadog.dockerOrCriSocketPath" mount the docker pipe.
```suggestion
        # By default, "datadog.dockerOrCriSocketPath" mounts the Docker pipe.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-logs.yaml
> +        # so with this additional hostPath, by default both are mounted.
```suggestion
        # So with this additional hostPath, by default, both are mounted.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-vanilla.yaml
> +        # if the CRI or is not provived we should try to mount the default containerd pipe.
```suggestion
        # if the CRI is not provided, try to mount the default containerd pipe.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-vanilla.yaml
> +        # by default "datadog.dockerOrCriSocketPath" mount the docker pipe.
```suggestion
        # By default, "datadog.dockerOrCriSocketPath" mounts the Docker pipe.
```

2022-01-03 22:14 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-vanilla.yaml
> +        # so with this additional hostPath, by default both are mounted.
```suggestion
        # So with this additional hostPath, by default, both are mounted.
```

2022-01-04 10:18 UTC, L3n41c commented
In order to avoid having the fixes being reverted at the next manifest generation, I’ve retrofitted the suggested changes upstream in DataDog/helm-charts#505.

2022-01-04 14:29 UTC, maycmlee approved these changes

2022-01-04 14:29 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-apm.yaml
> +        # if the CRI is not provided, try to mount the default containerd pipe.
```suggestion
        # If the CRI is not provided, try to mount the default containerd pipe.
```

2022-01-04 14:29 UTC, maycmlee commented on static/resources/yaml/datadog-agent-windows-vanilla.yaml
> +        # if the CRI is not provided, try to mount the default containerd pipe.
```suggestion
        # If the CRI is not provided, try to mount the default containerd pipe.
```

2022-01-06 14:29 UTC, merged