[DOCS-2983] mention admission controller in k8s section
DataDog/documentation pull request #12737
Opened 2022-01-06 16:07 UTC by anapsix

### What does this PR do?
Make sure to mention Datadog Admissions Controller's ability to mutate Pods, rendering manual configuration unnecessary.

### Motivation
Direct users looking to enable collection of metrics and APM traces in Kubernetes environment to relevant documentation, helping them avoid superfluous configuration.

### Preview
Not available

---

### Reviewer checklist
- [x] Review the changed files.
- [x] Review the URLs listed in the [Preview](#preview) section.
- [x] Check images for PII
- [x] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-01-06 16:19 UTC, ruthnaebeck requested changes

2022-01-06 16:19 UTC, ruthnaebeck commented on content/en/getting_started/tagging/unified_service_tagging.md
> +**Note**: If you deployed Datadog Cluster Agent with [Admission Controller][14] enabled, the Admission Controller will mutate the Pod manifests and inject all required environment variables (based on
```suggestion
**Note**: If you deployed the Datadog Cluster Agent with [Admission Controller][14] enabled, the Admission Controller mutates the pod manifests and injects all required environment variables (based on configured mutation conditions). In that case, manual configuration of `DD_` environment variables in pod manifests is unnecessary. See the [Admission Controller][14] documentation for more details.
```

2022-01-06 21:56 UTC, ruthnaebeck approved these changes
lgtm

2022-06-21 19:26 UTC, jtappa approved these changes

2022-06-21 19:27 UTC, merged

2022-06-21 19:28 UTC, jtappa commented
Hi @anapsix, thanks so much for your contribution to our Docs!
![high-five-dog-high-five-xiteb](https://user-images.githubusercontent.com/605271/174882112-b99a1c25-575b-478b-8b13-16fe870ee647.gif)