Chrisnas/docs 2799 dotnet profiler
DataDog/documentation pull request #12736
Opened 2022-01-06 14:47 UTC by chrisnas

### What does this PR do?
Add support for .NET Profiler

### Motivation
Beta coming soon

### Preview
https://docs-staging.datadoghq.com/chrisnas/docs-2799-dotnet-profiler/tracing/profiler/enabling/dotnet/?tab=windows

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-01-07 22:41 UTC, kayayarai approved these changes

2022-01-11 19:04 UTC, dbenamydd commented on content/en/tracing/profiler/enabling/dotnet.md
> +1. Set environment variables:
We still want to suggest setting env, maybe service, and version for an optimal experience, so should include that here even though the installer sets the "enable the profiler" env vars.

2022-01-11 19:04 UTC, dbenamydd commented on content/en/tracing/profiler/enabling/dotnet.md
> +| Environment variable                             | Type          | Description                                                                                      |
Gotcha. Which tracer doc are you comparing with? I think there are a couple.

2022-01-11 19:06 UTC, dbenamydd commented on content/en/tracing/profiler/enabling/dotnet.md
> +2. Download the [.NET Monitoring MSI installer][1] version TODO+. Continuous Profiler only supports 64-bit, with 32-bit support coming soon.
We do this in other language pages so if, in the future, an apm user wants to enable profiling, if they're already running a new enough version, they can skip this step. There are pros and cons to this but if we want to get rid of it should do it for all languages.

2022-01-11 19:07 UTC, dbenamydd commented on content/en/tracing/profiler/enabling/dotnet.md
> + TODO show example batch file
Thanks!

2022-01-11 19:44 UTC, kayayarai requested changes

2022-01-11 19:44 UTC, kayayarai commented on content/en/tracing/profiler/enabling/dotnet.md
> +  <strong>Note:</strong> Datadog's.NET Tracer and Profiler rely on the .NET CLR Profiling API. This API allows only one subscriber (for example, APM). To ensure maximum visibility, run only one APM s
```suggestion
  <strong>Note:</strong> Datadog's .NET Tracer and Profiler rely on the .NET CLR Profiling API. This API allows only one subscriber (for example, APM). To ensure maximum visibility, run only one APM solution in your application environment.
```

2022-01-11 19:44 UTC, kayayarai commented on content/en/tracing/profiler/enabling/dotnet.md
> +2. A minute or two after starting your application, your profiles will show up on the [Datadog APM > Profiler page][1].
```suggestion
2. A minute or two after you start your application, your profiles appear on the [Datadog APM > Profiler page][1].
```

2022-01-11 19:44 UTC, kayayarai commented on content/en/tracing/profiler/enabling/dotnet.md
> +   If the environment variables are set for the current user, _all_ .NET applications will be profiled. Instead, we recommend setting them in a batch file that also starts the application and running
```suggestion
   If the environment variables are set for the current user, _all_ .NET applications are profiled. Instead, set them in a batch file that also starts the application, and run the batch file.
```

2022-01-11 19:44 UTC, kayayarai commented on content/en/tracing/profiler/enabling/dotnet.md
> +2. A minute or two after starting your application, your profiles will show up on the [Datadog APM > Profiler page][1].
```suggestion
2. A minute or two after you start your application, your profiles appear on the [Datadog APM > Profiler page][1].
```

2022-01-11 19:44 UTC, kayayarai commented on content/en/tracing/profiler/enabling/dotnet.md
> +| `DD_TRACE_AGENT_PORT`      | String        | Sets the port where profiles are sent (the port where the Agent is listening for connections). Ignored if `DD_TRACE_AGENT_URL` is set. Defaults to`8126`
```suggestion
| `DD_TRACE_AGENT_PORT`      | String        | Sets the port where profiles are sent (the port where the Agent is listening for connections). Ignored if `DD_TRACE_AGENT_URL` is set. Defaults to`8126`.  |
```

2022-01-11 19:48 UTC, kayayarai commented on content/en/tracing/profiler/enabling/dotnet.md
> +2. The profiler and tracer are shipped together. Install or upgrade to version TODO+ if needed, using the [.NET Monitoring MSI installer][3]. Continuous Profiler only supports 64-bit Windows, with 32
Commenting here to make sure we don't merge without fixing this TODO.

2022-01-21 17:59 UTC, kayayarai requested changes

2022-01-21 17:59 UTC, kayayarai commented on content/en/tracing/profiler/enabling/dotnet.md
> +2. The profiler ships together with the tracer. Install or upgrade to the last beta version if needed, using the [.NET Monitoring MSI installer][3]. Continuous Profiler only supports 64-bit Windows,
```suggestion
2. The profiler ships together with the tracer. Install or upgrade to the last beta version if needed, using the [.NET Monitoring MSI installer][3]. Continuous Profiler only supports 64-bit Windows, so you need the file like `datadog-dotnet-apm-2.1.0-x64-profiler-beta.msi`.
```

2022-01-21 17:59 UTC, kayayarai commented on content/en/tracing/profiler/enabling/dotnet.md
> +**Note**: Profiling requires the .msi version 2.1
```suggestion
**Note**: Profiling requires the `.msi` version 2.1.
```

2022-01-27 17:18 UTC, kayayarai commented on content/en/tracing/profiler/enabling/dotnet.md
> +1. Set needed environment variables to configure and enable Profiler for a non-service application, such as console, ASP.NET (Core), Windows Forms, or WPF. You can do this machine-wide, user-wide, or
```suggestion
1. Set needed environment variables to configure and enable Profiler for a non-service application, such as console, ASP.NET (Core), Windows Forms, or WPF. You can do this machine-wide, user-wide, or just for your service. The recommended way to do this is in a batch file that also starts the application, and to run your application using the batch file.
```

2022-01-27 17:34 UTC, kayayarai approved these changes

2022-01-27 20:18 UTC, kayayarai commented on content/en/tracing/profiler/_index.md
> +To get notified when a private beta is available for the **PHP** Profiler, complete the [Continuous Profiler - Product Access Request form][1].
```suggestion

```

2022-01-27 21:47 UTC, merged