Add install instructions for macOS
DataDog/documentation pull request #12733
Opened 2022-01-06 09:10 UTC by fredrikaverpil

### What does this PR do?

- Add ability to run datadog agent directly on macOS.

### Motivation

When setting up reporting from our apps into DD at work, I had issues getting this to work on my macOS (M1) laptop. I resorted to running an Ubuntu VM, where the datadog-agent worked straight away as expected. 

After reaching out to you [in Slack](https://datadoghq.slack.com/archives/C4JREERCY/p1640010574176000) and after having tinkered on my own, which finally got the datadog-agent to run as expected in macOS without the use of a VM, I figured the docs could need some updating to help others who are attempting the same thing.

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

One concern I have is I am not sure exactly if the `/var/lib/docker/containers` mount actually works on macOS, as I haven't attempted to make use of it. Perhaps this path also must be entered into Docker Desktop's settings under Resources/File Sharing?

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-01-06 16:02 UTC, ruthnaebeck requested changes

2022-01-06 16:02 UTC, ruthnaebeck commented on content/en/agent/docker/log.md
> +Note: Add the path `/opt/datadog-agent/run` under Docker Desktop -> Settings -> Resources -> File sharing.
```suggestion
Add the path `/opt/datadog-agent/run` under Docker Desktop -> Settings -> Resources -> File sharing.
```

2022-01-06 21:56 UTC, ruthnaebeck approved these changes
lgtm

2022-01-07 08:35 UTC, fredrikaverpil commented
@ruthnaebeck thanks for reviewing :) I noticed something went wrong with the CI checks.

2022-02-14 14:55 UTC, fredrikaverpil commented
@ruthnaebeck @cswatt ☝️

2022-02-15 22:14 UTC, cswatt approved these changes

2022-02-15 22:16 UTC, cswatt commented
this looks good @fredrikaverpil !

2022-02-15 22:16 UTC, merged