Update CWS rules docs to reflect rule split
DataDog/documentation pull request #12741
Opened 2022-01-06 23:50 UTC by sarina-dd

### What does this PR do?
Updates the CWS rules documentation to reflect upcoming changes, which includes a new Agent Configuration tab in Setup and Configuration.

### Motivation
Jira request

### Preview
https://docs-staging.datadoghq.com/sarina/cws-rule-split/content/en/security_platform/cloud_workload_security/workload_security_rules

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-01-10 22:26 UTC, alai97 requested changes

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +To finalize setup, restart the [Datadog Agent][5].
```suggestion
To finalize your setup, restart the [Datadog Agent][5].
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +2. Select **Workload Security** under **Rule types**. Select a detection method, such as **Threshold** or **New Term**.
```suggestion
2. Select **Workload Security** under **Rule types**. Select a detection method such as **Threshold** or **New Term**.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +6. Click Download Workload Security Policy in the top right corner to download a default policy file to your local machine.
```suggestion
6. Click **Download Workload Security Policy** in the top right corner to download a default policy file to your local machine.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +5. Save the rule. This automatically navigates you back to the Rules page.
```suggestion
5. Save the rule. This automatically navigates you back to the **Rules** page.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +4. Define the Agent expression. Enter the rule in the Expression field using Datadog Security Language (SECL).
```suggestion
4. Define the Agent expression by entering the rule in the **Expression** field with Datadog Security Language (SECL).
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +2. Click **Add an Agent Rule** in the top right.
```suggestion
2. Click **Add an Agent Rule** in the top right.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +1. In Datadog, navigate to the [Agent Configuration page][4] under Setup and Configuration.
```suggestion
1. In Datadog, navigate to the [Agent Configuration page][4] under **Setup & Configuration**.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +First, create a new default policy file to load to the Agent by following the instructions below.
"New" is redundant when we talk about creating (new) things.

```suggestion
### Create a default policy file

First, create a default policy file to load to the Agent by following the instructions below.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +**Note**: `[event_type]` can be open or exec, for example.
Do you think "exec" as an executable command should be in monospace here? Feel free to discard this suggestion.

```suggestion
**Note**: `[event_type]` can be open or `exec`, for example.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +An Agent Rule contains the [Agent Expression][2], which determines which activity to collect from the Agent. These collected events are then evaluated based on patterns of events described in a [rule
```suggestion
An Agent Rule contains [Agent Expressions][2] that determine which activities the Agent collects. These captured events are then evaluated based on patterns of events described in a [rule][3]. 

A full set of rules for the Agent is called a policy. Datadog provides you with several [out-of-the-box CWS Agent rules][1] in the default policy.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +With Cloud Workload Security (CWS) enabled, the Datadog Agent actively monitors system activity and evaluates it against a set of rules to detect suspicious behavior. Datadog provides [bundled CWS Ag
```suggestion
With Cloud Workload Security (CWS) enabled, the Datadog Agent actively monitors system activity and evaluates it against a set of rules to detect suspicious behavior. 

When you upgrade the Datadog Agent, you receive [bundled CWS Agent rules][1]. You can also write your own custom Agent rules. This guide covers Agent rules and how to create them.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +1. Create a configmap containing `default.policy`. For example, `kubectl create configmap jdefaultpol --from-file=default.policy`.
```suggestion
1. Create a ConfigMap containing `default.policy`. For example, `kubectl create configmap jdefaultpol --from-file=default.policy`.
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +2. Add the configMap (`jdefaultpol`) into `values.yaml` with `datadog.securityAgent.runtime.policies.configMap`:
```suggestion
2. Add the ConfigMap (`jdefaultpol`) into `values.yaml` with `datadog.securityAgent.runtime.policies.configMap`:
```

2022-01-10 22:26 UTC, alai97 commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +3. Upgrade the helm chart with `helm upgrade <RELEASENAME> -f values.yaml --set datadog.apiKey=<APIKEY> datadog/datadog`.
```suggestion
3. Upgrade the Helm chart with `helm upgrade <RELEASENAME> -f values.yaml --set datadog.apiKey=<APIKEY> datadog/datadog`.
```

2022-01-12 19:48 UTC, rishi-ilangomaran commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
>  Use wildcards (`*`) carefully. For example, never use `open.file.path =~ "*/myfile"`. If you must use wildcards prefixing directories, at least two levels are required: `open.file.path =~ "*/mydir/my
Can we add an explanation on why we don't recommend using wildcards - ie. can cause name conflict and ambiguities

2022-01-12 19:54 UTC, rishi-ilangomaran commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +When you upgrade the Datadog Agent, you receive [bundled CWS Agent rules][1]. You can also write your own custom Agent rules. This guide covers Agent rules and how to create them.
When you upgrade the Datadog Agent, you receive bundled CWS Agent rules used in our [default Signal Rules ](https://docs-staging.datadoghq.com/sarina/cws-rule-split/security_platform/default_rules/#cat-workload-security). You can also write your own custom Agent rules. This guide covers Agent rules, how to create them, and how to use them to generate security signals.

2022-01-12 19:57 UTC, rishi-ilangomaran commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +When you upgrade the Datadog Agent, you receive [bundled CWS Agent rules][1]. You can also write your own custom Agent rules. This guide covers Agent rules and how to create them.
The URL is changed to filter by CWS rules

2022-01-12 19:57 UTC, rishi-ilangomaran commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +A full set of rules for the Agent is called a policy. Datadog provides you with several [out-of-the-box CWS Agent rules][1] in the default policy.
A full set of rules for the Agent is called a policy. Datadog provides you with several [out-of-the-box CWS Agent](https://docs-staging.datadoghq.com/sarina/cws-rule-split/security_platform/default_rules/#cat-workload-security) Rules powered by the default Agent policy

2022-01-12 20:47 UTC, sarina-dd commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +When you upgrade the Datadog Agent, you receive [bundled CWS Agent rules][1]. You can also write your own custom Agent rules. This guide covers Agent rules and how to create them.
```suggestion
When you upgrade the Datadog Agent you receive bundled CWS Agent rules, which are used in the [default signal rules][1]. You can also write your own custom Agent rules. This guide covers Agent rules, how to create them, and how to use them to generate security signals.
```

2022-01-12 20:48 UTC, sarina-dd commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +[1]: /security_platform/default_rules
```suggestion
[1]: /security_platform/default_rules/#cat-workload-security
```

2022-01-12 20:48 UTC, sarina-dd commented on content/en/security_platform/cloud_workload_security/workload_security_rules.md
> +A full set of rules for the Agent is called a policy. Datadog provides you with several [out-of-the-box CWS Agent rules][1] in the default policy.
```suggestion
A full set of rules for the Agent is called a policy. Datadog provides you with several [out-of-the-box CWS Agent rules][1] powered by the default Agent policy.
```

2022-01-12 20:51 UTC, sarina-dd commented
@rishi-ilangomaran Updated based on the notes, thanks for adding! If there are anymore edits, let me know. If not, we can push to final review + merge.

2022-01-13 03:23 UTC, alai97 approved these changes

2022-01-24 15:59 UTC, rishi-ilangomaran approved these changes
LGTM - can this be merged as early as possible on Tuesday 25th, 2021

2022-01-25 15:26 UTC, merged