Uchen/event migration
DataDog/documentation pull request #12933
Opened 2022-01-27 20:05 UTC by urseberry

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-02-10 19:33 UTC, sguyon commented on content/en/events/guides/migrating_to_new_events_features.md
> +Datadog is responsible for migrating data stored in its servers. You do not need to take any action for configuration stored directly in Datadog. Datadog automatically migrates Event data contained i
to precise:

1) legacy event monitors will be duplicated:
- new monitors based on the new query will be created and automatically enabled.
- existing monitors will be muted. A "(legacy)" prefix will be added to distinguish them.
You can filter the 2 monitor types using the "Event Migration" facet in the monitors list: https://a.cl.ly/rRuNAgm1

SLO and downtimes links will also be updated to point to the new monitors.

2) dashboard widgets using event queries will directly updated.
No new dashboard will be created

2022-02-10 19:33 UTC, sguyon commented on content/en/events/guides/migrating_to_new_events_features.md
> +### Datadog migrates data stored in Datadog servers
I'd switch the 2 sections are be more precise.
Something along the line of:
1. Monitor and dashboards definitions stored on Datadog servers are automatically updated (no action required)
2. Definitions stored externally (Terraform or API-based configuration tools must update) must be updated (your action is required)

2022-02-10 19:35 UTC, sguyon commented on content/en/events/guides/migrating_to_new_events_features.md
>  ## What this means for your organization
This will slightly change (details still TBD - please ask #event-migration if no updates in the next days)

2022-02-10 19:35 UTC, sguyon commented on content/en/events/guides/migrating_to_new_events_features.md
> +The introduction of the Events Explorer and its associated changes means that Event features work similarly to other Datadog products. Event query syntax, explorer and analytics views, processing pip
To add timeline in intro with sunset date (final date still TBD)

2022-02-15 19:04 UTC, isaacdd commented on content/en/events/guides/migrating_to_new_events_features.md
> +You do not need to take any action for configuration stored directly in Datadog.
You do not need to take any action for any dashboards or monitors created via Datadog.

2022-02-15 19:04 UTC, isaacdd commented on content/en/events/guides/migrating_to_new_events_features.md
> +Datadog is responsible for migrating data stored in its servers. You do not need to take any action for configuration stored directly in Datadog. The changes to Event query syntax affect two Datadog
same as above. maybe remove this paragraph.

2022-02-15 19:08 UTC, isaacdd commented on content/en/events/guides/migrating_to_new_events_features.md
> +Datadog directly migrates dashboard widgets that use Event queries. Datadog does not create any new dashboards or widgets.
Perhaps add more details after the first sentence: This includes Event Stream, Event Timeline widgets and event overlays in other widgets.

2022-02-15 23:35 UTC, isaacdd approved these changes

2022-02-16 17:13 UTC, urseberry commented
Ready for docs team editorial review.

2022-02-16 17:46 UTC, kayayarai requested changes
A few little edits. :)

2022-02-16 17:46 UTC, kayayarai commented on content/en/events/guides/migrating_to_new_events_features.md
> +- Update all SLOs and monitor downtimes that reference the legacy Event monitor to point to the new monitor.
```suggestion
- For each legacy Event monitor, creates a duplicate that uses the new query syntax. Enables the new monitor.
- Adds the prefix "legacy" to the legacy Event monitor, and mutes it.
- Updates all SLOs and monitor downtimes that reference the legacy Event monitor to point to the new monitor.
```

2022-02-16 17:46 UTC, kayayarai commented on content/en/events/guides/migrating_to_new_events_features.md
> +When viewing monitors, you can filter which of the two monitor types you would like to see using the **Event Migration** facet. This facet has available values "Event Monitors V1" and "Event Monitors
```suggestion
When viewing monitors, you can filter which of the two monitor types you would like to see using the **Event Migration** facet. This facet has available values `Event Monitors V1` and `Event Monitors V2`.
```

2022-02-16 17:46 UTC, kayayarai commented on content/en/events/guides/migrating_to_new_events_features.md
> +### User impact
```suggestion
### Impact
```

2022-02-16 20:06 UTC, urseberry commented
Thanks, Kari! I applied your suggestions.

2022-02-16 21:01 UTC, kayayarai approved these changes

2022-02-16 21:02 UTC, merged