(DOCS-3043) initial appsec guide commit
DataDog/documentation pull request #13053
Opened 2022-02-08 19:47 UTC by jtappa

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/jorie/DOCS-3043/security_platform/guide/how-appsec-works/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-02-09 14:12 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Application Security includes over 100 OOTB detection rules that help safegaurd against many different kinds of attacks, including the following:
safeguard?

2022-02-09 14:16 UTC, arnaudbreton requested changes

2022-02-09 14:16 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +## Attack types
Coverage

2022-02-09 14:16 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Signals are automatically created when Datadog detects meaningful attacks targeting your production services. It provides you with visibility on the attackers and the targeted services. You can set m
Security Signals

2022-02-09 14:16 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Signals are automatically created when Datadog detects meaningful attacks targeting your production services. It provides you with visibility on the attackers and the targeted services. You can set m
Monitors > Custom Detection rules

2022-02-09 14:16 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +* Sever-side Request Forgery (SSRF)
Full source, see the type facet in the AppSec configuration page https://app.datadoghq.com/security/appsec/event-rules

Feel free to link to this

2022-02-09 14:16 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +## Overview
Worth highlighting it relies on the same Library than is used by the APM suite, thus not requiring teams to deploy and maintain yet another one

2022-02-09 14:16 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Application Security categorizes these attacks into different threat types and notifies Datadog services such as monitors and events, based on your settings.
Not sure what this paragraph aims to describe

2022-02-09 14:16 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +* A **Vulnerability is triggered** when there is a correlation between attack patterns, and there's evidence of a successful vulnerability trigger.
Should go above imho

2022-02-18 16:38 UTC, jtappa commented on content/en/security_platform/guide/how-appsec-works.md
> +### Data Privacy
```suggestion
### Data privacy
```

2022-02-28 19:10 UTC, arnaudbreton requested changes

2022-02-28 19:10 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +APM records information about each HTTP request, these are referred to as traces. Application security uses the information APM is already collecting, and flags any suspicious requests or attack atte
attack attempt is what we detect. "suspicious" is how Application Security qualifies a request where such attempts has been detected

2022-02-28 19:10 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +APM records information about each HTTP request, these are referred to as traces. Application security uses the information APM is already collecting, and flags any suspicious requests or attack atte
> Depending on your settings and the severity of the attempt, you can receive notifications from Slack, email, or PagerDuty.

Not attack attempt level, only Security Signals can alert, as they aggregate multiple traces and detect attacks impacting production systems

2022-02-28 19:10 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Traditional Web Application Firewalls (WAFs) are usually deployed at the perimeter and have no context of the application behavior. For Application Security to be effective, it’s critical to be embed
> For Application Security to be effective
Confusing if about the domain or Datadog product. Maybe use lower-case and always refer to the product as "Datadog Application Security"?

> Application Security provides WAF-like capabilities with additional application context and lower false positives.
Application Security leverages known attack patterns like WAF and leverage the execution context to increase the signal/noise ratio, i.e reduce false positives

2022-02-28 19:10 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +### Performance
Good to mention that the additional processing is done platform-wise. All what is done on the service-side is matching the attack patterns

2022-02-28 19:10 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Application Security only scans HTTP request headers, it does not scan the body.
Not true anymore, some libraries do scan the body now

2022-02-28 19:10 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Datadog uses multiple pattern sources, including the [OWASP ModSecurity Core Rule Set][6] to detect known threats and vulnerabilities in HTTP requests. When an HTTP request matches one of those rules
> When an HTTP request matches one of those rules, a security signal is generated in Datadog.
Only when one of the OOTB detection rules match. Otherwise it'd be too noisy

2022-02-28 19:10 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Security Signals are automatically created when Datadog detects meaningful attacks targeting your production services. It provides you with visibility on the attackers and the targeted services. You
Link to OOTB rules for Application Security

2022-02-28 19:10 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Application Security includes over 100 OOTB detection rules that help protect against [many different kinds of attacks][7], including the following:
100 attack patterns. Detection rule is another thing

2022-02-28 19:10 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> + Application Security identifies Log4Shell attack payloads and provides visibility into vulnerable apps that attempt to remotely load malicious code. When used in tandem with the rest of [Datadog's S
> Log4Shell attack payloads
Log4j Log4Shell attack payloads

> visibility into vulnerable apps
vulnerable Java web services

> When used in tandem with the rest of [Datadog's Security Platform][8]
More specifically Datadog Cloud Workload Security here

2022-03-09 09:11 UTC, arnaudbreton requested changes

2022-03-09 09:11 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +APM records information about each HTTP request, these are referred to as traces. Datadog Application Security uses the information APM is already collecting, and flags any attack attempts based on s
> Datadog Application Security uses the information APM is already collecting, and flags any attack attempts based on suspicious requests as security signals

Still not accurate as a Security Signals is an aggregation of suspicious requests.

A Suspicious requests is a trace where security activity - today attack attempts - have been flagged.

2022-03-09 09:11 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Datadog Application Security uses processes already contained in the Agent and APM, so there are no performance implications when using it. Datadog Application Security collects and enriches trace da
> Datadog Application Security collects and enriches trace data from APM. It doesn't require extra overhead for processes like analyzing attack attempts, because it matches against known patterns and flags them. All processing is done platform-side, after traces have been flagged.

- When APM is enabled, the Datadog Library generates Distributed Traces
- Datadog Application Security flags security activity in traces - today attack attempts using known attack patterns. This adds no overhead and no traffic redirection
- Then, platform-wise, the correlation between the attack patterns and the execution context provided by the distributed trace is performed enabling to detect security signals based on detection rules (OOTB, custom)

2022-03-09 09:11 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +* **Unqualified attacks** match inbound HTTP requests with known attack patterns, but don't have any correlation to the business-logic.
* **Unqualified attacks** match inbound HTTP requests with known attack patterns. No correlation with the service's business-logic was found after correlating with the execution context provided by the trace

2022-03-09 09:11 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +* **Contextualized attacks** have a correlation between known attack patterns and business-logic.
* **Contextualized attacks** the attack attempts performed on the service was correlated with a matching business-logic. For example, SQL injection patterns on a service performing SQL statements

2022-03-09 09:11 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +The [Sensitive Data Scanner][5] automatically scans traces that have been flagged by Datadog Application Security.
Double-checked with the team. Not released yet

2022-03-09 09:11 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +* A **Vulnerability is triggered** when there is a correlation between attack patterns, and there's evidence of a successful vulnerability trigger.
* **Vulnerability is triggered** evidences of a vulnerability successfully being exploited have been found after matching known attack patterns

2022-03-09 09:11 UTC, arnaudbreton commented on content/en/security_platform/guide/how-appsec-works.md
> +Datadog Application Security includes over 100 attack patterns that help protect against [many different kinds of attacks][8], including the following:
Datadog Application Security includes over 100 attack patterns that help protect against [many different kinds of attacks][8], covering the following _vulnerabilities_:

2022-03-17 20:10 UTC, jtappa commented on content/en/security_platform/guide/how-appsec-works.md
> +Datadog Application Security includes over 100 attack patterns that help protect against [many different kinds of attacks][8], including the following:
```suggestion
Datadog Application Security includes over 100 attack patterns that help protect against [many different kinds of attacks][8], including the following vulnerabilities:
```

2022-03-17 20:11 UTC, jtappa commented on content/en/security_platform/guide/how-appsec-works.md
> +The [Sensitive Data Scanner][5] automatically scans traces that have been flagged by Datadog Application Security.
```suggestion
```

2022-03-17 20:13 UTC, jtappa commented on content/en/security_platform/guide/how-appsec-works.md
> +APM records information about each HTTP request, these are referred to as traces. Datadog Application Security uses the information APM is already collecting, and flags any attack attempts based on s
```suggestion
APM records information about each HTTP request, these are referred to as traces. Datadog Application Security uses the information APM is already collecting, and flags any attack attempts based or suspicious requests that match known attack patterns. Security signals are an aggregation of suspicious requests. Depending on your security signal settings, you can receive notifications from Slack, email, or PagerDuty.
```

2022-03-24 17:57 UTC, sarina-dd reviewed
Editorial Review completed

2022-03-24 17:57 UTC, sarina-dd commented on content/en/security_platform/guide/how-appsec-works.md
> +Datadog Application Security uses processes already contained in the Agent and APM, so there are no performance implications when using it. Datadog Application Security collects and enriches trace da
```suggestion
Datadog Application Security uses processes already contained in the Agent and APM, so there are no performance implications when using it. When APM is enabled, the Datadog Library generates distributed traces. Datadog Application Security flags security activity in traces by using known attack patterns. Correlation between the attack patterns and the execution context provided by the distributed trace triggers security signals based on detection rules.
```

2022-03-24 17:57 UTC, sarina-dd commented on content/en/security_platform/guide/how-appsec-works.md
> +* **Unqualified attacks** match inbound HTTP requests with known attack patterns, but don't have any correlation to the business-logic.
```suggestion
* **Unqualified attacks** match inbound HTTP requests with known attack patterns. For example, no correlation with the service's business-logic is found after correlating with the execution context provided by the trace.
```

2022-03-24 17:57 UTC, sarina-dd commented on content/en/security_platform/guide/how-appsec-works.md
> +* **Contextualized attacks** have a correlation between known attack patterns and business-logic.
```suggestion
* **Contextualized attacks** correlate the attack attempts performed on the service with a matching business-logic. For example, SQL injection patterns on a service performing SQL statements.
```

2022-03-24 17:57 UTC, sarina-dd commented on content/en/security_platform/guide/how-appsec-works.md
> +title: How Application Security works in Datadog
```suggestion
title: How Application Security Works in Datadog
```

2022-03-24 17:57 UTC, sarina-dd commented on content/en/security_platform/guide/how-appsec-works.md
> +APM records information about each HTTP request, these are referred to as traces. Datadog Application Security uses the information APM is already collecting, and flags any attack attempts based or s
```suggestion
APM records information about each HTTP request, referred to as traces. Datadog Application Security uses the information APM is already collecting, and flags attack attempts based on suspicious requests that match known attack patterns. Security signals are an aggregation of suspicious requests. Depending on your security signal settings, you can receive notifications from Slack, email, or PagerDuty.
```

2022-03-24 17:57 UTC, sarina-dd commented on content/en/security_platform/guide/how-appsec-works.md
> +Traditional Web Application Firewalls (WAFs) are usually deployed at the perimeter and have no context of the application behavior. For application security to be effective, it’s critical to be embed
```suggestion
Traditional Web Application Firewalls (WAFs) are usually deployed at the perimeter and have no context of the application behavior. For Application Security to be effective, it must be embedded in the application to get access to the data. Datadog Application Security leverages known attack patterns, similar to a Web Application Firewall (WAF) but with additional application context to increase the signal to noise ratio, lowering false positives.
```

2022-03-24 17:57 UTC, sarina-dd commented on content/en/security_platform/guide/how-appsec-works.md
> +For Datadog Application Security to be compatible with your Datadog configuration, you must have APM enabled, and [send traces to Datadog][1]. It uses the same libraries used by the APM suite, so you
```suggestion
For Datadog Application Security to be compatible with your Datadog configuration, you must have APM enabled, and [send traces to Datadog][1]. Application Security uses the same libraries used by APM, so you don't need to deploy and maintain another library. Steps to enable Datadog Application Security are specific to runtime language. Check to see if your language is supported in the [Application Security prerequisites][2].
```

2022-03-24 20:21 UTC, sarina-dd approved these changes

2022-03-24 21:30 UTC, merged