Warn serverless forwarder users
DataDog/documentation pull request #13055
Opened 2022-02-08 22:10 UTC by tianchu

### What does this PR do?
Make the warning message (what's originally in the first paragraph) more prominent. Apparently some new users have missed it and ended up following this guide to set up instrumentation using the Forwarder (instead of the recommended Extension). 

### Motivation
Customer feedback.

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-02-08 23:19 UTC, alai97 requested changes
Copy nits!

2022-02-08 23:19 UTC, alai97 commented on content/en/serverless/guide/datadog_forwarder_java.md
>  {{< img src="serverless/java-lambda-tracing.png" alt="Monitor Java Lambda Functions with Datadog" style="width:100%;">}}
```suggestion

## Overview

{{< img src="serverless/java-lambda-tracing.png" alt="Monitor Java Lambda Functions with Datadog" style="width:100%;">}}
```

2022-02-08 23:19 UTC, alai97 commented on content/en/serverless/guide/datadog_forwarder_java.md
>  </div>
Let's move this banner right below the H2 Overview so it goes yellow banner, image, and red banner.

2022-02-08 23:19 UTC, alai97 commented on content/en/serverless/guide/datadog_forwarder_python.md
> +<div class="alert alert-warning">
```suggestion
## Overview

<div class="alert alert-warning">
```

2022-02-08 23:19 UTC, alai97 commented on content/en/serverless/guide/datadog_forwarder_python.md
> +If you are a new user of Datadog Serverless, follow the <a href="/serverless/installation/python">instructions to instrument your Lambda functions using the Datadog Lambda Extension</a> instead. Howe
```suggestion
If you are a new user of Datadog Serverless, follow the <a href="/serverless/installation/python">instructions to instrument your Lambda functions</a> using the Datadog Lambda Extension instead. If you have setup Datadog Serverless with the Datadog Forwarder before Lambda offered out-of-the-box functionality, use this guide to maintain your instance.
```

2022-02-08 23:19 UTC, alai97 commented on content/en/serverless/guide/datadog_forwarder_node.md
> +If you are a new user of Datadog Serverless, follow the <a href="/serverless/installation/nodejs">instructions to instrument your Lambda functions using the Datadog Lambda Extension</a> instead. Howe
```suggestion
If you are a new user of Datadog Serverless, follow the <a href="/serverless/installation/nodejs">instructions to instrument your Lambda functions</a> using the Datadog Lambda Extension instead. If you have setup Datadog Serverless with the Datadog Forwarder before Lambda offered out-of-the-box functionality, use this guide to maintain your instance.
```

2022-02-08 23:19 UTC, alai97 commented on content/en/serverless/guide/datadog_forwarder_java.md
>  </div>
```suggestion
<div class="alert alert-warning">
If you are a new user of Datadog Serverless, follow the <a href="/serverless/installation/java">instructions to instrument your Lambda functions</a> using the Datadog Lambda Extension instead. If you have setup Datadog Serverless with the Datadog Forwarder before Lambda offered out-of-the-box functionality, use this guide to maintain your instance.

</div>
```

2022-02-09 14:03 UTC, tianchu commented
Updated the warning text copy, added the ## Overview to the guides where it was missing, adjusted the order of warning and alert for the java guide. @alai97 Mind taking another look? Thanks!

2022-02-09 20:34 UTC, alai97 approved these changes

2022-02-09 20:34 UTC, merged