[DOCS-3138] AWS Troubleshooting
DataDog/documentation pull request #13089
Opened 2022-02-12 00:19 UTC by sarina-dd

### What does this PR do?
Pulls the troubleshooting section out of the AWS docs into it's own guide

### Motivation
OKR 2 - the troubleshooting section is getting long and will continue to expand; making this more accessible

### Preview
https://docs-staging.datadoghq.com/sarina/aws-troubleshooting/integrations/guide/
https://docs-staging.datadoghq.com/sarina/aws-troubleshooting/integrations/guide/aws-integration-troubleshooting

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-02-23 23:16 UTC, jtappa requested changes

2022-02-23 23:16 UTC, jtappa commented on content/en/integrations/guide/aws-integration-troubleshooting.md
> +If you prefer to have these AWS host tags permanently removed from a host, you can do this by using the [Remove host tags API endpoint][7].
```suggestion
If you want to permanently remove AWS host tags from a host, you can do this by using the [Remove host tags API endpoint][7].
```

2022-03-01 18:26 UTC, sarina-dd commented
@jtappa Thanks for the review! 😸 Ready for final review.

2022-03-02 23:54 UTC, jtappa approved these changes

2022-03-03 03:41 UTC, merged