App Sec Custom Rules
DataDog/documentation pull request #13109
Opened 2022-02-15 16:01 UTC by sarina-dd

### What does this PR do?
Adds the Application Security Custom Rule doc

### Motivation
Jira request / OKR1

### Preview
https://docs-staging.datadoghq.com/sarina/app-sec-custom-rules/content/en/security_platform/application_security/custom_rules

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-02-15 16:02 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +Query `successful_attack_trigger`: `security_activity_to_monitor` ``-@http_status_code:[500-599]`.
```suggestion
Query `successful_attack_trigger`: `security_activity_to_monitor -@http_status_code:[500-599]`.
```

2022-02-15 16:02 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +Query `failed_attack_trigger`: `security_activity_to_monitor``@http_status_code:[500-599]`.
```suggestion
Query `failed_attack_trigger`: `security_activity_to_monitor @http_status_code:[500-599]`.
```

2022-02-15 16:02 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +Rule cases, such as `succesful trigger > 0`, are evaluated as case statements. Thus, the first case to match generates the signal. Create one or multiple rule cases, and click on the grey area next t
```suggestion
Rule cases, such as `successful trigger > 0`, are evaluated as case statements. Thus, the first case to match generates the signal. Create one or multiple rule cases, and click on the grey area next to them to drag and manipulate their ordering.
```

2022-02-15 16:45 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +To create a custom detection rule in Datadog, hover over **Security**, select **Detection Rules**, and select the **New Rule** button in the top right corner of the page.
Premise of custom rules goes here

2022-02-15 16:46 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +To create a custom detection rule in Datadog, hover over **Security**, select **Detection Rules**, and select the **New Rule** button in the top right corner of the page.
Main example goes here

2022-02-15 16:47 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +To create a custom detection rule in Datadog, hover over **Security**, select **Detection Rules**, and select the **New Rule** button in the top right corner of the page.
Primary use case: customizing OOTB rules

2022-03-03 23:01 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +### Template variables
```suggestion
#### Template variables
```

2022-03-03 23:10 UTC, sarina-dd commented
@arnaudbreton 👋 Hi there, made a few edits to the template and organized based on the app sec queries. Please take a look and let me know of any additional edits we need to make. I'm OOO tomorrow, so I'll check back in with you on Monday!

2022-03-09 08:58 UTC, arnaudbreton requested changes

2022-03-09 08:58 UTC, arnaudbreton commented on content/en/security_platform/application_security/custom_rules.md
> +However, there are situations where you may want to customize a rule based on your environment. For example, you may want to customize a rule that catches attack attempts on a service’s route. For in
However, there are situations where you may want to customize a **detection** rule...

2022-03-09 08:58 UTC, arnaudbreton commented on content/en/security_platform/application_security/custom_rules.md
> +Construct an Application Security query. For example, create a query to monitor an endpoint for SQL injection attempts: `@appsec.type:sql_injection @http.url_details.path:"/debug-endpoint-executing-s
Sorry that's my bad, I thought the query would be used in the context of an Exclusion Filter. If it is a detection rule query, then it misses an `-`: `@appsec.type:sql_injection -@http.url_details.path:"/debug-endpoint-executing-sql" env:production`

2022-03-09 15:26 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +However, there are situations where you may want to customize a rule based on your environment. For example, you may want to customize a rule that catches attack attempts on a service’s route. For in
```suggestion
However, there are situations where you may want to customize a rule based on your environment. For example, you may want to customize a detection rule that catches attack attempts on a service’s route. For instance, a pre-production development route accepting SQL and returning the results. Catching SQL attempts is noisy as the route is restricted to internal developers, therefore you can customize this rule to exclude these patterns.
```

2022-03-09 15:26 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +Construct an Application Security query. For example, create a query to monitor an endpoint for SQL injection attempts: `@appsec.type:sql_injection @http.url_details.path:"/debug-endpoint-executing-s
```suggestion
Construct an Application Security query. For example, create a query to monitor an endpoint for SQL injection attempts: `@appsec.type:sql_injection -@http.url_details.path:"/debug-endpoint-executing-sql" env:production`.
```

2022-03-23 20:56 UTC, cswatt requested changes

2022-03-23 20:56 UTC, cswatt commented on content/en/security_platform/application_security/custom_rules.md
> +Once a signal is generated, the signal will remain “open” if a case is matched at least once within this `keep alive` window. Each time a new event matches any of the cases, the *last updated* timest
```suggestion
When a signal is generated, it remains "open" if a case is matched at least once within this `keep alive` window. Each time a new event matches any of the cases, the *last updated* timestamp is updated for the signal.
```

2022-03-23 20:56 UTC, cswatt commented on content/en/security_platform/application_security/custom_rules.md
> +A signal will “close” regardless of the query being matched once the time exceeds the `maximum signal duration`. This time is calculated from the first seen timestamp.
```suggestion
A signal will "close" regardless of the query being matched once the time exceeds the `maximum signal duration`. This time is calculated from the first seen timestamp.
```

2022-03-23 20:56 UTC, cswatt commented on content/en/security_platform/application_security/custom_rules.md
> +Detection rules support template variables within the markdown notification box. Template variables permit injection of dynamic context from traces directly into a security signal and its associated
```suggestion
Detection rules support template variables within the Markdown notification box. Template variables permit injection of dynamic context from traces directly into a security signal and its associated notifications.
```

2022-03-23 20:56 UTC, cswatt commented on content/en/security_platform/application_security/custom_rules.md
> +For this attribute, you would use the following attribute in the “say what’s happening” section:
```suggestion
For this attribute, use the following in the “say what’s happening” section:
```

2022-03-25 20:45 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +You can also create [notification rules][4] to eleviate manual edits to notification preferences for individual detection rules.
LOL, what a mix of evaluate + alleviate, but i'll stick with alleviate!

2022-03-25 20:45 UTC, sarina-dd commented on content/en/security_platform/application_security/custom_rules.md
> +You can also create [notification rules][4] to eleviate manual edits to notification preferences for individual detection rules.
```suggestion
You can also create [notification rules][4] to alleviate manual edits to notification preferences for individual detection rules.
```

2022-03-25 20:49 UTC, cswatt approved these changes

2022-03-25 20:59 UTC, merged