[CWS] add troubleshooting section about security-agent flare
DataDog/documentation pull request #13172
Opened 2022-02-21 11:52 UTC by paulcacheux

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-02-21 17:01 UTC, n06 requested changes
Looks good to me! Had one slight nit for you, but that's it

2022-02-21 17:01 UTC, n06 commented on content/en/security_platform/cloud_workload_security/troubleshooting.md
> +In order to ensure that the communication between the `security-agent` and the `system-probe` is working as expected and the Cloud Workload Security probe is able to detect system events, you can man
```suggestion
In order to ensure that the communication between the `security-agent` and the `system-probe` is working as expected and that Cloud Workload Security is able to detect system events, you can manually trigger self tests by running the following command:
```

2022-02-22 13:17 UTC, lebauce approved these changes

2022-02-22 13:57 UTC, n06 approved these changes

2022-02-22 17:19 UTC, urseberry commented on content/en/security_platform/cloud_workload_security/troubleshooting.md
> +## Security Agent Flare
```suggestion
## Security Agent flare
```

2022-02-22 17:19 UTC, urseberry commented on content/en/security_platform/cloud_workload_security/troubleshooting.md
> +If needed, the flare can be reviewed prior to sending since the flare prompts a confirmation before uploading it.
```suggestion
The flare asks for confirmation before upload, so you may review the content before the Security Agent sends it.
```

2022-02-22 21:56 UTC, urseberry approved these changes

2022-02-22 21:56 UTC, merged