[DOCS-3161] Add Watchdog RCA FAQ
DataDog/documentation pull request #13188
Opened 2022-02-22 20:51 UTC by maycmlee

### What does this PR do?

- Creates a Watchdog folder and a FAQ subfolder
- Creates FAQ index page.
- Moves `watchdog.md` into Watchdog folder.
- Adds Watchdog RCA FAQ page.

### Motivation

DOCS-3161

### Preview

https://docs-staging.datadoghq.com/may/watchdog-rca-faq/watchdog/faq/
https://docs-staging.datadoghq.com/may/watchdog-rca-faq/watchdog/faq/root-cause-not-showing/

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-02-22 22:06 UTC, crunchypistachiobutter approved these changes

2022-02-23 17:40 UTC, jtappa requested changes

2022-02-23 17:40 UTC, jtappa commented on content/en/watchdog/faq/root-cause-not-showing.md
> +Do you think Watchdog should have found something that it missed? Or, do you have another type of root cause we should prioritize adding? We're always looking to make Watchdog smarter, so [open a sup
```suggestion
Do you think Watchdog should have found something that it missed? Or, do you have another type of root cause that you would like to be added? Datadog is always looking to make Watchdog smarter, so [open a support request][5] to let us know.
```

2022-02-23 18:10 UTC, jtappa approved these changes

2022-02-23 18:12 UTC, merged