Serverless installation updates for 'serverless.ts' and trace merging
DataDog/documentation pull request #13199
Opened 2022-02-23 21:49 UTC by Hesperide

2022-02-23 21:51 UTC, Hesperide commented on content/en/serverless/installation/nodejs.md
> +<div class="alert alert-info">If you are instead deploying your Serverless Framework app <a href="https://www.serverless.com/framework/docs/providers/aws/guide/intro">by natively exporting a JSON obj
```suggestion
<div class="alert alert-info">If you are instead deploying your Serverless Framework app <a href="https://www.serverless.com/framework/docs/providers/aws/guide/intro">by natively exporting a JSON object from a Javascript file</a> (e.g. using a "serverless.ts" file), follow our <a href="https://docs.datadoghq.com/serverless/installation/nodejs?tab=custom"> custom installation instructions</a>.</div>
```

2022-02-23 21:56 UTC, cswatt requested changes

2022-02-23 21:56 UTC, cswatt commented on content/en/serverless/installation/nodejs.md
> +<div class="alert alert-warning">If you previously set up Datadog Serverless using the Datadog Forwarder, see the <a href="docs.datadoghq.com/serverless/guide/datadog_forwarder_node">installation ins
```suggestion
<div class="alert alert-warning">If you previously set up Datadog Serverless using the Datadog Forwarder, see the <a href="docs.datadoghq.com/serverless/guide/datadog_forwarder_node">Datadog Forwarder - Node</a> guide.</div>
```

2022-02-23 21:56 UTC, cswatt commented on content/en/serverless/installation/nodejs.md
> +<div class="alert alert-info">If you are instead deploying your Serverless Framework app <a href="https://www.serverless.com/framework/docs/providers/aws/guide/intro">by natively exporting a JSON obj
```suggestion
<div class="alert alert-info">If you are instead deploying your Serverless Framework app <a href="https://www.serverless.com/framework/docs/providers/aws/guide/intro">by natively exporting a JSON object from a Javascript file</a> (for example, by using a <code>serverless.ts</code> file), follow the <a href="https://docs.datadoghq.com/serverless/installation/nodejs?tab=custom">custom installation instructions</a>.</div>
```

2022-02-23 21:56 UTC, cswatt commented on content/en/serverless/installation/python.md
> +<div class="alert alert-info">If you are instead deploying your Serverless Framework app <a href="https://www.serverless.com/framework/docs/providers/aws/guide/intro">by natively exporting a JSON obj
```suggestion
<div class="alert alert-info">If you are instead deploying your Serverless Framework app <a href="https://www.serverless.com/framework/docs/providers/aws/guide/intro">by natively exporting a JSON object from a JavaScript file</a> (for example, by using a <code>serverless.ts</code> file), follow the <a href="https://docs.datadoghq.com/serverless/installation/python?tab=custom">custom installation instructions</a>.</div>
```

2022-02-23 22:06 UTC, tianchu approved these changes

2022-02-24 15:45 UTC, cswatt approved these changes

2022-02-24 15:45 UTC, merged