[docs] how to disable session replay
DataDog/documentation pull request #13234
Opened 2022-02-28 16:36 UTC by NSarfaty-Ddog

### What does this PR do?
Indicates how to disable session replay

### Motivation
Multiple tickets where customer asked this question

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-02-28 16:42 UTC, MirandaKapin requested changes
replaySampleRate to 0 
This removes the whole SKU, not just the feature. this should be clarified

2022-02-28 19:18 UTC, maycmlee requested changes

2022-02-28 19:18 UTC, maycmlee commented on content/en/real_user_monitoring/session_replay/_index.md
> +### How to disable?
```suggestion
### How do you disable Session Replay?
```

2022-02-28 19:18 UTC, maycmlee commented on content/en/real_user_monitoring/session_replay/_index.md
> +- Remove startSessionReplayRecording()
```suggestion
- Remove `startSessionReplayRecording()`.
```

2022-02-28 19:18 UTC, maycmlee commented on content/en/real_user_monitoring/session_replay/_index.md
> +- Set replaySampleRate to 0 to stop collecting resources and long tasks that are added to the usage for this feature
```suggestion
- Set `replaySampleRate` to `0` to stop collecting resources and long tasks, which are added to the usage for this feature.
```

2022-03-03 19:17 UTC, maycmlee approved these changes

2022-03-03 19:32 UTC, MirandaKapin requested changes
- Remove `startSessionReplayRecording()` to stop session recordings
- Set `replaySampleRate` to `0` to stop collecting the RUM Session Replay plan which includes resources and long tasks.

2022-03-03 22:36 UTC, merged