DOCS 2971 - adding cluster agent windows info
DataDog/documentation pull request #13263
Opened 2022-03-02 17:42 UTC by cswatt

adds info about how you can monitor windows containers with the cluster agent

Replace the branch name and add the complete path: -->
https://docs-staging.datadoghq.com/cswatt/windows-cluster/agent/troubleshooting/windows_containers/#mixed-clusters-linux--windows
https://docs-staging.datadoghq.com/cswatt/windows-cluster/agent/cluster_agent/setup/?tab=helm#windows-containers

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-02 18:01 UTC, hkaj requested changes

2022-03-02 18:01 UTC, hkaj commented on content/en/agent/troubleshooting/windows_containers.md
> +With Cluster Agent v2.98+, this configuration is supported by the Datadog Cluster Agent.
```suggestion
With Cluster Agent v1.18+, this configuration is supported by the Datadog Cluster Agent.
```

2022-03-03 17:59 UTC, hkaj approved these changes

2022-03-03 18:20 UTC, jtappa approved these changes
Small nit for translation, but otherwise LGTM!

2022-03-03 18:20 UTC, jtappa commented on content/en/agent/troubleshooting/windows_containers.md
> +With Cluster Agent v1.18+, this configuration is supported by the Datadog Cluster Agent.
```suggestion
With Cluster Agent v1.18+, a configuration with mixed clusters is supported by the Datadog Cluster Agent.
```

2022-03-03 18:44 UTC, merged