[ci-visibility] Instructions for `datadog-ci` standalone binary
DataDog/documentation pull request #13297
Opened 2022-03-07 11:03 UTC by juan-fernandez

### What does this PR do?
Include instructions for the usage of `datadog-ci`'s standalone binary.

### Motivation
Make it simpler to use `datadog-ci`, without needing to install `node` in your environment. 

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-09 15:13 UTC, soyguijarro commented on content/en/continuous_integration/setup_tests/junit_upload.md
> +If installing nodejs in the CI is an issue, a standalone binary is provided with releases. Only _linux-x64_, _darwin-x64_ (macOS) and _win-x64_ (Windows) are supported at the time. To install for lin
I would actually apply the architecture nomenclature you're using here to the download filenames:

- datadog-ci-linux -> datadog-ci_linux-x64
- datadog-ci-win -> datadog-ci_win-x64
- datadog-ci-macos -> datadog-ci_darwin-x64

2022-03-10 17:33 UTC, jtappa requested changes

2022-03-10 17:33 UTC, jtappa commented on content/en/continuous_integration/setup_tests/junit_upload.md
> +If installing nodejs in the CI is an issue, standalone binaries are provided with [releases][3]. Only _linux-x64_, _darwin-x64_ (MacOS) and _win-x64_ (Windows) are supported at the time. To install:
```suggestion
If installing NodeJS in the CI is an issue, standalone binaries are provided with [Datadog CI releases][3]. Only _linux-x64_, _darwin-x64_ (MacOS) and _win-x64_ (Windows) are supported. To install, run the following from your CLI:
```

2022-03-10 17:33 UTC, jtappa commented on content/en/continuous_integration/setup_tests/junit_upload.md
> +<div class="alert alert-warning"><strong>Note</strong>: the standalone binaries are in <strong>beta</strong> and their stability is not guaranteed.</div>
```suggestion
<div class="alert alert-warning"><strong>Note</strong>: The standalone binaries are in <strong>beta</strong> and their stability is not guaranteed.</div>
```

2022-03-10 17:33 UTC, jtappa commented on content/en/continuous_integration/setup_tests/junit_upload.md
> +<div class="alert alert-warning"><strong>Note</strong>: the standalone binaries are in <strong>beta</strong> and their stability is not guaranteed.</div>
Move this up to just after the header for this section, ~line 35

2022-03-10 18:15 UTC, jtappa approved these changes

2022-03-10 18:16 UTC, merged