DOCS-3179 Browser RUM Data Collected Edits + Preview Link
DataDog/documentation pull request #13324
Opened 2022-03-09 02:36 UTC by alai97

### What does this PR do?

Addresses copy nits in the Data Collected doc page + pulls two other preview branches.

### Motivation

DOCS-3179

### Preview

https://docs-staging.datadoghq.com/alai97/rum-data-collected-documentation-update-preview/real_user_monitoring/browser/data_collected/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-11 23:26 UTC, alai97 commented on content/en/real_user_monitoring/browser/data_collected.md
> +| Session   | 30 days   | A user session begins when a user starts browsing the web application. It contains high-level information about the user (browser, device, geo-location). It aggregates all R
```suggestion
| Session   | 30 days   | A user session begins when a user starts browsing the web application. It contains high-level information about the user (browser, device, geo-location). It aggregates all RUM events collected during the user journey with a unique `session.id` attribute. **Note:** The session resets after 15 minutes of inactivity. |
```

2022-03-14 16:57 UTC, kayayarai requested changes
No copy edits to make, but two things:
- should probably undo the changes to pull_config_preview before we merge, and
- There's a broken link being reported by the build

2022-03-15 22:13 UTC, kayayarai approved these changes
approved if you use these changes

2022-03-15 22:13 UTC, kayayarai commented on local/bin/py/build/configurations/pull_config_preview.yaml
> +      branch: alai97/rum-data-collected-docs-update
```suggestion
      branch: master
```

2022-03-15 22:13 UTC, kayayarai commented on local/bin/py/build/configurations/pull_config_preview.yaml
> +      branch: alai97/rum-data-collected-docs-update
```suggestion
      branch: alai97/master
```

2022-03-22 23:12 UTC, merged