[APM/PHP] Add spans limit property
DataDog/documentation pull request #13328
Opened 2022-03-09 14:50 UTC by labbati

### What does this PR do?
Add `DD_TRACE_SPANS_LIMIT` property description to our docs.

### Preview

https://docs-staging.datadoghq.com/apm/php/span-limit/tracing/setup_overview/setup/php/?tab=containers#configuration

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-09 20:17 UTC, maycmlee requested changes

2022-03-09 20:17 UTC, maycmlee commented on content/en/tracing/setup_overview/setup/php.md
> +The maximum number of spans that are generated within one trace. If this amount of span is reached, then no more spans are generated. If this limit is increased, then the amount of memory that is occ
```suggestion
The maximum number of spans that are generated within one trace. If the maximum number of spans is reached, then spans are no longer generated. If the limit is increased, then the amount of memory that is used by a pending trace will increase and might reach the PHP maximum amount of allowed memory. The maximum amount of allowed memory can be increased with the PHP INI system setting `memory_limit`.
```

2022-03-10 16:44 UTC, maycmlee approved these changes
@labbati let me know if I should go ahead and merge.

2022-03-10 16:46 UTC, labbati commented
@maycmlee yes please go ahead and merge. Thank you

2022-03-10 17:38 UTC, merged