[CIAPP-3783] Add job logs collection mention to exploring pipelines page
DataDog/documentation pull request #13331
Opened 2022-03-09 16:28 UTC by soyguijarro

### What does this PR do?

Add job logs collection mention to exploring pipelines page

### Motivation

 This is particularly needed to link to it from the UI (see context in https://datadoghq.atlassian.net/browse/CIAPP-3783).

### Preview

https://docs-staging.datadoghq.com/ramon/ci-app_job-log-collection/continuous_integration/explore_pipelines/#explore-connections-to-logs

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-10 16:09 UTC, fermayo approved these changes

2022-03-10 16:09 UTC, fermayo commented on content/en/continuous_integration/explore_pipelines.md
> +If job log collection is enabled for the pipeline provider, you'll also be able to find related log events in the Logs tab of the pipeline execution view. Note that job log collection is currently on
```suggestion
If job log collection is supported and enabled for the CI provider, related log events can be found in the _Logs_ tab of the pipeline execution view.

**Note**: job log collection is currently only supported for [Jenkins][2].
```

2022-03-10 18:59 UTC, jtappa requested changes
Just some small feedback, thanks!

2022-03-10 18:59 UTC, jtappa commented on content/en/continuous_integration/explore_pipelines.md
> +### Explore connections to services, resources and network events
We still want that Oxford comma ;)
```suggestion
### Explore connections to services, resources, and network events
```

2022-03-10 18:59 UTC, jtappa commented on content/en/continuous_integration/explore_pipelines.md
> +**Note**: job log collection is currently only supported for [Jenkins][2].
```suggestion
**Note**: Job log collection is only supported for [Jenkins][2].
```

2022-03-11 09:41 UTC, soyguijarro commented
> Just some small feedback, thanks!

Applied. Read to merge now, thank you!

2022-03-11 22:09 UTC, jtappa approved these changes

2022-03-11 22:09 UTC, merged