Update documentation for collecting Boolean string mBeans
DataDog/documentation pull request #13334
Opened 2022-03-09 22:31 UTC by lgh2

### What does this PR do?
Updates the documentation for collecting Boolean string-type mBeans. 
### Motivation
Customer request 

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-11 20:45 UTC, alai97 requested changes

2022-03-11 20:45 UTC, alai97 commented on content/en/integrations/faq/i-have-a-matching-bean-for-my-jmx-integration-but-nothing-on-collect.md
> +Jmxfetch then knows it's a string and uses this rule to transform that into a numeric metric. Only string values are supported as keys with this custom mapping.
```suggestion

**Note:** Boolean metrics are automatically mapped to integers.

Jmxfetch can identify this string and uses this rule to transform it into a numeric metric. Only string values are supported as keys with this custom mapping.
```

2022-03-11 21:41 UTC, lgh2 commented on content/en/integrations/faq/i-have-a-matching-bean-for-my-jmx-integration-but-nothing-on-collect.md
> +              attribute:
I'm not sure the original structure was correct, in the escalation this syntax caused the agent to panic: 

```tag.isActiveMaster:
  alias: jmx.hadoop.hbase.master.server.tag.isActiveMaster
  metric_type: gauge
  values:
    true: 1
    false: 0```

2022-03-16 20:29 UTC, alai97 approved these changes

2023-03-01 21:16 UTC, apigirl commented
Hey @lgh2, this PR hasn't been worked on in about a year, so I am going to close it. Please feel free to reopen or reach out in #documentation if you still want to work on it!

2023-03-01 21:16 UTC, closed without merging