[DOCS-3108] Add AWS Config Guide for Cloud SIEM
DataDog/documentation pull request #13383
Opened 2022-03-15 15:34 UTC by maycmlee

### What does this PR do?

- Adds new AWS Configuration Guide for Cloud SIEM doc.
- Adds links to the guide in the Cloud SIEM Getting Started page.
- Adds link to the guide in the Cloud SIEM Guide page.

### Motivation

DOCS-3108

### Preview

https://docs-staging.datadoghq.com/may/aws-config-cloud-siem/security_platform/guide/aws-config-guide-for-cloud-siem/

https://docs-staging.datadoghq.com/may/aws-config-cloud-siem/security_platform/cloud_siem/getting_started/

https://docs-staging.datadoghq.com/may/aws-config-cloud-siem/security_platform/guide/

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-15 18:06 UTC, jmassey-datadog approved these changes

2022-03-22 09:38 UTC, jmassey-datadog commented
Can we do a find and replace for Cloudtrail to CloudTrail?

2022-03-22 09:51 UTC, jmassey-datadog commented
Can we also reference the AWS Investigation dashboard in the "Use Cloud SIEM to triage Security Signals" section? It includes a lot of useful information to users and will be immediately useful to users whereas the customer will have to wait a little while for a security signal to be generated. 

Here is the relative URL for it. dash/integration/30459/aws-cloudtrail

2022-03-22 17:14 UTC, maycmlee commented
Hey @jmassey-datadog! I should have gotten all the Cloudtrail -> Cloud Trail changes. Also added the info AWS investigation dashboard. Let me know if that works.

2022-03-23 16:40 UTC, cswatt requested changes
just small nits!

2022-03-23 16:40 UTC, cswatt commented on content/en/security_platform/guide/aws-config-guide-for-cloud-siem.md
> +    **Note:** The DatadogAppKey parameter enables the CloudFormation stack to make API calls to Datadog to add and edit the Datadog configuration for this AWS account. The key is automatically genera
```suggestion
    **Note:** The `DatadogAppKey` parameter enables the CloudFormation stack to make API calls to Datadog to add and edit the Datadog configuration for this AWS account. The key is automatically generated and tied to your Datadog account. 
```

2022-03-23 16:40 UTC, cswatt commented on content/en/security_platform/guide/aws-config-guide-for-cloud-siem.md
> +8. After the Stack is created, go back to the AWS integration tile in Datadog and find the box for the new account you created. Click **Refresh to Check Status** to see a success message at the top o
```suggestion
8. After the CloudFormation stack is created, go back to the AWS integration tile in Datadog and find the box for the new account you created. Click **Refresh to Check Status** to see a success message at the top of the page, along with the new account visible on the page with the relevant details.
```

2022-03-23 21:37 UTC, cswatt approved these changes

2022-03-24 13:21 UTC, merged