added a cross reference about correlating logs.
DataDog/documentation pull request #13395
Opened 2022-03-16 01:40 UTC by zippy1981

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-16 20:04 UTC, maycmlee requested changes

2022-03-16 20:04 UTC, maycmlee commented on content/en/tracing/setup_overview/setup/dotnet-core.md
> +Note that your logger needs to have a `source` that set to the `trace_id` mapping properly. The default source for .NET Applications, `csharp` does this automatically. For more information [see the F
```suggestion
Your logger needs to have a `source` that sets the `trace_id` mapping correctly. The default source for .NET Applications, `csharp`, does this automatically. For more information [see the FAQ on correlation troubleshooting](/tracing/faq/why-cant-i-see-my-correlated-logs-in-the-trace-id-panel.md#trace_id-option).
```

2022-03-16 20:04 UTC, maycmlee commented on content/en/tracing/setup_overview/setup/dotnet-core.md
> +Note that your logger needs to have a `source` that set to the `trace_id` mapping properly. The default source for .NET Applications, `csharp` does this automatically. For more information [see the F
```suggestion
Your logger needs to have a `source` that sets the `trace_id` mapping correctly. The default source for .NET Applications, `csharp`, does this automatically. For more information [see the FAQ on correlation troubleshooting](/tracing/faq/why-cant-i-see-my-correlated-logs-in-the-trace-id-panel.md#trace_id-option).
```

2022-03-22 17:26 UTC, zippy1981 commented
@maycmlee I made the requested changes. Can this be approved?

2022-03-22 20:15 UTC, zacharycmontoya approved these changes
LGTM from the engineering side

2022-03-22 21:15 UTC, maycmlee approved these changes

2022-03-22 22:01 UTC, zacharycmontoya requested changes
Sorry, before merging can these changes be copied over to the `dotnet-framework.md` file so the two files are in-sync?

2022-03-23 04:05 UTC, zippy1981 commented
Done @zacharycmontoya

2022-03-23 16:49 UTC, zacharycmontoya approved these changes
LGTM, thanks for the contribution!

2022-03-23 21:05 UTC, merged