App Analytics migration instructions
DataDog/documentation pull request #13472
Opened 2022-03-23 11:15 UTC by dussault-antoine

### What does this PR do?

App Analytics migration instructions (page is linked from the app)

### Motivation

### Preview

https://docs-staging.datadoghq.com/antoine.dussault/app_analytics_migration_instructions/tracing/legacy_app_analytics

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-23 12:04 UTC, l0k0ms commented on content/en/tracing/legacy_app_analytics/_index.md
> +To move away from App Analytics, remove every [configuration option](#app-analytics-setup) related to this setup. Instead, use our agent and libraries [sampling mechanisms][2] that ensure to keep com
```suggestion
To move away from the legacy App Analytics setup, remove every [configuration option](#app-analytics-setup) related to it. Instead, use the Datadog Agent and tracing libraries [sampling mechanisms][2] that ensure to keep complete traces.
```

2022-03-23 12:32 UTC, nxnarbais commented
Not sure about this:

> App Analytics is used to filter Indexed Spans by user-defined tags such as `customer_id`, `error_type`, or `app_name` to help troubleshoot and filter your requests. To enable it, either:

App Analytics just has an impact on ingested spans. At least the doc, seems to focus on that. In addition, `help troubleshoot and filter your requests` is too broad and can be applied to APM. The way I see App Analytics, this is a "ingestion light" way (so less heavy than other ingestion mechanism) to submit spans that can later be used for advanced analytics (analytics on tags beyond the one provided by APM metrics). I believe we should find a way to position this vs the others.

2022-03-23 14:03 UTC, maycmlee requested changes
Hi, left some feedback! Also, should "Database services" be H4, too?

2022-03-24 13:05 UTC, maycmlee approved these changes

2022-03-24 13:08 UTC, merged