DOCS-3296 Adds the Synthetics CircleCI Orb README into Documentation
DataDog/documentation pull request #13493
Opened 2022-03-24 23:55 UTC by alai97

### What does this PR do?

Adds single sourcing logic for CircleCI Orbs documentation. I can't generate a preview link because I don't have write access to the repo yet (and am on a fork).

### Motivation

DOCS-3296

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

Remember to add single sourcing logic to the `pull_config.yaml` file before merging! 
---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-25 08:56 UTC, peculiarism approved these changes

2022-03-30 07:10 UTC, peculiarism requested changes
Just a couple of changes but looks good to go!

2022-03-30 07:10 UTC, peculiarism commented on content/en/synthetics/cicd_integrations/_index.md
> +    {{< nextlink href="synthetics/cicd_integrations/circleci_orbs" >}}CircleCI Orbs{{< /nextlink >}}
```suggestion
    {{< nextlink href="synthetics/cicd_integrations/circleci_orbs" >}}CircleCI Orb{{< /nextlink >}}
```

2022-03-30 07:10 UTC, peculiarism commented on local/bin/py/build/configurations/pull_config_preview.yaml
> +          title: Synthetics CI CircleCI Orbs
```suggestion
          title: Synthetics CI CircleCI Orb
```

2022-03-30 07:10 UTC, peculiarism commented on local/bin/py/build/configurations/pull_config_preview.yaml
> +        file_name: 'circleci_orbs.md'
Can we change the md file to `orb`?

2022-03-30 22:41 UTC, apigirl approved these changes
This LGTM pending Beths suggestions. Let me know on slack if you need another review/approval

2022-04-04 18:46 UTC, alai97 commented on config/_default/menus/menus.en.yaml
> +    identifier: synthetics_cicd_integrations_circleci_orbs
```suggestion
  - name: CircleCI Orb
    url: /synthetics/cicd_integrations/circleci_orb
    parent: synthetics_cicd_integrations
    identifier: synthetics_cicd_integrations_circleci_orb
```

2022-04-04 18:46 UTC, alai97 commented on Makefile
> +	rm -f content/en/synthetics/cicd_integrations/circleci_orbs.md ;fi
```suggestion
	@if [ content/en/synthetics/cicd_integrations/circleci_orb.md ]; then \
	rm -f content/en/synthetics/cicd_integrations/circleci_orb.md ;fi
```

2022-04-04 18:49 UTC, peculiarism commented on content/en/synthetics/cicd_integrations/_index.md
> +    {{< nextlink href="synthetics/cicd_integrations/circleci_orbs" >}}CircleCI Orb{{< /nextlink >}}
Do we need to change the href?

2022-04-04 18:49 UTC, alai97 commented on content/en/synthetics/cicd_integrations/_index.md
> +    {{< nextlink href="synthetics/cicd_integrations/circleci_orbs" >}}CircleCI Orb{{< /nextlink >}}
```suggestion
    {{< nextlink href="synthetics/cicd_integrations/circleci_orb" >}}CircleCI Orb{{< /nextlink >}}
```

2022-04-04 18:53 UTC, peculiarism approved these changes

2022-04-04 21:27 UTC, merged