Explain how to disable GitHub Actions CI Viz integration
DataDog/documentation pull request #13530
Opened 2022-03-29 15:31 UTC by cg14823

### What does this PR do?

Add instructions on how to disable the GitHub Actions CI Visibility integration

### Motivation

The process is not obvious so customers have been having doubts on how to do this.

### Preview

https://docs-staging.datadoghq.com/carlos.gonzalez/add-gha-disable-instructions/continuous_integration/setup_pipelines/github/#disabling-github-actions-tracing

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-03-29 16:07 UTC, juan-fernandez approved these changes

2022-03-29 17:14 UTC, jtappa requested changes

2022-03-29 17:14 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/github.md
> +To disable the CI Visibility GitHub Actions integration make sure the GitHub app is no longer subscribed to the
```suggestion
To disable the CI Visibility GitHub Actions integration, make sure the GitHub app is no longer subscribed to the
```

2022-03-29 17:14 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/github.md
> +3. Scroll down to the **Subscribe Events** and make sure that **Workflow job** and **Workflow run** are not selected.
I'm trying to follow along with a quick tester github app. Is this what you're referring to?
<img width="781" alt="Screen Shot 2022-03-29 at 10 11 39 AM" src="https://user-images.githubusercontent.com/605271/160667874-b9c5d67a-9db0-4078-a369-5cc1db99aa92.png">

if so, we should match their UI text exactly to be this:
```suggestion
3. Scroll to the **Subscribe to events** section, and make sure that **Workflow job** and **Workflow run** are not selected.
```

2022-03-30 18:28 UTC, jtappa approved these changes

2022-03-30 18:31 UTC, jtappa commented
Is this okay to merge, or did you want to wait for a review from @DataDog/ci-app-backend ?

2022-03-31 09:41 UTC, cg14823 commented
> Is this okay to merge, or did you want to wait for a review from https://github.com/orgs/DataDog/teams/ci-app-backend ?

It is ok to go through with out it.

2022-04-05 15:40 UTC, merged