Bryce/add aws manual setup guide
DataDog/documentation pull request #13571
Opened 2022-03-31 19:26 UTC by buraizu

### What does this PR do?
Add an AWS manual setup guide

### Motivation
DOCS-3234

### Preview
https://docs-staging.datadoghq.com/bryce/add-aws-manual-setup-guide/integrations/guide/aws-integration-manual-setup/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-04-07 17:59 UTC, warrierr requested changes

2022-04-07 17:59 UTC, warrierr commented on content/en/integrations/guide/aws-integration-manual-setup.md
> +Create an IAM policy for the Datadog role in your AWS account with [all permissions][4] to take advantage of every AWS integration offered by Datadog. As other components are added to an integration,
Let's move the Cloud Security Posture Management call our to the IAM role creation section, and have an explicit optional step to add the SecurityAudit policy to the role as well

2022-04-07 17:59 UTC, warrierr commented on content/en/integrations/guide/aws-integration-manual-setup.md
> +17. Give the role a name such as `DatadogAWSIntegrationRole`, as well as an apt description.
```suggestion
17. Give the role a name such as `DatadogIntegrationRole`, as well as an apt description. 
```

2022-04-07 17:59 UTC, warrierr commented on content/en/integrations/guide/aws-integration-manual-setup.md
> +22. Optionally, customize the AWS services to collect metrics from on the left side of the dialog.
Let's remove all these "Optionally" steps. Re-reading this, I think it is a bit confusing without explaining more about what/where each of these are, so I think we should just remove

2022-04-07 17:59 UTC, warrierr commented on content/en/integrations/guide/aws-integration-manual-setup.md
> +
Let's add a step like we have in the getting started guide: 
`Wait up to 10 minutes for data to start being collected, and then view the out-of-the-box [AWS overview dashboard](https://app.datadoghq.com/screen/integration/7/aws-overview) to see metrics sent by your AWS services and infrastructure`

2022-04-07 17:59 UTC, warrierr commented on content/en/integrations/guide/aws-integration-manual-setup.md
> +[1]: /integrations/amazon_web_services/
Can we add links to the docs/guides for lambda forwarder, kinesis firehose for logs, and metric streams to these links as well?

2022-04-08 18:58 UTC, warrierr requested changes
Also: Update all links to open in new tabs

Link to new permissions section on main page once available

2022-05-10 15:49 UTC, buraizu commented
Closing in favor of PR 13963

2022-05-10 15:49 UTC, closed without merging