[APM] .NET 6 is supported for functions
DataDog/documentation pull request #13626
Opened 2022-04-06 12:07 UTC by pierotibou

### What does this PR do?
Fix support of AAS Functions for NET6

### Preview
https://docs-staging.datadoghq.com/pierre/apm-net6-functions/serverless/azure_app_services?tab=net

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-04-06 13:42 UTC, tianchu approved these changes

2022-04-06 19:41 UTC, jtappa requested changes
Just a small suggestion to make translation process easier!

2022-04-06 19:41 UTC, jtappa commented on content/en/serverless/azure_app_services.md
> +    <div class="alert alert-warning">Support for .NET Function Apps is in beta for extension v2.2+. Function Apps on consumption plans are not supported. Out-of-process (aka Isolated) functions do no
```suggestion
    <div class="alert alert-warning">Support for .NET Function Apps is in beta for extension v2.2+. Function Apps on consumption plans are not supported. Out-of-process (also known as Isolated) functions do not yet support Distributed Tracing either. There are no billing implications for tracing functions during this period.<br/><br/>Interested in support for other App Service resource types or runtimes? <a href="https://forms.gle/n4nQcxEyLqDBMCDA7">Sign up</a> to be notified when a beta becomes available.</div>
```

2022-04-13 17:23 UTC, jtappa approved these changes

2022-04-13 17:34 UTC, merged