Profiler .NET - Add an explicit comment on "configuring environment variables at machine level
DataDog/documentation pull request #13676
Opened 2022-04-12 14:32 UTC by gleocadie

### What does this PR do?

Add a `warning note` to inform customers to avoid setting environment variables at machine-level.

### Motivation

We had customers lately that reported a huge overhead (CPU and memory) incurred by the profiler. After investigating, we discovered that they set the required environment variables at machine-level. This is not recommended and should be avoid.

### Preview

https://docs-staging.datadoghq.com/gleocadie/add-warning-for-dotnet-profiler-for-global-configuration/tracing/profiler/enabling/dotnet/?tab=internetinformationservicesiis

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-04-12 17:23 UTC, jtappa requested changes

2022-04-12 17:23 UTC, jtappa commented on content/en/tracing/profiler/enabling/dotnet.md
> +  <strong>Note:</strong> Below, you will have to set environment variables to enable the profiler. We <strong>do not recommend</strong> setting those environment variables at machine level. If you do
```suggestion
  <strong>Note:</strong> The following steps include setting environment variables to enable the profiler. Datadog <strong>do not recommend</strong> setting those environment variables at machine-level. If set at machine-level, every .NET application running on the machine is profiled and this incurs a significant overhead on the CPU and memory of your machine.
```

2022-04-12 19:50 UTC, jtappa approved these changes

2022-04-12 19:51 UTC, jtappa commented on content/en/tracing/profiler/enabling/dotnet.md
> +  <strong>Note:</strong> The following steps include setting environment variables to enable the profiler. Datadog <strong>do not recommend</strong> setting those environment variables at machine-lev
```suggestion
  <strong>Note:</strong> The following steps include setting environment variables to enable the profiler. Datadog <strong>does not recommend</strong> setting those environment variables at machine-level. If set at machine-level, every .NET application running on the machine is profiled and this incurs a significant overhead on the CPU and memory of your machine.
```

2022-04-15 17:08 UTC, chrisnas approved these changes
LGTM

2022-04-29 16:21 UTC, kayayarai approved these changes

2022-04-29 16:21 UTC, merged