DOCS-3257 Synthetics API Tests Assertions Update
DataDog/documentation pull request #13821
Opened 2022-04-25 23:46 UTC by alai97

### What does this PR do?

Updates assertions on most API Test types and screenshots for assertion sections.

### Motivation

DOCS-3257

### Preview

https://docs-staging.datadoghq.com/alai97/synthetics-api-tests-assertions-doc-update/synthetics/api_tests/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-04-26 20:49 UTC, buraizu requested changes
Hey Austin, could you add a bit more description to the alt text for the new images?

2022-04-27 07:34 UTC, HugoPct approved these changes
Looks good to me!

2022-04-27 20:21 UTC, alai97 commented on content/en/synthetics/api_tests/dns_tests.md
> +{{< img src="synthetics/api_tests/assertions_dns.png" alt="Define assertions for your DNS test" style="width:90%;" >}}
```suggestion
{{< img src="synthetics/api_tests/assertions_dns.png" alt="Define assertions for your DNS test to succeed or fail on" style="width:90%;" >}}
```

2022-04-27 20:21 UTC, alai97 commented on content/en/synthetics/api_tests/http_tests.md
> +{{< img src="synthetics/api_tests/assertions_http.png" alt="Define assertions for your HTTP test" style="width:90%;" >}}
```suggestion
{{< img src="synthetics/api_tests/assertions_http.png" alt="Define assertions for your HTTP test to succeed or fail on" style="width:90%;" >}}
```

2022-04-27 20:21 UTC, alai97 commented on content/en/synthetics/api_tests/ssl_tests.md
> +{{< img src="synthetics/api_tests/assertions_ssl.png" alt="Define assertions for your SSL test" style="width:90%;" >}}
```suggestion
{{< img src="synthetics/api_tests/assertions_ssl.png" alt="Define assertions for your SSL test to succeed or fail on" style="width:90%;" >}}
```

2022-04-27 20:21 UTC, alai97 commented on content/en/synthetics/api_tests/tcp_tests.md
> +{{< img src="synthetics/api_tests/assertions_tcp.png" alt="Define assertions for your TCP test" style="width:90%;" >}}
```suggestion
{{< img src="synthetics/api_tests/assertions_tcp.png" alt="Define assertions for your TCP test to succeed or fail on" style="width:90%;" >}}
```

2022-04-27 20:24 UTC, buraizu approved these changes

2022-04-27 20:25 UTC, merged