Add links for product ingested traces
DataDog/documentation pull request #13830
Opened 2022-04-26 17:47 UTC by dussault-antoine

### What does this PR do?

Add links to the external guide for reducing the ingestion volume + link to the ingestion mechanisms page

### Motivation

Missing links

### Preview

https://docs-staging.datadoghq.com/antoine.dussault/guide_add_links/tracing/guide/trace_ingestion_volume_control/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-04-26 19:36 UTC, buraizu requested changes
Small updates to clarify the link text

2022-04-26 19:36 UTC, buraizu commented on content/en/tracing/trace_ingestion/mechanisms.md
> +| Synthetic Monitoring | `synthetics` and `synthetics-browser` | An HTTP or browser test generates a trace when the backend services are instrumented. [Find the backend trace][4] from the synthetic t
```suggestion
| Synthetic Monitoring | `synthetics` and `synthetics-browser` | An HTTP or browser test generates a trace when the backend services are instrumented. Find the backend trace from the [synthetic test][4] run.
```

2022-04-26 19:36 UTC, buraizu commented on content/en/tracing/trace_ingestion/mechanisms.md
> +| Real User Monitoring        | `RUM`                               | A browser request from a web or mobile application generates a trace when the backend services are instrumented. [Find the backen
```suggestion
| Real User Monitoring        | `RUM`                               | A browser request from a web or mobile application generates a trace when the backend services are instrumented. Find the backend trace from the [RUM browser sessions][5] and resources. |
```

2022-04-26 19:36 UTC, buraizu commented on content/en/tracing/trace_ingestion/mechanisms.md
> +| Synthetic Monitoring | `synthetics` and `synthetics-browser` | An HTTP or browser test generates a trace when the backend services are instrumented. [Find the backend trace][4] from the synthetic t
Small update to make the link text more descriptive.

2022-04-26 19:36 UTC, buraizu commented on content/en/tracing/trace_ingestion/mechanisms.md
> +| Real User Monitoring        | `RUM`                               | A browser request from a web or mobile application generates a trace when the backend services are instrumented. [Find the backen
Small update to make the link text more descriptive.

2022-04-26 19:36 UTC, buraizu commented on content/en/tracing/trace_ingestion/mechanisms.md
> +[6]: /serverless/distributed_tracing/
```suggestion
[6]: /serverless/libraries_integrations/extension/
```

2022-04-26 19:36 UTC, buraizu commented on content/en/tracing/trace_ingestion/mechanisms.md
> +[6]: /serverless/distributed_tracing/
Is this link intended to point to the Lambda extension, as the link text on line 199 would suggest? If the link is indeed meant for /serverless/distributed_tracing/, could you update the link text to "serverless applications" or something similar?

2022-04-27 07:55 UTC, dussault-antoine commented on content/en/tracing/trace_ingestion/mechanisms.md
> +| Serverless | `lambda` and `xray`                   | Your traces received from the [Datadog Lambda Extension][6] or AWS X-Ray integration |
```suggestion
| Serverless | `lambda` and `xray`                   | Your traces received from the [Serverless applications][6] traced with Datadog Tracing Libraries or the AWS X-Ray integration |
```

2022-04-27 08:06 UTC, dussault-antoine commented on content/en/tracing/trace_ingestion/mechanisms.md
> +| Application Security Monitoring     | `appsec`                            | Traces ingested from Datadog tracing libraries and flagged by [ASM][7] as a threat |
```suggestion
| Serverless | `lambda` and `xray`                   | Your traces received from the [Serverless applications][6] traced with Datadog Tracing Libraries or the AWS X-Ray integration. |
| Application Security Monitoring     | `appsec`                            | Traces ingested from Datadog tracing libraries and flagged by [ASM][7] as a threat. |
```

2022-04-27 15:06 UTC, buraizu approved these changes

2022-04-27 15:07 UTC, merged