Highlight Admission controller+prep 1.20
DataDog/documentation pull request #13838
Opened 2022-04-27 10:29 UTC by yoannrobin

### What does this PR do?

* Highlight Admission controller in APM kubernetes setup
* Update Admission controller doc with new configuration modes (Cluster Agent 1.20)

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-04-28 10:52 UTC, clamoriniere commented on content/en/agent/cluster_agent/admission_controller.md
> +| `service`          | Inject Datadog's local-service DNS name in `DD_AGENT_HOST` environment variable |
we have a documentation card on our side to document the `network local service` and the new admission controller capability when Agent 7.36 and DCA 1.20 are released.

2022-04-28 10:54 UTC, hkaj commented on content/en/agent/cluster_agent/admission_controller.md
> +| `service`          | Inject Datadog's local-service DNS name in `DD_AGENT_HOST` environment variable |
ok great thank you

2022-06-02 07:38 UTC, ahmed-mez commented on content/en/agent/cluster_agent/admission_controller.md
> +| `service`          | Inject Datadog's local-service DNS name in `DD_AGENT_HOST` environment variable                                   |
perhaps we can add a note that this requires k8s v1.22+

2022-06-02 15:43 UTC, jtappa requested changes

2022-06-02 15:43 UTC, jtappa commented on content/en/agent/cluster_agent/admission_controller.md
> +The Datadog admission controller is a component of the Datadog Cluster Agent. The main benefit of the admission controller is to simplify the user's application pod configuration. For that, it has tw
```suggestion
The Datadog admission controller is a component of the Datadog Cluster Agent. The main benefit of the admission controller is to simplify your application pod configuration. For that, it has two main functionalities:
```

2022-06-02 15:43 UTC, jtappa commented on content/en/agent/cluster_agent/admission_controller.md
> +- Labels on the ownerReference (ReplicaSets, DaemonSets, Deployments...)
```suggestion
When these environment variables are not set, the admission controller uses standard tags value in the following order (highest first):

- Labels on the pod
- Labels on the `ownerReference` (ReplicaSets, DaemonSets, Deployments...)
```

2022-06-02 15:43 UTC, jtappa commented on content/en/agent/cluster_agent/admission_controller.md
> +Starting from Datadog Cluster Agent v1.20.0, the Datadog Admission Controller can be configured to inject different mode of communication between the application and Datadog agent.
```suggestion
Starting from Datadog Cluster Agent v1.20.0, the Datadog Admission Controller can be configured to inject different modes of communication between the application and Datadog agent.
```

2022-06-02 15:43 UTC, jtappa commented on content/en/agent/kubernetes/apm.md
> +[Datadog Admission Controller][1] is able to inject environment variables and mount the necessary volumes on new application-pods in order to configure pod/agent trace communication automatically.
```suggestion
[Datadog Admission Controller][1] is able to inject environment variables and mount the necessary volumes on new application-pods in order to configure pod and agent trace communication automatically.
```

2022-06-02 15:43 UTC, jtappa commented on content/en/agent/kubernetes/apm.md
> +To learn more on how to automatically configure you application to submit traces to Datadog Agent refer to [Datadog Admission Controller][1].
```suggestion
To learn more on how to automatically configure you application to submit traces to Datadog Agent read the [Datadog Admission Controller][1] documentation.
```

2022-06-02 15:50 UTC, jtappa approved these changes

2022-06-07 19:06 UTC, merged