[CIAPP] Document custom tags and metrics
DataDog/documentation pull request #13957
Opened 2022-05-06 13:59 UTC by cg14823

### What does this PR do?
Documents how to use the custom tags and metrics feature in CI Visibility. It also add links for providers that can use this feature.

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-05-12 08:07 UTC, juan-fernandez commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +A valid [Datadog API key][2] has to be specified using the eniroment variable `DATADOG_API_KEY`.
```suggestion
A valid [Datadog API key][2] has to be specified using the environment variable `DATADOG_API_KEY`.
```

2022-05-12 08:07 UTC, juan-fernandez commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +The [Datadog site][3] has to be specidied using the enviromental variable `DATADOG_SITE`.
```suggestion
The [Datadog site][3] has to be specified using the environment variable `DATADOG_SITE`.
```

2022-05-12 08:08 UTC, juan-fernandez commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +A valid [Datadog API key][2] has to be specified using the eniroment variable `DATADOG_API_KEY`.
```suggestion
A valid [Datadog API key][2] has to be specified using the environment variable `DATADOG_API_KEY`.
```

2022-05-12 08:08 UTC, juan-fernandez commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +The [Datadog site][3] has to be specidied using the enviromental variable `DATADOG_SITE`.
```suggestion
The [Datadog site][3] has to be specified using the enviroment variable `DATADOG_SITE`.
```

2022-05-12 09:14 UTC, cg14823 commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +{{< /code-block >}}
I added a section with this info, good call.

2022-05-18 14:48 UTC, alai97 commented
Created DOCS-3536!

2022-05-23 19:34 UTC, jtappa requested changes

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +The custom tags and metrics commands provide a way to add user defined text and numerical tags to the CI Visibility
```suggestion
The custom tags and metrics commands provide a way to add user-defined text and numerical tags to your CI Visibility
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +can, in turn, be used to search, graph, or monitor the pipelines.
```suggestion
can then be used to search, graph, or monitor the pipelines.
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +- GitLab (SaaS or self-hoster >= 14.1)
```suggestion
- GitLab (SaaS or self-hosted >= 14.1)
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +- GitHub.com (SaaS). **Note:** For GitHub tags and metrics can only be added to the pipeline span
```suggestion
- GitHub.com (SaaS) **Note:** For GitHub, tags and metrics can only be added to the pipeline span.
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +Alternatively you can try and use the beta [standalone binary][2] if you don't want to use `npm`
```suggestion
Alternatively, you can use the beta [standalone binary][2] if you don't want to use `npm`.
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +Tags can be added to the pipeline span or to the job span. To do this run:
```suggestion
Tags can be added to the pipeline span or to the job span. To do this, run:
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +A valid [Datadog API key][3] has to be specified using the environment variable `DATADOG_API_KEY`.
```suggestion
You must specify a valid [Datadog API key][3] using the environment variable `DATADOG_API_KEY`.
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +The [Datadog site][1] has to be specified using the environment variable `DATADOG_SITE`.
```suggestion
You must specify the [Datadog site][1] using the environment variable `DATADOG_SITE`.
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +The example below adds the tag `team` to the pipeline span.
```suggestion
The following example adds the tag `team` to the pipeline span:
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +The example below adds the tag `go.version` to the span for the current job.
```suggestion
The following example adds the tag `go.version` to the span for the current job:
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +You can then create facets from the tags by click on the gear next to the tag name in the [pipeline executions page][4]
```suggestion
To create facets from the tags, click the gear icon next to the tag name in the [pipeline executions page][4],
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +and then clicking on the `create facet` option.
```suggestion
and then click the **create facet** option.
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +Numerical tags can be added to the pipeline span or the job span. To do this run:
```suggestion
To add numerical tags to the pipeline span or the job span, run:
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +A valid [Datadog API key][3] has to be specified using the environment variable `DATADOG_API_KEY`.
```suggestion
You must specify a valid [Datadog API key][3] using the environment variable `DATADOG_API_KEY`.

```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +The [Datadog site][1] has to be specified using the environment variable `DATADOG_SITE`.
```suggestion
You must specify the [Datadog site][1] using the environment variable `DATADOG_SITE`.
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +The example below adds the metric `error_rate` to the pipeline span.
```suggestion
The following example adds the metric `error_rate` to the pipeline span:
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +The example below adds a metric `binary.size` to the span for the currently running job.
```suggestion
The following example adds a metric `binary.size` to the span for the currently running job:
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +You can create a measure by clicking on the gear next to the metrics name in the [pipeline executions page][4]
```suggestion
To create a measure, click the gear icon next to the metrics name in the [pipeline executions page][4]
```

2022-05-23 19:34 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
> +and then clicking on the `create measure` option.
```suggestion
and then click the **create measure** option.
```

2022-05-26 16:19 UTC, kayayarai approved these changes

2022-05-26 16:20 UTC, merged