Incident Management and Security Signals
DataDog/documentation pull request #14015
Opened 2022-05-12 00:35 UTC by amberben

Described how to declare incidents for Security Signals and linked to Incidents page

### What does this PR do?
Introduce new incident management capability for security signals (ASM, CWS and Cloud SIEM)

### Motivation
Doing a beta program for Incidents but wanted to add documentation for customers curious about the how and why of the functionality

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-05-19 20:24 UTC, maycmlee requested changes
Hey @amberben, left some suggestions!

2022-05-20 00:12 UTC, amberben commented on content/en/security_platform/security_signal_management/_index.md
> +Any security signal that may lead to a disruption in your organization’s services can be described as an incident, and it is often necessary to have a set framework for handling these threats. [Incid
lgtm, thank you!

2022-05-20 00:13 UTC, amberben commented on content/en/security_platform/security_signal_management/_index.md
> +You can declare an incident directly from a Cloud SIEM or Cloud Workload Security signal by clicking the kebab button in the top-right of the side panel, or by selecting the export button in the Appl
Fantastic! Appreciate the review :)

2022-05-20 00:13 UTC, amberben commented
@maycmlee totally ok with merging this!

2022-05-20 15:56 UTC, maycmlee approved these changes

2022-05-20 15:57 UTC, merged