DOCS-3545 Adds Alerting with Conversion Rates Guide
DataDog/documentation pull request #14118
Opened 2022-05-23 21:42 UTC by alai97

### What does this PR do?

Adds Alerting with Conversion Rates guide.

### Motivation

DOCS-3545

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-05-24 15:31 UTC, jamiemilstein requested changes
This looks good! Can we wait to merge it until ~tuesday of next week? the screenshots i took this on are in a new sidepanel that isn't going live until then

2022-05-24 20:25 UTC, apigirl approved these changes
just a nit, this looks great!

2022-05-24 20:25 UTC, apigirl commented on content/en/real_user_monitoring/guide/alerting-with-conversion-rates.md
> +The funnel displays the overall conversion and dropoff rates, number of converted or dropoff sessions, and percentage of converted or dropoff sessions.
```suggestion
The funnel displays the overall conversion and dropoff rates, the number of converted or dropoff sessions, and the percentage of converted or dropoff sessions.  
```

2022-06-01 07:36 UTC, jamiemilstein commented
these screenshots are going to be live by end of this week / early next. i dont see any harm in actually merging this now since the queries / content is all the same!

2022-06-01 07:36 UTC, jamiemilstein approved these changes

2022-06-02 17:40 UTC, merged