[ci-visibility] Update javascript instrumentation to recommend `NODE_OPTIONS`
DataDog/documentation pull request #14240
Opened 2022-06-08 15:40 UTC by juan-fernandez

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-06-09 14:02 UTC, albertvaka approved these changes
LGTM

2022-06-10 08:25 UTC, juan-fernandez commented
solving conflicts now

2022-06-10 08:26 UTC, juan-fernandez commented
⚠️ Do not merge this yet. It's a significant change and I'd prefer to merge it on Monday

2022-06-13 15:14 UTC, maycmlee requested changes
Left some feedback!

2022-06-13 15:14 UTC, maycmlee commented on content/en/continuous_integration/setup_tests/javascript.md
> +### Using `yarn>=2`
```suggestion
### Using Yarn >=2
```

2022-06-13 15:29 UTC, maycmlee approved these changes

2022-06-21 13:35 UTC, merged