DOCS-3491 RUM FAQs to Guides Migration
DataDog/documentation pull request #14323
Opened 2022-06-16 00:22 UTC by alai97

### What does this PR do?

Migrates most RUM FAQs into guides, implements title case in guide titles, addresses some copy nits in guides.

### Motivation

✨ Q2 2022 Docs Hackathon ✨

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-06-16 00:22 UTC, alai97 commented on content/en/real_user_monitoring/faq/content_security_policy.md
> +If you are using the CDN async or CDN sync setup for [Real User Monitoring][4] or [Browser Log Collection][5], you also add the following `script-src` entry:
```suggestion
If you are using the CDN async or CDN sync setup for [Real User Monitoring][4] or [Browser Log Collection][5], also add the following `script-src` entry:
```

2022-06-16 22:15 UTC, alai97 commented
@BenoitZugmeyer Yes, we're adding the deleted URLs as aliases to the nearest guide landing page according to the [Moving and Migrating Docs Pages](https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/2174550131/Moving+Migrating+Docs+Pages) instructions!

2022-06-17 17:27 UTC, kayayarai requested changes
Added the aliases on the two renamed files.

2022-06-17 17:27 UTC, kayayarai commented on content/en/real_user_monitoring/guide/proxy-rum-data.md
> +kind: guide
```suggestion
kind: guide
aliases:
  - /real_user_monitoring/faq/proxy_rum_data/
```

2022-06-17 17:27 UTC, kayayarai commented on content/en/real_user_monitoring/guide/session-replay-service-worker.md
> +kind: guide
```suggestion
kind: guide
aliases:
  - /real_user_monitoring/faq/session_replay_service_worker/
```

2022-06-17 19:48 UTC, kayayarai approved these changes

2022-06-17 19:48 UTC, merged