DOCS-3658 Adds Use Session Replay In Your Solutions/Support Workflows Guide + Troubleshooting Doc Page
DataDog/documentation pull request #14445
Opened 2022-06-27 23:42 UTC by alai97

### What does this PR do?

Extracts troubleshooting and FAQs from Session Replay index page into a Troubleshooting doc page, adds screenshots and content for the Use Session Replay In Your Solutions/Support Workflows guide. 

### Motivation

DOCS-3658 

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-06-28 03:56 UTC, alai97 commented on content/en/real_user_monitoring/session_replay/_index.md
> +In order to apply these configurations, upgrade the [Browser RUM SDK][5] to a version >= 3.6.
```suggestion
In order to apply these configurations, upgrade the [RUM Browser SDK][5] to a version >= 3.6.
```

2022-06-28 03:56 UTC, alai97 commented on content/en/real_user_monitoring/session_replay/_index.md
> +To stop session recordings, remove `startSessionReplayRecording()` and set `replaySampleRate` to `0`. This stops collecting data for the [Browser Premium plan][7] for RUM & Session Replay, which incl
```suggestion
To stop session recordings, remove `startSessionReplayRecording()` and set `replaySampleRate` to `0`. This stops collecting data for the RUM & Session Replay's [Browser Premium plan][7], which includes replays, resources, and long tasks.
```

2022-06-28 03:56 UTC, alai97 commented on content/en/real_user_monitoring/session_replay/_index.md
> +The usual [RUM initialization parameters][6] are all supported.
```suggestion
You can use the RUM Browser SDK's [initialization parameters][6].
```

2022-06-28 05:16 UTC, alai97 commented on content/en/real_user_monitoring/session_replay/_index.md
> +To stop session recordings, remove `startSessionReplayRecording()` and set `replaySampleRate` to `0`. This stops collecting data for the RUM & Session Replay's [Browser Premium plan][7], which includ
```suggestion
To stop session recordings, remove `startSessionReplayRecording()` and set `replaySampleRate` to `0`. This stops collecting data for RUM & Session Replay's [Browser Premium plan][7], which includes replays, resources, and long tasks.
```

2022-06-28 09:01 UTC, acorretti commented on content/en/real_user_monitoring/session_replay/_index.md
> +Session Replay is available through a dedicated build of the RUM Browser SDK. To start collecting data for Session Replay, set up [Datadog RUM Browser Monitoring][4] by creating a RUM application, ge
```suggestion
Session Replay is available in the RUM Browser SDK. To start collecting data for Session Replay, set up [Datadog RUM Browser Monitoring][4] by creating a RUM application, generating a client token generation, and initializing the RUM Browser SDK.
```
Just checked with @DataDog/rum-browser and this sentence isn't accurate anymore. There is no dedicated build, SR is included in the standard bundle/package now.

2022-06-28 14:46 UTC, kayayarai commented
created https://datadoghq.atlassian.net/browse/DOCS-3697 to track editorial review

2022-06-29 19:12 UTC, alai97 commented on content/en/real_user_monitoring/session_replay/troubleshooting.md
> +For example, if your application is on the `example.com` domain and depends on a CSS file on `assets.example.com` via a link element, the `crossorigin` attribute should be set to `anonymous`, unless
```suggestion
For example, if your application is on the `example.com` domain and depends on a CSS file on `assets.example.com` through a link element, the `crossorigin` attribute should be set to `anonymous`, unless credentials are required:
```

2022-07-06 16:42 UTC, cswatt requested changes

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/guide/session-replay-for-solutions.md
> +Let’s assume that a customer encounters an issue using Datadog. Your Technical Solutions team may use a support solution such as Zendesk or ServiceNow that creates a ticket when this customer reports
```suggestion
Assume that a customer encounters an issue using Datadog. Your Technical Solutions team may use a support solution, such as Zendesk or ServiceNow, that creates a ticket when this customer reports that they cannot update or save a Synthetics multistep API test. 
```

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/guide/session-replay-for-solutions.md
> +The team may request more information from the customer (such as the specific test ID and a screen recording with the [Browser Dev Tools][2] open) in order to obtain some additional context into the
```suggestion
The team may request more information from the customer (such as the specific test ID and a screen recording with the [Browser Dev Tools][2] open) that may provide additional context for the customer's test not updating or saving. If no console errors were recorded, the team would not have any hints to start investigating the multistep API test's issue. 
```

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/guide/session-replay-for-solutions.md
> +The Technical Solutions team may have internal tools that connect a support platform, like Zendesk, with Datadog products, such as RUM & Session Replay. For example, if you click on a contextual link
```suggestion
The Technical Solutions team may have internal tools that connect a support platform, like Zendesk, with Datadog products, such as RUM & Session Replay. For example, a contextual link in Zendesk can redirects you to the [RUM Explorer][4] and autofill the user ID in the search query. You can then filter for individual user sessions in the event list.
```

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/session_replay/_index.md
> +## Session Replay Recorder
```suggestion
## Session Replay recorder
```

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/session_replay/_index.md
> +The Session Replay recorder, part of the RUM Browser SDK, takes a snapshot of the browser's DOM and CSS by tailing and recording events happening on a web page (such as DOM modification, mouse move,
```suggestion
The Session Replay recorder is part of the RUM Browser SDK. The recorder takes a snapshot of the browser's DOM and CSS by tailing and recording events happening on a web page (such as DOM modification, mouse move, clicks, and input events) along with these events' timestamps. 
```

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/session_replay/_index.md
> +In order to reduce Session Replay's network impact and ensure the Session Replay recorder has minimal overhead on your application's performance, Datadog compresses the data prior to sending it, and
```suggestion
To reduce Session Replay's network impact and ensure the Session Replay recorder has minimal overhead on your application's performance, Datadog compresses the data prior to sending it. Datadog also reduces the load on a browser’s UI thread by delegating most of the CPU-intensive work (such as compression) to a background service worker. The expected network bandwidth impact is less than 100kB/min. 
```

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/session_replay/troubleshooting.md
> +Session Replay does not support the following HTML elements at the moment: `iframe`, `video`, `audio`, `canvas`, as well as Web Components.
```suggestion
Session Replay does not support the following HTML elements: `iframe`, `video`, `audio`, `canvas`. Session Replay does not support Web Components.
```

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/session_replay/troubleshooting.md
> +A Session Replay is not a video, but an actual iframe rebuilt based on snapshots of the DOM. The replay thus depends on the various assets of the page: fonts & images.
```suggestion
A Session Replay is not a video, but an actual iframe rebuilt based on snapshots of the DOM. The replay thus depends on the various assets of the page: fonts and images.
```

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/session_replay/troubleshooting.md
> +Several reasons might explain why assets are not available at the time of the replay.
```suggestion
Assets may not be available at the time of replay for the following reasons:
```

2022-07-06 16:42 UTC, cswatt commented on content/en/real_user_monitoring/session_replay/troubleshooting.md
> +   - Allow `session-replay-datadoghq.com` through the [`Access-Control-Allow-Origin`][3] header for any font or image assets your website depends on to ensure these resources are accessible for the r
```suggestion
- The resource no longer exists. For example, it was part of a previous deployment.
- The resource is inaccessible. For example, authentication might be required, or the resource might only be accessible from an internal network.
- The resource is blocked by the browser due to CORS (typically web-fonts).
   - The replay rendered on the `session-replay-datadoghq.com` sandbox domain and the asset requests are subject to cross-origin security checks by your browser. If the given asset is not authorized for the domain, your browser blocks the request.
   - Allow `session-replay-datadoghq.com` through the [`Access-Control-Allow-Origin`][3] header for any font or image assets your website depends on to ensure these resources are accessible for the replay. For more information, see [Cross Origin Resource Sharing][4].
```

2022-07-21 19:22 UTC, cswatt approved these changes

2022-07-21 19:49 UTC, alai97 commented on content/en/real_user_monitoring/_index.md
> +  text: "Check out the latest Datadog RUM releases! (App login required)."
```suggestion
  text: "Check out the latest Datadog RUM releases! (App login required)"
```

2022-07-21 19:52 UTC, merged