Set accept header in curl examples
DataDog/documentation pull request #14530
Opened 2022-07-05 15:53 UTC by therve

### What does this PR do?

Add accept headers in curl examples.

### Motivation

Recent breakage in some APIs.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-07-06 11:19 UTC, davidejones commented
Just noticed with these changes that the `\` is on a new line now instead of at the end of the first line e.g

```
# Curl command
curl -X GET "https://api.datadoghq.com/api/v1/dashboard"
 \
-H "Accept: "application/json" \
-H "DD-API-KEY: ${DD_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DD_APP_KEY}"
```

2022-07-06 12:15 UTC, therve commented
> Just noticed with these changes that the `\` is on a new line now instead of at the end of the first line e.g
> 
> ```
> # Curl command
> curl -X GET "https://api.datadoghq.com/api/v1/dashboard"
>  \
> -H "Accept: "application/json" \
> -H "DD-API-KEY: ${DD_API_KEY}" \
> -H "DD-APPLICATION-KEY: ${DD_APP_KEY}"
> ```

Yeah I don't know why... But I also want to make sure we only set it when the response can't be 204, need to spend more time investigating.

2022-07-11 17:21 UTC, kayayarai requested changes
There's either a superfluous " or a missing "

2022-07-11 17:21 UTC, kayayarai commented on layouts/partials/api/curl.html
> +<span class="o">-H</span> <span class="s1">"Accept: "application/json"</span>
```suggestion
<span class="o">-H</span> <span class="s1">"Accept: application/json"</span>
```

2022-07-15 13:43 UTC, bgdeutsch approved these changes

2022-07-20 15:47 UTC, buraizu approved these changes

2022-07-20 15:49 UTC, merged