(DOCS-3826) Add APM naming convention
DataDog/documentation pull request #14666
Opened 2022-07-18 12:40 UTC by yoannrobin

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-07-18 13:45 UTC, brettlangdon commented on content/en/tracing/trace_collection/tracing_naming_convention/_index.md
> +| `http.request.headers.*`                    | `string` | The request HTTP headers. None are collected by default but can optionally be configured with `DD_TRACE_HEADER_TAGS`.
We should link `DD_TRACE_HEADER_TAGS` to docs on how to use it.

2022-07-18 13:45 UTC, brettlangdon commented on content/en/tracing/trace_collection/tracing_naming_convention/_index.md
> +| `http.url`                                  | `string` | The URL of the HTTP request, including the obfuscated query string. For more informations on obfuscation refer to [Data security][2] |
we should document `http.url_details.*` tags as well.... once http url parsing is implemented on the backend

2022-07-18 13:45 UTC, brettlangdon commented on content/en/tracing/trace_collection/tracing_naming_convention/_index.md
> +### HTTP requests
missing `http.useragent` + `http.useragent_details.*`?

2022-07-26 21:05 UTC, maycmlee requested changes
Hey @yoannrobin, here's some feedback! I'll need to look into reformatting the HTTP table because it's overflowing: https://a.cl.ly/E0uyN1v9

2022-07-27 16:54 UTC, maycmlee approved these changes

2022-07-27 16:54 UTC, merged