Add note about 2 week Watchdog baseline
DataDog/documentation pull request #14698
Opened 2022-07-19 21:39 UTC by urseberry

### What does this PR do?
Adds a note to the top level Watchdog page saying that Watchdog requires two weeks of baseline data before it can report anomalies.

### Motivation
Discussion in #support-data-science Slack channel.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-07-21 16:19 UTC, sguyon commented
commented above

2022-07-22 20:30 UTC, cswatt requested changes

2022-07-22 20:30 UTC, cswatt commented on content/en/watchdog/_index.md
> +For any new source of metrics, logs, or other data, Watchdog requires two weeks of data to establish a baseline of expected behavior. Anomalies detected by Watchdog based on fewer than two weeks of d
```suggestion
For any new source of metrics, logs, or other data, Watchdog requires two weeks of data to establish a baseline of expected behavior. Anomalies detected by Watchdog based on less than two weeks of data may contain inaccuracies.
```

the ever-subtle fewer/less when applied to measures of time

2022-07-22 20:30 UTC, cswatt approved these changes

2022-07-22 20:47 UTC, merged