Provide uninstall instructions for macOS systemwide installation
DataDog/documentation pull request #14726
Opened 2022-07-21 13:16 UTC by bkabrda

### What does this PR do?

Adds instructions to remove systemwide macOS installation. I introduced another section for this, because I think it's more comfortable for users to C&P instead of having to go through one set of instructions and figure out what instruction to run when.

### Motivation

We added the systemwide installation feature in https://github.com/DataDog/datadog-agent/pull/10621 and want to document how to uninstall agent in this scenario.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-07-21 16:01 UTC, jtappa requested changes

2022-07-21 16:01 UTC, jtappa commented on content/en/agent/guide/how-do-i-uninstall-the-agent.md
> +2. Run:
```suggestion
2. To remove remaining files, run the following:
```

2022-07-22 11:25 UTC, KSerrania approved these changes

2022-07-22 21:19 UTC, jtappa approved these changes

2022-07-22 21:20 UTC, merged