CSP reporting integration
DataDog/documentation pull request #14731
Opened 2022-07-21 17:04 UTC by hestonhoffman

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-05 15:19 UTC, aviat approved these changes
This looks good to me, I think we can proceed!

2023-01-05 17:24 UTC, hestonhoffman commented
I need to get a logo for the integrations page before I publish this, so I'll work on that

2023-03-06 23:39 UTC, alai97 requested changes
Doc review~

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +integration_title: Content Security Policy logs
```suggestion
integration_title: Content Security Policy Logs
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +The Datadog Content Security Policy (CSP) integration sends logs to Datadog from web browsers as they interpret your CSP and detect violations. Using the CSP integration means you don't have to host
```suggestion
The Datadog Content Security Policy (CSP) integration sends logs to Datadog from web browsers as they interpret your CSP and detect violations. By using the CSP integration, you don't have to host or manage a dedicated endpoint to aggregate your CSP data.
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +<div class="alert alert-info">API keys cannot be used to configure the browser logs SDK, because the keys would be exposed client-side. To collect logs from web browsers, use a client token. <a href=
```suggestion
<div class="alert alert-info">For security reasons, you must use a client token to collect logs from web browsers. You cannot use Datadog API keys to configure the Datadog Browser Logs SDK as they would be exposed client-side. For more information, see the <a href="https://docs.datadoghq.com/logs/log_collection/?tab=host#setup">client token documentation for more details</a>.</div>
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +- `version`: the application's version
```suggestion
- `env`: the application's environment.
- `service`: the service name for your application.
- `version`: the application's version.
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +[2]: https://app.datadoghq.com/organization-settings/client-tokens
```suggestion
[2]: https://app.datadoghq.com/organization-settings/client-tokens
[3]: /getting_started/tagging/unified_service_tagging
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +Optionally, add the `ddtags` key to the URL to convey additional information such as the service name, the environment, and service version:
```suggestion
Optionally, add the `ddtags` key (service name, the environment, and service version) to the URL to set up [Unified Service Tagging][3]:
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +## Adding the URL to the CSP
```suggestion
## Add the URL to the CSP
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +This is the recommended way to embed a Content Security Policy. You can either use the `report-uri` directive or the `report-to` directive. The `report-to` directive will eventually supersede `report
Not sure about the temporal element of the second sentence here:

```suggestion
Datadog recommends embedding the Content Security Policy in an HTTP header. You can either use the `report-uri` directive or the `report-to` directive. The `report-to` directive will eventually supersede `report-uri`, but is not yet supported by all browsers.
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +### Policy embedded in a <meta> HTML tag
The preview is skipping the `meta` part.

```suggestion
### Policy embedded in a `<meta>` HTML tag
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +You can also embed the URL in an HTML <meta> tag.
The preview is skipping the `meta` part.

```suggestion
You can also embed the URL in a `<meta>` HTML tag.
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +integration_id: "content_security_policy_logs"
```suggestion
integration_id: "content_security_policy_logs"
further_reading:
  - link: "/getting_started/tagging/unified_service_tagging/"
    tag: "Documentation"
    text: "Learn about Unified Service Tagging"
```

2023-03-06 23:39 UTC, alai97 commented on content/en/integrations/content_security_policy_logs.md
> +
```suggestion

## Further Reading

{{< partial name="whats-next/whats-next.html" >}}

```

2023-03-07 18:40 UTC, alai97 approved these changes
Looks good!

2023-03-07 18:41 UTC, alai97 approved these changes
Looks good!

2023-03-07 18:48 UTC, merged