fix: Updated PHP example to use up to date API
DataDog/documentation pull request #14796
Opened 2022-07-28 02:42 UTC by CameronHall

### What does this PR do?
Updated PHP example to use up-to-date API

### Motivation
A colleague linked me to this doc and I was annoyed that it didn't work when I copied the example.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-07-28 16:52 UTC, jtappa commented
Hi @CameronHall, I'm sorry to hear you bumped into an old example. I really appreciate you taking action to update it though! I've added a Jira card for us to track this internally, and we'll get an SME to confirm the change before merging.

2022-07-29 08:38 UTC, labbati requested changes
Just a minor change, as the new api has a different way to set tags. Other than this it looks good to me! Thanks for the fix

2022-07-29 08:38 UTC, labbati commented on content/en/tracing/guide/add_span_md_and_graph_it.md
>                $span->setTag('customer_id', $request->get('customer_id'));
```suggestion
              $span->meta['customer_id'] = $request->get('customer_id');
```

2022-07-29 12:10 UTC, CameronHall commented
I did that originally before I force pushed 🤦🏼‍♂️😂

2022-07-29 12:35 UTC, labbati approved these changes
Thank you @CameronHall

2022-07-29 14:38 UTC, kayayarai approved these changes

2022-07-29 14:38 UTC, merged