add ksm core recommendation for helm installation
DataDog/documentation pull request #14808
Opened 2022-07-28 17:03 UTC by kennonkwok

### What does this PR do?

This adds a recommendation for new DD deployments to use KSM Core.

### Motivation

This is considered a best practice and will prevent future migration issues for the customer.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-03 18:15 UTC, buraizu requested changes
Thanks, left a few suggestions as per our [contributing guidelines](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md)

2022-08-03 18:15 UTC, buraizu commented on content/en/containers/kubernetes/installation.md
> +In new deployments, Datadog recommends using the newer kube-state-metrics core with the following values:
```suggestion
In new deployments, Datadog recommends using the newer `kube-state-metrics` core with the following values:
```

2022-08-03 18:15 UTC, buraizu commented on content/en/containers/kubernetes/installation.md
> +[12]: https://docs.datadoghq.com/integrations/kubernetes_state_core
```suggestion
[12]: /integrations/kubernetes_state_core
```

2022-08-04 01:37 UTC, buraizu requested changes
Thanks for implementing those changes, and apologies -- it looks like I didn't save one of my earlier comments, so I've added it back in.

2022-08-04 15:28 UTC, buraizu approved these changes
Thanks again! I took another look, and I actually think it might be slightly better to have the link show the exact name of the page it opens, so I added that suggestion, but either way I think it should be fine

2022-08-04 15:28 UTC, buraizu commented on content/en/containers/kubernetes/installation.md
> +For details about `kube-state-metrics` core, read the [`kube-state-metrics` core documentation][12].
```suggestion
For details about `kube-state-metrics` core, read the [Kubernetes State Metrics Core documentation][12].
```

2022-08-04 18:46 UTC, johnrk approved these changes
LGTM

2022-08-04 20:23 UTC, merged