DOCS-3872 CI Results Explorer Documentation Edits
DataDog/documentation pull request #14821
Opened 2022-07-29 04:38 UTC by alai97

### What does this PR do?

Adds two pages under the Explorer (Search and Search Syntax).

### Motivation

DOCS-3872

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-07-29 10:39 UTC, peculiarism commented on content/en/synthetics/explorer/search_syntax.md
> +## Overview
This is a really great suggestion to help customers with the query syntax!!

2022-07-29 10:39 UTC, peculiarism approved these changes

2022-07-29 20:16 UTC, kayayarai requested changes
Just some little things :)

2022-07-29 20:16 UTC, kayayarai commented on config/_default/menus/menus.en.yaml
> +  - name: Search
```suggestion
  - name: Search Test Batches
```

2022-07-29 20:16 UTC, kayayarai commented on content/en/synthetics/explorer/search.md
> +| `Execution Rule` | The execution rule associated with the test result of the batch: `Blocking`, `Non Blocking`, and `Skipped`. |
```suggestion
| <code>Execution&nbsp;Rule</code> | The execution rule associated with the test result of the batch: `Blocking`, `Non Blocking`, and `Skipped`. |
```
lol this drove me batty

2022-07-29 20:16 UTC, kayayarai commented on content/en/synthetics/explorer/search_syntax.md
> +- A **sequence** is a group of wods surrounded by double quotes, such as `"hello dolly"`.
```suggestion
- A **sequence** is a group of words surrounded by double quotes, such as `"hello dolly"`.
```

2022-07-29 20:16 UTC, kayayarai commented on content/en/synthetics/explorer/search_syntax.md
> +| `AND`        | **Intersection**: Both terms are in the selected views (if nothing is added, AND is taken by default). |
```suggestion
| `AND`        | **Intersection**: Both terms are in the selected views. If no operator is used, `AND` is used by default. |
```

2022-08-01 13:02 UTC, peculiarism commented on content/en/synthetics/explorer/search.md
> +| `Branch`    | The branch associated with the batch.     |
@alai97 Last minute change, could we also add the `Author Email` facet? We added it quite recently, and it corresponds to the commit author

2022-08-02 14:59 UTC, kayayarai approved these changes

2022-08-02 16:54 UTC, merged