Explain how to correlate GitHub runner metrics and jobs
DataDog/documentation pull request #14856
Opened 2022-08-02 13:48 UTC by cg14823

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-02 14:09 UTC, AdrianLC reviewed
I think we usually don't attach screenshots because they might become outdated without us remembering to update the docs

2022-08-02 14:09 UTC, AdrianLC commented on content/en/continuous_integration/setup_pipelines/github.md
> +matches the hostname of the machine it is running on. CI Visibility will automatically detect the runner name and link it to the
```suggestion
If you are using self-hosted GitHub runners you can correlate jobs to the host that is running them. To do so make sure the GitHub runner name
matches the hostname of the machine it is running on. CI Visibility uses this to link to
```
Not sure if self-hosted is the best word for Github but _you are running the GitHub runners_ sounds a bit too informal to me

2022-08-02 14:12 UTC, cg14823 commented
> I think we usually don't attach screenshots because they might become outdated without us remembering to update the docs

Fair I'll remove the image and add a bit more words.

2022-08-04 10:49 UTC, AdrianLC approved these changes

2022-08-04 16:41 UTC, jtappa requested changes

2022-08-04 16:41 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/github.md
> +If you are using self-hosted GitHub runners you can correlate jobs to the host that is running them. To do so make sure the GitHub runner name
```suggestion
If you are using self-hosted GitHub runners, you can correlate jobs to the host that is running them. To do this, make sure the GitHub runner name
```

2022-08-04 16:41 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/github.md
> +infrastructure metrics. To see the metrics just click on a job span in the trace view and in the drawer a new tab named **Infrastructure** will
```suggestion
infrastructure metrics. To see the metrics, click on a job span in the trace view and in the window a new tab named **Infrastructure** is
```

2022-08-04 16:41 UTC, jtappa commented on content/en/continuous_integration/setup_pipelines/github.md
> +show which contains the host metrics.
```suggestion
shown which contains the host metrics.
```

2022-08-11 14:26 UTC, kayayarai approved these changes

2022-08-11 14:26 UTC, merged