DOCS-3874 Browser Test and Browser Test Steps Edits
DataDog/documentation pull request #14851
Opened 2022-08-01 23:02 UTC by alai97

### What does this PR do?

Updates Browser Test doc pages with content for local and global variables, addresses consistency nits across API and multistep API test pages, and documents the **Hide and obfuscate variable values** option.

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-02 08:09 UTC, HugoPct requested changes

2022-08-02 08:09 UTC, HugoPct commented on content/en/synthetics/multistep.md
> +   * **Body type**: Select the type of the request body (`text/plain`, `application/json`, `text/xml`, `text/html`, `application/x-www-form-urlencoded`, `GraphQL`, or `None`) you want to add to your
nice catch !

2022-08-02 08:09 UTC, HugoPct commented on content/en/synthetics/multistep.md
> +   * **Body type**: Select the type of the request body (`text/plain`, `application/json`, `text/xml`, `text/html`, `application/x-www-form-urlencoded`, `GraphQL`, or `None`) you want to add to your
can you add it the the 
- HTTP tests page
- HTTP requests for browser tests in /browser_tests/actions/ page
too please

2022-08-02 08:09 UTC, HugoPct commented on content/en/synthetics/multistep.md
> +### Extract variables
can we keep this section as first section below ### Create local variables
Extracting variables from a step to reuse it in following steps is a key strength of multistep tests

2022-08-02 08:10 UTC, HugoPct commented
For API tests pages, I've commented the [dns_tests.md] only but the comments apply for all the API test pages

2022-08-02 18:10 UTC, alai97 commented on content/en/synthetics/api_tests/dns_tests.md
> +To create a local variable, click **Create Local Variable** at the top right hand corner. You can select one of the following available builtins:
I was thinking about removing the repetition of "You can..." from the first and second sentence mostly, but also looking in-app, the section for variables is pretty front and center as an option for users.

2022-08-02 20:20 UTC, kayayarai commented
Opened https://datadoghq.atlassian.net/browse/DOCS-3882 to track editorial review

2022-08-02 21:22 UTC, alai97 commented on content/en/synthetics/browser_tests/actions.md
> +If you want to use a variable on automatically recorded steps, click **Inject this variable** icon:
```suggestion
If you want to use a variable on automatically recorded steps, click the **Inject this variable** icon:
```

2022-08-03 07:22 UTC, HugoPct commented on content/en/synthetics/browser_tests/_index.md
> +{{< img src="synthetics/browser_tests/recording_inject_variable.mp4" alt="Injecting a local variable into a field during a browser recording" video="true" width="90%" >}}
this new vid is very cool!

2022-08-03 07:22 UTC, HugoPct commented on content/en/synthetics/browser_tests/_index.md
> +    | `{{#is_recovery}}`         | Show when the monitor recovers from alert.                          |
```suggestion
    | `{{#is_recovery}}`         | Show when the monitor recovers from `alert`.                          |
```

2022-08-03 07:22 UTC, HugoPct commented on content/en/synthetics/browser_tests/_index.md
> +    | `{{^is_recovery}}`         | Show unless the monitor recovers from alert.                        |
```suggestion
    | `{{^is_recovery}}`         | Show unless the monitor recovers from `alert`.                        |
```

2022-08-03 07:23 UTC, HugoPct approved these changes
added 2 suggestions otherwise good to go for me

2022-08-04 23:55 UTC, urseberry reviewed
I need to sign off for now, but I'm submitting these comments so they don't get lost. Will finish the review later.

2022-08-04 23:55 UTC, urseberry commented on content/en/agent/troubleshooting/agent_check_status.md
> -[4]: /integrations/
Please revert this change. Removing the link breaks a link above, in the Linux section, on the Agent v5 tab.

2022-08-05 21:11 UTC, closed without merging