[ci-visibility] Add Instructions to set custom tags and metrics
DataDog/documentation pull request #14866
Opened 2022-08-02 16:08 UTC by juan-fernandez

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-04 08:16 UTC, drodriguezhdez approved these changes
LGTM

2022-08-04 09:37 UTC, nachoBonafonte commented
I would remove the word metrics for this documentation, as it is an internal implementation detail and can produce confusion to users. The API just uses setTag and the user sees both kind of values (numeric or strings) mixed in the same place :

You can add custom tags and metrics to your test ... -> You can add custom tags to your test

2022-08-04 09:56 UTC, drodriguezhdez approved these changes

2022-08-04 09:56 UTC, drodriguezhdez commented on content/en/continuous_integration/setup_tests/javascript.md
> +### Adding custom tags and metrics to testss
```suggestion
### Adding custom tags and metrics to tests
```

2022-08-04 10:39 UTC, nachoBonafonte approved these changes

2022-08-04 16:51 UTC, jtappa requested changes

2022-08-04 16:51 UTC, jtappa commented on content/en/continuous_integration/setup_tests/javascript.md
> +You can add custom tags to your test by grabbing the current active span:
```suggestion
You can add custom tags to your tests by using the current active span:
```

2022-08-04 16:51 UTC, jtappa commented on content/en/continuous_integration/setup_tests/javascript.md
> +If you want to create filters or group bys for these tags you need to create facets for them. For more information about custom instrumentation you can read [NodeJS Custom Instrumentation][1].
```suggestion
To create filters or group bys for these tags, you need to create facets for them. For more information about custom instrumentation read the [NodeJS Custom Instrumentation][1] documentation.
```

2022-08-04 16:51 UTC, jtappa commented on content/en/continuous_integration/setup_tests/javascript.md
> +Set `NODE_OPTIONS` environment variable to `-r dd-trace/ci/init`. Run your tests as you normally would, specifying the environment where the tests are run in the `DD_ENV` environment variable. For ex
```suggestion
Set the `NODE_OPTIONS` environment variable to `-r dd-trace/ci/init`. Run your tests as you normally would, specifying the environment where the tests are run in the `DD_ENV` environment variable. For example, set `DD_ENV` to `local` when running tests on a developer workstation, or `ci` when running them on a CI provider:
```

2022-08-04 16:51 UTC, jtappa commented on content/en/continuous_integration/setup_tests/javascript.md
> +If you want to create filters or group bys for these tags you need to create facets for them. For more information about custom instrumentation you can read [NodeJS Custom Instrumentation][1].
```suggestion
To create filters or group bys for these tags, you must create facets for them. For more information about custom instrumentation, read the [NodeJS Custom Instrumentation][1] documentation.
```

2022-08-04 16:51 UTC, jtappa commented on content/en/continuous_integration/setup_tests/javascript.md
> +If you want to create filters or group bys for these tags you need to create facets for them. For more information about custom instrumentation you can read [NodeJS Custom Instrumentation][1].
```suggestion
To create filters or group bys for these tags, you must create facets for them. For more information about custom instrumentation, read the [NodeJS Custom Instrumentation][1] documentation.
```

2022-08-08 18:00 UTC, juan-fernandez commented
any other comment @jtappa ? I've applied all your feedback 😄

2022-08-09 15:56 UTC, alai97 requested changes

2022-08-09 15:56 UTC, alai97 commented on content/en/continuous_integration/setup_tests/javascript.md
> +To create filters or group bys for these tags, you need to create facets for them. For more information about custom instrumentation read the [NodeJS Custom Instrumentation][1] documentation.
```suggestion
To create filters or `group by` fields for these tags, you must first create facets. For more information about custom instrumentation, see the [NodeJS Custom Instrumentation documentation][1].
```

2022-08-09 15:56 UTC, alai97 commented on content/en/continuous_integration/setup_tests/javascript.md
> +You can fix it by setting `NODE_OPTIONS` to the following:
```suggestion
You can fix this by setting `NODE_OPTIONS` to the following:
```

2022-08-09 15:56 UTC, alai97 commented on content/en/continuous_integration/setup_tests/javascript.md
> +To create filters or group bys for these tags, you must create facets for them. For more information about custom instrumentation, read the [NodeJS Custom Instrumentation][1] documentation.
```suggestion
To create filters or `group by` fields for these tags, you must first create facets. For more information about custom instrumentation, see the [NodeJS Custom Instrumentation documentation][1].
```

2022-08-09 15:56 UTC, alai97 commented on content/en/continuous_integration/setup_tests/javascript.md
> +To create filters or group bys for these tags, you must create facets for them. For more information about custom instrumentation, read the [NodeJS Custom Instrumentation][1] documentation.
```suggestion
To create filters or `group by` fields for these tags, you must first create facets. For more information about custom instrumentation, see the [NodeJS Custom Instrumentation documentation][1].
```

2022-08-09 15:57 UTC, alai97 approved these changes

2022-08-09 16:06 UTC, merged