OTLP CONFIG vars take full endpoints not ports
DataDog/documentation pull request #14949
Opened 2022-08-09 19:30 UTC by ajgajg1134

Tested with the latest release candidate of the agent, note this brings this tab into alignment with the `host` tab

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-10 08:00 UTC, gbbr approved these changes
Thanks! Your change is correct!

2022-08-10 08:00 UTC, gbbr commented on content/en/tracing/trace_collection/open_standards/otlp_ingest_in_the_agent.md
> +   - For gPRC: `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT` and value `0.0.0.0:4317`
Can we use "address" or "endpoint" instead of "value"?

2022-08-10 14:09 UTC, gbbr approved these changes

2022-08-10 14:32 UTC, mx-psi reviewed
I think what the sentence was meant to say is that you need to pass the environment variable (with the full endpoint) **and** also expose the port. I left a suggestion to make the wording clearer

2022-08-10 14:32 UTC, mx-psi commented on content/en/tracing/trace_collection/open_standards/otlp_ingest_in_the_agent.md
> +   - For HTTP: `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT` and endpoint `0.0.0.0:4318`
```suggestion
   - For gPRC: Set `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT` to `0.0.0.0:4317` and expose port `4317`
   - For HTTP: Set `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT` to `0.0.0.0:4318` and expose port `4318`.
```

2022-08-10 15:07 UTC, mx-psi approved these changes

2022-08-10 15:51 UTC, buraizu requested changes
Thanks, just a minor edit for consistency.

2022-08-10 15:51 UTC, buraizu commented on content/en/tracing/trace_collection/open_standards/otlp_ingest_in_the_agent.md
> +   - For gPRC: Set `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT` to `0.0.0.0:4317` and expose port `4317`
```suggestion
   - For gPRC: Set `DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT` to `0.0.0.0:4317` and expose port `4317`.
```

2022-08-12 00:22 UTC, buraizu approved these changes

2022-09-23 16:02 UTC, merged