ASM Python: Add user information to traces
DataDog/documentation pull request #14941
Opened 2022-08-09 10:52 UTC by avara1986

### What does this PR do?
Add user information to traces for Python

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-09 11:36 UTC, gnufede approved these changes

2022-08-24 17:56 UTC, buraizu requested changes
Thanks, just made a suggestion to rephrase with active voice as per our [contributing guidelines](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#active-voice).

2022-08-24 17:56 UTC, buraizu commented on content/en/security_platform/application_security/setup_and_configure.md
> +The Python tracer package provides the `set_user` function, which allows you to monitor authenticated requests by adding user information to the trace.
```suggestion
Monitor authenticated requests by adding user information to the trace with the `set_user` function provided by the Python tracer package.
```

2022-08-25 15:15 UTC, buraizu approved these changes

2022-08-25 15:21 UTC, merged