Adding a note about Array objects
DataDog/documentation pull request #14957
Opened 2022-08-10 05:51 UTC by Muizmir

This edit was suggested by a customer when I found out that facets can't be added to Array objects (after consultation with T2 in Logs OH). The workaround is to extract the attribute in Array object and then remap it. The extracted attribute will have the 'create facet' option.

TICKET - https://datadog.zendesk.com/agent/tickets/882141

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-10 16:22 UTC, buraizu commented
Thanks, created DOCS-3920 for tracking.

2022-09-21 15:32 UTC, maycmlee requested changes
Hey @muizmir, sorry about the delay on this one! I made some changes (added info on how to make it an attribute), let me know if that works for you. Sorry I had to make the commit without getting your approval first because I couldn't add it in github.

2022-09-27 00:40 UTC, Muizmir commented
Hi @maycmlee , that looks good to me.

2022-09-27 14:17 UTC, maycmlee approved these changes

2022-09-27 14:46 UTC, merged