Ingestion Controls: Agent Level configuration modal
DataDog/documentation pull request #14969
Opened 2022-08-10 17:51 UTC by dussault-antoine

### What does this PR do?

Add documentation for the new Agent Level configuration modal
[JIRA Epic link](https://datadoghq.atlassian.net/browse/ATAFE-1769)

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-10 18:03 UTC, kayayarai commented
Opened DOCS-3921 to track edit pass

2022-08-11 17:01 UTC, kayayarai requested changes
Some edits, and a couple questions for you.

2022-08-11 17:01 UTC, kayayarai commented on content/en/tracing/trace_pipeline/ingestion_controls.md
> +5. Confirm on the Ingestion Control Page that your new percentage has been applied: the Traffic Breakdown column should surface the sampling rate applied. The ingestion reason for the service should
```suggestion
5. Confirm on the Ingestion Control Page that your new percentage has been applied by looking at the Traffic Breakdown column, which surfaces the sampling rate applied. The ingestion reason for the service is shown as `ingestion_reason:rule`.
```

2022-08-11 19:31 UTC, dussault-antoine commented on content/en/tracing/trace_pipeline/ingestion_controls.md
> +If the monthly usage is under `100%`, the projected ingested data fits in your [monthly allotment][3]. A quota over `100%` means that the monthly ingestion volume is projected to be over your monthly
let's use monthly allotment everywhere
and ingested data

2022-08-11 19:59 UTC, kayayarai commented on content/en/tracing/trace_pipeline/ingestion_controls.md
> +If the monthly usage is under `100%`, the projected ingested data fits in your [monthly allotment][3]. A quota over `100%` means that the monthly ingestion volume is projected to be over your monthly
```suggestion
If the monthly usage is under `100%`, the projected ingested data fits in your [monthly allotment][3]. A monthly usage value over `100%` means that the monthly ingested data is projected to be over your monthly allotment.
```

2022-08-29 17:16 UTC, kayayarai approved these changes

2022-08-30 16:08 UTC, merged