DOCS-3875 Adds Synthetics and CI/CD Troubleshooting
DataDog/documentation pull request #14971
Opened 2022-08-10 20:53 UTC by alai97

### What does this PR do?

Adds Synthetics and CI/CD Troubleshooting page with terminology.

### Motivation

DOCS-3875

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-11 00:26 UTC, buraizu requested changes
Thanks, just made a minor suggestion

2022-08-11 00:26 UTC, buraizu commented on content/en/synthetics/cicd_integrations/troubleshooting.md
> +: A single run of a Synthetic test. If you have configure retries, they count as individual test runs. For example, a test with two retries can have up to three associated test runs.
```suggestion
: A single run of a Synthetic test. If you have configured retries, they count as individual test runs. For example, a test with two retries can have up to three associated test runs.
```

2022-08-11 16:01 UTC, buraizu approved these changes

2022-08-16 08:07 UTC, peculiarism approved these changes

2022-08-16 21:10 UTC, merged