Update cpp.md
DataDog/documentation pull request #15000
Opened 2022-08-14 23:22 UTC by elee0625

### What does this PR do?
C++ Public Docs Modification

### Motivation
Onboarding Initiaitve

### Additional Notes
Content switches were pre-approved by D.Goffredo in an offline sync.
---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-14 23:57 UTC, cgilmour reviewed
This looks reasonable to me and doesn't affect technical aspects of C++ tracing, just makes overall descriptions of tracing setup more consistent.

Someone else would be better to review specific wording warnings and errors - it's not something I'm the appropriate person to judge.

2022-08-15 21:30 UTC, kayayarai requested changes
edit pass

2022-08-15 21:30 UTC, kayayarai commented on content/en/tracing/trace_collection/dd_libraries/cpp.md
> +3. After having instrumented your application, the tracing client sends traces to `localhost:8126` by default.  If this is not the correct host and port change it by setting the below env variables:
```suggestion
3. The tracing client sends traces to `localhost:8126` by default. If this is not the correct host and port for your Agent, set the `DD_AGENT_HOST` and `DD_TRACE_AGENT_PORT` environment variables.
```

2022-08-15 21:30 UTC, kayayarai commented on content/en/tracing/trace_collection/dd_libraries/cpp.md
> +Install and configure the Datadog Agent to receive traces from your now instrumented application. By default the Datadog Agent is enabled in your `datadog.yaml` file under `apm_config` with `enabled:
```suggestion
Install and configure the Datadog Agent to receive traces from your instrumented application. By default the Datadog Agent is enabled in your `datadog.yaml` file under `apm_config` with `enabled: true` and listens for trace traffic at `localhost:8126`. For containerized environments, follow the links below to enable trace collection within the Datadog Agent.
```

2022-08-15 21:30 UTC, kayayarai commented on content/en/tracing/trace_collection/dd_libraries/cpp.md
> +`DD_AGENT_HOST` and `DD_TRACE_AGENT_PORT`.
```suggestion
```

2022-08-15 21:30 UTC, kayayarai commented on content/en/tracing/trace_collection/dd_libraries/cpp.md
> +To connect to the agent using Unix Domain Sockets, `DD_TRACE_AGENT_URL` can be used instead. The value should match the Agent's value for `DD_APM_RECEIVER_SOCKET`.
```suggestion
To connect to the Agent using Unix Domain Sockets, use `DD_TRACE_AGENT_URL` instead. Set it to the same value as the Agent's value for `DD_APM_RECEIVER_SOCKET`.
```

2022-08-15 21:30 UTC, kayayarai commented on content/en/tracing/trace_collection/dd_libraries/cpp.md
> +Tracing is available for a number of other environments, such as  [Heroku][1], [Cloud Foundry][2], [AWS Elastic Beanstalk][3], and [Azure App Service][4].
```suggestion
Tracing is available for other environments, including [Heroku][1], [Cloud Foundry][2], [AWS Elastic Beanstalk][3], and [Azure App Service][4].
```

2022-08-15 21:30 UTC, kayayarai commented on content/en/tracing/trace_collection/dd_libraries/cpp.md
> +For other environments, please refer to the [Integrations][5] documentation for that environment and [contact support][6] if you are encountering any setup issues.
```suggestion
For other environments, see the [Integrations][5] documentation for that environment and [contact support][6] if you encounter setup issues.
```

2022-08-15 21:30 UTC, kayayarai commented on content/en/tracing/trace_collection/dd_libraries/cpp.md
> +## Instrument your Application
```suggestion
## Instrument your application
```

2022-08-15 21:30 UTC, kayayarai commented on content/en/tracing/trace_collection/dd_libraries/cpp.md
> +After the agent is installed, Datadog tracing can be enabled in one of two ways:
```suggestion
After the Agent is installed, follow these steps to add the Datadog tracing library to your C++ applications in one of two ways:
```

2022-08-15 21:47 UTC, kayayarai approved these changes

2022-08-15 21:47 UTC, merged