Initial draft of service accounts page
DataDog/documentation pull request #15033
Opened 2022-08-17 17:56 UTC by urseberry

### What does this PR do?
Create a page to document service accounts

### Motivation
Product manager request

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-09-26 10:04 UTC, louisthaboogie commented on content/en/account_management/org_settings.md
> +[Service accounts][3] are non-human users that can have roles and own application keys. You can use service accounts to access Datadog APIs without having your application or script be associated wit
I would align the copy here with the same headline as the service accounts page. Sounds weird here that we call a service accounts a non human users. Maybe replace it with "Service accounts are non-interactive accounts that can .."

2022-09-26 23:31 UTC, alai97 requested changes
Some copy suggestions. Can you add some Further Reading links to the front matter so the Further Reading partial contains more doc links?

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +Service accounts are non-interactive accounts that can be used to own application keys and other resources that are shared across your teams. Service account application keys can only be viewed once,
```suggestion
Service accounts are non-interactive accounts you can use to own application keys and other resources that are shared across your teams. Service account application keys can only be viewed once by the individual who created the key.
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +4. To save, click **Create Service Account**.
```suggestion
1. Click **New Service Account**. A dialog box appears.
2. Enter a name and email address for your service account.
3. Use the **Assign Roles** drop-down menu to choose one or more roles for your service account.
4. To save, click **Create Service Account**.
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +**Note:** Unlike the email addresses for Datadog users, service account email addresses do not need to be unique across an organization.
```suggestion
Unlike the email addresses for Datadog users, service account email addresses do not need to be unique across an organization.
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +To modify a service account, click on it from the service accounts page.
```suggestion
To modify a service account, click on one in the service accounts list. 
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +3. Click **Save**.
```suggestion

1. In the side panel, click **Edit** next to the service account name. A dialog box appears.
2. Update any fields you would like to change. You can edit the name, email address, status, and roles.
3. Click **Save**.
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +To disable a service account, follow the procedure above to edit the service account. In the pop-up dialog box, set the status to **Disabled**.
```suggestion
To disable a service account, follow the procedure above to edit the service account and set the status to **Disabled**.
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +To create or revoke service account application keys, select the service account on the service accounts page. The service account detailed view side panel appears.
```suggestion
To create or revoke service account application keys, select an account from the service account list. The service account's side panel appears.
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +- Click **Create Key**.
```suggestion

- Click **New Key**. A dialog box appears.
- Give the key a descriptive name.
- Click **Create Key**. 
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +To revoke an application key, find the key in the service account detailed view side panel. Mouse over it, and pencil and trash can icons appear on the right. Click the trash can to revoke the key. A
```suggestion
To revoke an application key, find the key in the service account's side panel and hover over it. A pencil and trash can icon appears on the right. Click the trash can to revoke the key. After the key is revoked, click **Confirm**.
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +By creating a service account, you create an actor that interacts with Datadog on your behalf. Therefore, your capabilities on the service accounts page vary depending on your Datadog roles and permi
```suggestion
By creating a service account, you create an actor that interacts with Datadog on your behalf. Your capabilities on the Service Accounts page vary depending on your Datadog roles and permissions.
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +When you create a service account, you may give it any subset of the roles and permissions that you have. The exception is if you have the User Access Manage permission. Having User Access Manage eff
```suggestion
When creating a service account, you can give it any subset of the roles and permissions that you have. The exception is if you have the User Access Manage permission, which effectively gives you administrator access to do anything in Datadog. Datadog accounts with the User Access Manage permission have no restrictions on the roles and permissions they can assign to service accounts.
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings/service_accounts.md
> +[1]: /account_management/org_settings/
```suggestion

## Further reading

{{< partial name="whats-next/whats-next.html" >}}

[1]: /account_management/org_settings/
```

2022-09-26 23:31 UTC, alai97 commented on content/en/account_management/org_settings.md
>  [1]: /account_management/users/default_roles/
```suggestion

## Further reading

{{< partial name="whats-next/whats-next.html" >}}

[1]: /account_management/users/default_roles/
```

2022-09-28 17:47 UTC, urseberry commented
This is ready for re-review.

2022-09-28 18:29 UTC, alai97 approved these changes
LGTM!

2022-09-28 18:55 UTC, merged