dd-trace-php b3 headers public documentation
DataDog/documentation pull request #15046
Opened 2022-08-18 14:09 UTC by krakjoe

### What does this PR do?
Add public PHP documentation for propagation (b3) headers

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-22 20:04 UTC, maycmlee requested changes
Hey @krakjoe! Left some suggestions and also fixed the links.

By the way, you should be able to clone the documentation repo, rather than fork, so that when you open a PR, a preview of your changes is automatically created.

2022-08-22 20:04 UTC, maycmlee commented on content/en/tracing/trace_collection/library_config/php.md
> +Multiple styles may be used, comma separated.
```suggestion
If using multiple styles, comma separate them.
```

2022-08-24 05:57 UTC, krakjoe commented
> Hey @krakjoe! Left some suggestions and also fixed the links.
> 
> By the way, you should be able to clone the documentation repo, rather than fork, so that when you open a PR, a preview of your changes is automatically created.

Thank you for the hint, and suggestions :)

2022-08-24 13:53 UTC, maycmlee reviewed
Hey @krakjoe! Is it okay to move that last line up? I'm having problems formatting it at the end (can't get it to flushed left for some reason). https://a.cl.ly/mXu2Rzgv

2022-08-24 13:53 UTC, maycmlee commented on content/en/tracing/trace_collection/library_config/php.md
> +If using multiple styles, comma separate them.
```suggestion
```

2022-08-24 13:53 UTC, maycmlee commented on content/en/tracing/trace_collection/library_config/php.md
> +Propagation styles to use when injecting tracing headers. The supported styles are:
```suggestion
Propagation styles to use when injecting tracing headers. If using multiple styles, comma separate them. The supported styles are:
```

2022-08-24 13:53 UTC, maycmlee commented on content/en/tracing/trace_collection/library_config/php.md
> +
```suggestion
```

2022-08-24 13:53 UTC, maycmlee commented on content/en/tracing/trace_collection/library_config/php.md
> +If using multiple styles, comma separate them.
```suggestion
```

2022-08-24 13:53 UTC, maycmlee commented on content/en/tracing/trace_collection/library_config/php.md
> +
```suggestion
```

2022-08-24 13:53 UTC, maycmlee commented on content/en/tracing/trace_collection/library_config/php.md
> +Propagation styles to use when extracting tracing headers. The supported styles are:
```suggestion
Propagation styles to use when extracting tracing headers. If using multiple styles, comma separate them. The supported styles are:
```

2022-08-30 13:24 UTC, maycmlee approved these changes

2022-08-30 13:26 UTC, merged