ASM Python: Enable python link in getting started page
DataDog/documentation pull request #15041
Opened 2022-08-18 09:15 UTC by avara1986

### What does this PR do?
Enable Python logo/link in https://docs.datadoghq.com/security_platform/application_security/getting_started/#prerequisites
---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-23 17:54 UTC, gnufede approved these changes

2022-08-24 16:49 UTC, buraizu approved these changes

2022-08-25 09:21 UTC, juanjux approved these changes

2022-08-25 09:30 UTC, avara1986 commented
One more review of @DataDog/corpweb please? :smile:

2022-08-25 15:15 UTC, bgdeutsch requested changes
looks like the mobile layout is broken by these changes: https://a.cl.ly/eDu7zyxY

i believe we should only need one `div.card-deck` parent element with all the language cards under that element.

2022-08-25 18:47 UTC, merged