adding in suggested tags feature beta banner as well as new demo video
DataDog/documentation pull request #15103
Opened 2022-08-24 15:07 UTC by annasun19

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-24 19:44 UTC, ijkaylin approved these changes

2022-08-25 00:54 UTC, buraizu requested changes
Thanks, made a few minor suggestions for accessibility and as per our contributing guidelines.
https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#first-and-second-person-pronouns

2022-08-25 00:54 UTC, buraizu commented on content/en/metrics/metrics-without-limits.md
> +As a beta feature of Metrics without Limits, we can prepopulate the tag configuration modal by default with an allowlist of tags that are actively queried on dashboards/notebooks/monitors for the pas
```suggestion
As a beta feature of Metrics without Limits, you can pre-populate the tag configuration modal by default with an allowlist of tags that have been actively queried on dashboards, notebooks, or monitors in the past 30 days (colored in blue with an icon). You may include additional tags as well. 
```

2022-08-25 00:54 UTC, buraizu commented on content/en/metrics/metrics-without-limits.md
> +As a beta feature of Metrics without Limits, we can prepopulate the tag configuration modal with an allowlist of aggregations that are actively queried on dashboards/notebooks/monitors for the past 3
```suggestion
As a beta feature of Metrics without Limits, you can pre-populate the tag configuration modal with an allowlist of aggregations that have been actively queried on dashboards, notebooks, or monitors in the past 30 days (colored in blue with an icon). 
```

2022-08-26 20:18 UTC, hestonhoffman approved these changes

2022-08-26 20:18 UTC, merged