Why is my "Save" button disabled? FAQ section
DataDog/documentation pull request #15147
Opened 2022-08-29 21:03 UTC by annasun19

### What does this PR do?
Create a new FAQ section explaining why some Metrics without Limits tag configurations cause the save button to be disabled.

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-29 21:49 UTC, apigirl commented
the editorial review tracked in DOCS-4012

2022-09-02 16:27 UTC, jtappa requested changes

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +This is not a bug but intentional. The "Save" button is disabled in infrequent scenarios where it is more cost effective to leave this metric entirely unconfigured without using Metrics without Limit
```suggestion
It is possible for a proposed configuration to result in an indexed custom metrics volume that is larger than the original ingested volume. The "Save" button is intentionally disabled in infrequent scenarios where it is more cost effective to leave a metric entirely unconfigured without using Metrics without Limits™. 
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +As a quick refresher on Metrics without Limits (more details [here](https://docs.datadoghq.com/metrics/metrics-without-limits/)), you can continue sending us their originally submitted volume of metr
```suggestion
Using [Metrics without Limits™][1], you can continue sending Datadog your originally submitted volume of metrics with no code-level changes, and define a tag configuration to keep only a smaller subset of custom metrics to index. 
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +By using MWL, your original raw metric’s data must now be recombined/reaggregated and stored against that smaller volume of indexed custom metrics in order to preserve mathematically accurate query r
```suggestion
By using Metrics without Limits™, your original raw metrics data must be recombined and re-aggregated, and stored against that smaller volume of indexed custom metrics in order to preserve mathematically accurate query results. Therefore, for each of the remaining indexed custom metrics, Datadog stores your specified number of time/space aggregations. 
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +The resulting number of indexed custom metrics for your MWL configuration is (`the # of remaining tag value combinations`–specified by your tag configuration) x (`the # of time/space aggregations`–sp
```suggestion
The resulting number of indexed custom metrics for your Metrics without Limits™ configuration is (`the number of remaining tag value combinations`—specified by your tag configuration) x (`the number of time/space aggregations`—specified by the Customize Aggregations section)
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +Suppose we want to use Metrics without Limits to reduce the cardinality of the `shopist.basket.size` metric.
```suggestion
Suppose you want to use Metrics without Limits™ to reduce the cardinality of the `shopist.basket.size` metric. 
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +Let’s assume `shopist.basket.size` reports values against 4 tag value combinations, like {host: a, region: us, env: prod}–that is, `shopist.basket.size` originally emits **4 custom metrics** as shown
```suggestion
Assuming `shopist.basket.size` reports values against four tag value combinations, such as {host: a, region: us, env: prod}—that is, `shopist.basket.size` originally emits **four custom metrics** as shown in the following diagram:
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +If we use MWL to tag configure only the {region, env} tags, only three tag value combinations remain:
```suggestion
Using Metrics without Limits™ to tag configure only the `{region, env}` tags, only three tag value combinations remain:
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +3. {region:us, env:staging}
```suggestion
* `{region:us, env:prod}`
* `{region:eu, env:prod}`
* `{region:us, env:staging}`
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +The resulting number of custom metrics from this proposed configuration is as follows: (`the # of remaining tag value combinations`) x (`the # of time/space aggregations`) = (3) x (2) = **6 custom me
```suggestion
The resulting number of custom metrics from this proposed configuration is as follows: (`the number of remaining tag value combinations`) x (`the number of time/space aggregations`) = `(3) x (2)` = **6 custom metrics**.
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +Consequently, it’s possible for a proposed configuration to result in an indexed custom metrics volume (6 custom metrics) that is larger than the original ingested volume (4 custom metrics). **In the
```suggestion
Therefore, it is possible for a proposed configuration to result in an indexed custom metrics volume (6 custom metrics) that is larger than the original ingested volume (4 custom metrics). **In these cases, it is better to leave this metric unconfigured with the “All Tags” toggle option for the most cost-optimized configuration of this metric.**

[1]: /metrics/metrics-without-limits/
```

2022-09-02 16:27 UTC, jtappa commented on content/en/metrics/faq/why-is-my-save-button-disabled.md
> +title: Why is my "Save" button disabled?
```suggestion
title: Why is my "Save" button disabled when configuring metrics tags?
```

2022-09-07 17:10 UTC, jtappa approved these changes

2022-09-07 17:21 UTC, merged