DOCS-3994 Adds SwiftUI Documentation
DataDog/documentation pull request #15161
Opened 2022-08-30 23:58 UTC by alai97

### What does this PR do?

Adds single sourcing logic and generates a preview for a SwifUI doc page.

### Motivation

DOCS-3994

### Additional Notes

Remember to update the staging branch back to `main` and update the `pull_config.yaml` file before merging!

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-08-31 14:18 UTC, maxep requested changes
Thanks @alai97 🙏 

It will be best to rename `Swift` -> `SwiftUI`

2022-08-31 14:18 UTC, maxep commented on config/_default/menus/menus.en.yaml
> +  - name: Swift
```suggestion
  - name: SwiftUI
```

2022-08-31 14:18 UTC, maxep commented on config/_default/menus/menus.en.yaml
> +    url: real_user_monitoring/ios/swift/
```suggestion
    url: real_user_monitoring/ios/swiftui/
```

2022-08-31 14:18 UTC, maxep commented on config/_default/menus/menus.en.yaml
> +    identifier: rum_ios_swift
```suggestion
    identifier: rum_ios_swiftui
```

2022-09-01 18:23 UTC, hestonhoffman approved these changes
Fixed the build issue in the other PR. Looks good

2022-09-01 18:27 UTC, maxep approved these changes
Looks great 🚀

2022-09-01 18:27 UTC, maxep commented on config/_default/menus/menus.en.yaml
> +    weight: 301
I think we can move this down the `Advanced Configuration` section, makes sense to have this close to `Mobile Vitals` and `Web View Tracking`

2022-09-06 23:22 UTC, merged