content/en/tracing/trace_collection/open_standards: warn about gateway deploys
DataDog/documentation pull request #15206
Opened 2022-09-05 12:45 UTC by gbbr

This change ensures to underline the fact that Datadog is only compatible with Gateway deployments where an agent is deployed on each application host, by adding a warning that looks like this:

<img width="858" alt="Screenshot 2022-09-05 at 15 43 51" src="https://user-images.githubusercontent.com/6686356/188452382-07eda640-d2e5-4d5a-8efc-161be299e2ba.png">

2022-09-06 15:55 UTC, pj-datadog requested changes
I don't agree with this note and it should not be merged for the following reasons:
1. It will deter potential OTel customers from even trying Datadog
2. Gateway is the most common way to use OTel collector for OTel customers
3. We should look into how we can solve this problem rather than calling it out

2022-09-06 16:00 UTC, dineshg13 requested changes

2022-09-06 16:06 UTC, dineshg13 commented on content/en/tracing/trace_collection/open_standards/otel_collector_datadog_exporter.md
> +Datadog is incompatible with Gateway deployments which do not have a Collector agent deployed running on each application host. Such a set up will result in a broken product exprience.
a diagram explaining each mode would also be good to add.

2022-09-06 17:10 UTC, gbbr commented on content/en/tracing/trace_collection/open_standards/otel_collector_datadog_exporter.md
> +Datadog is incompatible with Gateway deployments which do not have a Collector agent deployed running on each application host. Such a set up will result in a broken product exprience.
Since you have the most background here and proposed this change to begin with, I will let you take over this PR.

2022-09-06 19:24 UTC, cswatt requested changes

2022-09-06 19:24 UTC, cswatt commented on content/en/tracing/trace_collection/open_standards/otel_collector_datadog_exporter.md
> +Datadog is incompatible with Gateway deployments which do not have a Collector agent deployed running on each application host. Such a set up will result in a broken product exprience.
```suggestion
Datadog is incompatible with Gateway deployments, which do not have a Collector agent deployed running on each application host. Such a set up results in a broken product experience.
```

2022-09-06 21:05 UTC, dineshg13 commented on content/en/tracing/trace_collection/open_standards/otel_collector_datadog_exporter.md
> +Datadog is incompatible with Gateway deployments which do not have a Collector agent deployed running on each application host. Such a set up will result in a broken product exprience.
sure . Will take this forward.

2023-03-01 21:44 UTC, hestonhoffman commented
@dineshg13 This PR has been open for a while and it looks like you took over ownership. Are you still working on this?

2026-08-03 19:07 UTC, jhgilbert commented
This PR was closed after six or more months of inactivity. If this was done in error, feel free to re-open the PR.

2026-08-03 19:07 UTC, closed without merging