content/en/tracing/trace_collection/open_standards: update examples
DataDog/documentation pull request #15275
Opened 2022-09-14 09:21 UTC by gbbr

Update public docs to match https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13842 and https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14119

2022-09-14 11:31 UTC, mx-psi approved these changes

2022-09-14 19:37 UTC, kayayarai requested changes

2022-09-14 19:37 UTC, kayayarai commented on content/en/tracing/trace_collection/open_standards/otel_collector_datadog_exporter.md
> +   In this case, we do not want to use the `hostmetrics` receiver because those metrics will be emitted by the Datadog Agent.
```suggestion
   In this case, don't use the `hostmetrics` receiver because those metrics will be emitted by the Datadog Agent.
```

2022-09-14 19:38 UTC, kayayarai approved these changes
Committed a small edit. Let me know if you are ready for this to be merged.

2022-09-15 06:49 UTC, gbbr commented
@kayayarai thanks! I think this can be merged at any time. We are still working on getting more out of these, but they should be able to provide benefit today as they are.

2022-09-15 15:09 UTC, merged