[DOCS-4044] Update and move Reference Tables doc
DataDog/documentation pull request #15287
Opened 2022-09-14 19:02 UTC by maycmlee

### What does this PR do?

Adds Validation Rules section
Updates the Reference Tables doc so it's not only for logs. 
Moves docs, and images, to integrations guide folder.

### Motivation

DOCS-4044

### Additional Notes

Do not merge until validation rules functionality is rolled out (early October).

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-09-21 21:19 UTC, dflorea reviewed
The changes look good. I would like to hold off on merging until the validation checks are available.

2022-09-22 22:52 UTC, kayayarai requested changes
Tiny text comment, but also, I think you want to add a `{{< nextlink` link to this in `/integrations/guide/_index.md`, and maybe remove the old one in `logs/guide/_index.md`. Or maybe leave that second one because it is closely related to logs? 🤷‍♀️

2022-09-22 22:52 UTC, kayayarai commented on content/en/integrations/guide/reference-tables.md
> +| Names and headers must start with a lowercase letter. 							| Uppercase characters are converted to lowercase. Other characters are removed. For example, `23Two_three` becomes `two_three`.	|
```suggestion
| Names and headers must start with a lowercase letter. 							| Uppercase characters are converted to lowercase. Non-letter leading characters are removed. For example, `23Two_three` becomes `two_three`.	|
```

2022-09-23 14:56 UTC, maycmlee commented
> Tiny text comment, but also, I think you want to add a `{{< nextlink` link to this in `/integrations/guide/_index.md`, and maybe remove the old one in `logs/guide/_index.md`. Or maybe leave that second one because it is closely related to logs? 🤷‍♀️

Thanks @kayayarai! I forgot about the guide indexes. I removed it from the `logs/guide/_index.md` and added the link in /integrations/guide/_index.md`. I also added a space to all the `tag=<tag_name>` because it was aesthetically bothering me that there was no space between the title and tags: https://a.cl.ly/E0uZYvqQ

Could you re-review?

2022-09-23 15:20 UTC, kayayarai approved these changes

2022-10-13 19:11 UTC, merged