Bryce/update aws tile reference
DataDog/documentation pull request #15288
Opened 2022-09-14 19:36 UTC by buraizu

### What does this PR do?
- Update references to the AWS integration tile
- Replace outdated screenshots
- Minor copy edits

### Motivation
DOCS-3898

### Previews

https://docs-staging.datadoghq.com/bryce/update-aws-tile-reference/account_management/billing/aws/#aws-resource-exclusion

https://docs-staging.datadoghq.com/bryce/update-aws-tile-reference/integrations/guide/aws-integration-and-cloudwatch-faq/

https://docs-staging.datadoghq.com/bryce/update-aws-tile-reference/integrations/guide/error-datadog-not-authorized-sts-assume-role/

https://docs-staging.datadoghq.com/bryce/update-aws-tile-reference/integrations/guide/monitor-your-aws-billing-details/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-09-14 19:50 UTC, kayayarai approved these changes
You might want to consider not deleting the old images, as the translated pages will still try to use them until the translation pipeline catches up. We generally do a scan of unused images every few months to delete them after they aren't used anymore.

2022-09-15 12:44 UTC, warrierr requested changes
Just these few adjustments

2022-09-15 12:44 UTC, warrierr commented on content/en/account_management/billing/aws.md
> +Use the [Datadog-AWS integration page][3] to control your metric collection. Select the AWS account and click on the **Metric Collection** tab. Under **Limit Metric Collection to Specific Resources**
```suggestion
You can limit the AWS metrics collected for some services to specific resources. On the [Datadog-AWS integration page][3], select the AWS account and click on the **Metric Collection** tab. Under **Limit Metric Collection to Specific Resources** you can then exclude metrics for one or more of EC2, Lambda, ELB, Application ELB, Network ELB, RDS, SQS, and CloudWatch custom metrics.
```

2022-09-15 12:44 UTC, warrierr commented on content/en/account_management/billing/aws.md
>  **Note**: Datadog does not charge for ELB metrics, as they can’t be filtered out.
```suggestion
**Note**: Only EC2 (hosts), Lambda (active functions), and CloudWatch Custom Metrics (custom metrics) are billable by Datadog. Metrics integrated for the other services you can filter do not incur Datadog charges.
```

2022-09-15 12:44 UTC, warrierr commented on content/en/account_management/billing/aws.md
>  **Note**: Host resource exclusion settings apply to both EC2 and its attached EBS volumes.
```suggestion
**Note**: EC2 metrics resource exclusion settings apply to both EC2 and its attached EBS volumes. 
```

2022-09-15 15:02 UTC, warrierr approved these changes

2022-09-15 15:57 UTC, merged