DOCS-3930 Moving Around the Synthetic Testing Tunnel
DataDog/documentation pull request #15316
Opened 2022-09-19 21:55 UTC by alai97

### What does this PR do?

Updates CI/CD Integration links, shuffles some content around, and adds aliases.

### Motivation

DOCS-3930

### Additional Notes

Remember to update the `pull_config.yaml` file before merging!
---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-09-20 08:19 UTC, peculiarism commented on content/en/continuous_testing/_index.md
> +{{< img src="synthetics/ci_results_explorer/ci_results_explorer_1.png" alt="CI Results Explorer" style="width:100%;">}}
Could we update this image with this: https://a.cl.ly/Kou1lnBQ

2022-09-20 11:41 UTC, peculiarism requested changes
@alai97 A few changes, but I think we should definitely sync on this

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/_index.md
> +Leverage your Synthetic tests as [canary deployments][3] or run them directly in your [CI pipelines][3].
```suggestion
Leverage your Synthetic tests as [integration and end-to-end tests][3] for your staging, pre-prod or canary deployments, or run them directly in your [CI pipelines][3].
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/_index.md
> +With **end-to-end testing in production and CI environments**, your development teams can proactively ensure that defective code does not impact your users' experience.
```suggestion
With **integration and end-to-end testing in production and CI environments**, your development teams can proactively ensure that defective code does not impact your users' experience. 
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/_index.md
> +Explore browser tests running in a CI pipeline and troubleshoot failing test results by looking at executed jobs in the [CI Results Explorer][4].
```suggestion
Explore integration and end-to-end tests running in a CI/CD pipeline and troubleshoot failing test results by looking at executed jobs in the [CI Results Explorer][4].
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/cicd_integrations/testing_tunnel.md
> +Datadog recommends using the testing tunnel if you are willing to launch Synthetics tests from your CI/CD pipeline or against local versions of your application without deploying a dedicated and long
```suggestion
Datadog recommends using the testing tunnel if you need to launch Synthetics tests against local versions of your application without deploying a dedicated and long lasting probing system (such as [private locations][1]). The testing tunnel can be used to trigger tests on ephemeral cloud environments.
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/troubleshooting.md
> +title: Synthetics and CI/CD Troubleshooting
```suggestion
title: Continuous Testing and CI/CD Troubleshooting
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/troubleshooting.md
> +description: Learn about Synthetics and CI/CD concepts and troubleshoot common errors.
```suggestion
description: Learn about Continuous Testing and CI/CD concepts and troubleshoot common errors.
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/troubleshooting.md
> +Check whether you are using API endpoints to trigger your CI/CD test runs. In order to populate the CI Results Explorer with CI metadata, you must use the [NPM package][5].
```suggestion
Check whether you are using API endpoints to trigger your CI/CD test runs. In order to populate the CI Results Explorer with CI metadata, you must use one of our integrations under [CI/CD integrations][3].
```

Thinking we should point to the GitHub Action, Circle CI orb, Azure DevOps Extension and Jenkins integration, before deferring them to the NPM package.

2022-09-20 11:41 UTC, peculiarism commented on content/en/synthetics/private_locations/_index.md
> +In order to use private locations for continuous testing, the value you set for the `concurrency` parameter is the concurrency limit. For more information, see [Continuous Testing][23].
```suggestion
In order to use private locations for continuous testing, the value set in the `concurrency` parameter will control your parallelization. For more information, see [Continuous Testing][23].
```

I will follow up with you on this outside this PR

2022-09-20 11:41 UTC, peculiarism commented on local/bin/py/build/configurations/pull_config_preview.yaml
> +          title: Synthetics and CI CircleCI Orb
```suggestion
          title: Continuous Testing and CircleCI Orb
```

2022-09-20 11:41 UTC, peculiarism commented on local/bin/py/build/configurations/pull_config_preview.yaml
>            title: Synthetics and CI GitHub Actions
```suggestion
          title: Continuous Testing and GitHub Actions
```

2022-09-20 11:41 UTC, peculiarism commented on local/bin/py/build/configurations/pull_config_preview.yaml
>            title: Synthetics and Datadog CI Azure DevOps Extension
```suggestion
          title: Continuous Testing and Datadog CI Azure DevOps Extension
```

2022-09-20 11:41 UTC, peculiarism commented on data/partials/home.yaml
> +        desc: Implement codeless end-to-end testing using CI/CD providers
```suggestion
        desc: Implement codeless integration and end-to-end testing using CI/CD providers 
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/cicd_integrations/configuration.md
> +  text: "Use Datadog's GitHub Action to add Synthetic testing to workflows"
```suggestion
  text: "Use Datadog's GitHub Action to add continuous testing to workflows"
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/cicd_integrations/configuration.md
> +description: Configure Synthetics to run tests in your CI/CD pipelines.
```suggestion
description: Configure Continuous Testing to run tests in your CI/CD pipelines.
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/cicd_integrations/configuration.md
> +title: Synthetics and CI/CD Configuration
```suggestion
title: Continuous Testing and CI/CD Configuration
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/_index.md
> +  text: 'Synthetic Tests in a CI/CD Pipeline'
```suggestion
  text: 'Continuous Testing in a CI/CD Pipeline'
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/_index.md
> +  text: 'Synthetics and CI/CD Troubleshooting'
```suggestion
  text: 'Continuous Testing and CI/CD Troubleshooting'
```

2022-09-20 11:41 UTC, peculiarism commented on content/en/continuous_testing/_index.md
> +description: With test automation, use fast, codeless, and reliable testing in your CI pipelines to ship features with confidence.
```suggestion
description: With test automation, use fast, codeless, and reliable testing in your CI/CD pipelines to ship features with confidence.
```

2022-09-20 11:41 UTC, peculiarism commented on config/_default/menus/menus.en.yaml
> +  - name: CI Results Explorer
```suggestion
  - name: Explorer
```
We're planning to rename the left nav to `Explorer` soon

2022-09-20 23:12 UTC, alai97 commented on content/en/continuous_testing/troubleshooting.md
> +## CI Results Explorer
```suggestion
## Explorer
```

2022-10-11 20:08 UTC, alai97 commented on content/en/continuous_testing/_index.md
> +Performing tests in a unified monitoring platform allows you to quickly find the root cause of failed test runs and reduce MTTR. You can obtain the full context for troubleshooting—without switching
```suggestion
Performing tests in a unified monitoring platform allows you to quickly find the root cause of failed test runs and reduce MTTR. You can obtain the full context for troubleshooting—without switching between tools— through correlated metrics, traces, and logs surfaced by the Datadog [APM integration][8]. 
```

2022-10-11 20:08 UTC, alai97 commented on content/en/continuous_testing/_index.md
> +[7]: /continuous_testing/cicd_integrations/configuration
```suggestion
[7]: /continuous_testing/cicd_integrations/configuration
[8]: /synthetics/apm/
```

2022-10-11 22:03 UTC, alai97 commented on content/en/continuous_testing/settings/_index.md
> +* Reduce pipeline duration and ship new features faster
No, I like the variety!

2022-10-12 20:51 UTC, alai97 commented on config/_default/menus/menus.en.yaml
> +    pre: synthetics
```suggestion
    pre: continuous-testing
```

2022-10-17 19:24 UTC, peculiarism approved these changes
![giphy (2)](https://user-images.githubusercontent.com/13347714/196264671-567eb871-7e1f-44d7-8eaa-54dea8ab9b82.gif)

2022-10-17 22:39 UTC, jtappa requested changes
I left some suggestions, but overall the Continuous Testing index page needs some editing to make it less marketing-focused and more documentation-focused. We shouldn't be using buzzwords and jargon here, and should avoid making abstract claims about speed, reliability, or ease of use.

2022-10-17 22:46 UTC, alai97 commented on content/en/continuous_testing/_index.md
> +description: With Continuous Testing, use fast, codeless, and reliable testing in your CI/CD pipelines to ship features with confidence.
```suggestion
description: Set parallelization settings for Synthetic tests running in CI/CD pipelines.
```

2022-10-17 23:01 UTC, alai97 commented on content/en/continuous_testing/troubleshooting.md
> +This page provides information to help you troubleshoot issues with Continuous Testing and CI/CD. If you need additional help, contact [Datadog support][1].
Asking Beth!

2022-10-17 23:08 UTC, alai97 commented on content/en/continuous_integration/_index.md
> +<div class="alert alert-info">This page is about bringing your continuous integration (CI) metrics and data into Datadog dashboards. If you want to run Continuous Testing tests in your CI pipelines,
```suggestion
<div class="alert alert-info">This page is about bringing your continuous integration (CI) metrics and data into Datadog dashboards. If you want to run Synthetic tests in your CI pipelines, see the <a href="/continuous_testing/cicd_integrations/" target="_blank">Continuous Testing and CI/CD</a> section.</div>
```

2022-10-17 23:12 UTC, alai97 commented on content/en/continuous_testing/cicd_integrations/_index.md
>  description: Run Synthetic tests on-demand or at predefined intervals in your CI/CD pipelines.
```suggestion
description: Run Continuous Testing tests on-demand or at predefined intervals in your CI/CD pipelines.
```

2022-10-18 20:45 UTC, merged