[DOCS-3964] Add more details to troubleshooting section in Eventbridge guide
DataDog/documentation pull request #15358
Opened 2022-09-22 21:00 UTC by maycmlee

## What does this PR do?

Add more detailed steps.

### Motivation

DOCS-3964

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-09-22 21:47 UTC, alai97 requested changes
Some copy feedback!

2022-09-22 21:47 UTC, alai97 commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +    - If you are utilizing the events endpoint, you will need to include a `title` and `text` as `body.field` parameters in the API Destination connection. These are required values to `POST` to the
```suggestion
    - If you are utilizing the events endpoint, you need to include a `title` and `text` as `body.field` parameters in the API Destination connection. These are required values to `POST` to the events endpoint. For more information, see the [Post an event documentation][9].
```

2022-09-22 21:47 UTC, alai97 commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +2. Once you've set up the destination, you can now follow the Amazon instructions to [create an EventBridge rule][10], where you set Datadog as your destination.
```suggestion
2. Once you have set up the destination, see the Amazon documentation to [create an EventBridge rule][10], where you set Datadog as your destination.
```

2022-09-22 21:47 UTC, alai97 commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +3. Once you've set up the rule with Datadog as the destination, trigger an event by posting an event to EventBridge. For more information about pushing events to EventBridge from Datadog, see the [Ev
```suggestion
3. Once you have set up the rule with Datadog as the destination, trigger an event by posting an event to EventBridge. For more information about pushing events to EventBridge from Datadog, see the [EventBridge integration documentation][1]. For example, to trigger a test event by [uploading the objects to an S3 bucket][11] in your account, use this AWS CloudShell command:
```

2022-09-22 21:47 UTC, alai97 commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +4. Once events and logs are sending, after about five minutes, the data is available in the Datadog [logs console][12] or [events explorer][13], depending on which endpoint you are sending them to.
```suggestion
4. Once events and logs are sending, after about five minutes, the data is available in the Datadog [Logs Console][12] or [Events Explorer][13], depending on which endpoint you are sending them to.
```

2022-09-22 21:47 UTC, alai97 commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +You can set up an Amazon SQS queue to see more details regarding the payloads sent to Datadog and view the response of the API endpoints.
```suggestion
To see more details about the payloads sent to Datadog and to view the response of the API endpoints, set up an Amazon SQS queue:  
```

2022-09-22 21:47 UTC, alai97 commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +1. Create a new queue in [Amazon SQS][14].
```suggestion
1. Create a queue in [Amazon SQS][14].
```

2022-09-22 21:47 UTC, alai97 commented on content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
> +3. Select the **Targets** tab, and then click **Edit**.
```suggestion
3. Select the **Targets** tab and click **Edit**.
```

2022-09-23 14:04 UTC, maycmlee commented
Thanks @alai97! Accepted all suggestions, could you re-review?

2022-09-23 15:20 UTC, alai97 approved these changes

2022-09-23 15:29 UTC, merged