Backend added tags documentation
DataDog/documentation pull request #15409
Opened 2022-09-28 14:01 UTC by dussault-antoine

### What does this PR do?

Document backend added span tags as unusable to exclude traces at the Agent Level

### Motivation

https://datadoghq.atlassian.net/browse/APMS-7745

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-09-28 14:44 UTC, yoannrobin approved these changes

2022-09-28 16:52 UTC, alai97 requested changes
Some copy suggestions!

2022-09-28 16:52 UTC, alai97 commented on content/en/tracing/guide/ignoring_apm_resources.md
> +**Note**: Filtering traces this way removes these requests from [trace metrics][3]. For information on how to reduce ingestion without affecting the trace metrics, see [ingestion controls][4]
```suggestion
Filtering traces this way removes these requests from [trace metrics][3]. For more information on how to reduce ingestion without affecting the trace metrics, see [Ingestion Controls][4].
```

2022-09-28 16:52 UTC, alai97 commented on content/en/tracing/guide/ignoring_apm_resources.md
> +The following span tags are created and added to spans after ingestion on the Datadog backend side. Hence, these tags cannot be used to drop traces at the Datadog Agent level.
```suggestion
On the backend, Datadog creates and adds the following span tags to spans after ingestion. These tags cannot be used to drop traces at the Datadog Agent level.
```

2022-09-28 16:52 UTC, alai97 commented on content/en/tracing/guide/ignoring_apm_resources.md
> +| `http.useragent_details.device.family`  | The Device family reported by the User-Agent     |
```suggestion
| `http.path_group`                       | The full URL path from the `http.url` tag.        |
| `http.url_details.host`                 | The host name portion of the `http.url` tag.      |
| `http.url_details.path`                 | The full request target as passed in an HTTP request line or equivalent. |
| `http.url_details.scheme`               | The request scheme from the `http.url` tag.       |
| `http.url_details.queryString`          | The query string portion from the `http.url` tag. |
| `http.url_details.port`                 | The HTTP port from the `http.url` tag.            |
| `http.useragent_details.os.family`      | The OS family reported by the User-Agent.         |
| `http.useragent_details.browser.family` | The browser family reported by the User-Agent.    |
| `http.useragent_details.device.family`  | The device family reported by the User-Agent.     |
```

2022-09-29 16:02 UTC, alai97 approved these changes

2022-09-29 16:02 UTC, merged