SLO List widget
DataDog/documentation pull request #15402
Opened 2022-09-27 19:59 UTC by kaixintai

### What does this PR do?

Add docs for the new SLO List widget

### Motivation

https://docs-staging.datadoghq.com/kai/slo-list-widget/dashboards/widgets/slo_list/

### Additional Notes

The SLO List and Summary widgets are also supported for scheduled dashboard reporting.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-09-27 22:00 UTC, urseberry commented
Docs editorial review on DOCS-4149

2022-10-04 18:09 UTC, alai97 requested changes
Some copy suggestions!

2022-10-04 18:09 UTC, alai97 commented on content/en/dashboards/widgets/slo_list.md
> +{{< img src="dashboards/widgets/slo_list/slo_list_editor.png" alt="slo list widget editor" >}}
```suggestion
{{< img src="dashboards/widgets/slo_list/slo_list_editor.png" alt="A search query defining the service as web-store in the SLO List widget editor" style="width:90%;" >}}
```

2022-10-04 18:09 UTC, alai97 commented on content/en/dashboards/widgets/slo_list.md
> +{{< img src="dashboards/widgets/slo_list/slo_list_widget.png" alt="slo list widget" >}}
```suggestion
{{< img src="dashboards/widgets/slo_list/slo_list_widget.png" alt="The SLO List widget displaying a list of SLOs" style="width:90%;" >}}
```

2022-10-04 18:09 UTC, alai97 commented on content/en/dashboards/widgets/slo_list.md
> +2. Use tags to filter the list of SLOs (e.g., `service:foo, env:prod`). Template variables are supported.
```suggestion
2. Use tags to filter the list of SLOs (such as `service:foo, env:prod`). Template variables are supported. 
```

2022-10-04 18:09 UTC, alai97 commented on content/en/dashboards/widgets/slo_list.md
> +3. Choose the maximum number of SLOs to display (default is 100). The most recently created SLOs will appear at the top of the list.
```suggestion
3. Choose the maximum number of SLOs to display (the default is 100). The most recently created SLOs appear at the top of the list. 
```

2022-10-04 18:09 UTC, alai97 commented on content/en/dashboards/widgets/slo_list.md
> +4. Optionally, give the widget a title.
```suggestion
4. Optionally, give the widget a title.

When you are ready to create the widget, click **Save**.
```

2022-10-04 18:09 UTC, alai97 commented on content/en/dashboards/widgets/slo_list.md
> +  text: "Track the status of all your SLOs in Datadog"
```suggestion
  text: "Track the status of all your SLOs in Datadog"
- link: "/dashboards/graphing_json/"
  tag: "Documentation"
  text: "Building Dashboards using JSON" 
```

2022-10-04 19:54 UTC, kaixintai reviewed
Ok! I applied your changes, I hope I got all of them. Can you help me merge this once it's approved? @alai97

2022-10-04 20:08 UTC, alai97 approved these changes

2022-10-04 20:08 UTC, merged