[DOCS-2840] Update Configure Datadog Agent instructions for Go log collection
DataDog/documentation pull request #15442
Opened 2022-09-30 21:03 UTC by maycmlee

### What does this PR do?

- Add more instructions for Configure the Datadog Agent section.
- Move the Connect Traces and Logs section to after Configure the Datadog Agent
- Copy edits

### Motivation

DOCS-2840

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-10-05 00:22 UTC, buraizu requested changes
Thanks, just a few minor points, and also asked a question

2022-10-05 00:22 UTC, buraizu commented on content/en/logs/log_collection/go.md
> +Once [log collection is enabled][3], set up [custom log collection][4] to tail your log files and send them to Datadog.
Optional suggestion to clarify which logs will be sent (based on questions I've had from customers in the past).

2022-10-06 19:55 UTC, maycmlee commented on content/en/logs/log_collection/go.md
> +4. Run the [Agent’s status subcommand][7] and look for `csharp` under the `Checks` section to confirm logs are successfully submitted to Datadog.
Lol ooops...caught copying and pasting. Thanks for catching this!

2022-10-06 19:55 UTC, maycmlee commented on content/en/logs/log_collection/go.md
> +4. Run the [Agent’s status subcommand][7] and look for `csharp` under the `Checks` section to confirm logs are successfully submitted to Datadog.
```suggestion
4. Run the [Agent’s status subcommand][7] and look for `go` under the `Checks` section to confirm logs are successfully submitted to Datadog.
```

2022-10-07 15:27 UTC, buraizu approved these changes

2022-10-17 17:21 UTC, merged