DOCS-3949 - CSM
DataDog/documentation pull request #15509
Opened 2022-10-07 16:26 UTC by kayayarai

### What does this PR do?
Documents CSM

### Motivation
DOCS-3949

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-10-10 08:04 UTC, hdelaby reviewed
Hope I did not have a glance too soon 🤓

2022-10-10 08:04 UTC, hdelaby commented on content/en/security_platform/cloud_security_management/_index.md
> +Datadog Cloud Security Management delivers real time threat detection and continuous configuration audits across your entire cloud infrastructure - in a unified view for seamless collaboration and fa
I would say in general, if I compare this with the intro of APM or Log Management in the doc, this feels very weak. It's unclear what capabilities I can expect from the product, until I read the description of CSPM and CWS separately.

2022-10-11 14:31 UTC, n06 commented on content/en/security_platform/cloud_security_management/_index.md
> +Datadog Cloud Security Management delivers real time threat detection and continuous configuration audits across your entire cloud infrastructure - in a unified view for seamless collaboration and fa
@hdelaby this is copy we took straight from PMM and the investor day presentations, it is not new. I wanted to keep the description consistent with our public announcements

2022-10-11 14:33 UTC, n06 commented on content/en/security_platform/cloud_security_management/_index.md
> +{{< img src="security_platform/csm_overview.png" alt="Cloud Security Management in Datadog" width="100%">}}
Yes! @kayayarai here is a new screenshot: https://a.cl.ly/P8u72dml

2022-10-11 14:35 UTC, n06 commented on content/en/security_platform/cloud_security_management/_index.md
> +{{< img src="security_platform/csm_overview.png" alt="Cloud Security Management in Datadog" width="100%">}}
Scratch that, sorry @kayayarai lets use this one instead please: https://a.cl.ly/P8u72d56

2022-10-11 14:36 UTC, n06 commented on content/en/security_platform/cloud_security_management/_index.md
> +{{< img src="security_platform/csm_overview.png" alt="Cloud Security Management in Datadog" width="100%">}}
Yes, here it is: https://a.cl.ly/7KukzJEE

2022-10-14 15:26 UTC, jtappa requested changes

2022-10-14 15:26 UTC, jtappa commented on content/en/security_platform/cloud_security_management/_index.md
> +Datadog Cloud Security Management delivers real time threat detection and continuous configuration audits across your entire cloud infrastructure - in a unified view for seamless collaboration and fa
```suggestion
Datadog Cloud Security Management delivers real-time threat detection and continuous configuration audits across your entire cloud infrastructure - in a unified view for seamless collaboration and faster remediation.  Powered by observability data, security teams can determine the impact of a threat quickly by tracing the full attack flow and identify the resource owner where a vulnerability was triggered. Engineers are able to actively monitor their security risks by incorporating security metrics into their existing workflow.
```

2022-10-14 15:26 UTC, jtappa commented on content/en/security_platform/cloud_security_management/_index.md
> +To get started with Datadog Security, navigate to the [Setup & Configuration][3] section in the Datadog app, which has detailed information for single or multi-configuration, or follow the getting st
This is the end of the file, there's no getting started sections to see below...?
```suggestion
To get started with Datadog Security, navigate to the [Setup & Configuration][3] section in Datadog, which has detailed information for single or multi-configuration, or follow the getting started sections to learn more about each area of the platform.
```

2022-10-14 15:33 UTC, jtappa approved these changes

2022-10-19 15:03 UTC, merged