Add new search term for datadog config
DataDog/documentation pull request #15587
Opened 2022-10-14 12:32 UTC by NobodysNightmare

### What does this PR do?

We found out that the search was not simplified as much as we hoped for by the given keywords, because newer versions of ddtrace-rb (at least 1.5) do log under the key "DATADOG CONFIGURATION". Thus we didn't find the startup logs when we were looking for them.

### Motivation

> What inspired you to submit this pull request?

Incorrect documentation.

### Additional Notes

-

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-10-14 12:34 UTC, NobodysNightmare commented
Cross reference to `ddtrace-rb`: https://github.com/DataDog/dd-trace-rb/blob/da797293caaa1bbde3d2993709dabb956e457e84/lib/datadog/core/diagnostics/environment_logger.rb#L34

2022-10-17 21:08 UTC, kayayarai requested changes
Edit pass

2022-10-17 21:08 UTC, kayayarai commented on content/en/tracing/troubleshooting/tracer_startup_logs.md
> +Tracer startup logs capture all obtainable information at startup and log it either as `DATADOG TRACER CONFIGURATION` or `DATADOG TRACER DIAGNOSTICS` or `DATADOG CONFIGURATION` to simplify searching
```suggestion
Tracer startup logs capture all obtainable information at startup and log it as `DATADOG TRACER CONFIGURATION`, `DATADOG TRACER DIAGNOSTICS`, or `DATADOG CONFIGURATION` to simplify searching within your logs. 
```

2022-10-17 21:09 UTC, kayayarai approved these changes

2022-10-17 21:09 UTC, kayayarai commented
@NobodysNightmare Thanks, Jan. Adding this

2022-10-17 21:10 UTC, merged