Update cloud_cost_management.md
DataDog/documentation pull request #15582
Opened 2022-10-13 22:59 UTC by ktaylor19

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-10-13 23:05 UTC, cnharris10 approved these changes

2022-10-14 00:36 UTC, buraizu requested changes
Thanks, made a few minor suggestions.

2022-10-14 00:36 UTC, buraizu commented on content/en/infrastructure/cloud_cost_management.md
> +| `aws_member_account_id`      | The AWS member account id associated with the item.|
```suggestion
| `aws_member_account_id`      | The AWS member account ID associated with the item.|
```

2022-10-14 00:36 UTC, buraizu commented on content/en/infrastructure/cloud_cost_management.md
> +| `aws_cost_type`              | The type of charge covered by this item (for example, Usage, or Tax).|
```suggestion
| `aws_cost_type`              | The type of charge covered by this item (for example, Usage, Tax, and so on).|
```

2022-10-14 00:36 UTC, buraizu commented on content/en/infrastructure/cloud_cost_management.md
> +| `aws_pricing_term`           | Whether the usage is Reserved, Spot, or On Demand.|
```suggestion
| `aws_pricing_term`           | Whether the usage is Reserved, Spot, or On-Demand.|
```

2022-10-14 00:36 UTC, buraizu commented on content/en/infrastructure/cloud_cost_management.md
> +| `aws_resource_id`            | The resource id associated with the item.|
```suggestion
| `aws_resource_id`            | The resource ID associated with the item.|
```

2022-10-14 00:36 UTC, buraizu commented on content/en/infrastructure/cloud_cost_management.md
> +| `is_aws_ec2_compute_on_demand`| Whether the usage is on demand.|
```suggestion
| `is_aws_ec2_compute_on_demand`| Whether the usage is on-demand.|
```

2022-10-14 00:36 UTC, buraizu commented on content/en/infrastructure/cloud_cost_management.md
> +| `is_aws_ec2_compute_reservation`| Whether the usage associated with a Reserved Instance.|
```suggestion
| `is_aws_ec2_compute_reservation`| Whether the usage is associated with a Reserved Instance.|
```

2022-10-14 00:36 UTC, buraizu commented on content/en/infrastructure/cloud_cost_management.md
> +| `is_aws_ec2_capacity_reservation`| Whether the usage associated with a Capacity Reservation.|
```suggestion
| `is_aws_ec2_capacity_reservation`| Whether the usage is associated with a Capacity Reservation.|
```

2022-10-14 00:36 UTC, buraizu commented on content/en/infrastructure/cloud_cost_management.md
> +| `aws_management_account_id`  | The AWS management account id associated with the item.|
```suggestion
| `aws_management_account_id`  | The AWS management account ID associated with the item.|
```

2022-10-14 15:39 UTC, jtappa requested changes

2022-10-14 15:41 UTC, jtappa commented
I'm going to re-open this with a new branch name so that we can get preview builds up.

2022-10-14 15:41 UTC, closed without merging