DOCS-3153 OAuth 2.0 Support in HTTP Requests Doc Update
DataDog/documentation pull request #15643
Opened 2022-10-20 15:44 UTC by alai97

### What does this PR do?

Updates the Advanced Options section in API, browser, and multistep API test pages and refreshes two guides on Authentication.

### Motivation

DOCS-3153

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-10-20 21:13 UTC, cswatt requested changes

2022-10-20 21:13 UTC, cswatt commented on content/en/synthetics/api_tests/http_tests.md
> +   * **OAuth 2.0**: Choose between granting client credentials or a resource owner password and enter an access token URL. Depending on your selection, enter a client ID and secret or a username and
```suggestion
   * **OAuth 2.0**: Choose between granting client credentials or a resource owner password and enter an access token URL. Depending on your selection, enter a client ID and secret, or a username and password. From the dropdown menu, select an option to either send the API token as a basic authentication header, or send the client credentials in the body. Optionally, you can provide additional information such as the audience, resource, and scope (as well as the client ID and secret, if you selected **Resource Owner Password**).  
```

2022-10-20 21:13 UTC, cswatt commented on content/en/synthetics/browser_tests/actions.md
> +   * **OAuth 2.0**: Choose between granting client credentials or a resource owner password and enter an access token URL. Depending on your selection, enter a client ID and secret or a username and
```suggestion
   * **OAuth 2.0**: Choose between granting client credentials or a resource owner password and enter an access token URL. Depending on your selection, enter a client ID and secret, or a username and password. From the dropdown menu, select an option to either send the API token as a basic authentication header, or send the client credentials in the body. Optionally, you can provide additional information such as the audience, resource, and scope (as well as the client ID and secret, if you selected **Resource Owner Password**).
```

2022-10-20 21:13 UTC, cswatt commented on content/en/synthetics/guide/app-that-requires-login.md
> +<div class="alert alert-info"> Are you interested in testing applications sitting behind MFA? Visit the <a href="/synthetics/guide/app-that-requires-login/#multi-factor-authentication" target="_blank
```suggestion
<div class="alert alert-info">If you are interested in testing applications sitting behind MFA, visit the <a href="/synthetics/guide/app-that-requires-login/#multi-factor-authentication" target="_blank">Multi-factor authentication section</a> and <a href="https://docs.google.com/forms/d/e/1FAIpQLSdjx8PDZ8kJ3MD2ehouTri9z_Fh7PoK90J8arRQgt7QFgFxog/viewform?usp=sf_link">send feedback</a> to help Datadog work on the systems that matter the most to your teams.</div>
```

2022-10-20 21:13 UTC, cswatt commented on content/en/synthetics/guide/app-that-requires-login.md
> +The second method is to use one or several of the available advanced configuration options for [HTTP tests][6], [HTTP steps in browser tests][7], and [multistep API tests][8].
```suggestion
The second method is to use one or several of the available advanced configuration options for [HTTP tests][6], [HTTP steps in browser tests][7], or [multistep API tests][8]. 
```

2022-10-20 21:13 UTC, cswatt commented on content/en/synthetics/guide/app-that-requires-login.md
> +- Credentials for Basic Auth, Digest Auth, NTLM credentials, AWS Signature, or OAuth 2.0
```suggestion
- Credentials for basic authentication, digest authentication, NTLM, AWS Signature, or OAuth 2.0
```

2022-10-20 21:13 UTC, cswatt commented on content/en/synthetics/multistep.md
> +   * **OAuth 2.0**: Choose between granting client credentials or a resource owner password and enter an access token URL. Depending on your selection, enter a client ID and secret or a username and
```suggestion
   * **OAuth 2.0**: Choose between granting client credentials or a resource owner password and enter an access token URL. Depending on your selection, enter a client ID and secret, or a username and password. From the dropdown menu, select an option to either send the API token as a basic authentication header, or send the client credentials in the body. Optionally, you can provide additional information such as the audience, resource, and scope (as well as the client ID and secret, if you selected **Resource Owner Password**).
```

2022-10-21 15:39 UTC, HugoPct commented on content/en/synthetics/api_tests/http_tests.md
> +   Upload a private key and client certificate, select an authentication method, and provide additional configuration details as prompted.
Can we keep the wording for client certificates while  moving it at the top please
https://a.cl.ly/8Lu1e6LB

2022-10-21 15:48 UTC, HugoPct commented on content/en/synthetics/guide/app-that-requires-login.md
> +Once you have created secure variables, you can [import these global variables][10] into your browser tests and leverage them for your login steps, or use secure variables in your HTTP and multistep
we do not say 'secure variables' anymore but 'hidden' or 'obfuscated' variables

2022-10-21 15:55 UTC, HugoPct reviewed
added a comment

2022-10-26 16:59 UTC, HugoPct commented on content/en/synthetics/api_tests/http_tests.md
> +
```suggestion
```

2022-10-26 17:16 UTC, cswatt approved these changes

2022-10-27 15:43 UTC, alai97 commented on content/en/synthetics/guide/app-that-requires-login.md
> +- [Leverage advanced options for API, multistep, and browser tests](#leverage-test-configuration-options)
```suggestion
- [Leverage advanced options in your browser tests](#leverage-test-configuration-options)
```

2022-10-27 15:45 UTC, alai97 commented on content/en/synthetics/guide/app-that-requires-login.md
> +To ensure your credentials are securely stored and obfuscated across the application, use [secured global variables](#account-security).
```suggestion
To ensure your credentials are securely stored and obfuscated across the application, use [obfuscated global variables](#account-security).
```

2022-10-27 15:46 UTC, alai97 commented on content/en/synthetics/guide/app-that-requires-login.md
> +By default, the browser, API, or multistep API test automatically passes through authentication with your specified headers, cookies, and credentials at execution time and then completes all recorded
```suggestion
By default, the browser test automatically passes through authentication with your specified headers, cookies, and credentials at execution time and then completes all recorded steps.
```

2022-10-27 15:50 UTC, alai97 commented on content/en/synthetics/guide/browser-tests-totp.md
> +You can use the secret key or QR code stored in a global variable across all your Synthetic tests. When creating a [browser][2], [API][3], or [multistep API test][4], inject the TOTP generated from t
```suggestion
You can use the secret key or QR code stored in a global variable across all your Synthetic tests. When creating a [browser test][2], inject the TOTP generated from the secret key or QR code stored in the global variable to verify your application’s authentication workflow.
```

2022-10-27 15:51 UTC, alai97 commented on content/en/synthetics/guide/browser-tests-totp.md
> +[4]: /synthetics/multistep/
```suggestion
```

2022-10-27 16:54 UTC, HugoPct approved these changes

2022-10-27 19:30 UTC, alai97 commented on content/en/synthetics/browser_tests/actions.md
> +   * **OAuth 2.0**: Choose between granting client credentials or a resource owner password and enter an access token URL. Depending on your selection, enter a client ID and secret, or a username and
```suggestion
```

2022-10-28 07:58 UTC, HugoPct approved these changes

2022-11-01 19:09 UTC, merged