Julio.guerra/http client ip rework
DataDog/documentation pull request #15686
Opened 2022-10-24 19:51 UTC by Julio-Guerra

### What does this PR do?

This PR moves the existing documentation of this feature into the ASM setup and configure page.

### Motivation
Following up on a SEV-1 incident, it has been decided to report the APM span tag `http.client_ip` only with ASM.

### Additional Notes

How do you deal with existing translations?

---

### Reviewer checklist
- [x] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [x] Check images for PII
- [x] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-10-24 20:23 UTC, jtappa requested changes

2022-10-24 20:23 UTC, jtappa commented on content/en/security_platform/application_security/setup_and_configure.md
> +ASM automatically attempts to resolve `http.client_ip` from a number of well known headers, such as `X-Forwarded-For`. If you use a custom header for this field, or want to bypass the resolution algo
```suggestion
ASM automatically attempts to resolve `http.client_ip` from several well-known headers, such as `X-Forwarded-For`. If you use a custom header for this field, or want to bypass the resolution algorithm, set the `DD_TRACE_CLIENT_IP_HEADER` environment variable and the library only checks the specified header for the client IP.
```

2022-10-24 20:23 UTC, jtappa commented on content/en/tracing/configure_data_security/_index.md
> +    - /tracing/guide/agent-obfuscationDD
this looks like a typo/unintended line edit

```suggestion
    - /tracing/guide/agent-obfuscation
```

2022-10-25 07:55 UTC, Julio-Guerra commented
@jtappa, thanks for your review.
I was also wondering how do you deal with existing translations?

2022-10-25 16:21 UTC, jtappa approved these changes

2022-10-25 16:24 UTC, jtappa commented
@Julio-Guerra after this PR gets merged, the updates are automatically pulled into our translation pipeline and they should be reflected in the translated docs as soon as they get through that process. The deleted text usually is reflected in the translated docs fairly quickly as transifex can sort that out. Modified text can take a while to be updated though, because our translators have to edit and approve it.

2022-10-25 16:24 UTC, merged