Add troubleshooting doc for SQL Server integration
DataDog/documentation pull request #15689
Opened 2022-10-24 23:21 UTC by jmeunier28

### What does this PR do?

Prior to this PR, there were public docs around troubleshooting for the Postgres & MySQL integrations, but nothing for SQL Server. This adds docs around known issues that we see come up in support (mostly diagnosing connection issues / issues with the driver)

### Motivation

In an effort to decrease the number of support requests we get around the SQL Server integration setup, we are adding better troubleshooting docs to help customers diagnose issues on their own 

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-10-24 23:37 UTC, EmmaOnThursday commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +# this examples uses Windows Authentication
typo: `this example`

2022-10-24 23:37 UTC, EmmaOnThursday commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +This is described in more detail [in the microsoft documentation][7]
nit: capitalize Microsoft

2022-10-24 23:37 UTC, EmmaOnThursday commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +In versions of the agent older than 7.40.0, there exists a bug where `PROCEDURE` statistics are over counted. This leads to seeing many executions of `CREATE PROCEDURE...` in the database-monitoring
probably: `... please upgrade to the latest version of the Datadog agent` at the end

2022-10-24 23:37 UTC, EmmaOnThursday commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +The `user` tag has been removed from all sqlserver metric telemetry.
nit: SQL Server not sqlserver

2022-10-24 23:37 UTC, EmmaOnThursday commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +The `user` tag was previously incorrect and did not reflect the user who executed the query in the Query Metrics UI. This is due to a technical limitation in the tables that we are querying in sqlser
nit: nit: SQL Server not sqlserver

2022-10-24 23:37 UTC, EmmaOnThursday commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +`-2147467259` — **“could not open database requested for login”**: this error appears either due to network issues or due to an unknown database. To troubleshoot:
nit: last words `To troubleshoot:` unnecessary/duplicate following line

2022-10-25 14:25 UTC, jmeunier28 commented
Ty for review @EmmaOnThursday 🙇 I think I got it all

2022-10-25 16:39 UTC, EmmaOnThursday approved these changes
👍 this looks great

2022-10-25 17:08 UTC, cswatt commented
created DOCS-4287 to track

2022-10-25 17:25 UTC, justiniso requested changes

2022-10-25 17:25 UTC, justiniso commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +The `SQLOLEDB` and `SQLNCLI11` providers produce a particularly uninformative error message, `Invalid connection string attribute`. For example:
```suggestion
The `SQLOLEDB` and `SQLNCLI11` providers produce the error message `Invalid connection string attribute` for a wide variety of possible issues. For example:
```

2022-10-25 17:25 UTC, justiniso commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +The `SQLOLEDB` and `SQLNCLI11` providers produce a particularly uninformative error message, `Invalid connection string attribute`. For example:
But docs team, please feel free to suggest other language.

2022-10-25 17:25 UTC, justiniso commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +The `user` tag has been removed from all SQL Server metric telemetry.
```suggestion
The `user` tag is no longer supported for Query Metrics due to technical limitations in SQL Server which prevent the collection of the correct user running queries.

The `user` tag is available for Query Activity events and Database Load metrics.
```

2022-10-25 17:25 UTC, justiniso commented on content/en/database_monitoring/setup_sql_server/troubleshooting.md
> +The `user` tag was previously incorrect and did not reflect the user who executed the query in the Query Metrics UI. This is due to a technical limitation in the tables that we are querying in SQL Se
```suggestion

```

2022-10-28 21:39 UTC, jtappa requested changes
this page also needs to be added to the left navigation in menus.en.yaml, you can use the other troubleshooting pages in the DBM section as a reference, but let me know if you need help with this!

2022-10-31 14:16 UTC, jmeunier28 commented
@jtappa this look right? 40523a304791a709e69d250174de9a5bbceb7b74

2022-11-01 16:51 UTC, cswatt commented
@jmeunier28 nav looks good!

2022-11-01 16:51 UTC, cswatt approved these changes

2022-11-01 16:52 UTC, merged