single_span ingestion minimal version
DataDog/documentation pull request #15853
Opened 2022-11-08 17:06 UTC by dussault-antoine

### What does this PR do?

Add documentation for the single span mechanism

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-11-08 18:06 UTC, pierotibou requested changes
Just 2 small changes for .NET. Ok for PHP.
Thanks for doing it

2022-11-08 18:06 UTC, pierotibou commented on content/en/tracing/trace_collection/library_config/dotnet-core.md
> +: **TracerSettings property**: `SpanSamplingRule`<br>
It's not possible to set this in code. We tend to avoid changing the public API as much as possible

```suggestion
```

2022-11-08 18:40 UTC, dgoffredo approved these changes
The overall description and the C++ specifics look good to me.

As always, there's the issue of each proxy being configured in its own way, but that is likely out of scope here. If you disagree, then we can discuss how to integrate proxy-specific instructions, either here or in the "tracing a proxy" docs.

2022-11-08 20:01 UTC, kayayarai reviewed
I gave this an edit pass, some formatting, and added all the links to the Ingestion Mechanisms page. Added single quotes around the .NET example (per the docs). Have you updated the "The Public Docs Say Contact Support" confluence page about what support's actions are if someone uses the links for Java and Ruby?

2022-11-08 20:25 UTC, marcotc approved these changes
Ruby content looks good! ✅

2022-11-09 21:03 UTC, Qard approved these changes
LGTM, and also I've added a commit for Node.js env vars.

2022-11-10 09:33 UTC, pierotibou approved these changes
🙇

2022-11-15 21:14 UTC, ZStriker19 approved these changes

2022-11-15 21:22 UTC, ZStriker19 commented
This is good but we may want to update some of the examples/the description to show that wildcards can be used. The glob pattern language we used supports `*` as a multiple character wildcard which includes matches on `""`
    and `?` as a single character wildcard, but no escape sequences.

2022-11-15 21:23 UTC, ZStriker19 requested changes
This is good but we may want to update some of the examples/the description to show that wildcards can be used. The glob pattern language we used supports `*` as a multiple character wildcard which includes matches on `""`
and `?` as a single character wildcard, but no escape sequences.

2022-11-23 14:36 UTC, kayayarai approved these changes

2022-11-23 14:36 UTC, merged