CI Provider Feature Support
DataDog/documentation pull request #15931
Opened 2022-11-15 20:29 UTC by kassenq

### What does this PR do?
This PR adds details around the specific features offered for the different CI providers we support in our Pipeline Visibility product. It is based on the [feature support matrix here](https://datadoghq.atlassian.net/wiki/spaces/CIAPP/pages/2205614232/CI+Provider+integrations+feature+support). 

### Motivation
We have wanted to add this to our documentation for a long time, because it helps customers understand how much visibility we can provide for each CI provider we can support.

### Preview

### Additional Notes
We had originally discussed using a definition list for this, but our team felt that a definition list would take up too much space on the page, and thus reverted to using a bulleted list.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-11-15 21:07 UTC, maycmlee commented
Created DOCS-4411 for docs review.

2022-11-17 22:23 UTC, jtappa requested changes
Minor edits to make translation smoother and an open question

2022-11-17 22:23 UTC, jtappa commented on content/en/continuous_integration/pipelines/gitlab.md
> +- **Pipeline failure reasons**: Identify pipeline failure reasons via [error messages][15]
```suggestion
- **Pipeline failure reasons**: Identify pipeline failure reasons from [error messages][15]
```

2022-11-17 22:23 UTC, jtappa commented on content/en/continuous_integration/pipelines/jenkins.md
> +- **Queue time**: View amount of time pipeline jobs sit in the queue before processing
```suggestion
- **Queue time**: View amount of time pipeline jobs wait in the queue before processing
```

2022-11-17 22:23 UTC, jtappa commented on content/en/continuous_integration/pipelines/jenkins.md
> +- **Custom predefined tags**: Configure [custom tags][12] and metrics at runtime
```suggestion
- **Custom pre-defined tags**: Configure [custom tags][12] and metrics at runtime
```

2022-11-21 21:17 UTC, kassenq commented on content/en/continuous_integration/pipelines/circleci.md
> +- **Custom predefined tags**: Set [custom tags][6] to all generated pipeline and job spans
I want to keep "and" because we have separate spans for both pipelines and jobs (job being a more granular unit of work within a pipeline)

2022-11-22 17:34 UTC, jtappa approved these changes

2022-11-22 17:34 UTC, merged