Guide: Remotely configure RUM using LaunchDarkly
DataDog/documentation pull request #15983
Opened 2022-11-18 19:31 UTC by meghanlo

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-11-18 21:40 UTC, kayayarai commented
Opened https://datadoghq.atlassian.net/browse/DOCS-4444 to track editorial review

2022-11-21 20:53 UTC, rtrieu requested changes
Requesting another review to make sure it all looks good, then we can merge!

2022-11-21 20:53 UTC, rtrieu commented on content/en/real_user_monitoring/guide/remotely-configure-rum-using-launchdarkly.md
> +To set up your flag in LaunchDarkly, start by following their documentation on [setting up an SDK][3]. More information on the Client-side SDK is available in LaunchDarkly's [documentation][4].
```suggestion
To set up your flag in LaunchDarkly, start by following their documentation on [setting up an SDK][3]. For additional details, see LaunchDarkly's [Client-side SDK documentation][4].
```

2022-11-21 20:53 UTC, rtrieu commented on content/en/real_user_monitoring/guide/remotely-configure-rum-using-launchdarkly.md
> +If you want to change your RUM configuration directly in your Datadog application, you can embed the LaunchDarkly UI into Datadog and switch your feature flag on/off. The feature flags are set up so
```suggestion
If you want to change your RUM configuration directly in your Datadog application, you can embed the LaunchDarkly UI into Datadog and switch your feature flag on/off. The feature flags are set up so you can keep them off, with the default values. When you want to have higher fidelity data, you can turn on your feature flag and the values you set for the ON variation will be used for the RUM initialization. 
```

2022-11-21 22:18 UTC, rtrieu approved these changes

2022-11-21 22:30 UTC, merged