Add info on azure LB
DataDog/documentation pull request #15998
Opened 2022-11-21 19:12 UTC by CordeliaLopez

### What does this PR do?

This PR makes clients aware that they need to have the azure integration installed in order to see Azure LB data.

### Motivation

The added functionality to NPM

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-11-22 02:32 UTC, buraizu requested changes
Thanks, just made a small update per our contributing guidelines. Would you be open to using a site-region selector to display the information for only non-Govcloud users?

2022-11-22 02:32 UTC, buraizu commented on content/en/network_monitoring/performance/setup.md
> +6. [Optional] Make sure the Azure integration is installed for more visibility into Azure load balancers. This feature is currently not available in the Govcloud region.
```suggestion
6. Optionally, install the Azure integration for more visibility into Azure load balancers.
```

2022-11-22 22:26 UTC, CordeliaLopez commented
> Thanks, just made a small update per our contributing guidelines. Would you be open to using a site-region selector to display the information for only non-Govcloud users?

@buraizu sure, do you have any documentation you can point me to in order to see how that's used?

2022-11-23 19:42 UTC, buraizu requested changes
@CordeliaLopez thanks for confirming! I've added in the `site-region` shortcode and confirmed that the content is not visible for users with the `us-1 fed` documentation site selected. I'll follow up internally with a link to further details.

2022-11-23 19:46 UTC, buraizu approved these changes

2022-11-23 20:40 UTC, merged