[APM] Add a bit more details in the network troubleshooting doc
DataDog/documentation pull request #16009
Opened 2022-11-22 12:05 UTC by pierotibou

### What does this PR do?
Adds a bit more details in the network troubleshooting doc. It aims at guiding the users to troubleshoot more easily connectivity issues in containerized environments.

### Motivation
We had a customer call where the users had an egress rule that prevented them to connect the tracer to the agent.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-11-22 18:22 UTC, hestonhoffman requested changes

2022-11-22 18:22 UTC, hestonhoffman commented on content/en/tracing/troubleshooting/connection_errors.md
> +To do so, you can run the following command, from the application container and by replacing the `{agent_ip}`, `{agent_port}` variables:
```suggestion
To do so, you can run the following command from the application container, replacing the `{agent_ip}` and `{agent_port}` variables:
```

2022-11-22 18:22 UTC, hestonhoffman commented on content/en/tracing/troubleshooting/connection_errors.md
> +`curl -X GET http://{agent_ip}:{agent_port}/info`.
~~~suggestion
```
curl -X GET http://{agent_ip}:{agent_port}/info
```
~~~

2022-11-22 18:22 UTC, hestonhoffman commented on content/en/tracing/troubleshooting/connection_errors.md
> +If this command fails, your container cannot access the agent. Refer to the following sections to get hints on what could be causing this issue.
```suggestion
If this command fails, your container cannot access the Agent. Refer to the following sections to get hints on what could be causing this issue.
```

2022-11-22 18:22 UTC, hestonhoffman commented on content/en/tracing/troubleshooting/connection_errors.md
> +| [Kubernetes][12] | 1) [Unix Domain Socket][13], 2) [`status.hostIP`][14] added manually, or 3) through the [Admission Controller][15]. Also, if using TCP, don't forget to check the [network policie
```suggestion
| [Kubernetes][12] | 1) [Unix Domain Socket][13], 2) [`status.hostIP`][14] added manually, or 3) through the [Admission Controller][15]. If using TCP, check the [network policies][21] applied on your container |
```

2023-02-03 10:45 UTC, pierotibou commented
Thanks @hestonhoffman I've just applied your suggestions

2023-02-06 16:29 UTC, merged