Guide: Getting Started with Feature Flag data in RUM
DataDog/documentation pull request #16030
Opened 2022-11-23 21:15 UTC by meghanlo

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-12-02 18:54 UTC, drichards-87 commented
@meghanlo Thanks for submitting this new guide! I've created a docs ticket for the editorial review. It will be assigned during the team's docs planning on Monday.

2022-12-07 17:47 UTC, rtrieu requested changes
Mostly edits to make capitalizations consistent with our guidelines, and a few word cuts. Thanks for submitting this new guide!

2022-12-07 17:47 UTC, rtrieu commented on content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> +Feature Flag tracking is available in the RUM Browser SDK. To start, set up [RUM browser monitoring][1]. You need the Browser RUM SDK version >= 4.25.0.
```suggestion
Feature flag tracking is available in the RUM Browser SDK. To start, set up [RUM browser monitoring][1]. You need the Browser RUM SDK version >= 4.25.0.
```

2022-12-07 17:47 UTC, rtrieu commented on content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> +Filtering your Sessions with the `@feature_flags.{flag_name}` attribute, you will find all Sessions in the given time frame where your feature flag was evaluated.
```suggestion
Filtering your **Sessions** with the `@feature_flags.{flag_name}` attribute, you will find all sessions in the given time frame where your feature flag was evaluated.
```

2022-12-07 17:47 UTC, rtrieu commented on content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> +Filtering your Views with the `@feature_flags.{flag_name}` attribute, you will find the specific Views in the given time frame where your feature flag was evaluated.
```suggestion
Filtering your **Views** with the `@feature_flags.{flag_name}` attribute, you will find the specific views in the given time frame where your feature flag was evaluated.
```

2022-12-07 17:47 UTC, rtrieu commented on content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> +Filtering your Errors with the `@feature_flags.{flag_name}` attribute, you will find all the Errors in the given time frame that occurred on the View where your feature flag was evaluated
```suggestion
Filtering your **Errors** with the `@feature_flags.{flag_name}` attribute, you will find all the errors in the given time frame that occurred on the View where your feature flag was evaluated
```

2022-12-07 18:04 UTC, rtrieu approved these changes

2022-12-09 17:18 UTC, merged