Cleanup and add more samples for ECS/EC2 log collection
DataDog/documentation pull request #16087
Opened 2022-12-01 02:07 UTC by JacksonDavenport

### What does this PR do?

Make some large changes to the ECS Log Collection doc similar to the recent one for the core ECS Agent setup:

- https://github.com/DataDog/documentation/pull/15999

The main goal here was to provide simpler instructions with more detailed examples configurations. While also providing more context into some of the important details for the configuration. Changes like:

- Cleaning up and referencing the `datadog-agent-ecs-logs.json` Task Definition file (existed but unreferenced)
- Adding an example Task Definition file for Windows log collection `datadog-agent-ecs-win-logs.json`
- Provide example Task Definitions for customizing autodiscovery labels
- Provide example Task Definition for file collection / file and stream collection
- Re-frame the context towards what the Agent is collecting vs not (json files vs local files vs awslogs)
- Point users towards the in-app Pipeline Library

### Motivation

Similar to the core ECS Agent. Clarify the setup instructions from both a context/strategy perspective. With a large focus on providing valid samples to use. 

### Preview

- preview:
  - TBD
- current: 
  - https://docs.datadoghq.com/containers/amazon_ecs/logs/?tab=linux

### Additional Notes

The log collection from file samples is pretty much the same sample I used for Kubernetes and validated in ECS:
- https://docs.datadoghq.com/containers/kubernetes/log/?tab=daemonset#examples---log-collection-from-file-configured-in-an-annotation

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-12-02 01:04 UTC, cswatt requested changes

2022-12-02 01:04 UTC, cswatt commented on content/en/containers/amazon_ecs/logs.md
> +Docker with the `default` or `json-file` driver exposes the `stdout` and `stderr` log streams in a format that the Agent can readily find. However, if a container is creating a log file isolated with
```suggestion
Docker (with the `default` or `json-file` driver) exposes the `stdout` and `stderr` log streams in a format that the Agent can readily find. However, if a container is creating a log file isolated within its container, then the Agent does not natively have visibility to that file. Datadog recommends using the `stdout` and `stderr` output streams for containerized applications to more automatically set up log collection. If this is not possible, you can provide an Autodiscovery log configuration to point towards the desired file path, and ensure that the Agent container and application container share a directory on the host containing the log file.
```

2022-12-02 01:04 UTC, cswatt commented on content/en/containers/amazon_ecs/logs.md
> +The log configuration below can be provided to tell the Agent to [collect this custom log file][3] at the `/var/log/example/app.log` path.
```suggestion
The log configuration below tells the Agent to [collect this custom log file][3] at the `/var/log/example/app.log` path.
```

2022-12-02 01:04 UTC, cswatt commented on content/en/containers/amazon_ecs/logs.md
> +As an example the Task Definition below is
```suggestion
Example: the Task Definition below performs the following:
```

2022-12-02 01:04 UTC, cswatt commented on content/en/containers/amazon_ecs/logs.md
> +3. Has the host path `volumes` and `mountPoints` specified for this `/var/log/example` directory
```suggestion
* Writing some logs to that file `/var/log/example/app.log` file
* Has the `dockerLabels` present to setup the log configuration
* Has the host path `volumes` and `mountPoints` specified for this `/var/log/example` directory
```

2022-12-02 01:04 UTC, cswatt commented on content/en/containers/amazon_ecs/logs.md
> +The file paths for the configuration are always relative to the Agent. So that same `volume` and `mountPoint` need to be present within the Agent's Task Definition as well to give visibility to that
```suggestion
The file paths for the configuration are always relative to the Agent. The same `volume` and `mountPoint` also need to be present within the Agent's Task Definition to give visibility to that log file.
```

2022-12-02 01:04 UTC, cswatt commented on content/en/containers/amazon_ecs/logs.md
> +**Note**: When using this kind of configuration with a container the `stdout` and `stderr` logs streams are not collected automatically from the container, only the file. If collection from both the
```suggestion
**Note**: When using this kind of configuration with a container, the `stdout` and `stderr` logs streams are not collected automatically from the container—only the file. If collection from both the container streams and a file are needed, explicitly enable this in the configuration. For example:
```

2022-12-05 15:39 UTC, JacksonDavenport commented
Hey @cswatt ready for the re-review when you get the chance, added your suggestions

2022-12-08 22:11 UTC, cswatt approved these changes

2022-12-12 20:11 UTC, merged