Rename Custom check to Service check
DataDog/documentation pull request #16119
Opened 2022-12-05 17:05 UTC by estherk15

### What does this PR do?
- Rename the repo file name from `custom_check` to `service_check`
- Verify the URLs are updated in the `menus.en.yaml`
- Add alias for the `monitors/types/custom_check.md`
- Re order the weight in `menus.en.yaml` so that it’s alphabetical
- Change Custom Check to Service Check in Monitor Types page https://docs.datadoghq.com/monitors/create/#monitor-types 

### Motivation
[DOCS-4496](https://datadoghq.atlassian.net/browse/DOCS-4496)

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-12-05 22:29 UTC, buraizu approved these changes

2022-12-05 22:36 UTC, buraizu requested changes
It looks like this is working as expected in the preview, but our internal guidelines ask for the menu weights to be consecutive.

2022-12-05 22:36 UTC, buraizu commented on config/_default/menus/menus.en.yaml
> +    weight: 217
```suggestion
    weight: 218
```

2022-12-05 22:42 UTC, estherk15 commented on config/_default/menus/menus.en.yaml
> +    weight: 217
Ah, thanks for catching this!

2022-12-06 01:47 UTC, buraizu approved these changes

2022-12-06 14:33 UTC, merged