Add dd.trace.baggage.mapping config description for java tracing.
DataDog/documentation pull request #16194
Opened 2022-12-13 14:49 UTC by Xyaren

### What does this PR do?

Adds documentation about baggage mapping configuration parameters implemented by PR:  https://github.com/DataDog/dd-trace-java/pull/4404

### Motivation

I created the implementation, therefore the documentation must be kept up to date.

### Additional Notes

- [ ] The "available from" version must be updated before merging.
---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-12-13 14:51 UTC, Xyaren commented
@bantonsson I can't add you as a reviewer, as you requested.

2022-12-13 16:18 UTC, bantonsson commented on content/en/tracing/trace_collection/library_config/java.md
> +`trace.header.baggage`
This is missing the `dd.` prefix.

2022-12-13 22:07 UTC, rtrieu approved these changes
LGTM

2022-12-14 09:06 UTC, bantonsson commented
Just to be clear, this can't be merged until after the feature is released and the version number is updated.

2022-12-14 13:24 UTC, bantonsson commented on content/en/tracing/trace_collection/library_config/java.md
> +Available since version TODO: XX.XX.XX.
```suggestion
Available since version 1.3.0.
```

2022-12-14 13:28 UTC, bantonsson requested changes
This looks good. Will keep it blocked until the release is done for `dd-trace-java`

2022-12-20 08:20 UTC, bantonsson approved these changes
This version of the Java Tracer has now been released https://github.com/DataDog/dd-trace-java/releases/tag/v1.3.0

2022-12-28 17:07 UTC, apigirl approved these changes

2022-12-28 17:07 UTC, merged