APM Python - Decribe pip requirement for profiling
DataDog/documentation pull request #16213
Opened 2022-12-14 14:55 UTC by r1viollet

#  Description

Ensure pip requirement is described in the install. If pip is at an older version we are getting the following error 

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ymqm0401/ddtrace/setup.py", line 11, in <module>
        from Cython.Build import cythonize  # noqa: I100
    ModuleNotFoundError: No module named 'Cython'
```

### What does this PR do?

### Motivation

I was failing during installation for unknown reasons.

### Additional Notes

---

### Reviewer checklist
- [x] Review the changed files.
- [x] Review the URLs listed in the [Preview](#preview) section.
- [x] Check images for PII
- [x] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-12-14 15:30 UTC, r1viollet commented
TODO We should probably leave a link somewhere to the troubleshooting page
https://ddtrace.readthedocs.io/en/stable/troubleshooting.html

2022-12-20 09:15 UTC, r1viollet commented
> TODO We should probably leave a link somewhere to the troubleshooting page https://ddtrace.readthedocs.io/en/stable/troubleshooting.html

Done

2022-12-20 15:40 UTC, estherk15 requested changes

2022-12-20 15:40 UTC, estherk15 commented on content/en/profiler/profiler_troubleshooting.md
> +Please refer to the python APM client [troubleshooting documentation][3] for additional guidance.
```suggestion
Refer to the python APM client [troubleshooting documentation][3] for additional guidance.  
```

2022-12-20 15:41 UTC, merged