Add documentation on notification presets/format
DataDog/documentation pull request #16244
Opened 2022-12-19 10:43 UTC by Dalje-et

### What does this PR do?

Adds documentation on what content can be toggled on/off in monitor notifications.

### Motivation
Feature that needs documentation.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2022-12-19 23:09 UTC, cswatt requested changes

2022-12-19 23:09 UTC, cswatt commented on content/en/monitors/notify/_index.md
> +Providing additional context, monitor notifications can include content such as the monitor's query, the @-mentions used, metric snapshots (for metric monitors), and links back to relevant pages in D
```suggestion
Monitor notifications can provide additional context, such as the monitor's query, the @-mentions used, metric snapshots (for metric monitors), and links back to relevant pages in Datadog. You can configure the types of additional context included in each monitor's notifications. The options are:
```

2022-12-19 23:09 UTC, cswatt commented on content/en/monitors/notify/_index.md
> +- **Hide All**: notification does not include query, handles, any snapshot (for metric monitors), and additional links in footers
```suggestion
- **Default**: No content is hidden.
- **Hide Query**: Remove the monitor's query from the notification message.
- **Hide Handles**: Remove the @-mentions that are used in the notification message.
- **Hide All**: Notification message does not include query, handles, any snapshots (for metric monitors), or additional links in footers.
```

grammar stuff

2022-12-19 23:09 UTC, cswatt commented on content/en/monitors/notify/_index.md
> +Note, some content might not be displayed by defauly depending on the integration.
```suggestion
**Note**: Depending on the integration, some content may not be displayed by default.
```

2023-01-02 09:56 UTC, Dalje-et commented
Hey @cswatt, do you think this one is good to go? :)

2023-01-05 19:48 UTC, estherk15 commented on content/en/monitors/notify/_index.md
> +{{< img src="monitors/notifications/monitor_notification_presets.png" alt="Set a monitor preset" style="width:70%;" >}}
```suggestion
{{< img src="monitors/notifications/monitor_notification_presets.png" alt="Set a monitor preset" style="width:100%;" >}}
```

2023-01-05 20:34 UTC, estherk15 commented on content/en/monitors/notify/_index.md
> +{{< img src="monitors/notifications/monitor_notification_presets.png" alt="Set a monitor preset" style="width:100%;" >}}
```suggestion
{{< img src="monitors/notifications/monitor_notification_presets.png" alt="Set a monitor preset" style="width:70%;" >}}
```

2023-01-05 20:35 UTC, estherk15 approved these changes

2023-01-05 21:01 UTC, merged