WIP
DataDog/documentation pull request #16315
Opened 2022-12-28 23:28 UTC by hestonhoffman

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-05 20:04 UTC, hestonhoffman commented on content/en/developers/marketplace/marketplace-agent-integration.md
> +ddev validate all changes
```suggestion
ddev validate all <INTEGRATION_NAME>
```

2023-01-30 22:50 UTC, alai97 requested changes
Some copy suggestions!

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/marketplace-agent-integration.md
> +description: Learn how to create an Agent-based integration for the marketplace repo.
```suggestion
description: Learn how to create an Agent-based integration for the Datadog Marketplace repository.
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/marketplace-agent-integration.md
> +At the core of each Agent-based integration is an *Agent Check* that periodically collects information and sends it to Datadog. Checks inherit their logic from the `AgentCheck` base class and have th
```suggestion
At the core of each Agent-based integration is an *Agent Check* that periodically collects information and sends it to Datadog. Checks inherit their logic from the `AgentCheck` base class and have the following requirements:
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/marketplace-agent-integration.md
> +- Integrations running on the Datadog Agent v7 and later must be compatible with Python 3; however, Agents v5 and v6 still use Python 2.7.
```suggestion
- Integrations running on the Datadog Agent v7 or later must be compatible with Python 3; however, Agents v5 and v6 still use Python 2.7.
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/marketplace-agent-integration.md
> +For the example check, the toolkit uses `docker` to spin up an Nginx container and allows the check to retrieve the welcome page. The `docker-compose.yml` file has the following contents:
```suggestion
For the example check, the toolkit uses `docker` to spin up an NGINX container and allows the check to retrieve the welcome page. The `docker-compose.yml` file has the following contents:
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/marketplace-agent-integration.md
> +After you've setup an environment for the integration test, add an integration test to the `INTEGRATION_NAME/tests/test_INTEGRATION_NAME.py` file:
```suggestion
After you've set up an environment for the integration test, add an integration test to the `INTEGRATION_NAME/tests/test_INTEGRATION_NAME.py` file:
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/marketplace-agent-integration.md
> +The `pyproject.toml` file provides the metadata that is used to package and build the wheel. The wheel contains the files necessary for the functioning of the integration itself, which includes the C
"Functioning of the integration" sounded off to me, but feel free to reword or ignore!

```suggestion
The `pyproject.toml` file provides the metadata that is used to package and build the wheel. The wheel contains the files necessary for the integration to function itself, and includes the Check, configuration example file, and artifacts generated during the build of the wheel.
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/marketplace-agent-integration.md
> +The wheel is installed using the Agent `integration` command, available in [Agent v6.10.0 and up][21]. Depending on your environment, you may need to execute this command as a specific user or with s
```suggestion
The wheel is installed using the Agent `integration` command, available in [Agent v6.10.0 or later][21]. Depending on your environment, you may need to execute this command as a specific user or with specific privileges:
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/marketplace-agent-integration.md
> +After you've created your pull request, automatic checks run to verify that your pull request is in good shape and contains all the required content to be updated.
Extra sentence here I think

```suggestion
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/offering.md
> +The Agent Integration Developer Tool allows you to create scaffolding when you are developing an integration by generating a skeleton of your integration tile's assets and metadata. For instructions
```suggestion
The Agent Integration Developer Tool allows you to create scaffolding when you are developing an integration by generating a skeleton of your integration tile's assets and metadata. For instructions on installing the tool, see [Install the Datadog Agent Integration Developer Tool][17].
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/offering.md
> +Once you've installed the Developer tool, configure the tool for the `marketplace` repo:
```suggestion
Once you've installed the Developer tool, configure the tool for the `marketplace` repo.
```

2023-01-30 22:50 UTC, alai97 commented on content/en/developers/marketplace/offering.md
> +Run the `ddev` command to generate a skeleton of the folders and files needed for your integration. The options you use with the command are different depending on what type of integration you are de
```suggestion
Run the `ddev` command to generate a skeleton of the folders and files needed for your integration. The options you use with the command are different depending on what type of integration you are developing. For a full list of the files created by the `ddev` command, see the [Integrations assets](#complete-the-necessary-integration-asset-files) section below.
```

2023-02-03 21:50 UTC, alai97 approved these changes
Looks great, amazing work!

2023-02-03 22:04 UTC, closed without merging