Add Linux App Services
DataDog/documentation pull request #16329
Opened 2023-01-03 06:19 UTC by Danny-Driscoll

Adding a new section for Linux Azure App Services setup

### What does this PR do?
Add a new index page for Azure App Services, and add a new Linux App Services documentation page

### Motivation
We are beginning a public Beta for Linux Azure App Services APM

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-03 17:45 UTC, kayayarai commented
Opened https://datadoghq.atlassian.net/browse/DOCS-4611 to track docs team review

2023-02-09 20:15 UTC, cswatt requested changes

2023-02-09 20:15 UTC, cswatt commented on content/en/serverless/azure_app_services/azure_app_services_linux.md
> +- `DD_START_APP` is the command used to start your application. For example, `node ./bin/www`
```suggestion
- `DD_API_KEY` is your Datadog API key.
- `DD_SITE` is the Datadog [site parameter][2]. This defaults to `datadoghq.com`.
- `DD_SERVICE` is the service name used for this program. Defaults to the name field value in `package.json`.
- `DD_START_APP` is the command used to start your application. For example, `node ./bin/www`.
```

2023-02-09 20:15 UTC, cswatt commented on content/en/serverless/azure_app_services/azure_app_services_linux.md
> +### Startup Command
```suggestion
### Startup command
```

2023-02-09 20:15 UTC, cswatt commented on content/en/serverless/azure_app_services/azure_app_services_linux.md
> +      curl -s https://raw.githubusercontent.com/DataDog/datadog-aas-extension/linux-v0.1.4-beta/linux/datadog_wrapper | bash
```suggestion
`curl -s https://raw.githubusercontent.com/DataDog/datadog-aas-extension/linux-v0.1.4-beta/linux/datadog_wrapper | bash`
```

2023-02-09 20:15 UTC, cswatt commented on content/en/serverless/azure_app_services/azure_app_services_linux.md
> +After the application has been instrumented and restarted successfully, traces will be available from the application within. These can be accessed from  the [Azure Serverless view][3], or in the [AP
```suggestion
After the application is instrumented and successfully restarted, traces are available from the application within. You can access these in the [Azure Serverless view][3], or in the [APM Service page][4] of Datadog.
```

2023-02-09 20:15 UTC, cswatt commented on content/en/serverless/azure_app_services/azure_app_services_linux.md
> +### Custom Metrics
```suggestion
### Custom metrics
```

2023-02-09 23:30 UTC, cswatt approved these changes

2023-04-05 16:24 UTC, jcstorms1 commented
@cswatt @Danny-Driscoll  I just released the first version of this. The only changes we need are the links and snapshots should be updated. These can be found in the new Readme https://github.com/DataDog/datadog-aas-linux/#readme

2023-04-06 18:04 UTC, cswatt commented
new pr: https://github.com/DataDog/documentation/pull/16384

2023-04-07 22:48 UTC, closed without merging