Review define apps services components rum
DataDog/documentation pull request #16332
Opened 2023-01-03 13:16 UTC by bcaudan

### What does this PR do?

Improve guide: `Define Services And Track UI Components In Your Browser Application`

### Motivation

Spotted some inaccuracies / misleading statements

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-03 18:04 UTC, rtrieu requested changes
Hi Bastien, thanks so much for this PR! Requesting one small update before merging.

2023-01-03 18:04 UTC, rtrieu commented on content/en/real_user_monitoring/guide/define-services-and-track-ui-components-in-your-browser-application.md
> +The Browser SDK automatically tracks a set of industry standards timings, Core Web Vitals, page loading times [and more][4].
```suggestion
The Browser SDK automatically tracks a set of industry-standard timings, Core Web Vitals, page loading times [and more][4].
```

2023-01-04 08:53 UTC, amortemousque approved these changes

2023-01-05 20:28 UTC, rtrieu approved these changes

2023-01-05 20:28 UTC, merged