Document `DD_PROFILING_MAX_FRAMES` / `max_frames` setting for Ruby profiler
DataDog/documentation pull request #16361
Opened 2023-01-05 12:01 UTC by ivoanjo

### What does this PR do?

Document the `DD_PROFILING_MAX_FRAMES`/`max_frames` setting in the Ruby profiler troubleshooting section.

### Motivation

This setting is a rare workaround that most customers should never need to use. Hence, I decided to document it as part of the troubleshooting guide, and not elsewhere.

The plan is to also link to this documentation from the Datadog UX.

### Preview

### Additional Notes

(N/A)

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-05 19:02 UTC, alai97 commented
Opened https://datadoghq.atlassian.net/browse/DOCS-4629 for an editorial review!

2023-01-13 15:44 UTC, kayayarai requested changes

2023-01-13 15:44 UTC, kayayarai commented on content/en/profiler/profiler_troubleshooting.md
> +The Ruby profiler truncates deep backtraces when collecting profiling data. Truncated backtraces are missing some of their caller functions making it impossible to link them to the root call frame. A
```suggestion
The Ruby profiler truncates deep backtraces when collecting profiling data. Truncated backtraces are missing some of their caller functions, making it impossible to link them to the root call frame. As a result, truncated backtraces are grouped together under a `N frames omitted` frame.
```

2023-01-13 15:44 UTC, kayayarai commented on content/en/profiler/profiler_troubleshooting.md
> +The maximum depth can be increased using the `DD_PROFILING_MAX_FRAMES` environment variable, or via code:
```suggestion
You can increase the maximum depth with the `DD_PROFILING_MAX_FRAMES` environment variable, or in code:
```

2023-01-13 21:14 UTC, merged

2023-01-13 21:14 UTC, kayayarai reviewed
oops, approved.

2023-01-16 09:15 UTC, ivoanjo commented
Thank you! :)