[RUM Browser] Document new init parameters
DataDog/documentation pull request #16376
Opened 2023-01-06 16:15 UTC by bcaudan

### What does this PR do?

- Use new init parameters: `sessionSampleRate`, `traceSampleRate`, `trackUserInteractions`
- Deprecate old ones

### Motivation

Following #1917, document new init parameters

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-10 15:47 UTC, BenoitZugmeyer commented on content/en/real_user_monitoring/guide/sampling-browser-plans.md
> -    sampleRate: 100,
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**💬 suggestion:** ‏Introduce a `before v4.30.0` section to keep track of the history

2023-01-10 16:17 UTC, BenoitZugmeyer approved these changes

2023-01-10 21:32 UTC, rtrieu requested changes
Hi @bcaudan , added a few suggestions for your review!

2023-01-11 18:14 UTC, rtrieu approved these changes

2023-01-12 16:03 UTC, merged