Update troubleshooting steps with Windows steps
DataDog/documentation pull request #16397
Opened 2023-01-09 21:15 UTC by hestonhoffman

Updates Logs troubleshooting instructions for Linux and adds instructions for Windows.

### Motivation

See [DOCS-4576](https://datadoghq.atlassian.net/browse/DOCS-4576)

### Preview
Watch for a git comment below with a link to the preview.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-09 21:29 UTC, clarkb7 commented on content/en/logs/guide/log-collection-troubleshooting-guide.md
> +
could maybe show the `get-acl` output again with the permissions added.

2023-01-09 21:30 UTC, clarkb7 approved these changes

2023-01-09 21:37 UTC, clarkb7 approved these changes
LGTM for windows

2023-01-09 22:46 UTC, cswatt requested changes
just a tiny nit

2023-01-09 22:46 UTC, cswatt commented on content/en/logs/guide/log-collection-troubleshooting-guide.md
> +The Datadog Agent does not run as root (and running as root is not recommended, as a general best-practice). When you configure your Agent to tail log files for custom logs or for integrations, you n
```suggestion
The Datadog Agent does not run as root (and running as root is not recommended, as a general best practice). When you configure your Agent to tail log files for custom logs or for integrations, you need to take special care to ensure the Agent user has the correct access to the log files.
```

2023-01-10 17:46 UTC, clarkb7 approved these changes

2023-01-11 16:56 UTC, cswatt approved these changes

2023-01-11 18:56 UTC, merged