Add note about azure sql db billing implications
DataDog/documentation pull request #16413
Opened 2023-01-10 22:06 UTC by jmeunier28

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-10 22:14 UTC, jtappa requested changes

2023-01-10 22:14 UTC, jtappa commented on content/en/database_monitoring/setup_sql_server/azure.md
> +**Note:** Due to the fact that Azure SQL Database deploys a database in an isolated network, each database is treated as a single host. This means that if you run Azure SQL Database in an elastic poo
```suggestion
**Note:** Azure SQL Database deploys a database in an isolated network, each database is treated as a single host. This means that if you run Azure SQL Database in an elastic pool, each database in the pool is treated as a separate host.
```

2023-01-13 18:23 UTC, jtappa approved these changes

2023-01-13 18:24 UTC, merged

2023-01-13 19:23 UTC, jmeunier28 commented
thanks @jtappa !!