[synthetics] Update PL gov doc to mention FIPS-compliant requests
DataDog/documentation pull request #16466
Opened 2023-01-13 14:56 UTC by ruizb

### What does this PR do?
Update the documentation about Synthetics Private Location running on GovCloud, to mention the FIPS compliance of some requests it performs.

### Motivation
The next Private Location release will contain a component that allows some of its requests to run in FIPS mode, for PLs whose site is ddog-gov.com.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-13 23:12 UTC, buraizu requested changes
Thanks for the PR, I just suggested a minor update for accessibility. Also, could you remove your changes to `content/fr/synthetics/private_locations/_index.md`? It's sufficient to make changes to the English language repo; this initiates the translation process for the `/fr` and `/ja` documentation repos. If you'd like to know more about the process, feel free to reach out internally, and I can share some additional resources which explain it in more detail.

2023-01-13 23:12 UTC, buraizu commented on content/en/synthetics/private_locations/_index.md
> +| 443  | `intake.synthetics.ddog-gov.com` | Used by the private location to pull test configurations and push test results to Datadog using an in-house protocol based on [AWS Signature Version 4 prot
```suggestion
| 443  | `intake.synthetics.ddog-gov.com` | Used by the private location to pull test configurations and push test results to Datadog using an in-house protocol based on [AWS Signature Version 4 protocol][1]. For versions 1.32.0 and later, these requests are FIPS compliant. |
```

2023-01-17 17:55 UTC, buraizu approved these changes
Thanks for making that change, just added a final suggestion as I noticed FIPS is not spelled out elsewhere in the doc.

2023-01-17 17:55 UTC, buraizu commented on content/en/synthetics/private_locations/_index.md
> +| 443  | `intake.synthetics.ddog-gov.com` | Used by the private location to pull test configurations and push test results to Datadog using an in-house protocol based on [AWS Signature Version 4 prot
```suggestion
| 443  | `intake.synthetics.ddog-gov.com` | Used by the private location to pull test configurations and push test results to Datadog using an in-house protocol based on [AWS Signature Version 4 protocol][1]. For versions 1.32.0 and later, these requests are Federal Information Processing Standards (FIPS) compliant. |
```

2023-01-20 13:14 UTC, ruizb commented
Hello @buraizu, thank you for your reviews! Feel free to merge the PR as It seems I am not authorized to do it.

2023-01-24 09:19 UTC, m-rousse approved these changes

2023-01-24 17:01 UTC, merged