DOCS-4510 Synthetic Monitoring & Continuous Testing Explorer Edits + Search Test Runs Documentation
DataDog/documentation pull request #16561
Opened 2023-01-20 23:09 UTC by alai97

### What does this PR do?

Adds Search Test Runs doc page, adds an Explorer section in Synthetics and Continuous Testing doc sets, and renames the CI Results Explorer in several places.

### Motivation

DOCS-4510

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-20 23:09 UTC, alai97 commented on content/en/continuous_testing/explorer/_index.md
> +to add image here
Remember to add an image!

2023-01-20 23:09 UTC, alai97 commented on content/en/continuous_testing/explorer/_index.md
> +to add image here
Remember to add an image!

2023-01-23 18:11 UTC, buraizu commented
Thanks, created DOCS-4726 to review

2023-01-24 10:54 UTC, peculiarism reviewed
Just a couple of points, let me know what you think!

2023-01-24 10:54 UTC, peculiarism commented on content/en/continuous_testing/explorer/search_runs.md
> +| `DNS`  | The CI provider associated with the batch.  |
We need to update these descriptions, they slipped through my draft sorry about that! Let's go with the following: 

```
DNS: The time spent resolving the DNS name for an API test run
Download: The time spent downloading the response for an API test run
First Byte: The time spent waiting for the first byte of the response to be received for an API test run
Open: The overall time a websocket remained open for a WebSocket test run
Received: The overall time a websocket connection spent receiving data for a WebSocket test run
TCP: The time spend establishing a TCP connection for an API test run
Total: The total response time for an API test run
```

2023-01-24 10:54 UTC, peculiarism commented on content/en/continuous_testing/explorer/search_runs.md
> +**Timings** facets allow you to filter on timing related attributes.
```suggestion
**Timings** facets allow you to filter on timing related attributes for API test runs.
```

2023-01-25 14:08 UTC, peculiarism approved these changes

2023-01-25 19:31 UTC, alai97 commented on content/en/synthetics/_index.md
> +Create [search queries and visualizations][20] for your Synthetic test runs or batches of tests running in CI/CD pipelines.
```suggestion

{{< img src="continuous_testing/explorer_ci_batches.png" alt="Continuous Testing Explorer" style="width:100%;">}}

Create [search queries and visualizations][20] for your Synthetic test runs or batches of tests running in CI/CD pipelines. 
```

2023-01-25 19:38 UTC, alai97 commented on content/en/continuous_testing/explorer/_index.md
> +Navigate to [**UX Monitoring** > **Explorer**][1] and click on an out-of-the-box search query to start viewing your test batches or test runs and create visualizations.
```suggestion
Navigate to [**UX Monitoring** > **Explorer**][1] and click on an out-of-the-box search query to start viewing your test batches or runs and creating visualizations.
```

2023-01-27 18:50 UTC, alai97 commented on config/_default/menus/menus.en.yaml
> +    url: synthetics/explorer/
```suggestion
    url: synthetics/explorer
```

2023-01-27 18:57 UTC, alai97 commented on config/_default/menus/menus.en.yaml
> +    url: synthetics/explorer
```suggestion
    url: countinuous_testing/explorer
```

2023-01-27 19:10 UTC, alai97 commented on config/_default/menus/menus.en.yaml
> +    url: countinuous_testing/explorer
```suggestion
    url: continuous_testing/explorer
```

2023-01-27 19:23 UTC, alai97 commented on config/_default/menus/menus.en.yaml
> +    url: continuous_testing/explorer
```suggestion
    url: continuous_testing/explorer/
```

2023-01-27 19:23 UTC, alai97 commented on config/_default/menus/menus.en.yaml
> +    url: /continuous_testing/explorer/
```suggestion
    url: continuous_testing/explorer/
```

2023-01-27 21:16 UTC, rtrieu requested changes
Left a few suggestions for you!

2023-01-27 21:16 UTC, rtrieu commented on content/en/continuous_testing/explorer/_index.md
> +* Examine performance issues with result timing facets and filter runs by failing status codes
> * Examine performance issues with _result timing facets_ and filter runs by failing status codes

Once I found this in the UI, I understood what it was, but it's hard to know without context. Maybe a screenshot would help, if you were so inclined!

2023-01-27 22:25 UTC, rtrieu approved these changes
Looking good!

2023-01-30 19:03 UTC, merged