[dotnet] Add requirements for .NET profiler
DataDog/documentation pull request #16599
Opened 2023-01-24 18:21 UTC by chrisnas

### What does this PR do?

Add profiler and runtime version requirements

### Motivation

Avoid misunderstanding for the customers

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-24 18:55 UTC, kayayarai requested changes

2023-01-24 18:55 UTC, kayayarai commented on content/en/profiler/profile_types.md
>  : The number and size of allocated objects by each method, as well as their type.
```suggestion
: The number and size of allocated objects by each method, as well as their type.<br />
```

2023-01-24 18:55 UTC, kayayarai commented on content/en/profiler/profile_types.md
>  : A subset of the allocated objects (with their class name) that are still in memory and for how long.
```suggestion
: A subset of the allocated objects (with their class name) that are still in memory and for how long.<br />
```

2023-01-24 18:55 UTC, kayayarai commented on content/en/profiler/profile_types.md
> +CPU (since 2.15)
```suggestion
CPU (v2.15+)
```

2023-01-24 18:55 UTC, kayayarai commented on content/en/profiler/profile_types.md
> +Thrown Exceptions (beta since 2.10)
```suggestion
Thrown Exceptions (beta, v2.10+)
```

2023-01-24 18:55 UTC, kayayarai commented on content/en/profiler/profile_types.md
> +Allocations (beta since 2.18)
```suggestion
Allocations (beta, v2.18+)
```

2023-01-24 18:55 UTC, kayayarai commented on content/en/profiler/profile_types.md
> +Lock (beta since 2.18)
```suggestion
Lock (beta, v2.18+)
```

2023-01-24 18:55 UTC, kayayarai commented on content/en/profiler/profile_types.md
> +Live Heap (beta since 2.22)
```suggestion
Live Heap (beta, v2.22+)
```

2023-01-24 18:55 UTC, kayayarai commented on content/en/profiler/enabling/dotnet.md
> +| Live heap profiling        | beta since 2.22.0+                       |
```suggestion
| Exceptions profiling        | beta, 2.10.0+                       |
| Allocations profiling        | beta, 2.18.0+                       |
| Lock Contention profiling        | beta, 2.18.0+                       |
| Live heap profiling        | beta, 2.22.0+                       |
```

2023-01-25 21:26 UTC, dbenamydd approved these changes
Thanks!

2023-01-25 21:29 UTC, kayayarai approved these changes

2023-01-25 21:29 UTC, merged