Document new Agent option (hostname_trust_uts_namespace)
DataDog/documentation pull request #16610
Opened 2023-01-25 10:11 UTC by vboulineau

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-25 20:49 UTC, rtrieu requested changes
Left some minor suggestions for your review. Otherwise LGTM!

2023-01-25 20:49 UTC, rtrieu commented on content/en/agent/troubleshooting/hostname_containers.md
> +## Hostname errors in CI environments, sidecar setups, environments without access to container runtime
```suggestion
## Hostname errors in CI environments, sidecar setups, and environments without access to container runtime
```

2023-01-25 20:49 UTC, rtrieu commented on content/en/agent/troubleshooting/hostname_containers.md
> +- Setting `DD_HOSTNAME` (`hostname` in `datadog.yaml`) explicitly to host hostname:
```suggestion
- Setting `DD_HOSTNAME` (`hostname` in `datadog.yaml`) explicitly to the hostname:
```

2023-01-25 20:49 UTC, rtrieu commented on content/en/agent/troubleshooting/hostname_containers.md
> +When this is set, the Agent will use in-container hostname (usually, container name or pod name).
```suggestion
When this is set, the Agent will use the in-container hostname (usually the container name or pod name).
```

2023-01-25 20:49 UTC, rtrieu commented on content/en/agent/troubleshooting/hostname_containers.md
>  **Note:** This does not apply to serverless solutions like Fargate.
```suggestion
**Note**: This does not apply to serverless solutions like Fargate.
```

2023-01-26 20:31 UTC, rtrieu approved these changes
Thanks for making the changes!

2023-01-27 09:14 UTC, vboulineau commented
@rtrieu Thanks for the review, I don't have the rights to merge so I'd need for you to do it :)

2023-01-27 16:54 UTC, merged