(DOCS-4329) High CPU or Memory Troubleshooting
DataDog/documentation pull request #16695
Opened 2023-01-31 01:07 UTC by hestonhoffman

[DOCS-4329](https://datadoghq.atlassian.net/browse/DOCS-4329) 

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-31 19:52 UTC, urseberry commented
https://datadoghq.atlassian.net/browse/DOCS-4793

2023-02-08 19:32 UTC, cswatt requested changes

2023-02-08 19:32 UTC, cswatt commented on content/en/agent/troubleshooting/high_memory_usage.md
> +- The Agent is forwarding a very large number of log lines or DogstatsD metrics.
```suggestion
- The Agent is forwarding a very large number of log lines or DogStatsD metrics.
```

2023-02-08 19:32 UTC, cswatt commented on content/en/agent/troubleshooting/high_memory_usage.md
> +Common causes of high CPU or memory consumption:
should we make this an H3 or so? might make the page easier to parse at-a-glance
```suggestion
### Common causes of high CPU or memory consumption:
```

2023-02-08 19:32 UTC, cswatt commented on content/en/agent/troubleshooting/high_memory_usage.md
> +Here are some adjustments you can make to your Agent configuration to reduce resource usage:
```suggestion
### Here are some adjustments you can make to your Agent configuration to reduce resource usage:
```

same as above, but i'm not super opinionated about this

2023-02-08 19:56 UTC, cswatt approved these changes

2023-02-08 20:17 UTC, merged