CI Visibility - Swift - Add information about the GitHub action
DataDog/documentation pull request #16699
Opened 2023-01-31 14:51 UTC by nachoBonafonte

### What does this PR do?
Add information about the GitHub action
Add a section about Best practices

### Motivation
Adding new information to customers

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-31 18:55 UTC, albertvaka commented on content/en/continuous_integration/tests/swift.md
> +{{% /tab %}}
```suggestion
```

2023-01-31 21:56 UTC, urseberry reviewed
I need to pass this off to another writer due to time constraints. Stay tuned for more feedback.

Also, I was unable to get your new "Github Actions" tab to show up in the preview. If you have some time, please spin up a local build and debug it so it shows up correctly. Instructions are in the top level repository README file and troubleshooting is in Confluence here: https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/2231206099/Docs+Build

2023-01-31 21:56 UTC, urseberry commented on content/en/continuous_integration/tests/swift.md
> +If you use GitHub, you can use the [Swift Test Action][1] from GitHub marketplace to automatically configure and run your tests. By default, the rest of configuration explained in this document can b
```suggestion
If you use GitHub, you can use the [Swift test action][1] from GitHub marketplace to automatically configure and run your tests. By default, the rest of the configuration explained in this document can be skipped (except the configuration of the action itself), but can also use the configuration environment variables for disabling or configuring extra functionality.
```

2023-01-31 21:59 UTC, urseberry commented
https://datadoghq.atlassian.net/browse/DOCS-4799

2023-02-07 19:27 UTC, rtrieu requested changes
Hi @nachoBonafonte left some feedback for your review! Please let me know if you have any questions. Also, I love your username.

2023-02-07 19:27 UTC, rtrieu commented on content/en/continuous_integration/tests/swift.md
> +With some Xcode versions UITest bundles are built by default with sandbox settings, the testing framework needs to run some system commands with `xcrun` and this settings dissallow running them, so m
```suggestion
In some Xcode versions, UI Test bundles are built with a sandbox by default. The settings that come with a sandbox prevent the testing framework from being run by some system commands with `xcrun`, so you'll need to disable it.
```

2023-02-07 19:27 UTC, rtrieu commented on content/en/continuous_integration/tests/swift.md
> +Sandbox can be disabled by adding Entitlements to the UITest runner bundle & adding `App Sandbox = NO` to them. You can also create a .entitlement file and add it to the Signing Build Settings, this
```suggestion
Disable the sandbox by adding Entitlements to the UI Test runner bundle, then adding `App Sandbox = NO` to them. You can also create an `.entitlement` file and add it to the Signing Build Settings. This file should should include the following content:
```

2023-02-07 19:36 UTC, urseberry commented on content/en/continuous_integration/tests/swift.md
> +The testing framework uses symbol files for some of its functionality: simbolicating crashes, reporting test source location, report codeowners... It automatically generates the symbol file when debu
I believe this line needs a further edit: "and report codeowners" should be "and reporting code owners."

2023-02-10 09:49 UTC, nachoBonafonte commented on content/en/continuous_integration/tests/swift.md
> +This option has the benefit that no code changes are needed but has the drawback that it is less flexible to configure and run.
* It refers to the Swift test actions
* It is less flexible than he other ways, yes

2023-02-10 09:51 UTC, nachoBonafonte commented on content/en/continuous_integration/tests/swift.md
> +Build in Xcode using `DWARF with dSYM File` (or `-Xswiftc -debug-info-format=dwarf` if building with `swift`)
```suggestion
Build your code in Xcode using `DWARF with dSYM File` (or `-Xswiftc -debug-info-format=dwarf` if building with `swift`)
```

2023-02-10 16:26 UTC, rtrieu requested changes
One last edit and then we're good!

2023-02-10 16:26 UTC, rtrieu commented on content/en/continuous_integration/tests/swift.md
> +This option has the benefit that no code changes are needed but has the drawback that it is less flexible to configure and run.
```suggestion
Compared to other methods, such as Cocoapods and Framework linking, the Swift test action option may be less flexible to configure and run, but requires no code changes.
```

2023-02-14 18:09 UTC, rtrieu approved these changes

2023-02-14 22:27 UTC, merged