Add extra note for open ports
DataDog/documentation pull request #16698
Opened 2023-01-31 14:19 UTC by ajgajg1134

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-01-31 14:44 UTC, pawelchcki approved these changes
LGTM

2023-01-31 21:30 UTC, urseberry requested changes

2023-01-31 21:30 UTC, urseberry commented on content/en/agent/guide/network.md
> +</div>
```suggestion
<div class="alert alert-warning">
Ensure the Agent is only accessible by your applications or trusted network sources using a firewall rule or similar network restriction. Untrusted access allows malicious actors to perform several invasive actions, including but not limited to writing traces and metrics to your Datadog account, and obtaining information about your configuration and services.
</div>
```
Also, move this whole section to **before** "Open the following ports..." The current location is interrupts the instruction about which ports to open.

2023-02-01 03:50 UTC, urseberry commented on content/en/agent/guide/network.md
> +Ensure the Agent is only accessible by your applications or trusted network sources using a firewall rule or similar network restriction. Untrusted access can allow malicious actors to perform severa
```suggestion
<br>
Ensure the Agent is only accessible by your applications or trusted network sources using a firewall rule or similar network restriction. Untrusted access can allow malicious actors to perform several invasive actions, including but not limited to writing traces and metrics to your Datadog account, or obtaining information about your configuration and services.
```

2023-02-01 04:08 UTC, urseberry commented on content/en/agent/guide/network.md
> +<br>
```suggestion
<br><br>
```

2023-02-01 04:20 UTC, urseberry approved these changes

2023-02-01 04:20 UTC, merged