[Tracing][PHP] Document IP collection in PHP
DataDog/documentation pull request #16697
Opened 2023-01-31 14:06 UTC by pierotibou

### What does this PR do?
States that we are reintroduing IP Collection, disabled by default, in the php tracer.

### Motivation
Feature asked by clients. Will be merged when https://github.com/DataDog/dd-trace-php/pull/1895 is released

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-03 17:12 UTC, jtappa requested changes

2023-02-03 17:12 UTC, jtappa commented on content/en/tracing/trace_collection/library_config/dotnet-core.md
> +**Default**: We parse all the followings. `"x-forwarded-for", "x-real-ip", "client-ip", "x-forwarded", "x-cluster-client-ip", "forwarded-for", "forwarded", "via", "true-client-ip"`. If several are pr
```suggestion
**Default**: Datadog parses the following: `"x-forwarded-for", "x-real-ip", "client-ip", "x-forwarded", "x-cluster-client-ip", "forwarded-for", "forwarded", "via", "true-client-ip"`. If several are present, none will be reported.<br>
```

2023-02-03 17:12 UTC, jtappa commented on content/en/tracing/trace_collection/library_config/dotnet-framework.md
> +**Default**: We parse all the followings. `"x-forwarded-for", "x-real-ip", "client-ip", "x-forwarded", "x-cluster-client-ip", "forwarded-for", "forwarded", "via", "true-client-ip"`. If several are pr
```suggestion
**Default**: Datadog parses the following: `"x-forwarded-for", "x-real-ip", "client-ip", "x-forwarded", "x-cluster-client-ip", "forwarded-for", "forwarded", "via", "true-client-ip"`. If several are present, none will be reported.<br>
```

2023-02-03 17:12 UTC, jtappa commented on content/en/tracing/trace_collection/library_config/php.md
> +Enables IP Collection client side. Added in version `0.84.0`.
```suggestion
Enables IP collection client side. Added in version `0.84.0`.
```

2023-02-07 12:34 UTC, pierotibou commented
Thanks a lot @jtappa for the review. I've applied all your changes

2023-02-07 18:18 UTC, jtappa approved these changes

2023-02-07 18:23 UTC, jtappa commented
Looks like the runners were full so the build failed, re-running in gitlab

2023-02-07 20:40 UTC, merged