📝 [RUMF-1469] the new proxy configuration
DataDog/documentation pull request #16727
Opened 2023-02-01 15:09 UTC by BenoitZugmeyer

### What does this PR do?

Update the RUM proxy configuration. Should be released after https://github.com/DataDog/browser-sdk/pull/1947

### Motivation

Context: https://docs.google.com/document/d/1XTl6iuCbzVnnNceMkvgJH-bsBdW7sP2ExnDKQzJDBF8/edit#heading=h.rnd972k0hiye

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-02 10:28 UTC, bcaudan approved these changes
LGTM

2023-02-03 23:46 UTC, rtrieu requested changes
Left some feedback for your review. Otherwise, looks good!

2023-02-03 23:46 UTC, rtrieu commented on content/en/real_user_monitoring/guide/proxy-rum-data.md
> +When your proxy receives data from the RUM Browser SDK, it must be forwarded to Datadog. The RUM Browser SDK adds the `ddforward` query parameter to all POST requests to your proxy. This query parame
```suggestion
When your proxy receives data from the RUM Browser SDK, it must be forwarded to Datadog. The RUM Browser SDK adds the `ddforward` query parameter to all POST requests to your proxy. This query parameter contains the URL path and parameters that all data must be forwarded to.
```

2023-02-03 23:46 UTC, rtrieu commented on content/en/real_user_monitoring/guide/proxy-rum-data.md
>  4. The request body must remain unchanged.
```suggestion
4. Leave the request body unchanged.
```

2023-02-03 23:46 UTC, rtrieu commented on content/en/real_user_monitoring/guide/proxy-rum-data.md
> +The Site Parameter is an SDK [initialization parameter][1]. Datadog intake origins for each site are listed below:
```suggestion
The site parameter is an SDK [initialization parameter][1]. Datadog intake origins for each site are listed below:
```

2023-02-03 23:46 UTC, rtrieu commented on content/en/real_user_monitoring/guide/proxy-rum-data.md
> +The Datadog intake origin corresponding to your Site Parameter should be defined in your proxy implementation.
```suggestion
The Datadog intake origin corresponding to your site parameter should be defined in your proxy implementation.
```

2023-02-03 23:46 UTC, rtrieu commented on content/en/real_user_monitoring/guide/proxy-rum-data.md
> +<strong>If you are still using a proxy with an older version of the Browser SDK, please consider upgrading to a newer version of the Browser SDK.</strong>
```suggestion
<strong>If you are still using a proxy with an older version of the Browser SDK, we recommend upgrading to a newer version of the Browser SDK.</strong>
```

2023-02-07 19:30 UTC, rtrieu approved these changes
Looks good, thanks!

2023-02-09 16:56 UTC, merged