[DOCS-4684] Add images to Obs Pipelines Prod Deployment Overview docs
DataDog/documentation pull request #16748
Opened 2023-02-01 21:17 UTC by maycmlee

### What does this PR do?

Adds images to Obs Pipelines' Prod Deployment Overview docs.

### Motivation

[DOCS-4684](https://datadoghq.atlassian.net/browse/DOCS-4684)

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-07 17:19 UTC, barieom approved these changes
Looks great, thank you for updating this!

2023-02-09 01:33 UTC, rtrieu requested changes
Left a few suggestions, but otherwise lovely update!

2023-02-09 01:33 UTC, rtrieu commented on content/en/observability_pipelines/production_deployment_overview/architecture_design_and_principles.md
> +{{< img src="observability_pipelines/production_deployment_overview/agent.png" alt="A diagram showing two separate nodes, each containing services, other agents, other node data, and an Observability
```suggestion
{{< img src="observability_pipelines/production_deployment_overview/agent.png" alt="A diagram showing two separate nodes, each containing services, other agents, other node data, and an Observability Pipelines Worker, from which the node and agent data is sent to the Worker, and then to the sinks" style="width:70%;" >}}
```

2023-02-09 01:33 UTC, rtrieu commented on content/en/observability_pipelines/production_deployment_overview/architecture_design_and_principles.md
> +{{< img src="observability_pipelines/production_deployment_overview/unified.png" alt="A diagram showing a node containing multiple services and another agent, both sending data to the Worker in the n
```suggestion
{{< img src="observability_pipelines/production_deployment_overview/unified.png" alt="A diagram showing a node containing multiple services and another agent, both sending data to the Worker in the node, and the Worker sends the data to the load balancers. The load balancer then sends data to the aggregator, which contains multiple Workers" style="width:70%;" >}}
```

2023-02-09 17:19 UTC, maycmlee reviewed
Thanks @rtrieu for reviewing and the feedback! Could you re-review?

2023-02-09 20:13 UTC, rtrieu approved these changes
👍 🎉

2023-02-09 20:14 UTC, merged