[RUMF-1394] 📝 mention antivirus softwares in troubleshooting docs
DataDog/documentation pull request #16829
Opened 2023-02-08 13:42 UTC by BenoitZugmeyer

### What does this PR do?

mention antivirus softwares in RUM troubleshooting docs

### Motivation

It has been suggested that Antivirus Softwares might block Session Replay files from being sent to the datadog intake. 
See investigation: https://docs.google.com/document/d/1Wrm7QFp7P1ysMbEOtIaKDZfqK83oYcqRWbu3-pdqUjs/edit#

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-08 20:44 UTC, buraizu requested changes
Thanks for the PR, I left just a couple of small suggestions.

2023-02-08 20:44 UTC, buraizu commented on content/en/real_user_monitoring/browser/troubleshooting.md
> +| Network rules, VPNs or antivirus softwares can prevent the RUM Browser SDK from being downloaded or sending data to Datadog. | Grant access to the endpoints required to download the RUM Browser SDK
```suggestion
| Network rules, VPNs, or antivirus software can prevent the RUM Browser SDK from being downloaded or sending data to Datadog. | Grant access to the endpoints required to download the RUM Browser SDK or to send data. The list of endpoints is available in the [Content Security Policy documentation][5].                                        |
```

2023-02-09 08:56 UTC, bcaudan approved these changes

2023-02-09 16:53 UTC, buraizu approved these changes

2023-02-09 16:54 UTC, merged