usm: Added docker-swarm documentation
DataDog/documentation pull request #16825
Opened 2023-02-08 05:27 UTC by guyarb

### What does this PR do?

Adds docker-swarm installation instructions for USM

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-08 17:52 UTC, buraizu requested changes
Thanks for the PR, just suggested some minor edits.

2023-02-08 17:52 UTC, buraizu commented on content/en/universal_service_monitoring/_index.md
> +does not have a running `apparmor` instance.
```suggestion
As `Docker Swarm` does not yet support the changing of `security_opt`, the operating system
must not have a running `apparmor` instance.
```

2023-02-08 17:52 UTC, buraizu commented on content/en/universal_service_monitoring/_index.md
> +If that is the case, then use the same `docker-compose.yml` file from `Docker-Compose` [section][1] besides the field `security_opt`.
```suggestion
If the operating system does not have a running `apparmor` instance, then use the same `docker-compose.yml` file from `Docker-Compose` [section][1] beside the field `security_opt`.
```

2023-02-08 17:55 UTC, guyarb commented
@buraizu committed the suggestions, thanks

2023-02-09 19:07 UTC, buraizu approved these changes
Thanks for applying those changes, I left one last small suggestion but overall this LGTM

2023-02-09 19:08 UTC, merged