Update Installation docs
DataDog/documentation pull request #16831
Opened 2023-02-08 16:06 UTC by crysmags

The aim is to have the note about instrumenting machine wide be more visible and to include runtime version requirements in the feature table

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-09 18:28 UTC, rtrieu approved these changes
Looks great, thanks!

2023-02-09 18:37 UTC, rtrieu requested changes
WIP

2023-02-14 21:55 UTC, kayayarai approved these changes

2023-02-14 21:55 UTC, kayayarai commented
verified in local build

2023-02-14 21:55 UTC, merged