Docs 4864/asm user tracking updates
DataDog/documentation pull request #16876
Opened 2023-02-10 14:55 UTC by maxhedouin

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-10 19:59 UTC, hestonhoffman commented
Thanks for the update @maxhedouin, I've created an [Editorial review card](https://datadoghq.atlassian.net/browse/DOCS-4871) and someone on the docs team will take a look soon

2023-02-13 10:19 UTC, robertpi approved these changes

2023-02-13 15:26 UTC, kayayarai requested changes
Some minor edits. I'll commit these, and repeat the same edits on all the tabs.

2023-02-13 15:26 UTC, kayayarai commented on content/en/security/application_security/threats/add-user-info.md
> +Add authenticated user information on traces to identify and block bad actors targeting your authenticated attack surface. The authenticated user monitoring and blocking is done by setting the user i
```suggestion
Add authenticated user information on traces to identify and block bad actors targeting your authenticated attack surface. To do this, set the user ID tag on the running APM trace, providing the necessary instrumentation for ASM to block authenticated attackers. This allows ASM to associate attacks and business logic events to users.
```

2023-02-13 15:26 UTC, kayayarai commented on content/en/security/application_security/threats/add-user-info.md
> +Track user logins to detect account takeovers with out of the box detection rules, and ultimately block attackers.
```suggestion
Track user logins to detect account takeovers with out-of-the-box detection rules, and to ultimately block attackers.
```

2023-02-13 15:26 UTC, kayayarai commented on content/en/security/application_security/threats/add-user-info.md
> +Use the the Java tracer's API to track user events, released in dd-trace-java v1.8.0.
```suggestion
Starting in dd-trace-java v 1.8.0, you can use the the Java tracer's API to track user events. 
```

2023-02-13 15:26 UTC, kayayarai commented on content/en/security/application_security/threats/add-user-info.md
> +The example below shows how to track login events, as well as custom events (using signup as an example)
```suggestion
The following examples show how to track login events or custom events (using signup as an example).
```

2023-02-13 15:26 UTC, kayayarai commented on content/en/security/application_security/threats/add-user-info.md
> +{{% tab "login success" %}}
```suggestion
{{% tab "Login success" %}}
```

2023-02-13 15:26 UTC, kayayarai commented on content/en/security/application_security/threats/add-user-info.md
> +{{% tab "login failure" %}}
```suggestion
{{% tab "Login failure" %}}
```

2023-02-13 15:26 UTC, kayayarai commented on content/en/security/application_security/threats/add-user-info.md
> +{{% tab "custom business logic" %}}
```suggestion
{{% tab "Custom business logic" %}}
```

2023-02-13 16:06 UTC, kayayarai approved these changes

2023-02-13 16:26 UTC, merged

2023-02-13 16:29 UTC, Julio-Guerra commented on content/en/security/application_security/threats/add-user-info.md
> +Starting in dd-trace-py v1.9.0, you can use the the Python tracer's API to track user events.
```suggestion
Starting in dd-trace-py v1.9.0, you can use the Python tracer's API to track user events.
```

2023-02-13 16:29 UTC, Julio-Guerra commented on content/en/security/application_security/threats/add-user-info.md
> +Starting in dd-trace-java v1.8.0, you can use the the Java tracer's API to track user events.
```suggestion
Starting in dd-trace-java v1.8.0, you can use the Java tracer's API to track user events. 
```

2023-02-13 16:29 UTC, Julio-Guerra commented on content/en/security/application_security/threats/add-user-info.md
> +Starting in dd-trace-dotnet v2.23.0, you can use the the .NET tracer's API to track user events.
```suggestion
Starting in dd-trace-dotnet v2.23.0, you can use the .NET tracer's API to track user events. 
```

2023-02-13 16:29 UTC, Julio-Guerra commented on content/en/security/application_security/threats/add-user-info.md
> +Starting in dd-trace-go v1.47.0, you can use the the Go tracer's API to track user events.
```suggestion
Starting in dd-trace-go v1.47.0, you can use the Go tracer's API to track user events. 
```

2023-02-13 16:29 UTC, Julio-Guerra commented on content/en/security/application_security/threats/add-user-info.md
> +Starting in dd-trace-rb v1.9.0, you can use the the Ruby tracer's API to track user events.
```suggestion
Starting in dd-trace-rb v1.9.0, you can use the Ruby tracer's API to track user events.
```

2023-02-13 16:29 UTC, Julio-Guerra commented on content/en/security/application_security/threats/add-user-info.md
> +Starting in dd-trace-php v0.84.0, you can use the the PHP tracer's API to track user events.
```suggestion
Starting in dd-trace-php v0.84.0, you can use the PHP tracer's API to track user events.
```

2023-02-13 16:29 UTC, Julio-Guerra commented on content/en/security/application_security/threats/add-user-info.md
> +Starting in dd-trace-js v3.13.1, you can use the the NodeJS tracer's API to track user events.
```suggestion
Starting in dd-trace-js v3.13.1, you can use the NodeJS tracer's API to track user events.
```