Updated tag policies and added to monitor overview
DataDog/documentation pull request #16954
Opened 2023-02-15 19:07 UTC by estherk15

### What does this PR do?
- Updated Tag Policies with new image of the page.
- Added a section to the Monitors Overview page to reference tag policies.

**Do not merge**, pending PM review

### Motivation
[DOCS-4889](https://datadoghq.atlassian.net/browse/DOCS-4889)

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-16 20:32 UTC, cswatt requested changes

2023-02-16 20:32 UTC, cswatt commented on content/en/monitors/notify/_index.md
> +{{< img src="monitors/notifications/notifications_add_required_tags.png" alt="Policy tag requirements" style="width:100%;" >}}
```suggestion
{{< img src="monitors/notifications/notifications_add_required_tags.png" alt="View of policy tag configuration. Underneath 'Policy tags' are three tags, cost_center, product_id, and env, next to a 'Select value' dropdown." style="width:100%;" >}}
```

2023-02-16 20:32 UTC, cswatt commented on content/en/monitors/settings/_index.md
> +Enforce mandatory tags, select the **Required** check box and specify both the tag key and values. In this example, monitors are required to have the `cost_center` tag. The value must be set to `cc1`
```suggestion
To enforce mandatory tags, select the **Required** check box and specify both the tag key and values. In this example, monitors are required to have the `cost_center` tag. The value must be set to `cc1`, `cc2`, or `cc3`.
```

2023-02-16 20:32 UTC, cswatt commented on content/en/monitors/settings/_index.md
> +Require a tag but allow users to specify their own values. In this example, monitors are required to have the `product_id` tag. The value can be anything specified by the user.
```suggestion
You can require a tag but allow users to specify their own values. In this example, monitors are required to have the `product_id` tag. The value can be anything specified by the user.
```

2023-02-16 20:32 UTC, cswatt commented on content/en/monitors/settings/_index.md
> +Make a tag optional but require that monitors with the tag use specific values, enter the values for the tag in the **Values** field. In this example, the `env` tag is optional. However, if a monitor
```suggestion
To make a tag optional but require that monitors with the tag use specific values, enter the values for the tag in the **Values** field. In this example, the `env` tag is optional. However, if a monitor uses this tag, the value must be set to `dev`, `staging`, or `prod`.
```

2023-02-17 14:28 UTC, estherk15 commented on content/en/monitors/notify/_index.md
> +{{< img src="monitors/notifications/notifications_add_required_tags.png" alt="View of policy tag configuration. Underneath 'Policy tags' are three tags, cost_center, product_id, and env, next to a 'S
```suggestion
{{< img src="monitors/notifications/notifications_add_required_tags.png" alt="View of policy tag configuration. Underneath 'Policy tags' are three example tags, cost_center, product_id, and env, next to a 'Select value' dropdown." style="width:100%;" >}}
```

2023-02-21 19:42 UTC, cswatt approved these changes

2023-02-21 19:42 UTC, merged