New Feature Flag Tracking page in RUM
DataDog/documentation pull request #17088
Opened 2023-02-24 21:57 UTC by meghanlo

### What does this PR do?
* New page for Feature Flag Tracking in RUM
* Adding menu item for RUM

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-27 14:57 UTC, drichards-87 commented
Thanks for submitting this PR. I've created DOCS-4967 for the review. We'll get it assigned to someone this week.

2023-02-28 22:30 UTC, rtrieu requested changes
Some small suggestions, but otherwise looks good!

2023-02-28 22:30 UTC, rtrieu commented on content/en/real_user_monitoring/feature_flag_tracking/_index.md
> +From this view you can investigate any questions you have about your feature flag’s health and usage.
```suggestion
From this view, you can investigate any questions you have about your feature flag’s health and usage.
```

2023-02-28 22:30 UTC, rtrieu commented on content/en/real_user_monitoring/feature_flag_tracking/_index.md
> +Search and filter your feature flags by typing in the search bar. You can also use the faceted search, to narrow down, broaden, and shift your focus on subsets of feature flags you are interested in.
```suggestion
Search and filter your feature flags by typing in the search bar. You can also use the faceted search to narrow down, broaden, or shift your focus on subsets of feature flags you are interested in.
```

2023-02-28 22:30 UTC, rtrieu commented on content/en/real_user_monitoring/feature_flag_tracking/_index.md
> +- **Inactive**: For the past 2 weeks there have only been feature flag evaluations for your control variant
```suggestion
- **Inactive**: For the past 2 weeks, there have only been feature flag evaluations for your control variant
```

2023-02-28 22:30 UTC, rtrieu commented on content/en/real_user_monitoring/feature_flag_tracking/_index.md
> +- **Out to 100%**: For the past 2 weeks there have only been feature flag evaluations for one of your non-control variants
```suggestion
- **Out to 100%**: For the past 2 weeks, there have only been feature flag evaluations for one of your non-control variants
```

2023-02-28 22:30 UTC, rtrieu commented on content/en/real_user_monitoring/feature_flag_tracking/_index.md
> +To get more details about the health and performance of your feature flag, you can click on the flag in the list to navigate to a dedicated feature flag analysis dashboard. The Feature Flag analysis
```suggestion
To get more details about the health and performance of your feature flag, you can click the flag in the list to navigate to a dedicated feature flag analysis dashboard. The Feature Flag analysis dashboard provides an overview of the performance of your feature flag, displaying information about user sessions, changes in your Core Web Vitals, and error rates. 
```

2023-02-28 22:30 UTC, rtrieu commented on content/en/real_user_monitoring/feature_flag_tracking/_index.md
> +These out of the box graphs are aggregated across your flag variants, making it easy to spot problems in your feature releases before they turn into serious issues. This dashboard provides an easy wa
```suggestion
These out-of-the-box graphs are aggregated across your flag variants, making it easy to spot problems in your feature releases before they turn into serious issues. This dashboard provides an easy way to monitor your feature releases and allows you to quickly roll back as soon as you spot an issue so you can avoid negative user experiences. 
```

2023-02-28 22:30 UTC, rtrieu commented on content/en/real_user_monitoring/feature_flag_tracking/_index.md
> +You can compare important metrics to you and your teams by grouping your query by `@feature_flags.{flag_name}`. For example, if we want to understand how our new checkout flow is affecting the conver
```suggestion
You can compare important metrics to you and your teams by grouping your query by `@feature_flags.{flag_name}`. For example, if you want to understand how your new checkout flow is affecting the conversion rate from the checkout page to users making a purchase, you can add a "Group by" on the conversion rate graph.
```

2023-03-01 19:56 UTC, rtrieu approved these changes
Looks good, thanks!

2023-03-01 19:56 UTC, merged