ITR beta: Mention it also works with the Agent
DataDog/documentation pull request #17097
Opened 2023-02-27 14:37 UTC by albertvaka

### What does this PR do?
Remove note about requiring Agentless for ITR to work.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-02-27 14:48 UTC, edrevo requested changes
I think we need to remove the references to `DD_CIVISIBILITY_AGENTLESS_ENABLED=true` in the rest of the page, since it is not compulsory anymore.

Also, maybe we need to add a mention in the Swift section saying that agent support is not available?

2023-02-27 14:54 UTC, albertvaka commented
That assumes we want to recommend "agentful" over agentless. Is that the case? I think there's less friction for customers to onboard with Agentless (since they don't need to install/upgrade their Agent), so I think the current instructions are okay. But it's not a strong opinion, I can change it if we want to favor the agentful setup.

2023-02-27 14:58 UTC, edrevo commented
<img width="442" alt="image" src="https://user-images.githubusercontent.com/1845771/221597885-e1e94b18-8fe0-4d01-8aad-70b355f0c332.png">

My interpretation of that is that an API_KEY is required, and that the DD_CIVISIBILITY_AGENTLESS_ENABLED must be set to true. Maybe we can change it to this?

```
DD_CIVISIBILITY_AGENTLESS_ENABLED
Enables or disables Agentless mode.
Default: false
```

2023-02-27 17:46 UTC, drichards-87 approved these changes
Approved from Docs. Let me know when the PR is ready to be merged.

2023-02-27 20:27 UTC, albertvaka commented
I've made the changes you suggested @edrevo

2023-02-28 06:31 UTC, edrevo approved these changes

2023-02-28 06:31 UTC, edrevo commented on content/en/continuous_integration/intelligent_test_runner/_index.md
> +`DD_CIVISIBILITY_AGENTLESS_ENABLED=true`
```suggestion
`DD_CIVISIBILITY_AGENTLESS_ENABLED`
```

2023-02-28 06:31 UTC, edrevo commented on content/en/continuous_integration/intelligent_test_runner/_index.md
> +`DD_CIVISIBILITY_AGENTLESS_ENABLED=true`
```suggestion
`DD_CIVISIBILITY_AGENTLESS_ENABLED`
```

2023-02-28 09:53 UTC, albertvaka commented
@drichards-87 this is ready to be merged 😃 Thanks!

2023-02-28 15:27 UTC, merged