Call out tracing library step
DataDog/documentation pull request #17159
Opened 2023-03-03 22:13 UTC by Danny-Driscoll

Adding more specific callout for tracing library installation step

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-03-03 23:37 UTC, apigirl approved these changes

2023-03-22 19:22 UTC, cswatt requested changes

2023-03-22 19:22 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Agent via Dockerfile
```suggestion
#### Install Agent with Dockerfile
```

2023-03-22 19:22 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +Follow [these instructions][2] to install and configure the GO tracing library in your application to capture and submit traces.
```suggestion
Follow [these instructions][2] to install and configure the Go tracing library in your application to capture and submit traces. 
```

2023-03-22 19:22 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Agent via Dockerfile
```suggestion
#### Install Agent with Dockerfile
```

2023-03-22 19:22 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Agent via Dockerfile
```suggestion
#### Install Agent with Dockerfile
```

2023-03-22 19:22 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Agent via Dockerfile
```suggestion
#### Install Agent with Dockerfile
```

2023-03-22 19:22 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Agent via Dockerfile
```suggestion
#### Install Agent with Dockerfile
```

2023-03-22 19:22 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +[2]: tracing/trace_collection/dd_libraries/dotnet-framework/?tab=containers#custom-instrumentation
```suggestion
Follow the instructions to install and configure the [.NET Core tracing library][1] and the [.NET Framework tracing library][2]. 

[1]: /tracing/trace_collection/dd_libraries/dotnet-core?tab=containers#custom-instrumentation
[2]: /tracing/trace_collection/dd_libraries/dotnet-framework/?tab=containers#custom-instrumentation
```

2023-03-22 19:22 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Agent via Dockerfile
```suggestion
#### Install Agent with Dockerfile
```

2023-03-22 19:47 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:47 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:47 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:47 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:47 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:47 UTC, cswatt commented on content/en/serverless/azure_container_apps/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 20:59 UTC, cswatt approved these changes

2023-03-22 20:59 UTC, merged