Cloud Run Tracing library callouts
DataDog/documentation pull request #17164
Opened 2023-03-06 04:25 UTC by Danny-Driscoll

Matching change for Cloud Run to https://github.com/DataDog/documentation/pull/17159

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-03-06 22:41 UTC, rtrieu approved these changes
LGTM

2023-03-22 19:44 UTC, cswatt requested changes

2023-03-22 19:44 UTC, cswatt commented on content/en/serverless/google_cloud_run/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:44 UTC, cswatt commented on content/en/serverless/google_cloud_run/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:44 UTC, cswatt commented on content/en/serverless/google_cloud_run/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:44 UTC, cswatt commented on content/en/serverless/google_cloud_run/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:44 UTC, cswatt commented on content/en/serverless/google_cloud_run/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:44 UTC, cswatt commented on content/en/serverless/google_cloud_run/_index.md
> +#### Install Tracing Library
```suggestion
#### Install tracing library
```

2023-03-22 19:45 UTC, cswatt approved these changes

2023-03-22 20:59 UTC, merged