Add Business Logic Abuse to ASM docs
DataDog/documentation pull request #17244
Opened 2023-03-10 12:57 UTC by maxhedouin

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-03-10 13:15 UTC, maxhedouin commented
Adding the do not merge until the feature is released (should be next week). Reviews are welcomed!

2023-03-14 21:20 UTC, kayayarai requested changes
Some edits for grammar and style. Please make sure I didn't mangle any meaning.

2023-03-14 21:20 UTC, kayayarai commented on content/en/security/application_security/how-appsec-works.md
> +Datadog Application Security Management (ASM) provides observability into application-level attacks that aim to exploit code-level vulnerabilities, abuse the business logic of your application, and i
```suggestion
Datadog Application Security Management (ASM) provides observability into application-level attacks that aim to exploit code-level vulnerabilities or abuse the business logic of your application, and into any bad actors targeting your systems.
```

2023-03-14 21:20 UTC, kayayarai commented on content/en/security/application_security/threats/custom_rules.md
> +ASM offers out of the box rules to detect business logic abuse (Reset password brute forcing for example). Those rules require [adding business logic information to traces][7].
```suggestion
ASM offers out of the box rules to detect business logic abuse (for example, resetting a password through brute force). Those rules require [adding business logic information to traces][7].
```

2023-03-14 21:20 UTC, kayayarai commented on content/en/security/application_security/threats/custom_rules.md
> +You can filter the rules, and identify which business logic to start tracking. Additionally, these rules can be used as a blueprint to create your own rules based on your own business logic.
```suggestion
You can filter the rules, and identify which business logic to start tracking. Additionally, you can use these rules as a blueprint to create custom rules based on your own business logic. 
```

2023-03-14 21:20 UTC, kayayarai commented on content/en/security/application_security/threats/custom_rules.md
> +Optionally, define a unique count and signal grouping. Count the number of unique values observed for an attribute in a given timeframe. The defined group-by generates a signal for each group-by valu
```suggestion
Optionally, define a unique count and signal grouping. Count the number of unique values observed for an attribute in a given timeframe. The defined group-by generates a signal for each group-by value. Typically, the group-by is an entity (like user, IP, or service). The group-by is also used to [join the queries together](#joining-queries).
```

2023-03-23 16:58 UTC, kayayarai approved these changes

2023-04-04 15:56 UTC, merged