Update lib injection with lack of uWSGI support
DataDog/documentation pull request #17409
Opened 2023-03-23 20:04 UTC by Kyle-Verhoog

### What does this PR do?

Update the lib injection docs about uWSGI.

### Motivation

The Python injection mechanism does not currently support uWSGI so we should call it out to avoid confusion.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-03-23 21:51 UTC, rtrieu requested changes
Hey @Kyle-Verhoog , we generally do not advertise what we don't support in our docs. We list what we do support. Is there a different way you can frame this?

2023-03-27 16:08 UTC, elee0625 commented
Hey @rtrieu - we're adding this in explicitly because we've had a few customers ask about uWSGI for the Python tracer, and were hoping to avoid further escalations in the future. Is it okay to make an exception or do you have other recommended wording?

2023-03-27 18:25 UTC, rtrieu requested changes
Hey @elee0625 , let's change it to a note instead and remove "currently" so it doesn't seem like we are promising to support it in the future.

2023-03-27 18:25 UTC, rtrieu commented on content/en/tracing/trace_collection/library_injection.md
> +<div class="alert alert-warning">Python uWSGI applications are currently not supported.</div>
```suggestion
**Note:** Python uWSGI applications are not supported.
```

2023-04-04 16:30 UTC, rtrieu approved these changes
Looks good!

2023-04-04 17:07 UTC, merged