Add documentation for DBM-APM link for java tracer
DataDog/documentation pull request #17425
Opened 2023-03-25 23:29 UTC by jmeunier28

### What does this PR do?

Add documentation for enabling the DBM-APM linking feature for applications that use the java tracer

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-03-27 15:24 UTC, jmeunier28 commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> -#TODO: update postgres configurations
yeah for sure & same here. I just removed it bc I thought it was weird lol, I can add it back

2023-03-28 15:16 UTC, EmmaOnThursday commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +| **Java**     |                            |             |             |
can you link to the tracer and add a version to this line?

2023-03-28 16:07 UTC, jmeunier28 commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +defer rows.Close()
ugh I formatted the file & its messed up now. Fixing

2023-03-28 16:17 UTC, alexandre-normand approved these changes

2023-03-28 16:43 UTC, urseberry requested changes

2023-03-28 16:43 UTC, urseberry commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +Follow the [java tracing][1] instrumentation instructions and install the `1.11.0` version, or greater, of the agent.
```suggestion
Follow the [Java tracing][1] instrumentation instructions and install the `1.11.0` version, or greater, of the Agent.
```

2023-03-28 16:43 UTC, urseberry commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +2. Set the environment variable `DD_DBM_PROPAGATION_MODE=full`
```suggestion
Enable the database monitoring propagation feature using **one** of the following methods:

- Set the system property `dd.dbm.propagation.mode=full`
- Set the environment variable `DD_DBM_PROPAGATION_MODE=full`
```

2023-03-28 16:43 UTC, urseberry commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +# start the java agent with the required system properties
```suggestion
# Start the Java Agent with the required system properties
```

2023-03-28 16:59 UTC, jmeunier28 commented
Thanks @urseberry ! I think i got everything

2023-03-28 17:03 UTC, EmmaOnThursday approved these changes
LGTM for content

2023-03-28 18:45 UTC, urseberry approved these changes

2023-03-28 18:46 UTC, merged