Add Operator to Cluster Checks doc
DataDog/documentation pull request #17473
Opened 2023-03-29 17:16 UTC by fanny-jiang

### What does this PR do?
Update the Cluster Checks doc with the Datadog Operator v1 v2/alpha1 instructions.

### Motivation
Pre-GA

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-03-29 18:33 UTC, hestonhoffman approved these changes
LGTM!

2023-03-29 21:23 UTC, khewonc requested changes

2023-03-29 21:23 UTC, khewonc commented on content/en/containers/cluster_agent/clusterchecks.md
> +With the Datadog Operator, these configuration files can be created within the `spec.override.clusterAgent.extraConfd.configDataMap` section:
Could you add an example for `spec.override.clusterAgent.extraConfd.configMap` as well? There's an example for how the `configMap` section can be used in this PR: https://github.com/DataDog/datadog-operator/pull/616

2023-03-29 21:23 UTC, khewonc commented on content/en/containers/cluster_agent/clusterchecks.md
> +          <INTEGRATION_NAME>.yaml: |-
I think the `<INTEGRATION_NAME>.yaml` could be filled in with `http_check.yaml` for this section and the Helm tab to match the instructions we give in the DaemonSet tab about adding a `http_check.yaml` file to the Cluster Agent

2023-03-29 21:25 UTC, CharlyF approved these changes

2023-03-31 18:35 UTC, khewonc approved these changes

2023-04-03 17:30 UTC, cswatt approved these changes

2023-04-03 21:18 UTC, cswatt approved these changes

2023-04-03 21:18 UTC, merged