Bryce/azure programmatic guide
DataDog/documentation pull request #17496
Opened 2023-03-30 21:28 UTC by buraizu

### What does this PR do?
Creates a guide for Azure programmatic management.

### Motivation
DOCS-4695

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-22 22:27 UTC, rtrieu requested changes
Sorry this review took so long. A few small suggestions, but it otherwise looks like a great update!

2023-05-22 22:27 UTC, rtrieu commented on content/en/integrations/guide/azure-native-programmatic-management.md
> +The Azure Native integration uses the Datadog resource to streamline management and data collection for your Azure environment. Datadog recommends using this method when possible. This is possible th
```suggestion
The Azure Native integration uses the Datadog resource to streamline management and data collection for your Azure environment. Datadog recommends using this method when possible. This method involves creating the [azurerm_datadog_monitor][3] resource and assigning the [Monitoring Reader role][4] in Azure to link your Azure subscription(s) to your Datadog organization. This replaces the App Registration credential process for metric collection and Event Hub setup for log forwarding.
```

2023-05-22 22:27 UTC, rtrieu commented on content/en/integrations/guide/azure-native-programmatic-management.md
> +The Azure Native integration is only supported for users of Datadog's US3 site. If you're using a different [Datadog site][3], see the standard [Azure Programmatic Management guide][1]. If you're usi
```suggestion
The Azure Native integration is only supported for users of Datadog's US3 site. If you're using a different [Datadog site][1], see the standard [Azure Programmatic Management guide][2]. If you're using the Datadog US3 site, [change the site selector][3] on the right of this page.
```

2023-05-22 22:27 UTC, rtrieu commented on content/en/integrations/guide/azure-native-programmatic-management.md
> +[1]: /integrations/guide/azure-programmatic-management/
```suggestion
[1]: /getting_started/site/
```

2023-05-22 22:27 UTC, rtrieu commented on content/en/integrations/guide/azure-native-programmatic-management.md
> +[2]: ?site=us3
```suggestion
[2]: /integrations/guide/azure-programmatic-management/
```

2023-05-22 22:27 UTC, rtrieu commented on content/en/integrations/guide/azure-native-programmatic-management.md
> +[3]: /getting_started/site/
```suggestion
[3]: ?site=us3
```

2023-05-22 22:27 UTC, rtrieu commented on content/en/integrations/guide/azure-native-programmatic-management.md
> +The Azure Native integration is only supported for users of Datadog's US3 site. If you're using a different [Datadog site][3], see the standard [Azure Programmatic Management guide][1]. If you're usi
I don't think this impacts the functionality of the links, but figured it wouldn't hurt to make them consecutive :)

2023-05-22 22:27 UTC, rtrieu commented on content/en/integrations/guide/azure-programmatic-management.md
> +All sites: Users of all [Datadog Sites][3] can use the app registration credential process to implement the standard Azure integration with Datadog.
```suggestion
**All sites**: Users of all [Datadog Sites][3] can use the app registration credential process to implement the standard Azure integration with Datadog.
```

2023-05-22 22:27 UTC, rtrieu commented on content/en/integrations/guide/azure-programmatic-management.md
> +US3: If your org is on the Datadog US3 site, you can use the Azure Native integration to streamline management and data collection for your Azure environment. Datadog recommends using this method whe
```suggestion
**US3**: If your org is on the Datadog US3 site, you can use the Azure Native integration to streamline management and data collection for your Azure environment. Datadog recommends using this method when possible. Setup entails creating a [Datadog resource in Azure][14] to link your Azure subscriptions to your Datadog organization. This replaces the app registration credential process for metric collection and Event Hub setup for log forwarding.
```

2023-05-25 00:16 UTC, buraizu commented
@rtrieu thank you for the review, I've applied your suggestions.

2023-06-30 18:43 UTC, buraizu commented
Received approval from Azure team via Slack.

2023-06-30 18:43 UTC, merged