Update endpoint URL in OTLP-DD ingestion doc
DataDog/documentation pull request #17492
Opened 2023-03-30 19:51 UTC by rupalivohra

Haven't tested it, but I'm guessing this is a typo.

### What does this PR do?

Updates the grpc endpoint example in the docs.

### Motivation

I think it's a typo.

n/a - not a DD employee.

### Additional Notes

I haven't tested this out yet.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-03-30 21:14 UTC, drichards-87 commented
Thanks for submitting this PR! I've created DOCS-5168 for the review.

2023-04-04 20:13 UTC, kayayarai commented
@gbbr Hi Gabriel, can you verify whether this suggested change around the grpc URL is correct, or whether the fact that it's pointing at 4317 is what indicates it's grpc not http?

2023-06-06 07:46 UTC, gbbr requested changes
I'd suggest we don't make this change.

2023-06-06 07:46 UTC, gbbr commented on content/en/opentelemetry/otlp_ingest_in_the_agent.md
> +      value: "grpc://$(HOST_IP):4317" # sends to gRPC receiver on port 4317
Our documentation is correct. gRPC is HTTP. The URL doesn't need to change. Why do you think this change is necessary? Please take a look at https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options. There is an example there.

2023-06-06 17:34 UTC, closed without merging