Node.js: add instruction for bundlers/esbuild
DataDog/documentation pull request #17515
Opened 2023-03-31 20:20 UTC by tlhunter

### What does this PR do?
- adds a section to a Node.js page with instructions regarding bundling

### Motivation
- this is a new feature that users will likely have questions about using

### Additional Notes
- these docs are copied from the dd-trace-js README
- probably shouldn't land until dd-trace-js cuts a new release
- should the documentation mention the library version number that introduces the feature?

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-03-31 20:23 UTC, Qard approved these changes

2023-05-31 19:09 UTC, estherk15 requested changes
Let me know if you have any questions on my comments!

2023-06-05 13:40 UTC, estherk15 commented on content/en/tracing/trace_collection/dd_libraries/nodejs.md
> +Datadog recommends you have custom-built bundler plugins. These plugins are able to instruct the bundler on how to behave, inject intermediary code and intercept the "translated" `require() calls. As
```suggestion
Datadog recommends you have custom-built bundler plugins. These plugins are able to instruct the bundler on how to behave, inject intermediary code and intercept the "translated" `require()` calls. As a result, more packages are included in the bundled JavaScript file. 
```

2023-06-05 13:41 UTC, estherk15 commented on content/en/tracing/trace_collection/dd_libraries/nodejs.md
> +**Note**: Some applications can have 100% of modules bundled, however native modules still need to remain external to the bundle.`
```suggestion
**Note**: Some applications can have 100% of modules bundled, however native modules still need to remain external to the bundle.
```

2023-06-05 18:58 UTC, estherk15 approved these changes

2023-06-05 19:28 UTC, merged