DOCS-4883 Updates Error Tracking Screenshots
DataDog/documentation pull request #17544
Opened 2023-04-03 21:36 UTC by alai97

### What does this PR do?

Add a screenshot of the new product level header for Error Tracking in RUM, adds image width for images in Error Tracking for Backend Services.

### Motivation

DOCS-4883

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-04-04 19:37 UTC, cswatt requested changes
just some grammar nits, otherwise looks good!

2023-04-04 19:37 UTC, cswatt commented on content/en/real_user_monitoring/error_tracking/_index.md
> +{{< img src="real_user_monitoring/error_tracking/rum_error_tracking.png" alt="The Error Tracking Explorer for RUM displaying issues from your web and mobile application's crash reports" style="width:
```suggestion
{{< img src="real_user_monitoring/error_tracking/rum_error_tracking.png" alt="The Error Tracking Explorer for RUM displaying issues from your web and mobile applications' crash reports" style="width:100%;" >}}
```

2023-04-04 19:37 UTC, cswatt commented on content/en/real_user_monitoring/error_tracking/explorer.md
> +{{< img src="real_user_monitoring/error_tracking/page.png" alt="The Error Tracking Explorer for RUM displaying issues from your web and mobile application's crash reports" style="width:100%;" >}}
```suggestion
{{< img src="real_user_monitoring/error_tracking/page.png" alt="The Error Tracking Explorer for RUM displaying issues from your web and mobile applications' crash reports" style="width:100%;" >}}
```

2023-04-04 19:37 UTC, cswatt commented on content/en/tracing/error_tracking/explorer.md
> +The Error Tracking Explorer shows you a list of ongoing issues. An _issue_ is a group of similar errors that have the same _fingerprint_ and which might need to be fixed depending on how critical it
```suggestion
The Error Tracking Explorer shows you a list of ongoing issues. An _issue_ is a group of similar errors that have the same _fingerprint_ and which might need to be fixed depending on how critical they are. 
```

2023-04-04 19:37 UTC, cswatt commented on content/en/real_user_monitoring/error_tracking/_index.md
> +Once you have set up RUM for **Web and Mobile Apps** error tracking, the issue list populates with cards. You can view open, ignored, or all issues, sort issues by volume or age, and filter issues by
```suggestion
Once you have set up RUM for **Web and Mobile Apps** error tracking, the issue list populates with cards. You can view open, ignored, or all issues; sort issues by volume or age; and filter issues by all custom and default facets on your web and mobile applications.
```

2023-04-04 21:08 UTC, cswatt approved these changes

2023-04-07 21:18 UTC, alai97 commented on content/en/tracing/error_tracking/explorer.md
> +[3]: https://app.datadoghq.com/rum/error-tracking
```suggestion
[3]: https://app.datadoghq.com/apm/error-tracking
```

2023-04-07 21:18 UTC, alai97 commented on content/en/tracing/error_tracking/explorer.md
> +Each item listed in the Error Tracking Explorer surfaces high-level information about the issue, including the following:
```suggestion
Each item listed in the [Error Tracking Explorer][3] surfaces high-level information about the issue, including the following:
```

2023-04-25 20:02 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/_index.md
Should we mention somewhere here how to navigate to the Error Tracking page from UX Monitoring or elsewhere?

2023-04-25 20:32 UTC, rtrieu requested changes
This looks good, except the new image doesn't appear (I'm still seeing the old cached one). Any chance this is because the filename wasn't changed to something like `rum_error_tracking_1.png`?

2023-04-25 22:23 UTC, rtrieu requested changes
One last thing..

2023-04-25 22:23 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/_index.md
> +{{< img src="real_user_monitoring/error_tracking/rum_error_tracking.png" alt="The Error Tracking Explorer for RUM displaying issues from your web and mobile applications' crash reports" style="width:
```suggestion
{{< img src="real_user_monitoring/error_tracking/rum_error_tracking_1.png" alt="The Error Tracking Explorer for RUM displaying issues from your web and mobile applications' crash reports" style="width:100%;" >}}
```

2023-04-26 16:15 UTC, rtrieu approved these changes
Great!

2023-05-05 18:28 UTC, nhientrandatadog approved these changes

2023-06-14 22:19 UTC, merged