small tweaks to get docs ready for an open beta
DataDog/documentation pull request #17542
Opened 2023-04-03 21:06 UTC by EmmaOnThursday

### What does this PR do?
- remove note about asking CSM about feature
- make "Node.js" consistent across whole page
- move Node.js tab to end to match table
- update node tab to reference correct tracer version (3.13 not 3.9)

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-04-03 22:09 UTC, estherk15 requested changes

2023-04-03 22:09 UTC, estherk15 commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +This features requires automatic instrumentation to be enabled for your .NET service.
```suggestion
This feature requires automatic instrumentation to be enabled for your .NET service.
```

2023-04-03 22:09 UTC, estherk15 commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +Ensure that you are using a supported client library (e.g. `Npgsql`).
```suggestion
Ensure that you are using a supported client library. For example, `Npgsql`.
```

2023-04-03 22:09 UTC, estherk15 commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +This features requires the tracer extension to be enabled for your PHP service.
```suggestion
This feature requires the tracer extension to be enabled for your PHP service.
```

2023-04-03 22:09 UTC, estherk15 commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +Install or udpate [dd-trace-js][1] to version greater than `3.13.0` (or `2.22.0` if using end-of-life Node.js version 12):
```suggestion
Install or update [dd-trace-js][1] to a version greater than `3.13.0` (or `2.22.0` if using end-of-life Node.js version 12):
```

2023-04-03 22:11 UTC, EmmaOnThursday commented
@estherk15 I noticed this page is listed as `private`, but we've already added it to the docs sidebar under Guides. What does that mean in practice?

2023-04-04 03:43 UTC, estherk15 commented
@EmmaOnThursday It means it's not searchable. If you DON'T want this visible in the public docs we can remove it from sidebar. Or if you DO want this visible, you can remove the `private:true` from the frontmatter. Let me know if you have any questions on this!

2023-04-04 03:43 UTC, estherk15 approved these changes

2023-04-04 16:33 UTC, alexandre-normand approved these changes

2023-04-06 16:40 UTC, EmmaOnThursday commented
@estherk15 if you are happy with these changes can you merge this?

2023-04-06 19:00 UTC, merged