Rework SDKs intake domains section
DataDog/documentation pull request #17672
Opened 2023-04-12 08:20 UTC by bcaudan

### What does this PR do?

- Split RUM domains section into mobile and browse SDKs domains
- add `US1-FED` missing domains

### Motivation

Difference identified between mobile and browser SDKs

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-04-12 10:55 UTC, plousada approved these changes

2023-04-12 12:38 UTC, amortemousque approved these changes

2023-04-12 17:35 UTC, xgouchet approved these changes

2023-04-12 19:11 UTC, rtrieu commented on content/en/getting_started/site/_index.md
> +## SDKs domains
```suggestion
## SDK domains
```

2023-04-12 19:11 UTC, rtrieu requested changes
Minor feedback, but otherwise looks good.

2023-04-13 16:14 UTC, rtrieu approved these changes
Looks good!

2023-04-14 15:01 UTC, merged