Add manual api documention
DataDog/documentation pull request #17694
Opened 2023-04-13 13:39 UTC by tonyredondo

### What does this PR do?

This PR adds the CI Visibility Manual Api documentation for .NET

### Motivation

The feature was released but the documentation is missing.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-04-13 14:49 UTC, albertvaka approved these changes
Reworded some sentences but overall LGTM.

2023-04-13 14:49 UTC, albertvaka commented on content/en/continuous_integration/tests/dotnet.md
> +### Test Suites
```suggestion
### Test suites
```

2023-04-13 17:36 UTC, hestonhoffman commented
👋 I've added a [docs card](https://datadoghq.atlassian.net/browse/DOCS-5279) for this one

2023-04-13 21:31 UTC, drichards-87 requested changes

2023-04-13 21:31 UTC, drichards-87 commented on content/en/continuous_integration/tests/dotnet.md
> +The API is based around three concepts: *test module*, *test suites*, and *tests*.
```suggestion
The API is based around three concepts: test module, test suites, and tests.
```

2023-04-14 14:34 UTC, drichards-87 approved these changes
@tonyredondo PR is approved. Should I merge it now?

2023-04-14 15:06 UTC, tonyredondo commented
> @tonyredondo PR is approved. Should I merge it now?

Yes please! Thank you!

2023-04-14 15:21 UTC, merged