RUMM-3201 Add Roku documentation
DataDog/documentation pull request #17729
Opened 2023-04-17 13:28 UTC by xgouchet

### What does this PR do?

Add the documentation for the RUM Roku sdk.

### Motivation

Document our new product. 

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-04-17 21:49 UTC, cswatt requested changes

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/_index.md
> +The Datadog Roku SDK supports Brightscript channels for Roku OS 10 and higher.
```suggestion
The Datadog Roku SDK supports BrightScript channels for Roku OS 10 and higher.
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/_index.md
> +2. Specify application details in the UI.
```suggestion
2. Specify application details in Datadog.
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/_index.md
> +Make sure you have a `roku_modules/datadogroku` subfolder in both the `components` and ` source` folders of your projet.
```suggestion
Make sure you have a `roku_modules/datadogroku` subfolder in both the `components` and ` source` folders of your project.
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/_index.md
> +### Specify application details in the UI
```suggestion
### Specify application details in Datadog
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/_index.md
> +2. Select `Roku` as the application type and enter an application name to generate a unique Datadog application ID and client token.
```suggestion
2. Select **Roku** as the application type and enter an application name to generate a unique Datadog application ID and client token.
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/_index.md
> +To ensure the safety of your data, you must use a client token. If you used only [Datadog API keys][3] to configure the `dd-sdk-roku` library, they would be exposed client-side in the Roku Channel's
```suggestion
To ensure the safety of your data, you must use a client token. If you used only [Datadog API keys][3] to configure the `dd-sdk-roku` library, they would be exposed client-side in the Roku channel's BrightScript code. 
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/_index.md
> +See [`Track RUM Resources`][6] to enable automatic tracking of all your views (activities, fragments, and more), and [`Enrich user sessions`][7] to add custom global or user information to your event
```suggestion
See [**Track RUM Resources**][6] to enable automatic tracking of all your views (activities, fragments, and more), and [**Enrich user sessions**][7] to add custom global or user information to your events.
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/_index.md
> +#### Track RUM Errors
```suggestion
#### Track RUM errors
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/advanced_configuration.md
> +which supports most features of the `roUrlTransfer` component (except anything related to async network calls).
```suggestion
For *synchronous requests*, you can use Datadog's `datadogroku_DdUrlTransfer` wrapper to track the resource automatically. This wrapper supports most features of the `roUrlTransfer` component, but does not support anything related to async network calls.
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/advanced_configuration.md
> +For **asynchronous request**, there's no automatic instrumentation yet, meaning you need to track the resource manually. The following code snippet shows how to report the request as a RUM Resource:
```suggestion
For *asynchronous requests*, automatic instrumentation is not supported. You need to track the resource manually. The following code snippet shows how to report the request as a RUM Resource:
```

2023-04-17 21:49 UTC, cswatt commented on content/en/real_user_monitoring/roku/advanced_configuration.md
> +In addition to the default RUM attributes captured by the RUM Roku SDK automatically, you can choose to add additional contextual information, such as custom attributes, to your RUM events to enrich
```suggestion
In addition to the default RUM attributes captured by the RUM Roku SDK automatically, you can choose to add additional contextual information, such as custom attributes, to your RUM events to enrich your observability within Datadog. Custom attributes allow you to filter and group information about observed user behavior (such as cart value, merchant tier, or ad campaign) with code-level information (such as backend services, session timeline, error logs, or network health).
```

2023-04-19 21:20 UTC, rtrieu requested changes
Hi @xgouchet, as it is, the links are not working on the page because site-regions can't be nested inside of site-regions, so I've added the {{< site-region region="us,us3,us5,eu,ap1" >}} and {{< /site-region}} where appropriate. Can you double check that you've added all the necessary links and the links are correct?

Otherwise, the page looks great. Thanks for adding it!

2023-04-19 21:20 UTC, rtrieu commented on content/en/real_user_monitoring/roku/_index.md
> +[14]: /getting_started/tagging/using_tags/#rum--session-replay
```suggestion
[8]: /getting_started/tagging/using_tags/#rum--session-replay
```

2023-04-19 21:20 UTC, rtrieu commented on content/en/real_user_monitoring/roku/_index.md
> +Make sure you have a `roku_modules/datadogroku` subfolder in both the `components` and ` source` folders of your project.
```suggestion
Make sure you have a `roku_modules/datadogroku` subfolder in both the `components` and `source` folders of your project.
```

2023-04-19 21:20 UTC, rtrieu commented on content/en/real_user_monitoring/roku/_index.md
> +[5]: https://docs.datadoghq.com/real_user_monitoring/
```suggestion
[5]: /real_user_monitoring/
```

2023-04-19 21:20 UTC, rtrieu commented on content/en/real_user_monitoring/roku/_index.md
> +[15]: /real_user_monitoring/android/data_collected/
```suggestion
[9]: /real_user_monitoring/android/data_collected/
```

2023-04-19 21:20 UTC, rtrieu commented on content/en/real_user_monitoring/roku/_index.md
> +[15]: /real_user_monitoring/android/data_collected/
Also, I counted 10 links - I think one is unlinked.

2023-04-19 21:20 UTC, rtrieu commented on content/en/real_user_monitoring/roku/_index.md
> +
{{< site-region region="us,us3,us5,eu,ap1" >}}

2023-04-19 21:20 UTC, rtrieu commented on content/en/real_user_monitoring/roku/_index.md
> +
{{< /site-region >}}

2023-04-19 21:20 UTC, rtrieu commented on content/en/real_user_monitoring/roku/_index.md
> +
{{< /site-region >}}

{{< site-region region="us,us3,us5,eu,ap1" >}}

2023-04-20 08:53 UTC, xgouchet commented on content/en/real_user_monitoring/roku/_index.md
> +
```suggestion
{{< /site-region >}}

{{< site-region region="us,us3,us5,eu,ap1" >}}
```

2023-04-20 08:53 UTC, xgouchet commented on content/en/real_user_monitoring/roku/_index.md
> +
```suggestion
{{< /site-region >}}
```

2023-04-20 08:53 UTC, xgouchet commented on content/en/real_user_monitoring/roku/_index.md
> +
```suggestion
{{< site-region region="us,us3,us5,eu,ap1" >}}
```

2023-04-20 08:54 UTC, xgouchet commented on content/en/real_user_monitoring/roku/_index.md
> +3. To disable automatic user data collection for either client IP or geolocation data, uncheck the boxes for those settings. For more information, see [RUM Roku Data Collected][15].
```suggestion
3. To disable automatic user data collection for either client IP or geolocation data, uncheck the boxes for those settings. For more information, see [RUM Roku Data Collected][9].
```

2023-04-20 08:55 UTC, xgouchet commented on content/en/real_user_monitoring/roku/_index.md
> +In the initialization snippet, set an environment name. For more information, see [Using Tags][14].
```suggestion
In the initialization snippet, set an environment name. For more information, see [Using Tags][8].
```

2023-04-20 18:57 UTC, rtrieu approved these changes
This looks great, thanks! @xgouchet is it ready to merge?

2023-04-21 14:15 UTC, timmld requested changes
Thanks @xgouchet for putting this together! There are some things I didn't look at yet, I'll just do another pass later in the day when I find the time

2023-04-21 14:15 UTC, timmld commented on content/en/real_user_monitoring/roku/data_collected.md
> +RUM collects common attributes for all events and attributes specific to each event listed below automatically. You can also choose to enrich your user session data by tracking [additional events][2]
Don't know if this is expected at this point, but the links (not only these, but most of the others) are not showing properly in the preview

2023-04-21 14:15 UTC, timmld commented on content/en/real_user_monitoring/roku/_index.md
> +```brightscript
Do we have syntax highlighting for brightscript snippets or not? Looks like not when looking at the preview.

2023-04-24 09:53 UTC, timmld approved these changes

2023-04-24 21:38 UTC, merged