React Native docs improvements
DataDog/documentation pull request #17815
Opened 2023-04-21 09:30 UTC by louiszawadzki

### What does this PR do?

Add a few improvements to the RN docs before un-single sourcing.
Also ports the following PRs that were not merged:
- https://github.com/DataDog/dd-sdk-reactnative/pull/456/commits
- https://github.com/DataDog/dd-sdk-reactnative/pull/458

### Motivation

### Additional Notes

### Reviewer checklist
- [x] Review the changed files.
- [x] Review the URLs listed in the [Preview](#preview) section.
- [x] Check images for PII
- [x] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-04-25 16:10 UTC, rtrieu requested changes
A few minor suggestions, but otherwise looks good!

2023-04-25 16:10 UTC, rtrieu commented on content/en/real_user_monitoring/reactnative/_index.md
> +If you experience any issue setting up View tracking with `@datadog/mobile-react-navigation` you can check out our [example application][16].
```suggestion
If you experience any issues setting up View tracking with `@datadog/mobile-react-navigation` you can see our [example application][16] as a reference.
```

2023-04-25 16:10 UTC, rtrieu commented on content/en/real_user_monitoring/reactnative/codepush.md
> +If you experience any issue setting up the Datadog SDK with codepush you can check out our [example application][6].
```suggestion
If you experience any issues setting up the Datadog SDK with codepush, you can see our [example application][6] as a reference.
```

2023-04-25 16:10 UTC, rtrieu commented on content/en/real_user_monitoring/reactnative/expo.md
> +If you experience any issue setting up the datadog SDK with an expo application you can check out our [example application][8].
```suggestion
If you experience any issues setting up the Datadog SDK with an Expo application, you can see our [example application][8] as a reference.
```

2023-05-09 18:23 UTC, rtrieu requested changes
A few very minor suggestions, but otherwise looks good!

2023-05-09 18:23 UTC, rtrieu commented on content/en/real_user_monitoring/reactnative/_index.md
>  **Note:** This solution comes from this [StackOverflow][14] post.
```suggestion
**Note**: This solution comes from this [StackOverflow][14] post.
```

2023-05-09 18:23 UTC, rtrieu commented on content/en/real_user_monitoring/reactnative/advanced_configuration.md
> +If you experience any issue setting up the asynchronous initialization of Datadog you can check out our [example application][7].
```suggestion
If you experience any issue setting up the asynchronous initialization of Datadog, you can check out our [example application][7].
```

2023-05-11 16:03 UTC, rtrieu approved these changes
Looks good, thanks!

2023-05-11 16:05 UTC, louiszawadzki commented
I don't have the rights to merge, I'll let you do it :)

2023-05-15 08:59 UTC, xgouchet approved these changes

2023-05-24 17:38 UTC, merged