New guide Compatible semantic tags
DataDog/documentation pull request #17868
Opened 2023-04-25 18:16 UTC by estherk15

### What does this PR do?

Add new guide to list compatible semantic tags

### Motivation

https://datadoghq.atlassian.net/browse/DOCS-5202

### Additional Notes

Ready to merge after review

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-04-25 19:26 UTC, drichards-87 commented
Created DOCS-5373 for the editorial review.

2023-04-28 19:51 UTC, kayayarai requested changes

2023-04-28 19:51 UTC, kayayarai commented on content/en/dashboards/guide/compatible_semantic_tags.md
> +For example, an error status code is mapped to red or success is green.
```suggestion
For example, an error status code is mapped to red, and success to green.
```

2023-04-28 19:51 UTC, kayayarai commented on content/en/dashboards/guide/compatible_semantic_tags.md
> +**Note**: Queries must be grouped with a single set of tags.
```suggestion
**Note**: To use the Semantic color palette, a query must be grouped with a single set of tags.
```

2023-04-28 19:51 UTC, kayayarai commented on content/en/dashboards/guide/compatible_semantic_tags.md
> +Queries with a single set of tags are supported. If multiple groupers are used with the semantic palette, coloring will be consistent, but not meaning-driven.
```suggestion
Queries grouped with a single set of tags are supported. If multiple groupers are used with the semantic palette, coloring is consistent, but not meaning-driven.
```

2023-05-03 15:35 UTC, kayayarai approved these changes

2023-05-03 16:45 UTC, merged