Update Test Suite Level Visibility support version for Java
DataDog/documentation pull request #17929
Opened 2023-04-28 10:30 UTC by nikita-tkachenko-datadog

### What does this PR do?

Updates CI Visibility Tests product docs. 
Compatibility section for Test Suite Level Visibility feature now mentions the version of DD Java tracer in which support for the feature was added.
Also, a definition of Test Module is given for Java tracer.

### Motivation

A new version of DD Java Tracer was released, that supports Test Suite Level Visibility Feature

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-04-28 14:37 UTC, drichards-87 requested changes
Left you one minor piece of feedback. Also, let me know if this ready to merge after you update the PR. Thanks!

2023-04-28 14:37 UTC, drichards-87 commented on content/en/continuous_integration/tests/_index.md
> +* In Java a test module groups every test that is run by the same Maven Surefire/Failsafe or Gradle Test task execution
```suggestion
* In Java a test module groups every test that is run by the same Maven Surefire/Failsafe or Gradle Test task execution.
```

2023-05-03 09:17 UTC, nikita-tkachenko-datadog commented
> Left you one minor piece of feedback. Also, let me know if this ready to merge after you update the PR. Thanks!

Thank you for the review! The changes are ready for merge from my perspective.

2023-05-03 15:27 UTC, drichards-87 commented
@nikita-tkachenko-datadog Sounds good. It looks like we have a merge conflict in the PR. Would you be able to take a look at it? I can also take a look as well, but it might make more sense for you to do so since you have more context than I do.

2023-05-03 15:33 UTC, nikita-tkachenko-datadog commented
> @nikita-tkachenko-datadog Sounds good. It looks like we have a merge conflict in the PR. Would you be able to take a look at it? I can also take a look as well, but it might make more sense for you to do so since you have more context than I do.

Done, conflict resolved

2023-05-04 14:12 UTC, drichards-87 approved these changes

2023-05-04 14:12 UTC, merged