adds DevCycle docs to RUM feature tracking
DataDog/documentation pull request #17953
Opened 2023-04-30 17:14 UTC by nikolasleblanc

### What does this PR do?

Adds DevCycle specific documentation to the RUM Feature Flag tracking documentation, explaining how to send flag evaluation data to RUM when using DevCycle.

### Motivation

I saw that DataDog had a Feature Flag tracking system in Beta and as an employee of DevCycle (and client of DataDog's), I wanted to demonstrate how to send DevCycle variable evaluations to DataDog.

### Additional Notes

Some of my prettier/eslint autoformatting was applied to the partials file. Happy to remove that if it's problematic.

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-01 14:23 UTC, maycmlee commented
Thanks @nikolasleblanc for opening this PR! We will review it and be back in touch.

2023-05-01 15:40 UTC, nikolasleblanc commented
Thank you @maycmlee!

2023-05-03 20:44 UTC, VicV commented
Hey @maycmlee ! 

Don't want to be a bother, but we've had our own clients come to us asking when we're going to be supported. 

We already have our own docs up: https://docs.devcycle.com/tools-and-integrations/

But our clients don't realize that we support this at DevCycle already because their entrypoint to knowing about this new RUM FF tracking is through the DD side.

2023-05-04 17:25 UTC, maycmlee commented
Hi @VicV, thanks for the additional context! We'll get this reviewed soon!

2023-05-10 07:29 UTC, bcaudan approved these changes

2023-05-10 13:20 UTC, nikolasleblanc commented
@maycmlee and @bcaudan thanks for the approval. I'm assuming I still need a few of the codeowner approvals before this can go in but keep me posted and I'll get this up to date.

2023-05-10 18:17 UTC, rtrieu requested changes
Hi @nikolasleblanc, thanks so much for creating this PR! I just made a couple of suggestions based on our own style guide, but otherwise, it looks good and has been approved by our eng team. Once you make the changes, I will approve and merge it. Thanks again!

2023-05-10 18:17 UTC, rtrieu commented on content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> +DevCycle does not currently support this integration. Create a ticket with DevCycle to request this feature.
```suggestion
DevCycle does not support this integration. Create a ticket with DevCycle to request this feature.
```

2023-05-10 18:17 UTC, rtrieu commented on content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> +DevCycle does not currently support this integration. Create a ticket with DevCycle to request this feature.
```suggestion
DevCycle does not support this integration. Create a ticket with DevCycle to request this feature.
```

2023-05-16 16:08 UTC, rtrieu commented
Hi @nikolasleblanc, I have a request for you. Would you mind creating an integration tile for this? [Here is some documentation](https://docs.datadoghq.com/developers/integrations/api_integration/) on what that is and how to get started. Please **ignore the details** around **Oauth** and **API endpoints**, since the integration does not need them.

[Here is the Github link to the code](https://github.com/DataDog/integrations-extras) where you will add the tile to (and you can create a new folder for the tile).

2023-05-16 19:00 UTC, nikolasleblanc commented
Hey @rtrieu I've submitted a PR to the integrations-extra repo: https://github.com/DataDog/integrations-extras/pull/1849

2023-05-17 16:09 UTC, rtrieu commented
@nikolasleblanc Thank you so much! Approving and merging this.

2023-05-17 16:10 UTC, rtrieu approved these changes
Looks good!

2023-05-17 19:52 UTC, rtrieu commented
Hi @nikolasleblanc thank you so much for the quick turnaround on that!

2023-05-17 19:52 UTC, merged