Update configuration.md with ASM steps
DataDog/documentation pull request #18082
Opened 2023-05-10 17:55 UTC by sourabhkatti

Add ASM in the serverless configuration

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-10 19:23 UTC, buraizu requested changes
Thanks for the PR, just flagging a few link issues and also made some suggestions per our [style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md).

2023-05-10 19:23 UTC, buraizu commented on content/en/serverless/installation/dotnet.md
> +- Turn on [threat monitoring][6] to get alerted on attackers targeting your service.
Suggesting to move all the `What's next` section additions to somewhere after the `You can now...` or `Congratulations! You can now...` lines, as the implication is that this step is needed to view metrics, logs, and traces. Please let me know if I'm misunderstanding anything in this regard.

2023-05-10 19:23 UTC, buraizu commented on content/en/serverless/aws_lambda/configuration.md
> +[40]: /serverless/installation#installation-instructions
```suggestion
[40]: /serverless/installation#installation-instructions
[41]: https://app.datadoghq.com/security/appsec?column=time&order=desc
```

2023-05-10 19:23 UTC, buraizu commented on content/en/serverless/aws_lambda/configuration.md
> +To see Application Security Management threat detection in action, send known attack patterns to your application. For example, send an HTTP header with value `acunetix-product` to trigger a [securit
This link is currently opening a blog post, which seems to match the other `[5]` reference link on line `223`. Is there a new link to go with `security scanner attack`?

2023-05-10 19:23 UTC, buraizu commented on content/en/serverless/aws_lambda/configuration.md
> +   curl -H 'My-ASM-Test-Header: acunetix-product' https://your-function-url/existing-route
```suggestion
   curl -H 'My-ASM-Test-Header: acunetix-product' https://<YOUR_FUNCTION_URL>/<EXISTING_ROUTE>
```

2023-06-01 17:43 UTC, buraizu commented
@sourabhkatti just reaching out to follow up on this PR -- I'm happy to take care of the remaining updates myself with your approval, but just want to confirm if this is the intended link for the `security scanner attack` text on line `119` of the  AWS Lambda configuration doc referenced in this [comment](https://github.com/DataDog/documentation/pull/18082#discussion_r1190299197):
https://docs.datadoghq.com/security/default_rules/security-scan-detected/

2023-06-06 16:58 UTC, sourabhkatti commented
Hey Bryce, yes that's the correct link for this case. It refers the user to the https://docs.datadoghq.com/security/default_rules/security-scan-detected/ page to learn more about what this type of risk is.

2023-06-06 16:58 UTC, sourabhkatti commented
Thanks for the help with bringing the PR up to the style guide also

2023-06-08 19:18 UTC, buraizu approved these changes
Thanks for your patience, LGTM

2023-06-08 21:24 UTC, buraizu commented
@sourabhkatti thanks for confirming, I've updated the link and approved the PR. Just to confirm, is this PR ready to merge?

2023-06-20 18:05 UTC, merged