Stefon.simmons/fix site gettingstarted pgs
DataDog/documentation pull request #18185
Opened 2023-05-18 15:17 UTC by StefonSimmons

### What does this PR do?

updates site-region shortcode syntax on en `/network_monitoring` and `/getting_started` pages.

### Motivation

As a part of this card: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3279

### Preview

Check that the TOC items are showing for the preview links below
Check that the hyperlinks on the modified files take you to the appropriate place:
 https://docs-staging.datadoghq.com/stefon.simmons/fix-site-networkmonitoring-pgs/

Specifically, notice that the `Access the Datadog for Government site` TOC items appears on this page now: https://docs-staging.datadoghq.com/stefon.simmons/fix-site-networkmonitoring-pgs/getting_started/site/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-18 15:53 UTC, aaxzheng approved these changes
Non-blocker for merge but when you have the region set to something that isn't US1-FED and have a section outlined, when you swap to US1-FED, both the current section and the reach government section appear active on the ToC.

![image](https://github.com/DataDog/documentation/assets/40276721/35cb937d-3ab8-4d9a-8593-8662f16ff708)

2023-05-18 17:07 UTC, urseberry commented
Something got messed up with the link at the bottom of the Site page: 
![image](https://github.com/DataDog/documentation/assets/58821586/0311436b-064b-4516-ba3c-9cfd34a5a91d)

2023-05-18 19:39 UTC, urseberry requested changes

2023-05-18 19:39 UTC, urseberry commented on content/en/getting_started/site/_index.md
> +The Datadog for Government site (US1-FED) is meant to allow US government agencies and partners to monitor their applications and infrastructure. For information about the Datadog for Government site
```suggestion
The Datadog for Government site (US1-FED) is meant to allow US government agencies and partners to monitor their applications and infrastructure. For information about the Datadog for Government site's security and compliance controls and frameworks, as well as how it supports FedRAMP, see the [Security page](https://www.datadoghq.com/security/).
```

2023-05-19 14:22 UTC, StefonSimmons commented on content/en/getting_started/site/_index.md
> +The Datadog for Government site (US1-FED) is meant to allow US government agencies and partners to monitor their applications and infrastructure. For information about the Datadog for Government site
@urseberry this is fixed. thanks!

2023-05-19 16:08 UTC, urseberry approved these changes

2023-05-19 16:09 UTC, merged