Add details of geomap points feature
DataDog/documentation pull request #18186
Opened 2023-05-18 15:18 UTC by estherk15

### What does this PR do?

- Add details of the new Geomap point layer
- Replace images
- Reformat some of the information for better user experience

### Motivation

[DOCS-5450](https://datadoghq.atlassian.net/browse/DOCS-5450)

### Additional Notes
Do not merge, pending PM review
---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-18 19:43 UTC, urseberry commented
Editorial review on https://datadoghq.atlassian.net/browse/DOCS-5514

2023-05-19 15:50 UTC, kayayarai requested changes
A few edits, looks like a great update!

2023-05-19 15:50 UTC, kayayarai commented on content/en/dashboards/widgets/geomap.md
> +  **Note**: Support for data sources vary based on the visualization layer you select.
```suggestion
  **Note**: Support for data sources varies based on the visualization layer you select.
```

2023-05-19 15:50 UTC, kayayarai commented on content/en/dashboards/widgets/geomap.md
> +  |Metric   | The group by tag must include a country ISO Code following the alpha-2 ISO format. You can [generate metrics from ingested logs][4], or manually include the [tags on ingest][2]. See the
```suggestion
  |Metric   | The group by tag must include a country ISO Code following the alpha-2 ISO format. You can [generate metrics from ingested logs][4], or manually include the [tags on ingest][2]. See the [querying documentation][5] to configure a metric query.|
```

2023-05-19 15:50 UTC, kayayarai commented on content/en/dashboards/widgets/geomap.md
> +3. Optional: configure your view box depending on where you'd like to zoom into on the map by default.
```suggestion
3. Optional: Configure your view box to specify where you want to focus the map initially.
```
Something like that?

2023-05-19 15:50 UTC, kayayarai commented on content/en/dashboards/widgets/geomap.md
> +[Context links][7] are enabled by default, and can be toggled on or off. Context links bridge dashboard widgets with other pages (in Datadog, or third-party).
```suggestion
[Context links][7] are enabled by default, you can toggle them on or off. Context links connect dashboard widgets with other pages (in Datadog, or third-party).
```

2023-05-31 20:08 UTC, merged