DOCS-5472: DBM AlwaysOn view
DataDog/documentation pull request #18191
Opened 2023-05-18 18:52 UTC by drichards-87

### What does this PR do?
Adds a new guide for the DBM SQL Server AlwaysOn Clusters view.

### Motivation
DOCS-5472

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-08 22:36 UTC, caseycull requested changes

2023-06-08 22:36 UTC, caseycull commented on content/en/database_monitoring/guide/sql_alwayson.md
> +View additional information about each secondary node on the **Secondary Nodes** tab. You can also use the timeseries graphs on the **Metrics** tab to spot abnormal behavior in individual nodes based
```suggestion
View additional information about each secondary node and its associated databases on the **Secondary Nodes** tab. You can also use the timeseries graphs on the **Metrics** tab to spot abnormal behavior in individual nodes and databases based on view send, redo, and lag metrics. 
```

2023-06-09 00:00 UTC, drichards-87 commented
Created DOCS-563 for the editorial review.

2023-06-13 18:29 UTC, hestonhoffman approved these changes
Left you some suggestions, but LGTM!

2023-06-13 18:29 UTC, hestonhoffman commented on content/en/database_monitoring/guide/heroku-postgres.md
> +<div class="alert alert-warning">Database Monitoring is not supported for this site.</div>
```suggestion
<div class="alert alert-warning">Database Monitoring is not supported on {{< region-param key=dd_datacenter >}}.</div>
```
Just a small QOL suggestion

2023-06-13 18:29 UTC, hestonhoffman commented on content/en/database_monitoring/guide/sql_alwayson.md
> +<div class="alert alert-warning">Database Monitoring is not supported for this site.</div>
```suggestion
<div class="alert alert-warning">Database Monitoring is not supported on {{< region-param key=dd_datacenter >}}.</div>
```
As above

2023-06-13 18:29 UTC, hestonhoffman commented on content/en/database_monitoring/guide/sql_alwayson.md
> +To identify groups that are experiencing issues, use the status filters to show groups with nodes that are Reverting, Not Synchronizing, and so forth. You can also use the timeseries graphs to spot u
I can't find any guidance on this in our style guides, but should these UI terms (Reverting, Not Synchronizing) be italicized/bold? I think I'd usually bold them, but it's up to you.

2023-06-13 18:52 UTC, merged