Added DSM-USM configuration
DataDog/documentation pull request #18213
Opened 2023-05-21 13:03 UTC by guyarb

### What does this PR do?

Adds USM-DSM documentation

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-22 21:11 UTC, urseberry commented
Docs review on https://datadoghq.atlassian.net/browse/DOCS-5534

2023-06-06 21:52 UTC, cswatt requested changes

2023-06-06 21:52 UTC, cswatt commented on content/en/data_streams/zero_instrumentation.md
> +* Install the [AWS Integration][2] for visibility in AWS Load Balancer. You must also enable ENI and EC2 metric collection.
```suggestion
If you are using load balancers with your services, enable additional cloud integrations to allow Universal Service Monitoring to discover cloud-managed entities. Install the [AWS Integration][2] for visibility in AWS Load Balancer. You must also enable ENI and EC2 metric collection.
```

2023-06-07 03:48 UTC, guyarb commented on content/en/data_streams/zero_instrumentation.md
> +[2]: /integrations/amazon_web_services/
USM should not be mentioned here, I didn't remove all instances of USM

2023-06-07 03:51 UTC, guyarb commented on content/en/data_streams/zero_instrumentation.md
> +For ECS, enable USM and the system probe with the following JSON task definition. Deploy the task definition as a [daemon service][1].
https://github.com/DataDog/documentation/pull/18213#discussion_r1220795167

2023-06-07 03:54 UTC, guyarb commented on content/en/data_streams/zero_instrumentation.md
> +[2]: /integrations/amazon_web_services/
switched to DSM

2023-06-07 20:36 UTC, cswatt approved these changes

2023-06-07 20:36 UTC, merged