add site specific settings for each datadog site
DataDog/documentation pull request #18239
Opened 2023-05-23 15:17 UTC by irabinovitch

### What does this PR do?

Adding docs for how to point dogshell at non US1 Datadog sites.

Note that the --api_host command line argument doesn't not yet seem to support API1 and DD-GOV, but dogrc does.  (see https://github.com/DataDog/datadogpy/issues/771)

### Motivation

Someone asked me how to do it.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-23 20:05 UTC, rtrieu requested changes
This looks good to me! The only thing was one closing tag for the text was outside a region tag.

2023-05-23 20:05 UTC, rtrieu commented on content/en/developers/guide/dogshell-quickly-use-datadog-s-api-from-terminal-shell.md
> +```
```suggestion
```

2023-05-23 20:05 UTC, rtrieu commented on content/en/developers/guide/dogshell-quickly-use-datadog-s-api-from-terminal-shell.md
> +api_host = https://us5.datadoghq.com
```suggestion
api_host = https://us5.datadoghq.com
```
```

2023-05-25 21:23 UTC, rtrieu commented on content/en/developers/guide/dogshell-quickly-use-datadog-s-api-from-terminal-shell.md
> +```
To clarify, my feedback here is that the closing tag for the text is out of place - it should be above the /site-region tag 😄

2023-05-31 23:11 UTC, hestonhoffman approved these changes
LGTM!

2023-05-31 23:15 UTC, merged