[RUMM-3147] Add Tracer configuration parameter
DataDog/documentation pull request #18259
Opened 2023-05-24 14:25 UTC by plousada

### What does this PR do?
Introduce the configuration parameters for the iOS Tracer. 

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-24 16:37 UTC, drichards-87 requested changes
Left you some light feedback from Docs.

2023-05-24 16:37 UTC, drichards-87 commented on content/en/tracing/trace_collection/dd_libraries/ios.md
> +| `samplingRate`   | Set a value `0-100` in order to define the percentage of Traces to collect. |
```suggestion
| Method                           | Description                                                                                                                                                                                                                         |
|----------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `serviceName`    | Set the value for the `service`. |
| `sendNetworkInfo` | Set to `true` to enrich traces with network connection info (reachability status, connection type, mobile carrier name, and more).|
| `globalTags`     | Set a `<KEY>:<VALUE>` pair of tags to be added to spans created by the Tracer. |
| `bundleWithRUM`    | Set to `true` to enable spans to be enriched with the current RUM View information. This enables you to see all of the spans produced during a specific View lifespan in the RUM Explorer. |
| `samplingRate`   | Set a value `0-100` to define the percentage of Traces to collect. |
```

2023-05-25 14:45 UTC, drichards-87 approved these changes

2023-05-26 14:44 UTC, xgouchet approved these changes

2023-06-07 13:48 UTC, plousada commented
Could we get this merged? :)

2023-06-12 16:34 UTC, merged