[RUMM-3306] Document react native SDK release 1.7.0
DataDog/documentation pull request #18256
Opened 2023-05-24 12:02 UTC by louiszawadzki

### What does this PR do?
Adds documentation for the new features introduced in the React Native SDK version 1.7.0:

- Feature flag evaluation
- Upload frequency parameter
- Batch size parameter
- Background events tracking parameter

### Motivation

### Additional Notes

The release is not yet out, I will remove the "Do not merge" label once it is ready to be merged :) 

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-24 12:22 UTC, louiszawadzki commented on content/en/real_user_monitoring/reactnative/advanced_configuration.md
> +`trackInteractions`
copy/paste issue - it's deprecated for browser but not for React Native. I've removed the deprecation mention.

2023-06-06 22:08 UTC, rtrieu requested changes
Some minor changes requested, but otherwise looks good!

2023-06-06 22:08 UTC, rtrieu commented on content/en/real_user_monitoring/reactnative/advanced_configuration.md
> +Enables automatic collection of users actions.
```suggestion
Enables automatic collection of user actions.
```

2023-06-06 22:08 UTC, rtrieu commented on content/en/real_user_monitoring/reactnative/advanced_configuration.md
> +The application's version, for example: 1.2.3, 6c44da20, and 2020.02.13. Follows the [tag syntax requirements][15].
```suggestion
The application's version. For example: 1.2.3, 6c44da20, and 2020.02.13. Follows the [tag syntax requirements][15].
```

2023-06-07 09:37 UTC, louiszawadzki commented on content/en/real_user_monitoring/reactnative/_index.md
> +You can track events such as crashes and network requests when your application is in the background (for example, no active view is available).
I'm not sure to understand your message. 
The way I understand it is that we should have "no active view is available" in the similar format it is displayed in RUM or in the app to the user. 

Actually we don't display any such information to users, when the a user switches app for instance, we stop RUM View tracking and therefore there is no active view for the SDK, but that information is not logged or displayed anywhere. 

I copied this part from the iOS / Android SDK docs: https://docs.datadoghq.com/real_user_monitoring/ios/?tab=swift#track-background-events

2023-06-07 16:40 UTC, rtrieu commented on content/en/real_user_monitoring/reactnative/_index.md
> +You can track events such as crashes and network requests when your application is in the background (for example, no active view is available).
```suggestion
You can track events such as crashes and network requests when your application is in the background (for example, when no active view is available).
```

2023-06-09 16:55 UTC, rtrieu approved these changes
Looks good!

2023-06-12 12:28 UTC, louiszawadzki commented
Thanks @rtrieu!
The PR is ready to be merged then :)

2023-06-12 16:31 UTC, merged