Update Windows supported platforms for Datadog Agent 7.46
DataDog/documentation pull request #18262
Opened 2023-05-24 15:44 UTC by clarkb7

PR marked draft and DO NOT MERGE until 7.46 is released.

### What does this PR do?

Update Windows supported platforms for Datadog Agent 7.46

### Motivation

As of Datadog Agent 7.46 the platforms Windows 7, Windows 8, and Windows Server 2008r2 are no longer supported. Datadog Agent 7.45 is the last release to support these platforms.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-25 12:52 UTC, shanelhuang approved these changes
looks good, thanks!

2023-07-10 15:29 UTC, buraizu requested changes
Minor feedback for accessibility via screen reader

2023-07-10 15:29 UTC, buraizu commented on content/en/agent/basic_agent_usage/_index.md
> +- Datadog Agent < 6.46.0/7.46.0 supports Windows Server 2008 R2 with the most recent Windows updates installed. There is also a [known issue with clock drift and Go][12] that affects Windows Server 2
```suggestion
- Datadog Agent versions previous to 6.46.0 and 7.46.0 support Windows Server 2008 R2 with the most recent Windows updates installed. There is also a [known issue with clock drift and Go][12] that affects Windows Server 2008 R2.
```

2023-07-10 17:04 UTC, buraizu approved these changes
LGTM

2023-07-10 17:29 UTC, merged