[DOCS-5536] Updates to Custom Code Vulnerability for beta
DataDog/documentation pull request #18267
Opened 2023-05-24 22:27 UTC by aliciascott

### What does this PR do?
This changes are related to the public beta of custom code vulnerability detection capability. This capability is part of the Vulnerability Management product.

This public beta is scheduled to launch the week of May 29.

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-29 19:30 UTC, kayayarai requested changes

2023-05-29 19:30 UTC, kayayarai commented on content/en/security/application_security/enabling/java.md
> +**Note**: Read-only file systems are not currently supported. The application must have access to a writable `/tmp` directory.
```suggestion
**Note**: Read-only file systems are not supported. The application must have access to a writable `/tmp` directory.
```

2023-05-29 19:30 UTC, kayayarai commented on content/en/security/application_security/enabling/nodejs.md
> + ```shell
~~~suggestion
   If you initialize the APM library on the command line using the `--require` option to Node.js:

   ```shell
~~~

2023-05-29 19:30 UTC, kayayarai commented on content/en/security/application_security/enabling/java.md
> +5. To see Application Vulnerability Management for custom code vulnerabilities in action, browse your service and the custom code vulnerabilities will appear in the [Vulnerability Explorer][4]. The `
```suggestion
5. To see Application Vulnerability Management for custom code vulnerabilities in action, browse your service and the custom code vulnerabilities appear in the [Vulnerability Explorer][4]. The `SOURCE` column shows the Custom Code value.
```

2023-05-29 19:30 UTC, kayayarai commented on content/en/security/application_security/enabling/java.md
> + ```shell
~~~suggestion
   From the command line:

   ```shell
~~~

2023-05-29 19:30 UTC, kayayarai commented on content/en/security/application_security/enabling/java.md
> +If your service is running a [tracing library version that supports Vulnerability Management for Custom Code Vulnerability Detection][3], enable it by setting the `DD_IAST_ENABLED=true` environment v
```suggestion
If your service runs a [tracing library version that supports Vulnerability Management for Custom Code Vulnerability Detection][3], enable the capability by setting the `DD_IAST_ENABLED=true` environment variable and restarting your service.
```

2023-05-29 19:31 UTC, kayayarai requested changes

2023-05-29 19:31 UTC, kayayarai commented on content/en/security/application_security/enabling/nodejs.md
> +5. To see Application Vulnerability Management for custom code vulnerabilities in action, browse your service and the custom code vulnerabilities will appear in the [Vulnerability Explorer][5]. The `
```suggestion
5. To see Application Vulnerability Management for custom code vulnerabilities in action, browse your service and the custom code vulnerabilities appear in the [Vulnerability Explorer][5]. The `SOURCE` column shows the Custom Code value.
```

2023-05-29 19:41 UTC, kayayarai commented on content/en/security/application_security/enabling/java.md
> +**Note**: Read-only file systems are not supported. The application must have access to a writable `/tmp` directory.
```suggestion
   Or one of the following methods, depending on where your application runs:

   **Note**: Read-only file systems are not supported. The application must have access to a writable `/tmp` directory.
```

2023-05-29 19:55 UTC, kayayarai approved these changes

2023-06-01 10:52 UTC, gorkavicente requested changes
/security/application_security/enabling/compatibility/
Replace Java version with 1.15.0

/security/application_security/enabling/compatibility/java/
Vulnerability Management
–> Custom code vulnerability detection 1.15.0

The minimum tracer version to get all supported ASM capabilities for Java is 1.15.0.

2023-06-01 16:37 UTC, merged