Add Flutter examples for feature flag integrations
DataDog/documentation pull request #18289
Opened 2023-05-26 11:15 UTC by fuzzybinary

### What does this PR do?

Added examples for feature flag evaluation for Flutter.

Also fix a few language definitions for iOS / Android code snippets.

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-05-26 16:51 UTC, drichards-87 requested changes
Hi @fuzzybinary. The build job for this PR is failing. I believe it's because of a missing % in one of the tab shortcodes. Could you fix the tabs (i.e., commit my suggestions), and then I'll review the rest of the PR. Thanks!

2023-05-26 16:51 UTC, drichards-87 commented on content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> +{{% tab "Flutter"}}
```suggestion
{{% tab "Flutter" %}}
```

2023-05-26 16:51 UTC, drichards-87 commented on content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> +{{% /tab }}
```suggestion
{{% /tab %}}
```

2023-05-30 17:03 UTC, drichards-87 approved these changes
Thanks for updating the PR. It's approved now. Let me know when it's ready to be merged.

2023-05-30 17:18 UTC, fuzzybinary commented
@drichards-87 Ready now. This was documenting already available APIs.

2023-05-30 17:21 UTC, merged