DOCS-5485 - Guide for service account impersonation and automatic project discovery
DataDog/documentation pull request #18317
Opened 2023-05-30 15:55 UTC by cswatt

hold for merge

2023-05-30 22:08 UTC, rtrieu requested changes
Some minor edits, but otherwise looks good!

2023-05-30 22:08 UTC, rtrieu commented on content/en/integrations/guide/service-account-impersonation.md
> +### Prerequisites
```suggestion
## Prerequisites
```

2023-05-30 22:08 UTC, rtrieu commented on content/en/integrations/guide/service-account-impersonation.md
> +### Setup
```suggestion
## Setup
```

2023-05-30 22:08 UTC, rtrieu commented on content/en/integrations/guide/service-account-impersonation.md
> +* If your organization restricts identities by domain, you must add Datadog's customer identity as an allowed value in your policy. Datadog's customer identity: `C0147pk0i`
```suggestion
* If your organization restricts identities by domain, you must add Datadog's customer identity as an allowed value in your policy. Datadog's customer identity is: `C0147pk0i`
```

2023-05-30 22:08 UTC, rtrieu commented on content/en/integrations/guide/service-account-impersonation.md
> +7. Paste your Datading principal into the **New principals** text box.
```suggestion
7. Paste your Datadog principal into the **New principals** text box.
```

2023-05-30 22:08 UTC, rtrieu commented on content/en/integrations/guide/service-account-impersonation.md
> +3. Return to the integration configuration tile in Datadog (where you coppied your Datadog principal in the [previous section](#2-add-the-datadog-principal-to-your-service-account)).
```suggestion
3. Return to the integration configuration tile in Datadog (where you copied your Datadog principal in the [previous section](#2-add-the-datadog-principal-to-your-service-account)).
```

2023-05-30 22:08 UTC, rtrieu commented on content/en/integrations/guide/service-account-impersonation.md
> +4. In the box under **Add Service Account Email**, paste the email you previously coppied.
```suggestion
4. In the box under **Add Service Account Email**, paste the email you previously copied.
```

2023-06-14 22:13 UTC, cswatt commented
stale, added to dogweb instead

2023-06-14 22:13 UTC, closed without merging