Spans indexed by intelligent retention filter can be viewed in Timeseries now
DataDog/documentation pull request #18384
Opened 2023-06-02 19:43 UTC by drichards-87

### What does this PR do?
Fix outdated lines

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-02 19:44 UTC, drichards-87 commented
@cecile75 Git doesn’t appear to like the special character in your branch name, so I went ahead and renamed it.

2023-06-02 19:47 UTC, drichards-87 reviewed
Left you some minor feedback from Docs.

2023-06-02 19:47 UTC, drichards-87 commented on content/en/tracing/trace_explorer/_index.md
> +From the timeseries view, export your query to a [dashboard][1], a [monitor][2] or a [notebook][3] to investigate further or to alert automatically when an aggregate number of spans crosses a specifi
```suggestion
From the timeseries view, export your query to a [dashboard][1], a [monitor][2] or a [notebook][3] to investigate further or to alert automatically when an aggregate number of spans crosses a specific threshold. 

**Note**: Spans indexed by the intelligent retention filter are excluded from APM queries that appear in dashboards, notebooks, and from trace analytics monitor evaluations. For more information, see [Trace Retention][4].
```

2023-06-02 19:47 UTC, drichards-87 commented on content/en/tracing/trace_explorer/_index.md
> +All spans indexed by custom retention filters *and* the intelligent retention filter are available to be searched when using trace analytics.
```suggestion
All spans indexed by custom retention filters **and** the intelligent retention filter are available to be searched when using trace analytics.
```

2023-06-02 19:47 UTC, drichards-87 reviewed
Left you some minor feedback from Docs.

2023-06-02 19:47 UTC, drichards-87 reviewed
Left you some minor feedback from Docs.

2023-06-05 16:54 UTC, cswatt requested changes

2023-06-05 16:54 UTC, cswatt commented on content/en/tracing/trace_explorer/_index.md
> +All spans indexed by custom retention filters **and** the intelligent retention filter are available to be searched when using trace analytics.
```suggestion
All spans indexed by custom retention filters or the intelligent retention filter are available to be searched when using trace analytics.
```

OR means "any span indexed by either the custom retention filter or the intelligent retention filter is available"
AND means "only spans that have been indexed by both the custom retention filter and intelligent retention filter are available"

2023-06-05 16:54 UTC, cswatt commented on content/en/tracing/trace_explorer/_index.md
> +From the timeseries view, export your query to a [dashboard][1], a [monitor][2] or a [notebook][3] to investigate further or to alert automatically when an aggregate number of spans crosses a specifi
```suggestion
From the timeseries view, export your query to a [dashboard][1], [monitor][2], or [notebook][3] to investigate further or to alert automatically when an aggregate number of spans crosses a specific threshold. 
```

2023-06-05 17:08 UTC, cswatt approved these changes

2023-06-05 17:47 UTC, merged