[profiling] Dual-shipping notes.
DataDog/documentation pull request #18424
Opened 2023-06-07 09:44 UTC by AlexJF

### What does this PR do?
Highlight caveats of profiling dual shipping, namely the priorities involving main and additional endpoints.

### Motivation
Clarifying operational details of profiling dual shipping.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-07 10:05 UTC, gturbat requested changes

2023-06-07 10:05 UTC, gturbat commented on content/en/agent/guide/dual-shipping.md
> +* Responses from additional endpoints are not forwarded back to the continuous profiler. Any errors during delivery to additional endpoints will simply be logged in the agent error logs.
```suggestion
* Responses from additional endpoints are not forwarded back to the continuous profiler. Any errors during delivery to additional endpoints will be logged in the agent error logs.
```

2023-06-07 11:24 UTC, gturbat commented on content/en/agent/guide/dual-shipping.md
> +* Responses from additional endpoints are not forwarded back to the continuous profiler. Any errors during delivery to additional endpoints will be logged in the agent error logs.
```suggestion
* Responses from additional endpoints are not forwarded back to the continuous profiler. Any errors during delivery to additional endpoints are logged in the agent error logs.
```

2023-06-08 11:48 UTC, gturbat approved these changes

2023-06-08 18:35 UTC, hestonhoffman reviewed
Some small edits

2023-06-08 18:35 UTC, hestonhoffman commented on content/en/agent/guide/dual-shipping.md
> +* Responses from additional endpoints are not forwarded back to the profiler. Any errors during delivery to additional endpoints are logged in the agent error logs.
```suggestion
**Note:** Uploads to additional endpoints for the Continuous Profiler product are done through best-effort delivery.
* The main endpoint has the highest priority. Uploads to additional endpoints are only handled after uploads to the main endpoint have completed successfully.
* Responses from additional endpoints are not forwarded back to the profiler. Any errors during delivery to additional endpoints are logged in the Agent error logs.
```

2023-06-15 15:05 UTC, merged