Prepare signing with new GPG keys
DataDog/documentation pull request #18483
Opened 2023-06-12 09:41 UTC by chouetz

### What does this PR do?
Update GPG keys for key rotation

### Motivation
Key rotation process

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-20 11:01 UTC, chouetz commented on content/en/agent/guide/linux-agent-2022-key-rotation.md
> +- The RPM signing key with hash [`C6559B690CA882F023BDF3F63F4D1729FD4BF915`][1] will be rotated on --month-- --day-- at 12:00 UTC, 2023 and replaced by the key with hash [`7408BFD56BC5BF0C361AAAE85D8
We don't know the dates yet, this PR must not be merged until this.

2023-06-20 12:01 UTC, bkabrda requested changes
Hi :wave: this mostly looks good, but I left couple inline comments to get addressed. Thanks!

2023-06-20 12:01 UTC, bkabrda commented on content/en/data_security/agent.md
> +  - [5F1E256061D813B125E156E8E6266D4AC0962C7D][5]
Why don't we use reference numbers that we would add to the end of the reference list, thus preventing shifting all other values? The numbers themselves don't really matter, we can use e.g. 19 here without a problem.

2023-07-12 16:29 UTC, urseberry approved these changes

2023-07-12 17:29 UTC, merged