updates
DataDog/documentation pull request #18512
Opened 2023-06-13 14:10 UTC by jcstorms1

### What does this PR do?

- Updates linux wrapper version
- Adds new information about Tomcat applications and that `DD_START_APP` is not necessary for them
- Removed unnecessary instructions in the Java section
### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-13 18:12 UTC, rtrieu requested changes
Minor suggestions for consistency. Also found an existing typo.

2023-06-13 18:12 UTC, rtrieu commented on content/en/serverless/azure_app_services/azure_app_services_linux.md
> +- `DD_START_APP` is the command used to start your application. For example, `node ./bin/www` (Unnecessary for applications running in Tomcat).
```suggestion
- `DD_START_APP` is the command used to start your application. For example, `node ./bin/www` (unnecessary for applications running in Tomcat).
```

2023-06-13 18:12 UTC, rtrieu commented on content/en/serverless/azure_app_services/azure_app_services_linux.md
>  | PHP       | `cp /home/site/wwwroot/default /etc/nginx/sites-available/default && service nginx reload` | Copies script to correct location and starts applicatio.
```suggestion
| PHP       | `cp /home/site/wwwroot/default /etc/nginx/sites-available/default && service nginx reload` | Copies script to correct location and starts application.                                                                                                                                                                           |
```

2023-06-13 18:12 UTC, rtrieu commented on content/en/serverless/azure_app_services/azure_app_services_linux.md
> +| Java      | `java -jar /home/site/wwwroot/datadog-demo.jar`                                            | The command to start your app. Not required for applications running in tomcat
```suggestion
| Java      | `java -jar /home/site/wwwroot/datadog-demo.jar`                                            | The command to start your app. This is not required for applications running in Tomcat.                                                                                                                                                                                                  |
```

2023-06-14 13:15 UTC, jcstorms1 commented
@rtrieu thanks for the suggestions. I commited them.

2023-06-14 17:23 UTC, rtrieu approved these changes
Looks good!

2023-06-15 13:44 UTC, jcstorms1 commented
@rtrieu Yes please!

2023-06-15 15:12 UTC, merged