RUMM-3290 Add Error Tracking page for Roku
DataDog/documentation pull request #18541
Opened 2023-06-14 14:34 UTC by xgouchet

### What does this PR do?

Add the Error Tracking documentation for our Roku RUM integration

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-14 23:41 UTC, buraizu commented
Thanks, created DOCS-5687 for documentation team review

2023-06-15 04:46 UTC, timmld requested changes

2023-06-15 04:46 UTC, timmld commented on content/en/real_user_monitoring/error_tracking/roku.md
> +3. Run the Gradle task to upload your Proguard/R8 mapping file to Datadog in order to access deobfuscated stack traces.
is this still valid for Roku?

2023-06-20 11:26 UTC, timmld commented
@xgouchet just one small thing, i never know if the fact that i'm not seeing all the sections in this side navigation is normal in staging or not? <img width="145" alt="Screenshot 2023-06-20 at 13 25 42" src="https://github.com/DataDog/documentation/assets/53906368/607ca470-9a9b-4c25-bf20-ead507e4069c">

2023-06-22 00:15 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/roku.md
> +Whenever you perform an operation that might throw an exception, you can forward the error to Datadog as follows:
```suggestion
Whenever you perform an operation that might throw an exception, you can forward the error to Datadog by adding the following code snippet:
```

2023-06-22 00:16 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/roku.md
> +Whenever you perform an operation that might throw an exception, you can forward the error to Datadog as follows:
Not sure if this is a code snippet or command, so please edit as necessary.

2023-06-22 00:17 UTC, rtrieu requested changes
A few minor suggestions, but otherwise looks good.

2023-06-26 09:32 UTC, timmld approved these changes

2023-06-27 16:41 UTC, rtrieu approved these changes
Looks good!

2023-06-27 16:41 UTC, merged