DOCS-5657 Handling Pop-Ups in Browser Tests Guide Edits
DataDog/documentation pull request #18562
Opened 2023-06-15 01:05 UTC by alai97

### What does this PR do?

Updates the output for `prompt` and `confirm` modals.

### Motivation

DOCS-5657

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-03 18:02 UTC, alai97 commented on content/en/synthetics/guide/popup.md
> +[5]: /synthetics/browser_test
```suggestion
[5]: /synthetics/browser_tests
```

2023-07-03 20:29 UTC, alai97 commented on content/en/synthetics/guide/popup.md
> + - `prompt` modals are answered with the text returned or `null` if the Cancel button or `Esc` is clicked.
```suggestion
 - `prompt` modals are answered with the text returned or `null` if the Cancel button or `Esc` is clicked. `prompt` modals offer a text input field that is filled with `Lorem Ipsum` for tests on Google Chrome or Microsoft Edge.
```

2023-07-03 20:55 UTC, alai97 commented on content/en/synthetics/guide/popup.md
>   - `alert` modals are closed.
```suggestion
 - `alert` modals are immediately dismissed. 
```

2023-07-03 20:56 UTC, alai97 commented on content/en/synthetics/guide/popup.md
> + - `confirm` modals are answered with `true` for OK and `false` if the Cancel button or `Esc` is clicked.
```suggestion
 - `confirm` modals that ask for confirmation are answered with `true` for OK and `false` if the Cancel button or `Esc` is clicked.
```

2023-07-03 21:00 UTC, alai97 commented on content/en/synthetics/guide/popup.md
> + - `prompt` modals are answered with the text returned or `null` if the Cancel button or `Esc` is clicked. `prompt` modals offer a text input field that is filled with `Lorem Ipsum` for tests on Goog
```suggestion
 - `prompt` modals are answered with the text returned or `null` if the Cancel button or `Esc` is clicked. `prompt` modals that offer a text input field are filled with `Lorem Ipsum` for tests on Google Chrome or Microsoft Edge.
```

2023-07-04 08:35 UTC, HugoPct requested changes
changed the 3 items following etienne's suggestion

2023-07-04 08:35 UTC, HugoPct commented on content/en/synthetics/guide/popup.md
> + - `confirm` modals that ask for confirmation are answered with `true` for OK and `false` if the Cancel button or `Esc` is clicked.
```suggestion
 - `confirm` modals that ask for confirmation are accepted.
```

2023-07-04 08:35 UTC, HugoPct commented on content/en/synthetics/guide/popup.md
> + - `prompt` modals are answered with the text returned or `null` if the Cancel button or `Esc` is clicked. `prompt` modals that offer a text input field are filled with `Lorem Ipsum` for tests on Goo
```suggestion
 - `prompt` modals are filled with `Lorem Ipsum` for tests on Google Chrome or Microsoft Edge.
```

2023-07-05 20:50 UTC, rtrieu approved these changes
Minor suggestion but otherwise looks good!

2023-07-05 20:50 UTC, rtrieu commented on content/en/synthetics/guide/popup.md
> +This guide describes how to manage pop-ups such as modals or application windows in a Synthetics [browser test][5].
```suggestion
This guide describes how to manage pop-ups such as modals or application windows in a Synthetic [browser test][5].
```

2023-07-06 07:59 UTC, HugoPct approved these changes

2023-07-06 16:36 UTC, merged