Update documentation for Datadog for IntelliJ plugin
DataDog/documentation pull request #18642
Opened 2023-06-22 12:01 UTC by jfree

### What does this PR do?
Updates the documentation for the Datadog plugin for IntelliJ IDEA.

### Motivation
The latest public beta release (v0.7.0) has new features and the UI has changed, so this PR brings the documentation up to date with respect to our current release.

https://datadoghq.atlassian.net/wiki/spaces/IP/pages/2312798790/Datadog+for+IntelliJ+IDEA

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-22 18:15 UTC, aliciascott requested changes
Thanks @jfree for the additions! I have added some small changes for sentence case, formatting, punctuation where needed, and minor wording changes. Also please review the "Log Navigation support" line as it doesn't seem to flow where it is, and should be moved down to the "Log Navigation" section? Or is this just a sentence there to highlight the basic overview of Log Navigation ?Thanks!

2023-06-22 18:15 UTC, aliciascott commented on content/en/developers/ide_integrations/idea/_index.md
> +A flame graph is a visualization of profiling samples that shows stack traces and their relative frequency during the sample period. The Datadog plugin take multiple individual profiles collected ove
```suggestion
A flame graph is a visualization of profiling samples that shows stack traces and their relative frequency during the sample period. The Datadog plugin collects multiple individual profiles from the requested time frame, and aggregates them. Each individual profile covers a 60 second interval within the requested time frame.
```

2023-06-22 18:15 UTC, aliciascott commented on content/en/developers/ide_integrations/idea/_index.md
> +### Source Highlighting
```suggestion
### Source highlighting
```

2023-06-22 18:15 UTC, aliciascott commented on content/en/developers/ide_integrations/idea/_index.md
> +When the Continuous Profiler tab is active, the plugin adds code highlights to the source code editor margin. For Top Methods an icon appears in the editor margin, and line-level highlights appear in
```suggestion
When the Continuous Profiler tab is active, the plugin adds code highlights to the source code editor margin. For Top Methods, an icon appears in the editor margin, and line-level highlights appear in the code based on the active Profiling data.
```

2023-06-22 18:15 UTC, aliciascott commented on content/en/developers/ide_integrations/idea/_index.md
> +## Logs Navigation
```suggestion
## Logs navigation
```

2023-06-22 18:15 UTC, aliciascott commented on content/en/developers/ide_integrations/idea/_index.md
> +You can navigate to the [Log Explorer][5] on the Datadog platform directly from your Java source files. Look out for **View Logs** links following log statements in your source code:
```suggestion
You can navigate to the [Log Explorer][5] on the Datadog platform directly from your Java source files. Look for the**View Logs** links following the log statements in your source code:
```

2023-06-22 18:15 UTC, aliciascott commented on content/en/developers/ide_integrations/idea/_index.md
> +Clicking the link opens the **Log Explorer** with a query that matches the logger name, log level and log message as closely as possible.
```suggestion
Clicking the link opens the **Log Explorer** with a query that matches the logger name, log level, and log message as closely as possible.
```

2023-06-22 18:15 UTC, aliciascott commented on content/en/developers/ide_integrations/idea/_index.md
> +## View In IntelliJ IDEA
```suggestion
## View in IntelliJ IDEA
```

2023-06-22 18:15 UTC, aliciascott commented on content/en/developers/ide_integrations/idea/_index.md
> +The **View in IntelliJ** feature provides a link from the Datadog platform directly to your source files. Look out for the button next to frames in stack traces displayed on the platform (for example
```suggestion
The **View in IntelliJ** feature provides a link from the Datadog platform directly to your source files. Look for the button next to frames in stack traces displayed on the platform (for example, in [Error Tracking][6]):
```

2023-06-23 08:34 UTC, jfree commented on content/en/developers/ide_integrations/idea/_index.md
> +The **Logs Navigation** support opens the Datadog Log Explorer with a view matching the context in which you are working.
The idea is for the Overview to mention each main feature the plugin offers.  Perhaps the real issue is that the description for the Continuous Profiler is too long? (previously it was the _main_ feature)

2023-06-26 15:24 UTC, aliciascott approved these changes
Looks good!

2023-06-26 15:37 UTC, merged