Add SQL Server to APM-DBM docs and clarify the modes
DataDog/documentation pull request #18669
Opened 2023-06-23 15:36 UTC by justiniso

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-23 15:46 UTC, alexandre-normand approved these changes
Yes! 🚀

2023-06-23 20:55 UTC, alexandre-normand approved these changes
💯

2023-07-11 19:47 UTC, drichards-87 requested changes

2023-07-11 19:47 UTC, drichards-87 commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +   - For Postgres & MySQL: `DD_DBM_PROPAGATION_MODE=full`
```suggestion
   - For Postgres and MySQL: `DD_DBM_PROPAGATION_MODE=full`
```

2023-07-11 19:47 UTC, drichards-87 commented on content/en/database_monitoring/guide/connect_dbm_and_apm.md
> +| `full`                   | {{< X >}} | {{< X >}} | unsupported  |
```suggestion
| `full`                   | {{< X >}} | {{< X >}} |          |
```

2023-07-11 19:49 UTC, drichards-87 approved these changes

2023-07-11 19:49 UTC, merged