Add precision on RUM connectivity attributes
DataDog/documentation pull request #18661
Opened 2023-06-23 09:01 UTC by xgouchet

### What does this PR do?
Add precision on the RUM connectivity attribute as they're not available on *all* the RUM events.

### Motivation
A customer got confused and thought some data was missing.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-23 20:38 UTC, buraizu requested changes
Thanks, just flagging a typo

2023-06-23 20:38 UTC, buraizu commented on content/en/real_user_monitoring/android/data_collected.md
> +The following netowrk-related attributes are attached automatically to Resource and Error events collected by Datadog:
```suggestion
The following network-related attributes are attached automatically to Resource and Error events collected by Datadog:
```

2023-06-23 20:38 UTC, buraizu commented on content/en/real_user_monitoring/ios/data_collected.md
> +The following netowrk-related attributes are attached automatically to Resource and Error events collected by Datadog:
```suggestion
The following network-related attributes are attached automatically to Resource and Error events collected by Datadog:
```

2023-06-26 09:19 UTC, mariusc83 approved these changes

2023-06-26 09:25 UTC, 0xnm approved these changes

2023-06-26 10:42 UTC, jonathanmos approved these changes

2023-06-26 17:36 UTC, buraizu approved these changes

2023-06-26 17:37 UTC, merged