Update 'Infrastructure List' documentation
DataDog/documentation pull request #18703
Opened 2023-06-27 15:01 UTC by hush-hush

### What does this PR do?

Update the documentation following https://github.com/DataDog/datadog-agent/pull/17857 which enabled this feature by default. This change targets agent 7.47 and should not be merged before this version of the agent is release.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-27 19:24 UTC, sgnn7 approved these changes
Left just a couple of tiny nits but LGTM

2023-06-27 19:24 UTC, sgnn7 commented on content/en/infrastructure/list.md
> +This feature is enabled by default since Agent version 7.47.0/6.47.0.
```suggestion
This feature is enabled by default in Agent version >= 7.47.0/6.47.0.
```

2023-06-27 19:24 UTC, sgnn7 commented on content/en/infrastructure/list.md
> +To enable or disable it, change the value of `inventories_configuration_enabled` setting in your [Agent configuration file][6] (set it to `true` to
```suggestion
To modify this behavior, change the value of `inventories_configuration_enabled` setting in your [Agent configuration file][6] (set it to `true` to
```

2023-06-27 19:24 UTC, sgnn7 commented on content/en/infrastructure/list.md
> +enable it and `false` to disable it):
```suggestion
enable send of the configuration and `false` to disable it):
```

2023-06-27 19:24 UTC, sgnn7 commented on content/en/infrastructure/list.md
>  Alternatively, use the `DD_INVENTORIES_CONFIGURATION_ENABLED=true` environment variable to enable this feature.
```suggestion
Alternatively, use the `DD_INVENTORIES_CONFIGURATION_ENABLED` environment variable to enable or disable this feature.
```

2023-08-17 17:24 UTC, rtrieu requested changes
Minor suggestion, but otherwise looks good!

2023-08-17 17:24 UTC, rtrieu commented on content/en/infrastructure/list.md
> +To modify this behavior, change the value of `inventories_configuration_enabled` setting in your [Agent configuration file][6] (true to send the configuration and false to disable it).
```suggestion
To modify this behavior, set the value of the `inventories_configuration_enabled` setting in your [Agent configuration file][6] to `true` to send the configuration, or `false` to disable it.
```

2023-08-18 13:16 UTC, sgnn7 commented on content/en/infrastructure/list.md
> +To modify this behavior, set the value of the `inventories_configuration_enabled` setting in your [Agent configuration file][6] to `true` to send the configuration, or `false` to disable it.
@hush-hush Tiny nit:
```suggestion
To modify this behavior, set the value of the `inventories_configuration_enabled` in your [Agent configuration file][6] to `true` to send the configuration, or `false` to disable it.
```

2023-08-31 16:18 UTC, rtrieu commented on content/en/infrastructure/list.md
> +To modify this behavior, set the value of the `inventories_configuration_enabled` in your [Agent configuration file][6] to `true` to send the configuration, or `false` to disable it.
```suggestion
To modify this behavior, set the value of `inventories_configuration_enabled` in your [Agent configuration file][6] to `true` to send the configuration, or `false` to disable it.
```

2023-08-31 16:18 UTC, rtrieu approved these changes
Approving with a minor suggestion!

2023-09-01 15:06 UTC, urseberry approved these changes

2023-09-01 15:06 UTC, merged