[ci-visibility] Add cypress' limitation with `after:run`
DataDog/documentation pull request #18728
Opened 2023-06-29 14:09 UTC by juan-fernandez

### What does this PR do?
Add a known limitation to the cypress plugin for ci visibility.

### Motivation
Let users know.

### Preview

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-06-29 18:59 UTC, alai97 requested changes
Some link + copy suggestions!

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +[7]: /continuous_integration/guides/rum_integration/
These links are nested in a tab, so it's important to have them as different anchors as the links at the bottom of the page!

```suggestion
[101]: https://docs.cypress.io/api/plugins/writing-a-plugin#Plugins-API
[102]: https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Plugins-file
[103]: https://docs.cypress.io/guides/references/configuration#cypress-json
[104]: https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file
[105]: /tracing/trace_collection/custom_instrumentation/nodejs?tab=locally#adding-tags
[106]: /real_user_monitoring/browser/#setup
[107]: /continuous_integration/guides/rum_integration/
```

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +If the browser application being tested is instrumented using [Browser Monitoring][6], your Cypress test results and their generated RUM browser sessions and session replays are automatically linked.
```suggestion
If the browser application being tested is instrumented using [Browser Monitoring][106], your Cypress test results and their generated RUM browser sessions and session replays are automatically linked. For more information, see the [Instrumenting your browser tests with RUM guide][107].
```

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +To create filters or `group by` fields for these tags, you must first create facets. For more information about adding tags, see the [Adding Tags][5] section of the Node.js custom instrumentation doc
```suggestion
To create filters or `group by` fields for these tags, you must first create facets. For more information about adding tags, see the [Adding Tags][105] section of the Node.js custom instrumentation documentation.
```

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +2. Add the following line to the **top level** of your [`supportFile`][4]:
```suggestion
2. Add the following line to the **top level** of your [`supportFile`][104]:
```

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +1. Set [`pluginsFile`][2] to `"dd-trace/ci/cypress/plugin"`, for example, through [`cypress.json`][3]:
```suggestion
1. Set [`pluginsFile`][102] to `"dd-trace/ci/cypress/plugin"`, for example, through [`cypress.json`][103]:
```

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +   <div class="alert alert-warning"><strong>Note</strong>: Datadog requires the <a href="#cypress-afterrun-event">'after:run'</a> cypress event to work, and Cypress does not currently allow multiple
```suggestion
   <div class="alert alert-warning"><strong>Note</strong>: Datadog requires the <a href="#cypress-afterrun-event">'after:run'</a> cypress event to work, and Cypress does not allow multiple <a href="">'after:run'</a> handlers. If you are using this event, <code>dd-trace</code> will not work properly.</div>
```

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +<div class="alert alert-warning"><strong>Note</strong>: Datadog requires the <a href="#cypress-afterrun-event">'after:run'</a> cypress event to work, and Cypress does not currently allow multiple <a
```suggestion
<div class="alert alert-warning"><strong>Note</strong>: Datadog requires the <a href="#cypress-afterrun-event">'after:run'</a> cypress event to work, and Cypress does not allow multiple <a href="">'after:run'</a> handlers. If you are using this event, <code>dd-trace</code> will not work properly.</div>
```

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +Use the Cypress API documentation to [learn how to write plugins][1] for `cypress>=10`.
```suggestion
Use the Cypress API documentation to [learn how to write plugins][101] for `cypress>=10`.
```

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +[Mocha >=9.0.0][8] uses an ESM-first approach to load test files. That means that if [ES modules][9] are used (for example, by defining test files with the `.mjs` extension), _the instrumentation is
I'm not sure if the ES modules and the Node.js documentation are supposed to share the same link or not!

```suggestion
[Mocha >=9.0.0][8] uses an ESM-first approach to load test files. That means that if [ES modules][10] are used (for example, by defining test files with the `.mjs` extension), _the instrumentation is limited_. Tests are detected, but there isn't visibility into your test. For more information about ES modules, see the [Node.js documentation][10].
```

2023-06-29 18:59 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +Datadog requires the usage of Cypress' [`after:run` event][14]. Currently, Cypress only allows a single listener for this event, so if your custom Cypress plugin requires `after:run`, it will be inco
```suggestion
Datadog requires usage of the Cypress [`after:run` event][14]. Cypress only allows a single listener for this event, so if your custom Cypress plugin requires `after:run`, it is incompatible with `dd-trace`.
```

2023-07-03 09:19 UTC, juan-fernandez commented
is there any other concern @alai97 ?

2023-07-03 16:48 UTC, alai97 approved these changes

2023-07-03 16:50 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +<div class="alert alert-warning"><strong>Note</strong>: Datadog requires the <a href="#cypress-afterrun-event">'after:run'</a> cypress event to work, and Cypress does not allow multiple <a href="">'a
```suggestion
<div class="alert alert-warning"> Datadog requires the <a href="#cypress-afterrun-event">after:run</a> Cypress event to work, and Cypress does not allow multiple <a href="">'after:run'</a> handlers. If you are using this event, dd-trace will not work properly.</div>
```

2023-07-03 16:50 UTC, alai97 commented on content/en/continuous_integration/tests/javascript.md
> +   <div class="alert alert-warning"><strong>Note</strong>: Datadog requires the <a href="#cypress-afterrun-event">'after:run'</a> cypress event to work, and Cypress does not allow multiple <a href=""
```suggestion
   <div class="alert alert-warning"> Datadog requires the <a href="#cypress-afterrun-event">'after:run'</a> Cypress event to work, and Cypress does not allow multiple <a href="">'after:run'</a> handlers. If you are using this event, <code>dd-trace</code> will not work properly.</div>
```

2023-07-03 17:05 UTC, merged