[ci-visibility] Add manual testing API for javascript
DataDog/documentation pull request #18773
Opened 2023-07-03 10:14 UTC by juan-fernandez

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-03 17:47 UTC, kayayarai requested changes
A few edits for your consideration.

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +  <strong>Note:</strong> To use the manual testing API, you must pass <code>DD_CIVISIBILITY_MANUAL_API_ENABLED=1</code> as an environment variable.
```suggestion
  <strong>Note</strong>: To use the manual testing API, you must pass <code>DD_CIVISIBILITY_MANUAL_API_ENABLED=1</code> as an environment variable.
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +  <strong>Note:</strong> Manual testing API is currently in <strong>beta</strong>, so its API might change. It is is available from <code>dd-trace>=4.4.0</code>, <code>dd-trace>=3.25.0</code> and <co
```suggestion
  <strong>Note</strong>: The manual testing API is in <strong>beta</strong>, so its API might change. It is available starting in <code>dd-trace</code> versions <code>4.4.0</code>, <code>3.25.0</code>, and <code>2.38.0</code>.
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +If you use Jest, Mocha, Cypress, Playwright or Cucumber, CI Visibility automatically instruments them and sends the test results to Datadog. If you use an unsupported testing framework or if you have
```suggestion
If you use Jest, Mocha, Cypress, Playwright, or Cucumber, CI Visibility automatically instruments them and sends the test results to Datadog. If you use an unsupported testing framework or if you have a different testing mechanism, you can instead use the API to report test results to Datadog.
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +Grab this channel by its ID `dd-trace:ci:manual:test:start` to publish that a test is going to start. A good place to do this might be a `beforeEach` hook, or similar.
```suggestion
Grab this channel by its ID `dd-trace:ci:manual:test:start` to publish that a test is starting. A good place to do this is a `beforeEach` hook or similar.
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +The payload that needs to be published has attributes `testName` and `testSuite`, both of which are strings, that identify the test about to start.
```suggestion
The payload to be published has attributes `testName` and `testSuite`, both strings, that identify the test that is about to start.
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +Grab this channel by its ID `dd-trace:ci:manual:test:finish` to publish that a test is about to end. A good place to do this might be a `afterEach` hook, or similar.
```suggestion
Grab this channel by its ID `dd-trace:ci:manual:test:finish` to publish that a test is ending. A good place to do this is an `afterEach` hook or similar.
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +The payload that needs to be published has attributes `status` and `error`:
```suggestion
The payload to be published has attributes `status` and `error`:
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +* `status` is a string that can only take three values:
```suggestion
* `status` is a string that takes one of three values:
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +The payload that needs to be published is a dictionary `<string, string|number>` of tags or metrics that will be added to the test.
```suggestion
The payload to be published is a dictionary `<string, string|number>` of tags or metrics that are added to the test.
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +### How to run
```suggestion
### Run the tests
```

2023-07-03 17:47 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +Once the test start and end channels are put in place in your code, you may run your testing framework like you normally do, including the following environment variables:
```suggestion
When the test start and end channels in your code, run your testing framework like you normally do, including the following environment variables:
```

2023-07-03 17:57 UTC, juan-fernandez commented on content/en/continuous_integration/tests/javascript.md
> +Once the test start and end channels are put in place in your code, you may run your testing framework like you normally do, including the following environment variables:
would this be 
```
When the test start and end channels **are** in your code, run your testing...
```
?

2023-07-03 17:58 UTC, juan-fernandez commented
> A few edits for your consideration.

thanks for the great feedback! I applied all but https://github.com/DataDog/documentation/pull/18773#discussion_r1251153624, which seems to be missing a word?

2023-07-05 16:58 UTC, kayayarai commented on content/en/continuous_integration/tests/javascript.md
> +Once the test start and end channels are put in place in your code, you may run your testing framework like you normally do, including the following environment variables:
Yes, **are** :)

2023-07-05 17:15 UTC, juan-fernandez commented on content/en/continuous_integration/tests/javascript.md
> +Once the test start and end channels are put in place in your code, you may run your testing framework like you normally do, including the following environment variables:
thanks!

2023-07-05 17:17 UTC, kayayarai approved these changes

2023-07-05 17:30 UTC, merged