Fix DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED documentation
DataDog/documentation pull request #18812
Opened 2023-07-05 15:48 UTC by PerfectSlayer

### What does this PR do?

This PR fixes the documentation of `DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED` behavior.

### Motivation

The description is not compliant with the RFC nor the documentation.
The issue was brought to eng from support.

### Additional Notes

There is the same sentence for the Go Tracer. I don't know what the implementation status is or who to contact about it?

---

### Reviewer checklist
- [x] Review the changed files.
- [x] Review the URLs listed in the [Preview](#preview) section.
- [x] Check images for PII
- [x] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-05 21:09 UTC, rtrieu requested changes
Super minor suggestion but otherwise looks good!

2023-07-05 21:09 UTC, rtrieu commented on content/en/tracing/trace_collection/library_config/java.md
> +When true, the trace ID is printed as a full 128-bit ID in hexadecimal format, except if the ID itself is only 64 bits (then formatted as an integer).
```suggestion
When true, the trace ID is printed as a full 128-bit ID in hexadecimal format, except if the ID itself is only 64 bits (then it is formatted as an integer).
```

2023-07-06 06:21 UTC, PerfectSlayer commented
Thanks @rtrieu 🙏  I just applied it!

In the meantime, I am reaching Go team.

2023-07-06 16:27 UTC, PerfectSlayer commented
I also update the Go tracer documentation. The Go tracer team ensures the tracer behaves as expected [here](https://github.com/DataDog/dd-trace-go/pull/2101).

It should be ready for review / merge 👍

2023-07-06 21:41 UTC, rtrieu approved these changes
LGTM

2023-07-06 21:41 UTC, merged