Improve mobile logs documentation
DataDog/documentation pull request #18985
Opened 2023-07-17 07:23 UTC by xgouchet

### What does this PR do?

Add the missing React native logs collection page. Also: 

- Add the missing `AP1` code snippet for Android
- Make the client token paragraph more complete, we don't just do Browser monitoring...

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-17 08:01 UTC, 0xnm commented
I believe AP1 code snippet is not necessary, it is already a part of https://github.com/DataDog/documentation/pull/18936/files#diff-c76ab012c6a08b1d07d145a1e3bbac397ec386c322b628dacf5b326e871cd1deR237

2023-07-17 08:04 UTC, xgouchet commented
Good point @0xnm   I'll remove it ;)

2023-07-17 21:28 UTC, cswatt commented
Thanks for this! Added DOCS-5895 to review.

2023-07-28 18:00 UTC, rtrieu requested changes
Some small edits for style and formatting consistency.

2023-08-09 16:10 UTC, rtrieu approved these changes
Looks good, thanks!

2023-08-09 16:10 UTC, merged