Add CI Visibility custom metrics section to dotnet docs.
DataDog/documentation pull request #18993
Opened 2023-07-17 14:09 UTC by tonyredondo

### What does this PR do?
This PR adds a new section into the CI Visibility DotNet documentation to `Add custom metrics to tests`.

### Motivation
This section was missing.

### Additional Notes
This is a continuation of: https://github.com/DataDog/documentation/pull/18831

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-17 14:45 UTC, juan-fernandez commented on content/en/continuous_integration/tests/dotnet.md
> +To create filters or `group by` fields for these tags, you must first create facets. For more information about adding tags, see the [Adding Tags][7] section of the .NET custom instrumentation docume
```suggestion
To create filters or visualizations for these tags, you must first create facets. For more information about adding tags, see the [Adding Tags][7] section of the .NET custom instrumentation documentation.
```
I don't think you can group by a measure 

Also, here we should link to the guide here https://github.com/DataDog/documentation/pull/18831

2023-07-17 16:47 UTC, juan-fernandez commented on content/en/continuous_integration/tests/dotnet.md
> +To create filters or `group by` fields for these tags, you must first create facets. For more information about adding tags, see the [Adding Tags][7] section of the .NET custom instrumentation docume
https://github.com/DataDog/documentation/pull/18831 is merged, so you can link to the guide

2023-07-17 21:48 UTC, cswatt requested changes
looks good, but i don't think we need callouts or a bolded "note" — I think it's sufficient to just  have it as the first line of the section.

2023-07-17 21:48 UTC, cswatt commented on content/en/continuous_integration/tests/dotnet.md
> +</div>
```suggestion
To add custom tags to tests, configure [custom instrumentation](#custom-instrumentation) first.
```

2023-07-17 21:48 UTC, cswatt commented on content/en/continuous_integration/tests/dotnet.md
> +</div>
```suggestion
To add custom metrics to tests, configure [custom instrumentation](#custom-instrumentation) first.
```

2023-07-17 21:48 UTC, cswatt commented on content/en/continuous_integration/tests/dotnet.md
> +Read more about custom metrics in [Add Custom Metrics Guide][15].
```suggestion
Read more about custom metrics in the [Add Custom Metrics Guide][15].
```

2023-07-18 08:24 UTC, juan-fernandez approved these changes

2023-07-18 08:51 UTC, tonyredondo commented
We have to wait a dotnet tracer release before merging.

2023-07-25 15:57 UTC, tonyredondo commented
The release is out, we can merge this.

2023-07-25 16:48 UTC, rtrieu approved these changes
Looks great!

2023-07-25 16:50 UTC, merged