Update documentation for Android SDK v2
DataDog/documentation pull request #19062
Opened 2023-07-21 09:32 UTC by 0xnm

### What does this PR do?

This PR updates documentation for the features provided by the [Datadog Android SDK](https://github.com/DataDog/dd-sdk-android) in accordance with the changes made with upcoming SDK v2 release.

With SDK v2 we split the `dd-sdk-android` monolith into different parts:

* `dd-sdk-android-core` - core module, containing the code to handle common parts of SDK (data storage, data upload), etc.
* `dd-sdk-android-rum` - module containing RUM feature functionality
* `dd-sdk-android-logs` - module containing Logs feature functionality
* `dd-sdk-android-trace` - module containing Trace feature functionality
* `dd-sdk-android-webview` - module containing WebView Tracking functionality
* `dd-sdk-android-okhttp` - module containing OkHttp instrumentation functionality

This split allows to use and configure features independently.

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-21 09:56 UTC, xgouchet approved these changes

2023-07-21 16:43 UTC, rtrieu requested changes
Some suggestions for consistency with our style guide, but otherwise looks good!

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/android/integrated_libraries.md
> +If you use RxJava in your application, take a look at Datadog's [dedicated RxJava library][8].
```suggestion
If you use RxJava in your application, see Datadog's [dedicated RxJava library][8].
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/android/troubleshooting.md
> +If you've been using the SDK v1, there are some breaking changes introduced in version `2.0.0`. Check our [migration guide][1] to get more information.
```suggestion
If you've been using the SDK v1, there are some breaking changes introduced in version `2.0.0`. See the [migration guide][1] for more information.
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/android/web_view_tracking.md
> +1. If you want to forward RUM events coming from web page, download the [latest version][2] of RUM Android SDK and setup RUM feature following the [dedicated guide][3].
```suggestion
1. If you want to forward RUM events coming from web pages, download the [latest version][2] of RUM Android SDK and setup RUM feature following the [dedicated guide][3].
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/android/web_view_tracking.md
> +2. If you want to forward Log events coming from web page, download the [latest version][4] of Logs Android SDK and setup Logs feature following the [dedicated guide][5].
```suggestion
2. If you want to forward Log events coming from web pages, download the [latest version][4] of Logs Android SDK and setup Logs feature following the [dedicated guide][5].
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/android/web_view_tracking.md
> +4. Enable tracking for web view you want with the following code snippet:
```suggestion
4. Enable tracking for web views with the following code snippet:
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/android.md
> +| `site`                     | The Datadog site to upload your data to (US1, US3, US5, EU1, US1_FED or AP1).
```suggestion
| `site`                     | The Datadog site to upload your data to (US1, US3, US5, EU1, US1_FED, or AP1).                                                                                                                                       |
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/reactnative.md
> +In your `android/app/build.gradle` file, add the [latest version of plugin][15] and configure it **at the very top of the file**:
```suggestion
In your `android/app/build.gradle` file, add the [latest version of the plugin][15] and configure it **at the top of the file**:
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/android/integrated_libraries.md
> +If you use Picasso, let it use your `OkHttpClient` instrumented with Datadog SDK for RUM and APM information about network requests made by Picasso.
```suggestion
If you use Picasso, use it with the `OkHttpClient` that's been instrumented with Datadog SDK for RUM and APM information about network requests made by Picasso.
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/android/integrated_libraries.md
> +If you use Retrofit, let it use your `OkHttpClient` instrumented with Datadog SDK for RUM and APM information about network requests made with Retrofit.
```suggestion
If you use Retrofit, use it with the `OkHttpClient` that's been instrumented with Datadog SDK for RUM and APM information about network requests made with Retrofit.
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/android/integrated_libraries.md
> +If you use SQLDelight in your application, take a look at Datadog's [dedicated SQLDelight library][4].
```suggestion
If you use SQLDelight in your application, see Datadog's [dedicated SQLDelight library][4].
```

2023-07-21 16:43 UTC, rtrieu commented on content/en/real_user_monitoring/android/integrated_libraries.md
> +If you use Apollo, let it use your `OkHttpClient` instrumented with Datadog SDK for RUM and APM information about all the queries performed through Apollo client.
```suggestion
If you use Apollo, use it with the `OkHttpClient` that's been instrumented with Datadog SDK for RUM and APM information about all the queries performed through Apollo client.
```

2023-07-21 18:49 UTC, rtrieu approved these changes
Looks good!

2023-07-21 18:57 UTC, rtrieu requested changes
Sorry just noticed a few more things.

2023-07-21 18:57 UTC, rtrieu commented on content/en/real_user_monitoring/android/integrated_libraries.md
> +If you use Picasso, use it with the `OkHttpClient` that's been instrumented with Datadog SDK for RUM and APM information about network requests made by Picasso.
```suggestion
If you use Picasso, use it with the `OkHttpClient` that's been instrumented with the Datadog SDK for RUM and APM information about network requests made by Picasso.
```

2023-07-21 18:57 UTC, rtrieu commented on content/en/real_user_monitoring/android/integrated_libraries.md
> +If you use Retrofit, use it with the `OkHttpClient` that's been instrumented with Datadog SDK for RUM and APM information about network requests made with Retrofit.
```suggestion
If you use Retrofit, use it with the `OkHttpClient` that's been instrumented with the Datadog SDK for RUM and APM information about network requests made with Retrofit.
```

2023-07-21 18:57 UTC, rtrieu commented on content/en/real_user_monitoring/android/integrated_libraries.md
> +If you use Apollo, use it with the `OkHttpClient` that's been instrumented with Datadog SDK for RUM and APM information about all the queries performed through Apollo client.
```suggestion
If you use Apollo, use it with the `OkHttpClient` that's been instrumented with the Datadog SDK for RUM and APM information about all the queries performed through Apollo client.
```

2023-07-26 15:08 UTC, 0xnm commented
@rtrieu I've addressed your comments and also added 2 new commit with additional edits, can you please review this PR again?

2023-07-26 16:39 UTC, rtrieu approved these changes
LGTM

2023-07-26 16:40 UTC, rtrieu commented
@0xnm Let me know when this is ready to merge!

2023-07-31 15:56 UTC, merged