[RUM][Mobile] RUMM-2892 iOS SDK `2.0` Release
DataDog/documentation pull request #19061
Opened 2023-07-21 08:36 UTC by maxep

### What does this PR do?

Version `2.0` of the iOS SDK will introduced breaking changes to the public APIs. This PR reflects those changes in doc.

The impacted sections are:
- Logs
- Tracing
- RUM
- RUM/Error Tracking

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-21 18:53 UTC, rtrieu requested changes
Some suggestions for consistency with our style. I also pushed an update to close some unclosed tabs. Otherwise, looks good!

2023-07-24 17:37 UTC, rtrieu requested changes
Some very minor suggestions, but otherwise looks good!

2023-07-24 17:37 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/ios.md
> +| Yes | dSYM files are available after [App Store Connect][6] completes processing your application's build. |
```suggestion
| Yes | `.dSYM` files are available after [App Store Connect][6] completes processing your application's build. |
```

2023-07-24 17:37 UTC, rtrieu commented on content/en/real_user_monitoring/ios/web_view_tracking.md
> +To enable Crash Reporting, make sure to also enable [RUM][3] and, or [Logs][5]. Then, add the package according to your dependency manager and update your initialize snippet.
```suggestion
To enable Crash Reporting, make sure to also enable [RUM][3] and, or [Logs][5]. Then, add the package according to your dependency manager and update your initialization snippet.
```

2023-07-28 12:22 UTC, maxep commented
Hey @rtrieu 👋  Thank you so much for your reviews!
Can you give it a final look? We are planning on releasing on Monday 🙏

2023-07-31 07:28 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +	trackingConsent: .trackingConsent
```suggestion
	trackingConsent: trackingConsent
```

2023-07-31 07:29 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +						trackingConsent:trackingConsent];
```suggestion
[DDDatadog initializeWithConfiguration:configuration
                       trackingConsent:trackingConsent];
```

2023-07-31 07:30 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +		site: .eu1
wrong parameters order:
```suggestion
		site: .eu1,
		service: "<service name>"
```

2023-07-31 07:30 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +	trackingConsent: .trackingConsent
```suggestion
	trackingConsent: trackingConsent
```

2023-07-31 07:31 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +						trackingConsent:trackingConsent];
```suggestion
[DDDatadog initializeWithConfiguration:configuration
                       trackingConsent:trackingConsent];
```

2023-07-31 07:32 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +	trackingConsent: .trackingConsent
```suggestion
	trackingConsent: trackingConsent
```

2023-07-31 07:32 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +						trackingConsent:trackingConsent];
```suggestion
[DDDatadog initializeWithConfiguration:configuration
                       trackingConsent:trackingConsent];
```

2023-07-31 07:32 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +		site: .us5
wrong order:
```suggestion
		site: .us5,
		service: "<service name>"
```

2023-07-31 07:32 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +	trackingConsent: .trackingConsent
```suggestion
	trackingConsent: trackingConsent
```

2023-07-31 07:38 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +		site: .us1_fed
```suggestion
		site: .us1_fed,
		service: "<service name>"
```

2023-07-31 07:38 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +	trackingConsent: .trackingConsent
```suggestion
	trackingConsent: trackingConsent
```

2023-07-31 07:39 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +						trackingConsent:trackingConsent];
```suggestion
[DDDatadog initializeWithConfiguration:configuration
                       trackingConsent:trackingConsent];
```

2023-07-31 07:42 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +						trackingConsent:trackingConsent];
```suggestion
[DDDatadog initializeWithConfiguration:configuration
                       trackingConsent:trackingConsent];
```

2023-07-31 07:42 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +		site: .ap1
```suggestion
		site: .ap1,
		service: "<service name>"
```

2023-07-31 07:43 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +	trackingConsent: .trackingConsent
```suggestion
	trackingConsent: trackingConsent
```

2023-07-31 07:43 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +						trackingConsent:trackingConsent];
```suggestion
[DDDatadog initializeWithConfiguration:configuration
                       trackingConsent:trackingConsent];
```

2023-07-31 07:45 UTC, ncreated commented on content/en/logs/log_collection/ios.md
> +
This shouldn't be there, no?
```suggestion
```

2023-07-31 07:46 UTC, ncreated commented on content/en/logs/log_collection/ios.md
>  The following methods in `Logger.Builder` can be used when initializing the logger to send logs to Datadog:
```suggestion
The following methods in `Logger.Configuration` can be used when initializing the logger to send logs to Datadog:
```

2023-07-31 07:48 UTC, ncreated commented on content/en/real_user_monitoring/error_tracking/ios.md
> +  trackingConsent: .trackingConsent
```suggestion
  trackingConsent: trackingConsent
```

2023-07-31 07:48 UTC, ncreated commented on content/en/real_user_monitoring/error_tracking/ios.md
> +Depending on your setup, you may need to download .`dSYM` files from App Store Connect or find them on your local machine.
```suggestion
Depending on your setup, you may need to download `.dSYM` files from App Store Connect or find them on your local machine. 
```

2023-07-31 07:49 UTC, ncreated commented on content/en/real_user_monitoring/ios/_index.md
> +  trackingConsent: .trackingConsent
```suggestion
  trackingConsent: trackingConsent
```

2023-07-31 07:49 UTC, ncreated commented on content/en/real_user_monitoring/ios/_index.md
> +    site: .eu1
```suggestion
    site: .eu1,
    service: "<service name>"
```

2023-07-31 07:50 UTC, ncreated commented on content/en/real_user_monitoring/ios/_index.md
> +    site: .us3
```suggestion
    site: .us3,
    service: "<service name>"
```

2023-07-31 07:50 UTC, ncreated commented on content/en/real_user_monitoring/ios/_index.md
> +  trackingConsent: .trackingConsent
```suggestion
  trackingConsent: trackingConsent
```

2023-07-31 07:50 UTC, ncreated commented on content/en/real_user_monitoring/ios/_index.md
> +  trackingConsent: .trackingConsent
```suggestion
  trackingConsent: trackingConsent
```

2023-07-31 07:55 UTC, ncreated requested changes
For all SDK init snippets:
- make sure `site:` comes before `service:` everywhere
- make sure we use valid `trackingConsent` variable name (no dot prefix)

2023-07-31 08:08 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +To manually register instantaneous RUM actions such as `.tap` on `RUMMonitor.shared()`, use `.addUserAction(type:name:)`. For continuous RUM actions such as `.scroll`, use `.startUserAction(type:name
Ref.: _breaking changes_ in https://github.com/DataDog/dd-sdk-ios/pull/1310
```suggestion
To manually register instantaneous RUM actions such as `.tap` on `RUMMonitor.shared()`, use `.addAction(type:name:)`. For continuous RUM actions such as `.scroll`, use `.startAction(type:name:)` or `.stopAction(type:)`.
```

2023-07-31 08:09 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +    rum.addUserAction(
```suggestion
    rum.addAction(
```

2023-07-31 08:11 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
>  In addition to [tracking actions automatically](#automatically-track-user-actions), you can track specific custom user actions (taps, clicks, and scrolls) with the `addUserAction(type:name:)` API.
```suggestion
In addition to [tracking actions automatically](#automatically-track-user-actions), you can track specific custom user actions (taps, clicks, and scrolls) with the `addAction(type:name:)` API. 
```

2023-07-31 08:13 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
>  - `.stopResourceLoading(resourceKey:response:)`
Here and more in other snippets:
> resource tracking APIs are renamed - we no longer use word "Loading":
> - startResourceLoading() → startResource()
> - stopResourceLoading() → stopResource()
> - stopResourceLoadingWithError() → stopResourceWithError()

Ref. _breaking changes_ from https://github.com/DataDog/dd-sdk-ios/pull/1310

2023-07-31 08:14 UTC, maxep commented on content/en/logs/log_collection/ios.md
> +
nop, indeed!

2023-07-31 08:15 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +You can use the following properties in `Datadog.Configuration` when creating the Datadog configuration to initialize the library:
```suggestion
You can use the following properties in `RUM.Configuration` when creating the Datadog configuration to initialize the library:
```

2023-07-31 08:17 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +  trackingConsent: .trackingConsent
```suggestion
  trackingConsent: trackingConsent
```

2023-07-31 08:18 UTC, ncreated commented on content/en/tracing/trace_collection/dd_libraries/ios.md
> +        site: .eu1
In tracing too - `site` always before `service` otherwise it won't copile.

2023-07-31 08:19 UTC, ncreated commented on content/en/tracing/trace_collection/dd_libraries/ios.md
> +    trackingConsent: .trackingConsent
Same patter in whole file:
```suggestion
    trackingConsent: trackingConsent
```

2023-07-31 09:27 UTC, ncreated requested changes

2023-07-31 09:27 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +- `.stopResourceWithError(resourceKey:errorMessage:)`
```suggestion
- `.stopResourceWithError(resourceKey:message:)`
```
Ref.: https://github.com/DataDog/dd-sdk-ios/pull/1310
> `errorMessage` parameter in `stopResourceWithError()` was renamed to `message` - for simplicity

2023-07-31 09:27 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +rum.startResourceLoading(
```suggestion
rum.startResource(
```
Ref.: https://github.com/DataDog/dd-sdk-ios/pull/1310
> resource tracking APIs are renamed - we no longer use word "Loading":
> - `startResourceLoading()` → `startResource()`
> - `stopResourceLoading()` → `stopResource()`
> - `stopResourceLoadingWithError()` → `stopResourceWithError()`
> this is to align with `dd-sdk-android` where we never used "Loading" phrase

2023-07-31 09:27 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +rum.stopResourceLoading(
```suggestion
rum.stopResource(
```

2023-07-31 09:27 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +                                                attributes:@{}];
```suggestion
[[DDRUMMonitor shared] startResourceWithResourceKey:@"resource-key"
                                            request:request
                                         attributes:@{}];
```

2023-07-31 09:27 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +                                               attributes:@{}];
```suggestion
[[DDRUMMonitor shared] stopResourceWithResourceKey:@"resource-key"
                                          response:response
                                        attributes:@{}];
```

2023-07-31 09:27 UTC, ncreated commented on content/en/real_user_monitoring/ios/advanced_configuration.md
> +: Enables tracking user interactions (taps) as RUM actions. You can use the default implementation of `predicate` by setting the `DefaultUIKitRUMActionsPredicate` or implement [your own `UIKitRUMUser
```suggestion
: Enables tracking user interactions (taps) as RUM actions. You can use the default implementation of `predicate` by setting the `DefaultUIKitRUMActionsPredicate` or implement [your own `UIKitRUMActionsPredicate`](#automatically-track-user-actions) customized for your app.
```

2023-07-31 09:31 UTC, ncreated approved these changes
🏅

2023-07-31 15:57 UTC, merged