[STAT-430] update other section
DataDog/documentation pull request #19099
Opened 2023-07-25 02:02 UTC by dastrong

### What does this PR do?

Updates the Other section onboarding to use our new static analyzer versus our old one.

### Motivation

Transitioning our suggestions from our old to new static analyzer now.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-25 10:21 UTC, juli1 requested changes

2023-07-25 10:21 UTC, juli1 commented on content/en/continuous_integration/static_analysis/_index.md
>  Add the following to your CI pipeline:
We should add a note that the following script works for `x86_64` on Linux. We should list all the architecture available and their link to to the latest download.

2023-07-25 10:21 UTC, juli1 commented on content/en/continuous_integration/static_analysis/_index.md
> +/tmp/datadog-static-analyzer -i . -o /tmp/report.sarif -f sarif --cpus <cpu_count>
No eed to specify the cpu count here.

2023-07-25 16:49 UTC, juli1 requested changes

2023-07-25 16:49 UTC, juli1 commented on content/en/continuous_integration/static_analysis/_index.md
> +| `x86_64`     | `Windows` | `datadog-static-analyzer-x86_64-unknown-linux-gnu.zip`  |
@dastrong let's also have a link to the latest

2023-07-25 19:06 UTC, juli1 commented on content/en/continuous_integration/static_analysis/_index.md
> +| `x86_64`     | `Windows` | `datadog-static-analyzer-x86_64-unknown-linux-gnu.zip`  |
The user should not have to guess the link themselves. We should give the links to them.

Just have a fourth column with a link to the download.

Example of link: `https://github.com/DataDog/datadog-static-analyzer/releases/latest/download/datadog-static-analyzer-x86_64-unknown-linux-gnu.zip` - just replace `datadog-static-analyzer-x86_64-unknown-linux-gnu.zip`. It gives a link to the latest release if people want to integrate it in their CI.

2023-07-25 19:29 UTC, rtrieu approved these changes
LGTM. Please let us know via requesting re-review or in #documentation when you are ready to merge this!

2023-07-26 16:04 UTC, dastrong commented
@rtrieu it's ready to go now

2023-07-26 16:37 UTC, merged