Update generic_actions.md to seperate Logic Actions from Generic actions
DataDog/documentation pull request #19097
Opened 2023-07-24 23:42 UTC by sarjyusuf

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-25 18:24 UTC, rtrieu requested changes
Minor feedback, but otherwise looks good!

2023-07-25 18:24 UTC, rtrieu commented on content/en/service_management/workflows/actions_catalog/generic_actions.md
> +Generic actions are workflow actions which are not associated with a tool or integration. This allows you to overcome any action that may not be currently present in the Actions catalog.
```suggestion
Generic actions are workflow actions that are not associated with a tool or integration. They allow you to overcome any action that may not be currently present in the Actions catalog. 
```

2023-07-27 22:31 UTC, hestonhoffman commented on content/en/service_management/workflows/actions_catalog/generic_actions.md
> +You can also [request for a new action or entire integration][5].
```suggestion
Generic actions are workflow actions that are not associated with a tool or integration. They allow you to overcome any action that may not be currently present in the Actions catalog.

As with all workflow actions, you can use the [context variables][1] tab to access any values available in the workflow context.

You can also [request a new action or entire integration][5].
```

2023-07-27 23:03 UTC, rtrieu approved these changes
Looks good!

2023-07-28 20:37 UTC, hestonhoffman approved these changes

2023-07-28 20:37 UTC, merged