New change alert monitor guide
DataDog/documentation pull request #19114
Opened 2023-07-25 19:25 UTC by estherk15

### What does this PR do?
  - Add new file for change alert guide
  - Add new file to the guide index
  - Add change alert example images

### Motivation
[DOCS-5683](https://datadoghq.atlassian.net/browse/DOCS-5683)

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-08-01 22:17 UTC, buraizu requested changes
Nice work! This review fills in a bit of missing alt text and other minor punctuation details, but I also suggested some alternate phrasing in a couple of places. I'm open to iterating on any of those parts further if you have better suggestions.
Also, just wanted to confirm if it's intentional to include the `change_alert_define_the_metric_options.png` image, as it doesn't seem to be used in the doc.

2023-08-01 22:17 UTC, buraizu commented on content/en/monitors/guide/change-alert.md
> +Change alerts can be mistaken to be false positives. You can reconstruct the metric queries with Notebooks to verify the results of your monitor evaluation.
```suggestion
If you suspect that your change alert evaluation is a false positive, you can reconstruct the metric queries with a Notebook to verify the results. 
```

2023-08-01 22:17 UTC, buraizu commented on content/en/monitors/guide/_index.md
> +    {{< nextlink href="monitors/guide/change-alert" >}}Change Alert monitors{{< /nextlink >}}
Optional suggestion here, but I think grouping this with the `Anomaly monitors` entry makes slightly more sense for organization

2023-08-02 20:03 UTC, estherk15 commented
@buraizu Thanks so much for the review and catching the unused image!

2023-08-03 21:56 UTC, buraizu approved these changes
@estherk15 thanks, LGTM!

2023-08-03 23:36 UTC, merged