Add cws runtime anomaly detection docs
DataDog/documentation pull request #19178
Opened 2023-07-28 13:49 UTC by DominicBurkart

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-28 14:47 UTC, DominicBurkart commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +- make new DNS resolutions (e.g. to exfiltrate data).
NIT from contributing: https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md

```suggestion
- make new DNS resolutions (such as to exfiltrate data).
```

2023-07-28 14:50 UTC, DominicBurkart commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +Notifications can be used to alert you via slack or email when anomaly signals are generated. They can also be used to trigger webhooks or Datadog Workflows, enabling automated remediation pipelines.
```suggestion
Notifications can be used to alert you via slack or email when anomaly signals are generated. They can also be used to trigger webhooks or Datadog Workflows, enabling automated remediation pipelines. This is done with [Security Notification Rules][3]. To specifically target anomaly signals in a notification rule, use the rule criteria `rule_id:anomaly_detection`.
```

2023-07-28 14:51 UTC, DominicBurkart commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +Runtime Anomaly Detection provides out of the box detection of unusual behavior on your _containerized_ workloads, using a model based on [CWS Security Profiles][6].
```suggestion
Runtime Anomaly Detection provides out of the box detection of unusual behavior on your containerized workloads, using a model based on [CWS Security Profiles][6].
```

2023-07-31 18:29 UTC, drichards-87 requested changes
Left you feedback from Docs. Do you want this article to appear in the left-nav Table of Contents? Currently, it isn't displayed there. If you'd like, I can pull the branch and add it to the left-nav.

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/setup.md
> +**Optional, to enable Runtime Anomaly Detection** add the following field to the `system-probe.yaml` file:
```suggestion
**Optional**: To enable Runtime Anomaly Detection, add the following to the `system-probe.yaml` file:
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/setup.md
> +    **Optional, to enable Runtime Anomaly Detection** add the following field to the `values.yaml` file:
```suggestion
    **Optional** To enable Runtime Anomaly Detection, add the following to the `values.yaml` file:
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/setup.md
> +    **Optional, to enable Runtime Anomaly Detection** add the following field to the `values.yaml` file:
```suggestion
    **Optional**: To enable Runtime Anomaly Detection, add the following to the `values.yaml` file:
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +To exclusively show Audit Logs generated by actions taken in Cloud Security Management:
```suggestion
To view audit logs generated by actions taken in Cloud Security Management, navigate to **Organization Settings** > **Compliance** > **Audit Trail** and do one of the following:
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +- or select the “Cloud Security Platform” facet under the “Event Name” facet.
```suggestion
- Create the following query: `@evt.name:"Cloud Security Platform"`
- In the **Event Name** facet, select **Cloud Security Platform**.
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +To exclusively show Audit Logs generated by actions taken on security signals:
```suggestion
To view audit logs generated by actions taken on security signals:
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +- or select the “security_signal” facet under the “Asset Type” facet.
```suggestion
- Create the following query: `@asset.type:security_signal`
- In the **Asset Type** facet, select **security_signal**..
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +As an administrator or security team member, you can use [Datadog Audit Trail][5] to see what actions your team is taking within the Cloud Security Product. As an individual, you can see a stream of
```suggestion
As an administrator or security team member, you can use [Datadog Audit Trail][5] to see what actions your team is taking in Cloud Security Management. As an individual, you can see a stream of your own actions. Audit trails for security signals are provided without additional configuration.
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +### Navigate to Organization Settings and select Audit Trail under Compliance.
```suggestion
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +Notifications can be used to alert you via slack or email when anomaly signals are generated. They can also be used to trigger webhooks or Datadog Workflows, enabling automated remediation pipelines.
```suggestion
You can set up [security notification rules][3] to alert you via Slack or email when anomaly signals are generated. Notifications can also be used to trigger webhooks or Datadog Workflows, enabling automated remediation pipelines. To target anomaly signals in a notification rule, use the rule criteria `rule_id:anomaly_detection`.
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +## Notifications
```suggestion
## Set up real-time notifications
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +## Inspect a Runtime Anomaly Signal
```suggestion
## Inspect runtime anomaly signals
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +- Runtime Anomaly Detection enabled: review [CWS setup instructions][2] to learn how to enable it.
```suggestion
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +Once Runtime Anomaly Detection is activated, CWS agents start recording the normal behavior of your containerized workloads: commands run, file accesses, and DNS resolutions. This behavior is aggrega
```suggestion
Once you activate Runtime Anomaly Detection, the CWS Agents start recording the normal behavior of your containerized workloads. This includes commands run, files accessed, and DNS resolutions. This behavior is aggregated across all running containers with the same short image name and stored as Security Profiles.
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +After a learning period, your agents can begin detecting anomalies. The learning duration varies depending on the workload’s activity, by default taking between 48 and 120 hours.
```suggestion
After a learning period, your Agents can begin detecting anomalies. The learning duration varies depending on the workload’s activity, by default taking between 48 and 120 hours.
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +As soon as the learning period is over, the agent begins evaluating new anomalous behavior and sending anomaly events to Datadog. Datadog’s platform aggregates these events by container and confirms
```suggestion
As soon as the learning period is over, the Agent begins evaluating new anomalous behavior and sending anomaly events to Datadog. Datadog’s platform aggregates these events by container and confirms that the anomalous behavior is not present in the Security Profile.
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +If the behavior is not known in the profile, then the event (or events) are then surfaced as Security Signals. Signals are updated dynamically based on any newly detected anomalous behavior in the sa
```suggestion
If the behavior is not present in the security profile, the events are then surfaced as security signals. Signals are updated dynamically based on any newly detected anomalous behavior in the same container.
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +*For more information about investigating Security Signals, see the Security [Signals Explorer docs][4].*
```suggestion
```

2023-07-31 18:29 UTC, drichards-87 commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +- Suggested Next Steps provides essential pivots into Datadog observability tools such as Infrastructure Monitoring, access to the Security Profile to review known behavior for the service, and links
```suggestion
The Overview tab on Anomaly Detection Security Signals have three main sections, visible here:

{{< img src="security/cws/security_profiles/runtime-anomaly-detection-signal-sidepanel.png" alt="A CWS runtime anomaly detection signal with three parts described below." width="50%">}}

- The **What Happened** section explains which container was impacted and describes how to evaluate the signal.
- **Suggested Next Steps** provides essential pivots into Datadog observability tools such as Infrastructure Monitoring, access to the Security Profile to review known behavior for the service, and links to escalate the workflow using Case Management or Incidents, along with any custom-defined workflows. If the signal is benign, you can add it to the Security Profile of the workload to mark it as normal activity and avoid generating signals if the same behavior is observed again.
```

2023-08-01 16:49 UTC, DominicBurkart commented on content/en/security/cloud_workload_security/runtime_anomaly_detection.md
> +- Runtime Anomaly Detection enabled: review [CWS setup instructions][2] to learn how to enable it.
We need for them to add a config value. We can delete the "CWS enabled" section though!

2023-08-01 16:52 UTC, DominicBurkart commented
@drichards-87 please do; this has already been approved by the CWS eng team and shared with our PMs, so feel free to merge this ASAP at your disgression.

2023-08-01 17:38 UTC, drichards-87 approved these changes

2023-08-01 17:39 UTC, merged