Mobile Application Testing Banner Updates
DataDog/documentation pull request #19205
Opened 2023-07-31 20:26 UTC by alai97

### What does this PR do?

Update beta banners + add site region specificity.

### Motivation

Chat with Mike on Slack, ready to merge.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-07-31 21:56 UTC, michaelperalta submitted a review, later dismissed

2023-07-31 21:56 UTC, michaelperalta commented on content/en/mobile_app_testing/_index.md
> +  Mobile Application Testing is in limited availability.
Can we update this to include a note about it being in US1 only so customers don't have to switch the Datadog site to see that? 

Something like:

Mobile Application Testing is in Limited Availability for customers using the US1 site only.

2023-07-31 22:00 UTC, rtrieu requested changes
This could be a personal preference but I referenced phrasing we've used before in our docs that is slightly more concise.

2023-07-31 22:05 UTC, rtrieu approved these changes
Looks good!

2023-08-02 22:23 UTC, kayayarai reviewed
Suggesting giving the user some context about why it's not supported when we show the site region message.

2023-08-02 22:23 UTC, kayayarai commented on content/en/mobile_app_testing/_index.md
> +<div class="alert alert-warning">Mobile Application Testing is not supported.</div>
```suggestion
<div class="alert alert-warning">Mobile Application Testing is not supported on this site.</div>
```

2023-08-02 22:23 UTC, kayayarai commented on content/en/mobile_app_testing/mobile_app_tests/_index.md
> +<div class="alert alert-warning">Mobile Application Testing is not supported.</div>
```suggestion
<div class="alert alert-warning">Mobile Application Testing is not supported on this site.</div>
```

2023-08-02 22:23 UTC, kayayarai commented on content/en/mobile_app_testing/mobile_app_tests/advanced_options.md
> +<div class="alert alert-warning">Mobile Application Testing is not supported.</div>
```suggestion
<div class="alert alert-warning">Mobile Application Testing is not supported on this site.</div>
```

2023-08-02 22:23 UTC, kayayarai commented on content/en/mobile_app_testing/mobile_app_tests/results.md
> +<div class="alert alert-warning">Mobile Application Testing is not supported.</div>
```suggestion
<div class="alert alert-warning">Mobile Application Testing is not supported on this site.</div>
```

2023-08-02 22:23 UTC, kayayarai commented on content/en/mobile_app_testing/mobile_app_tests/steps.md
> +<div class="alert alert-warning">Mobile Application Testing is not supported.</div>
```suggestion
<div class="alert alert-warning">Mobile Application Testing is not supported on this site.</div>
```

2023-08-02 22:23 UTC, kayayarai commented on content/en/mobile_app_testing/settings/_index.md
> +<div class="alert alert-warning">Mobile Application Testing is not supported.</div>
```suggestion
<div class="alert alert-warning">Mobile Application Testing is not supported on this site.</div>
```

2023-08-02 22:52 UTC, merged