Update orchestrion references in Cloud Run and Container App docs
DataDog/documentation pull request #19212
Opened 2023-08-01 05:16 UTC by Danny-Driscoll

Switching back to a manual tracer sample, and label Orchestrion information as private beta

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-08-01 21:49 UTC, rtrieu requested changes
Some feedback on grammar and formatting, but otherwise looks good!

2023-08-01 21:49 UTC, rtrieu commented on content/en/serverless/azure_container_apps/_index.md
> +2. Change the entrypoint to wrap your application into the Datadog `serverless-init` process
```suggestion
2. Change the entrypoint to wrap your application into the Datadog `serverless-init` process.
```

2023-08-01 21:49 UTC, rtrieu commented on content/en/serverless/azure_container_apps/_index.md
> +**Note**: [Orchestrion][2] is a tool for automatically instrumentation of Go code, which is currently in Private Beta. With Orchestrion, it is possible to instrument your Go applications via Dockerfi
```suggestion
**Note**: [Orchestrion][2] is a tool for automatically instrumenting Go code, which is currently in Private Beta. With Orchestrion, it is possible to instrument your Go applications through Dockerfile. If you are interested in participating in the Beta or providing feedback on Orchestrion, please open a Github issue or reach out to support. 
```

2023-08-01 21:49 UTC, rtrieu commented on content/en/serverless/google_cloud_run/_index.md
> +[Manually install][1] the Go tracer before you deploy your application. Add the following instructions and arguments to your Dockerfile.
```suggestion
[Manually install][1] the Go tracer before you deploy your application. Add the following instructions and arguments to your Dockerfile:
```

2023-08-01 21:49 UTC, rtrieu commented on content/en/serverless/google_cloud_run/_index.md
> +2. Change the entrypoint to wrap your application into the Datadog `serverless-init` process
```suggestion
2. Change the entrypoint to wrap your application into the Datadog `serverless-init` process:
```

2023-08-01 21:49 UTC, rtrieu commented on content/en/serverless/google_cloud_run/_index.md
> +**Note**: [Orchestrion][2] is a tool for automatically instrumentation of Go code, which is currently in Private Beta. With Orchestrion, it is possible to instrument your Go applications via Dockerfi
```suggestion
**Note**: [Orchestrion][2] is a tool for automatically instrumenting Go code, which is currently in Private Beta. With Orchestrion, it is possible to instrument your Go applications through Dockerfile. If you are interested in participating in the Beta or providing feedback on Orchestrion, please open a Github issue or reach out to support. 
```

2023-08-02 23:10 UTC, Danny-Driscoll commented
Thanks @rtrieu, I added one more set of changes to add a callout note to the PR after committing your suggestions

2023-08-02 23:15 UTC, rtrieu approved these changes
LGTM

2023-08-03 15:29 UTC, merged