Update OTel runtime metrics documentation
DataDog/documentation pull request #19247
Opened 2023-08-03 18:14 UTC by liustanley

### What does this PR do?

- Updates Java runtime metric mapping
- Adds important notes to .NET documentation

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-08-03 19:57 UTC, drichards-87 requested changes
Left you two very minor bits of feedback from Docs.

2023-08-03 19:57 UTC, drichards-87 commented on content/en/opentelemetry/runtime_metrics/dotnet.md
> +- Minimum .NET OTel SDK version of [1.5.0][6]
```suggestion
- Minimum .NET OTel SDK version of [1.5.0][6].
```

2023-08-03 19:57 UTC, drichards-87 commented on content/en/opentelemetry/runtime_metrics/dotnet.md
> +The default metric export interval for the .NET OTel SDK is different from the default for the Datadog .NET SDK. We recommend setting the [OTEL_METRIC_EXPORT_INTERVAL][7] environment variable on your
```suggestion
The default metric export interval for the .NET OTel SDK is different from the default for the Datadog .NET SDK. Datadog recommends setting the [OTEL_METRIC_EXPORT_INTERVAL][7] environment variable on your .NET service to match the default Datadog metric export interval for viewing integration metric graphs:
```

2023-08-03 20:44 UTC, drichards-87 approved these changes

2023-08-03 20:44 UTC, drichards-87 commented
@liustanley Is this ready to be merged?

2023-08-04 15:21 UTC, liustanley commented
@drichards-87 I think we can hold off until Agent 7.48.0 gets released, this is the PR with the change: https://github.com/DataDog/datadog-agent/pull/18587

2023-08-21 15:19 UTC, drichards-87 commented
Hi @liustanley. Do you still need me to merge this?

2023-08-23 17:47 UTC, liustanley commented
@drichards-87 Yes but we're still waiting for Agent 7.48.0 to be released, which is targeted for mid September

2023-10-10 17:24 UTC, liustanley commented
@drichards-87 Agent 7.48.0 was just released, could you merge this PR?

2023-10-10 18:07 UTC, merged