Update Kubernetes resource utilization known limitations
DataDog/documentation pull request #19333
Opened 2023-08-10 13:56 UTC by xlucas

### What does this PR do?

### Motivation

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-08-10 14:31 UTC, drichards-87 requested changes
Left you one small bit of feedback for the paragraph above the one you added. Let me know when this is ready to be merged. Thanks!

2023-08-10 14:31 UTC, drichards-87 commented on content/en/infrastructure/containers/kubernetes_resource_utilization.md
>  Metrics are not displayed for groups containing at least one pod with container(s) that do not set requests or limits, as Datadog cannot infer the usage percentage without them. These groups without
```suggestion
Metrics are not displayed for groups containing at least one pod with containers that do not set requests or limits, as Datadog cannot infer the usage percentage without them. These groups without metrics appear last, regardless of the sorting order.
```

2023-08-11 12:35 UTC, kangyili approved these changes

2023-08-11 12:54 UTC, xlucas commented
@drichards-87 thanks, it's ready to be merged

2023-08-11 14:08 UTC, merged