Update troubleshooting doc
DataDog/documentation pull request #19340
Opened 2023-08-10 18:35 UTC by kimi-p

Add two more points for troubleshooting

2023-08-14 15:56 UTC, hestonhoffman commented on content/en/serverless/step_functions/troubleshooting.md
> +## I can only see `aws.stepfunctions` root span but cannot see any step spans
```suggestion
## I can see the `aws.stepfunctions` root span but I cannot see any step spans
```

2023-08-14 15:56 UTC, hestonhoffman commented on content/en/serverless/step_functions/troubleshooting.md
> +Please enable `Include execution data` option on the state machine's logging. By enabling this option, log execution input, data passed between states, and execution output will be logged in the logs
```suggestion
Please enable the `Include execution data` option on the state machine's logging. After enabling this option, log execution input, data passed between states, and execution output is logged. The Datadog backend uses the logs to construct these step spans for you.
```

2023-08-14 15:56 UTC, hestonhoffman commented on content/en/serverless/step_functions/troubleshooting.md
> +- For actions, we support basic actions of Lambda and DynamoDB, e.g. Lambda Invoke, DynamoDB GetItem, DynamoDB PutItem, DynamoDB UpdateItem... etc.
```suggestion
- For actions, we support basic actions of Lambda and DynamoDB. For example, Lambda Invoke, DynamoDB GetItem, DynamoDB PutItem, DynamoDB UpdateItem and more.
```

2023-08-14 17:17 UTC, sumedham requested changes

2023-08-14 17:17 UTC, sumedham commented on content/en/serverless/step_functions/troubleshooting.md
> +- For different flows, we do not support `Wait`, `Choice`, `Map`, `Success`, `Fail`, and `Pass`. For `Parrallel` flow, you would be able to see parallel executing spans stacking on top of each other,
```suggestion
- For different flows, we do not support `Wait`, `Choice`, `Map`, `Success`, `Fail`, and `Pass`. For `Parallel` flow, you would be able to see parallel executing spans stacking on top of each other, but there will be no `Parallel` spans showing on the flame graph.
```

2023-08-14 17:17 UTC, sumedham approved these changes

2023-08-15 15:00 UTC, kimi-p commented
@hestonhoffman This is ready to be merged. Could you merge it for me? Thank you!

2023-08-15 15:02 UTC, hestonhoffman approved these changes

2023-08-15 15:02 UTC, merged