Update environment-variables
DataDog/documentation pull request #19344
Opened 2023-08-11 03:45 UTC by ian28223

### What does this PR do?
Fix some 404 and document https://github.com/DataDog/datadog-agent/pull/16017

### Motivation
- document new feature

### Additional Notes
- No translated version of this change for for ES, FR, and JA

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-08-11 15:11 UTC, brett0000FF requested changes
Thanks for this content! I left a couple small suggestions.

2023-08-11 15:11 UTC, brett0000FF commented on content/en/agent/guide/environment-variables.md
> +In Operating Systems that uses SystemD to manage services, environment variables - global (e.g. `/etc/environment`) or session-based (e.g. `export VAR=value`) - are not generally made available to se
```suggestion
In operating systems that uses systemd to manage services, environment variables—global (for example, `/etc/environment`) or session-based (for example, `export VAR=value`)—are not generally made available to services unless configured to do so. See [systemd Exec manual page][8] for more details.
```

2023-08-11 15:11 UTC, brett0000FF commented on content/en/agent/guide/environment-variables.md
> +From Datadog Agent 7.45,the Datadog Agent service (`datadog-agent.service` unit) can optionally load environment variables assignments from a file (`<ETC_DIR>/environment`).
```suggestion
From Datadog Agent 7.45, the Datadog Agent service (`datadog-agent.service` unit) can optionally load environment variables assignments from a file (`<ETC_DIR>/environment`).
```

2023-08-11 15:11 UTC, brett0000FF commented on content/en/agent/guide/environment-variables.md
> +- Create `/etc/datadog-agent/environment` if it does not exist.
```suggestion
1. Create `/etc/datadog-agent/environment` if it does not exist.
```

2023-08-11 15:11 UTC, brett0000FF commented on content/en/agent/guide/environment-variables.md
> +- Define newline-separated environment variable assignments. Example:
```suggestion
2. Define newline-separated environment variable assignments. Example:
```

2023-08-11 15:11 UTC, brett0000FF commented on content/en/agent/guide/environment-variables.md
> +- Restart the service for changes to take effect
```suggestion
3. Restart the service for changes to take effect
```

2023-08-14 15:03 UTC, brett0000FF approved these changes
Looks good! Let me know if you need me to merge for you.

2023-08-14 17:18 UTC, ian28223 commented
> Looks good! Let me know if you need me to merge for you.

Yes, please; I'm not authorised to merge. 
 Much appreciated!

2023-08-22 15:33 UTC, merged