Create first draft of suspect commit documentation
DataDog/documentation pull request #19529
Opened 2023-08-28 18:47 UTC by jhgilbert

### What does this PR do?
Adds documentation on Error Tracking > Suspect Commits.

### Motivation
DOCS-6806

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2023-08-28 19:04 UTC, jhgilbert commented
Hi @AyushK1, interested in your thoughts on this draft of Suspect Commits documentation. I kept it simple, so let me know if you want more detail anywhere. When you're happy with it, I'll also add it to the other Error Tracking sections of the docs.

🔴 Also want to flag that I guessed at which GitHub integration permissions were needed, since the Confluence doc just said "correct permissions". If more permissions are needed, I can add those.

2023-11-29 21:12 UTC, meghanlo reviewed
a couple of nits

2023-11-29 21:12 UTC, meghanlo commented on content/en/logs/error_tracking/suspect_commits.md
> +For some issues, Error Tracking can identify a suspect commit, helping you determine the root cause and resolve the issue. This feature is automatically enabled when its [setup requirements](#setup)
```suggestion
Error Tracking can identify a suspect commits, helping you pinpoint the root cause of your errors and resolve issue faster. This feature is automatically enabled on issues when the [setup requirements](#setup) are met.
```

2023-11-29 21:12 UTC, meghanlo commented on content/en/logs/error_tracking/suspect_commits.md
> +If a suspect commit is associated with an issue, it is displayed on the issue panel, as shown in the highlighted area of the image below.
```suggestion
Once a suspect commit has been identified, it is displayed on the issue panel as shown in the highlighted area of the image below.
```

2023-12-22 19:00 UTC, aliciascott requested changes
Looks good just a few small suggestions! Let me know if you need a re-review :)

2024-01-02 17:08 UTC, meghanlo approved these changes

2024-01-03 17:53 UTC, aliciascott approved these changes
looks good!

2024-01-03 23:20 UTC, merged