Add allowFallbackToLocalStorage init parameter
DataDog/documentation pull request #19642
Opened 2023-09-07 08:10 UTC by yannickadam

### What does this PR do?
Add `allowFallbackToLocalStorage` RUM browser SDK  init parameter.

### Motivation
This parameter has been recently added to the browser SDK. 

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.
- [ ] Check that `cache_enabled` is set to `true` in the `pull_config_preview.yaml` file

2023-09-07 18:23 UTC, rtrieu commented on content/en/real_user_monitoring/browser/_index.md
> +Allows to use Local Storage when cookies cannot be set. This enables the RUM Browser SDK to run in environments that do not provide cookie support. See [Monitor Electron Applications Using the Browse
```suggestion
Allows the use of Local Storage when cookies cannot be set. This enables the RUM Browser SDK to run in environments that do not provide cookie support. See [Monitor Electron Applications Using the Browser SDK][23] for a typical use-case.
```

2023-09-07 18:23 UTC, rtrieu requested changes
Minor change requested, but otherwise looks good!

2023-09-08 08:01 UTC, bcaudan approved these changes

2023-09-11 07:41 UTC, yannickadam commented on content/en/real_user_monitoring/browser/_index.md
> +Allows to use Local Storage when cookies cannot be set. This enables the RUM Browser SDK to run in environments that do not provide cookie support. See [Monitor Electron Applications Using the Browse
👍

2023-09-11 15:09 UTC, merged