Data Security: update Agent Trace obfuscation
DataDog/documentation pull request #19656
Opened 2023-09-07 16:56 UTC by katiehockman

### What does this PR do?

Updates the Agent Trace obfuscation documentation to indicate database statement obfuscation is on by default, and adds missing options.

### Motivation

Reflects behavioral changes created by https://github.com/DataDog/datadog-agent/pull/19321.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.
- [ ] Check that `cache_enabled` is set to `true` in the `pull_config_preview.yaml` file

2023-09-07 17:14 UTC, rtrieu requested changes
A few minor suggestions to follow our style guide, but otherwise looks good!

2023-09-07 17:14 UTC, rtrieu commented on content/en/tracing/configure_data_security/_index.md
> +The Agent can obfuscate other sensitive data in [traces][2] that is not within the resource name. Configuration of obfuscation rules can be done with environment variables or the `datadog.yaml` confi
```suggestion
The Agent can obfuscate other sensitive data in [traces][2] that is not within the resource name. You can configure the obfuscation rules using environment variables or the `datadog.yaml` configuration file.
```

2023-09-07 17:14 UTC, rtrieu commented on content/en/tracing/configure_data_security/_index.md
> +* `keep_values` or environment variable `DD_APM_OBFUSCATION_MONGODB_KEEP_VALUES` - defines a set of keys to exclude from Agent trace obfuscation. If not set, all keys will be obfuscated.
```suggestion
* `keep_values` or environment variable `DD_APM_OBFUSCATION_MONGODB_KEEP_VALUES` - defines a set of keys to exclude from Agent trace obfuscation. If not set, all keys are obfuscated.
```

2023-09-07 17:14 UTC, rtrieu commented on content/en/tracing/configure_data_security/_index.md
> +* `obfuscate_sql_values` or environment variable `DD_APM_OBFUSCATION_MONGODB_OBFUSCATE_SQL_VALUES` - defines a set of keys to include Agent trace obfuscation. If not set, all keys will be obfuscated.
```suggestion
* `obfuscate_sql_values` or environment variable `DD_APM_OBFUSCATION_MONGODB_OBFUSCATE_SQL_VALUES` - defines a set of keys to include Agent trace obfuscation. If not set, all keys are obfuscated.
```

2023-09-07 17:14 UTC, rtrieu commented on content/en/tracing/configure_data_security/_index.md
> +* `keep_values` or environment variable `DD_APM_OBFUSCATION_ELASTICSEARCH_KEEP_VALUES` - defines a set of keys to exclude from Agent trace obfuscation. If not set, all keys will be obfuscated.
```suggestion
* `keep_values` or environment variable `DD_APM_OBFUSCATION_ELASTICSEARCH_KEEP_VALUES` - defines a set of keys to exclude from Agent trace obfuscation. If not set, all keys are obfuscated.
```

2023-09-07 17:14 UTC, rtrieu commented on content/en/tracing/configure_data_security/_index.md
> +* `obfuscate_sql_values` or environment variable `DD_APM_OBFUSCATION_ELASTICSEARCH_OBFUSCATE_SQL_VALUES` - defines a set of keys to include Agent trace obfuscation. If not set, all keys will be obfus
```suggestion
* `obfuscate_sql_values` or environment variable `DD_APM_OBFUSCATION_ELASTICSEARCH_OBFUSCATE_SQL_VALUES` - defines a set of keys to include Agent trace obfuscation. If not set, all keys are obfuscated.
```

2023-09-07 17:57 UTC, rtrieu approved these changes
Looks good!

2023-10-11 14:10 UTC, katiehockman commented
The Agent release has gone out, so this is now good to merge.

2023-10-11 14:52 UTC, merged