Add core dump docs for PHP in docker
DataDog/documentation pull request #19820
Opened 2023-09-20 14:20 UTC by realFlowControl

### What does this PR do? What is the motivation?

We had a customer that experienced a crash but was unable to obtain a core dump as they were running PHP in docker, which is another layer to overcome when you need to create a core file.
This PR will add the docs to help customers that run PHP in docker create core files.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-09-20 22:26 UTC, buraizu requested changes
Thanks, just suggesting a few minor edits

2023-09-20 22:26 UTC, buraizu commented on content/en/tracing/trace_collection/dd_libraries/php.md
> +### Obtaining a core dump from within a docker container
```suggestion
### Obtaining a core dump from within a Docker container
```

2023-09-20 22:26 UTC, buraizu commented on content/en/tracing/trace_collection/dd_libraries/php.md
> +Obtaining a core dump in a docker container adds another layer of challenges to overcome. Here are a few tips to help you obtain a core dump:
```suggestion
Use the information below to assist with obtaining a core dump in a Docker container:
```

2023-09-20 22:26 UTC, buraizu commented on content/en/tracing/trace_collection/dd_libraries/php.md
> +1. The docker container needs to run as a privileged container and the ulimit for core files needs to be maxed out.
```suggestion
1. The Docker container needs to run as a privileged container, and the `ulimit` value for core files needs to be set to its maximum as shown in the examples below.
```

2023-09-20 22:26 UTC, buraizu commented on content/en/tracing/trace_collection/dd_libraries/php.md
> +   - In case you use `docker compose` add the following to the container in the `docker-compose.yml`:
```suggestion
   - If you use the `docker run` command, add the `--privileged` and the `--ulimit core=99999999999` arguments
   - If you use `docker compose`, add the following to the `docker-compose.yml` file:
```

2023-09-25 15:51 UTC, realFlowControl commented
Hey there @buraizu 👋 
can you have another look and feel free to merge when everything is okay from your side

2023-09-25 16:04 UTC, buraizu approved these changes
@realFlowControl thanks for applying those changes, LGTM!

2023-09-25 16:05 UTC, merged