Add INP to RUM browser monitoring page
DataDog/documentation pull request #19983
Opened 2023-09-29 15:35 UTC by amortemousque

### What does this PR do? What is the motivation?

Add Interaction To Next Paint (INP) to the RUM browser monitoring page performance

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-09-29 19:37 UTC, aliciascott requested changes
Just a small change to remove a period where it shouldn't be :) Please request re-review after this is fixed and I'll get it merged.

2023-09-29 19:37 UTC, aliciascott commented on content/en/real_user_monitoring/browser/monitoring_page_performance.md
> +| `view.interaction_to_next_paint`| number (ns) | Time elapsed between a user's longest interaction with the page to the next paint. response.
```suggestion
| `view.interaction_to_next_paint`| number (ns) | Time elapsed between a user's longest interaction with the page to the next paint response.                                                                                                                                     |
```

2023-10-02 09:38 UTC, anediaz approved these changes

2023-10-03 14:47 UTC, aliciascott approved these changes
looks good!

2023-10-04 15:38 UTC, aliciascott commented
Hi @amortemousque is this ready for merge and if so do you want us to go ahead and merge it ?

2023-10-05 23:26 UTC, merged