Update distributions.md
DataDog/documentation pull request #20035
Opened 2023-10-03 16:44 UTC by CyrusBelsoi

### What does this PR do? What is the motivation?

Updates to our dist. metrics type offering, new functionality release

### Merge instructions

- [ ] Awaiting a few changes before merge

### Additional notes

2023-10-03 17:00 UTC, maycmlee reviewed
Left a couple of suggestions!

2023-10-03 17:00 UTC, maycmlee commented on content/en/metrics/distributions.md
> +* **Calculation of percentile aggregations**: Distributions are stored as DDSketch data structures that represent raw, unaggregated data such that globally accurate percentile aggregations (p50, p75,
```suggestion
* **Calculation of percentile aggregations**: Distributions are stored as DDSketch data structures that represent raw, unaggregated data such that globally accurate percentile aggregations (p50, p75, p90, p95, p99 or any percentile of your choosing with up to two decimal points, including standard deviation) can be calculated across the raw data from all your hosts. Enabling percentile aggregations can unlock advanced query functionalities such as: 
```

2023-10-03 17:00 UTC, maycmlee commented on content/en/metrics/distributions.md
> +     _"What is the standard deviation (stddev) of my application's CPU consumption over the past 3 months?"_
```suggestion
     _"What is the standard deviation (STDDEV) of my application's CPU consumption over the past 3 months?"_
```

2023-10-03 17:00 UTC, maycmlee commented on content/en/metrics/distributions.md
> +However, you can enable advanced query functionality such as the calculation of globally accurate percentile aggregations for all queryable tags on your distribution on the Metrics Summary page. This
```suggestion
However, you can enable advanced query functionality such as the calculation of globally accurate percentile aggregations for all queryable tags on your distribution on the Metrics Summary page. This provides aggregations for `p50`, `p75`, `p90`, `p95`, and `p99` or any user-defined percentile of your choosing (with up to two decimal points such as 99.99), including standard deviation. Enabling advanced queries also unlocks threshold queries.
```

2023-10-04 13:49 UTC, maycmlee approved these changes
@CyrusBelsoi is this good to merge?

2023-10-12 21:51 UTC, ijkaylin requested changes

2023-10-12 21:51 UTC, ijkaylin commented on content/en/metrics/distributions.md
> +* **Calculation of percentile aggregations**: Distributions are stored as DDSketch data structures that represent raw, unaggregated data such that globally accurate percentile aggregations (p50, p75,
I don't think we should be including standard deviation in this percentiles (). 

```suggestion
* **Calculation of percentile aggregations**: Distributions are stored as DDSketch data structures that represent raw, unaggregated data such that globally accurate percentile aggregations (p50, p75, p90, p95, p99 or any percentile of your choosing with up to two decimal points) can be calculated across the raw data from all your hosts. Enabling percentile aggregations can unlock advanced query functionalities such as: 
```

2023-10-12 21:51 UTC, ijkaylin commented on content/en/metrics/distributions.md
> +  * **Variance in performance over time**:
```suggestion
  * **Standard deviation over any timeframe
```

2023-10-12 21:51 UTC, ijkaylin commented on content/en/metrics/distributions.md
> +However, you can enable advanced query functionality such as the calculation of globally accurate percentile aggregations for all queryable tags on your distribution on the Metrics Summary page. This
Same as above - standard deviation is not a percentile. This phrasing implies that it is 

```suggestion
However, you can enable advanced query functionality such as the calculation of globally accurate percentile aggregations for all queryable tags on your distribution on the Metrics Summary page. This provides aggregations for `p50`, `p75`, `p90`, `p95`, and `p99` or any user-defined percentile of your choosing (with up to two decimal points such as 99.99). Enabling advanced queries also unlocks threshold queries and the standard deviation.
```

2023-10-17 17:24 UTC, merged