[CCM] add links to Labels as tags configuration
DataDog/documentation pull request #20117
Opened 2023-10-10 18:22 UTC by enemyghost

### What does this PR do? What is the motivation?

This adds instructions for enabling Labels as tags, in order to add labels as tags on cost metrics.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2023-10-10 19:09 UTC, aliciascott requested changes
Thanks @enemyghost just a minor suggestion, please request re-review once the changes are incorporated. Thanks!

2023-10-10 19:09 UTC, aliciascott commented on content/en/cloud_cost_management/container_cost_allocation.md
> +Note: Only _tags_ from pods and nodes are added to cost metrics. To include labels, enable labels as tags for [Nodes][7] and [Pods][8].
```suggestion
**Note**: Only _tags_ from pods and nodes are added to cost metrics. To include labels, enable labels as tags for [nodes][7] and [pods][8].
```

2023-10-10 19:17 UTC, estherk15 approved these changes

2023-10-10 19:17 UTC, estherk15 commented on content/en/cloud_cost_management/container_cost_allocation.md
> +Note: Only _tags_ from pods and nodes are added to cost metrics. To include labels, enable labels as tags for [Nodes][7] and [Pods][8].
```suggestion
**Note**: Only _tags_ from pods and nodes are added to cost metrics. To include labels, enable labels as tags for [Nodes][7] and [Pods][8].
```

2023-10-11 14:04 UTC, aliciascott approved these changes

2023-10-11 14:05 UTC, merged