[APPSEC-11306] Adding threat intelligence docs for ASM
DataDog/documentation pull request #20114
Opened 2023-10-10 13:33 UTC by jkirsteins

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-10-11 09:25 UTC, netcode approved these changes

2023-10-11 17:05 UTC, buraizu requested changes
Hi, thanks for the PR. I've left some feedback mostly based on our [style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md), and also asked for additional detail in some places.

A couple of other minor details:
- For the screenshots, could you please obfuscate the IP addresses and any other PII? I'll follow up internally with a link to a relevant resource for that. If possible, it might also be helpful to "zoom in" or otherwise highlight the sections that users should view
- Also, could you please remove the Japanese language update? It's sufficient to update the English source file; updates to the translated docs are managed through a 3rd party service and the Japanese doc will eventually be brought into sync

Thanks again, and let me know if you have any questions!

2023-10-12 07:07 UTC, udgover requested changes

2023-10-23 11:55 UTC, jkirsteins commented on config/_default/menus/menus.en.yaml
> +    weight: 508
This was in anticipation of a parallel PR to be merged first. Now there's no gap anymore.

2023-10-23 12:21 UTC, jkirsteins commented on content/en/security/application_security/threats/threat-intelligence.md
> +|Cloud SIEM| *Any* |Threat intelligence will be present in every log.|
`|Cloud SIEM| *Any* |Threat intelligence is present in matching logs.|`

2023-10-23 15:52 UTC, jkirsteins commented on content/en/security/application_security/threats/threat-intelligence.md
> +|APM| ASM |Threat intelligence will be present the same way as in ASM.|
@buraizu It would repeat the information 2 rows down. Maybe I can add something like `See the ASM row for details.` ?

2023-10-23 17:38 UTC, buraizu requested changes
Thanks for implementing those changes! This review makes a few additional minor wording and punctuation edits, but also bumps the unresolved conversation [here](https://github.com/DataDog/documentation/pull/20114/files#r1355357074). 

Thanks again for your patience, and let me know if you have any alternative suggestions or feedback!

2023-10-23 17:38 UTC, buraizu commented on content/en/security/application_security/threats/threat-intelligence.md
> +Use the table below to understand how to find threat intelligence information for the Datadog services in use:
```suggestion
The table below shows the availability of threat intelligence information for Datadog services:
```

2023-10-23 17:38 UTC, buraizu commented on content/en/security/application_security/threats/threat-intelligence.md
> +When viewing the traces in the UI, you can see threat intelligence data under the `@appsec` attribute. The `category` and `security_activity` are both set.
```suggestion
When viewing the traces in the ASM Traces Explorer, you can see threat intelligence data under the `@appsec` attribute. The `category` and `security_activity` attributes are both set.
```

2023-10-23 17:38 UTC, buraizu commented on content/en/security/application_security/threats/threat-intelligence.md
> +As seen in the table above, APM requires ASM to display threat intelligence. Also, Cloud SIEM may display logs with threat intelligence data, which are not surfaced in ASM for the same IP addresses
```suggestion
As seen in the table above, APM requires ASM to display threat intelligence. Also, Cloud SIEM may display logs with threat intelligence data, which are not surfaced in ASM for the same IP addresses.
```

2023-10-23 17:38 UTC, buraizu commented on content/en/security/application_security/threats/threat-intelligence.md
> +In ASM the Threat Intelligence data is used in two ways:
```suggestion
In ASM, the Threat Intelligence data is used in two ways:
```

2023-10-23 17:52 UTC, jkirsteins commented
@buraizu Thanks for the followup suggestions.

Sorry for overlooking some of those earlier suggestions. I was sure I had addressed them, I don't know how I missed them!

I think now there's only resolved conversations. Except only one where I'm not sure it's a good idea duplicating the information in two rows that are nearby each other. But if you think it's better to have each row be standalone, I don't have a strong objection to that.

2023-10-23 18:31 UTC, buraizu commented on content/en/security/application_security/threats/threat-intelligence.md
> +|APM| ASM |Threat intelligence will be present the same way as in ASM.|
@jkirsteins thanks for pointing that out, I missed that previously and don't think any update is needed here

2023-10-23 18:42 UTC, buraizu approved these changes
Thanks again for working with me on these updates, approving with a final update to a section title

2023-10-23 18:42 UTC, buraizu commented on content/en/security/application_security/threats/threat-intelligence.md
> +## Behavior across Cloud SIEM, APM, and ASM
```suggestion
## Availability across Cloud SIEM, APM, and ASM
```

2023-10-23 20:37 UTC, udgover approved these changes
My requested changes have been taken into account and other changes are great addition as well. LGTM!

2023-10-24 18:37 UTC, merged