Update dual-shipping.md
DataDog/documentation pull request #20198
Opened 2023-10-16 17:11 UTC by mrdoggopat

Add missing configurations in the docs to fully dual ship cluster agent metrics and Orchestrator Explorer Data

### What does this PR do? What is the motivation?

Add missing configurations in the docs to fully dual ship cluster agent metrics and Orchestrator Explorer Data

### Merge instructions

- [✅] Please merge after reviewing

### Additional notes

2023-10-16 17:36 UTC, maycmlee requested changes
Made a couple of suggestions. Let me know if it doesn't work.

2023-10-16 17:36 UTC, maycmlee commented on content/en/agent/guide/dual-shipping.md
> +
```suggestion
Configure the Agent to send Cluster Agent metrics, such as Kubernetes State Metrics Core, to additional endpoints.
```

2023-10-16 17:36 UTC, maycmlee commented on content/en/agent/guide/dual-shipping.md
> +## Cluster Agent metrics (e.g. Kubernetes State Metrics Core)
```suggestion
## Cluster Agent metrics
```

2023-10-17 14:00 UTC, mrdoggopat commented on content/en/agent/guide/dual-shipping.md
> +
IGTM

2023-10-17 14:00 UTC, mrdoggopat commented on content/en/agent/guide/dual-shipping.md
> +## Cluster Agent metrics (e.g. Kubernetes State Metrics Core)
IGTM

2023-10-17 19:41 UTC, maycmlee commented on content/en/agent/guide/dual-shipping.md
> +## Cluster Agent metrics (e.g. Kubernetes State Metrics Core)
```suggestion
## Cluster Agent metrics
```

2023-10-17 19:41 UTC, maycmlee commented on content/en/agent/guide/dual-shipping.md
> +
```suggestion
Configure the Agent to send Cluster Agent metrics, such as Kubernetes State Metrics Core, to additional endpoints.
```

2023-10-18 13:42 UTC, maycmlee approved these changes

2023-10-18 14:10 UTC, merged