Add instructions for an included datadog_archives sink.
DataDog/documentation pull request #20276
Opened 2023-10-19 22:54 UTC by silversupreme

### What does this PR do? What is the motivation?
We've decided to include a sample `datadog_archives` sink in the included configurations for Linux, Docker, Terraform, and EKS. This PR includes instructions for how to setup a customer's environment to properly use this config.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2023-10-20 12:43 UTC, jszwedko reviewed
👍 Do we already have docs about how to rehydrate from these? Or are those forthcoming? If we have them already, we should link from here.

2023-10-20 20:13 UTC, maycmlee reviewed
Left some suggestions! There were also a couple of links missing so I added them in.

2023-10-20 20:13 UTC, maycmlee commented on content/en/observability_pipelines/setup/datadog.md
>  {{% /tab %}}
```suggestion

[1]: https://aws.amazon.com/s3/pricing/

{{% /tab %}}
```

2023-10-20 20:13 UTC, maycmlee commented on content/en/observability_pipelines/setup/datadog.md
>  {{% /tab %}}
```suggestion

[1]: https://aws.amazon.com/s3/pricing/

{{% /tab %}}
```

2023-10-20 20:13 UTC, maycmlee commented on content/en/observability_pipelines/setup/datadog.md
>  {{% /tab %}}
```suggestion

[1]: https://aws.amazon.com/s3/pricing/

{{% /tab %}}
```

2023-10-26 15:30 UTC, maycmlee requested changes
Left some suggestions! Can we also:

- Rename the file from `archives.md` to `datadog_with_archiving.md`.
- Remove CloudFormation content, since it doesn't have any archiving info (I don't think)?

Jesse also mentioned adding a link to the Rehydrating doc: https://docs.datadoghq.com/logs/log_configuration/rehydrating/

2023-10-26 21:15 UTC, maycmlee commented on content/en/observability_pipelines/setup/datadog_with_archiving.md
> +
```suggestion

{{< site-region region="gov" >}}
<div class="alert alert-warning">Observability Pipelines is not available on the US1-FED Datadog site.</div>
{{< /site-region >}}

```

2023-10-26 21:15 UTC, maycmlee commented on config/_default/menus/menus.en.yaml
> +    weight: 101
```suggestion
    weight: 102
```

2023-10-26 21:15 UTC, maycmlee commented on content/en/observability_pipelines/setup/datadog_with_archiving.md
> +The sample configuration you download later includes a sink for sending logs to Amazon S3 under a Datadog-rehydratable format. To use this configuration,  set up an IAM policy that allows the Workers
```suggestion
The sample configuration you download later includes a sink for sending logs to Amazon S3 under a Datadog-rehydratable format. To use this configuration, set up an IAM policy that allows the Workers to write to S3.
```

2023-10-26 21:15 UTC, maycmlee commented on content/en/observability_pipelines/setup/datadog_with_archiving.md
> +    ```
Want to see if I can fix the markdown...for some reason the rest of the content is in blue

```suggestion

    ```shell
```
```

2023-10-27 20:32 UTC, maycmlee approved these changes
@barieom did you want to review as well?

2023-11-08 17:04 UTC, closed without merging