DOCS-6460 Adds Creating an HTTP Test with HMAC Authentication Guide
DataDog/documentation pull request #20292
Opened 2023-10-20 21:16 UTC by alai97

### What does this PR do? What is the motivation?

Adds a guide on creating an HTTP test with an HMAC signature + screenshots.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-10-20 22:14 UTC, urseberry commented on content/en/synthetics/guide/http-tests-with-hmac.md
> +Create an [Synthetic HTTP test][3] and click **Create a Local Variable** to add the following variables:
```suggestion
Create a [Synthetic HTTP test][3] and click **Create a Local Variable** to add the following variables:
```

2023-10-20 22:14 UTC, urseberry commented on content/en/synthetics/guide/http-tests-with-hmac.md
> +: (Optional) An additional parameter to help compute the HMAC signature. You can create this as a [local variable][1] or create and export this [inside the pre-request script with `dd.variable.set('M
```suggestion
: (Optional) An additional parameter to help compute the HMAC signature. You can create this as a [local variable][1] or create and export this inside the [pre-request script](#define-a-pre-request-script) with `dd.variable.set('MY_TIMESTAMP', Date.now())`.
```

2023-10-20 22:14 UTC, urseberry commented on content/en/synthetics/guide/http-tests-with-hmac.md
> +You can configure the rest of your HTTP test and click **Create** to save.
```suggestion
Configure the rest of your HTTP test, and click **Create** to save.
```

2023-10-20 22:14 UTC, urseberry commented on content/en/synthetics/guide/http-tests-with-hmac.md
> +You can use the exported `MY_SIGNATURE` variable to build the HTTP request header before writing the pre-request script (hope this is clear).
```suggestion
You can use the exported `MY_SIGNATURE` variable to build the HTTP request header before writing the pre-request script.
```
Seems clear to me! 😃

2023-10-21 06:58 UTC, urseberry approved these changes

2024-03-18 14:45 UTC, ruizb commented
Hello @alai97, I've pushed 2 commits to update the screenshots, the JavaScript code snippet, and I also added a couple of bullet points regarding the APIs available in the script sandbox for our users. Feel free to improve the wording/presentation of it!

2024-03-27 14:37 UTC, aliciascott commented
> Hello @alai97, I've pushed 2 commits to update the screenshots, the JavaScript code snippet, and I also added a couple of bullet points regarding the APIs available in the script sandbox for our users. Feel free to improve the wording/presentation of it!
> 
> (feature still not available, but we are very close to it!)

Hi @ruizb I'm taking this one over from @alai97 , thanks for the update! I'll be keeping an eye on this one, just let us know when it's ready :)

2024-04-18 13:37 UTC, ruizb approved these changes

2024-04-18 13:59 UTC, HugoPct approved these changes

2024-04-18 14:02 UTC, ruizb commented
Hello @aliciascott, we can finally merge it! We'll enable the feature for everyone in our app as soon as the link to this documentation page is available publicly 👍

2024-04-18 15:10 UTC, aliciascott requested changes
Hey @ruizb I did another once over and just one very small fix is needed! Do you mind updating this, then I'll get it merged ?

2024-04-18 15:10 UTC, aliciascott commented on content/en/synthetics/guide/http-tests-with-hmac.md
> +**Note**: some of these APIs are disabled for security reasons.
```suggestion
**Note**: Some of these APIs are disabled for security reasons.
```

2024-04-18 15:35 UTC, ruizb commented on content/en/synthetics/guide/http-tests-with-hmac.md
> +**Note**: some of these APIs are disabled for security reasons.
Oh, my bad! Good catch 👍

2024-04-18 16:05 UTC, aliciascott approved these changes

2024-04-18 16:10 UTC, merged