[DOCS-6574] New Resource Catalog page
DataDog/documentation pull request #20423
Opened 2023-10-31 21:49 UTC by aliciascott

### What does this PR do? What is the motivation?
This PR creates a new page for Resource Catalog under Infrastructure, maintaining a lot of the existing content from where it currently [lives](https://docs.datadoghq.com/security/misconfigurations/resource_catalog). 
Replaces Ownership tab with Inventory tab.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-11-20 22:13 UTC, kayayarai requested changes
Just a few comments. The preview seems to work well with the single-sourcing changes you made 👍 . 

One note: it's best practice to name files (in this case, screen caps) all lower-case because occasionally they will pass through systems where filenames get downcased, and you still want it to work. I recommend changing your screen cap file names and the in-page links to them to be consistently lower-case.

2023-11-20 22:13 UTC, kayayarai commented on content/en/infrastructure/resource_catalog/_index.md
> +- link: "security/misconfigurations/"
```suggestion
- link: "/security/misconfigurations/"
```

2023-11-20 22:13 UTC, kayayarai commented on content/en/infrastructure/resource_catalog/_index.md
> +- link: "security/threats/"
```suggestion
- link: "/security/threats/"
```

2023-11-20 22:13 UTC, kayayarai commented on content/en/infrastructure/resource_catalog/_index.md
> +By default, you can view all resources monitored by the Datadog Agent and other Cloud Integrations. To view additional cloud resources in the Resource Catalog, please enable resource collection from
```suggestion
By default, you can view all resources monitored by the Datadog Agent and Cloud Integrations. To view additional cloud resources in the Resource Catalog, enable resource collection from the [Resource Catalog][5] setup page. To gain insights into your security risks, enable [Cloud Security Management][1] for each cloud account.
```

2023-11-20 22:13 UTC, kayayarai commented on content/en/infrastructure/resource_catalog/_index.md
> +The inventory tab allows you to understand the context for a resource such as team ownership and related service. This page allows you to proactively identify lack of ownership information and resolv
```suggestion
The Inventory tab shows context for a resource, including team ownership and related services. It helps you proactively identify and provide missing ownership information before you need it in an incident. The Resource Catalog shows configuration information customized for each resource type. You can search resources by specific configuration attributes such as `instance_type` for a host, or a `version` for a database.
```

2023-11-20 22:58 UTC, aliciascott commented on Makefile
> +
Hmmm... That must be auto-generated or not sure what happened as I didn't do anything with the `Makefile`, I'll take a look.

2023-11-20 23:29 UTC, aliciascott commented
> Just a few comments. The preview seems to work well with the single-sourcing changes you made 👍 .
> 
> One note: it's best practice to name files (in this case, screen caps) all lower-case because occasionally they will pass through systems where filenames get downcased, and you still want it to work. I recommend changing your screen cap file names and the in-page links to them to be consistently lower-case.

Ok - got those updated, I did re-name the images in the branch as well to lower-case but it didn't trigger them to be re-added with the new lowercase name, the preview is still fine, but let me know if that is ok.

2023-11-21 14:53 UTC, kayayarai approved these changes
LGTM!

2023-11-21 18:04 UTC, merged