DOCS-5877 Add DORA Metrics Documentation
DataDog/documentation pull request #20608
Opened 2023-11-14 00:04 UTC by alai97

### What does this PR do? What is the motivation?

Add documentation for DORA Metrics private beta release.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-11-14 18:09 UTC, AdrianLC commented
hey @alai97 thanks a lot for the help with this 😁 

How do you want to collaborate on this? Should I commit more content to your branch directly? or would you rather merge this to an integration branch and I can add more PRs targeting it before we do the final merge to master?

2023-11-16 21:05 UTC, alai97 commented on content/en/continuous_integration/dora_metrics/_index.md
> +[2]: /api/latest/continuous_integration/TBD
```suggestion
[2]: /api/latest/dora-metrics
```

2023-11-16 21:07 UTC, kassenq approved these changes

2023-11-17 17:23 UTC, AdrianLC approved these changes

2023-11-17 21:03 UTC, alai97 commented on content/en/continuous_integration/dora_metrics/_index.md
> +- link: "https://github.com/DataDog/datadog-ci"
```suggestion
- link: "/tracing/service_catalog"
  tag: "Documentation"
  text: "Learn about the Service Catalog"
- link: "https://github.com/DataDog/datadog-ci"
```

2023-11-20 15:00 UTC, kassenq requested changes

2023-11-20 15:00 UTC, kassenq commented on content/en/continuous_integration/dora_metrics/_index.md
> +DORA Metrics are in private beta for <a href="https://docs.datadoghq.com/continuous_integration/pipelines/">CI Pipeline Visibility</a> customers. To request access, complete the form.
"DORA Metrics are in private beta for CI Pipeline Visibility, [Test Visibility](https://docs.datadoghq.com/continuous_integration/tests/), and/or [Static Analysis](https://docs.datadoghq.com/continuous_integration/static_analysis/?tab=circleciorbs) customers."

2023-11-20 15:28 UTC, AdrianLC commented on content/en/continuous_integration/dora_metrics/_index.md
> +DORA Metrics are in private beta for <a href="https://docs.datadoghq.com/continuous_integration/pipelines/">CI Pipeline Visibility</a> customers. To request access, complete the form.
```suggestion
DORA Metrics are in private beta for <a href="https://docs.datadoghq.com/continuous_integration/pipelines/">CI Pipeline Visibility</a>, <a href="https://docs.datadoghq.com/continuous_integration/tests/">Test Visibility</a> and/or <a href="https://docs.datadoghq.com/continuous_integration/static_analysis/">Static Analysis</a> customers. To request access, complete the form.
```

2023-11-20 16:21 UTC, jhgilbert approved these changes

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +DORA Metrics are in private beta for <a href="https://docs.datadoghq.com/continuous_integration/pipelines/">CI Pipeline Visibility</a>, <a href="https://docs.datadoghq.com/continuous_integration/test
```suggestion
DORA Metrics are in private beta for <a href="https://docs.datadoghq.com/continuous_integration/pipelines/">CI Pipeline Visibility</a>, <a href="https://docs.datadoghq.com/continuous_integration/tests/">Test Visibility</a> and <a href="https://docs.datadoghq.com/continuous_integration/static_analysis/">Static Analysis</a> customers. To request access, complete the form.
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +export DD_SITE="DD_SITE"
```suggestion
export DD_SITE="<DD_SITE>"
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +export DD_API_KEY="api-key"
```suggestion
export DD_API_KEY="<API_KEY>"
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +#### Filter git commits in monorepos
```suggestion
#### Filter Git commits in monorepos
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +If you are using a monorepo (building several services from the same git repository), not every git commit affects the lead time of all services.
```suggestion
If you are using a monorepo (building several services from the same Git repository), not every Git commit affects the lead time of all services.
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +If the Service definition contains a **full** GitHub URL to the application folder, a single path pattern is automatically used.
```suggestion
If the service definition contains a **full** GitHub URL to the application folder, a single path pattern is automatically used.
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +DORA Metrics for the service `shopist` only consider the git commits that include changes within `src/apps/shopist/**` or `src/libs/utils/**`.
```suggestion
DORA Metrics for the service `shopist` only consider the Git commits that include changes within `src/apps/shopist/**` or `src/libs/utils/**`.
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +  - `git-repository-url` and `git-commit-sha` can be omitted if the deployment CI job is running on the exact same git checkout that has been deployed.
```suggestion
  - `git-repository-url` and `git-commit-sha` can be omitted if the deployment CI job is running on the exact same Git checkout that has been deployed.
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +  - `skip-git` disables the git details ([change lead time](#lead-time-for-changes) is not available).
```suggestion
  - `skip-git` disables the Git details ([change lead time](#lead-time-for-changes) is not available).
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +- For [change lead time](#lead-time-for-changes), the retention of git metadata is 1 month. Commits older that 1 month are not accounted for.
```suggestion
- For [change lead time](#lead-time-for-changes), the retention of Git metadata is 1 month. Commits older that 1 month are not accounted for.
```

2023-11-20 16:21 UTC, jhgilbert commented on content/en/continuous_integration/dora_metrics/_index.md
> +  text: "Learn about the `datadog-ci` CLI tool"
```suggestion
  text: "Learn about the datadog-ci CLI tool"
```
Backticks don't work in Further Reading, they just show up literally. Not sure how you feel about that -- you can leave them in if the visible backticks are better than nothing

2023-11-20 17:00 UTC, alai97 commented on content/en/continuous_integration/dora_metrics/_index.md
> +- link: "/tracing/service_catalog"
```suggestion
- link: "/continuous_integration/static_analysis"
  tag: "Documentation"
  text: "Learn about Static Analysis"
- link: "/tracing/service_catalog"
```

2023-11-20 17:05 UTC, alai97 commented on content/en/continuous_integration/dora_metrics/_index.md
> +DORA Metrics are in private beta for <a href="https://docs.datadoghq.com/continuous_integration/pipelines/">CI Pipeline Visibility</a>, <a href="https://docs.datadoghq.com/continuous_integration/test
```suggestion
DORA Metrics are in private beta for <a href="https://docs.datadoghq.com/continuous_integration/pipelines/">CI Pipeline Visibility</a>, <a href="https://docs.datadoghq.com/continuous_integration/tests/">Test Visibility</a>, and <a href="https://docs.datadoghq.com/continuous_integration/static_analysis/">Static Analysis</a> customers. To request access, complete the form.
```

2023-11-20 17:45 UTC, kassenq approved these changes

2023-11-20 18:20 UTC, merged