Update advanced-filtering.md
DataDog/documentation pull request #20602
Opened 2023-11-13 21:58 UTC by CyrusBelsoi

### What does this PR do? What is the motivation?

Updating feature name to reflect recent change

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-11-13 23:01 UTC, brett0000FF approved these changes

2023-11-13 23:01 UTC, brett0000FF commented
Give me a ping when this is ready to be merged.

2023-11-15 19:53 UTC, ijkaylin requested changes

2023-11-15 19:53 UTC, ijkaylin commented on content/en/metrics/advanced-filtering.md
> +Tag value prefix, suffix, and substring wildcard matching is supported:
```suggestion
Prefix, suffix and substring wildcard tag filtering is supported: 
```

2023-11-15 21:26 UTC, merged