Updating the documentation for dd-dotnet
DataDog/documentation pull request #20734
Opened 2023-11-21 17:11 UTC by kevingosse

### What does this PR do? What is the motivation?

Update the diagnostic doc to mention the new dd-dotnet tool. Update the expected outputs.

- [x] Please merge after reviewing

2023-11-21 17:36 UTC, andrewlock commented on content/en/tracing/troubleshooting/dotnet_diagnostic_tool.md
> +---- STARTING TRACER SETUP CHECKS -----
Where are the "issues"? 🤔

2023-11-21 17:38 UTC, andrewlock reviewed
LGTM, except I think you missed an update/updated one with the wrong grab

2023-11-21 17:38 UTC, andrewlock commented on content/en/tracing/troubleshooting/dotnet_diagnostic_tool.md
> +$ dd-dotnet check process 35888
I think you need to update the previous example too

2023-11-22 02:18 UTC, link04 requested changes
It looks like the example session the process check is using the older No Issues output instead of the new one and the output with issues has no issues, for the IIS output they both  got no issues. Could we add an example where they haven't set a key for it to show up on the `---- STARTING TRACER SETUP CHECKS -----` section?

2023-11-27 10:45 UTC, kevingosse commented
> It looks like the example session the process check is using the older No Issues output instead of the new one and the output with issues has no issues, for the IIS output they both got no issues. Could we add an example where they haven't set a key for it to show up on the `---- STARTING TRACER SETUP CHECKS -----` section?

My bad, fixed in https://github.com/DataDog/documentation/pull/20734/commits/ca9e467639d64b2f0ff5d43ff9b0128382f31bc4

2023-11-27 11:01 UTC, andrewlock approved these changes
LGTM thanks

2023-12-08 15:11 UTC, link04 approved these changes

2023-12-08 22:39 UTC, urseberry approved these changes

2023-12-08 22:39 UTC, merged