(DOCS-6596) App builder
DataDog/documentation pull request #20745
Opened 2023-11-21 22:15 UTC by hestonhoffman

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-11-21 22:35 UTC, hestonhoffman commented on config/_default/menus/menus.en.yaml
> +    pre: AppBuilder
@urseberry this is the icon name

2023-11-22 19:39 UTC, cswatt requested changes

2023-11-22 19:39 UTC, cswatt commented on content/en/service_management/app_builder/build.md
> +Similar to UI component events, you can configure a reaction to trigger after a query executes. A **Post-query Hook** can set a UI component state, open or close a modal, trigger another query, or ev
```suggestion
Similar to UI component events, you can configure a reaction to trigger after a query executes. A **post-query hook** can set a UI component state, open or close a modal, trigger another query, or even run custom JavaScript. For example, the [ECS Task Manager][7] blueprint's `scaleService` query uses a post-query hook to rerun the `describeService` query after it executes.
```

2023-11-22 19:39 UTC, cswatt commented on content/en/service_management/app_builder/build.md
> +To display a toast to the user when the system returns an error, toggle **Show Toast on Errors** in the **Advanced** section of a query.
```suggestion
To display a toast (a brief message notification) to the user when the system returns an error, toggle **Show Toast on Errors** in the **Advanced** section of a query.
```

i think we really can't assume that people know what "toast" means in the context of UI/UX (i'd actually argue that we also can't assume people know what "toast" means in the context of breakfast foods either)

2023-11-22 19:39 UTC, cswatt commented on content/en/service_management/app_builder/build.md
> +Variables are enclosed in braces, preceeded by a dollar sign (`${}`). To use a variable, enter the query or UI component name and access the child fields using dot notation. For example, if you have
```suggestion
Variables are enclosed in braces, preceded by a dollar sign (`${}`). To use a variable, enter the query or UI component name and access the child fields using dot notation. For example, if you have a select component named `select0` and you want to access its default value field, use the syntax `${select0.defaultValue}`. If you're not sure what to enter as a variable, type `${` to open a suggestions menu with all available variables.
```

2023-11-22 19:39 UTC, cswatt commented on content/en/service_management/app_builder/embedded_apps.md
> +**Note**: If you want to leave an element blank by default (such as a search field), you can set the default value as an empty string `""` or `undefined`.
```suggestion
**Note**: If you want to leave an element (such as a search field) blank by default, you can set the default value as an empty string `""` or `undefined`.
```

2023-11-22 20:53 UTC, urseberry commented on content/en/service_management/app_builder/_index.md
> +Below are a few examples of apps you can build:
I love your improved wording suggestion!

2023-11-27 16:00 UTC, merged