[CCV] CUR 2.0 - update public docs following CUR changes
DataDog/documentation pull request #20867
Opened 2023-12-01 16:31 UTC by crousseaux

### What does this PR do? What is the motivation?
AWS released CUR 2.0, we need to update all setup/documentation of “CUR” to the “Legacy CUR”

More details here: [CUR 2.0](https://docs.google.com/document/d/18I_jEIR65bK3H26AojMsA9crqDW-kID6GFyFpOe3LAQ/edit#heading=h.vw24el6pa3ln)

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2023-12-01 17:01 UTC, cnharris10 commented on content/en/cloud_cost_management/aws.md
> +To use Cloud Cost Management, you must have an AWS account with access to Cost and Usage Reports (CURs), and have the AWS integration installed in Datadog. To set up Cloud Cost Management in Datadog,
```suggestion
To use Cloud Cost Management, you must have an AWS account with access to Cost and Usage Reports (CURs), and have the AWS integration installed in Datadog. To set up Cloud Cost Management in Datadog, you need to generate a legacy Cost and Usage report through AWS Billing.
```

2023-12-01 17:02 UTC, cnharris10 requested changes

2023-12-01 17:02 UTC, cnharris10 commented on content/en/cloud_cost_management/aws.md
> +To use Cloud Cost Management, you must have an AWS account with access to Cost and Usage Reports (CURs), and have the AWS integration installed in Datadog. To set up Cloud Cost Management in Datadog,
Targeting this: 
<img width="359" alt="image" src="https://github.com/DataDog/documentation/assets/17853509/3d52e962-0680-4858-bab2-16f91a55726e">

and not this:
<img width="1542" alt="image" src="https://github.com/DataDog/documentation/assets/17853509/24fc95dd-f8ea-4bf8-ae70-417e6c6f41be">

2023-12-02 03:32 UTC, urseberry requested changes

2023-12-02 03:32 UTC, urseberry commented on content/en/cloud_cost_management/aws.md
> +### Prerequisite: generate a Legacy Cost and Usage Report
```suggestion
### Prerequisite: generate a legacy Cost and Usage Report
```

2023-12-02 03:32 UTC, urseberry commented on content/en/cloud_cost_management/aws.md
> +### Locate the Legacy Cost and Usage Report
```suggestion
### Locate the legacy Cost and Usage Report
```

2023-12-02 03:32 UTC, urseberry commented on content/en/cloud_cost_management/aws.md
> +### Configure access to the Legacy Cost and Usage Report
```suggestion
### Configure access to the legacy Cost and Usage Report
```

2023-12-11 12:41 UTC, cnharris10 approved these changes

2023-12-11 12:41 UTC, cnharris10 commented on content/en/cloud_cost_management/aws.md
> +[Create a Cost and Usage Report][1] in AWS under the **Legacy Pages** section. You cannot create a report with data exports.
```suggestion
[Create a Cost and Usage Report][1] in AWS under the **Legacy Pages** section. At this time, there is no support for creating a Cost and Usage Report data exports.
```

2023-12-11 14:14 UTC, cnharris10 commented on content/en/cloud_cost_management/aws.md
> +[Create a Cost and Usage Report][1] in AWS under the **Legacy Pages** section. At this time, there is no support for creating a Cost and Usage Report data exports.
```suggestion
[Create a Cost and Usage Report][1] in AWS under the **Legacy Pages** section. At this time, there is no support for creating Cost and Usage Report data exports.
```

2023-12-11 17:09 UTC, alai97 commented on content/en/cloud_cost_management/aws.md
> +3. Follow the steps below to create a Cost and Usage report
```suggestion
1. Have an AWS account with billing access.
2. Have the AWS integration installed in Datadog.
3. Follow the steps below to create a Cost and Usage report.
```

2023-12-12 12:35 UTC, crousseaux commented on content/en/cloud_cost_management/aws.md
> +[Create a Cost and Usage Report][1] in AWS under the **Legacy Pages** section. At this time, there is no support for creating Cost and Usage Report data exports.
AWS released last week a new way of generating billing exports called "data exports". The previous way that we support has been moved under the "Legacy Pages" section.
We want to make it clear that they should continue to use the legacy way. We plan to provide support for data exports in the near future.

2023-12-12 18:51 UTC, urseberry approved these changes

2023-12-12 18:52 UTC, merged