Update summary.md
DataDog/documentation pull request #20905
Opened 2023-12-05 17:31 UTC by CyrusBelsoi

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-12-11 16:22 UTC, ijkaylin requested changes

2023-12-11 16:22 UTC, ijkaylin commented on content/en/metrics/summary.md
> +This information is also available via the Metrics APIs.
```suggestion
This information is also available via API here. 
```

Make sure to link to the API directly

2023-12-11 16:22 UTC, ijkaylin commented on content/en/metrics/summary.md
> +### Metrics Related Assets
```suggestion
## Metrics Related Assets
```

2023-12-11 16:22 UTC, ijkaylin commented on content/en/metrics/summary.md
> + Metrics related assets refers to any dashboard, notebook, monitor or SLO that queries a particular metric.
```suggestion
To determine the value of any metric name to your organization, use Metrics Related Assets. Metrics related assets refers to any dashboard, notebook, monitor or SLO that queries a particular metric. 

{{< img src="metrics/summary/IMAGEHERE.JPG" alt="Metrics Related Assets" style="width:75%;">}}
```

2023-12-11 16:22 UTC, ijkaylin commented on content/en/metrics/summary.md
> +1. Scroll down to the bottom of the metric’s details sidepanel, landing on the ‘Related Assets’ section.
```suggestion
1. Scroll down to the bottom of the metric's details sidepanel to the "Related Assets" section
```

2024-01-18 19:26 UTC, ijkaylin approved these changes

2024-01-18 20:03 UTC, aliciascott approved these changes
Looks good, I just fixed a couple small things that the vale linter was catching, did you want this merged as well ?

2024-01-18 20:49 UTC, CyrusBelsoi commented
> Looks good, I just fixed a couple small things that the vale linter was catching, did you want this merged as well ?

Hey @aliciascott thank you so much for the revie, yes please merge

2024-01-18 20:50 UTC, merged