[apm] Add data_jobs ingestion mechanism
DataDog/documentation pull request #20910
Opened 2023-12-05 20:23 UTC by raphaelgavache

### What does this PR do? What is the motivation?
Document new data_jobs span ingestion mechanism.

[Link to changed section
](https://docs-staging.datadoghq.com/raphael/add_data_jobs/tracing/trace_pipeline/ingestion_mechanisms/?tab=java#other-products)

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-12-05 20:24 UTC, raphaelgavache commented on content/en/tracing/trace_pipeline/ingestion_mechanisms.md
> +| Data Jobs Monitoring    | `data_jobs`                            | Traces ingested from Datadog Java Tracer spark integration or the Databricks integration. |
will add a link to data jobs public doc as soon as it's created

2023-12-06 13:21 UTC, dussault-antoine approved these changes

2023-12-06 13:22 UTC, warrierr approved these changes
LGTM

2023-12-06 16:40 UTC, buraizu requested changes
Thanks, just requesting some very minor updates

2023-12-06 16:40 UTC, buraizu commented on content/en/tracing/trace_pipeline/ingestion_mechanisms.md
> +| Data Jobs Monitoring    | `data_jobs`                            | Traces ingested from Datadog Java Tracer spark integration or the Databricks integration. |
```suggestion
| Data Jobs Monitoring    | `data_jobs`                            | Traces ingested from the Datadog Java Tracer Spark integration or the Databricks integration. |
```

2023-12-07 16:36 UTC, merged