Add Test Visibility and Intelligent Test Runner Documentation
DataDog/documentation pull request #20944
Opened 2023-12-07 22:30 UTC by alai97

### What does this PR do? What is the motivation?

Extracts Test Visibility and ITR documentation from CI Visibility doc set along with guides and troubleshooting content.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-12-11 23:08 UTC, drichards-87 requested changes
Looks good overall! I just had a few minor suggestions + I noted a couple of broken links.

2023-12-11 23:08 UTC, drichards-87 commented on content/en/intelligent_test_runner/troubleshooting/_index.md
> +[Intelligent Test Runner][12] works by analyzing your commit history along with code coverage information about past test runs to determine which tests need to be run and which ones can be safely ski
```suggestion
[Intelligent Test Runner][12] works by analyzing your commit history along with code coverage information about past test runs to determine which tests need to be run and which ones can be safely skipped. A minimum amount of information needs to exist in order for Intelligent Test Runner to work correctly:
```

2023-12-12 00:06 UTC, alai97 commented on content/en/tests/_index.md
> +    {{< nextlink href="tests/junit_upload" >}}Uploading JUnit test report files to Datadog{{< /nextlink >}}
```suggestion
    {{< nextlink href="tests/junit_xml" >}}Uploading JUnit test report files to Datadog{{< /nextlink >}}
```

2023-12-12 00:07 UTC, alai97 commented on content/en/tests/browser_tests.md
> +[1]: /tests/javascript/?tab=cypress#instrument-your-tests
```suggestion
[1]: /tests/setup/javascript/?tab=cypress#instrument-your-tests
```

2023-12-12 15:02 UTC, drichards-87 commented on content/en/tests/_index.md
> +    {{< nextlink href="tests/junit_xml" >}}Uploading JUnit test report files to Datadog{{< /nextlink >}}
```suggestion
    {{< nextlink href="tests/setup/junit_xml" >}}Uploading JUnit test report files to Datadog{{< /nextlink >}}
```

2023-12-12 15:08 UTC, romainkomorndatadog approved these changes
This looks good to me from the libraries side, but I'd like to defer to @KickingTheTV for the way this makes ITR a product separate from test visibility, so my approval's contingent on his approval.

2023-12-14 14:55 UTC, KickingTheTV approved these changes
LGTM

2023-12-14 18:18 UTC, merged