Add docs on composite monitor enrichment
DataDog/documentation pull request #20952
Opened 2023-12-08 10:01 UTC by Dalje-et

### What does this PR do? What is the motivation?

Explain sub-monitor enrichment in docs (e.g. `{{a.log.message}}`).

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-12-08 19:39 UTC, urseberry requested changes

2023-12-08 19:39 UTC, urseberry commented on content/en/monitors/notify/variables.md
> +Composite monitors also support tag variables in the same way as their underlying monitors. They follow the same format as other monitors, provided the underlying monitors are grouped by the same tag
```suggestion
Composite monitors also support tag variables in the same way as their underlying monitors. They follow the same format as other monitors, provided the underlying monitors are grouped by the same tag or facet.

For instance, assume your composite monitor has a sub-monitor `a`, which is a Logs monitor. You can include the value of any tag or facet of `a` with:
```

2024-01-29 10:26 UTC, Dalje-et commented
Sorry @urseberry, this PR kinda drowned over the holidays. Are we good to merge? :)

2024-02-20 19:58 UTC, urseberry approved these changes

2024-02-20 19:58 UTC, merged