[Database Monitoring] Update sqlserver setup documentation to mention log shipping
DataDog/documentation pull request #20989
Opened 2023-12-12 17:01 UTC by joelmarcotte

### What does this PR do? What is the motivation?
- Adds documentation about log shipping monitoring for the SQLServer integration, which will be available in agent 7.50+.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-12-12 19:23 UTC, ynnadkrap approved these changes

2023-12-12 19:52 UTC, cswatt requested changes
Left suggestions.

I'm also adding a `do not merge` label to this PR. Please let the documentation team know when this feature is available and we'll merge! Thanks!

2023-12-12 19:52 UTC, cswatt commented on content/en/database_monitoring/setup_sql_server/azure.md
> +-- If you intend on using monitoring log shipping (availably in agent v7.50+), proceed with the following:
```suggestion
-- To use Log Shipping Monitoring (available in Agent v7.50+), uncomment the next three lines:
```

2023-12-12 19:52 UTC, cswatt commented on content/en/database_monitoring/setup_sql_server/azure.md
> +-- If you intend on using monitoring log shipping (availably in agent v7.50+), proceed with the following:
```suggestion
-- To use Log Shipping Monitoring (available in Agent v7.50+), uncomment the next three lines:
```

2023-12-12 19:52 UTC, cswatt commented on content/en/database_monitoring/setup_sql_server/azure.md
> +-- If you intend on using monitoring log shipping (availably in agent v7.50+), proceed with the following:
```suggestion
-- To use Log Shipping Monitoring (available in Agent v7.50+), uncomment the next three lines:
```

2023-12-12 19:52 UTC, cswatt commented on content/en/database_monitoring/setup_sql_server/rds.md
> +- [Further reading](#further-reading)
```suggestion
1. [Configure the AWS integration](#configure-the-aws-integration)
1. [Grant the Agent access](#grant-the-agent-access)
1. [Install the Agent](#install-the-agent)
1. [Install the RDS integration](#install-the-rds-integration)
```

this is meant to be a numbered list of steps, not a table of contents (available in the right-hand panel)

2023-12-12 19:52 UTC, cswatt commented on content/en/database_monitoring/setup_sql_server/rds.md
> +-- If you intend on using log shipping monitoring (availably in agent v7.50), proceed with the following:
```suggestion
-- To use Log Shipping Monitoring (available in Agent v7.50+), uncomment the next line:
```

2023-12-12 19:52 UTC, cswatt commented on content/en/database_monitoring/setup_sql_server/selfhosted.md
> +- [Further reading](#further-reading)
```suggestion
1. [Grant the Agent access](#grant-the-agent-access)
1. [Install the Agent](#install-the-agent)
```

again, this is meant to be explicit steps, not a table of contents

2023-12-12 19:52 UTC, cswatt commented on content/en/database_monitoring/setup_sql_server/selfhosted.md
> +-- If you intend on using monitoring log shipping (availably in agent v7.50+), proceed with the following:
```suggestion
-- To use Log Shipping Monitoring (available in Agent v7.50+), uncomment the next three lines:
```

2023-12-12 19:52 UTC, cswatt commented on content/en/database_monitoring/setup_sql_server/selfhosted.md
> +-- If you intend on using monitoring log shipping (availably in agent v7.50+), proceed with the following:
```suggestion
-- To use Log Shipping Monitoring (available in Agent v7.50+), uncomment the next three lines:
```

2023-12-19 16:25 UTC, joelmarcotte commented
The feature is now available @cswatt so this is good to merge.

2024-01-04 16:23 UTC, cswatt approved these changes

2024-01-04 16:46 UTC, merged