[Metrics] Query Activity Facet Changes
DataDog/documentation pull request #21055
Opened 2023-12-15 16:40 UTC by ouracheal

### What does this PR do? What is the motivation?
Reflects changes in public doc for the new query activity facet.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2023-12-15 17:00 UTC, ijkaylin requested changes

2023-12-19 17:16 UTC, brett0000FF requested changes

2023-12-19 17:16 UTC, brett0000FF commented on content/en/metrics/summary.md
> +{{< img src="metrics/summary/configurationbuttons2.jpg" alt="Bulk Configuration Buttons" style="width:75%;">}}
```suggestion
{{< img src="metrics/summary/configurationbuttons2.png" alt="Bulk Configuration Buttons" style="width:75%;">}}
```

2023-12-19 17:16 UTC, brett0000FF commented on content/en/metrics/summary.md
> +* **Configuration** : Quickly identify metrics with tag configurations
I think we can trim these bullet points down and avoid the repetition. For example:

- **Configuration**: Metrics with tag configurations
- **Percentiles**: Distribution metrics enabled by percentiles/advanced query capabilities
- **Historical Metrics**: Disabled historical metrics
- **Query Activity**: Metrics not queried in Datadog products in the past 30 days
- **Metric Type**: Differentiate between distributions and non-distributions (counts, gauges, rates)
- **Distribution Metric Origin**: Metric origination by product (for example, metrics generated from Logs or APM Spans)

2023-12-19 22:29 UTC, brett0000FF approved these changes

2023-12-20 18:13 UTC, ijkaylin requested changes

2023-12-20 18:13 UTC, ijkaylin commented on content/en/metrics/summary.md
> +- **Query Activity** (Beta): Metrics not queried in the app or by the API in the past 30 days
```suggestion
- **Historical Metrics**: Metrics that have historical metrics ingestion enabled 
- **Query Activity** (Beta): Metrics not queried in the app or by the API in the past 30 days
```

2023-12-20 18:56 UTC, merged