DOCS-6928 - updating serverless lambda logs page
DataDog/documentation pull request #21116
Opened 2023-12-19 22:17 UTC by cswatt

### What does this PR do? What is the motivation?
Enhances Lambda Log Collection page with instructions for using the Forwarder

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

Should probably have explicit directions for disabling log collection through the forwarder.

2024-01-11 22:39 UTC, sumedham requested changes

2024-01-11 22:39 UTC, sumedham commented on content/en/serverless/aws_lambda/logs.md
> +- The [Datadog Lambda Extension][2], which collects logs in real time and bypasses CloudWatch.
I would say "pushes logs to Datadog in real time" vs. collects to be clear about how logs are transmitted to Datadog

2024-01-11 22:39 UTC, sumedham commented on content/en/serverless/aws_lambda/logs.md
> +- The [Datadog Forwarder][4], which forwards Lambda logs from CloudWatch. This setup increases redundancy, as you have an extra place to store your logs.
```suggestion
- The [Datadog Forwarder][4], which forwards Lambda logs from CloudWatch to Datadog. This setup increases redundancy, as you have an extra place to store your logs.
```

2024-01-11 22:39 UTC, sumedham commented on content/en/serverless/aws_lambda/logs.md
> +1. Deploy the [Datadog Forwarder][4].
I think this belongs in the 'Disable' section?

2024-01-11 22:39 UTC, sumedham commented on content/en/serverless/aws_lambda/logs.md
> +1. Deploy the [Datadog Forwarder][4].
I would link to these docs for the "enable" section

2026-08-03 19:11 UTC, jhgilbert commented
This PR was closed after six or more months of inactivity. If this was done in error, feel free to re-open the PR.

2026-08-03 19:11 UTC, closed without merging