Update RUM Next.js guide to recommend CDN method for Next.js app router
DataDog/documentation pull request #21226
Opened 2024-01-03 20:13 UTC by sfirrin

### What does this PR do? What is the motivation?
Updates the RUM Next.js doc to more strongly recommend that customers use the CDN method when using the Next.js app router

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-01-03 21:00 UTC, alai97 requested changes

2024-01-03 21:00 UTC, alai97 commented on content/en/real_user_monitoring/guide/monitor-your-nextjs-app-with-rum.md
> +   - If your application relies on the **newer** Next.js [App Router][1] (versions 13+), we recommend using the CDN RUM instrumentation to ensure that the RUM initialization occurs in the client. If
```suggestion
   - If your application relies on the **newer** Next.js [App Router][1] (versions 13+), Datadog recommends using the CDN RUM instrumentation to ensure that the RUM initialization occurs in the client. If you want to use the npm package, the initialization code must run in a [client component][5] so RUM can collect telemetry from the client. You can achieve this without making your [`layout.tsx`][2] file itself a client component by following the example below to create an empty `<DatadogInit />` component with the RUM initialization code, and then rendering that `<DatadogInit />` component in your `layout.tsx`.
```

2024-01-03 21:00 UTC, alai97 commented on content/en/real_user_monitoring/guide/monitor-your-nextjs-app-with-rum.md
> +   If using npm, you need to make a few small changes to the code snippet from the Datadog RUM UI before pasting it into either the root `layout.tsx` or custom `_app.tsx` file (Datadog supports both)
```suggestion
   When using npm, you need to make a few small changes to the code snippet from the Datadog RUM UI before pasting it into either the root `layout.tsx` or custom `_app.tsx` file (Datadog supports both):
```

2024-01-03 21:01 UTC, alai97 approved these changes

2024-01-08 09:03 UTC, yannickadam approved these changes

2024-01-08 19:44 UTC, merged