Add files via upload
DataDog/documentation pull request #21286
Opened 2024-01-08 21:53 UTC by CyrusBelsoi

### What does this PR do? What is the motivation?

Adding new media to update docs to accurately reflect newer feature releases

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-01-08 23:21 UTC, brett0000FF requested changes
Thanks for adding these images! I added a commit to update the reference to facets4 in the Metrics summary page.

Where should we add the Related Assets beta image?

2024-01-10 17:25 UTC, CyrusBelsoi commented
> Thanks for adding these images! I added a commit to update the reference to facets4 in the Metrics summary page.
> 
> Where should we add the Related Assets beta image?

Hey Brett, the related assets image will be added to an upcoming "Metrics Related Assets" sections - to be added to docs soon

2024-01-10 20:04 UTC, ijkaylin approved these changes

2024-01-11 17:07 UTC, brett0000FF approved these changes
@CyrusBelsoi - Got it--thanks for the clarification! 

Edit: Actually, I think the parentheses might be causing an error in the file name. Could we please remove those? Something like `related-assets-beta-tags.png` instead.

2024-01-11 20:47 UTC, closed without merging