Improve explanation of code coverage in excluded branches
DataDog/documentation pull request #21333
Opened 2024-01-11 15:27 UTC by edrevo

### What does this PR do? What is the motivation?

Add some context on how code coverage works on excluded branches.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-01-24 13:17 UTC, KickingTheTV requested changes
overall LGTM, but added a few modifications

2024-01-24 13:17 UTC, KickingTheTV commented on content/en/intelligent_test_runner/_index.md
> +Excluded branches still collect per-test code coverage, so you might notice a performance impact on your excluded branches. However, code coverage is enabled
Excluded branches collect per-test code coverage, which will have a performance impact on the total testing time. However, this performance impact is mitigated by only collecting code coverage when Datadog detects that running with code coverage will generate enough new coverage information that it offsets the cost of collecting the coverage.

2024-01-24 13:23 UTC, edrevo commented
Wording changed.

2024-01-24 15:44 UTC, buraizu requested changes
Looks good overall, just requesting a couple of minor wording changes per the [documentation style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#tense)

2024-01-24 15:44 UTC, buraizu commented on content/en/intelligent_test_runner/_index.md
> +Excluded branches collect per-test code coverage, which will have a performance impact on the total testing time. However, this performance impact is mitigated by only collecting code coverage when D
```suggestion
Excluded branches collect per-test code coverage, which has a performance impact on the total testing time. However, this performance impact is mitigated by only collecting code coverage when Datadog detects that running with code coverage generates enough new coverage information that it offsets the cost of collecting the coverage. You can check whether a test session has code coverage enabled or not by looking at the `@test.code_coverage.enabled` field.
```

2024-01-26 22:10 UTC, buraizu approved these changes
LGTM

2024-01-28 17:57 UTC, KickingTheTV approved these changes

2024-01-29 09:14 UTC, edrevo commented
@buraizu, i'm getting a weird error in CI: https://app.datadoghq.com/logs?query=ci.pipeline_correlation_id%3A2297adb264c4e345%20ci.job_correlation_id%3Ad1df7fade70b89b1%20&cols=%40ci.job.name&event=AgAAAY1T4P0q0v6RbAAAAAAAAAAYAAAAAEFZMVQ0TGgtQUFDZWFkWGczQWdyQUFBQQAAACQAAAAAMDE4ZDUzZTktMGM0My00ODZlLWE0YjAtMzNjYTM5NzdmMmE2&index=&messageDisplay=inline&refresh_mode=paused&stream_sort=time%2Cdesc&viz=stream&from_ts=1706507984000&to_ts=1706510130000&live=false

do you know if this is something related to the build itself or my PR?

2024-01-30 14:14 UTC, edrevo commented
@buraizu , the CI is now green. Can you merge? Thanks!

2024-01-30 19:20 UTC, merged