security ootb deeplinks - [WEB-4345]
DataDog/documentation pull request #21461
Opened 2024-01-19 20:17 UTC by StefonSimmons

### What does this PR do? What is the motivation?

adds buttons that direct users to the product. 

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-01-29 20:40 UTC, bgdeutsch commented on layouts/security_rules/single.html
> +				{{ $view_findings_text = "View Identity Risks"}}
hey @StefonSimmons would you mind fixing the indentation here?

2024-01-31 15:34 UTC, brett0000FF requested changes
Wow, this is really cool! Thanks for all your work on this. I just left one comment about switching `cache_enabled` back to `true`.

Otherwise, the new functionality worked great for me from the preview site.

2024-01-31 15:34 UTC, brett0000FF commented on local/bin/py/build/configurations/pull_config_preview.yaml
> +    cache_enabled: false
```suggestion
    cache_enabled: true
```

2024-01-31 15:47 UTC, bgdeutsch approved these changes
LGTM 👍

2024-01-31 16:14 UTC, brett0000FF approved these changes

2024-01-31 16:15 UTC, merged