PROF-8999: Describe timelines view for Node.js
DataDog/documentation pull request #21511
Opened 2024-01-24 16:29 UTC by szegedi

### What does this PR do? What is the motivation?
Timelines for Node.js are in public beta, we should document them for users.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes
For most languages, the text in respective language tab for timelines in `profile_visualizations` and `connect_traces_and_profiles` is the same. Here, the text in the latter does not have description of one kind of lanes ("asynchronous activity".) This is intentional, as sadly we can't associate those activities with a particular trace, so they don't show there.

2024-01-24 23:09 UTC, buraizu requested changes
Looks good overall, just left some minor wording updates per the [documentation style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#tense)

2024-01-24 23:09 UTC, buraizu commented on content/en/profiler/connect_traces_and_profiles.md
> +Lanes on the top are **runtime activities** that may add extra latency to your request, currently these are garbage collector activities.
```suggestion
Lanes on the top are garbage collector **runtime activities** that may add extra latency to your request.
```

2024-01-24 23:09 UTC, buraizu commented on content/en/profiler/profile_visualizations.md
> +There can also be lanes visualizing various kinds of **asynchronous activity**, currently these are DNS requests and TCP connect operations. The number of lanes matches
```suggestion
There can also be lanes visualizing various kinds of **asynchronous activity** consisting of DNS requests and TCP connect operations. The number of lanes matches
```

2024-01-24 23:09 UTC, buraizu commented on content/en/profiler/profile_visualizations.md
> +Lanes on the top are **runtime activities** that may add extra latency to your request. Currently these are various garbage collection activities.
```suggestion
Lanes on the top are garbage collector **runtime activities** that may add extra latency to your request.
```

2024-01-25 10:57 UTC, szegedi commented
> Looks good overall, just left some minor wording updates per the documentation style guide

Awesome; I was unhappy with the wording there myself, but couldn't hit on the shape that'd feel right. Your suggestions certainly do. Thank you @buraizu!

2024-01-25 18:28 UTC, buraizu approved these changes

2024-01-25 18:29 UTC, merged