DOCS-7104 Add Software Composition Analysis Documentation
DataDog/documentation pull request #21528
Opened 2024-01-25 19:09 UTC by alai97

### What does this PR do? What is the motivation?

Adds a section for Software Composition Analysis in the Code Analysis doc set + screenshots.
 
### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-01-30 19:38 UTC, alai97 commented on local/bin/py/build/configurations/pull_config_preview.yaml
> +          branch: alai97/configure-ci-cd-provider-instructions
```suggestion
          branch: main
```

2024-01-30 19:38 UTC, alai97 commented on local/bin/py/build/configurations/pull_config_preview.yaml
> +              dependencies: ["https://github.com/DataDog/datadog-sca-github-action/blob/alai97/configure-ci-cd-provider-instructions/README.md"]
```suggestion
              dependencies: ["https://github.com/DataDog/datadog-sca-github-action/blob/main/README.md"]
```

2024-02-05 23:42 UTC, aliciascott requested changes
Hey @alai97 , looking good! I added a few comments and suggestions for wording and flow, let me know if you have any questions :)

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +[1]: /getting_started/application_security/software_composition_analysis
```suggestion
[1]: /security/application_security/software_composition_analysis/
```
I  think we should link to the main ASM - SCA doc as I'm linking to the SCA getting started page from there and it has more context.

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +For more information, see the [Application Security documentation][4].
```suggestion
```
Since we are changing the above link to the ASM SCA main landing page I think we can remove this line.

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +[4]: /security/application_security/software_composition_analysis/
```suggestion
```
Can remove this too since we replaced it in [1]

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +1. Go
```suggestion
- Go
```

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +2. Java
```suggestion
- Java
```

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +4. Python
```suggestion
- Python
```

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +3. NodeJS
```suggestion
- Node.js
```

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +5. Ruby
```suggestion
- Ruby
```
Maybe personal preference but I think it reads better with dashes instead of numbers.

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +After you configure your CI pipelines to run Datadog SCA, violations are summarized per repository on the [Code Analysis page][1]. After drilling down to a specific repository, SCA results are divide
```suggestion
After you configure your CI pipelines to run Datadog SCA, violations are summarized per repository on the [Code Analysis page][2]. Drill down to a specific repository, observer that SCA results are divided into the **Library Vulnerabilities** and **Library List** lenses. 
```
What is the Code Analysis page suppose to be ? Right now this links to the ASM SCA page. [1], I took a guess and  changed it to [2] ? But this is the setup page (in-app) so maybe double check this :)

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +* Full Description: A description of the vulnerability contained within this specific version of the library.
```suggestion
- **Full Description**: A description of the vulnerability contained within this specific version of the library.
```

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/_index.md
> +* Event: JSON metadata regarding the SCA violation event.
```suggestion
- **Event**: JSON metadata regarding the SCA violation event.
```

2024-02-05 23:42 UTC, aliciascott commented on content/en/code_analysis/software_composition_analysis/setup.md
> +When setting up [Code Analysis][2] on your project, select **Enable Software Composition Analysis**.
```suggestion
When setting up [Code Analysis][2] on your project, select **Enable Software Composition Analysis**.
```
Is there a place in-app we could link to here as well? Such as "Navigate to...., select .." ?

2024-02-08 20:02 UTC, markazerdd approved these changes

2024-02-12 14:56 UTC, merged