Add CircleCI log collection to CircleCI CI Visibility docs
DataDog/documentation pull request #21611
Opened 2024-01-31 17:24 UTC by calvarjorge

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-01-31 20:57 UTC, brett0000FF requested changes
Some language tweak recommendations and fixing the broken link. Let me know if you have any questions. 🙂

2024-01-31 20:57 UTC, brett0000FF commented on content/en/continuous_integration/pipelines/circleci.md
> +[11]: integrations/circleci/#setup
```suggestion
[11]: /integrations/circleci/#setup
```

2024-01-31 20:57 UTC, brett0000FF commented on content/en/continuous_integration/pipelines/circleci.md
> +The DataDog CircleCI integration allows to collect logs from your finished CircleCI jobs and forward them to DataDog.
```suggestion
The Datadog CircleCI integration collects logs from your finished CircleCI jobs and forwards them to Datadog.
```

2024-01-31 20:57 UTC, brett0000FF commented on content/en/continuous_integration/pipelines/circleci.md
> +To enable this feature, follow [this guide][11] to install and configure the DataDog CircleCI integration.
```suggestion
To install and configure this integration, follow the [CircleCI setup guide][11].
```

2024-02-01 10:57 UTC, drodriguezhdez approved these changes

2024-02-01 15:24 UTC, brett0000FF approved these changes
Thanks!

2024-02-01 15:24 UTC, merged