[DOCS-6319] Standard Attribute Updates
DataDog/documentation pull request #21632
Opened 2024-02-01 15:53 UTC by brett0000FF

### What does this PR do? What is the motivation?

- Merge duplicate logs and APM entries.
- Link from Span Attributes page to Default Attributes table.
- Removed duplicate content.
- Add more content comparing span attributes and tags.
- Include page in Agent section of TOC.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-02-12 13:41 UTC, yoannrobin requested changes

2024-02-12 13:41 UTC, yoannrobin commented on content/en/tracing/trace_collection/tracing_naming_convention/_index.md
> +- **Container tags**: `container_name`, k`ube_deployment`, `pod_name`
```suggestion
- **Container tags**: `container_name`, `kube_deployment`, `pod_name`
```

2024-02-12 13:41 UTC, yoannrobin commented on content/en/tracing/trace_collection/tracing_naming_convention/_index.md
> +Tags are usually enriched from other data sources like host tags, container tags, or service catalog tags. These tags are added to the span to describe the context. For example, tags might describe t
```suggestion
Tags are usually enriched from other data sources like tags sourced from host, container, or service catalog. These tags are added to the span to describe the context. For example, tags might describe the properties of the host and the container the span is coming from, or the properties of the services the span is emitted from.
```

2024-02-12 13:41 UTC, yoannrobin commented on content/en/tracing/trace_collection/tracing_naming_convention/_index.md
> +One span can have multiple tags with the same key. For example, consider a `team` tag. You might have one `team` tag that describes the team owning the infrastructure layer (host tag), and another `t
I would get rid of this part. The multiple values with the same key does not work everywhere and can be misleading

2024-02-12 13:41 UTC, yoannrobin commented on content/en/tracing/trace_collection/tracing_naming_convention/_index.md
>      - link: 'logs/log_configuration/attributes_naming_convention'
Probably worth adding a link to the naming convention in the further reading links

2024-02-23 22:00 UTC, hestonhoffman approved these changes
LGTM!

2024-03-01 16:04 UTC, yoannrobin approved these changes

2024-03-01 16:25 UTC, merged