Add documentation about code-level-vulnerability in Python
DataDog/documentation pull request #21645
Opened 2024-02-02 13:08 UTC by juanjux

### What does this PR do? What is the motivation?
It add information about the soon-to-be-public-beta code level vulnerability feature for Python.

### Merge instructions
Waiting for the public beta announcement, do not merge.

- [ ] Please merge after reviewing

2024-07-10 10:32 UTC, juanjux commented
@DataDog/documentation ready to review and merge.

2024-07-10 10:47 UTC, gnufede commented on content/en/security/application_security/enabling/tracing_libraries/code_security/python.md
> +  - /security/application_security/getting_started/dotnet
```suggestion
  - /security_platform/application_security/getting_started/python
  - /security/application_security/getting_started/python
```

2024-07-10 10:47 UTC, gnufede commented on content/en/security/application_security/enabling/tracing_libraries/code_security/python.md
> +    - link: 'https://github.com/DataDog/dd-trace-dotnet'
```suggestion
    - link: 'https://github.com/DataDog/dd-trace-py'
```

2024-07-10 10:48 UTC, gnufede commented on content/en/security/application_security/enabling/tracing_libraries/code_security/python.md
> +      text: '.NET Datadog library source code'
```suggestion
      text: 'Python Datadog library source code'
```

2024-07-10 10:48 UTC, gnufede commented on content/en/security/application_security/enabling/tracing_libraries/code_security/python.md
> +If your service runs a [tracing library version that supports Vulnerability Management for code-Level vulnerability detection][3], enable the capability by setting the `DD_IAST_ENABLED=true` environm
```suggestion
If your service runs a [tracing library version that supports Vulnerability Management for Code-Level vulnerability detection][3], enable the capability by setting the `DD_IAST_ENABLED=true` environment variable and restarting your service.
```

2024-07-10 10:49 UTC, gnufede commented on content/en/security/application_security/enabling/tracing_libraries/code_security/python.md
> +To detect code-level vulnerabilities for your service:
```suggestion
To detect Code-Level vulnerabilities for your service:
```

2024-07-10 11:11 UTC, gnufede approved these changes

2024-07-10 18:34 UTC, buraizu commented
Thanks, created DOCS-8411 to review

2024-07-18 19:51 UTC, michaelcretzman requested changes
this Python page was not integrated into the Enabling Code Security using Datadog Tracing Libraries page.

There should be a card for Python here, just like the other languages:
https://docs-staging.datadoghq.com/juanjux/code-level-vulns-python/security/application_security/enabling/tracing_libraries/code_security/

2024-07-26 08:19 UTC, juanjux commented
> this Python page was not integrated into the Enabling Code Security using Datadog Tracing Libraries page.
> 
> There should be a card for Python here, just like the other languages: https://docs-staging.datadoghq.com/juanjux/code-level-vulns-python/security/application_security/enabling/tracing_libraries/code_security/

Card added, please take a look, thanks!

2024-07-29 17:48 UTC, michaelcretzman approved these changes

2024-07-29 17:57 UTC, merged