Update _index.md
DataDog/documentation pull request #21697
Opened 2024-02-06 21:31 UTC by ddjessicay

Updating docs to reflect feature release

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-02-06 23:22 UTC, buraizu requested changes
Thanks for the PR; just requesting a minor update to comply with our style guide

2024-02-06 23:22 UTC, buraizu commented on content/en/infrastructure/resource_catalog/_index.md
> +To find a particular resource, search by its name. To filter the list to see a subset of resources you're most interested in, select facets on the left panel. For example, you may find it helpful to
```suggestion
To find a particular resource, search by its name. To filter the list to see a subset of resources you're most interested in, select facets on the left panel. For example, you may find it helpful to filter by your team name, or to scope the misconfigurations to particular environments and clusters. To access the relevant cloud console, select the cloud console icon for the desired resource. 
```

2024-02-07 17:30 UTC, buraizu approved these changes

2024-02-07 17:31 UTC, buraizu commented
@ddjessicay thanks for making that update. Let me know if this change is ready to be merged

2024-02-07 17:35 UTC, ddjessicay commented
@buraizu Yes it's ready to be merged, sorry I may have clicked merge master branch into this branch - hopefully this doesn't result in any errors! Thanks

2024-02-07 19:13 UTC, merged