Document rare segmentation fault triggered by Ruby profiler
DataDog/documentation pull request #21752
Opened 2024-02-09 10:24 UTC by ivoanjo

### What does this PR do? What is the motivation?

This PR documents an issue triggered by the Ruby profiler in certain Ruby VM versions (see
<https://github.com/DataDog/dd-trace-rb/issues/3430> and <https://bugs.ruby-lang.org/issues/19991> for reference), as well as the current recommended solution for this issue.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

N/A

2024-02-09 16:59 UTC, aliciascott requested changes
Just a quick wording suggestion as we want to avoid words like "we/ we've" , let me know once updated, request re review and I'll get it merged :)

2024-02-09 16:59 UTC, aliciascott commented on content/en/profiler/profiler_troubleshooting/ruby.md
> +In rare situations, we've discovered that the profiler can trigger [Ruby VM Bug #19991][12] that manifests itself as a "Segmentation fault" with a crash stack trace including the `gc_finalize_deferre
```suggestion
In rare situations, the profiler can trigger [Ruby VM Bug #19991][12] that manifests itself as a "Segmentation fault" with a crash stack trace including the `gc_finalize_deferred` function.
```

2024-02-12 15:25 UTC, ivoanjo commented
Suggestion sounds good, thank you! We're actually going to try to have a workaround in the library for this too, but I think for now let's go with the doc and I may come back later with a tweak that says "on version xx and above the workaround is no longer needed". :)

2024-02-12 20:25 UTC, aliciascott approved these changes
looks good !

2024-02-12 20:25 UTC, merged