updated slo summary widget initial updates
DataDog/documentation pull request #21858
Opened 2024-02-20 16:56 UTC by roxanne-moslehi

### What does this PR do? What is the motivation?

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-02-20 16:57 UTC, roxanne-moslehi commented
Updates to make:
- update screenshot used

2024-02-20 18:22 UTC, mmeyer724 commented on content/en/dashboards/widgets/slo.md
> +  - `Groups`: displays a table of status percentages for each monitor
```suggestion
  - `Monitors`: displays a table of status percentages for each monitor
```
Looks like an error in our existing documentation. For multi-monitor SLOs, this option is named 'Monitors'

2024-02-20 19:32 UTC, buraizu requested changes
Thanks for the PR, requested some minor edits and clarifications.

Additionally, it looks like the new screenshot shows information about Datadog data centers. Could you re-load the image with obfuscated group values, or otherwise provide a fresh image?

2024-02-20 20:50 UTC, roxanne-moslehi commented
Thanks @buraizu for the comments - I will make updates. We will still need to wait to merge this PR since we are testing out the new features still. For the image, I just have that as a placeholder and will update, but the groups will always be cut off since it's a scrollable preview of the groups.

2024-02-23 20:48 UTC, roxanne-moslehi commented
@buraizu also FYI @estherk15 - We are going to start releasing this feature next week and will need to merge in the updated docs. I've made all changes on my end and will follow up when I'm ready to merge this in?

2024-02-23 20:54 UTC, estherk15 commented
@roxanne-moslehi There's one unresolved suggestion: https://github.com/DataDog/documentation/pull/21858/files#r1496299959
After Bryce approves, this is good to go, feel free to ping either of us or #documentation to merge!

2024-02-28 15:43 UTC, roxanne-moslehi commented
@estherk15 @buraizu This is ready to merge now

2024-02-28 16:01 UTC, estherk15 approved these changes

2024-02-28 16:16 UTC, merged