[RUM-3349] RUM Browser consent management doc
DataDog/documentation pull request #22087
Opened 2024-03-06 16:45 UTC by BenoitZugmeyer

### What does this PR do? What is the motivation?

Document https://github.com/DataDog/browser-sdk/pull/2634

### Merge instructions

This should be merged after https://github.com/DataDog/browser-sdk/pull/2634 is released. Please ask me or @nhientrandatadog  before merging.

### Additional notes

2024-03-06 23:14 UTC, cswatt commented
created DOCS-7391 to review.

2024-03-07 15:49 UTC, bcaudan approved these changes
LGTM

2024-03-07 21:37 UTC, nhientrandatadog approved these changes
lgtm!

2024-03-11 17:33 UTC, rtrieu requested changes
Some minor feedback suggestions, but otherwise looks good!

2024-03-11 17:33 UTC, rtrieu commented on content/en/real_user_monitoring/browser/_index.md
> +Whether the user granted their tracking consent. See [User Tracking Consent][27].
```suggestion
Affirm whether the user has granted their tracking consent. See [User Tracking Consent][27].
```

2024-03-11 17:33 UTC, rtrieu commented on content/en/real_user_monitoring/browser/advanced_configuration.md
> +To be compliant with the GDPR, CCPA and similar regulations, the RUM Browser SDK allows to provide the tracking consent value at initialization.
```suggestion
To be compliant with the GDPR, CCPA and similar regulations, the RUM Browser SDK lets you provide the tracking consent value at initialization.
```

2024-03-11 17:33 UTC, rtrieu commented on content/en/real_user_monitoring/browser/advanced_configuration.md
> +* when changed from `"granted"` to `"not-granted"`, the RUM session is stopped, and no data will be sent anymore.
```suggestion
* when changed from `"granted"` to `"not-granted"`, the RUM session is stopped, data is no longer sent to Datadog.
```

2024-03-11 17:33 UTC, rtrieu commented on content/en/real_user_monitoring/browser/advanced_configuration.md
> +* when changed from `"not-granted"` to `"granted"`, a new RUM session is be created if no previous session is active, and data collection is be started again.
```suggestion
* when changed from `"not-granted"` to `"granted"`, a new RUM session is created if no previous session is active, and data collection resumes.
```

2024-03-11 17:33 UTC, rtrieu commented on content/en/logs/log_collection/javascript.md
> +| `trackingConsent`          | `"granted"` or `"not-granted"`                                            | No       | `"granted"`     | Whether the user granted their tracking consent. See [User Trac
Not sure if this is an affirmation or indication of the user's preference.

2024-03-12 13:27 UTC, BenoitZugmeyer commented on content/en/logs/log_collection/javascript.md
> +| `trackingConsent`          | `"granted"` or `"not-granted"`                                            | No       | `"granted"`     | Whether the user granted their tracking consent. See [User Trac
I'm not sure about what's the best wording here. I'm not used to see the verb "affirm" within documentation... maybe we could keep it simple and reword it as:
```
Set the initial user tracking consent state.
````
so it's in-line with the `setTrackingConsent` API wording

2024-03-12 13:30 UTC, rtrieu commented on content/en/logs/log_collection/javascript.md
> +| `trackingConsent`          | `"granted"` or `"not-granted"`                                            | No       | `"granted"`     | Whether the user granted their tracking consent. See [User Trac
Thanks Benoit, I agree with you, I think set would be the most simple and clear here.

2024-03-12 13:41 UTC, rtrieu requested changes
Hi @BenoitZugmeyer, sorry, I missed one edit.

2024-03-12 13:41 UTC, rtrieu commented on content/en/real_user_monitoring/browser/advanced_configuration.md
> +To be compliant with GDPR, CCPA and similar regulations, the RUM Browser SDK lets you provide the tracking consent value at initialization.
```suggestion
To be compliant with GDPR, CCPA, and similar regulations, the RUM Browser SDK lets you provide the tracking consent value at initialization.
```

2024-03-12 13:45 UTC, rtrieu approved these changes
Looks good, thanks!

2024-03-12 14:14 UTC, merged