Update java_sqs.md
DataDog/documentation pull request #22196
Opened 2024-03-13 21:02 UTC by Nancyzhu278

updating Java docs with SQS

### What does this PR do? What is the motivation?

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-03-13 21:43 UTC, drichards-87 requested changes
Left you some light feedback.

2024-03-13 21:43 UTC, drichards-87 commented on content/en/data_streams/java.md
> +### Libraries Supported
```suggestion
### Supported libraries
```

2024-03-13 21:43 UTC, drichards-87 commented on content/en/data_streams/java.md
> +### Monitoring SQS Pipelines
```suggestion
### Monitoring SQS pipelines
```

2024-03-13 21:43 UTC, drichards-87 commented on content/en/data_streams/java.md
> +Data Streams Monitoring uses one [message attribute][4] to track a message's path through an SQS queue. As Amazon SQS has a maximum limit of 10 message attributes allowed per message, all messages st
```suggestion
Data Streams Monitoring uses one [message attribute][4] to track a message's path through an SQS queue. As Amazon SQS has a maximum limit of 10 message attributes allowed per message, all messages streamed through the data pipelines must have 9 or fewer message attributes set, allowing the remaining attribute for Data Streams Monitoring.
```

2024-04-04 16:22 UTC, aliciascott approved these changes

2024-04-04 16:23 UTC, merged