[CIVIS-9536] Add documentation for AWS CodePipelines running pipelines
DataDog/documentation pull request #22331
Opened 2024-03-25 16:46 UTC by ManuelPalenzuelaDD

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-03-25 21:57 UTC, buraizu requested changes
Thanks for the PR, just requesting a minor style update

2024-03-25 21:57 UTC, buraizu commented on content/en/continuous_integration/pipelines/awscodepipeline.md
> +    - NOTE: Running pipelines don't have git information until they have finished.
```suggestion
    - **Note**: Running pipelines don't have Git information until they have finished.
```

2024-03-26 10:03 UTC, ManuelPalenzuelaDD commented on content/en/continuous_integration/pipelines/_index.md
> +|  | Jenkins | GitLab | CircleCI | Buildkite | GitHub Actions | Azure Pipelines | Codefresh | TeamCity | AWS CodePipeline | Other CI Providers |
The CI provider name is AWS CodePipeline

2024-03-26 12:04 UTC, drodriguezhdez approved these changes
LGTM

2024-03-26 15:49 UTC, buraizu approved these changes
LGTM; let me know when this PR is ready to merge

2024-03-26 16:23 UTC, ManuelPalenzuelaDD commented
@buraizu Thank you! It should be ready, i forgot to tick the box 🙇

2024-03-27 14:13 UTC, merged