[CLOUDCRAFT-457] Crafting Better Diagrams: Cloudcraft's Live Diagramming and Filtering
DataDog/documentation pull request #22461
Opened 2024-04-02 17:51 UTC by jamesponddotco

### What does this PR do? What is the motivation?
Add the beginning of an article about the new live experience in Cloudcraft. Still need to work on an introduction and conclusion, so the article is here mostly for discussion.

### Merge instructions
Please wait until the Cloudcraft team has reviewed the content before going ahead with the review and merging of the article.

- [x] Please merge after reviewing

2024-04-02 18:16 UTC, licaroline commented on content/en/cloudcraft/getting-started/crafting-better-diagrams.md
> +Under **Region**, select the regions you want to scan. By default, `Global` and `US East (N. Virginia)` are selected, but you can click the **More** button to select or search for additional regions.
We select `Global` and whichever region they configured as their default region by default, with `US East (N. Virginia)` being the fallback region if they don't have any default region configured. Similarly, Azure regions selected by default are `Global` and their configured default region, or `East US`

2024-04-02 18:16 UTC, licaroline commented on content/en/cloudcraft/getting-started/crafting-better-diagrams.md
> +Tags are automatically detected from your AWS account and displayed in the **Custom tags**, **AWS tags**, and **Kubernetes tags** sections.
There is also a "Terraform tags" section, which are tags automatically added to resources by Terraform

2024-04-03 17:48 UTC, jamesponddotco commented
@licaroline Added an introduction, conclusion, and a few more pieces here and there. Please review when you have time :)

2024-04-03 19:30 UTC, maycmlee commented
Created [DOCS-7581](https://datadoghq.atlassian.net/browse/DOCS-7581) for docs review when this is ready.

2024-04-03 20:22 UTC, jamesponddotco commented
@maycmlee Content itself should be ready, so you can go ahead and review, if you have the time :)

2024-04-04 16:19 UTC, licaroline commented
Should the second video be cropped more? It is showing selection of EC2 and RDS in the beginning, which is shown in the first video

2024-04-04 16:26 UTC, jamesponddotco commented
> Should the second video be cropped more? It is showing selection of EC2 and RDS in the beginning, which is shown in the first video

I left it in its entirety in the case the user didn't watch the first one.

2024-04-08 15:08 UTC, licaroline approved these changes

2024-04-08 17:39 UTC, estherk15 requested changes
The closing tag for `nextlink` needs to match. Most suggestions are for formatting, let me know if have any questions!

2024-04-08 17:39 UTC, estherk15 commented on content/en/cloudcraft/getting-started/create-your-first-cloudcraft-diagram.md
> +<div class="alert alert-info">If you are using Cloudcraft's new live experience, please read this article instead: <a href="https://docs.datadoghq.com/cloudcraft/getting-started/crafting-better-diagr
```suggestion
<div class="alert alert-info">If you are using Cloudcraft's New Live Experience, see this documentation: <a href="https://docs.datadoghq.com/cloudcraft/getting-started/crafting-better-diagrams/" title="Crafting Better Diagrams: Cloudcraft's Live Diagramming and Filtering">Crafting Better Diagrams: Cloudcraft's Live Diagramming and Filtering</a>.</div>
```

2024-04-08 17:39 UTC, estherk15 commented on content/en/cloudcraft/getting-started/crafting-better-diagrams.md
> +<hr>
```suggestion
## Feedback
```

2024-04-08 17:39 UTC, estherk15 commented on content/en/cloudcraft/getting-started/crafting-better-diagrams.md
> +Cloudcraft's new live experience is part of an ongoing effort to improve the user experience and make cloud infrastructure diagramming more efficient and effective. We're excited to see how you use t
```suggestion
Cloudcraft's New Live Experience is part of an ongoing effort to improve the user experience and make cloud infrastructure diagramming more efficient and effective. Tell us how you use these new features and [give feedback in this form][3].
```

2024-04-08 17:39 UTC, estherk15 commented on content/en/cloudcraft/getting-started/crafting-better-diagrams.md
> +Click **Apply layout** to create a diagram showing only the selected resources.
```suggestion
```suggestion

## Use cases

### Create a diagram showing only EC2 instances and RDS databases

1. Click the **Resource** section.
1. Deselect all resource types, and select **EC2** and **RDS**.
1. Click **Apply layout** to create a diagram showing only the selected resources.

{{< img src="cloudcraft/getting-started/crafting-better-diagrams/select-specific-resources.mp4" alt="A 9 seconds video showing a Cloudcraft user selecting EC2 and RDS instances from the Resource section." video="true">}}
```

2024-04-08 17:39 UTC, estherk15 commented on content/en/cloudcraft/getting-started/crafting-better-diagrams.md
> +Click **Apply layout** to create a diagram showing only the selected resources without the `Environment` tag.
```suggestion
### Create a diagram showing EC2 instances and RDS databases without the `Environment` tag

1. Click the **Resource** section.
1. Deselect all resource types, and select **EC2** and **RDS**.
1. Click the **Custom tags** section.
1. Click the **Environment** tag, and leave only the `Untagged` option selected.
1. Click **Apply layout** to create a diagram showing only the selected resources without the `Environment` tag.

{{< img src="cloudcraft/getting-started/crafting-better-diagrams/select-specific-resources-and-tags.mp4" alt="A 15 seconds video showing a Cloudcraft user selecting EC2 and RDS instances and untagged resources from the Resource and Custom tags sections." video="true">}}
```

2024-04-08 17:39 UTC, estherk15 commented on content/en/cloudcraft/getting-started/use-filters-to-create-better-diagrams.md
> +<div class="alert alert-info">If you are using Cloudcraft's new live experience, please read this article instead: <a href="https://docs.datadoghq.com/cloudcraft/getting-started/crafting-better-diagr
```suggestion
<div class="alert alert-info">If you are using Cloudcraft's New Live Experience, see this documentation: <a href="https://docs.datadoghq.com/cloudcraft/getting-started/crafting-better-diagrams/" title="Crafting Better Diagrams: Cloudcraft's Live Diagramming and Filtering">Crafting Better Diagrams: Cloudcraft's Live Diagramming and Filtering</a>.</div>
```

2024-04-08 17:39 UTC, estherk15 commented on content/en/cloudcraft/getting-started/crafting-better-diagrams.md
> +{{< img src="cloudcraft/getting-started/crafting-better-diagrams/enable-new-experience.png" alt="Screenshot highlighting the switch to enable the new live experience beta feature in the Cloudcraft in
```suggestion
{{< img src="cloudcraft/getting-started/crafting-better-diagrams/enable-new-experience.png" alt="Screenshot highlighting the switch to enable the new live experience beta feature in the Cloudcraft interface with a red arrow pointing to the switch." responsive="true" style="width:80%;">}}
```

2024-04-08 17:51 UTC, jamesponddotco commented
@estherk15 Ready for a second review, then :)

2024-04-08 19:50 UTC, estherk15 approved these changes

2024-04-08 19:50 UTC, estherk15 commented on content/en/cloudcraft/getting-started/crafting-better-diagrams.md
> +To enable the new live experience, toggle the **New Live Experience** switch at the top of the **Live** tab in Cloudcraft.
```suggestion
To enable, toggle the **New Live Experience** switch at the top of the **Live** tab in Cloudcraft.
```

2024-04-08 19:50 UTC, estherk15 commented on content/en/cloudcraft/getting-started/crafting-better-diagrams.md
> +If you're a new user, you may already have the new live experience enabled by default.
```suggestion
If you're a new user, you may already have the New Live Experience enabled by default.
```

2024-04-08 20:19 UTC, jamesponddotco commented
@estherk15 Yep, good to merge. Thank you!

2024-04-08 21:32 UTC, merged