[DOCS-7209] updating network vendors and SD-WAN support
DataDog/documentation pull request #22491
Opened 2024-04-03 22:07 UTC by aliciascott

### What does this PR do? What is the motivation?
This PR adds a table for the full list of supported network vendors and links to their integration (where applicable), as well as links to their config (yaml) files for the network profile.
Also adds support for SD-WAN devices (beta)

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-04-08 21:16 UTC, buraizu requested changes
Thanks, just requesting some minor edits, as well as updating a few relative links that aren't opening the expected pages.

In addition, could you please update the new links to use the **reference** format as mentioned in the [documentation style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#text)? This is intended to aid with the translation process.

2024-04-08 21:16 UTC, buraizu commented on content/en/network_monitoring/devices/_index.md
> +| [Fortinet](integrations/snmp_fortinet/) | [fortinet.yaml](https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/fortinet.yaml) <br>[fortinet-fortig
```suggestion
| [Fortinet](https://docs.datadoghq.com/integrations/snmp_fortinet/) | [fortinet.yaml](https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/fortinet.yaml) <br>[fortinet-fortigate.yaml](https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/fortinet-fortigate.yaml) <br> |
```

2024-04-08 21:16 UTC, buraizu commented on content/en/network_monitoring/devices/_index.md
> +| [Infoblox](integrations/rapdev_infoblox/) | [infoblox-ipam.yaml](https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/infoblox-ipam.yaml) <br> |
```suggestion
| [Infoblox](https://docs.datadoghq.com/integrations/rapdev_infoblox/) | [infoblox-ipam.yaml](https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/infoblox-ipam.yaml) <br> |
```

2024-04-08 21:16 UTC, buraizu commented on content/en/network_monitoring/devices/_index.md
> +| [Palo Alto Networks](integrations/pan_firewall/) | [palo-alto.yaml](https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/palo-alto.yaml) <br>[_pal
```suggestion
| [Palo Alto Networks](https://docs.datadoghq.com/integrations/pan_firewall/) | [palo-alto.yaml](https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/palo-alto.yaml) <br>[_palo-alto.yaml](https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/_palo-alto.yaml) <br> |
```

2024-04-09 14:20 UTC, aliciascott commented
Thanks @buraizu ! I committed the changes you requested, and requested re-review. let me know if I did the links correctly, thanks for catching those.

2024-04-09 18:05 UTC, buraizu requested changes
Thanks @aliciascott for following up and making those changes. The broken links now seem to be working.

With that said, I've left some additional feedback on this review showing what I mean about the reference links. Would you be able to apply the same type of update to the other links in the table? As mentioned, this aids the translation process, and in this case also makes the table somewhat easier to read. Let me know if you have any questions!

2024-04-09 18:05 UTC, buraizu commented on content/en/network_monitoring/devices/_index.md
> +| A10 | [a10.yaml](https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/a10.yaml) <br> |
```suggestion
| 3com | [3com.yaml][11] <br> |
| TP-Link | [tp-link.yaml][12] <br> |
| A10 | [a10.yaml][13] <br> |
```

2024-04-09 18:05 UTC, buraizu commented on content/en/network_monitoring/devices/_index.md
> +[10]: /integrations/meraki/
```suggestion
[10]: /integrations/meraki/
[11]: https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/3com.yaml
[12]: https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/tp-link.yaml
[13]: https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/a10.yaml
```

2024-04-09 21:45 UTC, aliciascott commented
Hey @buraizu !! Ok last time I hope :) I think I got all the links fixed now.

2024-04-09 22:23 UTC, buraizu approved these changes
Thanks for applying those changes @aliciascott. This review corrects a few additional broken links, but overall LGTM and approving. 

As one final request, it might be helpful for future maintainers of this doc to put the reference links in numerical order.

2024-04-09 22:23 UTC, buraizu commented on content/en/network_monitoring/devices/_index.md
> +| [Meraki][7] | [meraki-cloud-controller.yaml][89] <br>[meraki.yaml][89] <br> |
```suggestion
| [Meraki][7] | [meraki-cloud-controller.yaml][89] <br>[meraki.yaml][90] <br> |
```

2024-04-09 22:23 UTC, buraizu commented on content/en/network_monitoring/devices/_index.md
> +[96]:ttps://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/nvidia.yaml
```suggestion
[96]: https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/nvidia.yaml
```

2024-04-09 22:23 UTC, buraizu commented on content/en/network_monitoring/devices/_index.md
> +| [pfSense][33] | [pf-sense.yaml][103] <br> |
```suggestion
| [pfSense][212] | [pf-sense.yaml][103] <br> |
```

2024-04-10 14:39 UTC, merged