Use approved wording for GCP PSC
DataDog/documentation pull request #22525
Opened 2024-04-04 22:51 UTC by simnyc

* replace "GCP Private Service Connect" with "Google Cloud Private Service Connect"
* replace "GCP" with "Google Cloud" 

> we are going with "Google Cloud Private Service Connect" uniformly for the integration for ease of use in finding it and it also is more consistent with our other naming

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-04-04 22:55 UTC, sriramkraman approved these changes
LGTM

2024-04-05 15:58 UTC, drichards-87 requested changes
Left two very small suggestions.

2024-04-05 15:58 UTC, drichards-87 commented on content/en/agent/guide/gcp-private-service-connect.md
> +You can configure a PSC endpoint to expose a private IP address for each Datadog intake service; this IP address routes traffic to the Datadog backend. You can then configures a Google Cloud [_Privat
```suggestion
You can configure a PSC endpoint to expose a private IP address for each Datadog intake service. This IP address routes traffic to the Datadog backend. You can then configure a Google Cloud [_Private DNS Zone_][3] to override the DNS names corresponding to the products for each endpoint that is consumed. 
```

2024-04-05 15:58 UTC, drichards-87 commented on content/en/agent/guide/gcp-private-service-connect.md
> +You can configure a PSC endpoint to expose a private IP address for each Datadog intake service; this IP address routes traffic to the Datadog backend. You can then configures a Google Cloud [_Privat
```suggestion
You can configure a PSC endpoint to expose a private IP address for each Datadog intake service. This IP address routes traffic to the Datadog backend. You can then configure a Google Cloud [_Private DNS Zone_][3] to override the DNS names corresponding to the products for each endpoint that is consumed. 
```

2024-04-05 19:51 UTC, drichards-87 commented
@simnyc Are you still waiting on a review from @shris-github?

2024-04-05 19:51 UTC, drichards-87 approved these changes

2024-04-08 15:21 UTC, simnyc commented
> @simnyc Are you still waiting on a review from @shris-github?

no actually i used the wrong GH handle, you can ignore this review request and merge this. thanks

2024-04-10 18:28 UTC, drichards-87 approved these changes

2024-04-10 19:42 UTC, merged