Add "report" errors to types tracked for Error Tracking
DataDog/documentation pull request #22531
Opened 2024-04-05 10:30 UTC by milanboers

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-04-05 11:49 UTC, GianlucaBortoli approved these changes

2024-04-05 15:20 UTC, drichards-87 requested changes
Left one small bit of feedback from Docs.

2024-04-05 15:20 UTC, drichards-87 commented on content/en/real_user_monitoring/error_tracking/browser.md
> +Error Tracking processes errors collected from the browser by the RUM Browser SDK. Whenever a [source][1], [custom][2] or [report][3] error containing a stack trace is collected, Error Tracking proce
```suggestion
Error Tracking processes errors collected from the browser by the RUM Browser SDK. Whenever a [source][1], [custom][2], or [report][3] error containing a stack trace is collected, Error Tracking processes and groups it under an issue, or group of similar errors. 
```

2024-04-05 16:04 UTC, drichards-87 approved these changes

2024-04-08 08:50 UTC, N-Boutaib approved these changes

2024-04-09 15:20 UTC, merged