Add sentence concerning renotification timeout of 30 hours
DataDog/documentation pull request #22645
Opened 2024-04-12 12:57 UTC by pierreln-dd

### What does this PR do? What is the motivation?

Several customers have reached out wondering why their monitor stopped renotifying after 30 hours. Adding a sentence to the docs will help have a record of this default behavior.

### Merge instructions

- [X] Please merge after reviewing

### Additional notes

2024-04-12 18:25 UTC, rtrieu requested changes
Minor feedback to follow our style guide, but otherwise looks good. Thank you for this update!

2024-04-12 18:25 UTC, rtrieu commented on content/en/monitors/notify/_index.md
> +For example, configure the monitor to `stop renotifying after 1 occurrence` to receive a single escalation message after the main alert. By default, the renotifications will stop 30 hours after the f
```suggestion
For example, configure the monitor to `stop renotifying after 1 occurrence` to receive a single escalation message after the main alert. By default, the renotifications stop 30 hours after the first alert.
```

2024-04-15 12:58 UTC, pierreln-dd commented
Thanks for the review!

2024-04-18 17:24 UTC, rtrieu approved these changes
LGTM

2024-10-11 10:02 UTC, closed without merging