traceContextInjection init parameter documentation
DataDog/documentation pull request #22673
Opened 2024-04-16 12:37 UTC by dussault-antoine

### What does this PR do? What is the motivation?

Related to the implementation of [the short term solution in APM <> RUM correlation improvement](https://docs.google.com/document/d/1w7qe6Jp9vF6HmRA5bNjzZI9JxmXq8cwscqpUPpF686Y/edit#heading=h.y8mrkhm00858)

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-04-16 16:55 UTC, cswatt commented
Created DOCS-7721 to track.

2024-04-23 19:49 UTC, rtrieu requested changes
I've left some feedback for your review.

2024-04-23 19:49 UTC, rtrieu commented on content/en/real_user_monitoring/platform/connect_rum_and_traces.md
> +_Example_: If you set the `traceSampleRate` to 20% in the Browser SDK:
```suggestion
    For example, if you set the `traceSampleRate` to 20% in the Browser SDK:
```

2024-04-23 19:49 UTC, rtrieu commented on content/en/real_user_monitoring/platform/connect_rum_and_traces.md
> +- When `traceContextInjection` is set to `all`, **20%** of backend traces are kept and **80%** of backend traces are dropped.
```suggestion
    - When `traceContextInjection` is set to `all`, **20%** of backend traces are kept and **80%** of backend traces are dropped.
```

2024-04-23 19:49 UTC, rtrieu commented on content/en/real_user_monitoring/platform/connect_rum_and_traces.md
> +{{< img src="real_user_monitoring/connect_rum_and_traces/traceContextInjection_all.png" alt="traceContextInjection set to all" style="width:90%;">}}
```suggestion
  {{< img src="real_user_monitoring/connect_rum_and_traces/traceContextInjection_all.png" alt="traceContextInjection set to all" style="width:90%;">}}
```

2024-04-23 19:49 UTC, rtrieu commented on content/en/real_user_monitoring/platform/connect_rum_and_traces.md
> +- When `traceContextInjection` is set to `sampled`, **20%** of backend traces are kept. For the remaining **80%**, the browser SDK **does not inject** a sampling decision. The decision is made on the
```suggestion
  - When `traceContextInjection` is set to `sampled`, **20%** of backend traces are kept. For the remaining **80%**, the browser SDK **does not inject** a sampling decision. The decision is made on the server side and is based on the tracing library head-based sampling [configuration][2]. In the example below, the backend sample rate is set to 40%, and therefore 32% of the remaining backend traces are kept.
```

2024-04-23 19:49 UTC, rtrieu commented on content/en/real_user_monitoring/platform/connect_rum_and_traces.md
> +{{< img src="real_user_monitoring/connect_rum_and_traces/traceContextInjection_sampled.png" alt="traceContextInjection set to sampled" style="width:90%;">}}
```suggestion
    {{< img src="real_user_monitoring/connect_rum_and_traces/traceContextInjection_sampled.png" alt="traceContextInjection set to sampled" style="width:90%;">}}
```

2024-04-23 19:49 UTC, rtrieu commented on content/en/real_user_monitoring/platform/connect_rum_and_traces.md
> +- When `traceContextInjection` is set to `sampled`, **20%** of backend traces are kept. For the remaining **80%**, the browser SDK **does not inject** a sampling decision. The decision is made on the
Hi @dussault-antoine , I added the bit at the end to clarify the example further, but not sure if it is accurate. Can you verify and edit if needed? Thank you!

2024-04-25 15:24 UTC, dussault-antoine commented
@rtrieu committed the suggestions ! Thanks ! 
Good to merge

2024-04-26 13:53 UTC, rtrieu commented
Thanks @dussault-antoine , letting you know that I've put in a request to Brand Design to make brand-approved versions of your diagrams, so don't be surprised if they don't look different in another update :)

2024-04-26 13:58 UTC, rtrieu approved these changes
Looks good, thanks!

2024-05-08 20:02 UTC, merged