DOCS-6279 Adds Getting Started with CI Visibility Documentation
DataDog/documentation pull request #22692
Opened 2024-04-16 23:23 UTC by alai97

### What does this PR do? What is the motivation?

Adds a Getting Started with CI Visibility doc page + screenshots to the Getting Started section of the Docs Site.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-04-26 18:50 UTC, rtrieu requested changes
Left some feedback for your review, but otherwise looks good!

2024-04-26 18:50 UTC, rtrieu commented on content/en/getting_started/ci_visibility/_index.md
> +To start sending pipeline metrics, see the documentation for one of the following CI providers.
Should we mention what they can do if Datadog does not support their CI provider? Manual steps, if any?

2024-04-26 18:50 UTC, rtrieu commented on content/en/getting_started/ci_visibility/_index.md
> +[15]: https://app.datadoghq.com/monitors/create/
Link doesn't work when there is a slash at the end

```suggestion
[15]: https://app.datadoghq.com/monitors/create
```

2024-04-26 18:50 UTC, rtrieu commented on content/en/getting_started/ci_visibility/_index.md
> +1. Define the monitor's notification.
```suggestion
1. In the `Notify your team` section, configure your monitor's notification settings.
```

2024-04-26 20:41 UTC, alai97 commented on content/en/getting_started/ci_visibility/_index.md
> +Depending on the CI provider(s) of choice, CI Visibility may not support all of the levels in your pipeline (stage, job, step, or command). For more information about how CI Visibility defines a CI p
```suggestion
For a CI provider that is not supported by Datadog, you can send your pipeline events programmatically using the [CI Visibility Pipelines API].

Depending on the CI provider(s) of choice, CI Visibility may not support all of the levels in your pipeline (stage, job, step, or command). For more information about how CI Visibility defines a CI pipeline, see the [Terminology section][4].
```

2024-04-26 21:39 UTC, alai97 commented on content/en/getting_started/ci_visibility/_index.md
> +If your CI provider is not supported, you can programmatically send your pipeline events to Datadog using the [CI Visibility Pipelines API][16].
```suggestion
If your CI provider is not supported, you can programmatically send your pipeline events to Datadog. See [Send pipeline events to Datadog](#send-pipeline-events-to-datadog).
```

2024-04-26 21:40 UTC, alai97 commented on content/en/getting_started/ci_visibility/_index.md
> +For other pipeline providers and custom pipelines, you can programmatically send pipeline events to Datadog using the CI Visibility Pipelines API endpoint. For more information, see [Pipeline Data Mo
```suggestion
For other pipeline providers and custom pipelines, you can programmatically send pipeline events to Datadog using the [CI Visibility Pipelines API endpoint][16]. For more information, see [Pipeline Data Model and Execution Types][13].
```

2024-04-29 13:36 UTC, rtrieu approved these changes
Looks good!

2024-05-02 19:49 UTC, KickingTheTV approved these changes

2024-05-02 20:24 UTC, merged