Update Granular Access page with supported resources
DataDog/documentation pull request #22751
Opened 2024-04-19 15:02 UTC by saidurgas

### What does this PR do? What is the motivation?
Update Granular access page with supported resources

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-04-19 15:23 UTC, Jennyliu00 approved these changes

2024-04-19 15:28 UTC, aliciascott requested changes
Hi @saidurgas the links are broken as there is an extra space, can you fix those and request re-review then I'll merge it !

2024-04-19 15:28 UTC, aliciascott commented on content/en/account_management/rbac/granular_access.md
> +| [AppBuilder] [8]                                 | {{< X >}}         | {{< X >}}         | {{< X >}}                           |
```suggestion
| [AppBuilder][8]                                 | {{< X >}}         | {{< X >}}         | {{< X >}}                           |
```

2024-04-19 17:13 UTC, sanjaythakkar-dd commented
looks like [modified files](https://docs-staging.datadoghq.com/saidurga.subramanian/update_granular_access_page/account_management/rbac/granular_access) doesnt have correct formatting

2024-04-19 20:08 UTC, aliciascott approved these changes
looks good thanks for fixing the links! @saidurgas is this ready to be merged as well ?

2024-04-19 21:12 UTC, sanjaythakkar-dd commented
overall looks good
again same comment as https://github.com/DataDog/datadog-api-spec/pull/2763#discussion_r1572680050
my thought here is
if workflows give 👍  feel free to merge it
if not, maybe remove workflows for now and merge it

2024-04-22 17:39 UTC, saidurgas commented
> looks good thanks for fixing the links! @saidurgas is this ready to be merged as well ?

yes ready to be merged

2024-04-23 14:30 UTC, merged