Add Security Agent flare creation steps
DataDog/documentation pull request #22779
Opened 2024-04-22 14:26 UTC by tiphainePLQ

Slack discussion with Sylvain https://dd.slack.com/archives/C053TE945S8/p1713794209453469?thread_ts=1713520873.514109&cid=C053TE945S8

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-04-22 14:33 UTC, safchain approved these changes

2024-04-22 17:15 UTC, rtrieu requested changes
Some suggestions for your review before publishing. Thanks!

2024-04-22 17:15 UTC, rtrieu commented on content/en/security/cloud_security_management/setup/fargate.md
> +If you are still running into an issue, please [open a ticket][10] to Support with a `security-agent` flare attached to the latter.
Hi @tiphainePLQ , is this more of what you meant?

```suggestion
If you still have issues with the configuration, please [contact Datadog support][10] for help and attach the `security-agent` flare to the ticket.
```

2024-04-22 17:15 UTC, rtrieu commented on content/en/security/cloud_security_management/setup/fargate.md
> +Find below the step to create a `security-agent` flare according to your deployment:
```suggestion
Use the appropriate command below to create a `security-agent` flare based on your deployment:
```

2024-04-22 17:15 UTC, rtrieu commented on content/en/security/cloud_security_management/setup/fargate.md
> +[10]: https://docs.datadoghq.com/help/
```suggestion
[10]: /help/
```

2024-04-22 17:15 UTC, rtrieu commented on content/en/security/cloud_security_management/setup/fargate.md
> +[11]: https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6v7#ecs-fargate
```suggestion
[11]: /agent/troubleshooting/send_a_flare/?tab=agentv6v7#ecs-fargate
```

2024-04-23 13:13 UTC, rtrieu approved these changes
LGTM

2024-04-23 13:50 UTC, merged