(Developer) Nav updates
DataDog/documentation pull request #22813
Opened 2024-04-23 17:05 UTC by hestonhoffman

### What does this PR do? What is the motivation?

See [DOCS-7748](https://datadoghq.atlassian.net/browse/DOCS-7748)

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-04-23 17:06 UTC, hestonhoffman commented on content/en/developers/service_checks/_index.md
> +The [Check Summary][1] page lists of all checks reported across your infrastructure in the past day. Select a check to get insights on the status and tags associated with the check.
```suggestion
The [Check Summary][1] page lists all checks reported across your infrastructure in the past day. Select a check to get insights on the status and tags associated with the check.
```

2024-04-23 20:42 UTC, urseberry commented on content/en/developers/integrations/create-an-integration-recommended-monitor.md
> +1. [Create a monitor][5].
```suggestion
1. [Create a monitor][4].
```
Gremlins maybe changed the link number?

2024-04-23 20:50 UTC, eho1307 requested changes

2024-04-23 20:50 UTC, eho1307 commented on content/en/developers/integrations/create-a-cloud-siem-detection-rule.md
> +   **Note**: Only threshold based rules are supported.
```suggestion
```
This note can be removed now

2024-04-23 20:50 UTC, eho1307 commented on content/en/developers/integrations/log_pipeline.md
> +1. Click **Create**.
```suggestion
1. From the [**Pipelines**][3] page, click **+ New Pipeline**.
2. In the **Filter** field, enter a unique `source` tag that defines the log source for the Technology Partner's logs. For example, `source:okta` for the Okta integration. **Note**: Make sure that logs sent through the integration are tagged with the correct source tags before they are sent to Datadog.
3. Optionally, add tags and a description.
4. Click **Create**.
```

2024-04-24 15:18 UTC, eho1307 approved these changes

2024-04-24 22:13 UTC, urseberry approved these changes

2024-04-24 22:13 UTC, merged