DOCS-7653 Adds Getting Started with Test Visibility Documentation
DataDog/documentation pull request #22830
Opened 2024-04-23 23:51 UTC by alai97

### What does this PR do? What is the motivation?

Adds a Getting Started with Test Visibility page to the Getting Started section of the Docs Site, updates a supported languages partial and reuses it in this Getting Started page, and adds screenshots.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-04-24 21:51 UTC, buraizu commented
Thanks, created DOCS-7805 to review

2024-04-30 00:01 UTC, aliciascott requested changes
Hi @alai97 looks great! Just a few small suggestions for wording :)

2024-04-30 18:22 UTC, aliciascott approved these changes
Looks good!

2024-05-01 18:28 UTC, KickingTheTV approved these changes

2024-05-01 20:36 UTC, merged