Update vids and images on APM Resource page
DataDog/documentation pull request #22867
Opened 2024-04-25 16:37 UTC by domalessi

### What does this PR do? What is the motivation?
Update vids and images on APM Resource page to remove references to old DD app left-hand nav. 

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-04-25 21:37 UTC, cswatt requested changes
This looks good! But the alt text on these images can also be improved. I've written one suggestion to give you an idea—we have more info on this on the "Writing alt text" page in our team confluence.

2024-04-25 21:37 UTC, cswatt commented on content/en/tracing/services/resource_page.md
> +{{< img src="tracing/visualization/resource/dependency-map-navigator-cropped.png" alt="dependency map navigator" style="width:100%;" >}}
```suggestion
{{< img src="tracing/visualization/resource/dependency-map-navigator-cropped.png" alt="A dependency map for a resource, with a list of service dependencies and flow diagram of requests from service to service" style="width:100%;" >}}
```

2024-04-30 19:20 UTC, brett0000FF approved these changes

2024-04-30 19:58 UTC, cswatt approved these changes

2024-04-30 19:59 UTC, merged