DOCS-7728 Adds Getting Started with Intelligent Test Runner
DataDog/documentation pull request #22860
Opened 2024-04-24 23:16 UTC by alai97

### What does this PR do? What is the motivation?

Adds a Getting Started with Intelligent Test Runner page to the Getting Started section of the Docs Site, updates the Intelligent Test Runner supported languages partial, and adds screenshots.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-04-25 00:06 UTC, buraizu commented
Thanks, created DOCS-7806 to review

2024-04-29 23:11 UTC, aliciascott requested changes
Hi @alai97 ! Looks great, just a few suggestions for wording and flow :)

2024-04-29 23:11 UTC, aliciascott commented on content/en/getting_started/intelligent_test_runner/_index.md
> +Use the following out-of-the-box Intelligent Test Runner [facets][9] to customize the search query.
```suggestion
Use the following out-of-the-box Intelligent Test Runner [facets][9] to customize the search query:
```

2024-05-01 18:28 UTC, KickingTheTV approved these changes

2024-05-01 21:01 UTC, merged