Update dogstatd _index.md - hint to overwrite default site
DataDog/documentation pull request #22865
Opened 2024-04-25 12:55 UTC by iKsSs

### What does this PR do? What is the motivation?

Update DogStatD Docker run command to reflect another site than the default one.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-04-25 18:40 UTC, cswatt requested changes
This is a great catch! My suggestion is just formatting/style.

Thank you for finding this, and for correctly using our Hugo shortcode!

2024-04-25 18:40 UTC, cswatt commented on content/en/developers/dogstatsd/_index.md
> +Where your <DATADOG_SITE> is {{< region-param key="dd_site" code="true" >}} (defaults to datadoghq.com).
```suggestion
Replace `<DATADOG_SITE>` with {{< region-param key="dd_site" code="true" >}} (defaults to `datadoghq.com`).
```

2024-06-01 21:45 UTC, iksss-invia commented
@cswatt is there anything else I can do to merge this?

2024-06-04 06:28 UTC, iKsSs commented
@cswatt is there anything else I can do to merge this?

2024-10-01 13:11 UTC, iKsSs commented
ping..

2026-08-03 19:15 UTC, jhgilbert commented
This PR was closed after six or more months of inactivity. If this was done in error, feel free to re-open the PR.

2026-08-03 19:15 UTC, closed without merging