update wd monitors after ui change
DataDog/documentation pull request #22898
Opened 2024-04-26 17:33 UTC by HugoPct

### What does this PR do? What is the motivation?
We updated the UI for Watchdog Monitors.
this PR changes the docs to reflect such change
https://app.datadoghq.com/monitors/create/watchdog

### Merge instructions
- [x] Please merge after reviewing

### Additional notes

2024-04-26 19:02 UTC, estherk15 requested changes
Looks good, left feedback for image and minor fixes!

2024-04-26 19:02 UTC, estherk15 commented on content/en/monitors/types/watchdog.md
> +For detailed instructions on the **Say what's happening** and **Notify your team** sections, see the [Notifications][4] page.
```suggestion
For more instructions on the **Notify your team** section, see the [Notifications][4] page.
```

2024-04-26 19:02 UTC, estherk15 commented on content/en/monitors/types/watchdog.md
> +{{< img src="/monitors/monitor_types/watchdog/watchdog-monitor-2.png" alt="Configuring a Watchdog Monitor with advanced settings" style="width:80%;">}}
```suggestion
* Filter on any additional tag available on the Watchdog event.
* Group By the dimensions you want to [group notifications by][3].
{{< img src="/monitors/monitor_types/watchdog/watchdog-monitor-2.png" alt="Configuring a Watchdog Monitor with advanced settings" style="width:90%;">}}
```

2024-04-29 15:37 UTC, HugoPct reviewed
accepted suggestions

2024-05-03 13:51 UTC, estherk15 approved these changes

2024-05-03 13:51 UTC, merged