DOCS-7780 - OpenTelemetry for AWS Lambda
DataDog/documentation pull request #22965
Opened 2024-05-01 22:09 UTC by cswatt

### What does this PR do? What is the motivation?
Adds an OpenTelemetry page to the Serverless > AWS Lambda section.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

Open questions:
- Are there any other options that should be documented?
- What are the high-level reasons one option would be used over another?
- Please review the code samples in the OTel SDK option, as they've been modified significantly

2024-05-10 03:16 UTC, sumedham requested changes
Some minor positioning comments

2024-05-10 03:16 UTC, sumedham commented on content/en/serverless/aws_lambda/opentelemetry.md
> +- [OpenTelemetry SDK within the Datadog Agent](#opentelemetry-sdk-within-the-datadog-agent) (beta)
```suggestion
- [Send OpenTelemetry Traces from any OpenTelemetry SDK through the Datadog Lambda Extension](#opentelemetry-sdk-within-the-datadog-agent) (beta)
```

2024-05-10 03:16 UTC, sumedham commented on content/en/serverless/aws_lambda/opentelemetry.md
> +- [OpenTelemetry SDK within the Datadog Agent](#opentelemetry-sdk-within-the-datadog-agent) (beta)
Open to other syntax here, I just felt like this was more straightforward

2024-05-10 03:16 UTC, sumedham commented on content/en/serverless/aws_lambda/opentelemetry.md
> +The Datadog tracing library, which is included in the Datadog Lambda Extension upon installation, accepts the spans and traces generated by OpenTelemetry-instrumented code, processes the telemetry, a
```suggestion
The Datadog tracing library, which is included in the Datadog Lambda Extension upon installation, accepts custom spans and traces created with OpenTelemetry-instrumented code, processes the telemetry, and sends it to Datadog.
```

2024-05-10 03:16 UTC, sumedham commented on content/en/serverless/aws_lambda/opentelemetry.md
> +You can use this approach if, for example, your code has already been instrumented with the OpenTelemetry API. You may also use this approach if you want to instrument using vendor-agnostic code with
```suggestion
You can use this approach if, for example, your main goal is to code has already been instrumented with the OpenTelemetry API. This means you can maintain vendor-neutral instrumentation of all your services, while still taking advantage of Datadog’s native implementation, tagging, and, features. 
```

2024-05-10 03:16 UTC, sumedham commented on content/en/serverless/aws_lambda/opentelemetry.md
> +To instrument AWS Lambda with the OpenTelemetry API, set the environment variable `DD_TRACE_OTEL_ENABLED` to `true`.
```suggestion
To instrument AWS Lambda with the OpenTelemetry API, set the environment variable `DD_TRACE_OTEL_ENABLED` to `true` in your Lambda function and see [Custom instrumentation with the OpenTelemetry API][3]  for runtime-specific instructions.
```

2024-05-10 03:16 UTC, sumedham commented on content/en/serverless/aws_lambda/opentelemetry.md
> +This approach is analogous to [OLTP Ingest in the Datadog Agent][4].
```suggestion
This approach is analogous to [OLTP Ingest in the Datadog Agent][4]. It is recommended in situations where tracing support may not be available for your runtime (e.g. Rust or PHP). 
```

2024-05-10 03:16 UTC, sumedham commented on content/en/serverless/aws_lambda/opentelemetry.md
> +1. Tell OpenTelemetry to export spans to the Datadog Lambda Extension. Then, add OpenTelemetry's instrumentation for AWS Lambda. This is analogous to adding the tracing layer.
Customers may not know what "this is analagous to the tracing layer" means. Should we just remove it?

2024-05-17 18:30 UTC, cswatt commented on content/en/serverless/aws_lambda/opentelemetry.md
> +See [Custom instrumentation with the OpenTelemetry API][3] for more details.
```suggestion
```

2024-05-17 18:31 UTC, cswatt commented on content/en/serverless/aws_lambda/opentelemetry.md
> +1. Tell OpenTelemetry to export spans to the Datadog Lambda Extension. Then, add OpenTelemetry's instrumentation for AWS Lambda. This is analogous to adding the tracing layer.
```suggestion
1. Tell OpenTelemetry to export spans to the Datadog Lambda Extension. Then, add OpenTelemetry's instrumentation for AWS Lambda.
```

2024-05-17 18:33 UTC, cswatt commented on content/en/serverless/aws_lambda/opentelemetry.md
> +### OpenTelemetry SDK within the Datadog Agent
```suggestion
### Send OpenTelemetry traces from any OpenTelemetry SDK through the Datadog Lambda Extension {#sdk}
```

2024-05-17 19:29 UTC, merged