Update _index.md
DataDog/documentation pull request #22976
Opened 2024-05-02 15:44 UTC by dogeahill

Update the top level documentation to inform users that there are Kubernetes options availble as there are docker and windows options

### What does this PR do? What is the motivation?
Update top level of synthetics private worker docs to clarify that helm options are available

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-05-02 15:49 UTC, drichards-87 requested changes
Left you some minor feedback.

2024-05-02 15:49 UTC, drichards-87 commented on content/en/synthetics/private_locations/_index.md
> +Private locations are Kubernetes deployments that you can install on your Kubernetes cluster with Helm. You can access the [helm chart][101] on Github. It can run on Linux-based Kubernetes.**\***
```suggestion
Private locations are Kubernetes deployments that you can install on your Kubernetes cluster with Helm. The [helm chart][101] can run on Linux-based Kubernetes.
```

2024-05-02 15:49 UTC, drichards-87 commented on content/en/synthetics/private_locations/_index.md
> +**\*** **Use and operation of this software is governed by the End User License Agreement available [here][102].**
```suggestion
**Note**: Use and operation of this software is governed by the [End-User License Agreement][102].
```

2024-05-02 15:54 UTC, dogeahill commented
> Left you some minor feedback.

@drichards-87 thank you, I have committed the feedback

2024-05-02 15:57 UTC, drichards-87 reviewed
Thanks @dogeahill. Is this ready to be merged now?

2024-05-02 15:57 UTC, drichards-87 commented on content/en/synthetics/private_locations/_index.md
> +**Note**: Use and operation of this software is governed by the [End-User License Agreement][102].
```suggestion
**Note**: Use and operation of this software is governed by the [End-User License Agreement][103].
```

2024-05-02 17:42 UTC, dogeahill commented
> Thanks @dogeahill. Is this ready to be merged now?

I think if someone from Synthetics could verify this it would be good before merging

2024-05-03 08:20 UTC, RomainGuarinoni approved these changes

2024-05-03 15:23 UTC, drichards-87 approved these changes

2024-05-03 15:23 UTC, merged