[CIVIS] Fix outdated documentation
DataDog/documentation pull request #23060
Opened 2024-05-08 13:47 UTC by TovRudyy

### What does this PR do? What is the motivation?
Fixing outdated documentation regarding the concept of "wall time" of Test Visibility. 

The wall time was deprecated in a past PR:
- https://github.com/DataDog/documentation/pull/20486

However, a posterior PR overwrote the changes and introduced it again by mistake:
- https://github.com/DataDog/documentation/pull/20816

We have just realised about this today.

### Merge instructions

- [X] Please merge after reviewing

### Additional notes

2024-05-08 13:53 UTC, ManuelPalenzuelaDD approved these changes
💯

2024-05-08 15:37 UTC, buraizu requested changes
Thanks, suggesting some minor edits.

2024-05-08 15:37 UTC, buraizu commented on content/en/tests/troubleshooting/_index.md
> +If after updating the tracer version you still don't see the total time, contact [Datadog support][2] for help.
```suggestion
If you still don't see the total time after updating the tracer version, contact [Datadog support][2] for help.
```

2024-05-08 15:37 UTC, buraizu commented on content/en/tests/troubleshooting/_index.md
> +2. Sum the maximum test session durations.
```suggestion
1. The maximum duration of a test session grouped by the test session fingerprint is calculated.
2. The maximum test session durations are summed.
```

2024-05-08 15:37 UTC, buraizu commented on content/en/tests/troubleshooting/_index.md
> +2. Sum the maximum test session durations.
Suggesting to rephrase these as descriptions rather than imperatives.

2024-05-09 16:33 UTC, buraizu approved these changes

2024-05-09 16:38 UTC, merged