DOCS-7722 CI Visibility and Test Visibility Product Landing Page Edits
DataDog/documentation pull request #23064
Opened 2024-05-08 17:54 UTC by alai97

### What does this PR do? What is the motivation?

Now that we've separated CI Visibility into CI Pipeline Visibility and Test Visibility, it's time to distinguish the pipeline content from the test content on the product landing pages. We're scrubbing any mention of "tests" from CI Visibility, and making sure that information is covered on the Test Visibility landing page (along with an update to the language/options partial).

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-05-08 23:39 UTC, buraizu approved these changes
Looks good, approving with a suggestion to break up a long sentence.

2024-05-08 23:39 UTC, buraizu commented on content/en/tests/_index.md
> +{{< whatsnext desc="Integrate Test Visibility with tools for reporting code coverage data, enhancing browser tests with Real User Monitoring, and ensuring insights across platforms by streamlining is
```suggestion
{{< whatsnext desc="Streamline issue identification and resolution in your development cycle by integrating Test Visibility with tools for reporting code coverage data. You can enhance browser tests with Real User Monitoring, and ensure insights across platforms." >}}
```

2024-05-08 23:39 UTC, buraizu commented on content/en/tests/_index.md
> +{{< whatsnext desc="Integrate Test Visibility with tools for reporting code coverage data, enhancing browser tests with Real User Monitoring, and ensuring insights across platforms by streamlining is
Left a suggestion here to break up a long sentence, feel free to make any additional adjustments.

2024-05-09 08:46 UTC, nikita-tkachenko-datadog approved these changes

2024-05-15 14:48 UTC, KickingTheTV requested changes
Everything LGTM

But can we just make one change while we're here. For the test setup page where we have the table of features and compatibility, can we add a checkmark for Intelligent Test Runner for Ruby? We now support ITR for all languages

2024-05-22 18:28 UTC, KickingTheTV approved these changes
LGTM

2024-05-22 19:02 UTC, merged