Add direct link to auto discovery docs in mysql/postgres aurora setup
DataDog/documentation pull request #23110
Opened 2024-05-10 13:38 UTC by jmeunier28

### What does this PR do? What is the motivation?

Adds direct note in setup docs on how to use the new auto discovery feature in the agent

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-05-10 16:01 UTC, aliciascott requested changes
Hi @jmeunier28 this looks good, just some small suggestions, please request re-review once updated, thanks!

2024-05-10 16:01 UTC, aliciascott commented on content/en/database_monitoring/setup_postgres/aurora.md
> +**The Datadog Agent supports auto-discovering all aurora endpoints in a cluster.** In order to do this, please [follow this guide.][14]
```suggestion
**The Datadog Agent supports [Autodiscovery][14] of all Aurora endpoints in a cluster.** 
```

Same with this one

2024-05-10 16:01 UTC, aliciascott commented on content/en/database_monitoring/setup_mysql/aurora.md
> +**The Datadog Agent supports auto-discovering all aurora endpoints in a cluster.** In order to do this, please [follow this guide.][10]
```suggestion
**The Datadog Agent supports [Autodiscovery][10] of all Aurora endpoints in a cluster.** 
```

Simplifying this sentence so it flows better to just link directly within to the autodiscovery config page (also the link wasn't working as is).

2024-05-10 19:31 UTC, jmeunier28 commented
@aliciascott  thanks!

2024-05-10 21:34 UTC, aliciascott approved these changes
Hi @jmeunier28 I forgot to mention that the links that are within tabs need to be placed within the tab section, I just pushed up a fix to correct that, let me know if this is ready to be merged as well?

2024-05-13 13:54 UTC, jmeunier28 commented
Ah sorry about that! Yes @aliciascott please merge whenever you get a chance! Thanks so much!

2024-05-13 15:25 UTC, merged