Add mention to DD_TRACE_OTEL_ENABLED
DataDog/documentation pull request #23123
Opened 2024-05-10 22:20 UTC by julianocosta89

### What does this PR do? What is the motivation?

`DD_TRACE_OTEL_ENABLED=true`
is mentioned under https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/java/otel/#setup and should also be called out under https://docs.datadoghq.com/tracing/trace_collection/library_config/java.

### Merge instructions

- [ ] Please merge after reviewing

2024-05-11 08:19 UTC, mcculls commented
We should remove this from the experimental section at the same time, because `DD_TRACE_OTEL_ENABLED` replaces it:
```
dd.integration.opentelemetry.experimental.enabled : Environment Variable: DD_INTEGRATION_OPENTELEMETRY_EXPERIMENTAL_ENABLED
Default: false
Enables experimental OpenTelemetry features. When you enable this setting, you can use the OpenTelemetry tracing API backed by the Datadog Trace Agent.
Available since version 1.10.0
```

2024-05-13 06:35 UTC, PerfectSlayer approved these changes

2024-05-13 16:48 UTC, rtrieu commented on content/en/tracing/trace_collection/library_config/java.md
> +When `true`, enables OpenTelemetry based tracing for [custom][16] instrumentation.
```suggestion
When `true`, OpenTelemetry-based tracing for [custom][16] instrumentation is enabled.
```

2024-05-13 16:49 UTC, rtrieu requested changes
Minor suggestion but otherwise looks good. Thanks!

2024-05-22 13:56 UTC, rtrieu approved these changes
Looks good!

2024-05-22 19:13 UTC, merged