Getting started with Azure documentation
DataDog/documentation pull request #23205
Opened 2024-05-15 21:35 UTC by iadjivon

### What does this PR do? What is the motivation?
This is a Getting Started documentation for the Azure integration. 

### Merge instructions
This is still a work in progress pending the approval of the Azure SME's. Once they give the go ahead, this should be all set to merge. 
- [ ] Please merge after reviewing

### Additional notes

2024-05-16 01:17 UTC, buraizu requested changes
Looks good! I left some minor suggestions based on the style guide, and also flagged some links that don't seem to be working as expected (which I suspect is related to some of the ongoing issues with the site-region selector). Let me know if you have any questions or feedback.

2024-05-16 01:17 UTC, buraizu commented on content/en/getting_started/integrations/azure.md
> +      tag: "Datadog's full list of integrations"
```suggestion
      tag: "Datadog's full list of integrations"
    - link: 'https://www.datadoghq.com/blog/azure-integration-configuration/'
      text: 'Fine-tune observability configurations for all your Azure integrations in one place'
      tag: 'Blog'
```

2024-05-16 01:17 UTC, buraizu commented on content/en/getting_started/integrations/azure.md
> +      tag: "Datadog's full list of integrations"
Suggesting to add a recent Azure blog post for variety

2024-05-16 18:48 UTC, iadjivon commented on content/en/getting_started/integrations/azure.md
> +
I could add it, since that link points to a page that redirects to the US3 site if their site is anything other than US3.

2024-05-17 20:47 UTC, buraizu approved these changes
LGTM with a couple of minor updates!

2024-05-17 20:47 UTC, buraizu commented on content/en/getting_started/integrations/azure.md
> +<!-- ---------------------------------------------------------- -->
```suggestion
```

2024-05-17 20:47 UTC, buraizu commented on content/en/getting_started/integrations/azure.md
> +[202]: https://docs.datadoghq.com/integrations/guide/azure-manual-setup/?tab=azurecli
```suggestion
[201]: /integrations/guide/azure-native-programmatic-management/
[202]: /integrations/guide/azure-native-manual-setup/
```

2024-05-17 20:47 UTC, buraizu commented on content/en/getting_started/integrations/azure.md
> +<div class="alert alert-warning"> <strong>Note</strong>: <a href="https://docs.datadoghq.com/logs/log_configuration/archives/?tab=azurestorage">log archives </a> are only supported with App registrat
```suggestion
<div class="alert alert-warning"> <strong>Note</strong>: <a href="https://docs.datadoghq.com/logs/log_configuration/archives/?tab=azurestorage">log archives </a> are only supported with App registration. For US3 sites that have set up the Datadog Azure Native integration, you need to create an <a href="https://docs.datadoghq.com/integrations/guide/azure-manual-setup/?tab=manual#creating-the-app-registration"> App registration</a> to access these functionalities.
```

2024-05-17 20:47 UTC, buraizu commented on content/en/getting_started/integrations/azure.md
> +<div class="alert alert-warning"> <strong>Note</strong>: <a href="https://docs.datadoghq.com/logs/log_configuration/archives/?tab=azurestorage">log archives </a> are only supported with App registrat
Borrowed this from reference link `[4]`

2024-05-17 21:25 UTC, merged