Update c++ documentation
DataDog/documentation pull request #23258
Opened 2024-05-19 10:25 UTC by dmehala

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-05-21 08:18 UTC, dmehala commented on content/fr/tracing/guide/setting_up_APM_with_cpp.md
> +Commencez par lancer une nouvelle box Vagrant `ubuntu/jammy64` et connectez vous a la VM :
```suggestion
Commencez par lancer une nouvelle box Vagrant `ubuntu/jammy64` et connectez vous à la VM :
```

2024-05-21 17:26 UTC, rtrieu requested changes
Hi @dmehala, thank you for your PR! I made one suggestion so that the variables appear as code instead of being enclosed by backticks. Thank you for editing the French version, but our translators will handle it so I would ask you to discard your changes in /fr/, because they'll be overwritten by our Translation pipeline anyway. To answer your question, any change made to the English version gets translated by Transifex a few days or weeks after, but sometimes they get a backlog. I will ask them to prioritize these files in Japanese and Korean!

2024-05-21 17:26 UTC, rtrieu commented on content/en/tracing/trace_collection/proxy_setup/_index.md
> +  <strong>Note:</strong> The variables `DD_AGENT_HOST`, `DD_TRACE_AGENT_PORT` and `DD_TRACE_AGENT_URL` do not apply to Envoy, as the address of the Datadog Agent is configured using the `cluster` set
```suggestion
  <strong>Note:</strong> The variables <code>DD_AGENT_HOST</code>, <code>DD_TRACE_AGENT_PORT</code> and <code>DD_TRACE_AGENT_URL</code> do not apply to Envoy, as the address of the Datadog Agent is configured using the <code>cluster</code> settings.
```

2024-05-21 17:40 UTC, rtrieu commented
@dmehala  FYI, I have prioritized the translation of this file.

<img width="1027" alt="Screenshot 2024-05-21 at 10 39 42 AM" src="https://github.com/DataDog/documentation/assets/107086888/06bfeccc-6f71-430f-b087-fdcf91198729">

2024-05-22 13:55 UTC, rtrieu approved these changes
Looks good, thank you for these updates!

2024-05-22 13:56 UTC, merged