[rum] Update Expo View Tracking docs
DataDog/documentation pull request #23471
Opened 2024-06-03 18:58 UTC by rtrieu

### What does this PR do? What is the motivation?

As per [DOCS-8088](https://datadoghq.atlassian.net/browse/DOCS-8088), this update adds instructions on how to add View Tracking for Expo. 

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-06-03 21:36 UTC, hestonhoffman approved these changes
small edit

2024-06-04 13:45 UTC, marco-saia-datadog requested changes

2024-06-04 13:45 UTC, marco-saia-datadog commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/expo.md
> +#### Manual initialization
```suggestion
#### Manual tracking
```

2024-06-04 13:45 UTC, marco-saia-datadog commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/expo.md
> +#### Automatic initialization
```suggestion
#### Automatic tracking
```

2024-06-04 14:21 UTC, MaelNamNam approved these changes
LGTM! Thanks chief!

2024-06-05 07:37 UTC, marco-saia-datadog approved these changes
Looks good to me 👍

2024-06-05 13:39 UTC, merged