Added RN docs for DATADOG_RELEASE_VERSION env var
DataDog/documentation pull request #23482
Opened 2024-06-04 09:20 UTC by marco-saia-datadog

### What does this PR do? What is the motivation?
Adds documentation for new environment variable that can be used to override the release version of the uploaded sourcemaps on Android and iOS.

### Merge instructions

- [ ] Waiting for Datadog React Native v2.3.4 to be released

2024-06-04 15:21 UTC, drichards-87 requested changes
Left a small suggestion.

2024-06-04 15:21 UTC, drichards-87 commented on content/en/real_user_monitoring/error_tracking/mobile/reactnative.md
> +#### Custom Release Version
```suggestion
#### Specifying a custom release version
```

2024-06-05 16:26 UTC, drichards-87 commented
@marco-saia-datadog Feel free to message me or post in the documentation Slack channel when this is ready to be merged. Thanks!

2024-06-06 08:07 UTC, marco-saia-datadog commented
@drichards-87 It is ready to be merged now, thank you!

2024-06-06 13:43 UTC, drichards-87 approved these changes

2024-06-06 13:43 UTC, merged