Add kube_node to kubernetes host tags
DataDog/documentation pull request #23579
Opened 2024-06-10 09:31 UTC by mfpierre

### What does this PR do? What is the motivation?
this PR https://github.com/DataDog/datadog-agent/pull/17982 was not reflected in the documentation

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-06-10 18:31 UTC, rtrieu commented on content/en/containers/kubernetes/tag.md
> +  | `kube_node`         | Low         | `NodeName` field in a pod specifications               |                                                                |
```suggestion
  | `kube_node`         | Low         | `NodeName` field in a pod's specifications               |                                                                |
```

2024-06-10 18:31 UTC, rtrieu requested changes
Grammatical feedback but otherwise LGTM

2024-11-15 15:06 UTC, rtrieu approved these changes

2024-12-18 13:41 UTC, mfpierre commented
👋 @rtrieu do you happen to know why this one did not merge?

2024-12-19 17:26 UTC, rtrieu commented
/merge

2024-12-19 17:29 UTC, rtrieu commented
@mfpierre I'm not sure but I'm trying again and will monitor this one.

2024-12-19 21:26 UTC, rtrieu commented
Closing this as I cloned it here: https://github.com/DataDog/documentation/pull/26859

2024-12-19 21:26 UTC, closed without merging