watchdog insights
DataDog/documentation pull request #23580
Opened 2024-06-10 11:56 UTC by HugoPct

filtering on a outlier makes it disapear

### What does this PR do? What is the motivation?

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-06-10 18:44 UTC, rtrieu requested changes
Minor feedback, but otherwise looks good.

2024-06-11 08:01 UTC, HugoPct commented on content/en/watchdog/insights.md
> +Beware, fIltering on Watchdog Insights will automatically change the scope you're looking at. Hence, if you select an outlier insight, it won't be shown anymore but the traces and scope associated.
when you filter on an insights outlier, the scope of the query is updated. 
As you are scoped on the traces of the outlier, the outlier is not an outlier anymore but the baseline, therefore we do not show it.
what do you think about the latest suggestion?

2024-06-11 14:13 UTC, rtrieu commented on content/en/watchdog/insights.md
> +Beware, fIltering on Watchdog Insights will automatically change the scope you're looking at. Hence, if you select an outlier insight, it won't be shown anymore but the traces and scope associated.
That's help, thanks @HugoPct. I updated my suggestion. What do you think?

2024-06-11 14:42 UTC, HugoPct commented on content/en/watchdog/insights.md
> +Beware, fIltering on Watchdog Insights will automatically change the scope you're looking at. Hence, if you select an outlier insight, it won't be shown anymore but the traces and scope associated.
@rtrieu 
great!
can we be a bit more specific and explicitly say the outlier will not be visible anymore

2024-06-11 17:24 UTC, rtrieu commented on content/en/watchdog/insights.md
> +Beware, fIltering on Watchdog Insights will automatically change the scope you're looking at. Hence, if you select an outlier insight, it won't be shown anymore but the traces and scope associated.
@HugoPct yes!

2024-06-12 07:36 UTC, HugoPct commented on content/en/watchdog/insights.md
> +Beware, fIltering on Watchdog Insights will automatically change the scope you're looking at. Hence, if you select an outlier insight, it won't be shown anymore but the traces and scope associated.
@rtrieu 
thanks!
looks good to me

2024-06-12 15:00 UTC, merged