docs(vscode): expand vscode extension docs
DataDog/documentation pull request #23588
Opened 2024-06-10 17:24 UTC by robertohuertasm

### What does this PR do? What is the motivation?

Harmonizes the current documentation and the extension documentation used in the [Microsoft marketplace](https://marketplace.visualstudio.com/items?itemName=Datadog.datadog-vscode)

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

IDE-2463
IDE-2916

2024-06-10 19:08 UTC, rtrieu requested changes
Left some feedback for clarity and consistency, but otherwise looks good!

2024-06-10 19:08 UTC, rtrieu commented on content/en/developers/ide_plugins/vscode/_index.md
> +[datadog]: https://www.datadoghq.com/
```suggestion
[datadog]: https://www.datadoghq.com/
```

Hi @robertohuertasm, can you please update these relative link references to the correct consecutive numbers to be consistent with the docs style guide? Thank you!

2024-06-11 09:17 UTC, robertohuertasm commented
Hi @rtrieu, thank you very much for your review! I think I have addressed all the issues. Let me know if you find something else.

2024-06-11 14:19 UTC, rtrieu requested changes
A few more things!

2024-06-11 14:19 UTC, rtrieu commented on content/en/developers/ide_plugins/vscode/_index.md
> +If you don't wish to send this data to [Datadog][2], you can opt out at any time in the extension settings: `Datadog > Telemetry > Setup > Enable Telemetry`.
```suggestion
If you don't wish to send this data to [Datadog][2], you can opt out at any time in the VS Code extension settings: `Datadog > Telemetry > Setup > Enable Telemetry` and select `disabled`.
```

2024-06-11 17:41 UTC, robertohuertasm commented
@rtrieu committed all your suggestions! Thanks a lot!

2024-06-11 20:58 UTC, rtrieu approved these changes
It looks great! Thank you!

2024-06-11 20:59 UTC, merged