update data jobs monitoring setup guide wrt databricks integration permissions
DataDog/documentation pull request #23676
Opened 2024-06-13 22:12 UTC by yiliangzhou

### What does this PR do? What is the motivation?

This update is to call out some important steps in data jobs monitoring setup wrt the access token permission during Databricks Integration setup:
* the token needs to never expire.
* the token needs to have Can View ACL permissions to Databricks Jobs.
* call out an alternative way of generating access token (as service principal is recommended way of managing identity in Databricks for automated tools)

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-06-13 22:31 UTC, alai97 reviewed
Looks good, some suggestions.

2024-06-13 22:31 UTC, alai97 commented on content/en/data_jobs/databricks.md
> +1. Click **Generate new token**, enter a comment, leave the Lifetime as empty and click **Generate**. Take note of your token.
```suggestion
1. Click **Generate new token**, enter a comment, leave the Lifetime as empty, and click **Generate**. Take note of your token.
```

2024-06-13 22:31 UTC, alai97 commented on content/en/data_jobs/databricks.md
> +1. As an alternative, follow [the guide][10] to generate access token for a [service principal][11].
```suggestion
1. As an alternative, follow the [official Databricks documentation][10] to generate access token for a [service principal][11].
```

2024-06-13 22:31 UTC, alai97 commented on content/en/data_jobs/databricks.md
> +1. Ensure the account generating the token has [CAN VIEW][9] access for Databricks Jobs you want to monitor and the token is configured to never expire.
```suggestion
1. Ensure the account generating the token has [CAN VIEW access][9] for the Databricks jobs you want to monitor, and that the token is configured to never expire.
```

2024-06-13 23:44 UTC, warrierr approved these changes
LGTM after you make Alpine's changes

2024-06-14 15:34 UTC, warrierr requested changes

2024-06-14 15:34 UTC, warrierr commented on content/en/data_jobs/databricks.md
>  1. In your Databricks workspace, go to **Settings** > **Developer**. Next to **Access tokens**, click **Manage**.
```suggestion
1. In your Databricks workspace, click on your profile in the top right corner and go to **Settings**. Select **Developer** in the left side bar. Next to **Access tokens**, click **Manage**.
```

2024-06-14 15:34 UTC, warrierr commented on content/en/data_jobs/databricks.md
> +1. Click **Generate new token**, enter "Datadog Integration" in the **Comment** field, remove the default value in **Lifetime (days)**, and click **Generate**. Take note of your token. **Important:**
Is it possible to get the **Important:...**  callout to be on a newline but not create a separate step in markdown?

2024-06-14 15:34 UTC, warrierr commented on content/en/data_jobs/databricks.md
> +1. Ensure the account generating the token has [CAN VIEW access][9] for the Databricks jobs you want to monitor, and that the token is configured to never expire.
```suggestion
1. Ensure the account generating the token has [CAN VIEW access][9] for the Databricks jobs and clusters you want to monitor, and that the token is configured to never expire.
```

2024-06-14 15:37 UTC, warrierr commented on content/en/data_jobs/databricks.md
> +1. Ensure the account generating the token has [CAN VIEW access][9] for the Databricks jobs you want to monitor, and that the token is configured to never expire.
Also, the "as an alternative..." and "ensure account generating token ...." shouldn't be explicity steps, but additional details/alternatives on step 2

2024-06-14 18:24 UTC, alai97 approved these changes
LGTM!

2024-06-14 19:40 UTC, warrierr approved these changes

2024-06-14 19:58 UTC, alpinet approved these changes

2024-06-14 20:00 UTC, alpinet commented
looks good!

2024-06-14 20:24 UTC, merged