[DOCS-7966] Trace Waterfall View
DataDog/documentation pull request #23678
Opened 2024-06-13 22:18 UTC by brett0000FF

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-06-13 22:33 UTC, alai97 approved these changes
LGTM!

2024-06-14 08:06 UTC, dussault-antoine requested changes

2024-06-14 08:06 UTC, dussault-antoine commented on content/en/tracing/trace_explorer/trace_view.md
> +- **Span details**: The corresponding service name, operation name, and resource name are displayed.
```suggestion
- **Span details**: The corresponding service name and resource name are displayed.
```

2024-06-25 16:24 UTC, merged

2024-06-28 14:51 UTC, dussault-antoine reviewed
LGTM 👍