[PROF-9342] Add issue with Ruby profiler dir class to profiler FAQ
DataDog/documentation pull request #23769
Opened 2024-06-19 10:41 UTC by ivoanjo

### What does this PR do? What is the motivation?

This PR adds one more issue we uncovered with the Ruby profiler to the profiler FAQ.

I've also gone ahead and cleaned up some of the references we had to older Ruby profiler versions. Given that 1.11.0 and 1.23.0 are > 1 year old, I think it makes more sense for the text to just assume customers are using 1.11.0 or later, rather than explaining how there's this "new" thing that changed in those versions.

### Merge instructions

This PR should only be merged after [version 2.2.0 of the Ruby library gets released](https://github.com/DataDog/dd-trace-rb/milestone/147). Aka please review, and I'll put a reminder and come back once the release is out :)

- [ ] Please merge after reviewing

### Additional notes

N/A

2024-06-19 17:25 UTC, kayayarai requested changes
Fixing a linter warning

2024-06-19 17:25 UTC, kayayarai commented on content/en/profiler/profiler_troubleshooting/ruby.md
> +The Ruby profiler gathers data by sending `SIGPROF` unix signals to Ruby applications, enabling finer-grained data gathering.
```suggestion
The Ruby profiler gathers data by sending `SIGPROF` UNIX signals to Ruby applications, enabling finer-grained data gathering.
```

2024-06-19 17:26 UTC, kayayarai approved these changes
Thanks Ivo, looks good. Ping us in #documentation when it's ready to merge

2024-07-11 13:09 UTC, ivoanjo commented
Version 2.2.0 of the Ruby library has been released, please go ahead and merge this PR :)

2024-07-11 15:04 UTC, merged

2024-07-11 15:38 UTC, ivoanjo commented
Thank you!