[SFTY-925] Add Safety Center documentation
DataDog/documentation pull request #23820
Opened 2024-06-24 12:49 UTC by yaro-dd

### What does this PR do? What is the motivation?

Safety Center is currently in public beta. This PR adds official documentation before we start promoting Safety Center more actively.

https://datadoghq.atlassian.net/browse/SFTY-925

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

Safety Center can be found both in [staging](https://dd.datad0g.com/organization-settings/safety-center) in [prod](https://app.datadoghq.com/organization-settings/safety-center).

2024-06-24 14:39 UTC, daisukixci approved these changes

2024-06-24 15:55 UTC, rtrieu commented
Created DOCS-8300 for docs team review.

2024-06-25 18:22 UTC, aliciascott requested changes
Hi @yaro-dd this looks great, just a couple of small suggestions and please remove the updates to the non English language menu files, we only need to update the English files as we have a translation process that will update the others :)
Go ahead and request a re-review once the changes are in place, thanks !

2024-06-25 18:22 UTC, aliciascott commented on content/en/account_management/safety_center.md
> +- [Admin users][1] in case their number exceeds 10% of all users within an organization.
```suggestion
- [Admin users][1] in the event their number exceeds 10% of all users within an organization.
```

2024-06-25 18:22 UTC, aliciascott commented on content/en/account_management/safety_center.md
> +Giving **admin access** to users without careful consideration increases potential security risks in case a user account with elevated privileges gets compromised. To keep the number of users with **
```suggestion
Giving **admin access** to users without careful consideration increases potential security risks in the event where a user account with elevated privileges gets compromised. To keep the number of users with **admin access** low, review your admin users regularly and revoke admin privileges if users do not require them.
```

2024-06-25 19:04 UTC, yaro-dd commented
Thank you so much for the review @aliciascott! Addressed the comments ✅

2024-06-25 20:10 UTC, aliciascott approved these changes
Hi @yaro-dd sorry I had one more suggestion, since Safety Center is in public beta, we should add the banner at the top of the page:

It can be something simple like this:

<div class="alert alert-info">Datadog Safety Center is in public beta.</div>

Reference: https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/1182958054/Markdown#Callouts-(formerly-beta-callout)

If you don't mind adding that then I can go ahead and get this merged :)

2024-06-25 20:56 UTC, merged