[rum] DOCS-7945 Retrieve Session ID at runtime for Android/iOS/Flutter
DataDog/documentation pull request #23861
Opened 2024-06-25 20:22 UTC by rtrieu

### What does this PR do? What is the motivation?

Adds details on how to retrieve session IDs for Android, iOS, and Flutter

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-06-27 18:14 UTC, MaelNamNam requested changes
Thanks for putting all of this together, but I feel we should ensure the info is at the same place for each platform.

Currently we have

Android | iOS | React Native | Flutter
-- | -- | -- | --
Overview | Enrich user sessions | Overview | Overview
Enrich user sessions | Track custom global attributes | Testing with Jest | Automatic View Tracking
Track custom global attributes | **`Retrieve the RUM session ID`** | Initialization parameters | Enrich user sessions
Track widgets | Initialization Parameters | Manual instrumentation | Track custom global attributes
Initialization parameters | Modify or drop RUM events | Modify or drop RUM events | **`Retrieve the RUM session ID`**
Modify or drop RUM events | Set tracking consent (GDPR compliance) | **`Retrieve the RUM session ID`** | Modify or drop RUM events
**`Retrieve the RUM session ID`** | Sending data when device is offline | Resource timings | Set tracking consent (GDPR & CCPA compliance)
Further Reading | Further Reading | Initializing asynchronously | Flutter-specific performance metrics
  |   | Delaying the initialization | Sending data when device is offline
  |   | Monitoring hybrid React Native applications | OpenTelemetry setup
  |   | Further reading | Further reading

Let's not necessarily reshuffle the entire structure right now, but could you move the "Retrieve the RUM session ID" section after the "Modify or drop RUM events" one on
- [x] iOS
- [ ] Flutter

please?

2024-06-27 18:42 UTC, rtrieu commented
@MaelNamNam thanks for the review and taking the time to show the inconsistencies via the table, which I never thought to do. I'll add making this more consistent to my to-do list!

2024-06-27 19:50 UTC, cswatt approved these changes

2024-06-27 21:33 UTC, MaelNamNam approved these changes
LGTM!

2024-06-28 07:42 UTC, xgouchet approved these changes

2024-06-28 13:01 UTC, merged