Stefon.simmons/update kind fm 7
DataDog/documentation pull request #23919
Opened 2024-06-27 21:28 UTC by StefonSimmons

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-06-28 21:09 UTC, csantosdd approved these changes

2024-06-28 21:49 UTC, buraizu commented
Created DOCS-8356 to review

2024-07-01 16:45 UTC, buraizu requested changes
Looks like code blocks are being modified in:
- `content/fr/database_monitoring/setup_postgres/rds.md`
- `content/fr/database_monitoring/setup_sql_server/azure.md`

2024-07-01 18:30 UTC, buraizu approved these changes

2024-07-01 18:57 UTC, merged