Stefon.simmons/bump hugo bin version
DataDog/documentation pull request #23949
Opened 2024-07-01 18:09 UTC by StefonSimmons

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-07-08 19:25 UTC, domalessi approved these changes

2024-07-10 09:14 UTC, davidejones requested changes
I've noticed a few things:

- The [404 page](https://docs-staging.datadoghq.com/stefon.simmons/bump-hugo-bin-version/404.html) has no left nav 
- I've also noticed a number of urls now have the anchor in the href or query params in it, this doesn't appear to be causing any issues but thought i should call it out
<img width="887" alt="Screenshot 2024-07-10 at 10 02 18" src="https://github.com/DataDog/documentation/assets/871552/a3f67a4e-4589-4aea-874e-4790e1ff4ca3">
- Some images aren't working e.g see these pages [here](https://docs-staging.datadoghq.com/stefon.simmons/bump-hugo-bin-version/service_management/events/) and [here](https://docs-staging.datadoghq.com/stefon.simmons/bump-hugo-bin-version/service_management/case_management/)

2024-07-11 20:02 UTC, bgdeutsch commented
> I've noticed a few things:
> 
> * An update with master locally meant i also needed to update en/agent/guide to remove some more kind entries
> * The [404 page](https://docs-staging.datadoghq.com/stefon.simmons/bump-hugo-bin-version/404.html) has no left nav
> * Some images aren't working e.g see these pages [here](https://docs-staging.datadoghq.com/stefon.simmons/bump-hugo-bin-version/service_management/events/) and [here](https://docs-staging.datadoghq.com/stefon.simmons/bump-hugo-bin-version/service_management/case_management/)
> * I've also noticed a number of urls now have the anchor in the href or query params in it, this doesn't appear to be causing any issues but thought i should call it out

thanks @davidejones!
- there may still be some commits containing `kind` from translations or other changes.   that param is mostly gone from source files in transifex, and any working branches in docs containing `kind` will just have to be updated after this PR goes out.
- 404 page should be showing the left nav now
- images should be working again
- the URLs containing anchor or query params doesnt seem to have any effect as you mentioned.

2024-07-12 15:08 UTC, davidejones approved these changes

2024-07-12 16:05 UTC, hestonhoffman approved these changes
Poked around in preview - LGTM, but I think the cache value needs to be switched back?

2024-07-12 16:05 UTC, hestonhoffman commented on local/bin/py/build/configurations/pull_config_preview.yaml
> +    cache_enabled: false
Need to switch this back?

2024-07-12 19:31 UTC, domalessi approved these changes

2024-07-12 20:09 UTC, hestonhoffman reviewed
local build is also failing for me on:
Error: error building site: process: readAndProcessContent: "/Users/heston.hoffman/repos/documentation/content/en/code_analysis/static_analysis_rules/csharp-best-practices/avoid-call-gc-suppress-finalize.md:1:1": unknown kind "documentation" in front matter
Weird that it's not happening in CI. I did a clean-all before building.
Does the logic that removes the kind parameter need to be in the pull-and-push-folder action as well?

2024-07-15 18:02 UTC, hestonhoffman approved these changes

2024-07-15 19:14 UTC, merged