docs(vscode): add exception replay feature
DataDog/documentation pull request #23944
Opened 2024-07-01 14:10 UTC by robertohuertasm

IDE-2999

### What does this PR do? What is the motivation?

This PR adds the new Exception Replay feature to the Datadog VS Code extension documentation.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-07-01 16:38 UTC, rtrieu commented
Hi @robertohuertasm, the paragraph you currently have for Exception Replay is a bit marketing-sounding. It should not point to the blog post. Can you please write instructions on how to use Exception Replay here? For example, it should include:

- Action-oriented benefits to the feature
- How to enable it / prerequisites
- How to navigate to it
- How to use use it (e.g. local variable data to reproduce exceptions and accelerate bugging, etc.)

Please let me know if you have any questions! Thank you!

2024-07-01 17:03 UTC, robertohuertasm commented
@rtrieu it makes sense. Thanks for the comment. Indeed, I used some text from the blog post. I'll revisit this and will try to follow your guidelines.

2024-07-01 17:52 UTC, robertohuertasm commented
@rtrieu I pushed a new version. Feel free to correct, suggest or edit as you see fit.

2024-07-02 14:22 UTC, rtrieu reviewed
Left some feedback and will add the blog post as a Further Reading in a separate commit.

2024-07-02 15:51 UTC, robertohuertasm commented on content/en/developers/ide_plugins/vscode/_index.md
> +Check out the following video to see the feature in action:
Hi @rtrieu, the video shows what has been described in the previous paragraph. Isn´t that enough?

2024-07-02 16:30 UTC, robertohuertasm commented on content/en/developers/ide_plugins/vscode/_index.md
> +Check out the following video to see the feature in action:
Maybe I should remove the sentence...?

2024-07-02 16:31 UTC, robertohuertasm commented on content/en/developers/ide_plugins/vscode/_index.md
> +In order to get access to this feature, you have to enable [Error Tracking Exception Replay][29] on Datadog.
@rtrieu one of my teammates suggested to add `on Datadog` to avoid users thinking this is something we can enabled in the extension itself. WDYT?

2024-07-02 21:33 UTC, robertohuertasm commented on content/en/developers/ide_plugins/vscode/_index.md
> +Check out the following video to see the feature in action:
Ok, I changed the text trying to follow your instructions. Let me know what do you think. Happy to change it if needed. Thank you for your support!

2024-07-03 21:00 UTC, rtrieu requested changes
Some minor feedback but otherwise looking good!

2024-07-04 10:55 UTC, robertohuertasm commented
Thanks @rtrieu for your suggestions! Merged all of them.

2024-07-04 23:21 UTC, robertohuertasm commented
@rtrieu, please let me know if there's anything missing for this PR to be approved and merged. Thanks again for your help!

2024-07-08 14:09 UTC, rtrieu approved these changes
LGTM

2024-07-08 14:09 UTC, merged