Update requirements for Data Jobs Monitoring EMR setup page
DataDog/documentation pull request #23987
Opened 2024-07-02 22:23 UTC by yiliangzhou

### What does this PR do? What is the motivation?

Data Jobs Monitoring updated its setup process to support earlier EMR releases, update the documentation to reflect this in the requirement section of the setup page.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-07-16 21:29 UTC, gabe-ochoa approved these changes

2024-07-16 21:30 UTC, warrierr requested changes

2024-07-16 21:30 UTC, warrierr commented on content/en/data_jobs/emr.md
> +You can skip this step if you are using the default role **EMR_EC2_DefaultRole** for cluster EC2 instances and its associated AWS default managed policy, **AmazonElasticMapReduceforEC2Role**.
```suggestion
Only do this step if you are NOT using the default role **EMR_EC2_DefaultRole** for cluster EC2 instances and its associated AWS default managed policy, **AmazonElasticMapReduceforEC2Role**.
```

2024-07-17 15:59 UTC, drichards-87 commented
Created DOCS-8472 for Docs Team review.

2024-07-17 19:10 UTC, warrierr approved these changes
LGTM

2024-07-19 19:49 UTC, warrierr requested changes

2024-07-19 19:49 UTC, warrierr commented on content/en/data_jobs/emr.md
> +#### Permissions to get secret value using AWS Secret Management (Recommended)
```suggestion
#### Permissions to get secret value using AWS Secret Management (required if using Secrets Manager)
```

2024-07-19 19:49 UTC, warrierr commented on content/en/data_jobs/emr.md
> +EMR EC2 instance profile is a IAM role assigned to every EC2 instance in an Amazon EMR cluster when the instance launches, follow [the offical guide][11] to prepare this role based on your applicatio
```suggestion
EMR EC2 instance profile is a IAM role assigned to every EC2 instance in an Amazon EMR cluster when the instance launches, follow [the offical guide][11] to prepare this role based on your application's need to interact with other AWS services. The following additional permssions may be required for Data Jobs Monitoring.
```

2024-07-19 19:49 UTC, warrierr commented on content/en/data_jobs/emr.md
> +#### Permissions to describe cluster
```suggestion
#### Permissions to describe cluster (required if NOT using the default role EMR_EC2_DefaultRole)
```

2024-07-19 19:49 UTC, warrierr commented on content/en/data_jobs/emr.md
> +Only do this step if you are NOT using the default role **EMR_EC2_DefaultRole** for cluster EC2 instances and its associated AWS default managed policy, **AmazonElasticMapReduceforEC2Role**.
```suggestion
```

2024-07-19 20:49 UTC, cswatt commented on content/en/data_jobs/emr.md
> +EMR EC2 instance profile is a IAM role assigned to every EC2 instance in an Amazon EMR cluster when the instance launches, follow [the offical guide][11] to prepare this role based on your applicatio
```suggestion
EMR EC2 instance profile is a IAM role assigned to every EC2 instance in an Amazon EMR cluster when the instance launches. Follow [the Amazon guide][11] to prepare this role based on your application's need to interact with other AWS services. The following additional permissions may be required for Data Jobs Monitoring.
```

2024-07-19 20:49 UTC, cswatt commented on content/en/data_jobs/emr.md
> +#### Permissions to get secret value using AWS Secret Management (required if using Secrets Manager)
```suggestion
#### Permissions to get secret value using AWS Secrets Manager

<div class="alert alert-warning">
These permissions are <strong>required</strong> if you are using AWS Secrets Manager.
</div>
```

2024-07-19 20:49 UTC, cswatt commented on content/en/data_jobs/emr.md
> +#### Permissions to describe cluster (required if NOT using the default role EMR_EC2_DefaultRole)
```suggestion
#### Permissions to describe cluster

<div class="alert alert-warning">
These permissions are <strong>required</strong> if you are <strong>NOT</strong> using the default role, <code>EMR_EC2_DefaultRole</code>.
</div>
```

2024-07-19 20:49 UTC, cswatt commented on content/en/data_jobs/emr.md
> +   The script above sets the required parameters, downloads and runs the latest init script for Data Jobs Monitoring in EMR. If you want to pin your script to a specific version, you can replace the
```suggestion
   The script above sets the required parameters, and downloads and runs the latest init script for Data Jobs Monitoring in EMR. If you want to pin your script to a specific version, you can replace the file name in the URL with `emr_init_1.4.0.sh` to use the last stable version.
```

2024-07-19 22:04 UTC, cswatt approved these changes

2024-07-19 22:04 UTC, merged