Update Test Visibility docs: add links to Github Action
DataDog/documentation pull request #23993
Opened 2024-07-03 12:11 UTC by nikita-tkachenko-datadog

### What does this PR do? What is the motivation?

This PR updates Test Visibility setup docs for .NET, Java, JS and Python.
A link to Test Visibility Github Action is added for this languages.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-07-03 21:59 UTC, urseberry requested changes
Can you change the links to use numbered links instead of HTML links? Our translation process does not support HTML links. Here is some documentation on how to properly add links within a tab in the public documentation: https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/1182958054/Markdown#Tabs

2024-07-03 21:59 UTC, urseberry commented on content/en/tests/setup/java.md
> +Configuring Datadog Java Tracer varies depending on your CI provider.
```suggestion
Configuring the Datadog Java Tracer varies depending on your CI provider.
```

2024-07-03 21:59 UTC, urseberry commented on content/en/tests/setup/java.md
> +If you do so, you can skip the "Downloading tracer library" and "Running your tests" steps below.
```suggestion
If you do so, you can skip the **Downloading tracer library** and **Running your tests** steps below.
```

2024-07-04 09:09 UTC, nikita-tkachenko-datadog commented
> Can you change the links to use numbered links instead of HTML links? Our translation process does not support HTML links. Here is some documentation on how to properly add links within a tab in the public documentation: https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/1182958054/Markdown#Tabs

Thanks for the explanation, replaced the HTML links with the numbered links.

2024-07-05 20:58 UTC, urseberry approved these changes

2024-07-05 20:59 UTC, merged