Add Rust sdk examples to api documentation
DataDog/documentation pull request #24187
Opened 2024-07-16 21:20 UTC by nkzou

### What does this PR do? What is the motivation?

adds Rust SDK code examples to the public api docs

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-07-17 15:50 UTC, drichards-87 requested changes

2024-07-17 15:50 UTC, drichards-87 commented on content/en/api/latest/_index.md
> +Run `cargo add datadog-api-client` or add the following to `Cargo.toml` under `[dependencies]`:
```suggestion
Run `cargo add datadog-api-client`, or add the following to `Cargo.toml` under `[dependencies]`:
```

2024-07-17 15:58 UTC, renteria1010 approved these changes

2024-07-18 15:05 UTC, drichards-87 approved these changes
@nkzou Are you waiting for additional approvals, or are we good to merge this now?

2024-07-18 15:08 UTC, nkzou commented
> @nkzou Are you waiting for additional approvals, or are we good to merge this now?

I'm planning to merge this in 2 weeks after our next set of Client library releases - currently this PR works because in `data/sdk_versions.json`, the rust sdk is set to the latest master branch and contains properly formatted examples. If we merge it now I think the bump sdk job will try to replace `master` with `0.1.3` which is an older version that will break the examples.

2024-07-18 15:27 UTC, drichards-87 commented
@nkzou Sounds good. You can reach out to me or the Documentation Slack channel when this is ready to be merged.

2024-08-01 20:18 UTC, merged