Adding custom error collection info to the ET FE standalone docs
DataDog/documentation pull request #24241
Opened 2024-07-21 17:12 UTC by meghanlo

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-07-22 13:29 UTC, estherk15 commented
Docs editorial review: https://datadoghq.atlassian.net/browse/DOCS-8506

2024-07-26 16:56 UTC, rtrieu requested changes
Added an intro to the feature, and I am wondering what the purpose of `content/en/error_tracking/standalone_frontend/collecting_browser_errors.md` is, but otherwise looks good.

2024-07-26 16:56 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/browser.md
> +For more information about collecting browser errors, check our documentation [here][2]
```suggestion
You can monitor handled exceptions, handled promise rejections, and other errors that the Browser SDK does not automatically track. Learn more about [Collecting Browser Errors][2].
```

2024-07-26 16:56 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/browser.md
> +Monitor handled exceptions, handled promise rejections, and other errors not tracked automatically by the Browser SDK with the `addError()` API:
```suggestion
To manually collect errors, use the `addError()` API:
```

2024-07-26 18:23 UTC, rtrieu approved these changes
Looks good!

2024-07-29 17:06 UTC, merged