List SPM as the recommended package manager
DataDog/documentation pull request #24347
Opened 2024-07-26 17:18 UTC by jhgilbert

### What does this PR do? What is the motivation?
Fulfills a request made during a security review of [this PR](https://github.com/DataDog/documentation/pull/24142).

DOCS-8402

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-07-29 09:15 UTC, maxep approved these changes
Thank you, @jhgilbert 🙏

2024-07-29 09:42 UTC, olacin-dd approved these changes
Approving for the security incident response team 👍 

Thank you !

2024-07-29 10:02 UTC, plousada approved these changes

2024-07-29 16:29 UTC, drichards-87 requested changes
Left a note about an inline link.

2024-07-29 16:29 UTC, drichards-87 commented on content/en/tracing/trace_collection/custom_instrumentation/ios/otel.md
> +You can use [CocoaPods](https://cocoapods.org/) to install `dd-sdk-ios`:
Just FYI, this link is formatted inline.

2024-07-31 19:16 UTC, drichards-87 approved these changes

2024-07-31 19:46 UTC, merged