Add glibc error
DataDog/documentation pull request #24348
Opened 2024-07-26 17:43 UTC by juli1

### What does this PR do? What is the motivation?

This PR adds more error cases customers had. Customers will find the resolution to these issues in the page instead of asking a customer success manager.

2024-07-26 18:49 UTC, michaelcretzman approved these changes
Approved with minor suggestions.

2024-07-26 18:49 UTC, michaelcretzman commented on content/en/code_analysis/troubleshooting/_index.md
> +- running your CI pipeline with a Linux distribution that contains an old version of the glibc. In this case, we
```suggestion
- running your CI pipeline with a Linux distribution that contains an old version of the glibc. In this case,
```

2024-07-26 18:49 UTC, michaelcretzman commented on content/en/code_analysis/troubleshooting/_index.md
> +  recommend you upgrade to the latest version. Our analyzer will always run with the latest of Ubuntu/Debian based-systems.
```suggestion
  recommend you upgrade to the latest version. The analyzer will always run with the latest of Ubuntu/Debian based-systems.
```

2024-07-26 18:49 UTC, michaelcretzman commented on content/en/code_analysis/troubleshooting/_index.md
> +- running your CI pipeline with a Linux distribution that does not rely on the glibc (such as Alpine Linux). We recommend
```suggestion
- running your CI pipeline with a Linux distribution that does not rely on the glibc (such as Alpine Linux). Instead,
```

2024-07-26 18:49 UTC, michaelcretzman commented on content/en/code_analysis/troubleshooting/_index.md
> +If you are running on a non-GitHub repository, make sure you first commit on your default branch (e.g. branch name like
```suggestion
If you are running on a non-Github repository, ensure you first commit on your default branch (for example, a branch name like
```

2024-07-26 18:49 UTC, michaelcretzman commented on content/en/code_analysis/troubleshooting/_index.md
> +If you are running on a non-GitHub repository, make sure you first commit on your default branch (e.g. branch name like
```suggestion
If you are running on a non-Github repository, ensure you first commit on your default branch (for example, a branch name like
```

2024-07-26 19:04 UTC, juli1 commented
/merge

2024-07-29 12:33 UTC, kassenq requested changes

2024-07-29 12:33 UTC, kassenq commented on content/en/code_analysis/troubleshooting/_index.md
> +  recommend you upgrade to the latest version. The analyzer will always run with the latest of Ubuntu/Debian based-systems.
"In this case, Datadog recommends upgrading to the latest version."

2024-07-29 12:33 UTC, kassenq commented on content/en/code_analysis/troubleshooting/_index.md
> +If you are running on a non-Github repository, ensure you first commit on your default branch (for example, a branch name like
"If you are running Code Analysis on a non-GitHub repository, ensure that the first scan is ran on your default branch ...."

2024-07-29 14:52 UTC, jacobotb commented on content/en/code_analysis/troubleshooting/_index.md
> +  you run your CI pipeline with a distribution that supports the latest version of the glibc (such as the stable version of Ubuntu).
```suggestion
  run your CI pipeline with a distribution that supports the latest version of the glibc (such as the stable version of Ubuntu).
```

2024-07-29 15:04 UTC, jacobotb approved these changes

2024-07-30 00:53 UTC, kassenq approved these changes

2024-07-30 00:55 UTC, juli1 commented
/merge

2024-07-30 16:22 UTC, merged