Code Analysis: add FAQ
DataDog/documentation pull request #24356
Opened 2024-07-26 20:15 UTC by juli1

### What does this PR do? What is the motivation?

We add a list of frequently asked questions that customers asked us during calls. This way, we can easily refer them to the list of questions and customers can proactively learn about the capabilities of our tools.

2024-07-26 20:54 UTC, michaelcretzman requested changes
Please incorporate the suggested edits.

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +## Common Questions
```suggestion
## Common questions
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +With Datadog-hosted scans, you do not need to do the heavy lifting and configure any CI pipeline to run the analyzer.
```suggestion
When using a Datadog-hosted scan, Datadog scans your code within the Datadog infrastructure. Datadog acts
as a CI pipeline: it clones your code, runs the analyzer, and uploads the results for you.

With Datadog-hosted scans, you do not need to do the heavy lifting and configure any CI pipeline to run the analyzer.
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +## Static Analysis
```suggestion
## Static analysis
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +### May I import results from other analyzers into Datadog?
```suggestion
### Can results be imported into Datadog from other analyzers?
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +While we recommend to use the Datadog Static Analyzer tool[4], Datadog supports the ingestion of files that enforces the SARIF format.
```suggestion
While the [Datadog Static Analyzer tool][4] is recommended, Datadog supports the ingestion of files that enforce the SARIF format.
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> + - Invoke the tool to upload the file to Datadog.
```suggestion
1. Install the `datadog-ci` CLI (requires that Node.js is installed).
2. Ensure that your `DD_SITE`, `DD_API_KEY`, and `DD_APP_KEY` environment variables are set.
3. Invoke the tool to upload the file to Datadog.
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +If you want to import from a tool not support at this time, please contact your Customer Success Manager.
```suggestion
If you want to import using a tool that is not supported currently, contact your Customer Success Manager.
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +### Can I write custom rules?
```suggestion
### Can custom rules be used?
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +Custom rules will be available to all beta customers at the end of Q3 2024.
```suggestion
Custom rule availability is planned for all beta customers at the end of Q3 2024.
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +the [static analyzer documentation][5]
```suggestion
Our Static Analyzer has been tested against the OWASP benchmark with a score of 44. We periodically update the results against the benchmark and publish the results in the [static analyzer documentation][5].
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +is [available on GitHub][4].
```suggestion
The Datadog Static Analyzer is available under an open-source license and the code is [available on Github][4].
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +### May I import any SBOM file in Datadog?
```suggestion
### Can I import any SBOM file into Datadog?
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +While we recommend to use Datadog SBOM generator tool[6], Datadog supports the ingestion of any SBOM files.
```suggestion
While the [Datadog SBOM generator tool][6] is recommended, Datadog supports the ingestion of any SBOM files.
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +Datadog only supports SBOM file with the Cyclone-DX 1.4 and Cyclone-DX 1.5 formats.
```suggestion
Datadog only supports SBOM files with the Cyclone-DX 1.4 and Cyclone-DX 1.5 formats.
```

2024-07-26 20:54 UTC, michaelcretzman commented on content/en/code_analysis/faq/_index.md
> +- Invoke the tool to upload the file to Datadog.
```suggestion
To ingest your SARIF file into Datadog:
1. Install the `datadog-ci` CLI (requires that Node.js is installed).
2. Ensure that your `DD_SITE`, `DD_API_KEY` and `DD_APP_KEY` environment variables are set.
3. Invoke the tool to upload the file to Datadog.
```

2024-07-26 21:09 UTC, michaelcretzman approved these changes

2024-07-29 12:31 UTC, kassenq requested changes

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +When using a Datadog-hosted scan, Datadog scans your code within the Datadog infrastructure. Datadog acts
With Datadog-hosted scans, your code is scanned within Datadog's infrastructure as opposed to within your CI pipeline. Datadog clones your code, runs the static analyzer to perform Static Analysis and/or Software Composition Analysis, and uploads the results for you.

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +With Datadog-hosted scans, you do not need to do the heavy lifting and configure any CI pipeline to run the analyzer.
The benefit of Datadog-hosted scans is that no configuration is needed in your CI pipeline(s) to use Code Analysis.

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +## Static analysis
capitalize Analysis

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +While the [Datadog Static Analyzer tool][4] is recommended, Datadog supports the ingestion of files that enforce the SARIF format.
remove tool - "Datadog Static Analyzer"

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +While the [Datadog Static Analyzer tool][4] is recommended, Datadog supports the ingestion of files that enforce the SARIF format.
"files that adhere to SARIF format"

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +At this time, we tested our API with the following tools:
Ingestion of SARIF files is verified for the following third-party tools:

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +Scans on the default branches are always full scans.
Remove the - "Scans on default branches are always full scans."

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +Scans on non-default branches use *diff-aware* scans. With diff-aware scans, the analyzer only
By default, scans on non-default branches use ...

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +last seconds while full-scans may take a few minutes (depending on the codebase).
last seconds, while

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +In order for diff-aware to scan, you need to be using the Datadog platform.
You must be using Datadog's analyzer to enable diff-aware scans.

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +### What is Datadog Static Analyzer on the OWASP benchmark?
"What is Datadog's OWASP benchmark score for Static Analysis?"

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +Our Static Analyzer has been tested against the OWASP benchmark with a score of 44. We periodically update the results against the benchmark and publish the results in the [static analyzer documentat
Datadog's Static Analyzer has been tested against the OWASP benchmark with a score of 44. The analyzer is periodically checked against the benchmark and updated results are published to the [static analyzer documentation][5].

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +The Datadog Static Analyzer is available under an open-source license and the code is [available on Github][4].
can we specify the license?

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +While the [Datadog SBOM generator tool][6] is recommended, Datadog supports the ingestion of any SBOM files.
remove "tool"

2024-07-29 12:31 UTC, kassenq commented on content/en/code_analysis/faq/_index.md
> +At this time, we tested our CLI tools with the following tools:
Ingestion of SBOM files is verified for the following third-party tools:

2024-07-30 01:06 UTC, juli1 commented
/merge

2024-07-30 11:52 UTC, dastrong commented on content/en/code_analysis/faq/_index.md
> +To ingest your SARIF file into Datadog:
```suggestion
To ingest your SBOM file into Datadog:
```

2024-07-30 13:31 UTC, dastrong approved these changes

2024-07-30 16:20 UTC, merged