Update troubleshooting.md
DataDog/documentation pull request #24463
Opened 2024-08-05 12:22 UTC by lee-brian

Include more info on how monitors are tagged to services

### What does this PR do? What is the motivation?

### Merge instructions

- [ x] Please merge after reviewing

### Additional notes

2024-08-05 19:01 UTC, rtrieu requested changes
Minor feedback but otherwise looks good!

2024-08-05 19:01 UTC, rtrieu commented on content/en/service_catalog/guides/troubleshooting.md
> +The Service Catalog associates monitors to services when are tagged, scoped or grouped with service or [APM primary tags][3].
```suggestion
The Service Catalog associates monitors to services when they are tagged, scoped, or grouped with service or [APM primary tags][3]. 
```

2024-08-28 18:23 UTC, lee-brian reviewed
Looks good! Thank you

2024-08-28 18:27 UTC, rtrieu approved these changes
LGTM

2024-08-28 18:57 UTC, merged