Add standalone Application Security guide
DataDog/documentation pull request #24644
Opened 2024-08-14 14:50 UTC by smola

### What does this PR do? What is the motivation?
Add a guide about standalone Application Security, which can be used to enable some of our products without requiring APM.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2025-03-10 19:31 UTC, michaelcretzman requested changes

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +title: Using standalone Application Security products
```suggestion
title: Set Up Application Security Products without using APM
```

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +title: Using standalone Application Security products
I think this title is a clearer explanation of what this guide does

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +DataDog [Application Threat Management][1] and [Code Security][2] are built on top of [APM][3]. While recommend using our application security products alongside with APM and adopt DevSecOps practice
```suggestion
Datadog ASM [Threat Management][1] and [Code Security][2] are built on top of [APM][3]. While Datadog recommends using these security products with APM and adopting DevSecOps practices, you can also use these security products without using APM. This configuration is referred to as Standalone Application Security. This guide explains how to set up Standalone Application Security. 
```

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +* **Supported Tracing Library:** The Datadog Tracing Library used by your application or service supports application security. For more details, refer to the to the setuo guides for [Appplication Th
```suggestion
This guide assumes you have the following:

- **Datadog Agent installation:** The Datadog Agent is installed and configured for your application’s operating system, container, cloud, or virtual environment.
- **Supported Tracing Library:** The Datadog Tracing Library used by your application or service supports application security. For more details, see the guides for [Application Threat Management][4] or [Code Security][5].
```

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +### Agent setup
```suggestion
```

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +However, when setting up the Tracing Library, you should add the `DD_APM_TRACING_ENABLED=false` environment variable to the service that runs the Tracing Library.
```suggestion
Set up the Datadog Agent using the standard method for APM or Application Security setup, but set up the Tracing Library by adding the `DD_APM_TRACING_ENABLED=false` environment variable to the service that runs the Tracing Library.
```

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +This environment variable will reduce the amount of APM data sent to Datadog to a minimum required by Application Security products. It can then be combined with environment variables to enable Appli
```suggestion
This environment variable will reduce the amount of APM data sent to Datadog to the minimum required by Application Security products. The environment variable can then be combined with environment variables to enable ASM Threat Management or Code Security.
```

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +For Application Threat Management, add the `DD_APM_TRACING_ENABLED=false DD_APPSEC_ENABLED=true` environment variables.
```suggestion
For ASM Threat Management, add the `DD_APM_TRACING_ENABLED=false DD_APPSEC_ENABLED=true` environment variable.
```

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +For Code Security, add the `DD_APM_TRACING_ENABLED=false DD_IAST_ENABLED=true` environment variables.
```suggestion
For Code Security, add the `DD_APM_TRACING_ENABLED=false DD_IAST_ENABLED=true` environment variable.
```

2025-03-10 19:31 UTC, michaelcretzman commented on content/en/security/application_security/guide/standalone_application_security.md
> +{{< partial name="whats-next/whats-next.html" >}}
```suggestion
```

2025-03-13 10:22 UTC, robertpi commented
Hey @michaelcretzman , I applied you're changes, are we good to merge now?

2025-03-13 16:28 UTC, michaelcretzman approved these changes

2025-03-13 20:36 UTC, merged

2025-03-13 20:37 UTC, michaelcretzman commented
@robertpi merged. thanks!