[MLOBS] Update IO in API docs
DataDog/documentation pull request #24693
Opened 2024-08-16 16:14 UTC by lievan

### What does this PR do? What is the motivation?

Add documentation for `Document` IO type and add clarification for setting IO values 

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-08-16 17:17 UTC, Yun-Kim approved these changes

2024-08-16 18:43 UTC, aliciascott requested changes
Hi @lievan some small changes on this one too, don't need the extra bracket for the links, let me know once updated and I'll approve and merge.

2024-08-16 18:43 UTC, aliciascott commented on content/en/llm_observability/setup/api.md
> +| value   | string | Input or output value. If not set, this value will be inferred from messages or documents. |
```suggestion
| value   | string | Input or output value. If not set, this value is inferred from messages or documents. |
```

2024-08-16 18:43 UTC, aliciascott commented on content/en/llm_observability/setup/api.md
>  | messages| [[Message](#message)] | List of messages. This should only be used for LLM spans. |
```suggestion
| messages| [Message](#message) | List of messages. This should only be used for LLM spans. |
```

2024-08-16 18:43 UTC, aliciascott commented on content/en/llm_observability/setup/api.md
> +| documents| [[Document](#document)] | List of documents. This should only be used as the output for retrieval spans |
```suggestion
| documents| [Document](#document) | List of documents. This should only be used as the output for retrieval spans |
```

2024-08-20 19:10 UTC, aliciascott approved these changes
Hi @lievan just re-approved after the last changes, thanks! Is this ready to be merged ?

2024-08-21 17:46 UTC, lievan commented
Yep this is ready to be merged, thanks! @aliciascott

2024-08-21 18:59 UTC, merged