[MLOBS] Update instrumentation examples in SDK docs
DataDog/documentation pull request #24692
Opened 2024-08-16 16:04 UTC by lievan

### What does this PR do? What is the motivation?

Instrumentation examples are bit outdated, customers have been directly copy pasting the logic in them which results in issues. This PR updates the instrumentation examples to contain more guidance on best practices. 

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-08-16 17:17 UTC, Yun-Kim approved these changes

2024-08-16 18:39 UTC, aliciascott requested changes
Hi @lievan just a small suggestion! let me know when it's updated and i'll approve and merge!

2024-08-20 19:08 UTC, aliciascott approved these changes

2024-08-20 19:09 UTC, aliciascott commented
Hi @lievan thanks for the update, I just approved, is this ready to merge?

2024-08-20 20:11 UTC, lievan commented
Hi @aliciascott, it is ready to merge, thanks!

2024-08-20 20:28 UTC, merged