[error tracking] Add unified template variables
DataDog/documentation pull request #24736
Opened 2024-08-20 07:16 UTC by GianlucaBortoli

### What does this PR do? What is the motivation?

We're adding "unified" template variables to Error Tracking monitors.
This PR adds the list of additional template variables available for alert messages for Error Tracking monitors only.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-08-20 12:57 UTC, meghanlo approved these changes

2024-08-20 13:53 UTC, rtrieu commented on content/en/monitors/types/error_tracking.md
> +on alert message notifications:
```suggestion
for alert message notifications:
```

2024-08-20 13:53 UTC, rtrieu requested changes
Minor suggestion, but otherwise looks good.

2024-08-20 14:00 UTC, rtrieu approved these changes
Looks good, thanks!

2024-08-26 07:53 UTC, GianlucaBortoli commented
Hi @rtrieu, feel free to merge this PR. Thanks!

2024-08-26 13:41 UTC, merged