Minor updates on some section with outdated information
DataDog/documentation pull request #24752
Opened 2024-08-20 16:13 UTC by mervebolatdd

### What does this PR do? What is the motivation?

Some of the sections on Trace exploration documentation was out of date and misleading. The full list of the changes can be found here: https://docs.google.com/document/d/1Q5R119FUXj31GO86aWv5ZNFIsa7puP5WMfDCcBkmsEo/edit 

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-08-20 20:27 UTC, rtrieu requested changes
Minor feedback, but otherwise looks good!

2024-08-20 20:27 UTC, rtrieu commented on content/en/tracing/trace_explorer/query_syntax.md
> +Once you create a new facet, it will be available in the facet panel for quick filtering and basic analytics.
```suggestion
After you create a new facet, it is available in the facet panel for filtering and basic analytics.
```

2024-08-21 07:39 UTC, mervebolatdd reviewed
Looks great, thanks!

2024-09-02 14:24 UTC, rtrieu approved these changes
LGTM

2024-09-02 14:24 UTC, merged