Error Tracking Standalone Doc Reshuffle
DataDog/documentation pull request #24984
Opened 2024-08-29 14:20 UTC by meghanlo

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-09-09 16:43 UTC, hestonhoffman commented
Hi, created https://datadoghq.atlassian.net/browse/DOCS-8967 for this one. Someone on the docs team will take a look

2024-09-09 17:38 UTC, rtrieu requested changes
Left some minor feedback and a few questions for your review. Mostly looks great though, thanks for this big PR!

2024-09-09 17:38 UTC, rtrieu commented on content/en/error_tracking/backend/exception_replay.md
> +  * `dd-trace-java` version `1.35.0` or higher.
```suggestion
   * `dd-trace-java` version `1.35.0` or higher.
```

2024-09-09 17:38 UTC, rtrieu commented on content/en/error_tracking/backend/exception_replay.md
> +  * `dd-trace-dotnet` version `2.53.0` or higher.
```suggestion
   * `dd-trace-dotnet` version `2.53.0` or higher.
```

2024-09-09 17:38 UTC, rtrieu commented on content/en/error_tracking/backend/exception_replay.md
> +  * `ddtrace` version `1.16.0` or higher.
Indenting these so they are under step 2.

2024-09-09 17:38 UTC, rtrieu commented on content/en/error_tracking/frontend/collecting_browser_errors.md
> +Front-end errors are collected with with Browser SDK. The error message and stack trace are included when available.
```suggestion
Front-end errors are collected with Browser SDK. The error message and stack trace are included when available.
```

2024-09-09 19:47 UTC, rtrieu commented on content/en/error_tracking/_index.md
> +Error Tracking captures and processes errors across your web, mobile, and backend applications. You can instrument your applications and services using the [Browser SDK][6], [Mobile SDK][7], or inges
Updated my suggestion.

2024-09-09 19:52 UTC, meghanlo commented on content/en/error_tracking/frontend/_index.md
Are you saying we should have the framework/language logos on the page instead of a list in the setup section?

2024-09-09 20:18 UTC, rtrieu requested changes
One last minor feedback and then it looks good!

2024-09-09 20:18 UTC, rtrieu commented on content/en/error_tracking/backend/_index.md
> +Datadog's standalone backend Error Tracking is in private beta. Sign up to be notified and added when the private beta opens.
```suggestion
Datadog's standalone backend Error Tracking is in private beta. Sign up to be notified and gain access when the private beta opens.
```

2024-09-09 20:52 UTC, rtrieu commented on content/en/error_tracking/frontend/_index.md
@meghanlo yes, correct

2024-09-09 20:54 UTC, rtrieu approved these changes
LGTM

2024-09-10 15:25 UTC, meghanlo commented on content/en/real_user_monitoring/browser/collecting_browser_errors.md
The RUM pages that we are moving are purely related to Error Tracking. As we are selling Error Tracking as a standalone product, we want all the docs to be available in one place. For those pages we can add rum browser as the owner? But to me it makes sense that all the product docs related to Error Tracking are in one place

2024-09-10 16:30 UTC, meghanlo commented on content/en/real_user_monitoring/browser/collecting_browser_errors.md
Ah I was looking at a different page. Deleting

2024-09-10 16:30 UTC, meghanlo commented on content/en/real_user_monitoring/browser/browser.md
Ah I was looking at a different page. Deleting

2024-09-10 17:12 UTC, meghanlo commented on content/en/real_user_monitoring/browser/collecting_browser_errors.md
I guess Error Tracking is looking to own the error data model + object. Error Tracking is the main use case of collecting errors and the view for those errors in app

2024-09-11 13:53 UTC, BenoitZugmeyer approved these changes

2024-09-11 15:25 UTC, merged