CSM Threats eBPF-free agent guide
DataDog/documentation pull request #25105
Opened 2024-09-05 22:15 UTC by michaelcretzman

DOCS-8668

### What does this PR do? What is the motivation?
how to use ptrace (Linux system call) instead of eBPF

### Merge instructions
Waiting for PM to give the go ahead for this guide before moving it into the review stage.

DO NOT MERGE

2024-10-29 18:07 UTC, maycmlee commented
Created [DOCS-9369](https://datadoghq.atlassian.net/browse/DOCS-9369).

2024-10-29 18:22 UTC, michaelcretzman commented
ed review ticket: https://datadoghq.atlassian.net/browse/DOCS-9370

2024-10-30 14:55 UTC, spikat commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +```
kube section to be removed

2024-10-30 14:55 UTC, spikat commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +FROM datadog/agent-dev:7-55-1-beta-host-ebpfless-v0 AS datadogagent
replace version with datadog/agent:latest

2024-10-30 14:55 UTC, spikat commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +- More performance overhead.
Maybe we can add the why again here: because when attaching we cannot setup any seccomp profile

2024-10-30 14:55 UTC, spikat commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +FROM datadog/agent-dev:7-55-1-beta-host-ebpfless-v0
same here, datadog/agent:latest :)

2024-10-30 21:31 UTC, michaelcretzman commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +Alternartively, to manually install the `.deb/.rmp` provided custom build packages, modify the `/etc/datadog-agent/system-probe.yaml` file to enable CWS and eBPF-free mode as follow:
okay. I added it to the install script section.

2024-10-31 21:47 UTC, drichards-87 requested changes
Left some minor feedback. Also noting that the link to the staging preview doesn't work, likely due to the filename containing uppercase letters. (Which I saw you just noted in Slack, as well.)

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +Alternartively, to manually install the `.deb/.rmp` provided custom build packages, modify the `/etc/datadog-agent/system-probe.yaml` file to enable CWS and eBPF-less mode as follow:
```suggestion
Alternatively, to manually install the `.deb/.rmp` provided custom build packages, modify the `/etc/datadog-agent/system-probe.yaml` file to enable CWS and eBPF-less mode as follows:
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +## Deploy eBPF-less agent
```suggestion
## Deploy eBPF-less Agent
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +- eBPF improves safety by validating each program through the Linux kernel verifier. This ensures that a program can’t crash, fall into infinite loops, harm the system, etc.
```suggestion
- eBPF improves safety by validating each program through the Linux kernel verifier. This ensures that a program can’t crash, fall into infinite loops, or harm the system.
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +The Datadog eBPF agent code is [fully open source][2].
```suggestion
The Datadog eBPF Agent code is [fully open source][2].
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +The following features are not available in the eBPF-less agent:
```suggestion
The following features are not available in the eBPF-less Agent:
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +<div class="alert alert-info">The current implementation supports amd64 and arm64 architecture and ABIs but can be extended to 32-bit ABIs.</div>
```suggestion
<div class="alert alert-info">The current implementation supports amd64 and arm64 architecture and ABIs, but can be extended to 32-bit ABIs.</div>
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +- Open source verification: Datadog has open-sourced the ptrace-based and eBPF agent, allowing clients and the security community to verify its safety and effectiveness themselves, fostering transpar
```suggestion
- Open source verification: Datadog has open-sourced the ptrace-based and eBPF Agent, allowing clients and the security community to verify its safety and effectiveness themselves, fostering transparency and trust in the solution.
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +You can set up the eBPF-less agent on various platforms, including Docker and Linux hosts.
```suggestion
You can set up the eBPF-less Agent on various platforms, including Docker and Linux hosts.
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +This section covers Docker and Linux hosts. For steps on setting up an Amazon fargate environment where eBPF is disabled, see [AWS Fargate Configuration Guide for Datadog Security][3].
```suggestion
This section covers Docker and Linux hosts. For steps on setting up an Amazon Fargate environment where eBPF is disabled, see [AWS Fargate Configuration Guide for Datadog Security][3].
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +Ensure you perform the following configuration requirements before deploying the agent:
```suggestion
Ensure you perform the following configuration requirements before deploying the Agent:
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +2. Install/update the agent with CSM enabled. For steps, see [Setting up Cloud Security Management on the Agent][4].
```suggestion
2. Install/update the Agent with CSM enabled. For steps, see [Setting up Cloud Security Management on the Agent][4]. 
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +To validate your agent installation and setup, connect to your Linux host or Docker container and run:
```suggestion
To validate your Agent installation and setup, connect to your Linux host or Docker container and run:
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +After the eBPF-less agent is installed and set up to use the eBPF-Free mode, you can set up how your application is traced. This section provides you two different methods:
```suggestion
After the eBPF-less Agent is installed and set up to use the eBPF-Free mode, you can set up how your application is traced. This section provides you two different methods:
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +## Set up application tracing with eBPF-less agent
```suggestion
## Set up application tracing with eBPF-less Agent
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +Both modes use the **cws-instrumentation** binary packaged with the datadog agent, and located at `/opt/datadog-agent/embedded/bin/cws-instrumentation`.
```suggestion
Both modes use the **cws-instrumentation** binary packaged with the Datadog Agent, and located at `/opt/datadog-agent/embedded/bin/cws-instrumentation`.
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +This tracer communicates with system-probe (part of the Datadog agent) on localhost using port 5678. The system-probe address can be configured with the <code>--probe-addr=host:port</code> cws-instru
```suggestion
This tracer communicates with system-probe (part of the Datadog Agent) on localhost using port 5678. The system-probe address can be configured with the <code>--probe-addr=host:port</code> cws-instrumentation option. The server-side address can be updated through the runtime_security_config.ebpfless.socket option of the <code>/etc/datadog-agent/system-probe.yaml</code> Agent config file.
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +<div class="alert alert-info">An application won’t start until cws-instrumentation has initialized its connection with the Datadog agent.</div>
```suggestion
<div class="alert alert-info">An application won’t start until cws-instrumentation has initialized its connection with the Datadog Agent.</div>
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +- Use the [Docker network][6] feature to run both containers on the same bridge network.
Noting that this link is broken in the staging preview.

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +To attach the wrapper to a Docker image running an application, use this following Dockerfile:
```suggestion
To attach the wrapper to a Docker image running an application, use the following Dockerfile:
```

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +  - Use the [Docker network][6] feature to run both containers on the same bridge network.
Same comment as above re: the missing destination link.

2024-10-31 21:47 UTC, drichards-87 commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +- To ensure the application container is running on the host pid (just as the Datadog agent does), add these options: `--cgroupns host --pid host`.
```suggestion
- To ensure the application container is running on the host pid (just as the Datadog Agent does), add these options: `--cgroupns host --pid host`.
```

2024-11-04 10:41 UTC, spikat commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +DD_REPO_URL=datad0g.com \
This was needed to retrieve the custom build, now we can remove it

2024-11-04 10:41 UTC, spikat commented on content/en/security/cloud_security_management/guide/eBPF-free-agent.md
> +FROM gcr.io/datadoghq/agent:latest
It should be the same, but to stay consistent with the other parts I would replace the `latest` tag by `7`

2024-11-04 18:12 UTC, michaelcretzman reviewed
incorp final tech review

2024-11-04 18:12 UTC, michaelcretzman reviewed
incorp final tech review

2024-11-04 19:59 UTC, michaelcretzman commented
/merge

2024-11-04 19:59 UTC, merged