added new metrics origin mapping table to docs
DataDog/documentation pull request #25153
Opened 2024-09-09 19:01 UTC by ouracheal

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-09-09 22:07 UTC, hestonhoffman commented
Hi! I've added the Do Not Merge label to remove this from our queue. When you're done, remove that label to put the PR back in our queue :)

2024-09-13 13:58 UTC, ouracheal commented
> Hi! I've added the Do Not Merge label to remove this from our queue. When you're done, remove that label to put the PR back in our queue :)

Thanks!

2024-10-09 21:00 UTC, brett0000FF requested changes
Thanks for adding this comment! Please let me know if you have any questions about my suggestions. Most of them are addressing style tweaks that Vale flagged.

2024-10-09 21:00 UTC, brett0000FF commented on content/en/metrics/summary.md
> +| SAAS Integrations       | Timeseries collected from popular SAAS platforms like Slack, Docker, PagerDuty etc.
```suggestion
| SaaS Integrations       | Timeseries collected from popular SaaS platforms like Slack, Docker, PagerDuty, etc.
```

2024-10-09 21:10 UTC, ouracheal reviewed
added changes!

2024-10-09 21:37 UTC, brett0000FF approved these changes
🚀

2024-10-09 21:38 UTC, merged