Additional section for the search span
DataDog/documentation pull request #25165
Opened 2024-09-10 11:39 UTC by mervebolatdd

Adding a new section to explain a feature enhancement to trace view.

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-09-10 13:14 UTC, assma-ben-aicha approved these changes

2024-09-11 21:53 UTC, buraizu requested changes
Thanks for the PR, just requesting some minor edits.

2024-09-11 21:53 UTC, buraizu commented on content/en/tracing/trace_explorer/trace_view.md
> +In the Waterfall and Flamegraph visualizations, the search option allows you to quickly find the spans that meet specific queries. Spans that match the search query are highlighted in the trace view
```suggestion
In the Waterfall and Flamegraph visualizations, the search option allows you to find the spans that meet specific queries. Spans that match the search query are highlighted in the trace view and you can navigate between these matches using the arrows next to the search bar.
```

2024-09-11 21:53 UTC, buraizu commented on content/en/tracing/trace_explorer/trace_view.md
> +Note: When the `Error` checkbox is selected, the search results return spans that match the query and are in an error state.
```suggestion
**Note**: When the `Error` checkbox is selected, the search results return spans that match the query and are in an error state.
```

2024-09-11 21:53 UTC, buraizu commented on content/en/tracing/trace_explorer/trace_view.md
> +The search query on trace side panel supports the following options:
```suggestion
The search query on the trace side panel supports the following options:
```

2024-09-11 21:53 UTC, buraizu commented on content/en/tracing/trace_explorer/trace_view.md
> +Free-form text search allows filtering by service, resource or operation name. It highlights the spans containing the specified text within these categories.
```suggestion
Free-form text search allows filtering by service, resource, or operation name. It highlights the spans containing the specified text within these categories.
```

2024-09-11 21:53 UTC, buraizu commented on content/en/tracing/trace_explorer/trace_view.md
> +Note: Wildcard is not supported for Trace search bar.
```suggestion
**Note**: Wildcards are not supported in the Trace search bar.
```

2024-09-11 21:53 UTC, buraizu commented on content/en/tracing/trace_explorer/trace_view.md
> +Boolean expression: `service: event-query OR terminator`
```suggestion
Boolean expression: `service:event-query OR terminator`
```

2024-09-11 21:53 UTC, buraizu commented on content/en/tracing/trace_explorer/trace_view.md
> +Note: Numberical values suport `<`, `>`, `<=`, and `>=` expressions.
```suggestion
**Note**: Numerical values support `<`, `>`, `<=`, and `>=` expressions.
```

2024-09-12 12:15 UTC, mervebolatdd reviewed
Thanks for the review

2024-09-12 15:27 UTC, buraizu approved these changes
@mervebolatdd Thank you for applying those changes, this looks good to me and is approved. Let me know either here or in the documentation Slack channel when this PR is ready to be merged.

2024-09-13 13:38 UTC, merged