[DBM for MongoDB] Update DBM for MongoDB beta agent version & new data collected
DataDog/documentation pull request #25188
Opened 2024-09-11 00:19 UTC by lu-zhengda

### What does this PR do? What is the motivation?
This PR updates DBM for MongoDB beta agent to `7.58.0-dbm-mongo-1.6`. With the new beta agent version, we also introduce new MongoDB schemas and indexes analysis feature. 

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-09-11 00:28 UTC, buraizu requested changes
Thanks for the PR, I requested a few minor updates per the [documentation style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#first-and-second-person-pronouns)

2024-09-11 00:28 UTC, buraizu commented on layouts/shortcodes/dbm-mongodb-agent-data-collected.md
> +Database Monitoring for MongoDB collects inferred schema and indexes of MongoDB collections. This information is used to provide insights into the structure and organization of your collections.
```suggestion
Database Monitoring for MongoDB collects inferred schemas and indexes of MongoDB collections. This information is used to provide insights into the structure and organization of your collections.
```

2024-09-11 00:28 UTC, buraizu commented on layouts/shortcodes/dbm-mongodb-agent-data-collected.md
> +When analyzing MongoDB collections, we collect inferred schema information by sampling documents using the `$sample` aggregation stage. From this analysis, we only gather and send metadata about the
```suggestion
When analyzing MongoDB collections, Datadog collects inferred schema information by sampling documents using the `$sample` aggregation stage. From this analysis, only metadata about the schema is gathered and sent to Datadog, including field names, field prevalence (how often each field appears), and their respective data types. Datadog does not collect or transmit the actual content of documents or any customer business data. This ensures that sensitive data remains protected while still providing valuable insights into the structure and organization of your collections.
```

2024-09-11 00:28 UTC, buraizu commented on layouts/shortcodes/dbm-mongodb-beta-new-features
> +Using a document sampling approach with the `$sample` aggregation stage, we analyze your collection to identify common fields, their data types, and how often each field appears across the sampled do
```suggestion
Using a document sampling approach with the `$sample` aggregation stage, Datadog analyzes your collection to identify common fields, their data types, and how often each field appears across the sampled documents (field prevalence). In addition to schema details, Database Monitoring for MongoDB also gathers information on the indexes present, giving you a comprehensive view of how data is structured and optimized for querying.
```

2024-09-11 15:35 UTC, buraizu approved these changes
Thanks, LGTM and approved. Let me know here or in the documentation Slack channel when it's ready to be merged.

2024-09-11 17:10 UTC, caseycull approved these changes

2024-09-11 17:10 UTC, caseycull commented on layouts/shortcodes/dbm-mongodb-agent-data-collected.md
> +When analyzing MongoDB collections, Datadog collects inferred schema information by sampling documents using the `$sample` aggregation stage. From this analysis, only metadata about the schema is gat
LGTM, I'll ask Noah to take a look as well but good to merge in the meantime

2024-09-12 18:55 UTC, bgdeutsch approved these changes

2024-09-12 18:56 UTC, merged