Document Profiling+SSI beta k8s support
DataDog/documentation pull request #25237
Opened 2024-09-13 15:35 UTC by szegedi

### What does this PR do? What is the motivation?
Adds documentation for enabling Profiling+SSI support on Kubernetes.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-09-24 20:04 UTC, urseberry requested changes
Thank you for making this update! I have a few wording suggestions.

2024-09-24 20:04 UTC, urseberry commented on content/en/profiler/enabling/ssi.md
> +Operator defaults to an older agent version.
```suggestion
Use the "latest" image tag to install a recent Agent version with support for profiling, as 
the Datadog Operator defaults to an older Agent version.
```

2024-09-24 20:04 UTC, urseberry commented on content/en/profiler/enabling/ssi.md
> +environment variable. Running processes will not be affected. The Datadog library dynamically turns
```suggestion
environment variable. Running processes are not affected. The Datadog library dynamically turns
```

2024-09-24 20:04 UTC, urseberry commented on content/en/profiler/enabling/ssi.md
> +are profiled as Java applications are usually deployed as a single Java process on a host. For Node
```suggestion
The logic for identifying a process as a good candidate varies by language. For Java, all processes
are profiled, as Java applications are usually deployed as a single Java process on a host. For Node
```

2024-09-24 20:04 UTC, urseberry commented on content/en/profiler/enabling/ssi.md
>  Additionally, you can disable profiling by:
```suggestion
Additionally, you can disable profiling by taking one of the following steps:
```

2024-09-24 20:04 UTC, urseberry commented on content/en/profiler/enabling/ssi.md
> +  host and container deployments.
```suggestion
* Repeat the installation instructions using a `false` value in place of `auto`.
* Remove the `DD_PROFILING_ENABLED` setting from the `/etc/environment` file on the host, for host and container deployments.
```

2024-09-25 11:13 UTC, szegedi commented
@urseberry thank you for the thoughtful suggestions – I applied them all.

2024-09-25 20:50 UTC, urseberry approved these changes

2024-09-25 20:51 UTC, urseberry commented
Is this ready to merge, or do you want to wait for yoannrobin to review?

2024-09-26 12:44 UTC, szegedi commented
@urseberry I'll give Yoann some time to review.

2024-09-27 13:31 UTC, szegedi commented
@urseberry I'd like to merge it now – thank you!

2024-09-30 19:25 UTC, merged