SCICM-2609
DataDog/documentation pull request #25304
Opened 2024-09-18 17:35 UTC by OmerRaviv

### What does this PR do? What is the motivation?
Put the the instructions on .pdb files at the top level of .NET instructions (previously they only appear under SourceLink, which is misleading as without .pdbs, we will not have any file path / line number information available, and so Source Code Integration would provide a degraded experience.

### Merge instructions

Please wait for review from @jminuscula before merging.

2024-09-18 21:33 UTC, buraizu requested changes
Thanks for the PR, just requesting to re-add the formatting for the file extensions.

2024-09-19 08:58 UTC, jminuscula approved these changes
thank you @OmerRaviv!

2024-09-26 23:59 UTC, OmerRaviv commented
Thanks @buraizu ! Ready to merge from my standpoint.

2024-09-30 20:44 UTC, buraizu approved these changes

2024-09-30 20:44 UTC, merged