Add Preview page for adaptive sampling
DataDog/documentation pull request #25397
Opened 2024-09-23 18:35 UTC by bm1549

### What does this PR do? What is the motivation?

Adds a new page (and links) that describe our new adaptive sampling feature.

🎉  This officially marks the transition to `Preview` for adaptive sampling

### Merge instructions

Looking for approval from either @yuanyuanzhao3 or @dussault-antoine prior to merge

- [ ] Please merge after reviewing

### Additional notes

2024-09-24 19:27 UTC, lucaspimentel commented on content/en/tracing/guide/adaptive_sampling.md
> +| .NET        | [v.2.54.0][13]           |
I was actually looking for this list today and remember you had pushed a docs PR, so I came to see if it was here. Thanks!

However, some of these values start with `v` and others with`v.`
```suggestion
| Python      | [v2.9.6][10]             |
| Ruby        | [v2.0.0][11]             |
| Node.js     | [v5.16.0][12]            |
| .NET        | [v2.54.0][13]            |
```

2024-09-24 21:31 UTC, lucaspimentel commented on content/en/tracing/trace_pipeline/ingestion_controls.md
> +<div class="alert alert-info"><strong>Adaptive sampling rates are in Preview</strong>. Request access to the feature via this <a href="https://www.datadoghq.com/private-beta/resource-based-sampling-a
```suggestion
<div class="alert alert-info"><strong>Adaptive sampling rates are in Preview</strong>. Request access to the feature via this <a href="https://www.datadoghq.com/private-beta/resource-based-sampling-adaptive-sampling/">link</a> to have Datadog adapt to your traffic to keep you under your configured monthly ingestion target. Follow the instructions in the <a href="/tracing/guide/adaptive_sampling">Adaptive sampling guide</a> to get started.</div>
```

2024-09-24 22:00 UTC, brett0000FF requested changes
Thanks for writing up this content! I left a few suggestions for you to consider. The main blocker for me approving this is the images. Seems like they weren't captured in the Demo org, and some of them include usernames. Let me know once you've reviewed my suggestions and I can take another look!

2024-09-24 22:36 UTC, bm1549 commented on content/en/tracing/guide/adaptive_sampling.md
> +private: true
I was following the existing precedent set for [resource_based_sampling](https://github.com/DataDog/documentation/blob/master/content/en/tracing/guide/resource_based_sampling.md)

@dussault-antoine any reason to keep this private? If not, I can remove these lines

2024-09-24 22:53 UTC, bm1549 commented on content/en/tracing/guide/adaptive_sampling.md
> +   {{< img src="/tracing/guide/adaptive_sampling/ingestion_control_page.png" alt="Ingestion Control Page" style="width:100%;">}}
Removed - we can always add them back in if we decide we need them

That being said, I don't have a demo account so I'll need a bit of help there

2024-09-24 22:54 UTC, bm1549 commented on content/en/tracing/guide/adaptive_sampling.md
> +   {{< img src="/tracing/guide/adaptive_sampling/adaptive_sampling_rate.png" alt="Datadog Adaptive Sampling Rates" style="width:100%;">}}
Removed

2024-09-24 23:46 UTC, brett0000FF approved these changes
🚀

2024-09-25 11:45 UTC, yuanyuanzhao3 commented
This looks good to me. I have a few small changes on the branch. Just a heads up as I need to resolve conflict before I can push.

2024-09-25 14:20 UTC, dussault-antoine approved these changes

2024-09-25 14:20 UTC, dussault-antoine commented
Good to go on my side

2024-09-25 14:58 UTC, merged