Update CSM VM deployment types
DataDog/documentation pull request #25421
Opened 2024-09-25 10:58 UTC by cyrbouchiat

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-09-27 12:54 UTC, cyrbouchiat commented
Yeah, absolutely. Thanks
--

Cyril Bouchiat | Datadog
Product Manager, Security


On Wed, Sep 25, 2024 at 6:14 PM DeForest Richards ***@***.***>
wrote:

> @cyrbouchiat <https://github.com/cyrbouchiat> Given the upcoming changes
> to the product lifecycle, should we change beta to In Preview?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DataDog/documentation/pull/25421#issuecomment-2374530860>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4OEUJNWZ6LGQNY2SOM3RNDZYLOOLAVCNFSM6AAAAABO2IJHKGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNZUGUZTAOBWGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-30 15:59 UTC, drichards-87 requested changes

2024-09-30 15:59 UTC, drichards-87 commented on content/en/security/cloud_security_management/setup/supported_deployment_types.md
> +| Azure Account       |                        | {{< X >}}             |             | agentless beta      | {{< X >}}          |                        |
```suggestion
| Azure Account       |                        | {{< X >}}             |             | Agentless Scanning (beta)      | {{< X >}}          |                        |
```

2024-09-30 16:02 UTC, drichards-87 commented
@cyrbouchiat I made a couple of small changes to the PR.

- Changed "agentless" to "Agentless Scanning"
- Added parentheses around the word "beta"

The product lifecycle changes haven't been released yet, so we can keep beta for now.

Is this ready to be merged now?

2024-09-30 16:23 UTC, drichards-87 approved these changes

2024-09-30 16:24 UTC, merged