Update _index.md to add session replay notice
DataDog/documentation pull request #25420
Opened 2024-09-25 09:52 UTC by c-tshibas

Adding more information on how to find the Session replays after the associated RUM session has expired.

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-09-25 16:10 UTC, rtrieu requested changes
Minor feedback, but otherwise looks good!

2024-09-25 16:10 UTC, rtrieu commented on content/en/real_user_monitoring/session_replay/browser/_index.md
> +**Note:** In order to preserve the [15-month session replays][11] after enabling _Extended Retention_ on individual session replays, add them to [Playlists][10]. This ensures that the session replays
```suggestion
**Note**: In order to preserve any [15-month session replays][11] after enabling _Extended Retention_ on individual session replays, add them to [Playlists][10]. This ensures that the session replays can be found after the associated RUM sessions have expired.
```

2024-09-26 12:01 UTC, cy-moi approved these changes

2025-07-09 17:06 UTC, rtrieu commented on content/en/real_user_monitoring/session_replay/browser/_index.md
>  [7]: https://docs.datadoghq.com/account_management/audit_trail/
```suggestion
[7]: /account_management/audit_trail/
```

2025-07-09 17:06 UTC, rtrieu commented on content/en/real_user_monitoring/session_replay/browser/_index.md
>  [8]: https://docs.datadoghq.com/notebooks/
```suggestion
[8]: /notebooks/
```

2025-07-09 17:06 UTC, rtrieu commented on content/en/real_user_monitoring/session_replay/browser/_index.md
> +[10]: https://docs.datadoghq.com/real_user_monitoring/session_replay/playlists
```suggestion
[10]: /real_user_monitoring/session_replay/playlists
```

2025-07-09 17:06 UTC, rtrieu commented on content/en/real_user_monitoring/session_replay/browser/_index.md
> +[11]: https://docs.datadoghq.com/real_user_monitoring/session_replay/browser/#retention
```suggestion
[11]: /real_user_monitoring/session_replay/browser/#retention
```

2025-07-09 17:07 UTC, rtrieu commented on content/en/real_user_monitoring/session_replay/browser/_index.md
> +**Note**: In order to preserve any [15-month session replays][11] after enabling _Extended Retention_ on individual session replays, add them to [Playlists][10]. This ensures that the session replays
```suggestion
**Note**: To preserve any [15-month session replays][11] after enabling _Extended Retention_ on individual session replays, add them to [Playlists][10]. This ensures that the session replays can be found after the associated RUM sessions have expired.
```

2025-07-09 17:08 UTC, rtrieu approved these changes

2026-08-03 19:34 UTC, jhgilbert commented
This PR was closed after six or more months of inactivity. If this was done in error, feel free to re-open the PR.

2026-08-03 19:34 UTC, closed without merging