[orchestrator] add explorter retention
DataDog/documentation pull request #25445
Opened 2024-09-26 13:56 UTC by fisherevans

2024-09-26 15:55 UTC, drichards-87 requested changes
@fisherevans Left some minor feedback for spelling.

2024-09-26 15:55 UTC, drichards-87 commented on content/en/developers/guide/data-collection-resolution-retention.md
> +| Infrastructure                      | Orchestrator Explorer (Kubrenetes)                                                | Datadog Agent
```suggestion
| Infrastructure                      | Orchestrator Explorer (Kubernetes)                                                | Datadog Agent                                                                                                                         | 15 seconds                                                                                     | 15 seconds            | 15 minutes                                                                                                                     |
```

2024-09-26 15:56 UTC, drichards-87 commented
@fisherevans I'll go ahead and commit the change I suggested (spelling typo). After I do so, can I merge the PR? Or are you waiting for additional reviews?

2024-09-26 20:28 UTC, fisherevans commented
Go for it @drichards-87 - I've got a general 👍 from the team

2024-09-27 15:21 UTC, drichards-87 approved these changes

2024-09-27 15:21 UTC, merged