Remove groupby_simple_monitor parameter
DataDog/documentation pull request #25446
Opened 2024-09-26 14:24 UTC by estherk15

### What does this PR do? What is the motivation?

- Remove the `groupby_simple_monitor` from the curl examples in the docs repo. This is deprecated
- [DOCS-8881](https://datadoghq.atlassian.net/browse/DOCS-8881)

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

2024-09-26 18:33 UTC, drichards-87 requested changes
Looks good. I left one small bit of feedback re: a spelling typo. I'll go ahead and commit that for you, and merge the PR after the build job finishes running.

2024-09-26 18:33 UTC, drichards-87 commented on content/en/monitors/configuration/_index.md
> +Alerts are grouped automatically based on your selection of the aggregation selected for your query (for exanple, `avg by service`). If the query has no grouping, it defaults to `Simple Alert`. If th
```suggestion
Alerts are grouped automatically based on your selection of the aggregation selected for your query (for example, `avg by service`). If the query has no grouping, it defaults to `Simple Alert`. If the query is grouped by any dimension, grouping changes to `Multi Alert`.
```

2024-09-27 20:11 UTC, phillip-dd approved these changes
lgtm thanks

2024-09-30 15:49 UTC, drichards-87 approved these changes
Looks good!

2024-09-30 15:50 UTC, merged