Update rds.md
DataDog/documentation pull request #25443
Opened 2024-09-26 13:34 UTC by J0ns0x

adding interest form for RDS agent setup script (take 2)

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-09-26 13:35 UTC, lu-zhengda approved these changes

2024-09-26 18:53 UTC, drichards-87 requested changes
Left a couple of small suggestions. Also, let me know if this PR is ready to be merged.

2024-09-26 18:53 UTC, drichards-87 commented on content/en/database_monitoring/setup_postgres/rds.md
> +<div class="alert alert-info">Looking for a more streamlined setup where Datadog automatically deploys the agent to monitor your RDS? Click <a href="https://forms.gle/1dyK11ubXdmKuriH7">here</a> to s
```suggestion
<div class="alert alert-info">Interested in a more streamlined setup where Datadog automatically deploys the Agent to monitor your RDS? Click <a href="https://forms.gle/1dyK11ubXdmKuriH7">here</a> to share your interest.</div>
```

2024-09-30 17:04 UTC, drichards-87 commented
Hi @J0ns0x. I just wanted to follow-up on this PR to see if it's still relevant/needs to be merged.

2024-10-04 00:56 UTC, J0ns0x commented
yes! I'm behind on implementing your suggestion in slack. hopefully
tomorrow.. thanks for the tip...

On Mon, Sep 30, 2024 at 1:04 PM DeForest Richards ***@***.***>
wrote:

> Hi @J0ns0x <https://github.com/J0ns0x>. I just wanted to follow-up on
> this PR to see if it's still relevant/needs to be merged.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DataDog/documentation/pull/25443#issuecomment-2383729619>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK3XWGJFCGCGEJGBY2Z4P3TZZGACLAVCNFSM6AAAAABO5BML3GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOBTG4ZDSNRRHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2026-08-03 19:15 UTC, jhgilbert commented
This PR was closed after six or more months of inactivity. If this was done in error, feel free to re-open the PR.

2026-08-03 19:15 UTC, closed without merging