[test visibility] Update "new test" logic for early flake detection
DataDog/documentation pull request #25769
Opened 2024-10-17 09:48 UTC by juan-fernandez

### What does this PR do? What is the motivation?
The "new test" logic has changed in our backend. We need to reflect this in the docs. 

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-10-17 10:30 UTC, juliomalegria-dd approved these changes

2024-10-18 15:05 UTC, aliciascott requested changes
Hi @juan-fernandez just a couple small things on this one and also can you add back the image itself? It's ok to remove that `img` tag in the markdown but just physically leave the image in the repo as it will take a few days to update on the non-English docs and we don't want it to display as a broken image in the meantime, thanks!

2024-10-18 15:05 UTC, aliciascott commented on content/en/tests/early_flake_detection/_index.md
> +Excluded Branches will not have any tests retried by Early Flake Detection. Tests run in these branches are not considered new for the purposes of Early Flake Detection. You can manage the list of ex
```suggestion
Excluded Branches do not have any tests retried by Early Flake Detection. Tests run in these branches are not considered new for the purposes of Early Flake Detection. You can manage the list of excluded branches on the [Test Service Settings page][7], ensuring that the feature is tailored to your specific workflow and branch structure.
```

2024-10-18 15:05 UTC, aliciascott commented on content/en/tests/early_flake_detection/_index.md
> +* This test has already run before.
```suggestion
* This test has ran previously.
```

2024-10-18 15:13 UTC, juan-fernandez commented
> Hi @juan-fernandez just a couple small things on this one and also can you add back the image itself? It's ok to remove that `img` tag in the markdown but just physically leave the image in the repo as it will take a few days to update on the non-English docs and we don't want it to display as a broken image in the meantime, thanks!

that makes sense, thanks. I added it back

2024-10-18 15:41 UTC, aliciascott commented
/merge

2024-10-18 16:18 UTC, merged