[RUM-6774] Update and expand Unity documentation
DataDog/documentation pull request #25868
Opened 2024-10-22 21:51 UTC by fuzzybinary

### What does this PR do? What is the motivation?

Unity is moving forward in public beta, so we want to expand on the current documentation offerings and bring it up to the level of other mobile SDKs

### Merge instructions
- [x] Please merge after reviewing

### Additional notes

2024-10-22 22:26 UTC, jhgilbert commented
Thanks for this update, @fuzzybinary! I've filed a [ticket](https://datadoghq.atlassian.net/browse/DOCS-9322) for the docs team to review it.

2024-10-23 19:16 UTC, rtrieu commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/unity.md
> +If you select `Enable Automatic Scene Tracking`, Datadog will hook into Unity's `SceneManager` to detect scenes loading and unloading, and start RUM Views appropriately. If you are using methods to m
```suggestion
If you select `Enable Automatic Scene Tracking`, Datadog hooks into Unity's `SceneManager` to detect scenes loading and unloading, and start RUM Views appropriately. If you are using methods to move between scenes other than `SceneManager`, or would like to track changes in views that occur without `SceneManager`, you need to track views manually using `DdRum.StartView` and `DdRum.StopView`.
```

2024-10-23 19:23 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/mobile/unity.md
> +code_lang: cs
```suggestion
code_lang: unity
```

Needs to be "unity" so it appears in the tab name.

2024-10-23 19:24 UTC, rtrieu commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/unity.md
> +code_lang: cs
```suggestion
code_lang: unity
```

2024-10-23 19:24 UTC, rtrieu commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/data_collected/unity.md
> +code_lang: cs
```suggestion
code_lang: unity
```

2024-10-25 19:27 UTC, rtrieu requested changes
Suggestions to fix some broken links (that were already present).

2024-10-25 19:27 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/mobile/unity.md
> +[5]: https://github.com/DataDog/datadog-ci/tree/master/src/commands/unity-symbols
```suggestion
[5]: https://github.com/DataDog/datadog-ci/tree/master/src/commands/unity-symbols
[6]: https://app.datadoghq.com/source-code/setup/rum
```

2024-10-25 19:27 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/mobile/unity.md
> +5. For crashes, after the crash happens, restart your application and wait for the Unity SDK to upload the crash report in [**Error Tracking**][8].
```suggestion
5. For crashes, after the crash happens, restart your application and wait for the Unity SDK to upload the crash report in [**Error Tracking**][1].
```

2024-10-25 19:27 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/mobile/unity.md
> +4. For obfuscated error reports that do not result in a crash, you can verify symbolication and deobfuscation in [**Error Tracking**][8].
```suggestion
4. For obfuscated error reports that do not result in a crash, you can verify symbolication and deobfuscation in [**Error Tracking**][1].
```

2024-10-25 19:27 UTC, rtrieu commented on content/en/real_user_monitoring/error_tracking/mobile/unity.md
> +See the [RUM Debug Symbols][10] page to view all uploaded symbols.
```suggestion
See the [RUM Debug Symbols][6] page to view all uploaded symbols.
```

2024-11-14 17:05 UTC, rtrieu approved these changes

2024-11-14 18:24 UTC, rtrieu commented
/merge

2024-11-18 15:06 UTC, davidejones approved these changes

2024-11-18 15:10 UTC, rtrieu commented
/merge

2024-11-18 15:40 UTC, merged