RUM-6885 Add the docs for RumMonitor#addViewLoadingTime API
DataDog/documentation pull request #25914
Opened 2024-10-25 14:06 UTC by mariusc83

### What does this PR do? What is the motivation?

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

2024-10-28 12:02 UTC, fuzzybinary commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md
> +through the `GlobalRumMonitor` instance. This method should be called when your view is fully loaded and ready to be displayed to the user:
We don't have a `GlobalRumMontior`.
```suggestion
on `DdRum`. This method should be called when your view is fully loaded and ready to be displayed to the user:
```

2024-10-28 12:03 UTC, fuzzybinary commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
> +
This would be a good addition for Flutter as well.

2024-10-28 21:37 UTC, hestonhoffman requested changes
Left some suggestions

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android.md
> +through the `GlobalRumMonitor` instance. This method should be called when your view is fully loaded and displayed to the user:
```suggestion
iOS RUM tracks the time it takes for your view to load. To notify the SDK that your view has finished loading, call the `addViewLoadingTime(override=)` method
through the `GlobalRumMonitor` instance. Call this method when your view is fully loaded and displayed to the user:
```

Not sure who "we" is here, so made some guesses.

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android.md
> +Use `override` option to replace previously calculated loading time for current view.
```suggestion
Use the `override` option to replace the previously calculated loading time for the current view.
```

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android.md
> +Once the view loading time is sent, the loading time is accessible as `@view.loading_time` and will be visible also in the RUM UI.
```suggestion

After the loading time is sent, it is accessible as `@view.loading_time` and is visible in the RUM UI.
```

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md
> +We are tracking the time it takes for your view to load. To notify the SDK that your view has finished loading you will need to call the `addViewLoadingTime` method
```suggestion
iOS RUM tracks the time it takes for your view to load. To notify the SDK that your view has finished loading, call the `addViewLoadingTime` method on `DatadogRum`.
```

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md
> +on `DatadogRum`. This method should be called when your view is fully loaded and ready to be displayed to the user:
```suggestion
Call this method when your view is fully loaded and ready to be displayed to the user:
```

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md
> +Use `override` option to replace previously calculated loading time for current view.
```suggestion
Use the `override` option to replace the previously calculated loading time for the current view.
```

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md
> +Please note that this API is still experimental and might change in the future.
```suggestion
After the loading time is sent, it is accessible as `@view.loading_time` and is visible in the RUM UI.

Please note that this API is still experimental and might change in the future.
```

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
> +through the `RUMMonitor` instance. This method should be called when your view is fully loaded and displayed to the user:
```suggestion
iOS RUM tracks the time it takes for your view to load. To notify the SDK that your view has finished loading, call the `addViewLoadingTime(override:)` method
through the `RUMMonitor` instance. Call this method when your view is fully loaded and displayed to the user:
```

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
> +Use `override` option to replace previously calculated loading time for current view.
```suggestion
Use the `override` option to replace the previously calculated loading time for the current view..
```

2024-10-28 21:37 UTC, hestonhoffman commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
> +Please note that this API is still experimental and might change in the future.
```suggestion
After the loading time is sent, it is accessible as `@view.loading_time` and is visible in the RUM UI.
Please note that this API is still experimental and might change in the future.
```

2024-10-29 14:05 UTC, fuzzybinary approved these changes

2024-11-01 16:29 UTC, hestonhoffman approved these changes

2024-11-01 16:30 UTC, hestonhoffman commented
Looks good! When you're ready to merge, post a comment with `/merge` to add this one to our merge queue :shipit:

2024-11-04 09:11 UTC, mariusc83 reviewed
/merge

2024-11-05 07:35 UTC, mariusc83 commented
> Looks good! When you're ready to merge, post a comment with `/merge` to add this one to our merge queue :shipit:

I added a comment there, not sure it worked 🤔 ?

2024-11-06 15:21 UTC, merged