Update to serverless docs with links to new sample apps
DataDog/documentation pull request #25985
Opened 2024-10-29 21:35 UTC by jeastham1993

### What does this PR do? What is the motivation?

The getting started pages for AWS Lambda linked to an old version of the serverless-sample-app repository. The instructions and screenshots no longer matched the application. This PR updates the docs, as well as adding links to the repo for the runtime specific install pages.

### Merge instructions

Should have a review by a member of the serverless engineering team.

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-10-29 23:33 UTC, drichards-87 commented
Created DOCS-9377 for Docs Team editorial review.

2024-11-07 15:48 UTC, aliciascott commented
Thank you! Created [Editorial review](https://datadoghq.atlassian.net/browse/DOCS-9451) card

2024-11-15 19:05 UTC, cswatt requested changes
Thank you so much for this! I've left some smaller grammar nits.

However, instead of replacing images, could you:
- Keep the old images
- Add the new images under a new filename (e.g. `trace_map_2.png`)
- Update the img tags to reference the new filename

My team will clean up the old images after changes have been propagated across translations. Thank you!

2024-11-15 19:05 UTC, cswatt commented on content/en/getting_started/serverless/_index.md
> +If you are viewing a trace with an error the lower half of the detailed trace view will show the details:
```suggestion
If you are viewing a trace with an error, the lower half of the detailed trace view shows the details:
```

2024-12-06 10:06 UTC, jeastham1993 commented
@cswatt sorry for the delay on this, I've just been through and added all your suggestions + update the images. This can be merged whenever you are happy!

2024-12-11 07:05 UTC, jeastham1993 commented
/merge

2024-12-11 07:11 UTC, merged