[test visibility] Update EFD diagram for new tests
DataDog/documentation pull request #25999
Opened 2024-10-30 16:26 UTC by juan-fernandez

### What does this PR do? What is the motivation?
Update EFD diagram to reflect new "new test" logic.

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-10-30 16:45 UTC, drichards-87 requested changes

2024-10-30 16:45 UTC, drichards-87 commented on static/images/continuous_integration/early_flake_detection_commit_new_test_explanation.png
@juan-fernandez For the diagram, we'll need to keep the old file and instead add the new one and reference it with a different filename. This is due to cacheing issue with the docs site. If you replace an image and don't rename it, the site will often just use the old cached image and we then have to go and manually remove the file from cache.

2024-10-30 16:50 UTC, juan-fernandez commented on static/images/continuous_integration/early_flake_detection_commit_new_test_explanation.png
that makes sense. Done in https://github.com/DataDog/documentation/pull/25999/commits/9afe52ec3d496164111a17f52fe9cf93e63d2bbc

2024-10-30 17:19 UTC, drichards-87 approved these changes

2024-10-31 09:45 UTC, juan-fernandez commented
/merge

2024-10-31 10:10 UTC, merged