Update datadog_operator.md: Add `site` to the sample YAML
DataDog/documentation pull request #26112
Opened 2024-11-05 08:02 UTC by scottgerring

Adds `site` to the example YAML for the operator setup

### What does this PR do? What is the motivation?
There is no mention of the `global.site` field in the example YAML. Without going through the linked CRD field spec, users who are not using the default site datadoghq.com will struggle to get the agent running. The error messages received lead down a "bad credentials" rabbit hole which does not make it immediately obvious that the site might be wrong, so I think it is a good idea to point out this needs to be set, here, on the getting started pages. 

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-11-05 18:53 UTC, rtrieu requested changes
Minor feedback for style consistency.

2024-11-05 18:53 UTC, rtrieu commented on content/en/getting_started/containers/datadog_operator.md
> +  **Note**: add an application key for autoscaling using the external metrics server by adding `--from-literal app-key=<DATADOG_APP_KEY>`
```suggestion
  **Note**: Add an application key for autoscaling using the external metrics server by adding `--from-literal app-key=<DATADOG_APP_KEY>`
```

2024-11-05 18:53 UTC, rtrieu commented on content/en/getting_started/containers/datadog_operator.md
> +  **Note**: Make sure to set `site` to the datadog site you are using - for instance, **datadoghq.eu**.
```suggestion
  **Note**: Make sure to set `site` to the Datadog site you are using (for instance, `datadoghq.eu`). 
```

2024-11-06 06:12 UTC, scottgerring commented
> Minor feedback for style consistency.

Cheers @rtrieu! Applied

2024-11-06 14:42 UTC, rtrieu approved these changes

2024-11-06 14:42 UTC, rtrieu commented
/merge

2024-11-06 15:07 UTC, merged