Adding SQLServer schema collection information
DataDog/documentation pull request #26127
Opened 2024-11-05 18:44 UTC by edengorevoy

### What does this PR do? What is the motivation?

We are able to display schema information in the frontend now, so this adds instructions to our SQLServer documentation for collecting schemas.

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-11-05 20:14 UTC, rtrieu requested changes
Minor feedback for style consistency.

2024-11-05 20:14 UTC, rtrieu commented on layouts/shortcodes/dbm-sqlserver-agent-config-examples.en.md
> +To enable this feature, use the `schemas_collection` option. Schemas will be collected on databases for which the Agent has `CONNECT` access.
```suggestion
To enable this feature, use the `schemas_collection` option. Schemas are collected on databases for which the Agent has `CONNECT` access.
```

2024-11-11 15:11 UTC, caseycull commented on layouts/shortcodes/dbm-sqlserver-agent-config-examples.en.md
> +To enable this feature, use the `schemas_collection` option. Schemas are collected on databases for which the Agent has `CONNECT` access.
Can we add min required Agent version here?

2024-11-11 17:44 UTC, rtrieu approved these changes

2024-11-11 18:45 UTC, caseycull approved these changes

2024-11-11 18:54 UTC, edengorevoy commented
/merge

2024-11-11 19:22 UTC, merged