Update azure-private-link.md
DataDog/documentation pull request #26130
Opened 2024-11-05 19:41 UTC by simnyc

Customers were waiting for their connection requests to be accepted, but this requires a manual intervention. Until we have an automated process, let's ask customers to reach out to support so they can escalate to `#support-fabric`.

### What does this PR do? What is the motivation?

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-11-05 19:42 UTC, mitchcail approved these changes

2024-11-05 20:27 UTC, rtrieu requested changes
Minor suggestion, but otherwise looks good

2024-11-05 20:27 UTC, rtrieu commented on content/en/agent/guide/azure-private-link.md
> +### Reach out to support
```suggestion
### Connection request acceptance
```

2024-11-05 20:27 UTC, rtrieu commented on content/en/agent/guide/azure-private-link.md
> +Azure Private Link requires that the Provider accepts new connection requests from a Consumer. Please reach out to support@datadoghq.com with your newly created Endpoint ID and request that we accept
```suggestion
Azure Private Link requires that the Provider accepts new connection requests from a Consumer. Please reach out to support@datadoghq.com with your newly created Endpoint ID and request that we accept the connection.
```

2026-08-03 19:17 UTC, jhgilbert commented
This PR was closed after six or more months of inactivity. If this was done in error, feel free to re-open the PR.

2026-08-03 19:17 UTC, closed without merging