Add partition selection section to aws manual setup docs
DataDog/documentation pull request #26370
Opened 2024-11-19 18:19 UTC by saleelsaptarshi-dd

### What does this PR do? What is the motivation?

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-11-19 20:31 UTC, ktmq commented on content/en/integrations/guide/aws-manual-setup.md
> +18. Return to the AWS integration configuration page for manually adding an account in Datadog that you had open in another tab. Click the checkbox to confirm the Datadog IAM role was added to the AW
```suggestion
18. Return to the AWS integration configuration page for manually adding an account in Datadog that you had open in another tab. Click the checkbox to confirm the Datadog IAM role was added to the AWS account.
```

2024-11-20 00:56 UTC, buraizu commented
Created DOCS-9559 to review

2024-11-25 17:51 UTC, buraizu requested changes
Thanks for the PR, requesting a few minor edits

2024-11-25 17:51 UTC, buraizu commented on content/en/integrations/guide/aws-manual-setup.md
> +4. Select the **JSON** tab. Paste the [permission policies](#aws-integration-iam-policy) in the textbox.
```suggestion
4. Select the **JSON** tab. Paste the [permission policies](#aws-integration-iam-policy) in the textbox.<br>
```

2024-11-25 17:51 UTC, buraizu commented on content/en/integrations/guide/aws-manual-setup.md
> +20. Choose which AWS partition your AWS account is scoped to. The partition is either `aws` for commercial regions, `aws-cn` for China, or `aws-us-gov` for GovCloud. Refer to [AWS documentation][9] f
```suggestion
20. Choose which AWS partition your AWS account is scoped to. The partition is either `aws` for commercial regions, `aws-cn` for China*, or `aws-us-gov` for GovCloud. See [Partitions][9] in the AWS documentation for more information.
```

2024-11-25 17:51 UTC, buraizu commented on content/en/integrations/guide/aws-manual-setup.md
> +23. Wait up to 10 minutes for data to start being collected, and then view the out-of-the-box <a href="https://app.datadoghq.com/screen/integration/7/aws-overview" target="_blank">AWS Overview Dashbo
```suggestion
23. Wait up to 10 minutes for data to start being collected, and then view the out-of-the-box <a href="https://app.datadoghq.com/screen/integration/7/aws-overview" target="_blank">AWS Overview Dashboard</a> to see metrics sent by your AWS services and infrastructure.

*\* All use of Datadog Services in (or in connection with environments within) mainland China is subject to the disclaimer published in the [Restricted Service Locations][62] section on our website.*
```

2024-11-25 17:51 UTC, buraizu commented on content/en/integrations/guide/aws-manual-setup.md
> +4. Select the **JSON** tab. Paste the [permission policies](#aws-integration-iam-policy) in the textbox.
The double spaces at the end of the line here create a line break in markdown, so the note renders indented on the next line. If you want to delete these spaces, they should be replaced with a `<br>` element to achieve the same effect.

2024-11-25 17:51 UTC, buraizu commented on content/en/integrations/guide/aws-manual-setup.md
> +20. Choose which AWS partition your AWS account is scoped to. The partition is either `aws` for commercial regions, `aws-cn` for China, or `aws-us-gov` for GovCloud. Refer to [AWS documentation][9] f
Per the [style guide on link text](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#links)

2024-11-25 17:51 UTC, buraizu commented on content/en/integrations/guide/aws-manual-setup.md
> +23. Wait up to 10 minutes for data to start being collected, and then view the out-of-the-box <a href="https://app.datadoghq.com/screen/integration/7/aws-overview" target="_blank">AWS Overview Dashbo
In addition to adding this disclaimer here, it should be deleted from line `146`

2024-11-25 20:31 UTC, buraizu approved these changes

2024-12-18 17:33 UTC, saleelsaptarshi-dd commented
/merge

2024-12-18 17:39 UTC, merged