adding storage monitoring doc
DataDog/documentation pull request #26377
Opened 2024-11-19 21:25 UTC by rmshree

### What does this PR do? What is the motivation?

Add a new "private" setup guide for the Storage Monitoring product in Preview.

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-11-19 22:18 UTC, buraizu commented
DOCS-9557 has been created for review

2024-11-21 00:46 UTC, buraizu requested changes
Thanks for the PR! In addition to the edits requested:

- Image files are not rendering in their current location. They will need to be moved to `static/images/integrations/guide/storage_monitoring/`. Note that the `storage_monitoring` folder will need to be created first
- For the `cloud-inventory-policies-cfn.yaml` instructions, no information is provided for the **Configure stack options** screen. Is this intentional?

Please let me know if you have any feedback or questions!

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +  1. Go to the AWS S3 Console
```suggestion
  1. Go to the [Amazon S3 buckets page][5] in the AWS console, and select the bucket.
```

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +  2. Navigate to the bucket's Management tab
```suggestion
  2. Navigate to the bucket's **Management** tab.
```

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +  3. Click Create Inventory Configuration
```suggestion
  3. Click **Create inventory configuration**.
```

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +    - In select destination bucket, pick the newly created destination bucket. Example, if bucket is named destination-bucket `s3://your-destination-bucket`
```suggestion
    - **Destination**: select the destination bucket. For example, if the bucket is named `destination-bucket`, enter `s3://your-destination-bucket`.
```

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +    - If you wish to have a prefix on the destination bucket, please define it and let us know
```suggestion
       **Note**: If you want to use a prefix on the destination bucket, add this as well  
```

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +    - Choose frequency: Daily (recommended) or Weekly [Note that this setting determines how often your prefix level metrics will be updated in Datadog]
```suggestion
    - **Frequency**: Datadog recommends choosing **Daily**. This setting determines how often your prefix-level metrics are updated in Datadog  
```

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +    - Format: CSV
```suggestion
    - **Output format**: CSV  
```

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +    - Select required metadata fields:
```suggestion
    - Select the following **Additional metadata fields**:  
```

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +4. Datadog Org ID
```suggestion
After completing the above steps, reach out on the `#storage-monitoring` Slack channel with the following information:

1. Name of the destination bucket where inventories are stored.
2. Prefix to store the inventory files.
3. Region of the destination bucket.
4. AWS account ID containing the bucket.
5. Datadog role name that has the permissions to read objects in destination bucket.
6. Datadog org ID.
```

2024-11-21 00:46 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +- Contact us at mahashree.rajendran@datadoghq.com with your bucket details, AWS account ID and Datadog Org ID
Please correct me if I'm wrong, but I think Datadog org ID isn't something that's readily available -- as far as I know, a user has to send a request to [this API endpoint](https://docs.datadoghq.com/api/latest/users/#get-user-details) and get the org ID from the returned data. Unless you're aware of another way for users to find their org ID, this is something we should probably provide guidance for

2024-11-21 21:47 UTC, rmshree commented on content/en/integrations/guide/storage-monitoring-setup.md
> +1. Download the source-bucket-inventory-cfn.yaml template
Added the link in a new commit

2024-11-21 21:47 UTC, rmshree commented on content/en/integrations/guide/storage-monitoring-setup.md
> +{{< img src="integrations/guide/acknowledge_bucket_policy.png" alt="Verify and launch stack" responsive="true" style="width:60%;" >}}
The screenshot was partial view of the screen. I actually removed the screenshot because the bullet explains it pretty well.

2024-11-21 21:47 UTC, rmshree commented on content/en/integrations/guide/storage-monitoring-setup.md
> +After completing the CloudFormation setup, reach out with the following information:
We're working on creating an email handle but putting in my email in here until that's ready!

2024-11-22 01:22 UTC, buraizu requested changes
This review:
- Fixes image addresses
- Moves links within tabs (each tab needs to contain its own set of links, apologies for my mistaken suggestions in the first review)
- Updates image widths to `90%`, because currently the text on them is too small to read without expanding the image
- Moves your email address out of the page and into the list of reference links, since our guidance on [PII in public content](https://datadoghq.atlassian.net/wiki/spaces/ISEC/pages/3013411411/Guidance+for+PII+in+Public+Blogs+and+Documentation) requests that these not be added to the docs. With that said, could users just as well reach out on #storage-monitoring instead, as mentioned on line `127`? If so, that would likely be the ideal approach.

Also, I'm guessing that it's intentional to **not** add a link to this page to the [integration guides page](https://docs.datadoghq.com/integrations/guide/), but let me know if that's incorrect

2024-11-22 01:22 UTC, buraizu commented on content/en/integrations/guide/storage-monitoring-setup.md
> +   - Navigate to **Infrastructure -> Resource Catalog -> Monitoring -> S3 Buckets -> Installation Recommendations** to see if the bucket you configured is showing in the list
```suggestion
       - Navigate to **Infrastructure -> Resource Catalog -> Monitoring -> S3 Buckets -> Installation Recommendations** to see if the bucket you configured is showing in the list
```

2024-11-22 16:54 UTC, rmshree commented
Thank you Bryce! Yes it's intentional that we've not added to the [integration guides page](https://docs.datadoghq.com/integrations/guide/) because we will be sharing this as a "private" link to interested customers and this page shouldn't be visible in search or lists.
I've also removed my personal email and replaced it with a common mailing list. I've also removed the slack handle.

2024-11-22 20:00 UTC, urseberry commented on content/en/integrations/guide/storage-monitoring-setup.md
> +   - **DestinationBucketName**: The name of the bucket that to receive your inventory files. **Note**: You must only use one destination bucket for all inventory files generated in an AWS account.
```suggestion
   - **DestinationBucketName**: The name of the bucket that receives your inventory files. **Note**: You must only use one destination bucket for all inventory files generated in an AWS account.
```

2024-11-22 20:00 UTC, urseberry commented on content/en/integrations/guide/storage-monitoring-setup.md
> +    6. Datadog org ID.
In the preview, this list isn't getting formatted correctly. Let's try removing the indentation and see if that fixes it.
```suggestion
1. Name of the destination bucket holding the inventory files.
2. Prefix where the files are stored in the destination bucket.
3. Name of the source bucket you want to monitor (the bucket producing inventory files).
4. AWS region of the destination bucket holding the inventory files.
5. AWS account ID containing the buckets.
6. Datadog org ID.
```

2024-11-22 20:00 UTC, urseberry commented on content/en/integrations/guide/storage-monitoring-setup.md
> +To manually set up the required [Amazon S3 Inventory][2] and related configuration, follow these steps:
The link to Amazon S3 Inventory is broken in the preview.

2024-11-22 20:00 UTC, urseberry commented on content/en/integrations/guide/storage-monitoring-setup.md
> +  4. Configure the following settings:
This formatting is broken in the preview. To make a nested list, each level of nesting needs to be indented by 4 spaces. Here it looks like you may have indented it only 2 sapces.

2024-11-22 20:00 UTC, urseberry commented on content/en/integrations/guide/storage-monitoring-setup.md
> +**Note**: Review [AWS S3 pricing][204] for costs related to inventory generation.
```suggestion
**Note**: Review [Amazon S3 pricing][204] for costs related to inventory generation.
```

2024-11-22 23:21 UTC, urseberry approved these changes

2024-11-22 23:22 UTC, urseberry commented
/merge

2024-11-22 23:31 UTC, merged