(TO) Repository-centric docs
DataDog/documentation pull request #26402
Opened 2024-11-20 22:49 UTC by hestonhoffman

### What does this PR do? What is the motivation?

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-12-11 21:11 UTC, KickingTheTV commented on content/en/tests/repositories.md
> +If you have a suite of test services that require their own configuration, you can override your default repository settings.
```suggestion
If you have test services that require their own configuration, you can override your default repository settings.
```

2024-12-11 21:13 UTC, KickingTheTV commented on content/en/tests/branches.md
> +The [Branches][1] view of the Tests page lists all branches from all {{< tooltip glossary="test service" >}}s that have reported test results. This tab is useful for seeing the status of tests run on
```suggestion
The [Branches][1] view of the Repositories page lists all branches from all repositories and {{< tooltip glossary="test service" >}}s that have reported test results. This tab is useful for seeing the status of tests run on your code branches and troubleshooting test failures.
```

2024-12-11 21:14 UTC, KickingTheTV commented on content/en/tests/branches.md
> +For each branch, you can see the test service, the number of failed, passed, and skipped tests, test regressions, total test time, when the commit was last updated, and the avatar of the author of th
```suggestion
For each branch, you can see the repository, test service, the number of failed, passed, and skipped tests, test regressions, total test time, when the commit was last updated, and the avatar of the author of the commit.
```

2024-12-11 21:15 UTC, KickingTheTV commented on content/en/tests/branches.md
> +For each branch, you can see the test service, the number of failed, passed, and skipped tests, test regressions, total test time, when the commit was last updated, and the avatar of the author of th
```suggestion
For each branch, you can see the repository, test service, the number of failed, passed, and skipped tests, new flaky tests, test regressions, total test time, when the commit was last updated, and the avatar of the author of the commit.
```

2024-12-11 21:17 UTC, KickingTheTV commented on content/en/tests/branches.md
> +Click on a branch to explore the test details page, which includes information about the branch's latest commits, flaky tests, test performance, common error types, and all test runs.
```suggestion
Click on a branch to explore the commit details page, which includes information about the failed tests, new flaky tests, test regressions, test performance, related pipeline executions, and all test runs against that commit.
```

2024-12-11 21:22 UTC, KickingTheTV commented on content/en/tests/branches.md
> +For each branch, you can see the test service, the number of failed, passed, and skipped tests, test regressions, total test time, when the commit was last updated, and the avatar of the author of th
```suggestion
For each branch, you can see the repositories test service(s), the number of failed, passed, and skipped tests, test regressions, total test time, when the commit was last updated, and the avatar of the author of the commit.
```

2024-12-11 21:24 UTC, KickingTheTV commented on content/en/glossary/terms/test_service.md
> +In Datadog Synthetic Monitoring and Test Optimization, a test service is generally a group of tests associated with, for example, a project or repo. It contains all the individual tests for your code
```suggestion
In Datadog Test Optimization, a test service is generally a group of tests associated with, for example, a project or repo. It contains all the individual tests for your code, optionally organized into test suites, which are like folders for your tests. For more information on Test Optimization, <a href="/tests/">see the documentation</a>.
```

Test Services don't apply to Synthetics

2024-12-11 21:26 UTC, KickingTheTV commented on content/en/tests/flaky_test_management/auto_test_retries.md
> +If you suspect there are any issues with Auto Test Retries, navigate to the [Test Optimization Settings page][4], look for your test service, and click **Configure**. Disable Auto Test Retries by cli
```suggestion
If you suspect there are any issues with Auto Test Retries, navigate to the [Test Optimization Settings page][4], look for your repository, and click **Configure**. Disable Auto Test Retries by clicking on the toggle.
```

2024-12-11 21:27 UTC, KickingTheTV commented on content/en/tests/flaky_test_management/early_flake_detection.md
> +If you suspect there are issues with Early Flake Detection, navigate to the [Test Optimization Settings page][7], look for your test service, and click **Configure**. Disable Early Flake Detection by
```suggestion
If you suspect there are issues with Early Flake Detection, navigate to the [Test Optimization Settings page][7], look for your repository, and click **Configure**. Disable Early Flake Detection by clicking on the toggle.
```

2024-12-11 21:29 UTC, KickingTheTV requested changes
Have a few suggestions, but overall LGTM

2024-12-17 16:09 UTC, hestonhoffman commented on content/en/tests/repositories.md
> +<!-- vale Datadog.pronouns = NO -->
It turns off a linter that would fire on the word "My"

2024-12-17 17:16 UTC, hestonhoffman commented on content/en/tests/developer_workflows.md
> +1. Navigate to the [Test Optimization Settings page][3] and search for the repository you want to enable. You can also search by repository.
```suggestion
1. Navigate to the [Test Optimization Settings page][3].
```

2024-12-17 17:17 UTC, hestonhoffman commented on content/en/tests/developer_workflows.md
> +1. Select the repository.
```suggestion
1. Select the repository where you want to enable test summaries.
```

2024-12-18 19:14 UTC, KickingTheTV approved these changes
LGTM

2024-12-18 21:00 UTC, rtrieu commented on content/en/tests/repositories.md
> +- See the test status for the most recent commit in each repository.
```suggestion
- See the test status for the most recent commit in each repo.
```

2024-12-18 21:02 UTC, rtrieu approved these changes
One suggestion for consistency, but otherwise, great update. Thanks for this PR!

2024-12-18 23:08 UTC, hestonhoffman commented
/merge

2024-12-18 23:14 UTC, merged