Add Data Access Control
DataDog/documentation pull request #26492
Opened 2024-11-26 01:32 UTC by urseberry

### What does this PR do? What is the motivation?

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-11-26 18:30 UTC, aliciascott requested changes
Hi @urseberry this looks good! I have some suggestions mostly for wording and flow and trying to be consistent with capitalizing or not capitalizing Restricted Dataset. Also I think the Supported and not supported examples could benefit from a little bit of re-formatting, but feel free to keep it as is!

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +Each restricted dataset can control access to multiple types of data, such as metrics. You are free to use the same or different tags across multiple types of telemetry. Within each telemetry type, y
```suggestion
Each Restricted Dataset can control access to multiple types of data, such as metrics. You are free to use the same or different tags across multiple types of telemetry. Within each telemetry type, you must use a _single_ tag or attribute to define your access strategy.
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +
```suggestion
# Supported examples and restrictions for Restricted Datasets
```
I think the flow and formatting can be improved here but feel free to take or reject the suggestion

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +**Supported example**
```suggestion
## Supported example
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +Restricted dataset 1:
```suggestion
### Restricted dataset 1
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +* Telemetry type: RUM
```suggestion
- **Telemetry Type**: RUM  
   - **Filters**: `@application.id:ABCD`
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +    * Filters: `@application.id:ABCD`
```suggestion
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +Restricted dataset 2:
```suggestion
### Restricted dataset 2
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +**Not supported**
```suggestion
## Not supported examples
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +While this example uses the right `@application.id` tag for RUM as was done for restricted dataset 1, the limit is 1 tag per telemetry type. Instead, consider either creating a restricted dataset wit
```suggestion
This example correctly uses the `@application.id` tag for RUM, as was done for restricted dataset 1. However, the limit is one tag per telemetry type. Instead, consider creating a restricted dataset with _either_ `application.id` or `env`, or identify a different tag that better combines these attributes.
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +Restricted dataset 1:
```suggestion
### Restricted dataset 1: 
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +Restricted dataset 2:
```suggestion
### Restricted dataset 2:
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +**Not supported**
```suggestion
## Not supported examples
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +Restricted dataset 1:
```suggestion
### Restricted dataset 1: 
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +Restricted Dataset 2:
```suggestion
### Restricted Dataset 2: 
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +Users in a Datadog organization with Data Access Control enabled can only see query results for data to which they have access, such as in a Dashboard, in an Explorer, or through the API. A restricte
```suggestion
Users in a Datadog organization with Data Access Control enabled can only see query results for data to which they have access, such as in a Dashboard, in an Explorer, or through the API. A restricted dataset removes access to the data defined in the restricted dataset for users who are not permitted, across all Datadog experiences and entry points.
```

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +When exploring Datadog with restrictions enabled, users without permissions are still able to cycle through the list of asset names (for example: applications or metrics), but they do not see query r
```suggestion
When exploring Datadog with restrictions enabled, users without permissions can still browse the list of asset names (applications or metrics), but they cannot see query results, top tags, or facet details restricted by datasets. For instance, querying a metric with restricted data returns a blank graph, making it appear as if the query does not match any data.
```

Trying to remove the redundancy here with the word restricted in the same sentence :)

2024-11-26 18:30 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +When querying data through Datadog APIs with restrictions enabled, users without permissions do not see query results that have been restricted by Restricted Datasets.
```suggestion
When querying data through Datadog APIs with restrictions enabled, users without permissions do **not** see query results that have been restricted by Restricted Datasets.
```

2024-11-26 23:32 UTC, urseberry commented
I'm doing the changes in batches to make them easier to reason about. Will come back later to address the rest of the feedback.

2024-11-27 06:57 UTC, urseberry commented
Alicia, this is ready for your re-review. Some things to note:
- I accepted all your wording suggestions.
- I decided to make Restricted Dataset capitalized throughout. Thanks for pointing out the inconsistency!
- The in-app link to Data Access Control requires the `org_management` permission, which I don't have in any org, so I can't test it. I assume the PM gave me the right link. Do you have `org_management` anywhere?
- I adjusted your formatting for the examples a bit. I also removed the bolding from the field names, because I thought it made them hard to read. See attached screenshot. Thanks for the suggestion, though. I think the new version is clearer than what I originally had.
<img width="1041" alt="Screenshot 2024-11-27 at 12 45 25 AM" src="https://github.com/user-attachments/assets/1f722198-a2a1-4a10-9a62-93c015a835ea">

2024-11-27 16:19 UTC, aliciascott commented on content/en/account_management/rbac/data_access.md
> +1. On the left side of the page, select [Data Access Controls][7].
Ah good point, I do not have that permission either

2024-11-27 16:30 UTC, aliciascott approved these changes
Looks good! Thanks for fixing those things, much easier to read and good flow :)

2024-11-27 17:15 UTC, urseberry commented
/merge

2024-11-27 17:21 UTC, merged