adding coterm
DataDog/documentation pull request #26528
Opened 2024-11-27 18:06 UTC by cswatt

### What does this PR do? What is the motivation?

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-12-17 20:52 UTC, rgwood-dd requested changes
Thank you for putting this together! I've added some comments/questions.

I'm not sure what you used to create these docs, but we've been working on internal docs here:
https://datadoghq.atlassian.net/wiki/spaces/coscreen/pages/4127753035/CoTerm+terminal+recording+approval
https://datadoghq.atlassian.net/wiki/spaces/coscreen/pages/4129226790/CoTerm+Lua+Rule+Reference

I think these docs are missing 2 important sections:
1. Approvals
2. Documentation for the Lua rules

I'm not sure those _need_ to be documented publicly now. Just thought I'd mention them in case you weren't aware of the features.

2024-12-17 20:52 UTC, rgwood-dd commented on content/en/coterm/_index.md
> +   Replace `<DATADOG_API_KEY>` with your API key.
```suggestion
2. Initialize and authenticate CoTerm:

   ```shell
   ddcoterm init
   ```
```

These days it's easiest to use `ddcoterm init` to set up/authenticate CoTerm.

2024-12-17 20:52 UTC, rgwood-dd commented on content/en/coterm/_index.md
> +```
```suggestion
To record the output of an individual command, use `ddcoterm -- <COMMAND>`.

For example, to record the output of `kubectl`, use:

```shell
ddcoterm -- kubectl
```
```

2024-12-17 20:52 UTC, rgwood-dd commented on content/en/coterm/_index.md
> +Datadog recommends that you add CoTerm to your scripts and containers so that you can record your terminal sessions without manually launching CoTerm. You can use aliases to automatically record cert
Typically we'd recommend using "shims", i.e. `ddcoterm shim create kubectl`. More details here: https://datadoghq.atlassian.net/wiki/spaces/coscreen/pages/4127753035/CoTerm+terminal+recording+approval#Shimming-%2F-Wrapping-Commands

2024-12-17 20:52 UTC, rgwood-dd commented on content/en/coterm/_index.md
> +- The maximum duration of a recorded session is approximately 55 minutes.
It depends a lot on how frequently the text in the terminal is changing, but these days we should be able to do at least 24h (knock on wood)

2024-12-17 20:52 UTC, rgwood-dd commented on content/en/coterm/_index.md
> +- On macOS, [Apple SIP][6] prevents the observation of some commands under `/bin`, `/sbin`, etc.
I don't recall this being an issue (but my memory's bad). Do you recall where this info came from?

2025-01-06 22:38 UTC, cswatt commented on content/en/coterm/_index.md
> +- On macOS, [Apple SIP][6] prevents the observation of some commands under `/bin`, `/sbin`, etc.
I don't remember either—most likely this information is just outdated. removing

2025-01-07 23:10 UTC, rgwood-dd approved these changes
LGTM; I think you forgot to remove the SIP information but that's my only quibble. Thank you!

2025-02-11 22:22 UTC, cswatt commented
Ready to merge once docs has reviewed.

2025-02-18 15:18 UTC, maycmlee approved these changes
LGTM! The preview font looks a little strange, but I think it might be because master hasn't been merged in recently.

2025-02-18 22:42 UTC, cswatt commented
/merge

2025-02-18 22:57 UTC, merged