Update mapping file upload limits
DataDog/documentation pull request #26619
Opened 2024-12-05 13:14 UTC by plousada

### What does this PR do? What is the motivation?

This PR adds and updates the symbol mapping file limits to the currently support values.. 

### Merge instructions

Merge readiness:
- [x] Ready for merge

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-12-23 14:35 UTC, MaelNamNam requested changes
Thanks for doing this 🙇
I did a pass and suggested a few changes for the sake of phrasing consistency.

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/error_tracking/frontend/browser.md
> +Source maps are limited to **500 MB** each.
```suggestion
Source maps are limited in size to **500 MB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/error_tracking/mobile/expo.md
> +Source maps and mapping files are limited in size up to **500 MB** each, while dSYM files are limited up to **2 GB**.
```suggestion
Source maps and mapping files are limited in size to **500 MB** each, while dSYM files can go up to **2 GB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/error_tracking/mobile/flutter.md
> +Mapping files are limited in size up to **500 MB** each, while dSYM files are limited up to **2 GB**.
```suggestion
Mapping files are limited in size to **500 MB** each, while dSYM files can go up to **2 GB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/error_tracking/mobile/ios.md
> +dSYM files are limited in size up to **2 GB**.
```suggestion
dSYM files are limited in size to **2 GB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/error_tracking/mobile/kotlin-multiplatform.md
> +Mapping files are limited in size up to **500 MB** each, while dSYM files are limited up to **2 GB**.
```suggestion
Mapping files are limited in size to **500 MB** each, while dSYM files can go up to **2 GB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/error_tracking/mobile/reactnative.md
> +Source maps and mapping files are limited in size up to **500 MB** each, while dSYM files are limited up to **2 GB**.
```suggestion
Source maps and mapping files are limited in size to **500 MB** each, while dSYM files can go up to **2 GB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/guide/debug-symbols.md
> +For iOS dSYMs, up to **2 GB** are supported.
```suggestion
For iOS dSYMs, individual files up to **2 GB** are supported. 
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/guide/upload-javascript-source-maps.md
> +Ensure that the size of each source map augmented with the size of the related minified file does not exceed the limit of 500 MB.
```suggestion
Ensure that the size of each source map augmented with the size of the related minified file does not exceed the limit of **500 MB**.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/android/error_tracking.md
> +Mapping files are limited up to **500 MB**. If your project has a mapping file larger than this, use one of the following options to reduce the file size:
```suggestion
Mapping files are limited in size to **500 MB** each. If your project has a mapping file larger than this, use one of the following options to reduce the file size:
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/error_tracking.md
> +Mapping files are limited in size up to **500 MB** each, while dSYM files are limited up to **2 GB**.
```suggestion
Mapping files are limited in size to **500 MB** each, while dSYM files can go up to **2 GB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/error_tracking.md
> +dSYM files are limited to **2 GB**.
```suggestion
dSYM files are limited in size to **2 GB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/react_native/error_tracking.md
> +Source maps and mapping files are limited in size up to **500 MB** each, while dSYM files are limited up to **2 GB**.
```suggestion
Source maps and mapping files are limited in size to **500 MB** each, while dSYM files can go up to **2 GB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/en/real_user_monitoring/mobile_and_tv_monitoring/unity/error_tracking.md
> +Mapping files are limited in size up to 500 MB each, while dSYM files are limited up to 2GB.
```suggestion
Mapping files are limited in size to **500 MB** each, while dSYM files can go up to **2 GB** each.
```

2024-12-23 14:35 UTC, MaelNamNam commented on content/es/synthetics/guide/testing-file-upload-and-download.md
> +1. **Graba el paso que genera la descarga del archivo** en tu test de navegador. El siguiente ejemplo muestra cómo grabar un clic en un botón que activa la descarga de un archivo `.docx`. El tamaño d
```suggestion
1. **Graba el paso que genera la descarga del archivo** en tu test de navegador. El siguiente ejemplo muestra cómo grabar un clic en un botón que activa la descarga de un archivo `.docx`. El tamaño del archivo debe ser inferior a **500 MB**.
```

2024-12-23 15:35 UTC, rtrieu requested changes
Hi @plousada, I left just one feedback. I think Mael's suggestions make sense to add as well. Thanks for making the changes in Spanish and Japanese, but I would suggest removing the updates from the PR, as they will get overwritten by the Translation build. Our external translation service will handle the translations for other languages!

2024-12-23 15:35 UTC, rtrieu commented on content/en/real_user_monitoring/guide/debug-symbols.md
> +Ensure that the size of each debug symbol does not exceed the limit of **500 MB**, otherwise its upload will be rejected.
```suggestion
Ensure that the size of each debug symbol does not exceed the limit of **500 MB**, otherwise the upload is rejected.
```

2025-01-06 16:18 UTC, rtrieu approved these changes

2025-01-06 16:19 UTC, rtrieu commented
/merge

2025-01-13 16:07 UTC, MaelNamNam approved these changes
LGTM, thanks

2025-01-13 16:10 UTC, BenoitZugmeyer approved these changes

2025-01-13 18:10 UTC, merged