[SDTEST-171] add Ruby to the list of supported languages of Datadog Jenkins plugin
DataDog/documentation pull request #26716
Opened 2024-12-11 11:17 UTC by anmarchenko

### What does this PR do? What is the motivation?
Adds Ruby to the list of supported languages for Jenkins Plugin. Updates Jenkins Plugin settings screenshot.

### Merge instructions

Merge readiness:
- [x] Ready for merge

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

2024-12-11 19:01 UTC, janine-c requested changes

2024-12-11 19:01 UTC, janine-c commented on static/images/ci/ci-jenkins-plugin-tests-config.png
Hi @anmarchenko 👋🏻 For image updates, we sometimes run into caching issues when you update images with the same filename. Could you add the new image as `ci-jenkins-plugin-tests-config-2.png`, and update the reference to that image with the new filename? (We have a script that will then delete the old version of the image for you.) Thank you!

2024-12-12 07:48 UTC, anmarchenko commented on static/images/ci/ci-jenkins-plugin-tests-config.png
yes, will do that!

2024-12-12 08:05 UTC, anmarchenko commented on static/images/ci/ci-jenkins-plugin-tests-config.png
@janine-c done

2024-12-12 08:11 UTC, romainkomorndatadog approved these changes
LGTM

2024-12-12 08:16 UTC, drodriguezhdez approved these changes

2024-12-12 18:08 UTC, janine-c approved these changes

2024-12-13 07:39 UTC, anmarchenko commented
/merge

2024-12-13 07:45 UTC, merged