update screenshot and 1line for llm obs config doc
DataDog/documentation pull request #26773
Opened 2024-12-13 20:44 UTC by barieom

### What does this PR do? What is the motivation?

### Merge instructions

Merge readiness:
- [ ] Ready for merge

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-12-13 22:09 UTC, aliciascott requested changes
Hi @barieom just one small spacing thing and then can you also keep the original image as it takes some time for the translated pages to update and it could show a broken image there. You'd just want to rename the new one like openai-tile_2.png and update that in the `img src`.

2024-12-13 22:09 UTC, aliciascott commented on content/en/llm_observability/configuration/_index.md
> +1. Enable **Use this API key to evaluate your  LLM applications**.
```suggestion
1. Enable **Use this API key to evaluate your LLM applications**.
```

2024-12-17 23:15 UTC, barieom commented
> Hi @barieom just one small spacing thing and then can you also keep the original image as it takes some time for the translated pages to update and it could show a broken image there. You'd just want to rename the new one like openai-tile_2.png and update that in the `img src`.

Thanks @aliciascott - addressed your comments

2024-12-17 23:17 UTC, aliciascott approved these changes
looks good thank you!

2024-12-17 23:18 UTC, aliciascott commented
/merge

2024-12-17 23:24 UTC, merged