docs: Add GrowthBook Feature Flag integration
DataDog/documentation pull request #26779
Opened 2024-12-14 00:51 UTC by ahdriel

### What does this PR do?

Adds a new section on how to integrate DataDog Feature Flag with [Growthbook](https://www.growthbook.io/), an [open-source a/b testing and feature flagging platform](https://github.com/growthbook/growthbook).

### Merge instructions

Merge readiness:
- [x] Ready for merge

2024-12-16 18:30 UTC, drichards-87 commented
@ahdriel Thanks for submitting this PR. I've created a Jira card to track the review of your PR. Someone on the Docs Team will take a look at it shortly.

2024-12-19 21:06 UTC, rtrieu commented on content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> +Currently GrowthBook does not support this integration. Reach out to GrowthBook to request this feature.
```suggestion
GrowthBook does not support this integration. Reach out to GrowthBook to request this feature.
```

2024-12-19 21:09 UTC, rtrieu requested changes
Hi @ahdriel, thank you for this PR! I have left one minor suggestion, but otherwise looks good. FYI, I've submitted a request for our design team to make a version of the logo card that is center aligned on our feature flags landing page. Once you review my feedback and I've gotten the updated logo, I'll merge this PR. Thanks!

2025-01-07 17:34 UTC, ahdriel commented
@rtrieu Thank you for the review! I have just updated the PR with the requested change. Let me know if there's anything else I can assist with.

2025-01-07 18:29 UTC, closed without merging

2025-01-07 18:29 UTC, rtrieu commented
Hi @ahdriel Thank you so much for your PR! I was having issues pulling it locally, so I'm closing this in favor of this one: https://github.com/DataDog/documentation/pull/26999. So you are aware, I changed the wording for the iOS tab slightly to be consistent with the language we have for the other products.