Ruby DI documentation page
DataDog/documentation pull request #26829
Opened 2024-12-18 14:06 UTC by p-datadog

### What does this PR do? What is the motivation?

Adds Ruby to the dynamic instrumentation languages.

### Merge instructions

Merge readiness:
- [ ] Ready for merge

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-12-18 20:01 UTC, janine-c commented
Hey @p-datadog 👋🏻 To check and merge your branch into the documentation repo, the branch name has to follow our [branch naming convention](https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/2231206099/Docs+Build#Branch-naming-convention). Could you please close this PR and reopen it with a branch name that has your Slack username in it, followed by a slash? Sorry for the confusion!

2024-12-18 20:48 UTC, rtrieu commented
Created DOCS-9777 for docs review.

2024-12-18 20:48 UTC, rtrieu commented
Created DOCS-9777 for docs review.

2024-12-30 18:02 UTC, brett0000FF requested changes
@p-datadog Thanks for adding this content! It looks good--just had a few small suggestions.

Requesting changes because we need to rename the branch in order to merge this. Could you please re-open with your branch in `<username>/<branch-name>` format? Otherwise, our build preview won't run, and this blocks our merge queue. Thanks!

2024-12-30 18:02 UTC, brett0000FF commented on content/en/dynamic_instrumentation/enabling/ruby.md
> +| `DD_ENV`                                         | String        | The [environment][4] name, for example: `production`.                                                                     |
```suggestion
| `DD_ENV`                                         | String        | The [environment][4] name, for example, `production`.                                                                     |
```

2024-12-30 18:02 UTC, brett0000FF commented on content/en/dynamic_instrumentation/enabling/ruby.md
> +## Further Reading
```suggestion
## Further reading
```

2024-12-30 19:24 UTC, p-datadog commented
Now in https://github.com/DataDog/documentation/pull/26924

2024-12-30 19:24 UTC, closed without merging