feat(admission): add instruction to remove Datadog Admission Controllers
DataDog/documentation pull request #26904
Opened 2024-12-26 15:40 UTC by wdhif

### What does this PR do? What is the motivation?

Adds a Container Guide on how to properly disable the Cluster Agent Admission Controllers.

### Merge instructions

Merge readiness:
- [ ] Ready for merge

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-12-26 19:33 UTC, aliciascott requested changes
Hi @wdhif this looks good! Just a few minor things, let me know when this is ready for re-review.

2024-12-26 19:33 UTC, aliciascott commented on content/en/containers/guide/cluster_agent_disable_admission_controller.md
> +1. DataDog Cluster Agent v7.63+
```suggestion
Datadog Cluster Agent v7.63+
```
Since there is only one requirement we don't need a numbered list here.

2024-12-26 19:33 UTC, aliciascott commented on content/en/containers/guide/cluster_agent_disable_admission_controller.md
> +## Requirements
```suggestion
## Prerequisites
```
usually title these as Prerequisites

2024-12-26 19:33 UTC, aliciascott commented on content/en/containers/guide/cluster_agent_disable_admission_controller.md
> +* Set `features.admissionController.enabled` to `true` in your `DatadogAgent` configuration.
```suggestion
1. Set `features.admissionController.enabled` to `true` in your `DatadogAgent` configuration.
```

2024-12-26 19:33 UTC, aliciascott commented on content/en/containers/guide/cluster_agent_disable_admission_controller.md
> +* Set `features.admissionController.validation.enabled` to `false` in your `DatadogAgent` configuration.
```suggestion
2. Set `features.admissionController.validation.enabled` to `false` in your `DatadogAgent` configuration.
```

2024-12-26 19:33 UTC, aliciascott commented on content/en/containers/guide/cluster_agent_disable_admission_controller.md
> +* Set `features.admissionController.mutation.enabled` to `false` in your `DatadogAgent` configuration.
```suggestion
3. Set `features.admissionController.mutation.enabled` to `false` in your `DatadogAgent` configuration.
```
Here if all 3 steps are required we should make it a numbered list

2024-12-26 19:33 UTC, aliciascott commented on content/en/containers/guide/cluster_agent_disable_admission_controller.md
> +Note that the `features.admissionController.enabled` parameter is set to `true` to allow the Cluster Agent to manage the Kubernetes Admission Controllers.
```suggestion
**Note**: The the `features.admissionController.enabled` parameter is set to `true` to allow the Cluster Agent to manage the Kubernetes Admission Controllers.
```

2024-12-26 19:33 UTC, aliciascott commented on content/en/containers/guide/cluster_agent_disable_admission_controller.md
> +* Set `clusterAgent.admissionController.enabled` to `true`.
```suggestion
1. Set `clusterAgent.admissionController.enabled` to `true`.
```

2024-12-26 19:33 UTC, aliciascott commented on content/en/containers/guide/cluster_agent_disable_admission_controller.md
> +* Set `clusterAgent.admissionController.validation.enabled` to `false`.
```suggestion
2. Set `clusterAgent.admissionController.validation.enabled` to `false`.
```

2024-12-26 19:33 UTC, aliciascott commented on content/en/containers/guide/cluster_agent_disable_admission_controller.md
> +* Set `clusterAgent.admissionController.mutation.enabled` to `false`.
```suggestion
3. Set `clusterAgent.admissionController.mutation.enabled` to `false`.
```

2024-12-27 09:22 UTC, wdhif commented
Thanks for the review and suggestions 🙏 @aliciascott

2024-12-27 15:45 UTC, aliciascott approved these changes
looks good!

2024-12-27 15:46 UTC, aliciascott commented
/merge

2024-12-27 15:53 UTC, merged