add documentation for watchdog 3rd party monitoring
DataDog/documentation pull request #26918
Opened 2024-12-30 14:54 UTC by HugoPct

### What does this PR do? What is the motivation?
add documentation for watchdog 3rd party monitoring, new feature that we are soon going to release.

### Merge instructions

- [ ] Roll out the feature 
- [ ] Roll out the blog post
- [ ] Edit the blog post URL in the FURTHER READING section of this docs page

Merge readiness:
- [ ] Ready for merge 

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

2024-12-30 16:35 UTC, aliciascott commented
Hi @HugoPct general comment on this before we start the review:
1. Is this a new doc/different from the Faulty Detection here? https://docs.datadoghq.com/watchdog/faulty_deployment_detection/
2. If so it should also probably be added to the [menu](https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/1169361249/Left+nav) file.
3. The Further Reading isn't showing up in the staging preview, because of this incorrectly formatted URL `"https://www.datadoghq.com/blog/<URL FROM THE BLOGPOST>/"`. We do have a process to add blog posts to docs pages after they are published so you can remove this section from further reading for now.

Let us know on the above once you get this added to the menu/left Nav, etc and then we can start a review, thanks!

2024-12-31 08:53 UTC, HugoPct commented
Hi @aliciascott 
1.2. ok added to the menu file
3. done

2024-12-31 17:58 UTC, buraizu requested changes
Thanks, left some suggestions! Let me know if you have any questions.

2024-12-31 17:58 UTC, buraizu commented on content/en/watchdog/faulty_cloud_saas_api_detection.md
> +Automatic Faulty Cloud & SaaS API Detection finds third-party providers (payment gateways, cloud providers, etc) having issues within minutes, reducing mean time to detection (MTTD). Watchdog continu
```suggestion
Automatic Faulty Cloud & SaaS API Detection detects third-party providers (payment gateways, cloud providers, and so on) having issues within minutes, reducing mean time to detection (MTTD). Watchdog uses APM telemetry to continuously monitor for elevated error rates in requests to external providers—such as AWS, OpenAI, Slack, Stripe, and more—to detect service degradation as soon as it occurs. This proactive detection gives you a head start in identifying and mitigating issues before they escalate, significantly reducing time spent on root cause analysis and improving response times.
```

2024-12-31 17:58 UTC, buraizu commented on content/en/watchdog/faulty_cloud_saas_api_detection.md
> +When Watchdog identifies that an external provider you are using is faulty, it adds which services are impacted by the problem and the extent of the disruption, allowing you to differentiate between
```suggestion
When Watchdog identifies that an external provider you are using is faulty, it flags the services impacted by the problem and the extent of the disruption. This allows you to differentiate between external and internal issues. Datadog also provides direct links to the provider's status page and support channels, so you can reach out to them as needed.
```

2024-12-31 17:58 UTC, buraizu commented on content/en/watchdog/faulty_cloud_saas_api_detection.md
> +When Watchdog identifies that an external provider you are using is faulty, it adds which services are impacted by the problem and the extent of the disruption, allowing you to differentiate between
It's not clear to me what Watchdog "adding" services means, so I've updated this to `flag` in the above suggestion. Feel free to make any additional updates if there's a better way to express this.

2024-12-31 17:58 UTC, buraizu commented on content/en/watchdog/faulty_cloud_saas_api_detection.md
> +Whenever a faulty deployment is detected, Watchdog adds this as an event in the [Event Explorer][1]. You can set up a monitor to get automatically notified on such events. To do so, navigate to the [
```suggestion
Whenever a faulty deployment is detected, Watchdog creates an event in the [Event Explorer][1]. You can set up a monitor to get automatically notified on such events:

1. Go to the [New Monitor][2] page.
2. Choose **Watchdog**.
3. Select `Third Party` in the alert category.
```

2024-12-31 17:58 UTC, buraizu commented on content/en/watchdog/faulty_cloud_saas_api_detection.md
> +[1]: /service_management/events/explorer
```suggestion
[1]: https://app.datadoghq.com/event/explorer
```

2024-12-31 17:58 UTC, buraizu commented on content/en/watchdog/faulty_cloud_saas_api_detection.md
> +{{< img src="watchdog/external_provider_outage.png" alt="Faulty SaaS API vendor detection" >}}
The text on this image is too small to easily read, even when expanded. Could you please update this image with one that is more zoomed-in?

2025-01-02 10:09 UTC, HugoPct commented on content/en/watchdog/faulty_cloud_saas_api_detection.md
> +{{< img src="watchdog/external_provider_outage.png" alt="Faulty SaaS API vendor detection" >}}
@buraizu 
unfortunately no major incident happened among the providers we monitor recently so I cannot replace the image

(i cannot retake the screenshot either, as data is not available anymore)

will update whenever we can

2025-01-03 00:21 UTC, buraizu approved these changes

2025-01-14 13:07 UTC, HugoPct commented
/merge

2025-01-14 13:30 UTC, merged