adding back in data collected missed info
DataDog/documentation pull request #8338
Opened 2020-08-20 16:37 UTC by apigirl

### What does this PR do?

Adds in info that we missed when we reorged the docs.

https://docs-staging.datadoghq.com/kaylyn/rum-missed-info/real_user_monitoring/browser/data_collected/

2020-09-01 19:50 UTC, apigirl commented
@hdelaby - okay, I think I found it and added it!

2020-09-02 07:13 UTC, hdelaby commented
Still some content is missing from the user action page, all the content before the attributes are listed.

2020-09-10 17:40 UTC, kayayarai requested changes

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +    - Or the difference between `navigationStart` and the first time the page has no activity for more than 100ms (activity being defined as ongoing network requests, or DOM mutations are currently o
```suggestion
    - Or the difference between `navigationStart` and the first time the page has no activity for more than 100ms (activity being defined as ongoing network requests or a DOM mutation).
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +* **SPA Route Change**: Loading Time is equal to the difference between the user click and the first time the page has no activity for more than 100ms (activity being defined as ongoing network reque
```suggestion
* **SPA Route Change**: Loading Time is equal to the difference between the user click and the first time the page has no activity for more than 100ms (activity being defined as ongoing network requests, or a DOM mutation).
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +| `view.measures.first_contentful_paint` | number (ns) | Time when the browser first rendered any text, image (including background images), non-white canvas, or SVG. For more information about brows
```suggestion
| `view.measures.first_contentful_paint` | number (ns) | Time when the browser first renders any text, image (including background images), non-white canvas, or SVG. For more information about browser rendering, see the [w3 definition][9].                                                                                            |
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +| `view.measures.dom_interactive`        | number (ns) | The moment when the parser finished its work on the main document. [More info from the MDN documentation][10]
```suggestion
| `view.measures.dom_interactive`        | number (ns) | The moment when the parser finishes its work on the main document. [More info from the MDN documentation][10]                                                                                                               |
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +| `view.measures.dom_content_loaded`     | number (ns) | Event fired when the initial HTML document has been completely loaded and parsed, without waiting for non-render blocking stylesheets, images,
```suggestion
| `view.measures.dom_content_loaded`     | number (ns) | Event fired when the initial HTML document is completely loaded and parsed, without waiting for non-render blocking stylesheets, images, and subframes to finish loading. [More info from the MDN documentation][11]. |
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +Detailed network timing data regarding the loading of an application’s resources are being collected with the [Performance Resource Timing API][2]
```suggestion
Detailed network timing data for the loading of an application’s resources are collected with the [Performance Resource Timing API][2].
```
Or:
The Performance Resource Timing API][2] collects detailed network timing data for the loading of an application's resources.

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +Front-end errors are automatically collected with Real User Monitoring (RUM). The error message and stack trace are included when available.
```suggestion
Front-end errors are collected with Real User Monitoring (RUM). The error message and stack trace are included when available.
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +- **console**: console.error() API calls
```suggestion
- **console**: `console.error()` API calls.
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +- **network**: XHR or Fetch errors resulting from AJAX requests. Specific attributes to network errors can be found [in the documentation][1]
```suggestion
- **network**: XHR or Fetch errors resulting from AJAX requests. Specific attributes to network errors can be found [in the documentation][1].
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +- **source**: unhandled exceptions or unhandled promise rejections (source-code related)
```suggestion
- **source**: Unhandled exceptions or unhandled promise rejections (source-code related).
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +| `error.origin`  | string | Where the error originates from (i.e. console, network, etc.)          |
```suggestion
| `error.origin`  | string | Where the error originates from (for example, the console or network).     |
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +Network errors include information about the failing HTTP request. Hence, the following facets are also collected:
```suggestion
Network errors include information about failing HTTP requests. The following facets are also collected:
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +### Network Errors
```suggestion
### Network errors
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +### Source Errors
```suggestion
### Source errors
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +Source Errors include code-level information about the error. More information about the different error types can be found in [the MDN documentation][2].
```suggestion
Source errors include code-level information about the error. More information about the different error types can be found in [the MDN documentation][2].
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +Real User Monitoring (RUM) SDKs automatically detect user interactions performed during a user journey. Set the `trackInteractions` [initialization parameter][5] to `true` to enable this feature.
```suggestion
Real User Monitoring (RUM) SDKs detect user interactions performed during a user journey. Set the `trackInteractions` [initialization parameter][5] to `true` to enable this feature.
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +**Note**:  The trackInteractions initialization parameter enables the automatic collection of user clicks in your application. **Sensitive and private data** contained on your pages may be included t
```suggestion
**Note**:  The `trackInteractions` initialization parameter enables the collection of user clicks in your application. **Sensitive and private data** contained on your pages may be included to identify the elements interacted with.
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +Once an interaction is detected, all new RUM events are attached to the ongoing user action until it is considered as finished. The user action also benefits from its parent view attributes: browser
```suggestion
Once an interaction is detected, all new RUM events are attached to the ongoing user action until it is considered finished. The user action also benefits from its parent view attributes such as browser information, geolocation data, [global context][1].
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +Once an interaction is detected, the RUM SDK watches for network requests an DOM mutations. It is considered finished once the page has no activity for more than 100ms (activity being defined as ongo
```suggestion
Once an interaction is detected, the RUM SDK watches for network requests an DOM mutations. It is considered finished once the page has no activity for more than 100ms (activity being defined as ongoing network requests or DOM mutations).
```

2020-09-10 17:40 UTC, kayayarai commented on content/en/real_user_monitoring/browser/data_collected.md
> +Custom User Actions are User Actions declared and sent manually via the [`addUserAction` API][2]. They are useful to send information relative to an event occuring during a user journey: a custom tim
```suggestion
Custom User Actions are User Actions declared and sent manually via the [`addUserAction` API][2]. They can send information relative to an event occurring during a user journey, for example, a custom timing or customer cart information.
```

2020-09-10 17:46 UTC, kayayarai approved these changes

2020-09-10 17:46 UTC, merged