Update datadog-agent-manager-windows.md
DataDog/documentation pull request #8476
Opened 2020-09-07 05:26 UTC by aquiladayc

Add supported browser section following below.
https://github.com/DataDog/web-ui/blob/89c39abcc1999c2cc04f6db433b549eb00586d77/javascript/datadog/lib/browser/warn-unsupported-browser.tsx#L6-L13

### What does this PR do?

### Motivation
Related zendesk ticket: https://datadog.zendesk.com/agent/tickets/389736
Customer found the Agent manager doesn't work on IE8 and it's not documented. So I added here.

### Preview link

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

Check preview base path using the URL in details in `preview` status check.

### Additional Notes

2020-09-08 22:34 UTC, kayayarai requested changes
Thanks for this update! Just a few minor style changes needed.

2020-09-08 22:34 UTC, kayayarai commented on content/en/agent/guide/datadog-agent-manager-windows.md
> +#### Supported browser
```suggestion
#### Supported browsers
```

2020-09-08 22:34 UTC, kayayarai commented on content/en/agent/guide/datadog-agent-manager-windows.md
> +| Edge          | 12                           |  Old, pre-chromium Edge |
```suggestion
| Edge          | 12                           |  Pre-Chromium Edge |
```

2020-09-08 22:34 UTC, kayayarai commented on content/en/agent/guide/datadog-agent-manager-windows.md
> +| Browser       | Supported Version (or later) | Comment                 |
```suggestion
| Browser       | Supported version (or later) | Comment                 |
```

2020-09-15 00:31 UTC, aquiladayc commented
Thanks for your review! Applied those changes!

2020-09-15 16:41 UTC, kayayarai approved these changes

2020-09-15 16:41 UTC, merged