Getting Started with Dashboards
DataDog/documentation pull request #8573
Opened 2020-09-17 15:48 UTC by kayayarai

### What does this PR do?

Adds getting started with dashboards page

### Motivation

Docs OKR/DOCS-899

### Preview link
https://docs-staging.datadoghq.com/kari/getting-started-dashboards/getting_started/dashboards/

2020-09-17 19:27 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +Creating a good dashboard is about bringing the answers to these questions to the surface. Also, it is important not to cram all of those conversations into the same dashboard. Create separate dashbo
```suggestion
Creating a good dashboard is about bringing the answers to these questions to the surface. Also, it is important not to cram all of those solutions into the same dashboard. Create separate dashboards to show answers to different kinds of questions.
```

2020-09-17 19:28 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +The key to getting started with dashboards is knowing what kinds of questions you ask yourself regularly. What are common issues your customers face? When a problem occurs, what questions help you fi
```suggestion
The key to getting started with dashboards is knowing what kind of questions you ask yourself regularly. What are common issues your customers face? When a problem occurs, what questions help you find a solution? 
```

2020-09-17 19:36 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +This guide gets you started on a path to making dashboards. These basic dashboards will help your team talk about things that really matter and get to the bottom of problems quickly.
```suggestion
This guide gets you started on a path to creating dashboards. The basic dashboards will help your team talk about things that really matter and get to the bottom of problems quickly.
```

2020-09-17 19:37 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +If you haven't already, create a [Datadog account][1]. Install an agent on a host, and an integration for something running on that host.
```suggestion
If you haven't already, create a [Datadog account][1]. Install the Agent on a host, and an integration for something running on that host.
```

2020-09-17 19:39 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +If you haven't already, create a [Datadog account][1]. Install an agent on a host, and an integration for something running on that host.
Maybe some links to the agent setup / integrations page here, just to make it easier for people to get up and running.

2020-09-17 19:50 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +Also think about what purpose you're creating the dashboard for. A dashboard can help you and your teammates focus on the right work. A _team dashboard_ reminds you what's high priority, what needs a
```suggestion
Also, determine the purpose of the dashboard you're creating. A dashboard can help you and your teammates focus on the right work. A _team dashboard_ reminds you what's high priority, what needs attention now, and what you're succeeding at. Make a team dashboard (or multiple) with the information that people most frequently need they have to dig for. SLO and SLI details make for an excellent team dashboard.
```

2020-09-17 19:51 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +Also think about what purpose you're creating the dashboard for. A dashboard can help you and your teammates focus on the right work. A _team dashboard_ reminds you what's high priority, what needs a
https://docs.datadoghq.com/dashboards/widgets/slo/ - would be good to link to the SLO widget here.

2020-09-17 19:57 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +A dashboard connected to real-time data is a powerful tool for guiding conversations with managers and executives. A good _executive dashboard_ can show that you are working on the most important thi
```suggestion
A dashboard connected to real-time data is a powerful tool for guiding conversations with managers and executives. A good _executive dashboard_ can show that you are working on the most important things, how much a service is costing you, or whether you're progressing toward goals, meeting your SLOs, and scaling effectively. Executive dashboards are most effective when they answer these questions at the highest level and are interconnected to drill down into the answer.
```

2020-09-17 20:03 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +Dashboards can also help you track down persistent problems and fix them. _Troubleshooting dashboards_ often start as a scratch pad of things you know, and gradually build as you discover more. For e
```suggestion
Dashboards can also help you track down persistent problems and fix them. _Troubleshooting dashboards_ often start as a scratch pad of things you know, and gradually build as you discover more. For example, start with a graph or widget from another dashboard or view that shows a problem. You can then drill down from there to find your solution.
```

2020-09-17 20:04 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +## Start by reusing good things
```suggestion
## Start by reusing other dashboards
```

2020-09-17 20:06 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +3. Delete widgets you don't use by selecting **Delete** from the widget's Settings menu.
```suggestion
3. Delete widgets you don't need by selecting **Delete** from the widget's Settings menu.
```

2020-09-17 20:07 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +1. Clone it by opening the dashboard and selecting **Clone dashboard** from the Settings menu (the gear icon on the right-hand side). This creates an unlinked copy of the dashboard; changes you make
Might be good to throw in a screenshot or gif in to show how to clone

2020-09-17 20:09 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +Through integrations, Datadog collects [metrics][3] about your infrastructure and applications. The collected metrics are documented in the integration's Readme files. If you encounter a metric in th
```suggestion
Through integrations, Datadog collects [metrics][3] from your infrastructure and applications. The collected metrics are documented in the integration's README files. If you encounter a metric in the [Metrics Explorer][4] or as you're creating a dashboard, and you want to know what the metric is, look it up in the Integrations docs. 
```

2020-09-17 20:09 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +Through integrations, Datadog collects [metrics][3] about your infrastructure and applications. The collected metrics are documented in the integration's Readme files. If you encounter a metric in th
Probably helpful to drop a link to an existing integrations doc with metrics for context

2020-09-17 20:15 UTC, sarina-dd requested changes
👍 Looks great so far! Only overall suggestion is a few screenshots or gifs to help guide/give users an idea of what they're looking for/at.

2020-09-17 20:15 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +For example, suppose you are looking at a time graph of the metric `aws.s3.first_byte_latency`. Go to the [Data collected][5] section of the AWS S3 integration Readme to see its description:
```suggestion
For example, suppose you are looking at a time graph of the metric `aws.s3.first_byte_latency`. Go to the [Data collected][5] section of the AWS S3 integration README to see its description: 
```

2020-09-17 20:15 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +    The average per-request time from the complete request being received by a bucket to when the response starts to be returned. Shown as millisecond
```suggestion
    `The average per-request time from the complete request being received by a bucket to when the response starts to be returned. Shown as millisecond.`
```

2020-09-17 20:15 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> + - **Top lists**: Show, for example, which hosts have the least free space, or which services are throwing the most errors or which URLs are returning the most 404s.
```suggestion
 - **Top lists**: For example, show which hosts have the least free space, which services are throwing the most errors, or which URLs are returning the most 404s.
```

2020-09-18 15:39 UTC, sarina-dd reviewed
Left a few small additional edits I missed in the first round and tried to reword a few headers to be active / a little shorter. Looks great! 👍

2020-09-18 15:39 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +This guide gets you started on a path to creating dashboards. The basic dashboards will help your team talk about things that really matter and get to the bottom of problems quickly.
```suggestion
This guide gets you started on a path to creating dashboards. These basic dashboards will help your team talk about things that really matter and get to the bottom of problems quickly.
```

2020-09-18 15:39 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +5. Copy in widgets you like from other dashboards by hovering over the widget and typing Command + C (Ctrl + C on Windows). Paste it into your dashboard by opening the dashboard and typing Command +
```suggestion
5. Copy in widgets you like from other dashboards by hovering over the widget and typing `Command + C` (`Ctrl + C` on Windows). Paste it into your dashboard by opening the dashboard and typing `Command + V` (`Ctrl + V` on Windows).
```

2020-09-18 15:39 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +### Share your dashboards outside the Datadog app
```suggestion
### Share your dashboards outside of the Datadog app
```

2020-09-18 15:39 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +## Try something not strictly timeseries metrics
```suggestion
## Try out other widgets
```

2020-09-18 15:39 UTC, sarina-dd commented on content/en/getting_started/dashboards/_index.md
> +## Figuring out what a metric means
```suggestion
## Learn more about metrics
```

2020-09-18 17:33 UTC, apigirl approved these changes

2020-09-18 20:08 UTC, sarina-dd approved these changes

2020-09-18 20:09 UTC, merged