Yael/apm network tab
DataDog/documentation pull request #8632
Opened 2020-09-24 16:34 UTC by shlomoartzi

### What does this PR do?
Adds documentation for a new Network tab in APM, including sample use cases.

### Motivation
We plan to release the feature this week.

### Preview
https://docs-staging.datadoghq.com/yael/apm_network_tab/documentation/content/en/tracing/visualization/trace.md

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2020-09-24 22:56 UTC, andrewardito approved these changes
LGTM!

2020-09-30 14:43 UTC, ruthnaebeck requested changes

2020-09-30 14:43 UTC, ruthnaebeck commented on content/en/tracing/visualization/trace.md
> +Click on a service’s span to see network dependencies of the service making the request. Use key network performance metrics such as volume, errors (TCP retransmits) and network latency (TCP round-tr
```suggestion
Click on a service’s span to see network dependencies of the service making the request. Use key network performance metrics such as volume, errors (TCP retransmits), and network latency (TCP round-trip time) to differentiate between application-specific and network-wide issues, especially when no code errors have been generated. For instance, you can use network telemetry to determine if high request latency is due to traffic overloading of the relevant application, or faulty dependencies with a downstream pod, security group, or any other tagged endpoint. Clicking on a process brings you to the [Network Overview][1]. To view span-specific processes, enable [Network Performance Monitoring][2].

**Note**: Related network telemetry is not currently supported for serverless traces.
```

2020-09-30 14:43 UTC, ruthnaebeck commented on content/en/tracing/visualization/trace.md
> +{{< img src="tracing/visualization/trace/trace_networks.png" alt="Trace Network Dependencies"  style="width:90%;">}}
```suggestion
{{< img src="tracing/visualization/trace/trace_networks.png" alt="Trace Network Dependencies" style="width:90%;">}}
```

2020-09-30 15:25 UTC, ruthnaebeck approved these changes
👍

2020-09-30 16:03 UTC, merged