Update notifications.md
DataDog/documentation pull request #8707
Opened 2020-10-01 23:58 UTC by aquiladayc

Add sample for Log facet variable. 
slack discussion
https://dd.slack.com/archives/C03MS5SNG/p1601424256275600?thread_ts=1601334801.460900&cid=C03MS5SNG

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2020-10-02 18:24 UTC, ruthnaebeck requested changes

2020-10-02 18:24 UTC, ruthnaebeck commented on content/en/monitors/notifications.md
> +#### Log facet for variables
```suggestion
#### Log facet variables
```

2020-10-02 18:24 UTC, ruthnaebeck commented on content/en/monitors/notifications.md
> +In Log monitor, you can group by facets. In that case, that facets can be used as a variable.
```suggestion
Log monitors can use facets as variables if the monitor is grouped by the facets.
```

2020-10-02 18:24 UTC, ruthnaebeck commented on content/en/monitors/notifications.md
> +For example, if your facet is `@facet` and your monitor is grouped by that, use:
```suggestion
For example, if your log monitor is grouped by the facet `@facet`, the variable is:
```

2020-10-02 18:24 UTC, ruthnaebeck commented on content/en/monitors/notifications.md
> +If your facet is with periods, let's say `@facet.with.dot` use:
```suggestion
If your facet has periods, use brackets around the facet, for example:
```

2020-10-13 06:03 UTC, aquiladayc commented
is it fine?

2020-10-13 21:23 UTC, ruthnaebeck approved these changes
👍

2020-10-13 21:24 UTC, merged

2020-10-14 00:38 UTC, aquiladayc commented
thank you!