Create access-your-log-data-programmatically.md
DataDog/documentation pull request #8745
Opened 2020-10-07 01:58 UTC by pgkamat

### What does this PR do?
This is a How-To Guide for our our Logs List API. This includes various API request and responses.

### Motivation
Customers need examples to understand how to use the new API 

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2020-10-12 07:43 UTC, NBParis commented on content/en/logs/guide/access-your-log-data-programmatically.md
> +With the following API call, limit the number of log events retrieved. The `limit` indicates the maximum number of log events returned in the response.
You do want to indicate the maximum value there. Otherwise we might think it is infinite and therefore wonder why there is pagination.

2020-10-12 07:44 UTC, NBParis commented on content/en/logs/guide/access-your-log-data-programmatically.md
> +                    "source:postman",
Looks weird that we get two postman source tags.

2020-10-12 07:44 UTC, NBParis commented on content/en/logs/guide/access-your-log-data-programmatically.md
> +With the following API call, limit the number of log events retrieved. The `limit` indicates the maximum number of log events returned in the response.
Especially as you say it in the next section :)

2020-10-12 07:46 UTC, NBParis commented
@pgkamat did I miss something or did we remove the guide on the Analytics API in this PR?

Are we adding it back in a different name in a different PR?

2020-10-16 18:26 UTC, sarina-dd requested changes

2020-10-16 18:26 UTC, sarina-dd commented on content/en/logs/guide/access-your-log-data-programmatically.md
> +To see next page of your logs, continue to resend your query but include the `cursor` parameter where it takes the `after` value from the previous call.
```suggestion
To see the next page of your logs, resend the query with the `cursor` parameter that takes the `after` value from the previous call. 
```

2020-10-16 18:26 UTC, sarina-dd commented on content/en/logs/guide/access-your-log-data-programmatically.md
> +From the above JSON example, use the `after` value of `eyJhZnRlciI6IkFRQUFBWFVBWFZOU3Z1TXZXd0FBQUFCQldGVkJXRlpPVTJJMlpXY3hYM2MyTFZWQlFRIiwidmFsdWVzIjpbIjUwMCJdfQ` to get the next 2 results.
```suggestion
From the above JSON example, use the `after` value `eyJhZnRlciI6IkFRQUFBWFVBWFZOU3Z1TXZXd0FBQUFCQldGVkJXRlpPVTJJMlpXY3hYM2MyTFZWQlFRIiwidmFsdWVzIjpbIjUwMCJdfQ` to get the next two results.
```

2020-10-16 18:26 UTC, sarina-dd commented on content/en/logs/guide/access-your-log-data-programmatically.md
> +In the response, the next two results i.e. `joe` with 500 `pageviews` and `chris` with 450 `pageviews` are retrieved. When you see `data` returns `null`, you have returned all pages of logs associate
```suggestion
In the response, the next two results, (for example, `joe` with 500 `pageviews` and `chris` with 450 `pageviews`) are retrieved. When you see `data` returns `null`, you have returned all pages of logs associated with your query.
```

2020-10-26 23:23 UTC, pgkamat commented
I followed up on Nils comment above.  The goal is to create a new guide for Logs List API. Instead, something seems messed up and it got mixed up with Log Analytics API guide during PR creation. So I am taking the content and starting a clean PR https://github.com/DataDog/documentation/pull/8918.

Closing this PR.

2020-10-26 23:23 UTC, closed without merging