Updated monitor_status.md to include a case for low frequency metrics
DataDog/documentation pull request #8861
Opened 2020-10-20 11:20 UTC by Tony-Mc

### What does this PR do?
Added another case for `no groups found` in the monitor status docs.

My issue was that my selected timeframe was too small (15 min) for a metric that was reporting in low frequency.

This warning is shown in the UI, but it's not provided in the docs.
![image](https://user-images.githubusercontent.com/8818187/96579016-ce699e00-12de-11eb-8adb-c9c7dc0cc257.png)

### Motivation
I ran into this issue myself, checked this documentation page, but it didn't include the case mentioned.

### Preview

This is a fork.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2020-10-21 21:27 UTC, kayayarai requested changes
Thank you for this improvement! I've suggested some slight wording changes -- if you commit them, we can approve and merge.

2020-10-21 21:27 UTC, kayayarai commented on content/en/monitors/monitor_status.md
> +* The monitor's timeframe is too small for a metric that provides data at low frequencies.
```suggestion
* The monitor's timeframe is too short for a metric that provides data infrequently.
```

2020-10-21 21:31 UTC, Tony-Mc commented
> Thank you for this improvement! I've suggested some slight wording changes -- if you commit them, we can approve and merge.

Done.

2020-10-26 22:08 UTC, apigirl approved these changes

2020-10-26 22:08 UTC, merged