WEB-896 add multi-code-lang page functionality
DataDog/documentation pull request #8925
Opened 2020-10-27 19:24 UTC by zbayoff

### What does this PR do?
Add functionality to swap pages out based on a code language cookie.

### Motivation
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-896

### Preview
https://docs-staging.datadoghq.com/zach/multi-page-code-lang/tracing/compatibility_requirements/

Click a language on this page ^ should go to that language. Each programming language page should have a code lang buttons to select users pref. This will also set a cookie which is compatible with the `programming-lang` shortcode used on main Docs pages and API pages.

2020-11-02 19:59 UTC, nsollecito approved these changes

2020-11-03 23:07 UTC, andrewsouthard1 requested changes
Few comments on clarifying language. In terms of areas that I did not comment on:

https://a.cl.ly/NQu198BN - - The language tiles themselves seem to be much larger than where they are across the documentation, making it jarring.

https://a.cl.ly/4guJGdGP - The Open Standards section overall I think we need to have more a succinct vision on, without some kind of intro to this content it doesn't feel warranted yet to be in it's own area.

2020-11-04 16:01 UTC, kayayarai commented on content/en/tracing/setup_overview/_index.md
> +Configuring your application to send [traces][1] to Datadog involves two steps:
Added rewording, fixed language tile widths. The Open Standards improvements are being tracked under DOCS-1409.

2020-11-04 16:02 UTC, kayayarai commented on content/en/tracing/setup_overview/setup/java.md
> +4. Install and configure the Datadog Agent to receive traces from your now instrumented application:
Done

2020-11-04 16:02 UTC, kayayarai commented on content/en/tracing/setup_overview/_index.md
> +Depending on your environment, there may be APM-specific configurations required on both the Tracer and Agent to ensure that traces can be properly received, so ensure you have followed instructions
Done

2020-11-04 18:41 UTC, sarina-dd approved these changes

2020-11-04 18:42 UTC, merged