Update kubernetes helm deployment doc
DataDog/documentation pull request #9143
Opened 2020-11-25 19:45 UTC by clamoriniere

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2020-11-25 19:58 UTC, cohenyair commented on content/en/agent/kubernetes/_index.md
> +- If `gcr.io/datadoghq` is not accessible in the deployment region, the Datadog docker hub registry images can be used [8][9].
If Google Container Registry (`gcr.io/datadoghq`) is not accessible in your deployment region, you can use Docker Hub registry by changing the following parameters in the `values.yaml` file:

2020-11-25 19:58 UTC, cohenyair commented on content/en/agent/kubernetes/_index.md
> +- If `gcr.io/datadoghq` is not accessible in the deployment region, the Datadog docker hub registry images can be used [8][9].
[8] & [9] are missing the text body, no?

2020-11-25 20:18 UTC, CharlyF approved these changes

2020-11-25 21:18 UTC, ruthnaebeck requested changes
docs review

2020-11-25 21:18 UTC, ruthnaebeck commented on content/en/agent/kubernetes/_index.md
> +- If Google Container Registry ([gcr.io/datadoghq][8]) is not accessible in your deployment region, the Docker Hub registry can be used with the images [datadog/agent][9] and [datadog/cluster-agent][
```suggestion
- If Google Container Registry ([gcr.io/datadoghq][8]) is not accessible in your deployment region, use the Docker Hub registry with the images [datadog/agent][9] and [datadog/cluster-agent][10] with the following configuration in the `values.yaml` file:
```

2020-11-25 21:21 UTC, clamoriniere commented
@ruthnaebeck thanks for the review. I have updated the PR with your comment.

2020-11-30 19:20 UTC, ruthnaebeck approved these changes
👍 for docs

2020-11-30 19:21 UTC, merged