Update docker logs collection with AD label supporting file tailing
DataDog/documentation pull request #9235
Opened 2020-12-10 17:41 UTC by prognant

### What does this PR do?
Document new feature coming with Agent 7.25.0 (https://github.com/DataDog/datadog-agent/pull/6883).

### Motivation
Keep doc up-to-date.

### Preview
https://docs-staging.datadoghq.com/prognant/file-tailing-from-docker-AD-label

### Additional Notes
It will be available for agent >= 7.25

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2020-12-10 19:16 UTC, ruthnaebeck requested changes

2020-12-10 19:16 UTC, ruthnaebeck commented on content/en/agent/docker/log.md
> +- The path is **relative** to the Agent, thus the directory containing the file should be shared between the container running the application logging to the file and the Agent container. For example
```suggestion
- The file path is **relative** to the Agent, so the directory containing the file should be shared between the container running the application and the Agent container. For example, if the container mounts `/logs` each container logging to file may mount a volume such as `/logs/app` where the log file is written.
```

2020-12-10 19:16 UTC, ruthnaebeck commented on content/en/agent/docker/log.md
> +- When using this kind of label on a container, its `stderr`/`stdout` logs are not collected automatically. If collection from both `stderr`/`stdout` and a file are needed it should be explicity enab
```suggestion
- When using this kind of label on a container, its `stderr`/`stdout` logs are not collected automatically. If collection from both `stderr`/`stdout` and a file are needed it should be explicity enabled by using a label, for example:
```

2020-12-10 19:16 UTC, ruthnaebeck commented on content/en/agent/docker/log.md
> +- When using this kind of combination, `source` and `service` have no default value, and therefore they should be explicitely set in the Autodiscovery label.
```suggestion
- When using this kind of combination, `source` and `service` have no default value and should be explicitly set in the Autodiscovery label.   
```

2020-12-14 15:52 UTC, sarina-dd commented
@cohenyair Did a review of the content and this looks great! 👍 I'll let Ruth finalize the review as she requested previous changes during the editorial review.

2021-01-11 17:44 UTC, sarina-dd commented
@prognant Hi there! Checking in on status: are we okay to merge this now that the feature is released, or are we waiting on additional merges?

2021-01-11 17:46 UTC, prognant commented
Hi @sarina-dd, the agent release (7.25.0) targeted by this documentation PR is due for release soon (unsure exactly when), If that's ok I can ping you here as soon as we got 7.25.0 out ?

2021-01-12 19:43 UTC, sarina-dd commented
@prognant Yep, sounds good 👍 Just ping me whenever we're ready and I can publish. Thanks for this!

2021-01-15 09:12 UTC, prognant commented
Hi @sarina-dd, the [Agent v7.25.0 ](https://github.com/DataDog/datadog-agent/releases/tag/7.25.0) so you can now merge this PR !

2021-01-15 18:45 UTC, sarina-dd approved these changes

2021-01-15 19:17 UTC, ruthnaebeck approved these changes
👍

2021-01-15 19:18 UTC, merged