add advanced filtering page
DataDog/documentation pull request #9236
Opened 2020-12-10 18:28 UTC by cswatt

### What does this PR do?

### Motivation

### Preview

https://docs-staging.datadoghq.com/cswatt/advanced-filtering/metrics/advanced-filtering

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2020-12-11 16:18 UTC, ijkaylin commented
For the advanced filtering doc: 

- can we bold the "From dropdown" phrase in the first paragraph? 
-  make sure the query strings appear before the photos/ GIFs ?

2020-12-11 21:43 UTC, ruthnaebeck commented on content/en/metrics/advanced-filtering.md
> +```
Add this to the bottom:

```
## Further Reading

{{< partial name="whats-next/whats-next.html" >}}
```

2020-12-11 21:44 UTC, ruthnaebeck commented on content/en/metrics/advanced-filtering.md
> +Regardless of whether you’re using Metrics Explorer, monitors, dashboards, or notebooks to query metrics data, you can filter the data to narrow the scope of the timeseries returned. Any metric can b
```suggestion
Regardless of whether you’re using the Metrics Explorer, monitors, dashboards, or notebooks to query metrics data, you can filter the data to narrow the scope of the timeseries returned. Any metric can be filtered by tag(s) using the from dropdown to the right of the metric. 
```

2020-12-11 21:47 UTC, ruthnaebeck commented on content/en/metrics/summary.md
> +Click on any metric name to display its details sidepanel for more detailed information regarding the metric’s metadata and tags:
```suggestion
Click on any metric name to display its details sidepanel for more information regarding the metric’s metadata and tags: 
```

2020-12-11 21:48 UTC, ruthnaebeck commented on content/en/metrics/summary.md
> +Learn more in the [counting custom metrics][4] documentation.
```suggestion
Learn more in the [custom metrics][4] documentation.
```

2020-12-11 21:48 UTC, ruthnaebeck commented on content/en/metrics/summary.md
> +The total number of hosts reporting a metric .
```suggestion
The total number of hosts reporting a metric.
```

2020-12-11 21:48 UTC, ruthnaebeck commented on content/en/metrics/summary.md
> +### Tag Values
```suggestion
### Tag values
```

2020-12-11 21:50 UTC, ruthnaebeck commented on content/en/metrics/summary.md
> +- Quickly search through the paginated table of tags for a particular tag key.
```suggestion
- Search through the paginated table of tags for a particular tag key.
```

2020-12-11 21:50 UTC, ruthnaebeck commented on content/en/metrics/summary.md
> +- Use a specific tag key:value to further filter the list of metrics displayed on the Metrics Summary page .
```suggestion
- Use a specific tag `key:value` to further filter the list of metrics displayed on the Metrics Summary page.
```

2020-12-11 21:51 UTC, ruthnaebeck commented on content/en/metrics/summary.md
> +- Open a graph of this metric filtered by your tag key:value pair in Metrics Explorer.
```suggestion
- Open a graph of this metric filtered by your tag `key:value` pair in the Metrics Explorer.
```

2020-12-11 21:52 UTC, ruthnaebeck commented on content/en/metrics/summary.md
> +- Copy any tag key:value for easier filtering across the application.
```suggestion
- Copy any tag `key:value` for filtering across the application.
```

2021-01-04 17:46 UTC, ruthnaebeck approved these changes
👍

2021-01-04 18:46 UTC, ijkaylin commented
Last edits for Advanced Filtering doc: 
Can we change this query to match the one in the GIF? 
_avg:system.cpu.user{env:shop.ist AND availability-zone IN (us-east-1a, us-east-1c, us-east-1d)} by {availability-zone}_ should now be

`avg:system.cpu.user{env:shop.ist AND availability-zone IN (us-east-1a, us-east-1b, us-east-4b)} by {availability-zone}`

** Edits for Metrics Summary ** 
* https://docs-staging.datadoghq.com/cswatt/advanced-filtering/metrics/summary/#metric-type: The type for your metric (gauge, rate, count, distribution). See the metric type page for more details.

Warning: Editing the metric type changes that metric’s behavior for ALL your dashboards and monitors.

2021-01-20 17:14 UTC, ijkaylin requested changes

2021-01-28 21:19 UTC, ijkaylin requested changes

2021-01-28 21:19 UTC, ijkaylin commented on content/en/metrics/_index.md
>  To make this concrete with an example, suppose your host reported metric values of [1,1,1,2,2,2,3,3] during a ten-second interval. Depending on the metric type you chose, Datadog would store complete
```suggestion
```

2021-01-28 21:19 UTC, ijkaylin commented on content/en/metrics/_index.md
> +_Count_ would add them up and send the value 15 over to Datadog's servers, while _rate_ would take the total sum and divide it by 10 seconds to report a value of 1.5. _Gauge_ would simply report the
```suggestion
```

2021-01-28 21:19 UTC, ijkaylin commented on content/en/metrics/_index.md
> +Metric types also determine which graphs and functions are available to use with the metric in the app. See the [metrics types][15] documentation for more detailed examples of each metric type and su
```suggestion
See the [metrics types][15] documentation for more detailed examples of each metric type and submission instructions.
```

2021-02-01 15:59 UTC, apigirl approved these changes

2021-02-01 16:01 UTC, merged