Adding distribution metrics FAq
DataDog/documentation pull request #9417
Opened 2021-01-05 20:00 UTC by apigirl

### What does this PR do?
Adds a FAq for updating to Distribution metrics

https://docs-staging.datadoghq.com/kaylyn/metrics-guide/metrics/faq/updating-to-distribution-metrics-faq/

2021-01-05 22:54 UTC, ijkaylin requested changes

2021-01-05 22:54 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +Datadog has a new pipeline for calculating globally accurate percentiles for your distribution metrics - this unlocks more query functionality and an easier configuration workflow for distributions.
Datadog has released a new pipeline for calculating globally accurate percentiles for your distribution metrics - this unlocks more query functionality and an easier configuration workflow for distributions.

2021-01-05 22:54 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +- Unlocks new query functionalities:
**Unlocks new query functionalities:**

2021-01-05 22:54 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +- Easier tag configuration and percentile aggregation workflows:
- **Easier tag configuration and percentile aggregation workflows:**

2021-01-05 22:54 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +  - Accurate percentiles in time for any historical timeframe (i.e., the past day, week, month) of their choosing.
- Accurate percentiles in time for any historical timeframe (i.e., the past day, week, month)

2021-01-05 22:54 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +  - The Metrics Summaray page now centrally manages all tag configuration and percentile aggregations.
- All tag configuration / percentile aggregations will be managed in one centralized location on the [Metrics Summary](https://app.datadoghq.com/metric/summary) page

2021-01-05 22:54 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +  | Metric Type                               | Query Type                                                                                                     | # of billable custom metrics emitted
| Metric Type                               | Query Type                                                                                                     | # of custom metrics emitted               |

2021-01-05 22:54 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +| Distribution with Percentile Aggregations | Queryable by `count`, `sum`, `min`, `max`,`avg` + p50, `avg` + p75, `avg` + p90, `avg` + p95, and `avg` + p99. | 10 * (tag value combinations emitted in
| Distribution with Percentile Aggregations | Queryable by `count`, `sum`, `min`, `max`,`avg`, `p50`, `p75`, `p90`, `p95`, and `p99`. | 10 * (tag value combinations emitted in your data) |

2021-01-05 22:54 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +Click *edit* and “Include percentile aggregations” on the same queryable tags defined as your baseline distribution.
Click *Edit* and “Include” to include percentile aggregations on the same queryable tags defined as your baseline distribution.

2021-01-05 22:54 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +Click the *Calculate Percentiles* button on the Metrics Summary page and use * for wildcard metric name(s).
Click the *Calculate Percentiles* button on the Metrics Summary page and use * for wildcarding metric names.

2021-01-05 23:22 UTC, apigirl commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +
```suggestion
[1]: https://app.datadoghq.com/metric/summary
```

2021-01-05 23:36 UTC, apigirl commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +**Unlocks new query functionalities:**```
```suggestion
- **Unlocks new query functionalities:**
```

2021-01-06 14:46 UTC, kayayarai requested changes
A few edits

2021-01-06 14:46 UTC, kayayarai commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +  - Accurate percentiles in time for any historical timeframe (i.e., the past day, week, month).
```suggestion
  - Accurate percentiles in time for any historical timeframe (such as the past day, week, or month).
```

2021-01-06 14:46 UTC, kayayarai commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +Datadog has released a new pipeline for calculating globally accurate percentiles for your distribution metrics - this unlocks more query functionality and an easier configuration workflow for distri
```suggestion
Datadog has released a new pipeline for calculating globally accurate percentiles for your distribution metrics --- this unlocks more query functionality and an easier configuration workflow for distributions.
```

2021-01-06 14:46 UTC, kayayarai commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +  - All tag configuration / percentile aggregations will be managed in one centralized location on the [Metrics Summary][1] page
```suggestion
  - All tag configuration-percentile aggregations are managed in one centralized location on the [Metrics Summary][1] page
```

2021-01-06 14:46 UTC, kayayarai commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +- More Intuitive number of Custom Metrics from Distributions with Percentiles:
```suggestion
- **More usable number of custom metrics from distributions with percentiles**:
```

2021-01-06 14:46 UTC, kayayarai commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +| Distribution with Percentile Aggregations | Queryable by `count`, `sum`, `min`, `max`, p50,  p75,  p90, p95, and p99. | 10 * (tag value combinations emitted in your data) |
```suggestion
| Distribution with percentile aggregations | Queryable by `count`, `sum`, `min`, `max`, `p50`,  `p75`,  `p90`, `p95`, and `p99`. | 10 for each tag-value combination emitted in your data |
```

2021-01-06 14:46 UTC, kayayarai commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +| Distribution                              | Queryable by `count`, `sum`, `min`, `max`, and `avg`.                                                          | 5 * (tag value combinations emitted in y
```suggestion
| Distribution                              | Queryable by `count`, `sum`, `min`, `max`, and `avg`.                                                          | 5 for each tag-value combination emitted in your data  |
```

2021-01-06 14:46 UTC, kayayarai commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +Clicking the *Manage Tags* button allows you to configure which tags are queryable on a particular metric. You’ll be able to preview the new number of indexed custom metrics from your tag configurati
```suggestion
Click the **Manage Tags** button to configure which tags are queryable on a particular metric. You can preview the new number of indexed custom metrics from your tag configuration before saving it.
```

2021-01-06 14:46 UTC, kayayarai commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +Click *Edit* and “Include” to include percentile aggregations on the same queryable tags defined as your baseline distribution.
```suggestion
Click **Edit** and select **Include** to include percentile aggregations on the same queryable tags defined as your baseline distribution.
```

2021-01-06 14:46 UTC, kayayarai commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +Click the *Calculate Percentiles* button on the Metrics Summary page and use * for wildcarding metric names.
```suggestion
Click **Calculate Percentiles** on the Metrics Summary page and use `*` for wildcarding metric names.
```

2021-01-06 15:26 UTC, ijkaylin requested changes

2021-01-06 15:26 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +title: Updating to Distribution Metrics FAQ
```suggestion
title: Update to Distribution Metrics Workflow FAQ
```

2021-01-06 15:26 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +  - Use the the “Manage Tags” button on the Metrics Summary details side panel to manage all tag configurations for your distribution metrics.
```suggestion
  - Use the “Manage Tags” button on the Metrics Summary details side panel to manage the queryable tags configuration for a distribution metric.
```

2021-01-06 15:26 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +  - All tag configuration-percentile aggregations are managed in one centralized location on the [Metrics Summary][1] page
```suggestion
  - All tag configuration-percentile aggregations are managed in one centralized location on the [Metrics Summary][1] page.
```

2021-01-06 15:26 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +  - To add percentile aggregations to your distribution, navigate to the new percentiles section on the side panel, click *Edit* and select “Include percentile aggregations” for the same queryable ta
```suggestion
  - To add percentile aggregations to your distribution, navigate to the new percentiles section on the side panel, click *Edit* and select “Include” for percentile aggregations on the same queryable tags defined on your baseline distribution. You’ll no longer need to specify an additional configuration rule.
```

2021-01-06 15:26 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +- **More usable number of custom metrics from distributions with percentiles**:
```suggestion
- **More intuitive number of custom metrics from distributions with percentiles**:
```

2021-01-06 15:26 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +| Distribution                              | Queryable by `count`, `sum`, `min`, `max`, and `avg`.                                                          | 5 for each tag-value combination emitted
```suggestion
| Distribution                              | Queryable by `count`, `sum`, `min`, `max`, and `avg`.                                                          | 5 for each tag value combination emitted in your data  |
```

2021-01-06 15:26 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +| Distribution with percentile aggregations | Queryable by `count`, `sum`, `min`, `max`, `p50`,  `p75`,  `p90`, `p95`, and `p99`. | 10 for each tag-value combination emitted in your data |
```suggestion
| Distribution with percentile aggregations | Queryable by `count`, `sum`, `min`, `max`, `p50`,  `p75`,  `p90`, `p95`, and `p99`. | 10 for each tag value combination emitted in your data |
```

2021-01-06 15:26 UTC, ijkaylin commented on content/en/metrics/faq/updating-to-distribution-metrics-faq.md
> +Click **Edit** and select **Include** to include percentile aggregations on the same queryable tags defined as your baseline distribution.
```suggestion
Click **Edit** and select **Include** to include percentile aggregations on the same queryable tags defined on your baseline distribution.
```

2021-01-06 15:31 UTC, kayayarai approved these changes

2021-01-06 15:33 UTC, merged