Gus/slo checklist
DataDog/documentation pull request #9420
Opened 2021-01-06 11:31 UTC by l0k0ms

### What does this PR do?

I found this PDF in the corpsite, decided to create a SLO guide from it.

### Motivation

Better SEO + better doc link

### Preview

https://docs-staging.datadoghq.com/gus/slo-checklist/monitors/guide/slo-checklist

2021-01-06 14:13 UTC, markazerdd requested changes

2021-01-06 14:13 UTC, markazerdd commented on content/en/monitors/guide/slo-checklist.md
> +      text: 'Track the status of your SLOs with the new monitor uptime widget'
Monitor uptime widget was deprecated a long time ago. Let's just change this to "Track the status and error budget of your SLOs with Datadog"

2021-01-07 12:18 UTC, markazerdd approved these changes

2021-01-11 17:27 UTC, apigirl approved these changes

2021-01-11 17:27 UTC, merged