Authentication logs guide
DataDog/documentation pull request #9434
Opened 2021-01-07 20:37 UTC by sarina-dd

### What does this PR do?
Adds the new authentication logs guide

### Motivation
We have a new blog post that goes in conjunction with this 😸 

### Preview
https://docs-staging.datadoghq.com/sarina/authenticating-logs-guide

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-01-11 22:12 UTC, cswatt requested changes
just grammar/style things—looks really good!

2021-01-11 22:12 UTC, cswatt commented on content/en/security_monitoring/guide/monitor-authentication-logs-for-security-threats.md
> +In order to gain visibility into all of your authentication activity, ensure log events for all login flows are at the application level. This eliminates gaps in your monitoring coverage. It also giv
```suggestion
To gain visibility into all of your authentication activity, ensure log events for all login flows are at the application level. This eliminates gaps in your monitoring coverage. It also gives you more control over how you log authentication events and what data you are collecting.
```

2021-01-11 22:12 UTC, cswatt commented on content/en/security_monitoring/guide/monitor-authentication-logs-for-security-threats.md
> +Logs that contain the "who" (John Doe), "what" (login success), and when (2020-01-01 12:00:01) of an event provide the best detail for you to perform complex analysis in Datadog.
```suggestion
Logs that contain the "who" (John Doe), "what" (login success), and when (2020-01-01 12:00:01) of an event provide the best level of detail for you to perform complex analysis in Datadog.
```

2021-01-11 22:12 UTC, cswatt commented on content/en/security_monitoring/guide/monitor-authentication-logs-for-security-threats.md
> +Another common authentication attack technique is [**credential stuffing**][11]. Credential stuffing is when an attacker mixes and matches breached login credentials to try to match a real user accou
```suggestion
Another common authentication attack technique is [**credential stuffing**][11]. Credential stuffing is when an attacker mixes and matches breached login credentials to try to match a real user account. To detect this type of attack, look for logins using multiple `usr.id` values all coming from the same `network.client.ip`.
```

2021-01-11 22:12 UTC, cswatt commented on content/en/security_monitoring/guide/monitor-authentication-logs-for-security-threats.md
> +Datadog offers pre-configured [Detection Rules][12] which scan your ingested logs in real time for common attacker techniques like these two. If any log triggers one of these rules, it automatically
```suggestion
Datadog offers pre-configured [Detection Rules][12] that scan your ingested logs in real time for common attacker techniques like the two mentioned above. If any log triggers one of these rules, Datadog automatically generates a [Security Signal][13]. This signal includes key data about the event, such as the type of attack detected and suggestions on how to respond and remedy the situation. You can view, filter, and sort all of your Security Signals in the explorer to triage them and see where to best focus your efforts.
```

2021-01-11 22:12 UTC, cswatt commented on content/en/security_monitoring/guide/monitor-authentication-logs-for-security-threats.md
> +For signals triggered from the `Credential Stuffing Attack` Detection Rule, there is an [out-of-the-box runbook][14] available to help with response and remediation. This runbook guides you through i
```suggestion
For signals triggered from the `Credential Stuffing Attack` Detection Rule, there is an [out-of-the-box runbook][14] available to help with response and remediation. This runbook guides you through investigating a potential credential stuffing attack and includes graphs of related logs. To use this runbook, save a copy and set the the time frame, document your investigation in markdown, and share it with teammates [for commenting][15].
```

2021-01-11 22:12 UTC, cswatt commented on content/en/security_monitoring/guide/monitor-authentication-logs-for-security-threats.md
> +Datadog provides out-of-the-box dashboards, such as the [IP investigation dashboard][16] and [User investigation dashboard][17]. These correlate key data from your authentication logs with relevant d
```suggestion
Datadog provides out-of-the-box dashboards, such as the [IP investigation dashboard][16] and [user investigation dashboard][17]. These correlate key data from your authentication logs with relevant data from the rest of your environment to assist in your investigations.
```

2021-01-12 19:43 UTC, sarina-dd commented
@cswatt committed all changes, thanks for the review!

2021-01-14 18:33 UTC, cswatt approved these changes

2021-01-14 19:35 UTC, merged