added note for supported file types for source maps
DataDog/documentation pull request #9435
Opened 2021-01-08 00:13 UTC by jueyaye

### What does this PR do?
Adds a note about the current supported files for source maps uploaded for Error Tracking. Currently only files with the `.min.js` are accepted.

### Motivation
Example scenario:
Source map is uploaded but errors are collected from minified files with a .mjs extension. Because the back-end seems to only accept the `.min.js` extension there is no unminified stack traces in Error Tracking UI despite source maps having been successfully uploaded.

### Preview

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-01-08 15:43 UTC, sarina-dd requested changes

2021-01-08 15:43 UTC, sarina-dd commented on content/en/real_user_monitoring/error_tracking/_index.md
> +**Note**: Currently only source maps with the `.min.js` extension will work to correctly unminify stack traces in the Error Tracking UI. Source maps with other extensions (i.e. `.mjs`, etc.) while ac
```suggestion
**Note**: Currently only source maps with the `.min.js` extension will work to correctly unminify stack traces in the Error Tracking UI. Source maps with other extensions (for example, `.mjs`, etc.) while accepted will not unminify stack traces. 
```

2021-01-08 15:43 UTC, sarina-dd commented on content/en/real_user_monitoring/guide/upload-javascript-source-maps.md
> +**Note**: Currently only source maps with the `.min.js` extension will work to correctly unminify stack traces in the Error Tracking UI. Source maps with other extensions (i.e. `.mjs`, etc.) while ac
```suggestion
**Note**: Currently only source maps with the `.min.js` extension will work to correctly unminify stack traces in the Error Tracking UI. Source maps with other extensions (for example, `.mjs`, etc.) while accepted will not unminify stack traces. 
```

2021-01-10 22:57 UTC, jueyaye commented
Thanks for the suggestions! I've committed the changes.

2021-01-11 14:13 UTC, sarina-dd approved these changes

2021-01-11 14:13 UTC, merged