Mahashree.rajendran/icmp test
DataDog/documentation pull request #9463
Opened 2021-01-12 09:59 UTC by rmshree

### What does this PR do?

Add documentation page for ICMP tests.

### Motivation
New feature release: https://docs.google.com/document/d/1krqrN0vxeVDXwYqZHe1afTBHTojZuSRajELMgFfToV4/edit#heading=h.svwxvwkd5dm2

### Preview

https://docs-staging.datadoghq.com/mahashree.rajendran/icmp_test/synthetics/api_tests/icmp_tests/

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-01-12 11:34 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/_index.md
>  {{< img src="synthetics/api_tests/api_tests.mp4" alt="API Test subtypes" video="true"  width="100%" >}}
We'll need a new video here :)

2021-01-12 11:36 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +ICMP tests allow you to easily **monitor the availability of your hosts and diagnose network communication issues to verify responsiveness from your application's endpoints**. By asserting on the val
```suggestion
ICMP tests allow you to easily **monitor the availability of your hosts** and **diagnose network communication issues**. By asserting on the values received from one or more **ICMP ping(s)** to your endpoint, Datadog can help **detect connectivity issues, above-quota latency or hops, and unexpected changes in security firewall configuration**.  
 
ICMP tests can run from [**managed**][1] and [**private locations**][2] depending on whether you are willing to trigger ICMP pings to your endpoints from outside or inside your network.
```

Can you also add the bit about the type of runs? (ie. scheduled, on demand, etc.).

2021-01-12 11:36 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +![][8]
Fix screenshot

2021-01-12 11:36 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +1. Specify the **domain name** or **IP address** to run your test on.
```suggestion
1. Specify the **Domain Name** or **IP address** to run your test on.
```

2021-01-12 11:36 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +2. Select the **number of pings** to trigger per test session. By default, the number of pings is set to 4 - you can choose to increase or decrease.
```suggestion
2. Select the **Number of Pings** to trigger per test session. By default, the number of pings is set to 4 - you can choose to increase or decrease.
```

2021-01-12 11:36 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +4. Add env **Tags** as well as any other tag to your ICMP test. You can then use these tags to quickly filter through your Synthetic tests on the [Synthetic Monitoring homepage][9].
```suggestion
4. Add `env` **Tags** as well as any other tag to your ICMP test. You can then use these tags to quickly filter through your Synthetic tests on the [Synthetic Monitoring homepage][9].
```

2021-01-12 11:36 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +* **On a schedule** to ensure your most important services are always accessible to your users. Select the frequency you want Datadog to run your ICMP test.
Add the screenshot that is used in other tests?

2021-01-12 11:36 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +Assertions define what an expected test result is. When hitting `Test URL` basic assertions on `latency`, `packet loss` and ICMP ping result is added. You must define at least one assertion for your
```suggestion
Assertions define what an expected test result is. When hitting `Test URL` basic assertions on `latency`, `packet loss` and `ICMP ping result` is added. You must define at least one assertion for your test to monitor.
```

2021-01-12 11:37 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +| latency       | `is less than`, `is less than or equal`, `is`, `is more than`, `is more than or equal` | _integer (ms)_   |
This table is lacking the aggregation method bit for the latency assertions

2021-01-12 11:37 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +You can create up to 10 assertions per API test by clicking on **New Assertion** or by clicking directly on the response preview:
Add screenshot

2021-01-12 11:37 UTC, MargotLepizzera commented
@rmshree 

A few notes in addition to the inlines ones:

- You'll also need to update https://docs-staging.datadoghq.com/mahashree.rajendran/icmp_test/synthetics/ to include ICMP tests :) 
- Good call updating all other test subtypes!
- We're missing the reference to ICMP test in the menu, see https://a.cl.ly/RBu9Dj6m. IIRC the file that needs to be updated is https://github.com/DataDog/documentation/blob/master/config/_default/menus/menus.en.yaml

2021-01-25 19:19 UTC, MargotLepizzera commented on content/en/synthetics/api_tests/icmp_tests.md
> +| `SSL`             | The SSL connection couldn't be performed. [See the dedicated error page for more information][8].
Let's completely get rid of the SSL line - I recently removed it on DNS & TCP tests :)

2021-03-05 19:07 UTC, jtappa requested changes

2021-03-05 19:07 UTC, jtappa commented on content/en/synthetics/api_tests/icmp_tests.md
> +You can create local variables by defining their values from one of the below available builtins:
```suggestion
You can create local variables by defining their values from one of the below available built-ins:
```

2021-03-05 19:07 UTC, jtappa commented on content/en/synthetics/api_tests/icmp_tests.md
> +A test is considered `FAILED` if it does not satisfy one or several assertions or if the request prematurely failed. In some cases, the test can indeed fail without being able to test the assertions
```suggestion
A test is considered `FAILED` if it does not satisfy one or several assertions or if the request prematurely failed. In some cases, the test can fail without being able to test the assertions against the endpoint, these reasons include:
```

2021-03-11 17:57 UTC, jtappa approved these changes

2021-03-11 21:29 UTC, merged