DOCS-1365 New RUM page: tracking user actions
DataDog/documentation pull request #9560
Opened 2021-01-22 22:15 UTC by kayayarai

### What does this PR do?
Adds a new docs page for tracking user actions in RUM.

### Motivation
DOCS-1365

### Preview
https://docs-staging.datadoghq.com/kari/docs-1365-rum-user-actions/real_user_monitoring/browser/tracking_user_actions/

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-01-25 10:06 UTC, hdelaby approved these changes

2021-01-29 19:10 UTC, cswatt requested changes
editorial review

2021-01-29 19:10 UTC, cswatt commented on content/en/real_user_monitoring/browser/monitoring_page_performance.md
> +For information about the default attributes for all RUM event types, see [Data Collected][5]. For information about configuring for sampling or global context see [Advanced Configuration][6]. The fo
```suggestion
For information about the default attributes for all RUM event types, see [Data Collected][5]. For information about configuring for sampling or global context see [Advanced Configuration][6]. The following table lists Datadog-specific metrics along with performance metrics collected from the [Navigation Timing API][7] and [Paint Timing API][8]:
```

2021-01-29 19:10 UTC, cswatt commented on content/en/real_user_monitoring/browser/tracking_user_actions.md
> +**Note**:  The `trackInteractions` initialization parameter enables the collection of user clicks in your application. **Sensitive and private data** contained on your pages may be included to identi
```suggestion
**Note**: The `trackInteractions` initialization parameter enables the collection of user clicks in your application. **Sensitive and private data** contained on your pages may be included to identify the elements interacted with.
```

2021-01-29 19:10 UTC, cswatt commented on content/en/real_user_monitoring/browser/tracking_user_actions.md
> +Once an interaction is detected, all new RUM events are attached to the ongoing action until it is considered finished. The action also benefits from its parent view attributes such as browser inform
```suggestion
Once an interaction is detected, all new RUM events are attached to the ongoing action until it is considered finished. The action also benefits from its parent view attributes such as browser information, geolocation data, and [global context][2].
```

2021-01-29 19:10 UTC, cswatt commented on content/en/real_user_monitoring/browser/tracking_user_actions.md
> +Once an interaction is detected, the RUM SDK watches for network requests an DOM mutations. It is considered finished once the page has no activity for more than 100ms (activity being defined as ongo
```suggestion
Once an interaction is detected, the RUM SDK watches for network requests and DOM mutations. It is considered finished once the page has no activity for more than 100ms (activity being defined as ongoing network requests or DOM mutations).
```

2021-01-29 19:10 UTC, cswatt commented on content/en/real_user_monitoring/browser/tracking_user_actions.md
> +| `action.target.name` | string | Element that the user interacted with. Only for automatically collected actions |
```suggestion
| `action.target.name` | string | Element that the user interacted with. Only for automatically collected actions. |
```

2021-01-29 19:10 UTC, cswatt commented on content/en/real_user_monitoring/browser/tracking_user_actions.md
> +Custom user actions are user actions declared and sent manually by using the `addUserAction` API. They can send information relative to an event occurring during a user journey, for example, a custom
```suggestion
Custom user actions are user actions declared and sent manually by using the `addUserAction` API. They can send information relative to an event occurring during a user journey (for example, a custom timing or customer cart information).
```

2021-01-29 19:10 UTC, cswatt commented on content/en/real_user_monitoring/browser/tracking_user_actions.md
> +Once RUM is initialized, generate user actions when you want to monitor specific interactions on your application pages or measure custom timings with the `addUserAction(name: string, context: Contex
```suggestion
Once RUM is initialized, generate user actions when you want to monitor specific interactions on your application pages or measure custom timings with the `addUserAction(name: string, context: Context)` API call. In the following examples, the RUM SDK collects the number of items within a cart, what they are, and how much the cart is worth overall.
```

2021-01-29 20:01 UTC, cswatt approved these changes

2021-01-29 20:34 UTC, merged