Priyanshi/rum home page
DataDog/documentation pull request #9580
Opened 2021-01-25 19:31 UTC by priyanshi-gupta

### What does this PR do?

Adds context about RUM capabilities on home page

### Motivation

### Preview

https://docs-staging.datadoghq.com/priyanshi/rum_home_page/real_user_monitoring/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-01-26 08:50 UTC, hdelaby approved these changes
Great job!!! :tada: 2 minor comments:
- for some reasons the language icons look zoomed-in and pixels are visible
- we can find better links for the further reading section

2021-01-28 21:17 UTC, apigirl reviewed
just some very small updates

2021-01-28 21:17 UTC, apigirl commented on content/en/real_user_monitoring/_index.md
> +* **Analytics / Usage**: Understand who is using your application (country, device, OS…), monitor individual users journeys, and analyze how users interact with your application (most common page vis
```suggestion
* **Analytics / Usage**: Understand who is using your application (country, device, OS), monitor individual users journeys, and analyze how users interact with your application (most common page visited, clicks, interactions, feature usage…)
```

2021-01-28 21:17 UTC, apigirl commented on content/en/real_user_monitoring/_index.md
> +* **Support**: Retrieve all of the information related to one user session to troubleshoot an issue (session duration, pages visited, interactions, resources loaded, errors…)
```suggestion
* **Support**: Retrieve all of the information related to one user session to troubleshoot an issue (session duration, pages visited, interactions, resources loaded, errors)
```

2021-01-28 21:17 UTC, apigirl commented on content/en/real_user_monitoring/_index.md
> +Slice and dice user sessions by segments such as checking when latency impacts your premium customers with [customizable analytics widgets][2]. Explore, save views and create monitors on your customi
```suggestion
View user sessions in segments, such as checking when latency impacts your premium customers with [customizable analytics widgets][2]. Explore, save views, and create monitors on your customized searches.
```

2021-01-28 21:17 UTC, apigirl commented on content/en/real_user_monitoring/_index.md
> +View your [backend traces, logs, infrastructure metrics][3] to line of code impacting your application performance that correspond  to user experiences and reported issues.
```suggestion
View your [backend traces, logs, infrastructure metrics][3] to line of code impacting your application performance that correspond to user experiences and reported issues.
```

2021-01-28 21:17 UTC, apigirl commented on content/en/real_user_monitoring/_index.md
> +Get automated alerts on outliers and groups of errors, timeouts, crashes to significantly reduce your MTTR with [Error Tracking][4].
```suggestion
Get automated alerts on outliers and groups of errors, timeouts, and crashes to significantly reduce your MTTR with [Error Tracking][4].
```

2021-02-17 23:29 UTC, kayayarai requested changes
Thanks! Some edits and a broken link fix

2021-02-17 23:29 UTC, kayayarai commented on content/en/real_user_monitoring/_index.md
> +* **Support**: Retrieve all of the information related to one user session to troubleshoot an issue (session duration, pages visited, interactions, resources loaded, errors)
```suggestion
* **Performance**: Track the performance of web pages, mobile application screens, user actions, network requests, and your front-end code.
* **Error Management**: Monitor the ongoing bugs and issues and track them over time and versions.
* **Analytics / Usage**: Understand who is using your application (country, device, OS), monitor individual users journeys, and analyze how users interact with your application (most common page visited, clicks, interactions, feature usage).
* **Support**: Retrieve all of the information related to one user session to troubleshoot an issue (session duration, pages visited, interactions, resources loaded, errors).
```

2021-02-17 23:29 UTC, kayayarai commented on content/en/real_user_monitoring/_index.md
> +### Out of the Box Dashboards
```suggestion
### Out of the box dashboards
```

2021-02-17 23:29 UTC, kayayarai commented on content/en/real_user_monitoring/_index.md
> +View your [backend traces, logs, infrastructure metrics][1] to line of code impacting your application performance that correspond  to user experiences and reported issues.
```suggestion
View your [backend traces, logs, infrastructure metrics][3] down to the exact line of code impacting your application performance, corresponding to user experiences and reported issues.
```

2021-02-17 23:29 UTC, kayayarai commented on content/en/real_user_monitoring/_index.md
> +[1]: real_user_monitoring/connect_rum_and_traces
```suggestion

```

2021-02-17 23:29 UTC, kayayarai commented on content/en/real_user_monitoring/_index.md
> +[2]:/real_user_monitoring/explorer/analytics
```suggestion
[2]:/real_user_monitoring/explorer/analytics
[3]: /real_user_monitoring/connect_rum_and_traces
```

2021-02-18 00:17 UTC, apigirl approved these changes

2021-02-18 00:17 UTC, merged