Document --flare for agent jmx commands
DataDog/documentation pull request #9616
Opened 2021-01-28 07:14 UTC by ian28223

### What does this PR do?
Document `--flare` for agent jmx commands to be made available in 6/7.26.x

### Motivation
- https://github.com/DataDog/datadog-agent/pull/7230

### Preview

https://docs-staging.datadoghq.com/ian.bucad/jmx_flare/integrations/faq/troubleshooting-jmx-integrations

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-01-28 18:28 UTC, ruthnaebeck requested changes

2021-01-28 18:28 UTC, ruthnaebeck commented on content/en/integrations/faq/troubleshooting-jmx-integrations.md
> +* [Agent Flare][1]
```suggestion
* [Agent Flare][1], which includes:
```

2021-01-28 18:28 UTC, ruthnaebeck commented on content/en/integrations/faq/troubleshooting-jmx-integrations.md
> +* A copy of the YAML integration. (Included in the flare)
Indent the 3 lines above and remove `(Included in the flare)`

2021-01-28 18:28 UTC, ruthnaebeck commented on content/en/integrations/faq/troubleshooting-jmx-integrations.md
> +* [Agent Flare][1]
```suggestion
* [Agent Flare][1], which includes:
```

2021-01-28 18:28 UTC, ruthnaebeck commented on content/en/integrations/faq/troubleshooting-jmx-integrations.md
> +* A copy of the YAML integration. (Included in the flare)
Indent the 4 lines above and remove (Included in the flare)

2021-01-28 18:28 UTC, ruthnaebeck commented on content/en/integrations/faq/troubleshooting-jmx-integrations.md
> +**Note**: if you're able to see some metrics (`jvm.heap_memory`, `jvm.non_heap_memory`, etc.) it is a sign that JMXFetch is properly running. If you're targeting another application and not seeing re
```suggestion
**Note**: If you're able to see some metrics (`jvm.heap_memory`, `jvm.non_heap_memory`, etc.) it is a sign that JMXFetch is properly running. If you're targeting another application and not seeing related metrics, the likely issue is a misconfiguration in your YAML.
```

2021-01-28 18:28 UTC, ruthnaebeck commented on content/en/integrations/faq/troubleshooting-jmx-integrations.md
> +- By default theses commands run on all the configured jmx checks. If you want to use them for specific checks, specify them using the `--checks` flag :
```suggestion
- By default these commands run on all the configured JMX checks. To limit the commands to specific checks, use the `--checks` flag, for example:
```

2021-01-28 18:28 UTC, ruthnaebeck commented on content/en/integrations/faq/troubleshooting-jmx-integrations.md
> +- On 6.26.x/7.26.x, appending `--flare` writes the output of the above commands under `/var/log/datadog/jmxinfo/` which gets included in the flare.
```suggestion
- For Agent v6.26.+ / v7.26+, appending `--flare` writes the output of the above commands under `/var/log/datadog/jmxinfo/`, which is included in the flare.
```

2021-02-05 04:21 UTC, sarina-dd approved these changes

2021-02-05 04:22 UTC, merged