Lint headings in serverless
DataDog/documentation pull request #9627
Opened 2021-01-28 19:50 UTC by jtappa

### What does this PR do?
Lints headings to be sentence case on all pages in the serverless folder

### Motivation
Docs hackathon

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-01-28 20:37 UTC, ruthnaebeck requested changes

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/custom_metrics/_index.md
> +## Sending custom metrics from the Datadog Lambda Library
```suggestion
## Sending custom metrics from the Datadog Lambda library
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/enhanced_lambda_metrics/_index.md
> +## Enable enhanced lambda metrics
```suggestion
## Enable enhanced Lambda metrics
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/nodejs.md
> +## Triage your lambda errors in the log explorer
```suggestion
## Triage your Lambda errors in the log explorer
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/nodejs.md
> +Visit the Datadog Serverless view to view all of the lambda functions. Navigate to a specific function to see the logs being emitted from the function. Then navigate to the log explorer to learn more
```suggestion
Visit the Datadog Serverless view to view all of the Lambda functions. Navigate to a specific function to see the logs being emitted from the function. Then navigate to the log explorer to learn more about the log.
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/nodejs.md
> +## Root cause analysis using traces, metrics and logs
```suggestion
## Root cause analysis using traces, metrics, and logs
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +## Graph lambda cold starts
```suggestion
## Graph Lambda cold starts
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +### Ingest lambda metrics
```suggestion
### Ingest Lambda metrics
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +You need to enable the Amazon Web Services integration to begin collecting CloudWatch metrics from lambda functions. To do this, [follow the steps on the Amazon Web Services documentation][1].
```suggestion
You need to enable the Amazon Web Services integration to begin collecting CloudWatch metrics from Lambda functions. To do this, [follow the steps on the Amazon Web Services documentation][1].
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +- In the AWS integration tile, lambda is checked under metric collection.
```suggestion
- In the AWS integration tile, Lambda is checked under metric collection.  
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +At this step, Datadog automatically starts collecting key lambda metrics such as invocations, duration, and errors. You can visualize them in the [out-of-the-box lambda dashboard][2], which you can f
```suggestion
At this step, Datadog automatically starts collecting key Lambda metrics such as invocations, duration, and errors. You can visualize them in the [out-of-the-box Lambda dashboard][2], which you can find under Dashboards.
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +### Graph lambda cold starts with enhanced metrics
```suggestion
### Graph Lambda cold starts with enhanced metrics
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +### Graph lambda cold starts
```suggestion
### Graph Lambda cold starts
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +## Navigate lambda error logs
```suggestion
## Navigate Lambda error logs
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +### Enable lambda log ingestion
```suggestion
### Enable Lambda log ingestion
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/guide/python.md
> +### Enable lambda distributed tracing
```suggestion
### Enable Lambda distributed tracing
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/installation/_index.md
> +1. Install the [AWS integration][1]. This allows Datadog to ingest Lambda metrics from AWS CloudWatch.
```suggestion
### Install the AWS integration

Install the [AWS integration][1]. This allows Datadog to ingest Lambda metrics from AWS CloudWatch. 
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/installation/_index.md
> +2. Install the [Datadog Forwarder Lambda function][2], which is required to ingest AWS Lambda traces, enhanced metrics, custom metrics, and logs.
```suggestion
### Install the Datadog Forwarder

Install the [Datadog Forwarder Lambda function][2], which is required to ingest AWS Lambda traces, enhanced metrics, custom metrics, and logs. 
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/installation/_index.md
> +   **Note**: Skip this step if you already have the Forwarder function installed as part of the [AWS integration][1] CloudFormation Stack.
```suggestion

**Note**: Skip this step if you already have the Forwarder function installed as part of the [AWS integration][1] CloudFormation Stack.
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/installation/_index.md
> +3. Select the Lambda runtime below for instructions to instrument your serverless application.
```suggestion
### Instrument your application

3. Select the Lambda runtime below for instructions to instrument your serverless application.
```

2021-01-28 20:37 UTC, ruthnaebeck commented on content/en/serverless/installation/ruby.md
> +#### Using the gem
```suggestion
#### Using the Gem
```

2021-02-03 18:55 UTC, kayayarai approved these changes

2021-02-03 18:55 UTC, merged