Refactor Python profiling installation and configuration process
DataDog/documentation pull request #9651
Opened 2021-02-01 12:43 UTC by jd

### What does this PR do?

This refactor the Python installation guide to be clearer and more concise.

### Motivation

It's hard for come users to install the Python profiler with current documentation.

### Preview
https://docs-staging.datadoghq.com/jd/jd/python-profiling-improvement/en/tracing/profiler

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-02-01 13:46 UTC, jd commented
It seems the language tabs are not working in the preview. Is this a bug in the preview or the PR breaking them in a way I don't understand?

2021-02-01 17:18 UTC, apigirl commented
> It seems the language tabs are not working in the preview. Is this a bug in the preview or the PR breaking them in a way I don't understand?

It looks like you're missing the closing tags. I'll add a suggestion to correct

2021-02-01 17:28 UTC, apigirl commented
> It seems the language tabs are not working in the preview. Is this a bug in the preview or the PR breaking them in a way I don't understand?

So we have a known issue that the code tabs don't support headers yet (so ## and ###). We're working on a fix. For now the path of least resistance would be to update the headers to be bold instead.

2021-02-02 11:47 UTC, jd commented
@davidejones why/what did you force-push this branch?

2021-02-02 22:12 UTC, cswatt requested changes
grammar changes

2021-02-02 22:12 UTC, cswatt commented on content/en/tracing/profiler/getting_started.md
> +The Datadog Profiler requires Python 2.7+ and agent to version [7.20.2][1]+ or
```suggestion
The Datadog Profiler requires Python 2.7+ and Agent version [7.20.2][1]+ or
```

2021-02-02 22:12 UTC, cswatt commented on content/en/tracing/profiler/getting_started.md
> +Those profiling features are available depending on your Python version:
```suggestion
The following profiling features are available depending on your Python version:
```

2021-02-02 22:12 UTC, cswatt commented on content/en/tracing/profiler/getting_started.md
> +|      Feature         | Supported Python Versions          |
```suggestion
|      Feature         | Supported Python versions          |
```

2021-02-02 22:12 UTC, cswatt commented on content/en/tracing/profiler/getting_started.md
> +Install `ddtrace` which provides both tracing and profiling functionalities:
```suggestion
Install `ddtrace`, which provides both tracing and profiling functionalities:
```

2021-02-02 22:12 UTC, cswatt commented on content/en/tracing/profiler/getting_started.md
> +**Note**: Profiling requires the `ddtrace` library versions 0.40+.
```suggestion
**Note**: Profiling requires the `ddtrace` library version 0.40+.
```

2021-02-02 22:12 UTC, cswatt commented on content/en/tracing/profiler/getting_started.md
> +To automatically profile your code, set `DD_PROFILING_ENABLED` environment
```suggestion
To automatically profile your code, set the `DD_PROFILING_ENABLED` environment
```

2021-02-02 22:12 UTC, cswatt commented on content/en/tracing/profiler/getting_started.md
> +It is strongly recommended to add tags like `service` or `version` as it
```suggestion
It is strongly recommended that you add tags like `service` or `version`, as they
```

2021-02-08 18:29 UTC, dbenamydd reviewed
This is much cleaner structure and generally better!

2021-02-08 18:29 UTC, dbenamydd commented on content/en/tracing/profiler/getting_started.md
> +prof = Profiler()
And we could do the equivalent here, with comments showing what env var is used if not specified, like
```
prof = Profiler(
    env="prod",  # if not specified, uses env var DD_ENV
...
```

2021-02-08 18:29 UTC, dbenamydd commented on content/en/tracing/profiler/getting_started.md
> +end of your program, not to selectively profile parts of your program.
If we do the above, we can probably ditch this. The less stuff people have to think about when onboarding, the better!

2021-02-08 18:29 UTC, dbenamydd commented on content/en/tracing/profiler/getting_started.md
> +| `DD_TAGS`                                        | String        | Tags to apply to an uploaded profile. Must be a list of `<key>:<value>` separated by commas such as: `layer:api,team:intake`.   |
Work another col for the programmatic equivalent of each?

2021-02-09 20:15 UTC, dbenamydd approved these changes
This is awesome!

2021-02-09 20:15 UTC, dbenamydd commented on content/en/tracing/profiler/getting_started.md
> +It is strongly recommended that you add tags like `service` or `version`, as they
I wonder if folks will think they need to do something in addition to the env vars above. Maybe something like

> In addition to the env, service, and version shown above, you can add other tags like `DD_TAGS=canary:true,shard:3` which will provide the ability to slice and dice...

Or maybe we just mention DD_TAGS and leave details for below. I'm not sure, just throwing something out to make it concrete. Non-blocking.

2021-03-01 14:03 UTC, jd commented
@cswatt @DataDog/corpweb what's blocking this from being merged?

2021-03-08 13:52 UTC, GaurabAryal approved these changes

2021-03-08 15:17 UTC, cswatt approved these changes

2021-03-08 15:27 UTC, merged