no_proxy_nonexact_match docs for agent 7.26
DataDog/documentation pull request #9656
Opened 2021-02-01 16:35 UTC by gh123man

### What does this PR do?
Add documentation for new `no_proxy_nonexact_match` that will be available in agent `7.26.0`. 
We should hold this PR until 7.26.0 is released

### Motivation
Document new feature. 

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-02-16 17:51 UTC, cswatt requested changes
capitalize Agent, everything else looks good

2021-02-16 17:51 UTC, cswatt commented on content/en/agent/proxy.md
> +`NO_PROXY` must match endpoints exactly for agent HTTP(S) requests. Enable `no_proxy_nonexact_match` to allow the agent to match `NO_PROXY` values with the same rules (above) used for integrations.
```suggestion
`NO_PROXY` must match endpoints exactly for Agent HTTP(S) requests. Enable `no_proxy_nonexact_match` to allow the Agent to match `NO_PROXY` values with the same rules (above) used for integrations. 
```

2021-02-16 18:09 UTC, cswatt approved these changes

2021-03-02 17:50 UTC, gh123man commented
This can now be merged since 7.26 is live

2021-03-03 20:13 UTC, merged