Add cherrypy to compatibility table, update ja/fr tables
DataDog/documentation pull request #9678
Opened 2021-02-02 22:28 UTC by Kyle-Verhoog

### What does this PR do?

Adds cherrypy to the compatibility table for the python client. Also updates the web framework table for the fr/ja docs.

**Note: this PR is on hold until ddtrace version 0.47 is released.**

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-04-07 18:21 UTC, jtappa commented
Hi @Kyle-Verhoog! You only need to update the english files, our translation pipelines take care of the rest for japanese and french! Can you please update to just english file and rebase so there's no conflicts?

Thanks!

2021-04-07 21:11 UTC, jtappa requested changes
Just needs english only files updated and a rebase

2021-04-08 03:32 UTC, Kyle-Verhoog commented
:+1: should be good to go now @jtappa 🙂

2021-04-08 16:23 UTC, jtappa requested changes

2021-04-08 16:23 UTC, jtappa commented on content/en/tracing/setup_overview/compatibility_requirements/python.md
> +| [CherryPy][6]            | >= 11.2.0         | https://ddtrace.readthedocs.io/en/stable/integrations.html#cherrypy|
Looks like link 6 at the bottom of the file is still Django, which means all the links are now off by one.

2021-04-23 21:58 UTC, apigirl approved these changes

2021-04-23 21:59 UTC, merged