APM > Logs and Traces -> .NET automatic instrumentation docs update
DataDog/documentation pull request #9707
Opened 2021-02-05 02:45 UTC by zacharycmontoya

### What does this PR do?
Revise NLog support for .NET automatic logs injection and show setup for applications using NLog versions below 4.5

### Motivation
Customer using a version of NLog below 4.5

### Preview
https://docs-staging.datadoghq.com/zach.montoya/apm-dotnet-logs-injection-setup/tracing/connect_logs_and_traces/dotnet/?tab=nlog

### Additional Notes
N/A

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-02-05 20:19 UTC, sarina-dd requested changes

2021-02-05 20:19 UTC, sarina-dd commented on content/en/tracing/connect_logs_and_traces/dotnet.md
> +We support [Serilog][4], [NLog][5] (version 4.0+), or [log4net][6]. Automatic injection only displays in the application logs after enabling `LogContext` enrichment in your `Serilog` logger or `Mappe
```suggestion
The .NET Tracer supports [Serilog][4], [NLog][5] (version 4.0+), or [log4net][6]. Automatic injection only displays in the application logs after enabling `LogContext` enrichment in your `Serilog` logger or `Mapped Diagnostics Context` in your `NLog` or `log4net` logger.
```

2021-02-09 19:15 UTC, lucaspimentel approved these changes

2021-02-12 20:22 UTC, sarina-dd approved these changes

2021-02-12 20:54 UTC, merged