[agent/logs] Additional multiline regexp example
DataDog/documentation pull request #9739
Opened 2021-02-10 13:27 UTC by prognant

### What does this PR do?
Add an additional example to the multiline regex sample table.

### Motivation
Emphase that regex matching is only from the beginning of a log line, no matter (like json formatting) what.

### Preview

https://docs-staging.datadoghq.com/prognant/agent-multiline-regex-additional-example/agent/logs/advanced_log_collection/

### Additional Notes
N/A
---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-02-10 15:16 UTC, kayayarai requested changes
Let's bring even more attention to it, since it's important.

2021-02-10 15:16 UTC, kayayarai commented on content/en/agent/logs/advanced_log_collection.md
> +**Very important note**: Regex patterns for multi-line logs must start at the **beginning** of a log. Patterns cannot be matched mid-line. *A never matching pattern may cause log line losses*.
```suggestion
<div class="alert alert-warning"><strong>Important!</strong> Regex patterns for multi-line logs must start at the <em>beginning</em> of a log. Patterns cannot be matched mid-line. <em>A never matching pattern may cause log line losses.</em></div>
```

2021-02-10 19:38 UTC, olivielpeau approved these changes

2021-02-12 15:06 UTC, kayayarai approved these changes

2021-02-12 15:06 UTC, merged