api: add instructions to run examples
DataDog/documentation pull request #9866
Opened 2021-02-24 15:58 UTC by jirikuncar

### What does this PR do?

Adds instructions how to run API code examples.

### Motivation

- `DD_SITE` needs to be exported
- command and file name might not be obvious

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-02-24 21:21 UTC, kayayarai requested changes
Minor edit

2021-02-24 21:21 UTC, kayayarai commented on layouts/partials/api/code-example.html
> +            <p>Save example to <code>{{ $lang.example_file }}</code> and run following commands.</p>
```suggestion
            <p>Save the example to <code>{{ $lang.example_file }}</code> and run following commands:</p>
```

2021-02-25 09:11 UTC, davidejones approved these changes
nice! looks good here

2021-02-26 15:02 UTC, kayayarai approved these changes
🎉 Looks great!

2021-02-26 22:30 UTC, merged