[DOCS-1700] add new prometheus metrics collection method
DataDog/documentation pull request #9870
Opened 2021-02-24 22:34 UTC by cswatt

### What does this PR do?
Adds another method of collecting metrics (with native Prometheus annotations)

### Motivation
PM request

### Preview

https://docs-staging.datadoghq.com/cswatt/k8s-prom/agent/kubernetes

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

2021-02-24 22:37 UTC, cohenyair approved these changes

2021-02-24 22:38 UTC, cswatt commented
Hold for release of agent 7.26

2021-03-03 18:35 UTC, ahmed-mez approved these changes
Thank you! Agent 7.26 is released and the helm chart is updated as well. This can be merged 🎉

2021-03-04 19:22 UTC, ruthnaebeck requested changes

2021-03-04 19:22 UTC, ruthnaebeck commented on content/en/agent/kubernetes/prometheus.md
> +- Datadog Agent 7 or 6.26+ (for Pod checks)
```suggestion
- Datadog Agent v7 or v6.26+ (for Pod checks)
```

2021-03-04 19:22 UTC, ruthnaebeck commented on content/en/agent/kubernetes/prometheus.md
> +- Datadog Cluster Agent 1.11+ (for service and endpoint checks)
```suggestion
- Datadog Cluster Agent v1.11+ (for service and endpoint checks)
```

2021-03-08 15:31 UTC, ruthnaebeck approved these changes

2021-03-08 15:31 UTC, merged